logstash-core/lib/logstash/modules/settings_merger.rb, logstash-core/lib/logstash/util/modules_setting_array.rb, logstash-core/spec/logstash/modules/settings_merger_spec.rb, logstash-core/spec/logstash/settings/modules_spec.rb, logstash-core/src/main/java/org/logstash/util/ModulesSettingArray.java
Move the implementation of the class `ModulesSettingArray` from Ruby to Java, while keeping the tests in Ruby to proove the Ruby compatibility of the changes.
This PR is a chore that later let us move also all the hierarchy of `Setting` subclasses to Java. This PR leverages the integration that JRuby offers to use Java code, without requiring special JRuby classes.
Since the PR changes module related stuff, the test consists of running Logstash using a module.
- start a local Kibana and Elasticsearch
<details>
<summary>Docker compose …
=> Moved ModulesSettingArray from Ruby to Java.

docs/static/ls-to-cloud.asciidoc
Start making use of the term 'Elastic Cloud' as this is the term being used to refer to the service we provide.
This PR changes uses the term of 'Elastic Cloud' instead of solely referring to ESS as Elasticsearch Service, as it is the term that's being used to promote the service.
Allows the user to related 'Elastic Cloud' term used widely to relate to the Elasticsearch Service.
=> Change text to use Elastic Cloud

logstash-core/lib/logstash/pipeline.rb
Correctly outputs the config reload interval as an integer number of nanoseconds.
This fixes a regression introduced in https://github.com/elastic/logstash/pull/11803, in which the _internal representation_ of the pipeline's reload interval was changed to a full-fledged object that carries time units. The PR correctly externalized this representation back to nanoseconds in the Java Execution Engine, but failed to do so in the legacy Ruby Execution engine.
In turn, this eliminates a warning encountered when running Logstash under REE with `--java-execution=false`:
~~~
[2020-12-02T17:26:12,997][WARN ][org.logstash.instrument.metrics.gauge.LazyDelegatingGauge][empty] A gauge metric of an unknown type (org.jruby.gen.RubyObject3) has been created for key: config_reload_interval. This may …
=> REE: gauge reload interval

docker/templates/Dockerfile.j2, qa/docker/spec/ubi8/image_spec.rb
these labels are required for redhat openshift certification.
These commit reintroduces the labels for the ubi8 image only, and adds
acceptance tests to ensure these labels are correct and not inherited
=> Add UBI8 image specific labels back to the docker image

Gemfile.jruby-2.5.lock.release, logstash-core/lib/logstash/pipeline.rb
Revert "Update (patch) gem versions for 7.10.1 again (#12488)"
This reverts commit a2c45e4c6f70c6b192b4eab7f81288029fde6c45.
Revert "REE: output reload interval as nanos instead of object"
This reverts commit 8ad108df2063ffb26f048d772f6ede7ea9a6badb.
=> Revert unnecessary commits for `7.10 BC3`

docker/templates/Dockerfile.j2, qa/docker/spec/ubi8/image_spec.rb
Clean backport of #12498
these labels are required for redhat openshift certification.
These commit reintroduces the labels for the ubi8 image only, and adds
acceptance tests to ensure these labels are correct and not inherited
=> [710_backport] Add UBI8 image specific labels back to the docker image

docker/templates/Dockerfile.j2, qa/docker/spec/ubi8/image_spec.rb
Clean backport of #12498
these labels are required for redhat openshift certification.
These commit reintroduces the labels for the ubi8 image only, and adds
acceptance tests to ensure these labels are correct and not inherited
=> [7x_backport] Add UBI8 image specific labels back to the docker image

docs/static/releasenotes.asciidoc
Relevant Commits:
- 2cf15a163 - remove evaluation dir from JRuby bundled did_you_mean gem (https://github.com/elastic/logstash/pull/12460) :white_check_mark: 
- 5500235cb - [710_backport] Fix docker image metadata (#12451) :white_check_mark: 
- db4e11788 - delete pipeline in registry (#12414) :white_check_mark: 
- da7f5f5f6 - hash function of pipeline config  with metadata (#12389) :white_check_mark: 
- 36b8b8be3 - [Backport] Doc: Add bundled JDK info (#12418) :grey_question:
=> Update release notes for 7.10.1

build.gradle
Fix error due to missing variable when listing gradle tasks and no architecture is externally specified with -Pos_arch=
Sets a default value for cpu architecture type in `build.gradle` when no value is defined on command line through the `-Pos_arch` parameter.
Before this fix, importing the project in IlliJIDEA or running  `gradle tasks` reports an error, in particular for command line:
```
* Where:
Build file '/tmp/logstash/build.gradle' line: 599
* What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':downloadJdk'.
> Could not set unknown property 'cpu_arch' for root project 'logstash' of type org.gradle.api.Project.
```
This issues impacted the developers opening the project into IntelliJIDEA and the ones that used Gradle management tasks, like `gradle tasks` …
=> Fix error due to missing variable when listing gradle tasks

build.gradle
Fix error due to missing variable when listing tasks and no architecture is externally specified with -Pos_arch=
Backport of #12513 to `7.x`
(cherry picked from commit 7144a3f7cf9628a2ce397b29cbf6f65dcbf3e334)
=> Fix error due to missing variable when listing tasks and no cpu architecture provided

logstash-core/lib/logstash/pipeline.rb
fixes a warning about an unsupported gauge type, matches the behaviour
on JEE.
Reintroduces reverted commit 8ad108df2063ffb26f048d772f6ede7ea9a6badb
=> REE: output reload interval as nanos instead of object

docker/data/logstash/env2yaml/env2yaml.go, docs/static/java-codec.asciidoc, docs/static/java-filter.asciidoc, docs/static/java-input.asciidoc, docs/static/java-output.asciidoc, docs/static/running-logstash-command-line.asciidoc, docs/static/settings-file.asciidoc, logstash-core/lib/logstash/environment.rb, logstash-core/lib/logstash/runner.rb, logstash-core/lib/logstash/settings.rb, logstash-core/locales/en.yml
Fixed: #11236
This PR remove config `pipeline.java_execution`. Every pipeline is defaulted to java execution
- remove config
- remove doc
=> Remove ruby execution engine config

docs/static/configuration.asciidoc, logstash-core/lib/logstash/config/mixin.rb, logstash-core/spec/logstash/config/mixin_spec.rb, logstash-core/src/main/java/org/logstash/FieldReference.java
Provide plugins a way of validating that an input is a literal field-reference.
This is useful for input plugins that implement a `target` or other
non-interpolated directive, and allows these plugins to reject invalid
configuration before start-up instead of at run-time.
~~~
config "target", :validate => :field_reference
~~~
Plugins should not use this named validator directly, as doing so would cause
validation to fail with "Unknown validator" when the plugin is run on older
releases of Logstash. Instead, plugins should use a to-be-released
support adapter that provides back-ports when necessary.
When a plugin can reject invalid configuration at startup instead of producing errors at runtime, users are less likely to get into situations that cannot be undone. A plugin that refuses to …
=> plugin: adds `:validate => :field_reference`

docs/static/configuration.asciidoc, logstash-core/lib/logstash/config/mixin.rb, logstash-core/spec/logstash/config/mixin_spec.rb, logstash-core/src/main/java/org/logstash/FieldReference.java
Clean back-port of https://github.com/elastic/logstash/pull/12459 for 7.x to trigger CI.
Provide plugins a way of validating that an input is a literal field-reference.
This is useful for input plugins that implement a `target` or other
non-interpolated directive, and allows these plugins to reject invalid
configuration before start-up instead of at run-time.
~~~
config "target", :validate => :field_reference
~~~
Plugins should not use this named validator directly, as doing so would cause
validation to fail with "Unknown validator" when the plugin is run on older
releases of Logstash. Instead, plugins should use a to-be-released
support adapter that provides back-ports when necessary.
When a plugin can reject invalid configuration at startup instead of producing errors at runtime, users …
=> plugin: adds `:validate => :field_reference` (7.x backport)

Gemfile.jruby-2.5.lock.release
Provides a dependencies and plugins lock in anticipation for the 7.11.0 release, as part of our standard release cycle.
Because the 7.x branch does not _have_ a lock file, it is easiest to view the diff commit-by commit:
- first, we copy the dependencies verbatim from the 7.10.1 release
- then, we update minor-level changes in plugins
=> Version bumps for 7.11

build.gradle
To silence missing javadoc the build.gradle task used the flag `-Xwerror '-quiet'`, with JDK 15 the javadoc tool the undocumented `-Xwerror` flag has become official as `-Werror` and the `-quiet` is not anymore effective.
This PR enables javadoc lint only for files that contains javadoc comments, avoid warning for missing javadoc comments on everything else using `-Xdoclint:all,-missing`.
The final user is not impacted, but the without this the developers can't run the build on JDK15
Run  `./gradlew :logstash-core:javadoc`  and verify that on it behaves in same way on JDK 14 and JDK 15
- relates to #12243
A developer can be able to build with JDK 15 without errors like in JDK 14
This simply make `./gradlew :logstash-core:javadoc` task to work also on JDK 15.
=> Silence missing javadocs in JDK 15

versions.yml
backport of #12385 to `7.10`
commit 00a2bc13b0b77d0754e3dbfde30b9715d36ab01f
=> Update jrjackson and databind versions (#12385)

build.gradle
backport PR of #12523 to `7.x`
(cherry picked from commit d176e608bdd20a3221bdbb8b3fc84fc3f1085229)
=> Enable javadoc lint only for files that contains javadoc comments

NOTICE.TXT, tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/racc-NOTICE.txt
This commit updates the license information for the license dependency report.
Specifically, this adds a notice for `racc`, a different version of which is now
pulled in by nokogiri from the version included with jruby.
=> Update license dependency information

config/jvm.options, logstash-core/src/main/java/org/logstash/Logstash.java, qa/integration/fixtures/fatal_error_spec.yml, qa/integration/specs/fatal_error_spec.rb
Currently, LS does not respect fatal errors such as `java.lang.OutOfMemoryError` and continues executing.
This is dangerous since JVM errors are a legitimate reason to halt the process and not continue processing.
Additionally:
- make sure we log the full stack-trace on fatal errors
- halt the JVM wout executing finalizers/hook (:scissors: on how ES [handles uncaught exceptions](https://github.com/elastic/elasticsearch/blob/v7.10.0/server/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java#L35-L59))
- also, we should now be aware of a potentially unexpectedly dying thread
Sample set of logs on various failures: https://gist.github.com/kares/84d3dcfbaceef130781e457066342a06 
(there's room for improvement but at least we're not missing anything)
resolves …
=>  Fix: make sure LS exits when running into fatal errors

logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV2.java
Prevents PQ corruption that can occur when Logstash crashes
before events have been written to a newly-created page file.
When the PQ creates a new page and allocates a memory-mapped buffer, the
underlying file is zero'd out to full page capacity and the version byte is
written to the buffer, but (emphashis mine):
> Changes made to the resulting [`MemoryMappedBuffer`] will **_eventually_** be propagated to the file
> -- [`FileChannel#map` with `MapMode.READ_WRITE`](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileChannel.html#map-java.nio.channels.FileChannel.MapMode-long-long-)
When writing a batch of events to the queue, we force the buffer to synchronize,
but if Logstash crashes or is killed before any elements have been pushed into
the queue page, we have no guarantees …
=> pq: eliminate corruption by forcing version byte to be persisted

logstash-core/src/main/java/org/logstash/Logstash.java, qa/integration/fixtures/fatal_error_spec.yml, qa/integration/specs/fatal_error_spec.rb
Currently, LS does not respect fatal errors such as java.lang.OutOfMemoryError and continues executing.
This is dangerous since JVM errors are a legitimate reason to halt the process and not continue processing.
Additionally:
-   make sure we log the full stack-trace on fatal errors
-   halt the JVM wout executing finalizers/hook (scissors on how ES handles uncaught exceptions)
-   also, we should now be aware of a potentially unexpectedly dying thread
Clean back-port of #12470
=>  Fix: make sure LS exits when running into fatal errors (#12470)

bin/logstash, bin/logstash.bat, bin/logstash.lib.sh, config/jvm.options, docs/static/config-details.asciidoc, logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java, logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
reviewable after rebase on top of #12512
Introduces the conditional behavior in `jvm.options` to define some options as usable with only certain versions of JVM. This feature is based on what Elasticsearch already does https://www.elastic.co/guide/en/elasticsearch/reference/master/jvm-options.html
This feature permit the user to define different options for different JVM versions, for example in we can configure CMS GC only for Java in versions range 8..14 and avoid it in JDK 15. This is available for any option in `jvm.options` file.
Use a jdk 15 for example, using sdkman
```
sdk install java 15.0.1.hs-adpt
sdk use java java 15.0.1.hs-adpt
```
then run `./gradlew build`, the build must be green
- 
A user want to enable certain JVM options based on JVM version.
=> Removed CMS GC flags to run tests successfully on JDK15

bin/logstash.bat
Fix launching logstash with bundled JDK if folder has spaces.
Currently starting logstash on windows without an external JDK causes logstash to crash.
1. On windows create a folder with spaces like "c:\this folder has spaces". 
2. Unzip logstash inside that folder.
3. Enter the logstash folder. e.g. "c:\this folder has spaces\logstash-7.10.2"
3. Run a few test commands:
a. `bin\logstash.bat -e ""`
b. `bin\logstash.bat -V`
NOTE TO REVIEWER: as we don't have acceptance tests dedicated to windows, I ask that you manually test this on windows using folders with and without spaces, and any other scenario you foresee where this could fail.
Fixes #6426
```
C:\folder with spaces\logstash>bin\logstash.bat -V
"Using bundled JDK: ""
The system cannot find the file C:\folder.
logstash Version not …
```
=> [windows] fix launch when folder contains spaces

bin/logstash.bat
Backport PR #12585 to 7.11 branch. Original message: 
Fix launching logstash with bundled JDK if folder has spaces.
Currently starting logstash on windows without an external JDK causes logstash to crash.
1. On windows create a folder with spaces like "c:\this folder has spaces". 
2. Unzip logstash inside that folder.
3. Enter the logstash folder. e.g. "c:\this folder has spaces\logstash-7.10.2"
3. Run a few test commands:
a. `bin\logstash.bat -e ""`
b. `bin\logstash.bat -V`
NOTE TO REVIEWER: as we don't have acceptance tests dedicated to windows, I ask that you manually test this on windows using folders with and without spaces, and any other scenario you foresee where this could fail.
Fixes #6426
```
C:\folder with spaces\logstash>bin\logstash.bat -V
"Using bundled JDK: ""
The system …
```
=> Backport PR #12585 to 7.11: [windows] fix launch when folder contains spaces

bin/logstash.bat
Backport PR #12585 to 7.x branch. Original message: 
Fix launching logstash with bundled JDK if folder has spaces.
Currently starting logstash on windows without an external JDK causes logstash to crash.
1. On windows create a folder with spaces like "c:\this folder has spaces". 
2. Unzip logstash inside that folder.
3. Enter the logstash folder. e.g. "c:\this folder has spaces\logstash-7.10.2"
3. Run a few test commands:
a. `bin\logstash.bat -e ""`
b. `bin\logstash.bat -V`
NOTE TO REVIEWER: as we don't have acceptance tests dedicated to windows, I ask that you manually test this on windows using folders with and without spaces, and any other scenario you foresee where this could fail.
Fixes #6426
```
C:\folder with spaces\logstash>bin\logstash.bat -V
"Using bundled JDK: ""
The system …
```
=> Backport PR #12585 to 7.x: [windows] fix launch when folder contains spaces

versions.yml
Recurrent bump of jrjackson and databind to ensure latest Logstash uses the latest patch releases.
=> bump jrjackson to 0.4.14 and jackson-databind to 2.9.10.8

versions.yml
Backport PR #12603 to 7.11 branch. Original message: 
Recurrent bump of jrjackson and databind to ensure latest Logstash uses the latest patch releases.
=> Backport PR #12603 to 7.11: bump jrjackson to 0.4.14 and jackson-databind to 2.9.10.8

versions.yml
Backport PR #12603 to 7.x branch. Original message: 
Recurrent bump of jrjackson and databind to ensure latest Logstash uses the latest patch releases.
=> Backport PR #12603 to 7.x: bump jrjackson to 0.4.14 and jackson-databind to 2.9.10.8

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent/converge_spec.rb
Due to a change in #11803, the sleep interval waiting for converge to
occur in this spec was effectively set to 0, as the sleep method was
using `to_seconds` on a `config.reload.interval` value set to `10ms` in
the spec. This change uses the `to_nanos` method to keep the functionality
as it was prior to this change.
=> Fix sub second `config.reload.interval`

.ci/matrix-runtime-javas.yml
Update JDK selector to run CI tasks also on JDK15
With this PR Logstash is tested to run on Open JDK 15
- Relates #12512
- Relates #12530
- Relates https://github.com/elastic/infra/pull/25638
- Relates to meta issue #12243
=> Update CI to run on OpenJDK15

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent_spec.rb
This PR allows the agent to converge state with predefined pipeline actions instead of fetching the full set of pipelines from elasticsearch and compute the pipeline actions internally. This opens a way for plugins to trigger pipeline reload. A usage is [logstash-filter-geoip](https://github.com/logstash-plugins/logstash-filter-geoip/pull/172/commits/badfc81d9c289c44c9ad817e3e8261e9ea6afbf7#diff-5421cf35b684cca803ff336c23f52918df0809819ae2bd6d36a4a4ec8250ddf1R129) which needs to shut down its own pipeline in certain conditions.
Related: https://github.com/logstash-plugins/logstash-filter-geoip/pull/172
Meta: #12560
=> enable converging state with predefined pipeline actions

qa/integration/services/logstash_service.rb, qa/vagrant/command.rb, tools/logstash-docgen/lib/logstash/docgen/github_generator.rb, tools/paquet/spec/integration/paquet_spec.rb
> 13:41:15     [DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /opt/logstash/qa/integration/services/logstash_service.rb:248)
Replace instances of `with_clean_env` with `with_unbundled_env`
=> replace with_clean_env with with_unbundled_env

qa/integration/services/kafka_setup.sh
Bump testing of kafka integration to 2.7.0 and also change location of kafka artifacts as berkeley mirror seems to be down.
Test failure https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-1/469/consoleFull
```
17:35:18 + echo 'Downloading Kafka version 2.4.1'
17:35:18 + curl -s -o /opt/logstash/qa/integration/services/installed/kafka.tgz https://mirrors.ocf.berkeley.edu/apache/kafka/2.4.1/kafka_2.11-2.4.1.tgz
17:35:18       can ingest 37 apache log lines from Kafka broker (FAILED - 1)
17:35:18 
17:35:18     CLI >
17:35:18 + mkdir /opt/logstash/qa/integration/services/installed/kafka
17:35:18 + tar xzf /opt/logstash/qa/integration/services/installed/kafka.tgz -C /opt/logstash/qa/integration/services/installed/kafka --strip-components 1
17:35:18 
17:35:18 gzip: …
```
=> fix url for kafka and bump to 2.7.0

qa/integration/services/logstash_service.rb, qa/vagrant/command.rb, tools/logstash-docgen/lib/logstash/docgen/github_generator.rb, tools/paquet/spec/integration/paquet_spec.rb
Backport PR #12615 to 7.x branch. Original message: 
> 13:41:15     [DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /opt/logstash/qa/integration/services/logstash_service.rb:248)
Replace instances of `with_clean_env` with `with_unbundled_env`
=> Backport PR #12615 to 7.x: replace with_clean_env with with_unbundled_env

qa/integration/services/kafka_setup.sh
Backport PR #12617 to 7.11 branch. Original message: 
Bump testing of kafka integration to 2.7.0 and also change location of kafka artifacts as berkeley mirror seems to be down.
Test failure https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-1/469/consoleFull
```
17:35:18 + echo 'Downloading Kafka version 2.4.1'
17:35:18 + curl -s -o /opt/logstash/qa/integration/services/installed/kafka.tgz https://mirrors.ocf.berkeley.edu/apache/kafka/2.4.1/kafka_2.11-2.4.1.tgz
17:35:18       can ingest 37 apache log lines from Kafka broker (FAILED - 1)
17:35:18 
17:35:18     CLI >
17:35:18 + mkdir /opt/logstash/qa/integration/services/installed/kafka
17:35:18 + tar xzf /opt/logstash/qa/integration/services/installed/kafka.tgz -C …
```
=> Backport PR #12617 to 7.11: fix url for kafka and bump to 2.7.0

qa/integration/services/kafka_setup.sh
Backport PR #12617 to 7.x branch. Original message: 
Bump testing of kafka integration to 2.7.0 and also change location of kafka artifacts as berkeley mirror seems to be down.
Test failure https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-1/469/consoleFull
```
17:35:18 + echo 'Downloading Kafka version 2.4.1'
17:35:18 + curl -s -o /opt/logstash/qa/integration/services/installed/kafka.tgz https://mirrors.ocf.berkeley.edu/apache/kafka/2.4.1/kafka_2.11-2.4.1.tgz
17:35:18       can ingest 37 apache log lines from Kafka broker (FAILED - 1)
17:35:18 
17:35:18     CLI >
17:35:18 + mkdir /opt/logstash/qa/integration/services/installed/kafka
17:35:18 + tar xzf /opt/logstash/qa/integration/services/installed/kafka.tgz -C …
```
=> Backport PR #12617 to 7.x: fix url for kafka and bump to 2.7.0

lib/pluginmanager/utils/http_client.rb, spec/unit/plugin_manager/utils/http_client_spec.rb
The plugin manager's http client was using an obsolete way to read headers, causing the plugin test to fail.
This PR changes to the right api: [`#[]`](https://www.rubydoc.info/stdlib/net/Net/HTTPHeader#[]-instance_method).
=> use correct headers api for redirects in plugin manager http client

lib/pluginmanager/utils/http_client.rb, spec/unit/plugin_manager/utils/http_client_spec.rb
Backport PR #12626 to 7.x branch. Original message: 
The plugin manager's http client was using an obsolete way to read headers, causing the plugin test to fail.
This PR changes to the right api: [`#[]`](https://www.rubydoc.info/stdlib/net/Net/HTTPHeader#[]-instance_method).
=> Backport PR #12626 to 7.x: use correct headers api for redirects in plugin manager http client

docs/static/jvm.asciidoc, logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent_spec.rb
**PREVIEW:** https://logstash_12614.docs-preview.app.elstc.co/guide/en/logstash/master/getting-started-with-logstash.html#ls-jvm
Updates documentation of getting started explaining what to do when an existing LS installation is upgraded to 7.12+ and runs on JDK15+
Describe how to change existing `log4j2.properties` and `jvm.options` to run with JDK15 after an update to Logstash `7.12+`
=> [Doc] added instruction on how to update LS to 7.12+ running on JDK15+

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent_spec.rb
Reintroduces into `master` the PR #12582 erroneously removed with PR #12614
=> Reintroduce the work done in PR #12614 erroneusly removed by PR #12582

.ci/matrix-runtime-javas.yml
Backport #12537 to `7.x`, Update CI to run on OpenJDK15
commit 8c3ff551ede17e23102b6857bb8cb233969ccfd9
=> Backport #12537 to `7.x`, update CI to run on OpenJDK15

docs/static/jvm.asciidoc
Backport of #12614 to `7.x` without the accidental removals fixed with #12631
=> Backport of #12614 [Doc] added instruction on how to update log and jvm files

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent_spec.rb
- enable agent to stop pipeline by pipeline_id (#12582)
=> [7.x] enable agent to stop pipeline by pipeline_id (#12582)

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent/converge_spec.rb
Clean backport of #12589
Due to a change in #11803, using `to_seconds` to normalize values of `config.reload.interval`
would resolve to a value of 0 causing issues in tests where short reload intervals were desired.
This commit uses the `to_nanos` method to preserve the previous functionality.
=> 7x Fix sub second `config.reload.interval`

qa/docker/shared_examples/container.rb
Docker container integration tests relating to the java process were
failing due to the introduction of the new JVM option parser. This
commit waits for logstash to start before testing that the logstash
java process is being run as expected
=> Update docker container tests to handle jvm option parser

lib/pluginmanager/utils/http_client.rb, spec/unit/plugin_manager/utils/http_client_spec.rb
Backport PR #12626 to 7.11 branch. Original message: 
The plugin manager's http client was using an obsolete way to read headers, causing the plugin test to fail.
This PR changes to the right api: [`#[]`](https://www.rubydoc.info/stdlib/net/Net/HTTPHeader#[]-instance_method).
=> Backport PR #12626 to 7.11: use correct headers api for redirects in plugin manager http client

config/jvm.options, docs/static/jvm.asciidoc
This PR is to remove CMS configuration in java 14
CMS collector is [no longer available](https://openjdk.java.net/jeps/363) in 14, however, the doc and jvm options are suggesting to use `-XX:+UseConcMarkSweepGC`
=> remove CMS from jvm options for java 14

config/jvm.options, docs/static/jvm.asciidoc
- remove CMS from jvm options in java 14 (#12638)
=> [7.x] remove CMS from jvm options in java 14 (#12638)

logstash-core/lib/logstash/deprecation_message.rb, logstash-core/lib/logstash/patches/clamp.rb, logstash-core/lib/logstash/runner.rb
This PR allows warning message from [clamp](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/patches/clamp.rb#L80) shows in log file. 
The reason of logger failed to log message is that logger is used before log4j setup. Putting log4j setup to an earlier stage, Runner#run, allows logger to function in clamp but this cause another problem of losing user config, `--path.log`, which is necessary for a proper log4j setup.
This PR proposes to store the deprecation message in memory and remove them once it shows to users.
Log should show
```
Sending Logstash logs to /Users/xxx/logstash/logs which is now configured via log4j2.properties
[2021-01-25T13:48:40,263][WARN ][logstash.runner          ] DEPRECATION WARNING: The flag ["--debug"] has been deprecated, please use …
```
=> Fix showing deprecation warning of command line flags

qa/docker/shared_examples/container.rb
Clean backport of #12633
Docker container integration tests relating to the java process were
failing due to the introduction of the new JVM option parser. This
commit waits for logstash to start before testing that the logstash
java process is being run as expected
=> [7.11 backport] Update docker container tests to handle jvm option parser

qa/docker/shared_examples/container.rb
Clean backport of #12633
Docker container integration tests relating to the java process were
failing due to the introduction of the new JVM option parser. This
commit waits for logstash to start before testing that the logstash
java process is being run as expected
=> [7x backport] Update docker container tests to handle jvm option parser

docker/templates/Dockerfile.j2
This commit updates the dockerfile template to support environment
variables being used to retrieve the architecture appropriate logstash
build, in the same way as is currently done for the Elasticsearch docker build.
This is required to support the official dockerhub builds of Logstash.
Relates #12578
=> Update dockerfile template to allow selection of architecture by env

logstash-core/lib/logstash/deprecation_message.rb, logstash-core/lib/logstash/patches/clamp.rb, logstash-core/lib/logstash/runner.rb
- Fix showing deprecation warning of command line flags (#12592)
=> [7.x] Fix showing deprecation warning of command line flags (#12592)

build.gradle
Introduces a new Gradle task to be executed before `downloadEs` task, that checks the local ES package fingerprint (if already present) against the one remote retrieved remotely. If the the two fingerprints differ or the local package is not present that permit the download, else avoid it.
This PR saves the sha512 of ES package to a local file in `build/` directory. In builds which require Elastisearch package download this file content is checked to avoid the unseful download of Elastisearch where the remote sha doesn't change
This PR makes faster the dev cycle in every task that require the integration with Elasticsearch, for example subsequent runs of `:logstash-xpack:rubyIntegrationTests` task downloads repeatedly the ES package which waste time.
=> Improve integrationTests task checking local ES fingerprint before full download

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent/converge_spec.rb
Clean backport of #12589
Due to a change in #11803, using `to_seconds` to normalize values of `config.reload.interval`
would resolve to a value of 0 causing issues in tests where short reload intervals were desired.
This commit uses the `to_nanos` method to preserve the previous functionality.
=> [7.11 backport] Fix sub second `config.reload.interval`

docker/templates/Dockerfile.j2
Clean backport of #12636
This commit updates the dockerfile template to support environment
variables being used to retrieve the architecture appropriate logstash
build, in the same way as is currently done for the Elasticsearch docker build.
This is required to support the official dockerhub builds of Logstash.
Relates #12578
=> [7x backport] Update dockerfile template to allow selection of architecture by env

docker/templates/Dockerfile.j2
Clean backport of #12636
This commit updates the dockerfile template to support environment
variables being used to retrieve the architecture appropriate logstash
build, in the same way as is currently done for the Elasticsearch docker build.
This is required to support the official dockerhub builds of Logstash.
Relates #12578
=> [7.11 backport] Update dockerfile template to allow selection of architecture by env

logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/pipelines_registry.rb, logstash-core/spec/logstash/pipelines_registry_spec.rb, logstash-core/spec/support/matchers.rb
Actually the pipelines (from the PipelineRegistry) point of view are in 2 states `terminated` and `running` where `running` is simply obtained as `not terminated`. This drive to a problem that also pipelines in `loading` status are considered as `running` and so are eligible to be queried for metrics while still building its metrics structure, and so generates a Nil access.
This commit separate the "not terminated" state explicitly in "running" and "loading" to avoid some pipelines in loading state to be defined as "running".
This PR fixes a bug that manifests on automatic reloading
Use this reproducer …
=> Separate "not terminated" state in "loading" and "running"

logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/pipelines_registry.rb, logstash-core/spec/logstash/pipelines_registry_spec.rb, logstash-core/spec/support/matchers.rb
clean backport of #12444 to `7.x` branch
(cherry picked from commit 79d8f47437e07758096191b077a8818a29fd5d98)
=> [backport]Separate "not terminated" pipeline state into "running" and "loading".

logstash-core/lib/logstash/agent.rb, x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb, x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb, x-pack/spec/monitoring/schemas/monitoring_document_schema.json
This PR is a follow up related to the comment https://github.com/elastic/logstash/pull/12444#issuecomment-737297054
When Logstash is confiugred to use the internal monitoring *and* has a user pipeline that has a slow start (for example an init step with a sleep or the scheduler decides to switch context before), it happens that the monitoring pipeline fails to grab a metric, named `http_address`. That metric is created by the webserver, when it's started, and actually the webserver is started after all the pipeline creation tasks are executed. The same problem happens also if Logstash starts with `http.enabled=false` and uses the internal monitoring collector.
This PR proposes 2 changes:
- start the webserver before the execution of create pipeline tasks.
- expose a default metric for …
=> Send monitoring information when LS pipelines is booting

logstash-core/lib/logstash/agent.rb, x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb, x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb, x-pack/spec/monitoring/schemas/monitoring_document_schema.json
Clean backport of #12571 to `7.x` branch
(cherry picked from commit 91996cf2a2b2b7cd9b11c8f003830874deab67f9)
=> Backport PR to 7.x of #12571

qa/integration/specs/cli/install_spec.rb
On certain instances of centos6 on the ci (https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-matrix-jdk-unix-integration-2/LS_RUNTIME_JAVA=adoptopenjdk15,os=centos&&immutable/23/consoleFull)  the build fails with:
```
09:36:18       1) CLI > logstash-plugin install pack when the command is run outside of the `$LOGSTASH_HOME` without internet connection (linux seccomp wrapper) successfully install the pack
09:36:18          Failure/Error: execute = @logstash_plugin.run_raw("#{offline_wrapper_cmd} #{install_command} #{pack}", change_dir)
09:36:18          
09:36:18          ChildProcess::LaunchError:
09:36:18            Cannot run program "/var/lib/jenkins/workspace/elastic+logstash+master+multijob-matrix-jdk-unix-integration-2/LS_RUNTIME_JAVA/adoptopenjdk15/os/centos&&immu …
```
=> Make integration test fail if 'offline' tool can't be compiled

qa/integration/services/elasticsearch_service.rb, qa/integration/specs/dlq_spec.rb, qa/integration/specs/es_output_how_spec.rb, qa/integration/specs/spec_helper.rb
This commit fixes up some IT flakiness which has been presenting mostly
in recent DLQ test failures, it includes the following improvements:
* A recent change to Elasticsearch has required the cluster setting
`action.destructive_requires_name` to be set to `false` to enable the use
of destruction actions with wildcards. This commit sets this before
tests on Elasticsearch and DLQ tests
* Adds some extra safety to the `have_hits` rspec matcher
* Makes the DLQ tests less noisy by removing debug flag
=> Fix Elasticsearch/DLQ integration test flakiness

qa/integration/services/elasticsearch_service.rb, qa/integration/specs/dlq_spec.rb, qa/integration/specs/es_output_how_spec.rb, qa/integration/specs/spec_helper.rb
Clean backport of #12685
This commit fixes up some IT flakiness which has been presenting mostly
in recent DLQ test failures, it includes the following improvements:
* A recent change to Elasticsearch has required the cluster setting
`action.destructive_requires_name` to be set to `false` to enable the use
of destruction actions with wildcards. This commit sets this before
tests on Elasticsearch and DLQ tests
* Adds some extra safety to the `have_hits` rspec matcher
=> [7x backport] Fix Elasticsearch/DLQ integration test flakiness

rubyUtils.gradle
JRuby had a few releases where it shipped with bundler,creating some difficulty in working with newer versions.
This no longer happens so we can remove these exclusions from the jruby unzipping task.
=> cleanup bundler exclusions during jruby unpacking

versions.yml
Backport PR #12693 to 7.x branch. Original message: 
Update adoptopenjdk version to 11.0.10+9
=> Backport PR #12693 to 7.x: update jdk to 11.0.10+9

versions.yml
Backport PR #12693 to 7.12 branch. Original message: 
Update adoptopenjdk version to 11.0.10+9
=> Backport PR #12693 to 7.12: update jdk to 11.0.10+9

rubyUtils.gradle
Backport PR #12692 to 7.x branch. Original message: 
JRuby had a few releases where it shipped with bundler,creating some difficulty in working with newer versions.
This no longer happens so we can remove these exclusions from the jruby unzipping task.
=> Backport PR #12692 to 7.x: cleanup bundler exclusions during jruby unpacking

x-pack/lib/filters/geoip/database_manager.rb, x-pack/lib/filters/geoip/database_metadata.rb, x-pack/lib/filters/geoip/download_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb, x-pack/spec/filters/geoip/download_manager_spec.rb
This PR adds a clean-up step after a new GeoIP database download.
After pointing to new database, database_manager removes .gz and .mmdb which is not in the metadata.
- add clean-up database
- improve log
Logstash PR https://github.com/elastic/logstash/pull/12675
Meta https://github.com/elastic/logstash/issues/12560
=> GeoIP clean up database after new download

x-pack/spec/filters/geoip/download_manager_spec.rb
This PR fix the broken test related GeoIP
`elastic_geoip_service_tos` is no longer optional
=> fix broken xpack unit test of GeoIP term of service

.ci/matrix-runtime-javas.yml
Add AdoptOpenJDK15 and Zulu15 to CI matrix
Backport of #12649
(cherry picked from commit 0d6666b1da8cf415630ce12701ded78f4a3fbf21)
=> [backport 7.x] Removed OpenJDK15 in CI matrix testing #12649

x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
This PR switch-off a test that's flaky and is influenced by issue #12711
run:
```
SPEC_OPTS="-fd -P spec/monitoring/inputs/metrics/stats_event_factory_spec.rb" ./gradlew --rerun-tasks :logstash-xpack:rubyTest
```
- related #12711
Output from CI:
```
18:53:06     Failures:
18:53:06 
18:53:06       1) LogStash::Inputs::Metrics::StatsEventFactory old model behaves like old model monitoring event with webserver setting should be valid
18:53:06          Failure/Error: expect(JSON::Validator.fully_validate(schema_file, monitoring_evt.to_json)).to be_empty
18:53:06            expected `["The property '#/events/in' of type null did not match the following type: number in schema file:///...ms 1 in schema file:///opt/logstash/x-pack/spec/monitoring/schemas/monitoring_document_schema.json"].empty?` …
```
=> Temporarly silenced an x-pack monitoring test, waiting to be fixed the root cause

logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/pipelines_registry.rb, logstash-core/spec/logstash/pipelines_registry_spec.rb, logstash-core/spec/support/matchers.rb
Clean backport of #12444 to `7.11` branch
(cherry picked from commit 79d8f47437e07758096191b077a8818a29fd5d98)
=> [backport #12444 7.11] Separate "not terminated" pipeline state into "running" and "loading".

logstash-core/spec/logstash/plugin_spec.rb, logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb, rubyUtils.gradle, versions.yml, x-pack/spec/config_management/elasticsearch_source_spec.rb, x-pack/spec/helpers/elasticsearch_options_spec.rb
replaces #12519
The `super` to `super()` change comes from the changes in JRuby, that make it behave like CRuby:
```ruby
require 'rspec'
describe "calling super in a let" do
let("object") { Hash.new }
context "when adding something to that object" do
let("object") { super.merge("hey" => "you") }
it "should show the new object with a key and value" do
expect(object).to include("hey")
expect(object["hey"]).to eq("you")
end
end
end
```
```
/tmp
❯ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
/tmp
❯ rspec test_rspec.rb                                                                                                                  
F
Failures:
1) calling super in a let when adding something to that object should show the new object with a key and value …
```
=> update jruby to 9.2.16.0

x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Clean backport of #12712 to `7.x` branch
(cherry picked from commit bca169f34890cf34b8debf760f9cd58cb502da06)
=> [backport #12712 7.x]Temporarly silenced an x-pack monitoring test

logstash-core/spec/logstash/plugin_spec.rb, logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb, rubyUtils.gradle, versions.yml, x-pack/spec/config_management/elasticsearch_source_spec.rb, x-pack/spec/helpers/elasticsearch_options_spec.rb
Backport PR #12699 to 7.x branch. Original message: 
replaces #12519
The `super` to `super()` change comes from the changes in JRuby, that make it behave like CRuby:
```ruby
require 'rspec'
describe "calling super in a let" do
let("object") { Hash.new }
context "when adding something to that object" do
let("object") { super.merge("hey" => "you") }
it "should show the new object with a key and value" do
expect(object).to include("hey")
expect(object["hey"]).to eq("you")
end
end
end
```
```
/tmp
❯ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
/tmp
❯ rspec test_rspec.rb                                                                                                                  
F
Failures:
1) calling super in a let when adding something to that object …
```
=> Backport PR #12699 to 7.x: update jruby to 9.2.16.0

logstash-core/build.gradle
runtime dependency (patch version) update
LS was defaulting to pull in *slf4j* 1.7.25 which we got complains about being "old" (16-Mar-2017).
SLF4j API is pulled in by *log4j-slf4j-impl* (defaults to 1.7.25) thus we now version *slf4j* explicitly.
NOTE: there's *log4j2* 1.14.0 [released a few months back](https://blogs.apache.org/logging/entry/log4j-2-14-0-released) we should consider updating as well.
=> Deps: update slf4j to latest 1.7.30

devtools/backport
Ensure we always prefix the version number with 'v', so it is added to both, the original and the backport PR.
=> backport: always prefix the version number

docker/bin/elastic-version
Prior to this release a VERSION_QUALIFER env set to an empty string
would create versions looking like `8.0.0--SNAPSHOT` instead of
`8.0.0-SNAPSHOT`, causing the release manager builds to fail.
=> [Build] Fix version script when VERSION_QUALIFIER is empty string

docs/index.asciidoc
Employ the universal {docs-root} attribute to replace relative paths
=> Docs: Implement docs-root for shared files

docs/static/getting-started-with-logstash.asciidoc
PR #12706 added the windows command.  This PR adds the framework for showing both windows and unix examples. 
**PREVIEW:**  https://logstash_12714.docs-preview.app.elstc.co/guide/en/logstash/master/first-event.html
=> Doc: Add unix command for running basic pipeline

x-pack/lib/filters/geoip/download_manager.rb, x-pack/spec/filters/geoip/download_manager_spec.rb, x-pack/spec/filters/geoip/fixtures/normal_resp.json, x-pack/spec/filters/geoip/test_helper.rb
infra has changed the endpoint of GeoIP database service 
-- | Old | New
-- | -- | --
Domain | paisano.elastic.dev | geoip.elastic.co
Staging | paisano-staging.elastic.dev | geoip.elastic.dev
URI Format | /v1/geoip/database | /v1/database
key=$UUID | Required | Optional
elastic_geoip_service_tos=agree | Optional | Required
This PR updated the endpoint
=> change domain and endpoint of GeoIP database service

tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LsMetricsMonitor.java, tools/benchmark-cli/src/test/java/org/logstash/benchmark/cli/LsMetricsMonitorTest.java, tools/benchmark-cli/src/test/resources/org/logstash/benchmark/cli/metrics.json
Since the introduction of this block:
```
"pipeline" : {
"workers" : 16,
"batch_size" : 125,
"batch_delay" : 50
},
```
to the node stats API, the benchmarking tool has been broken. This commit fixes the
tool, and updates the payload in the tests to reflect the current payload.
=> Fix Benchmarking tool

tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LsMetricsMonitor.java, tools/benchmark-cli/src/test/java/org/logstash/benchmark/cli/LsMetricsMonitorTest.java, tools/benchmark-cli/src/test/resources/org/logstash/benchmark/cli/metrics.json
Backport PR #12736 to 7.x branch. Original message:
Since the introduction of this block:
```
"pipeline" : {
"workers" : 16,
"batch_size" : 125,
"batch_delay" : 50
},
```
to the node stats API, the benchmarking tool has been broken. This commit fixes the
tool, and updates the payload in the tests to reflect the current payload.
=> Backport PR #12736 to 7.x: Fix Benchmarking tool

README.md
Removes the "Snapshot builds" section from README.md for 7.11 branch like #12682 done for 7.x
=> Remove information about snapshot builds (7.12)

logstash-core/lib/logstash/agent.rb, x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb, x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb, x-pack/spec/monitoring/schemas/monitoring_document_schema.json
Clean backport of #12571 to `7.11` branch
(cherry picked from commit 91996cf2a2b2b7cd9b11c8f003830874deab67f9)
=> [backport #12571 7.11]Fix Logstash pipelines management in case of slow loading pipelines

README.md
Removes the "Snapshot builds" section from README.md for `master` branch like #12682 done for `7.x`
=> Remove information about snapshot builds (master) 

logstash-core/build.gradle
Expected to improve logging experience for libraries stuck with Log4J 1.2 logging.
Updates Log4j2 to latest [**1.4.0**](https://blogs.apache.org/logging/entry/log4j-2-14-0-released)
Adds a Log4j 1.2 API compatible bridge (1.4.0 [fixed](https://issues.apache.org/jira/browse/LOG4J2-2899) a bug in the bridge that might be relevant if we're to use the bridge).
A use-case for the bridge is debug logging with the input snmp plugin (capturing [SNMP4J library logs](https://doc.snmp.app/pages/viewpage.action?pageId=27459590)).
Might impact plugins that ship with log4j 1.2 (in a "positive" way if the bridge is picked up - logging will end up redirected to LS).
none of the current logstash plugins are expected to be affected.
confusingly, the plugin deals with …
=> Deps: update log4j2 to latest and ship log4j 1.2 bridge

x-pack/lib/monitoring/monitoring.rb, x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Fixes Internal Monitoring to correctly rely on the `monitoring.elasticsearch.ssl.verification_mode` setting.
Ensures that explicitly-configured options are used.
- Set up monitoring over SSL (e.g., with https host)
- Start Logstash
- Observe no warning about SSL being disabled
- Closes https://github.com/elastic/logstash/issues/10352
=> internal-monitoring: use configured ssl verification mode

x-pack/lib/monitoring/monitoring.rb, x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Backport PR #12749 to 7.x branch. Original message: 
Fixes Internal Monitoring to correctly rely on the `monitoring.elasticsearch.ssl.verification_mode` setting.
Ensures that explicitly-configured options are used.
- Set up monitoring over SSL (e.g., with https host)
- Start Logstash
- Observe no warning about SSL being disabled
- Closes https://github.com/elastic/logstash/issues/10352
=> Backport PR #12749 to 7.x: internal-monitoring: use configured ssl verification mode

x-pack/lib/monitoring/monitoring.rb, x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Backport PR #12749 to 7.12 branch. Original message: 
Fixes Internal Monitoring to correctly rely on the `monitoring.elasticsearch.ssl.verification_mode` setting.
Ensures that explicitly-configured options are used.
- Set up monitoring over SSL (e.g., with https host)
- Start Logstash
- Observe no warning about SSL being disabled
- Closes https://github.com/elastic/logstash/issues/10352
=> Backport PR #12749 to 7.12: internal-monitoring: use configured ssl verification mode

x-pack/lib/helpers/elasticsearch_options.rb, x-pack/lib/monitoring/monitoring.rb, x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Backport PR #12749 to 6.8 branch. Original message: 
Fixes Internal Monitoring to correctly rely on the `monitoring.elasticsearch.ssl.verification_mode` setting.
Ensures that explicitly-configured options are used.
- Set up monitoring over SSL (e.g., with https host)
- Start Logstash
- Observe no warning about SSL being disabled
- Closes https://github.com/elastic/logstash/issues/10352
=> Backport PR #12749 to 6.8: internal-monitoring: use configured ssl verification mode

.github/PULL_REQUEST_TEMPLATE.md
Phase 1: Collect content for [published release notes](https://www.elastic.co/guide/en/logstash/current/releasenotes.html) when PR is created and reviewed. 
Related: #12659
=> Internal: Add release notes section to pr template

docs/static/releasenotes.asciidoc
=> Remove 'coming' tag from 6.8.15 release notes

rakelib/plugins_docs_dependencies.rake
This PR handles memory leaks that exhibit when running the rake/gradle task.
NOTE: this is mostly a partial understanding what's going on by simply following the "huge" objects from memory dumps. 
There might be better ways to handle the issue - without the patches (e.g. rewrite plugin generation to put each `bundle` resolution into a disposable runtime or run as a process).
Details on why each patch is relevant are to be found in code comments.
To be able to generate plugin docs we need to check available plugin versions.
`./gradlew generatePluginsVersion -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -Xmx2g"`
should no longer end up with an out of memory error
Tested with Bundler 2.2.14 as well as latest 2.2.15
resolves https://github.com/elastic/logstash/issues/12758
related: …
=> Build: avoid leaking memory from generate_plugins_version

rakelib/plugins_docs_dependencies.rake
Backport PR #12763 to 7.x branch. Original message: 
This PR handles memory leaks that exhibit when running the rake/gradle task.
NOTE: this is mostly a partial understanding what's going on by simply following the "huge" objects from memory dumps. 
There might be better ways to handle the issue - without the patches (e.g. rewrite plugin generation to put each `bundle` resolution into a disposable runtime or run as a process).
Details on why each patch is relevant are to be found in code comments.
To be able to generate plugin docs we need to check available plugin versions.
`./gradlew generatePluginsVersion -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -Xmx2g"`
should no longer end up with an out of memory error
Tested with Bundler 2.2.14 as well as latest 2.2.15
resolves …
=> Backport PR #12763 to 7.x: Build: avoid leaking memory from generate_plugins_version

rakelib/plugins_docs_dependencies.rake
Backport PR #12763 to 7.12 branch. Original message: 
This PR handles memory leaks that exhibit when running the rake/gradle task.
NOTE: this is mostly a partial understanding what's going on by simply following the "huge" objects from memory dumps. 
There might be better ways to handle the issue - without the patches (e.g. rewrite plugin generation to put each `bundle` resolution into a disposable runtime or run as a process).
Details on why each patch is relevant are to be found in code comments.
To be able to generate plugin docs we need to check available plugin versions.
`./gradlew generatePluginsVersion -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -Xmx2g"`
should no longer end up with an out of memory error
Tested with Bundler 2.2.14 as well as latest 2.2.15
resolves …
=> Backport PR #12763 to 7.12: Build: avoid leaking memory from generate_plugins_version

docs/static/keystore.asciidoc
[rn:skip] 
Reverts a direct commit to keystore docs for further testing and investigation
=> Revert commit for further testing

pkg/centos/after-install.sh, pkg/debian/after-install.sh, pkg/ubuntu/after-install.sh
Fix package install permissions of /usr/share/logstash
This PR fixes the the permissions of (RPM, DEB) for /usr/share/logstash.
Ensures /usr/share/logstash has the appropriate ownership as per the FHS. Also ensures the daemon cannot modify files it needs to run.
1. Create a debian or RPM package.
2. Manually install it
3. Check /usr/share/logstash is owned by root:root
- Closes #12771
=> Set correct permissions for /usr/share/logstash on pkg installs

pkg/centos/after-install.sh, pkg/debian/after-install.sh, pkg/ubuntu/after-install.sh
Backport PR #12782 to 7.x branch. Original message: 
Fix package install permissions of /usr/share/logstash
This PR fixes the the permissions of (RPM, DEB) for /usr/share/logstash.
Ensures /usr/share/logstash has the appropriate ownership as per the FHS. Also ensures the daemon cannot modify files it needs to run.
1. Create a debian or RPM package.
2. Manually install it
3. Check /usr/share/logstash is owned by root:root
- Closes #12771
=> Backport PR #12782 to 7.x: Set correct permissions for /usr/share/logstash on pkg installs

pkg/centos/after-install.sh, pkg/debian/after-install.sh, pkg/ubuntu/after-install.sh
Backport PR #12782 to 7.12 branch. Original message: 
Fix package install permissions of /usr/share/logstash
This PR fixes the the permissions of (RPM, DEB) for /usr/share/logstash.
Ensures /usr/share/logstash has the appropriate ownership as per the FHS. Also ensures the daemon cannot modify files it needs to run.
1. Create a debian or RPM package.
2. Manually install it
3. Check /usr/share/logstash is owned by root:root
- Closes #12771
=> Backport PR #12782 to 7.12: Set correct permissions for /usr/share/logstash on pkg installs

x-pack/qa/integration/support/helpers.rb
Elasticsearch [change](https://github.com/elastic/elasticsearch/pull/66908) the default behavior to not accept wildcard in DELETE 
This PR set the `action.destructive_requires_name` to false in integration test
=> Fix integration test to allow wildcard deletion in elasticsearch

qa/integration/specs/cli/keystore_spec.rb
In #12784 the integration spec could leave the unpacked tar with a `config/logstash-keystore` file.
This causes :red_circle:  while backporting to 7.x / 7.12 due order of tests.
Just a quick follow up on #12784 for a more stable test experience.
Avoids potentially unexpected CI failures.
=> Test: cleanup for every test (follow-up #12784)

lib/pluginmanager/bundler/logstash_uninstall.rb, qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb, qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
- Allow plugin manager uninstall plugin regardless of working directory (#12786)
=> [7.x] Allow plugin manager uninstall plugin regardless of working directory (#12786)

lib/pluginmanager/bundler/logstash_uninstall.rb, qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb, qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
Backports the following commits to 7.12:
- Allow plugin manager uninstall plugin regardless of working directory (#12786)
=> [7.12] Allow plugin manager uninstall plugin regardless of working directory (#12786)

logstash-core/logstash-core.gemspec, x-pack/lib/filters/geoip/database_manager.rb
It does 2 things:
- fix a class clash
- pinpoint openssl-java to `0.10.5` to avoid some problems proved with `0.10.6`
Fixes a class clash happening in integration tests, where a pipeline composed with `filter-date` and `filter-geoip` is used. This happens only in the integration test not in a self hosted pipeline, for example using:
```ruby
input {stdin{}}
filter {
date {
match => [ "timestamp", "dd/MMM/YYYY:HH:mm:ss Z" ]
locale => en
}
geoip {
source => "clientip"
}
}
output {
stdout {
codec => rubydebug
}
}
```
and run with `bin/logstash -f pipeline.conf` doesn't manifest the problem
It could raise some problems in pipelines with date filter and geoip
- run `./gradlew runIntegrationTests -PrubyIntegrationSpecs=specs/es_output_how_spec.rb`
- check for error `NoMethodError: undefined …
=> Fix Date class clash when used in pipelines with Date filter and GeoIP and pin open-ssl to 0.10.5

logstash-core/logstash-core.gemspec, x-pack/lib/filters/geoip/database_manager.rb
Clean backport of #12811 to `7.x`
This commit contains two fixes
* Fix Date class clash when used in pipelines with Date filter and GeoIP
* Pinned jruby-openssl version 0.10.5 to avoid SSL errors
(cherry picked from commit 6f55066b17bc795d07d629b5292258d1541171cc)
=> [backport 7.x] Fix Date class clash when used in pipelines with Date filter and GeoIP and pin open-ssl to 0.10.5 (#12811)

logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java, logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java, logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
- Removes the need of static initializer and static methods in `org.logstash.plugins.discovery.PluginRegistry`
- Changed `org.logstash.plugins.PluginLookup` to implement `org.logstash.plugins.factory.PluginFactoryExt.PluginResolver`
These changes are preparatory to adding an "alias resolver" during plugin lookup #12796
Static initializers and static method made test impossible when a dependency is static instead of customizable.
Other than this, the construction sequence is made explicit, describing better the chain of dependency of various services.
- [ x] Run Logstash to laod a pipeline configuration with and without Java native plugins. Java native plugins are those loaded by Java's PluginRegistry.
- Relates #12796
=> Removed static part from PluginRegistry to avoid static initializer

docs/static/cross-plugin-concepts.asciidoc
Adds an example showing users how to use the environment variable to define multiple whitespace-delimited URIs
Adds an example of how to use this functionality in an environment variable.
It is important because the current documentation is not clear enough and is confusing users as to how to use this behavior.
Closes #12661
=> [doc] Add example to cross-plugin-concepts

docs/static/field-reference.asciidoc
Field reference documentation update.
Confusing behavior on `["foo"]` quoted field references.
- see GH-5591
=> Docs: note on quoted field references

docs/static/field-reference.asciidoc
Backport PR #12801 to 7.x branch. Original message: 
Field reference documentation update.
Confusing behavior on `["foo"]` quoted field references.
- see GH-5591
=> Backport PR #12801 to 7.x: Docs: note on quoted field references

qa/integration/services/elasticsearch_service.rb, qa/integration/specs/dlq_spec.rb, qa/integration/specs/es_output_how_spec.rb, qa/integration/specs/spec_helper.rb
Backport PR #12685 to 7.12 branch. Original message: 
This commit fixes up some IT flakiness which has been presenting mostly
in recent DLQ test failures, it includes the following improvements:
* A recent change to Elasticsearch has required the cluster setting
`action.destructive_requires_name` to be set to `false` to enable the use
of destruction actions with wildcards. This commit sets this before
tests on Elasticsearch and DLQ tests
* Adds some extra safety to the `have_hits` rspec matcher
* Makes the DLQ tests less noisy by removing debug flag
=> Backport PR #12685 to 7.12: Fix Elasticsearch/DLQ integration test flakiness

logstash-core/lib/logstash/plugins/registry.rb, logstash-core/spec/logstash/java_pipeline_spec.rb, logstash-core/spec/logstash/plugins/registry_spec.rb, logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java, logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java, logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java, logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
If the plugin name is an alias and no other plugin exists with same name then load the alised one
Introduce the concept of aliased plugin, to let a plugin be renamed easily
An alias for a plugin is a just a rename of an existing plugin, in this way the alias can be used in pipeline configuration. If later a real plugin with same name of the alias is released then that plugin takes precedence over the alias name. 
Suppose we a plugin filter named `teleport` and we also alias it as `teleport_over_fiber`, the `teleport_over_fiber` alias can be used in interchangeable way as `teleport` with same parameters and behavior. In a future when a real plugin that leverage fiber transmission for teleport a plugin `teleport_over_fiber` name is effectively released, this real plugin takes precedence to …
=> Load a plugin by alias name.

lib/pluginmanager/install.rb, lib/pluginmanager/list.rb, lib/pluginmanager/remove.rb, lib/pluginmanager/update.rb, lib/pluginmanager/util.rb
Let `bin/logstash-plugin` to `install` `uninstall` aliased plugin and shows the aliased plugin name near to the original during `list` command.
This PR is follow up on #12796 and adapt the `logstash-plugin` tool to manage aliased plugins.
It follow this behavior:
- if a real plugin corresponding to the alias exists then installs it, else resolves the alias to the original plugin and installs that, notifying the user.
- in listing of plugins it displays the alias name close to the unaliased real plugin unless it's installed a plugin with same of the alias.
- during removal of an alias if there isn't installed a real plugin with same name it asks the user to remove the unaliased plugin
- update: if a real plugin with same name of the alias is already installed then updates normally, else …
=> Adapted install/uninstall/list PluginManager's command to respect the alised plugins

lib/pluginmanager/install.rb, lib/pluginmanager/list.rb, lib/pluginmanager/remove.rb, lib/pluginmanager/update.rb, lib/pluginmanager/util.rb
Clean backport of #12821 to `7.x`
Adapted install/uninstall/list PluginManager's CLI commands to respect the alised plugins
- adapt install plugin to resolve an alias giving precedence on a real plugin
- changed list to mark alised plugins
- uninstall avoid to remove the alias and ask the user to remove the original plugin
- update update the original plugin in case of alias, else fallback on usual behavior
Co-authored-by: Ry Biesemeyer <ry.biesemeyer@elastic.co>
(cherry picked from commit 1e08341e1ea7e269182cd40e70d13bd95bd6e9b2)
=> [Backport 7.x] Plugin Manager adaptation to handle alias plugins

docs/static/keystore.asciidoc
[rn:skip]
Updates docs to propagate this change to other branches.  The original was a direct commit to the 7.10 branch. 
Backport targets: 7.x, 7.12, 7.11
=> Doc: Keystore must be accessible to logstash user

docs/static/keystore.asciidoc
Backports #12775 to 7.x
[rn:skip]
=> Doc: Keystore must be accessible to logstash user 

build.gradle
Integration tests launched by `integrationTests` task needs to spawn instances of Elasticsearch, so for example when launching with `./gradlew integrationTests -PrubyIntegrationSpecs=specs/es_output_how_spec.rb` it needs the Elasticseach to be downloaded and unpacked in the `build/` folder
Doesn't affect the user directly
-
=> Change :logstash-integration-tests:integrationTests to depends on copyES

build.gradle
clean backport of #12847 
The integrationTests start instances of Elasticsearch so they need it to be present and unpacked in build/ folder before start.
(cherry picked from commit 149ee41a8b07b318eb17e1e72af5c743a5002468)
=> [backport 7.x] Change Gradle's :logstash-integration-tests:integrationTests task to depends on copyES (#12847)

x-pack/lib/filters/geoip/database_manager.rb, x-pack/lib/filters/geoip/database_metadata.rb, x-pack/lib/filters/geoip/download_manager.rb, x-pack/lib/filters/geoip/util.rb, x-pack/spec/filters/geoip/database_manager_spec.rb, x-pack/spec/filters/geoip/database_metadata_spec.rb, x-pack/spec/filters/geoip/download_manager_spec.rb, x-pack/spec/filters/geoip/test_helper.rb
Currently, the plugin downloads database and creates metadata under logstash-filter-geoip/vendor which has permission issue in docker and dep/rmps
This PR changes the working directory to `path.data`
There are some follow-up PRs for geoip, and the CI is highly coupling to the plugin. To simply the test/CI process, the removal of `vendor_path` in DatabaseManager constructor will be in another PR
Fixed: https://github.com/elastic/logstash/issues/12858
=> change download path for geoip plugin

Gemfile.jruby-2.5.lock.release
a [bug](https://github.com/elastic/logstash/issues/12856) is in `7.1.0`
before we fix it, pin it to an old version to avoid loading GeoIP service
=> [7.13] revert geoip plugin to 6.0.5

logstash-core/lib/logstash/config/string_escape.rb, logstash-core/spec/logstash/config/string_escape_spec.rb
When `config.support_escapes: true` is set in logstash.yaml, escape characters can be used in any string, most notably the string "delimiter" from input.file.
This works great for traditional logfiles under Windows/Mac/Unix.
But for modern logfiles, produced in a multibyte characterset, this facility is still insufficient.
e.g. under UTF-16LE the delimiter is actually "\r\0\n\0", but that format cannot be specified. I expect the same problems for the UTF-16BE, UTF-32BE, UTF-32LE, UTF-16, UTF-32, UCS-2BE, UCS-4BE or UCS-4LE character sets.
The suggested solution in this PR is simple:
Update [logstash-core/lib/logstash/config/string_escape.rb] to support "\0".
=> Support for UTF-16 and other multi-byte-character logfiles

qa/integration/fixtures/dlq_spec.yml, qa/integration/services/elasticsearch_setup.sh, qa/integration/specs/dlq_spec.rb
This PR changes the DLQ integration tests to not rely on default names of indices for writing data to ES.
Also ensures ES is started in a single node mode.
These changes remove some of the magic of the integration test, where we relied on a index having a template with a geoip field with geo data types already. In these commits we explicitly push a template and then use a message that clearly clashes with that template.
=> fix DLQ integration tests

logstash-core/logstash-core.gemspec
Update Elasticsearch minimum version requirement to `~>7` also on the `7.x` branch.
Relates to #11258
(cherry picked from commit ef9b0d2db5f1a30cd0cef7920991b3b309323019)
=> [Backport 7.x]Update elasticsearch gem dependency requirements (#11258)

Gemfile.jruby-2.5.lock.release
Validates that required functionality in ES is available, upon initial connection.
Changes: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1015/files
Also, the previous diff update seems to have been done manually as there was a left-over dependency.
Here's a different attempt to update ES output [from 7.12.1 on 7.13](https://github.com/elastic/logstash/pull/12828/files/9eabd0491e6448ea19dc6f80f33eb4fff73d2c6a..c02a5846b1d2eeae0cbfc021a5b23b90209b9cee#diff-127e1a3a65d315d86dbe640d9578a969da44e5226e5d9bf2de251b075c1d8b7aL484-L485) (cabin dependency removed w the 11.0 plugin update)
=> [7.13] update ES output plugin to latest

docs/static/fb-ls-kafka-example.asciidoc, docs/static/filebeat-modules.asciidoc
Backports #10671 to 7.13
[rn:skip]
Comments out configuration examples that are not ecs-compliant. The examples need to be updated and reevaluated in context of new capabilities and best practices. That is, the examples need work beyond replacing field names.
=> Comment out config examples pending rework (backport to 7.13)

docker/templates/Dockerfile.j2
When building the aarch64 docker artifacts, the initial `yum update` would fail with the following error:
```
http://d36uatko69830t.cloudfront.net/altarch/7/updates/aarch64/Packages/bind-license-9.11.4-26.P2.el7_9.5.noarch.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=updates clean metadata
```
This is currently blocking the unified release builds. This commit fixes the creation of the docker images. But does not fix the issue in https://github.com/elastic/logstash/issues/12898, which is currently failing CI on aarch64 nodes.
No user-facing changes in this commit
When building the aarch64 docker artifacts, the initial `yum update` would attempt to update the `bind-license` package from a location where it does not exist and fail with the …
=> [Build] On aarch64 docker build, install `noarch` version of bind-license first

docker/templates/Dockerfile.j2
ubi8 image uses microdnf as a package manager, and microdnf does
not support the "yum clean metadata" command. This commit adds
the logic to skip this command if the image_flavor is ubi8
To test this, you can use the following command to generate the Dockerfiles and compare them:
```
jinja2 -D created_date='2021-05-12T09:36:42Z' -D elastic_version='7.13.0-SNAPSHOT' -D arch='x86_64' -D version_tag='7.13.0-SNAPSHOT' -D image_flavor='oss' -D local_artifacts='true' docker/templates/Dockerfile.j2 > Dockerfile-oss
jinja2 -D created_date='2021-05-12T09:36:42Z' -D elastic_version='7.13.0-SNAPSHOT' -D arch='x86_64' -D version_tag='7.13.0-SNAPSHOT' -D image_flavor='full' -D local_artifacts='true' docker/templates/Dockerfile.j2 > Dockerfile-full
jinja2 -D created_date='2021-05-12T09:36:42Z' -D …
```
=> fix ubi8 docker image creation by skipping yum clean metadata

docker/templates/Dockerfile.j2
Backport PR #12902 to 7.13 branch. Original message: 
ubi8 image uses microdnf as a package manager, and microdnf does
not support the "yum clean metadata" command. This commit adds
the logic to skip this command if the image_flavor is ubi8
To test this, you can use the following command to generate the Dockerfiles and compare them:
```
jinja2 -D created_date='2021-05-12T09:36:42Z' -D elastic_version='7.13.0-SNAPSHOT' -D arch='x86_64' -D version_tag='7.13.0-SNAPSHOT' -D image_flavor='oss' -D local_artifacts='true' docker/templates/Dockerfile.j2 > Dockerfile-oss
jinja2 -D created_date='2021-05-12T09:36:42Z' -D elastic_version='7.13.0-SNAPSHOT' -D arch='x86_64' -D version_tag='7.13.0-SNAPSHOT' -D image_flavor='full' -D local_artifacts='true' docker/templates/Dockerfile.j2 > Dockerfile-full …
```
=> Backport PR #12902 to 7.13: fix ubi8 docker image creation by skipping yum clean metadata

x-pack/lib/filters/geoip/database_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb
We have decided to retarget the release version to 7.14 for a better user experience. This PR disable database auto-update
=> Geoip disable database manager

versions.yml
Backport of PR #12881 to `7.x` branch
(cherry picked from commit 4f63701d6d15d2e094f76c49804070f097414071)
=> [backport 7.x]Update bundled JDK to 11.0.11+9 (#12881)

x-pack/lib/filters/geoip/database_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb
Backports the following commits to 7.13:
- Geoip disable database manager (#12905)
=> [7.13] Geoip disable database manager (#12905)

x-pack/lib/filters/geoip/database_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb
- Geoip disable database manager (#12905)
=> [7.x] Geoip disable database manager (#12905)

docker/templates/Dockerfile.j2
JDK 1.8.0.292 has a race condition that impacts creating keystores.
Logstash issue: https://github.com/elastic/logstash/issues/12917
OpenJDK issue: https://bugs.openjdk.java.net/browse/JDK-8266261
For reviewers, to test this:
1. `rake artifact:docker`
2. `docker run -it docker.elastic.co/logstash/logstash-full:6.8.16-SNAPSHOT bash `
3. `echo y | LOGSTASH_KEYSTORE_PASS=hey bin/logstash-keystore create`
Fixes #12917
=> Pin JDK8 version in Docker to avoid KeyStore creation race condition 

docs/static/releasenotes.asciidoc
Update Release Notes for version 6.8.16
**PREVIEW:** https://logstash_12922.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-16.html
=> Created release notes for v6.8.16

rakelib/plugins-metadata.json, tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/elastic-workplace-search-NOTICE.txt
This PR adds the new enterprise search integration plugin to the plugin metadata list, and removes the `elastic_app_search` plugin.
=> Add logstash-integration-elastic_enterprise_search to plugins-metadata.json

versions.yml
Clean backport of PR #12881 to `7.13` branch
(cherry picked from commit 4f63701d6d15d2e094f76c49804070f097414071)
----
**WARN**
to be merged after 7.13.0 is released
=> [backport 7.13]Update bundled JDK to 11.0.11+9 (#12881)

docs/static/doc-for-plugin.asciidoc
[rn:skip]
Spells out words before introducing abbreviation and fixes typo
=> Doc: Expand definition and fix typo for CLA

docs/static/doc-for-plugin.asciidoc
Backports #12936 to 7.13
[rn:skip]
Spells out words before introducing abbreviation and fixes typo
=> Doc: Expand definition and fix typo 

x-pack/lib/template.cfg.erb
Since we default to data streams in 8.0.0, the internal collection for monitoring stops working due to the ES output trying to send data to the logs- data stream instead of the monitoring endpoint.
We can see this in the network traffic during the x-pack integration tests that are currently failing:
```
POST /_monitoring/bulk?system_id=logstash&system_api_version=7&interval=1s HTTP/1.1
Connection: Keep-Alive
Content-Type: application/json
Content-Length: 1870
Host: localhost:9200
User-Agent: Manticore 0.7.0
Accept-Encoding: gzip,deflate
 
{"create":{"_id":null,"_index":"logs-generic-default","routing":null}}
{"pipeline":...}
```
Reviewers can confirm that the tests no longer hang by running `./x-pack/ci/integration_tests.sh ` after applying this patch to the master branch
=> turn off data streams in internal monitoring collection

tools/release/generate_release_notes.rb
[rn:skip]
Our release notes script generates a list of changes that are the basis for our release notes.  The message text implies that the content should be deleted, and sometimes people do indeed delete it. :-) 
This PR updates the messaging to indicate that the content is generated.
=> Internal: Update messaging in release notes script

qa/integration/specs/cli/keystore_spec.rb
[rn:skip]
Use the JDK selected by the environment variable `BUILD_JAVA_HOME` also to run the `logstash_keystore` tool from integration test.
The CI runs JDK matrix tests selecting the JDK by setting path values into `BUILD_JAVA_HOME`. When the `ci/integration_test.sh` runs  `keystore_spec.rb` it forks a process to execute the `logstash-keystore` tool which selects the JDK giving precedence to JAVA_HOME. The problem is that the CI ships with JDK `1.8.292` as system's JDK which have problem with cypher algorithm.  This PR sets `JAVA_HOME` before forking the tool, in this way also the tool runs with same JDK as the rest of the build.
This doesn't impact directly the user but the CI system. 
- sets JDK 1.8.292 as system's JDK (maybe use `sdk install java 8.0.292.hs-adpt`)
- set …
=> Use the JVM specified in the CI matrix environment also to run spawned proccesses

qa/integration/specs/cli/keystore_spec.rb
Clean backport of #12945 to `7.x` branch
Use the JVM specified in the CI matrix environment also to run spawned proccesses
logstash-keystore integration tests spawn a Java process, which by default uses the system JDK generally exposed with JAVA_HOME environment variable. It could be that this JDK is not the one selected with the build system variable BUILD_JAVA_HOME.
This commit uses the JDK defined in BUILD_JAVA_HOME if present.
(cherry picked from commit fa9adb4b864966ca1aa218e1bad9fa03a5047e32)
=> [backport 7.x] #12945 Use the JVM specified in the CI matrix environment also to run spawned proccesses

qa/integration/specs/cli/keystore_spec.rb
**Don't merge till `7.13.1` is released**
Clean backport of #12945 to `7.13` branch
Use the JVM specified in the CI matrix environment also to run spawned proccesses
logstash-keystore integration tests spawn a Java process, which by default uses the system JDK generally exposed with JAVA_HOME environment variable. It could be that this JDK is not the one selected with the build system variable BUILD_JAVA_HOME.
This commit uses the JDK defined in BUILD_JAVA_HOME if present.
(cherry picked from commit fa9adb4b864966ca1aa218e1bad9fa03a5047e32)
=>  [backport 7.13] #12945 Use the JVM specified in the CI matrix environment also to run spawned proccesses 

logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
Clean backport of #12952 to branch `7.x`
(cherry picked from commit aa8305f1d4b942c8c3d036cc95d4496b57e6bb6d)
----
Streamline the flow of logic avoiding nesting of if-s to make evident the good path vs the error conditions.
=> [backport 7.x]Refactoring of JavaKeyStore.getKeyStorePassword method to simplify if conditions (#12952)

rakelib/test.rake
[rn:skip]
The module LogStash::PluginManager requires the file `lib/pluginmanager/plugin_aliases.yml` is created,
which happens during the Gradle's 'copyPluginAlias' executed as part of Rake's 'bootstrap'.
This PR moves the require of the module close to its usage inside `plugins` tasks which already depends on `bootstrap` task.
Before this the `rake artifacts:all` failed
Same as Author's checklist
- 
```
andrea@kalispera logstash_andsel (master) $ rake artifact:all
rake aborted!
Errno::ENOENT: No such file or directory - /home/andrea/workspace/logstash_andsel/lib/pluginmanager/plugin_aliases.yml
/home/andrea/workspace/logstash_andsel/lib/pluginmanager/util.rb:25:in `load_aliases_definitions'
/home/andrea/workspace/logstash_andsel/lib/pluginmanager/util.rb:50:in `<module:PluginManager>' …
```
=> Fix dependency on plugin_alias.yml during `rake artifacts:all`

rakelib/test.rake
Clean backport of #12962 to `7.x` branch
(cherry picked from commit 8e62e8a01c3e8be7a0821b9eb088b8e4c0ffc064)
----
The module LogStash::PluginManager requires the file `lib/pluginmanager/plugin_aliases.yml` is created,
which happend during the Gradle's 'copyPluginAlias' executed as part of Rake's 'bootstrap'.
=> [backport 7.x] Fix dependency on plugin_alias.yml during `rake artifacts:all` (#12962)

Gemfile.template, logstash-core/spec/logstash/filters/base_spec.rb, logstash-core/spec/support/helpers.rb, x-pack/qa/integration/management/multiple_pipelines_spec.rb
update logstash-devutils dependency from 1.x to 2.x
More information on what's new in logstash-devutils 2.x can be found in the changelog: https://github.com/elastic/logstash-devutils/blob/master/CHANGELOG.md#200
=> bump devutils dependency to 2.x

lib/bootstrap/bundler.rb, rubyUtils.gradle, versions.yml
Version bump of JRuby.
Includes upstream fixes for ARM64 support.
Dependency update, release notes (since 9.2.16.0): 
https://www.jruby.org/2021/03/29/jruby-9-2-17-0.html
https://www.jruby.org/2021/06/08/jruby-9-2-18-0.html
JRuby 9.2.18.0 include JNR fixes for ARM64: https://github.com/jnr/jnr-ffi/issues/240 https://github.com/jnr/jnr-posix/pull/165 
(present in 9.2.17.0 but resolved in 9.2.18.0)
https://github.com/elastic/logstash/issues/12077 (unfortunately the auto-load fixes were not backported to RGs 3.1)
=> Deps: update JRuby to 9.2.18.0

docs/static/monitoring/monitoring-mb.asciidoc
[rn:skip] 
Removes tagged regions from monitoring docs. They were used to share content in the Stack Overview, and are no longer used.
=> Doc: Remove unused tagged regions

qa/integration/specs/cli/prepare_offline_pack_spec.rb
in preparation for JRuby 9.2.18.0 which includes a RGs update while 7.x is still using Bundler 1.17 (compared to master)
merging this would allow us for a clean backport in https://github.com/elastic/logstash/pull/12971
=> Test: handle a RGs warning from packing output

lib/bootstrap/bundler.rb, rubyUtils.gradle, versions.yml
Backport PR #12791 to 7.x branch. Original message: 
Version bump of JRuby.
Includes upstream fixes for ARM64 support.
Dependency update, release notes (since 9.2.16.0): 
https://www.jruby.org/2021/03/29/jruby-9-2-17-0.html
https://www.jruby.org/2021/06/08/jruby-9-2-18-0.html
JRuby 9.2.18.0 include JNR fixes for ARM64: https://github.com/jnr/jnr-ffi/issues/240 https://github.com/jnr/jnr-posix/pull/165 
(present in 9.2.17.0 but resolved in 9.2.18.0)
https://github.com/elastic/logstash/issues/12077 (unfortunately the auto-load fixes were not backported to RGs 3.1)
=> Backport PR #12791 to 7.x: Deps: update JRuby to 9.2.18.0

rakelib/compile.rake
This commit avoid to check fo rexistence of jar file sto decide if run or not gradle assemble,
basically because the output of assemble task is not only jars but also others, for example plugin-aliases.yml.
In this way the decision to execute or not is left the Gradle logic.
[rn:skip]
This PR avoid to check for existence of jar files in `logstash-core/lib/jars` to decide is run the process `gradlew assemble` as a task of the `rake artifact:all`. The motivation is due to the fact that assemble produces directly or indirectly more files than just those jars, for example it also transitively create the `plugin_aliases.yml` definitions. 
The responsibility of the choice to run or not `assemble` should stay in Gradle's side, becuase it has more clear vision of the dependencies.
Doesn't impact …
=> Fix acceptance test when run artifact:deb

build.gradle, spec/unit/plugin_manager/install_spec.rb
[rn:skip]
Adds test coverage for plugin manager when it installs aliased plugins
No impact for the user
-
=> Added test to cover the installation of aliased plugins

docs/static/best-practice.asciidoc
Co-authored-by: Sebastian <gentunian@users.noreply.github.com>
Doc: Add tip for how to see if a boolean field exists
Provides a work-around for checking to see if a boolean field exists (long standing issue)
- Relates #1867
https://logstash_12899.docs-preview.app.elstc.co/guide/en/logstash/master/tips.html#tip-filters
=> Doc: Add tip for checking for existing field

docs/static/best-practice.asciidoc
Co-authored-by: Sebastian <gentunian@users.noreply.github.com>
Co-authored-by: Karol Bucek <kares@users.noreply.github.com>
Backports #12899: Provides a work-around for checking to see if a boolean field exists to address a long-standing issue (#1867)
=> Doc: Add tip for checking for existing field (backport to 7.x)

docs/static/best-practice.asciidoc
Co-authored-by: Sebastian <gentunian@users.noreply.github.com>
Co-authored-by: Karol Bucek <kares@users.noreply.github.com>
Backports #12899: Provides a work-around for checking to see if a boolean field exists to address a long-standing issue (#1867)
=> Doc: Add tip for checking for existing field (backport to 7.13)

rubyUtils.gradle, versions.yml
- Deps: update JRuby to 9.2.19.0 (#12989)
=> [7.x] Deps: update JRuby to 9.2.19.0 (#12989)

.gitignore, build.gradle, lib/pluginmanager/util.rb, logstash-core/build.gradle, logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java, logstash-core/src/main/resources/org/logstash/plugins/AliasRegistry.yml, logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java, logstash-core/src/test/resources/org/logstash/plugins/AliasRegistry.yml, spec/unit/plugin_manager/util_spec.rb
Clean backport of #12841 to branch `7.x`
(cherry picked from commit 446dc7d906d74b2aaa900d3772d9433cc65c8bc8)
----
Remove hard coded alias definitions in favor of yaml descriptor file.
Introduce a single point of aliases definition (logstash-core/src/main/resources/org/logstash/plugins/AliasRegistry.yml),  checksum and copy it around to be used by Logstash and by Logstash's plugin management tool.
The descriptor yml file contains a checksum to verify it's not changed accidentally in a deployment of Logstash, if the verification phase fail Logstash avoid to start and plugin management tool avoid to operate.
The signing and copying around is managed by a specific Gradle task invoked during the build.
Co-authored-by: Ry Biesemeyer <yaauie@users.noreply.github.com>
Fixes #12831
=> [backport 7.x] Avoid hard-coded plugin alias definitions (#12841)

rakelib/compile.rake
Clean backport of #12975 to `7.x`
This commit avoid to check for existence of jar files to decide if run or not Gradle assemble,
basically because the outputs of assemble task are not only jars but also others files, for example plugin-aliases.yml.
In this way the decision to execute or not is left the Gradle logic.
(cherry picked from commit 3eaff3612d633f3f832a98ab654d906ce0aef39a)
=> [backport 7.x] Fix acceptance test when run artifact:all (#12975)

.gitignore, config/log4j2.properties, logstash-core/benchmarks/src/main/resources/log4j2-with-script.properties, logstash-core/benchmarks/src/main/resources/log4j2-without-script.properties, logstash-core/src/test/resources/log4j2-log-pipeline-test.properties, qa/integration/build.gradle, qa/integration/fixtures/persistent_queues/log4j2.properties, qa/integration/specs/pipeline_log_spec.rb
Clean backport of #12964 to branch `7.x`
Remove an useful dynamic creation of appender's log file which leverages the `log.format` property
also when it's explicit by the appender itself.
Log4j configuration leverages the placeholder `${sys:ls.log.format}` to compose the name of the log file.
This generates some not evident conflicts in log4j internals, these conflicts became evident when enabling the `pipeline.separate_logs` feature is enabled and the log4j appender definitions contains both json and plain format.
The problem is that under those circumstances the rollover of the log file doesn't happen.
This commit also add a test against the production log4j configuration, to avoid future regressions.
(cherry picked from commit a0774c4e76301a54e77544cfa1e617f4118af3f6)
=> [backport 7.x] Explicitate the type of log format in appender's names (#12964)

build.gradle, spec/unit/plugin_manager/install_spec.rb
Clean backport of #12967 to branch `7.x`
Added test to cover the installation of aliased plugins when exists a gem with same name but that's not a Logstash plugin.
In this case the alias is resolved to the original, skipping the gem retrieved from RubyGems.
(cherry picked from commit cafbf0315876d9cf5b796a88a50600700b107ae1)
=> [backport 7.x] Added test to cover the installation of aliased plugins (#12967)

logstash-core/lib/logstash/settings.rb, x-pack/lib/config_management/elasticsearch_source.rb, x-pack/spec/config_management/elasticsearch_source_spec.rb
When using Kibana's Central Management for Logstash, values for `pipeline.ordered` and `pipeline.ecs_compatibility` settings are now supported.
Brings `pipeline.ordered` and `pipeline.ecs_compatibility` settings into the supported set here on the Logstash side so that they will be respected when provided by a pipeline that is managed by Kibana's Central Management for Logstash. Currently, the Kibana UI does not support setting these in the pipeline editor, but allows unvalidated k/v settings through pipelines managed through its API.
This PR does _NOT_ include the necessary changes to Kibana's pipeline editor to make these UI-accessible (hint: [here?](https://github.com/elastic/kibana/blob/4a541883557bcee83baf09b2c0ddab702f780e45/x-pack/plugins/logstash/public/application/components/pipeli …
=> Allow per-pipeline config of ECS Compatibility mode via Central Management

logstash-core/src/main/java/org/logstash/log/PipelineRoutingAppender.java, logstash-core/src/main/java/org/logstash/log/PipelineRoutingFilter.java, qa/integration/build.gradle, qa/integration/specs/pipeline_log_spec.rb
Clean backport of #12965 to branch `7.x`
Avoid the creation of log4j routing appender for log events without the `pipeline.id` fishtag.
In this way no spurious log file named "pipeline_${ctx:pipeline.id}.log" and logs are not duplicated with main Logstash log file.
(cherry picked from commit 1d6a3e4bb3705d43f94e3c0c939c9467237a5ace)
=> [backport 7.x] Fix/log4j routing to avoid create spurious file (#12965)

logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
Fix Reflections stack traces when process yml files in classpath and debug is enabled (#12991)
Backport of #12991 to branch `7.x`
----
Adds a filter to Reflections library initialization so that when it scan "org.logstash.plugins" it includes only .class files and avoid to load and process AliasRegistry.yml and plugin_aliases.yml
Fixes #12992
(cherry picked from commit a6e9a6bcfd400377d0ceb1449f0cc8e18af60825)
=> [backport 7.x] Fix Reflections stack traces when process yml files in ... (#12991)

rakelib/compile.rake
[rn:skip]
Uses the OS defined path separator in Rake script to invoke the `gradlew` command. Without this the `sh('./gradlew assemble')` results in error when running `.\gradlew clean installDefaultGems`.
This fixes a problem that Windows developers could find, starting from #12975
On a Windows host run `.\gradlew clean installDefaultGems`
- 
```
Use `bundle info [gemname]` to see where a bundled gem is installed.
Building logstash-core using gradle
./gradlew assemble
'.' is not recognized as an internal or external command,
operable program or batch file.
> Task :installDefaultGems FAILED
#<Class:0x3a7b8619>: Command failed with status (1): [./gradlew assemble...]
create_shell_runner at C:/Users/andrea_selva/workspace/logstash/vendor/bundle/jruby/2.5.0/gems/rake-12.3.3/lib/rake/file_utils …
```
=> Use the OS separator to invoke gradlew from Rake script

bin/logstash.bat
Fixed Windows logstash.bat not setting exit code
This PR makes the Windows logstash.bat exit with the last `%ERRORLEVEL%` at the end, so that any error in running Logstash will get propagated back to the command line.
Before this change, logstash.bat would always exit with code 0 - success (when doing `cmd.exe /C logstash.bat`), even if the java.exe process exited with a non-zero code (e.g. due to Logstash throwing an error at runtime).
Without this change, abnormal exits from Logstash are not detected as such by an owning process (such as service wrappers NSSM or WinSW, or the Windows Task Scheduler). This means recovery actions (like restarting the process or sending a notification) will not get triggered.
_I use WinSW as a service wrapper to "cmd.exe /C logstash.bat", and it was …
=> Fix logstash.bat not setting exit code

rakelib/compile.rake
Clean backport of #13000 to branhc `7.x`
Uses the OS defined path separator in Rake script to invoke the gradlew command. Without this the sh('./gradlew assemble') results in error when running .\gradlew clean installDefaultGems.
(cherry picked from commit d2c68fc0f928cecb119b3ec417088ee192e558fe)
=> [backport 7.x]Use the OS separator to invoke gradlew from Rake script (#13000)

build.gradle, logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java, logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
[rn:skip]
Loads the production plugin_aliases.yml definition file and check that every alias has
a properly published gem on RubyGems.
- add delete of generated `plugin_aliases.yml` to Gradle's clean task
- fix task dependency for copyPluginAlias task
Before aliasing a plugin in production that plugin must have an empty gem, this test grant for this during the testing of Logstash.
-
=> Add unit test to grant that production aliases correspond to a published RubyGem

bin/logstash.bat
Clean backport #12948 to branch `7.x`
This PR makes the Windows logstash.bat exit with the last %ERRORLEVEL% at the end, so that any error in running Logstash will get propagated back to the command line.
Before this change, logstash.bat would always exit with code 0 - success (when doing cmd.exe /C logstash.bat), even if the java.exe process exited with a non-zero code (e.g. due to Logstash throwing an error at runtime).
(cherry picked from commit 1f9ef978364a2dfc0d3126679d72eb7dc4f0ae9d)
=> Fix logstash.bat not setting exit code (#12948)

logstash-core/lib/logstash/dependency_report.rb, tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/test/resources/expectedOutput.txt, tools/dependencies-report/src/test/resources/licenseMapping-conflicting.csv, tools/dependencies-report/src/test/resources/licenseMapping-good.csv, tools/dependencies-report/src/test/resources/licenseMapping-missing.csv, tools/dependencies-report/src/test/resources/licenseMapping-missingNotices.csv, tools/dependencies-report/src/test/resources/licenseMapping-missingUrls.csv, tools/dependencies-report/src/test/resources/licenseMapping-unacceptable.csv, tools/dependencies-report/src/test/resources/rubyDependencies.csv
This commit fix the source URL for UBI image to ensure that it stays
consistent with the URL generated in
https://artifacts.elastic.co/reports/dependencies/dependencies-current.html
The `sourceURL` column contains a pointer to the source code, which is optional for most dependencies,
but a requirement for some, such as the Red Hat Universal Base Image.
Run `ci/license_check.sh` and verify that `report.csv` includes the good URL
=> Fix UBI source URL

qa/integration/specs/fatal_error_spec.rb
[rn:skip]
FIxes cross-spec leak from "fatal error" integration specs
Because the "Fatal Error" specs specifically inject fatal errors during
execution, and do so by reacting to a "poison" event, the fatal error prevents
the poison event from being ACK'd in the underlying queue.
By specifying a one-off temporary data directory in these specs and cleaning up
after ourselves, we ensure that a PQ containing un-ACK'd events isn't leaked to
the next spec to run.
Resolves random flaky tests that were caused by being executed immediately after one of the "fatal error" tests.
In the following specific test run, the `Test Logstash configuration expands environment variables in all plugin blocks` spec immediately followed one of the "fatal error" specs, which had left a "poison" event containing the …
=> ispec: fix cross-spec leak from fatal error integration specs

qa/integration/specs/fatal_error_spec.rb
Backport PR #13002 to 7.x branch. Original message: 
[rn:skip]
FIxes cross-spec leak from "fatal error" integration specs
Because the "Fatal Error" specs specifically inject fatal errors during
execution, and do so by reacting to a "poison" event, the fatal error prevents
the poison event from being ACK'd in the underlying queue.
By specifying a one-off temporary data directory in these specs and cleaning up
after ourselves, we ensure that a PQ containing un-ACK'd events isn't leaked to
the next spec to run.
Resolves random flaky tests that were caused by being executed immediately after one of the "fatal error" tests.
In the following specific test run, the `Test Logstash configuration expands environment variables in all plugin blocks` spec immediately followed one of the "fatal error" …
=> Backport PR #13002 to 7.x: ispec: fix cross-spec leak from fatal error integration specs

config/logstash.yml, docs/index.asciidoc, docs/static/ecs-compatibility.asciidoc, logstash-core/lib/logstash/environment.rb, logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb, logstash-core/spec/conditionals_spec.rb, logstash-core/spec/logstash/java_pipeline_spec.rb, logstash-core/spec/logstash/plugin_spec.rb, qa/integration/fixtures/es_output_how_spec.yml
**PREVIEW:** https://logstash_12830.docs-preview.app.elstc.co/guide/en/logstash/master/ecs-ls.html
Sets ECS to on-by-default (`v1`, for now). This setting will again change to `v8` when ECS v8 goes into public Alpha in advance of the Stack 8.0.0 release.
This change makes ECS Compatibility modes on-by-default (as previously promised in https://github.com/elastic/logstash/issues/11623) and adds documentation about how to configure ECS Compatibility Modes at the plugin instance, pipeline, and global levels.
These docs are from the perspective of someone running (the unreleased, pre-alpha) Logstash 8, and a backport will need to be entirely re-worded from the perspective of Logstash 7.x to lead people _toward_ the upgrade.
If a user wants to "lock in" pre-ECS behaviour in 7.x, they can do at …
=> ecs: on-by-default plus docs

logstash-core/lib/logstash/dependency_report.rb, tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/test/resources/expectedOutput.txt, tools/dependencies-report/src/test/resources/licenseMapping-conflicting.csv, tools/dependencies-report/src/test/resources/licenseMapping-good.csv, tools/dependencies-report/src/test/resources/licenseMapping-missing.csv, tools/dependencies-report/src/test/resources/licenseMapping-missingNotices.csv, tools/dependencies-report/src/test/resources/licenseMapping-missingUrls.csv, tools/dependencies-report/src/test/resources/licenseMapping-unacceptable.csv, tools/dependencies-report/src/test/resources/rubyDependencies.csv
Backport PR #13008 to 7.x branch. Original message:
This commit fix the source URL for UBI image to ensure that it stays
consistent with the URL generated in
https://artifacts.elastic.co/reports/dependencies/dependencies-current.html
=> Backport PR #13008 to 7.x: Fix UBI source URL

logstash-core/lib/logstash/dependency_report.rb, tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/test/resources/expectedOutput.txt, tools/dependencies-report/src/test/resources/licenseMapping-conflicting.csv, tools/dependencies-report/src/test/resources/licenseMapping-good.csv, tools/dependencies-report/src/test/resources/licenseMapping-missing.csv, tools/dependencies-report/src/test/resources/licenseMapping-missingNotices.csv, tools/dependencies-report/src/test/resources/licenseMapping-missingUrls.csv, tools/dependencies-report/src/test/resources/licenseMapping-unacceptable.csv, tools/dependencies-report/src/test/resources/rubyDependencies.csv
Backport PR #13008 to 7.13 branch. Original message:
Fix UBI source URL (#13008)
This commit fix the source URL for UBI image to ensure that it stays
consistent with the URL generated in
https://artifacts.elastic.co/reports/dependencies/dependencies-current.html
=> Backport PR #13008 to 7.13: Fix UBI source URL

config/logstash.yml, docs/index.asciidoc, docs/static/ecs-compatibility.asciidoc
Backport subset of PR #12830 to 7.x branch. Original message: 
[rn:skip]
This change adds documentation about how to configure ECS Compatibility Modes at the plugin instance, pipeline, and global levels.
These docs are a 7.x-targeted backport of docs introduced in #12830 for 8.0, that have been re-worded from the perspective of Logstash 7.x to lead people _toward_ the upgrade.
If a user wants to "lock in" pre-ECS behaviour in 7.x, they can do at different levels so by:
1. declaring `ecs_compatibility => disabled` on each individual plugin; OR
2. declaring `pipeline.ecs_compatibility: disabled` in each pipeline's definition (`config/pipelines.yml` or Central Management)
3. declaring `pipeline.ecs_compatibility: disabled` in `config/logstash.yml` to provide a global default for pipelines. …
=> Backport PR #12830 to 7.x: ecs-compatibility docs

logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/api/commands/stats.rb, logstash-core/lib/logstash/api/modules/node_stats.rb, rakelib/plugins-metadata.json, x-pack/lib/filters/geoip/database_manager.rb, x-pack/qa/integration/monitoring/geoip_metric_spec.rb, x-pack/spec/filters/geoip/database_manager_spec.rb, x-pack/spec/filters/geoip/test_helper.rb
Add geoip database metrics to /node/stats 
This PR exposes geoip database metrics to Logstash localhost:9600/node/stats API
Sample output
```
"geoip" : {
"database" : {
“ASN”: {
"status" : "healthy",
"fail_check_in_days" : 0,
"download_at" : "2021-06-21T16:06:54+02:00"
},
“City”: {
"status" : "healthy",
"fail_check_in_days" : 0,
"download_at" : "2021-06-21T16:06:54+02:00"
}
},
"download" : {
"successes" : 15,
"failures" : 1,
"last_check_at" : "2021-06-21T16:07:03+02:00",
"status" : "succeeded"
}
}
```
Schema
```
geoip
database
ASN/CIty
status:
- init, initial CC database status
- healthy, using up-to-date EULA database
- to_be_expired, 25 days without calling service
- expired, 30 days without calling service
fail_check_in_days: nr. of days LS fail to call service since the last success …
```
=> Add geoip database metrics to /node/stats API

logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/api/commands/stats.rb, logstash-core/lib/logstash/api/modules/node_stats.rb, rakelib/plugins-metadata.json, x-pack/lib/filters/geoip/database_manager.rb, x-pack/qa/integration/monitoring/geoip_metric_spec.rb, x-pack/spec/filters/geoip/database_manager_spec.rb, x-pack/spec/filters/geoip/test_helper.rb
- Add geoip database metrics to /node/stats API (#13004)
=> [7.x] Add geoip database metrics to /node/stats API (#13004)

docs/static/monitoring/monitoring-apis.asciidoc
**PREVIEW:** https://logstash_13019.docs-preview.app.elstc.co/guide/en/logstash/master/node-stats-api.html
[rn:skip] 
Adds geoip database API to node stats documentation with reference back to Geoip filter plugin docs. 
Updates topic to current documentation standards for tagging and capitalization. 
Related: https://github.com/logstash-plugins/logstash-filter-geoip/pull/187
**ToDo:**
Add deep link to Database Metrics section after https://github.com/logstash-plugins/logstash-filter-geoip/pull/187 has been merged and published.
=> Doc: Add geoip database API to node stats

build.gradle, logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java, logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
Add unit test to grant that production aliases correspond to a published RubyGem (#12993)
Loads the production plugin_aliases.yml definition file and check that every alias has
a properly published gem on RubyGems.
Adds clean up of plugin_aliases.yml files
Fixed task dependency for copyPluginAlias
(cherry picked from commit a5f3153a8fc7273c179de884865bfa15940f4f28)
=> [backport 7.x]Add unit test to grant that production aliases correspond to a published gems  (#12993)

build.gradle
Revert "Change Gradle's :logstash-integration-tests:integrationTests task to depends on copyES (#12847) (#12868)"
This reverts commit 5287e7740e87dc0dafd70804b77ccc4a400b168a.
=> Emergency revert to make bump `7.15.0`

build.gradle
Revert "Change Gradle's :logstash-integration-tests:integrationTests task to depends on copyES (#12847) (#12868)"
This reverts commit 5287e7740e87dc0dafd70804b77ccc4a400b168a.
=> Emergency revert of #12847 for 7.14

x-pack/qa/integration/monitoring/geoip_metric_spec.rb
otherwise the integration spec causes a LogStash::ConfigurationError (on master due ecs_compatibility on by default):
`GeoIP Filter in ECS-Compatiblity mode requires a target when source
is not an ip sub-field, eg. [client][ip]`
=> Test: resolve integration failure due ECS mode

tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LogstashInstallation.java
Fixes the Logstash benchmarking tool to work with Logstash versions above 7.10.0
Starting with version 7.10.0 the name of LS packages changed, adding os and CPU architecture in the name. This change broke the downloading of those from the benchmarking tool. This commit fixes it, composing correctly the name, based on the version it has to download
Let the user to be able to launch the benchmark tool with any Logstash version
- create the jars for the tool `./gradlew assemble`
- `cd tools/benchmark-cli`
- run `java -cp 'build/libs/benchmark-cli.jar:build/libs/*' org.logstash.benchmark.cli.Main --workdir=/tmp/benchmark --testcase=baseline --distribution-version=7.12.0` and check the tool completes successfully
- 
Failure example:
```
andrea@kalispera benchmark-cli (master) $ java -cp …
```
=> Fix LS benchmarking tool to work with releases >= 7.10.0

tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LogstashInstallation.java
Clean backport of #13052 to branch `7.x`
----
Starting with version 7.10.0 the name of LS packages changed, adding os and CPU architecture in the name. This change broke the downloading of those from the benchmarking tool. This commit fixes it, composing correctly the name, based on the version it has to download.
(cherry picked from commit b722360ebda1322ba87ead83cec69f1d40bde8a8)
=> [backport 7.x] Fix LS benchmarking tool to work with releases >= 7.10.0 (#13052)

rakelib/plugins-metadata.json
follow-up on https://github.com/elastic/logstash/pull/12925 which: 
- added the `logstash-integration-elastic_enterprise_search` into meta-data
- while removing `logstash-output-elastic_app_search`
believe the removal is problematic since when generating the **plugin_version_docs.json** we end up with:
```json
// ...
"logstash-output-appsearch": {
"version": "1.0.0.beta1",
"from": "missing"
},
"logstash-output-elastic_app_search": {
"version": "1.2.0",
"from": "missing"
}
```
expected behavior is that the old **logstash-output-elastic_app_search** should not be in the generated json,
restoring the listing for logstash-output-elastic_app_search (this PR) makes the entry disappear in the generated json.
(note: restoring the listing with props flipped is how [integration plugins were …
=> Docs: keep elastic_app_search output meta-data

rakelib/plugins-metadata.json
- Docs: keep elastic_app_search output meta-data (#13048)
=> [7.x] Docs: keep elastic_app_search output meta-data (#13048)

rakelib/plugins-metadata.json
Backports the following commits to 7.14:
- Docs: keep elastic_app_search output meta-data (#13048)
=> [7.14] Docs: keep elastic_app_search output meta-data (#13048)

build.gradle
[rn:skip]
This PR moves the downloading of Elasticsearch and Filebeat artifacts, used in integration tests, to happen at Gradle's execution phase instead of configuration time. This let the configuration step to work also it the requested integration artifacts aren't yet published.
It has to be possible to run Gradle tasks related to package creation and running unit test also if the stack version defined in `versions.yml` is not yet available. In this case integration tests is admitted to fail.
Modify `versions.yml` locally to a version not yet published, for example `7.15.0` and try to run the unit tests `./gradlew :logstash-core:unitTests` and  `./gradlew :logstash-core:rubyTests`. Those should  work without downloading any Elasticserach package, check `build/` folder. Run integration …
=> Move retrieval of Stack version from Gradle's configuration to execution

qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb, qa/config/platforms.json, qa/vagrant/command.rb
This PR contains commits attempting to fix the broken acceptance tests:
* Fix regexes for plugin list tests. …
Fixes tests to support the plugin alias feature. This introduced a new format for
entries emitted by `bin/logstash-plugin list`:
eg
```
└── logstash-input-elastic_agent (alias)
```
This commit fixes the test to account for this change, and whitespace variances.
* Fix the set of test platforms used to run unix acceptance tests
Modernizes the list of OS's used in acceptance tests, to the most modern OS's available at https://app.vagrantup.com/elastic,. This removes the centos-6 platform from the build, which is past end-of-life and fails vagrant bootstrapping, causing the build to fail.
This is more of band-aid than anything - in the longer term, we should remove these vagrant …
=> [Test] Fix Unix acceptance tests

qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb, qa/config/platforms.json, qa/vagrant/command.rb
Backport PR #13071 to 7.x branch. Original message:
This PR contains commits attempting to fix the broken acceptance tests:
* Fix the set of test platforms used to run unix acceptance tests
Modernizes the list of OS's used in acceptance tests, to the most modern OS's available at https://app.vagrantup.com/elastic,. This removes the centos-6 platform from the build, which is past end-of-life and fails vagrant bootstrapping, causing the build to fail.
This is more of band-aid than anything - in the longer term, we should remove these vagrant based tests completely, and rely
on the build infrastructure to perform OS-based acceptance tests.
* Fix regexes for plugin list tests. …
Fixes tests to support the plugin alias feature. This introduced a new format for
entries emitted by …
=> Backport PR #13071 to 7.x: [Test] Fix Unix acceptance tests

qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb, qa/config/platforms.json, qa/vagrant/command.rb
Backport PR #13071 to 7.14. Original message:
This PR contains commits attempting to fix the broken acceptance tests:
* Fix the set of test platforms used to run unix acceptance tests
Modernizes the list of OS's used in acceptance tests, to the most modern OS's available at https://app.vagrantup.com/elastic,. This removes the centos-6 platform from the build, which is past end-of-life and fails vagrant bootstrapping, causing the build to fail.
This is more of band-aid than anything - in the longer term, we should remove these vagrant based tests completely, and rely
on the build infrastructure to perform OS-based acceptance tests.
* Fix regexes for plugin list tests. …
Fixes tests to support the plugin alias feature. This introduced a new format for
entries emitted by `bin/logstash-plugin …
=> Backport PR #13071 to 7.14: [Test] Fix Unix acceptance tests

x-pack/lib/filters/geoip/database_manager.rb
This is a disabled mode and is not required to copy databases to `path.data`
This PR points database path to the original vendor path.
`database_type` is either "ASN" or "City"
Fixed: #13072
=> GeoIP remove multiple databases copy in multiple instances

docs/static/troubleshoot/ts-kafka.asciidoc
[rn:skip] 
Adds new schema registry setting info from https://github.com/logstash-plugins/logstash-integration-kafka/pull/97 to the plugin troubleshooting section
**PREVIEW:** https://logstash_13073.docs-preview.app.elstc.co/guide/en/logstash/master/ts-plugins.html#ts-schema-registry
=> Doc: Add kafka schema registry setting to troubleshooting

docs/static/releasenotes.asciidoc
Forward port of 7.13.4 (#13061) release notes to branch `7.x`
=> Forward port of 7.13.4 release notes to 7.x

docs/static/releasenotes.asciidoc
Forward port of release notes for 7.13.3 (#13031) and 7.13.4 (#13061) to branch `7.14`
=> Forward port of release notes for 7.13.3 and 7.13.4 to 7.14

config/logstash.yml, docs/static/ecs-compatibility.asciidoc, logstash-core/lib/logstash/environment.rb, logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb, logstash-core/locales/en.yml, logstash-core/spec/logstash/plugin_spec.rb
REVERTS previously-merged breaking change in default value of `pipeline.ecs_compatibility`
As we close in on the availability of 8.0.0 alphas, we are reassessing which
breaking changes are _necessary_, and which are merely _desired_. And while
we would love to be in a world where ECS was on by default, and have put
substantial effort into designing an upgrade path that would be as simple as
possible, we have determined that the time may not be right to change the
default value out of under our users.
This change restores the default value for `pipeline.ecs_compatibility` to
`disabled`, ensuring pipelines will continue running in Logstash 8 as they have
in Logstash 7 without modification. We will still encourage our users to be
explicit about which behaviour they desire, and will revisit …
=> ecs_compatibility: revert breaking change; keep `disabled` as default for 8.0

docs/static/settings-file.asciidoc
Adds doc section for `pipeline.ecs_compatibility` setting.
- `7.10`
- `7.x`
While this copy already exists in the `--help` output for the logstash command-line executable, bringing it to the web documentation makes it more accessible.
Click through to [Docs Build](https://logstash_12421.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-settings-file.html#logstash-settings-file), or observe this handy screenshot:
#12305
=> doc: add pipeline.ecs_compatibility docs

docs/static/keystore.asciidoc
**PREVIEW:** https://logstash_12779.docs-preview.app.elstc.co/guide/en/logstash/master/keystore.html
[rn:skip] 
Fixes typo and adjusts wording for keystore doc introduced in a direct commit
General formatting and content cleanup
=> Doc:Fix typo and adjust keystore text

docs/static/settings-file.asciidoc
Backport PR #12421 to 7.x branch. Original message: 
Adds doc section for `pipeline.ecs_compatibility` setting.
- `7.10`
- `7.x`
While this copy already exists in the `--help` output for the logstash command-line executable, bringing it to the web documentation makes it more accessible.
Click through to [Docs Build](https://logstash_12421.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-settings-file.html#logstash-settings-file), or observe this handy screenshot:
#12305
=> Backport PR #12421 to 7.x: doc: add pipeline.ecs_compatibility docs

docs/static/settings-file.asciidoc
Backport PR #12421 to 7.14 branch. Original message: 
Adds doc section for `pipeline.ecs_compatibility` setting.
- `7.10`
- `7.x`
While this copy already exists in the `--help` output for the logstash command-line executable, bringing it to the web documentation makes it more accessible.
Click through to [Docs Build](https://logstash_12421.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-settings-file.html#logstash-settings-file), or observe this handy screenshot:
#12305
=> Backport PR #12421 to 7.14: doc: add pipeline.ecs_compatibility docs

build.gradle
Clean backport of #13042 to branch `7.13`
The Gradle's configuration of task should be as fast as possible and don't break the build.
This commit moves retrieval of Elastic Stack version from the remote registry to the execution phase of the tasks.
Also the tasks that depends on this has received the same change (downloadEs and check EsSHA), moving from configuration to execution phase.
Close #13030
(cherry picked from commit cef339ce57b726d6cb5e833dc82217f378b31d56)
=> [backport 7.13]Move retrieval of Stack version from Gradle's configuration to execution (#13042)

docs/static/dead-letter-queues.asciidoc, docs/static/persistent-queues.asciidoc, docs/static/resiliency.asciidoc
**PREVIEW:** https://logstash_12959.docs-preview.app.elstc.co/guide/en/logstash/master/resiliency.html
Expand documentation for the dead letter queue (DLQ) to help users understand its purpose and management
We have identified improvements for the DLQ (#10493), and those improvements are pending design, scoping, and prioritization. We can help users in the interim by better explaining the design intent and offering maintenance techniques to help them use DLQs more effectively. 
- Relates #12923
- Relates #10493
=> Doc: Enhance and expand DLQ docs

docs/static/releasenotes.asciidoc
Placeholder for 6.8.18 release notes
**PREVIEW:** https://logstash_13110.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-18.html
=> Doc: Add placeholder for release notes

Gemfile.jruby-2.5.lock.release, README.md, versions.yml
[rn:skip]
Bumps versions to the 6.8.19 on branch 6.8 so that future snapshot builds will indicate the correct next patch-level release version.
=> Bump 6.8.19

Gemfile.jruby-2.5.lock.release, versions.yml
[rn:skip]
Bumps versions to the 7.14.1 on branch 7.4 so that future snapshot builds will indicate the correct next patch-level release version.
=> Bump 7.14.1

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/faraday-em_http-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-em_synchrony-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-excon-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-httpclient-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-net_http-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-net_http_persistent-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-patron-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-rack-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/ruby2_keywords-NOTICE.txt
[rn:skip]
- Adds NOTICES files for some faraday submodules
- Align `licenseMapping.csv`
- checkout the branch
- run ` bin/dependencies-report --csv /tmp/deps.csv` is must be green, on `master` it currently fails
-
=> Added faraday-* and ruby2_keywords notices to licences list

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/faraday-em_http-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-em_synchrony-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-excon-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-httpclient-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-net_http-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-net_http_persistent-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-patron-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-rack-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/ruby2_keywords-NOTICE.txt
Clean backport of #13126  to `7.x` branch
(cherry picked from commit 542dce81a786cb85a8564ac8ec2938685f4f01ba)
=> [backport 7.x] Added faraday-* and ruby2_keywords notices to licences list (#13126)

docs/static/breaking-changes.asciidoc
**PREVIEW:** https://logstash_13130.docs-preview.app.elstc.co/guide/en/logstash/master/breaking-8.0.html
[rn:skip] 
Adds breaking changes noted in [8.0.0-alpha1 release notes](https://github.com/elastic/logstash/pull/13098) to breaking changes page
Updates `[float]` tags to `[discrete]`
No backports needed
=> Doc: Add breaking changes to breaking changes page

build.gradle, logstash-core/benchmarks/build.gradle, logstash-core/build.gradle, rubyUtils.gradle, tools/benchmark-cli/build.gradle, tools/dependencies-report/build.gradle, tools/ingest-converter/build.gradle
Clean backport of #13129 to branch `7.x`
----
Snakeyaml is used only in the build chain, and it's not packaged with Logstash
(cherry picked from commit a7f6c01a3a8ba960233c4f7437964de67605ea92)
=> [backport 7.x] Update Snakeyaml version to 1.29 (#13129)

build.gradle, logstash-core/benchmarks/build.gradle, logstash-core/build.gradle, rubyUtils.gradle, tools/benchmark-cli/build.gradle, tools/dependencies-report/build.gradle, tools/ingest-converter/build.gradle
backport of #13129 to branch `7.15`
----
Snakeyaml is used only in the build chain, and it's not packaged with Logstash
(cherry picked from commit a7f6c01a3a8ba960233c4f7437964de67605ea92)
=> [backport 7.15] Update Snakeyaml version to 1.29 (#13129)

docs/static/releasenotes.asciidoc
[rn:skip]
Add notice about aarch64 support availability for 7.14.
Updates instances of ARM64 to "aarch64 (ARM64) for consistency with other products and better SEO
=> Doc: Add aarch64 support to release notes

docs/static/releasenotes.asciidoc
[rn:skip] 
Forwardports #13132 to 7.x
=> Doc: Forwardport aarch64 support note (#13132) to 7.x release notes

docs/static/breaking-changes.asciidoc
[rn:skip] 
Relocates shared region tags to highlight 8.0.0 breaking changes
=> Doc: Move shared region tags for breaking changes to 8.0.0 content

logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
Minor code refactoring.
[rn:skip]
Changes locking on `plugin.ecs_compatibility` initialization to lock per plugin instead of globally.
The global lock is slightly confusing and should not be required, even a pipeline level lock would be an enhancement.
=> Refactor: avoid global mutex on ecs_compatibility

logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
- Refactor: avoid global mutex on ecs_compatibility (#13036)
=> Backport to 7.x: Refactor: avoid global mutex on ecs_compatibility (#13036)

x-pack/lib/filters/geoip/database_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb, x-pack/spec/filters/geoip/test_helper.rb
Fixed: #13108
Fix the configuration of  GeoIP `database` path that is overwritten to the default value in 7.13.4.
The `database` path is overwritten in the [last](https://github.com/elastic/logstash/pull/13076/files#diff-ab6d19a69e9916bb6e9ffed07fba608bb7670d410d01f8dd51387ffbd612072bR39) version 7.13.4
This PR respects user input and pointed the default *.mmdb database to the original vendor directory (plugin gem bundled)
```
input {
heartbeat {
message => '{"host": "55.159.212.43", "app": "barfoo", "amount": 82.95}'
interval => 10
}
}
filter {
json {
source => "message"
}
geoip {
source => "[host]"
target => "[server]"
database => $LS_HOME/vendor/bundle/jruby/2.5.0/gems/logstash-filter-geoip-7.1.3-java/vendor/GeoLite2-ASN.mmdb
}
}
output {
stdout { codec => rubydebug }
}
```
=> fix geoip `database` path got overwritten

config/log4j2.properties, qa/integration/specs/monitoring_api_spec.rb
LS' monitoring logging specs were failing, interestingly (initially) only one target failed.
After some adjusting to not assert stuff (log4j2 configuration) outside the specs' control both targets went :red_circle:.
The incriminating spec did not account for loading more libraries -> having more libraries explicitly configured e.g.
```properties
logger.apache_http_client.name = org.apache.http
logger.apache_http_client.level = fatal
```
[rn:skip]
Improves asserts in spec, resolved :red_circle: CI.
N/A
=> Test: better logging reconfiguration asserts

qa/integration/specs/monitoring_api_spec.rb
- Test: improve monitoring api logging asserts (#13164)
=> [7.x] Test: improve monitoring api logging asserts (#13164)

qa/integration/specs/monitoring_api_spec.rb
- Test: improve monitoring api logging asserts (#13164)
=> [7.15] Test: improve monitoring api logging asserts (#13164)

versions.yml
[rn:skip]
Updates bundled AdoptopenJDK to 11.0.12+7
=> Update bundled JDK to 11.0.12+7

versions.yml
Clean backport of #13185 to branch `7.x`
(cherry picked from commit ebb9e04d14666bc2400bf548dba8e89f425d6aad)
check RN in #13185
=> [backport 7.x]Update bundled JDK to 11.0.12+7 #13185

docs/static/releasenotes.asciidoc
Forward port of 7.14.1 release notes to `7.x` branch, from #13174
=> Forward port of 7.14.1 release notes, from PR #13174

docs/static/releasenotes.asciidoc
Forward port of 7.14.1 release notes to `7.15` branch, from #13174
=> Forward port of 7.14.1 release notes to 7.15 branch

Gemfile.jruby-2.5.lock.release, versions.yml
**merge after 7.14.1 is out**
[rn:skip]
Bumps versions to the 7.14.2 on branch 7.4 so that future snapshot builds will indicate the correct next patch-level release version.
=> Bump 7.14.2

versions.yml
**don't merge before 7.14.1 is out**
Clean backport of #13185 to `7.14` branch
(cherry picked from commit ebb9e04d14666bc2400bf548dba8e89f425d6aad)
check RN in #13185
=> [backport 7.14] Update bundled JDK to 11.0.12+7 (#13185)

Gemfile.template
Remove dependencies that are no longer used and outdated.
- atomic gem was [manually pinned in LS](https://github.com/elastic/logstash/commit/cbbfcd42c2d68abbecbb292bc28723784b903f0e) despite being a plugin dependency
* the issue it was supposed to resolve is no longer relevant (https://github.com/elastic/logstash/issues/9194)
- builder gem was introduced with the [plugin manager work](https://github.com/elastic/logstash/commit/12cfa69215e186bcdf39006e8964f6fcbe769942#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR10) ... yet wasn't used
* unable to find any `Builder` usage in LS or plugins themselves
[rn:skip]
Removes unnecessary dependencies.
=> Deps: drop old and unused gem dependencies

.github/ISSUE_TEMPLATE/bug.md, bin/logstash.lib.sh, bin/setup.bat, docs/static/jvm.asciidoc, qa/acceptance/spec/shared_examples/installed_with_jdk.rb, qa/docker/shared_examples/container.rb, qa/integration/services/logstash_service.rb, qa/integration/specs/cli/keystore_spec.rb, qa/integration/specs/cli/prepare_offline_pack_spec.rb, x-pack/ci/integration_tests.sh
Logstash's  launch script support `LS_JAVA_HOME` as an override of environment variable over `JAVA_HOME`. 
It's the path to an installed JDK to be used to launch Logstash's service and support tools.
`JAVA_HOME` is going to be removed, however if `LS_JAVA_HOME` is not specified then Logstash still looks for `JAVA_HOME`.
This PR modifies the launch scripts to take care of the `LS_JAVA_HOME` giving precedence over the `JAVA_HOME`, which is still used it the first is not found.
The existing `JAVA_HOME` is an environment variable globally used by all JVM applications present on a host.
With the introduction of `LS_JAVA_HOME` the user is able to customize the JDK used by Logstash without changing the global `JAVA_HOME`. It introduces a layer of separation, permitting a more fine grained …
=> Introduce LS_JAVA_HOME environment variable

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/rexml-NOTICE.txt
[rn:skip]
- Adds NOTICES files for `rexml` modules
- Align `licenseMapping.csv`
No impact for final user
- checkout the branch
- run ` bin/dependencies-report --csv /tmp/deps.csv` is must be green, on `master` it currently fails
=> Added rexml notice to license list

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/rexml-NOTICE.txt
Clean backport of #13209 to branch `7.x`
(cherry picked from commit 6ed2eea890e9af334af39ba63541ab58c9f8e7bc)
=> [backport 7.x] Added rexml notice to license list (#13209)

.github/ISSUE_TEMPLATE/bug.md, bin/logstash.lib.sh, bin/setup.bat, docs/static/jvm.asciidoc
Deprecate the usage of `JAVA_HOME` preferring `LS_JAVA_HOME`
Simply print deprecation notices on stdout when Logstash is starting with `JAVA_HOME` instead of `LS_JAVA_HOME`
Helps the user to migrate from `JAVA_HOME` to `JAVA_HOME`
-
=> Deprecate JAVA_HOME preferring LS_JAVA_HOME

bin/logstash.lib.sh, bin/setup.bat, docs/static/jvm.asciidoc, qa/acceptance/spec/shared_examples/installed_with_jdk.rb, qa/docker/shared_examples/container.rb, qa/integration/services/logstash_service.rb, qa/integration/specs/cli/keystore_spec.rb, qa/integration/specs/cli/prepare_offline_pack_spec.rb, x-pack/ci/integration_tests.sh
Logstash's launch script support LS_JAVA_HOME as an override of environment variable over JAVA_HOME.
It's the path to an installed JDK to be used to launch Logstash's service and support tools.
JAVA_HOME is going to be removed, however if LS_JAVA_HOME is not specified then Logstash still looks for JAVA_HOME.
Backport of #13204 #13207 to `7.x` branch
=> [backport 7.x] Use LS_JAVA_HOME in favor of JAVA_HOME #12725

.github/ISSUE_TEMPLATE/bug.md, bin/logstash.lib.sh, bin/setup.bat, docs/static/jvm.asciidoc, qa/acceptance/spec/shared_examples/installed_with_jdk.rb, qa/docker/shared_examples/container.rb, qa/integration/specs/cli/prepare_offline_pack_spec.rb
**Don't backport to 7.x**
Logstash's launch script support LS_JAVA_HOME and abandon the JAVA_HOME.
It's the path to an installed JDK to be used to launch Logstash's service and support tools.
JAVA_HOME is not anymore looked at, only LS_JAVA_HOME.
Removes the usage of JAVA_HOME completely, that environment variable is not anymore used for JDK path resolution.
Updated all the Logstash launching scripts to use only LS_JAVA_HOME as environment variable to
determine the JDK to use to launch Logstash. JAVA_HOME is abandoned for this job.
Already with PR #13204 `JAVA_HOME` was considered deprecated, this is important for the user because let them to separate JDKs for each JVM process, without implicit interference with the global `JAVA_HOME`.
- [] ~~I have commented my code, particularly in …
=> Removed JAVA_HOME using only LS_JAVA_HOME

x-pack/lib/filters/geoip/database_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb
Fixed: #13208
Fix shutdown error when using an external GeoIP DB
Fix the nil exception in shutdown when using external geoip database
The error prevents the running pipelines from shutting down in the correct order, resulting in a stalled shutdown because of in-flight events.
1. checkout this branch
2. start Logstash with
```
input {
beats {
port => 3001
}
}
filter {
geoip {
source => "message"
database => "/your/local/db/GeoLite2-City.mmdb"
}
}
output {
stdout { codec => rubydebug }
}
```
3. shutdown Logstash and you should see no error
-
=> fix geoip with external DB shutdown error

x-pack/lib/filters/geoip/database_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb
- fix geoip external DB shutdown nil exception (#13224)
=> [7.x] fix geoip external DB shutdown nil exception (#13224)

x-pack/lib/filters/geoip/database_manager.rb, x-pack/spec/filters/geoip/database_manager_spec.rb
**Do not merge until 7.15 release**
- fix geoip external DB shutdown nil exception (#13224)
=> [7.15] fix geoip external DB shutdown nil exception (#13224)

docs/static/releasenotes.asciidoc
**PREVIEW: https://logstash_13139.docs-preview.app.elstc.co/guide/en/logstash/7.15/logstash-7-15-0.html**
DIFF from **7.14** (7.14.1 release pending atm): https://github.com/elastic/logstash/compare/7.14...7.15
**NOTE:** DO NOT MERGE UNTIL 1 DAY BEFORE RELEASE (Sep 20th)
=> Release notes for 7.15.0

Gemfile.jruby-2.5.lock.release, README.md, versions.yml
[rn:skip]
Bumps versions to the `6.8.20` on branch `6.8` so that future snapshot builds will indicate the correct next patch-level release version.
=> Bump version 6.8.20

docs/static/configuration.asciidoc
[rn:skip] 
Updates docs with info about date math in conditionals and provides a workaround example.
Brings topic up to current documentation standards for heading capitalization and tagging
Backports #13199 to 7.x
=> Doc: Add note and example for date math in conditionals to 7.x

docs/static/configuration.asciidoc
[rn:skip] 
Updates docs with info about date math in conditionals and provides a workaround example.
Brings topic up to current documentation standards for heading capitalization and tagging
Backports #13199 to 7.15
=> Doc: Add note and example for date math in conditionals to 7.15

Gemfile.jruby-2.5.lock.release, versions.yml
[rn:skip]
Bumps versions to the `7.15.1` on branch `7.15`
=> bump 7.15.1

versions.yml
**Don't merge before 7.15.0 is out**
Clean backport of #13185 to `7.15` branch
(cherry picked from commit ebb9e04d14666bc2400bf548dba8e89f425d6aad)
check RN in #13185
=> [backport 7.15]Update bundled JDK to 11.0.12+7 (#13185)

qa/integration/services/kafka_setup.sh
Backport PR #13248 to 7.15 branch. Original Message:
Fix kafka download link for integration tests
(cherry picked from commit aa1aa8e)
=> Backport PR#13248 to 7.15: Fix kafka download link for integration tests

qa/integration/services/kafka_setup.sh
Backport PR #13248 to 7.x branch. Original Message:
Fix kafka download link for integration tests
(cherry picked from commit aa1aa8e)
=> Backport PR#13248 to 7.x: Fix kafka download link for integration tests

config/logstash.yml, docker/data/logstash/env2yaml/env2yaml.go, x-pack/lib/filters/geoip/database_manager.rb, x-pack/lib/filters/geoip/download_manager.rb, x-pack/lib/filters/geoip/extension.rb, x-pack/lib/x-pack/logstash_registry.rb, x-pack/spec/filters/geoip/download_manager_spec.rb
- geoip integrate air-gapped bootstrap script (#13104)
=> [7.x] geoip integrate air-gapped bootstrap script (#13104)

config/logstash.yml, docker/data/logstash/env2yaml/env2yaml.go, x-pack/lib/filters/geoip/database_manager.rb, x-pack/lib/filters/geoip/download_manager.rb, x-pack/lib/filters/geoip/extension.rb, x-pack/lib/x-pack/logstash_registry.rb, x-pack/spec/filters/geoip/download_manager_spec.rb
- geoip integrate air-gapped bootstrap script (#13104)
=> [7.15] geoip integrate air-gapped bootstrap script (#13104)

tools/release/generate_release_notes.rb
Fixed: #13118
This commit avoids duplication of header and index when rerunning the script.
The content should append below `coming[x.y.z]`
=> improve release note to avoid overwriting

tools/release/generate_release_notes.rb
- avoid duplication of heading and index entry in release notes (#13192)
=> [7.x] avoid duplication of heading and index entry in release notes (#13192)

tools/release/generate_release_notes.rb
- avoid duplication of heading and index entry in release notes (#13192)
=> [7.15] avoid duplication of heading and index entry in release notes (#13192)

docs/include/attributes-ls.asciidoc, docs/include/attributes-lsplugins.asciidoc, docs/index.asciidoc
[rn:skip] 
Adds and links shared attribute file for accurately stating ecs default status.
We can add/update text related to ecs defaults (or other info we want to write once and use multiple places). Then, we can  reference it by calling the attribute. In this case `{ecs-default}`.
**Important:** This work requires a corresponding change for the Versioned Plugin Reference.
=> Doc: Add shared attribute for messaging ecs default info

docker/data/golang/Dockerfile, x-pack/spec/filters/geoip/download_manager_spec.rb
- update golang image to 1.17.1(#13260) (#13260)
=> [7.15] update golang image to 1.17.1(#13260) (#13260)

docker/data/golang/Dockerfile, x-pack/spec/filters/geoip/download_manager_spec.rb
- update golang image to 1.17.1(#13260) (#13260)
=> [7.x] update golang image to 1.17.1(#13260) (#13260)

docker/data/golang/Dockerfile
[rn:skip] 
Update golang image from 1.8 to 1.17.1 to get rid of SSL verification issue
Disable geoip download manager test to silent Faraday::SSLError certificate verify failed
A follow issue will replace Faraday lib with Manticore in download_manager
Allow jenkins to build snapshot image
original PR: https://github.com/elastic/logstash/pull/13260
=> update golang image

lib/bootstrap/bundler.rb, lib/pluginmanager/install.rb, spec/unit/bootstrap/bundler_spec.rb, spec/unit/plugin_manager/install_spec.rb, spec/unit/plugin_manager/util_spec.rb
- unlock ecs_compatibility_support version in plugin update (#13218)
=> [7.x] unlock ecs_compatibility_support version in plugin update (#13218)

lib/bootstrap/bundler.rb, lib/pluginmanager/install.rb, spec/unit/bootstrap/bundler_spec.rb, spec/unit/plugin_manager/install_spec.rb, spec/unit/plugin_manager/util_spec.rb
- unlock ecs_compatibility_support version in plugin update (#13218)
=> [7.15] unlock ecs_compatibility_support version in plugin update (#13218)

spec/unit/plugin_manager/util_spec.rb
[rn:skip] 
tests from https://github.com/elastic/logstash/pull/13218 are flickering
remove the untouchable `source` that fail to provide gem dependency
`Gem.sources` is a static setting across the project. As the new test cases fetch the dependencies from internet, a fake/ mock sources fail to provide the information, thus fail the tests.
The jenkins tests failed [[7.x]](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request/3906/) [[7.15]](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request/3907/)
-
=> Fix plugin manager test that fail to fetch dependency 

spec/unit/plugin_manager/util_spec.rb
- Fix plugin manager test that fail to fetch dependency (#13270)
=> [7.x] Fix plugin manager test that fail to fetch dependency (#13270)

spec/unit/plugin_manager/util_spec.rb
- Fix plugin manager test that fail to fetch dependency (#13270)
=> [7.15] Fix plugin manager test that fail to fetch dependency (#13270)

docs/index.asciidoc, docs/static/mem-queue.asciidoc, docs/static/resiliency.asciidoc
[rn:skip] 
Adds topic with considerations and config info related to in-memory queue. This approach facilitates easier comparison and makes info on par with PQ info. 
Users need more info on sizing the internal memory queue and need to know that settings are per pipeline.
Related: #13232 
**PREVIEW:** https://logstash_13246.docs-preview.app.elstc.co/guide/en/logstash/master/memory-queue.html
=> Doc: Add topic and expand info for in-memory queue

logstash-core/logstash-core.gemspec, x-pack/lib/filters/geoip/download_manager.rb, x-pack/spec/filters/geoip/download_manager_spec.rb
Fix GeoIP database service SSL verification error
- The certificate cross-signed by the expired DST Root CA X3 failed the verification since 30/9
- replace http client with Manticore that does not depend on jruby-openssl
Faraday, HTTP client lib, is replaced by Manticore as the former depends on [jruby-openssl](https://github.com/jruby/jruby-openssl/issues/236) that cause the underlying SSL error. 
Pipelines that use logstash-geoip-filter with MaxMind EULA database have to check updates regularly. After 30 consecutive days of failing updates, the pipelines stop due to the license requirement.
run with the following config should show no error
```
input {
heartbeat {
message => '{"host": "55.159.212.43", "app": "barfoo", "amount": 82.95}'
interval => 10
}
}
filter {
json {
source => …
```
=> replace Faraday with Manticore to get rid of jruby-openssl verification error

logstash-core/logstash-core.gemspec, x-pack/lib/filters/geoip/download_manager.rb, x-pack/spec/filters/geoip/download_manager_spec.rb
- Replace Faraday to Manticore to get rid of jruby-openssl verification error of Let's Encrypt cross-signed DST Root CA X3 (#13273)
=> [7.15] Replace Faraday to Manticore to get rid of jruby-openssl verification error of Let's Encrypt cross-signed DST Root CA X3 (#13273)

logstash-core/logstash-core.gemspec, x-pack/lib/filters/geoip/download_manager.rb, x-pack/spec/filters/geoip/download_manager_spec.rb
- Replace Faraday to Manticore to get rid of jruby-openssl verification error of Let's Encrypt cross-signed DST Root CA X3 (#13273)
=> [7.x] Replace Faraday to Manticore to get rid of jruby-openssl verification error of Let's Encrypt cross-signed DST Root CA X3 (#13273)

.ci/java-versions.properties
Add ability to pull the version used to build java from the logstash repo, rather
than rely on system Java. Previously, builds would use JAVA_HOME, now this setting
is ignored in Logstash (and by extension, parts of the Logstash build), which was causing
variations in the version of Java used to build Logstash, including the use of Java 8,
which the Logstash team would like to remove support for.
Relates: elastic/infra#32818
=> Add java version parameterization to Logstash builds

rubyUtils.gradle, versions.yml
Version bump of JRuby to latest in 9.2 series.
Update JRuby to 9.2.20.0
Dependency update, release notes: https://github.com/jruby/jruby/releases/tag/9.2.20.0
=> Deps: update JRuby to 9.2.20.0

devtools/backport, devtools/create_pr, lib/pluginmanager/templates/codec-plugin/README.md, lib/pluginmanager/templates/filter-plugin/README.md, lib/pluginmanager/templates/input-plugin/README.md, lib/pluginmanager/templates/output-plugin/README.md, logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb, logstash-core/benchmarks/build.gradle, logstash-core/build.gradle, logstash-core/lib/logstash-core/version.rb, logstash-core/lib/logstash/version.rb, tools/benchmark-cli/README.md, tools/benchmark-cli/build.gradle, tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/ui/UserInput.java, tools/benchmark-cli/src/test/java/org/logstash/benchmark/cli/MainTest.java, tools/dependencies-report/README.md, tools/dependencies-report/build.gradle, tools/ingest-converter/build.gradle, tools/logstash-docgen/README.md, tools/logstash-docgen/lib/logstash/docgen/github_generator.rb, tools/logstash-docgen/lib/logstash/docgen/parser.rb, x-pack/spec/filters/geoip/download_manager_spec.rb
This PR changes all references of the "master" branch to "main", but only for logstash related repos, and outside of the "docs" repo (which will be handled in a separate PR.
More on this effort can be read here: https://github.com/elastic/logstash/issues/12052
=> rename references of master branch to main branch

docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13373.docs-preview.app.elstc.co/guide/en/logstash/8.0/logstash-8-0-0-beta1.html
=> Release notes for 8.0.0-beta1

Gemfile.template
Fix a broken `rake artifact:deb` (due freshly minted :gem:  fpm 1.14.0)
[rn:skip]
Locks a build dependency - used for creating deb packages.
N/A
- https://github.com/jordansissel/fpm/issues/1854
=> Build: lock fpm to 1.13.x to avoid dep packaging issues using 1.14.0

Gemfile.template
[rn:skip]
fpm was pinned to 1.13.x since 1.14.0 didn't allow creating packages under certain conditions through the api (see more at https://github.com/jordansissel/fpm/issues/1854)
This prevented our build from creating Logstash debian packages.
(with jruby 9k on the PATH)
`rake artifact:deb`
- Relates https://github.com/jordansissel/fpm/issues/1854
- Relates: https://github.com/elastic/logstash/pull/13400
=> Relax fpm version constraint after bug fix fpm#1856

x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb, x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
[rn:skip] 
With #13308 configuration namespace that started with `http.` was renamed to `api.`, this commit fix a usage left behind.
Use the new `api.enabled` setting in one place instead of the deprecated `http.enable`.
Avoid polluting Logstash logs with warning messages like:
```
[WARN ][logstash.settings        ] The value of setting `api.enabled` has been queried by its deprecated alias `http.enabled`. Code should be updated to query `api.enabled` instead
```
-
=> Fixes a usage of deprecated 'http.enabled' to the new 'api.enabled'

logstash-core/lib/logstash/util.rb, logstash-core/src/main/java/org/logstash/util/UtilExt.java
[rn:skip]
When reporting stalled threads (e.g. an input thread) they usually have a meaningful Java thread name, these changes will cause the Java thread name to be reported (on `PipelineRepoter#to_hash`).
N/A
=> Refactor: report Java thread name in thread info

logstash-core/src/main/java/org/logstash/secret/store/SecretStoreFactory.java
which causes a redundant Full GC while Logstash is starting
[rn:skip]
Internal cleanup - avoid triggering GC manually.
N/A
=> Refactor: avoid futile attempt to gc a string quickly

x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb, x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Clean backport to `8.0` of #13380
=> [backport 8.0]Fixes a usage of deprecated 'http.enabled' #13380

x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb, x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Clean backport of #13380 to branch `7.16`
(cherry picked from commit 88c80ebb199122efdbf9475788aa072ada22ad91)
=> [backport 7.16]Fixes a usage of deprecated 'http.enabled' to the new 'api.enabled' (#13380)

docs/static/breaking-changes.asciidoc
Add removal of JAVA_HOME to 8.0 breaking changes
Add java 11 minimum to breaking changes
Backport target: 8.0
**PREVIEW:** https://logstash_13376.docs-preview.app.elstc.co/guide/en/logstash/master/breaking-8.0.html
=> Doc: Add breaking changes

x-pack/spec/filters/geoip/download_manager_spec.rb
[rn:skip]
Fixes 7.16 branch build to reflect changes to the default branch name in the geoip filter repository
None. Fixed build only, release artifacts unaffected.
Related: #13301
=> propagate master/main branch rename for geoip filter (7.16)

x-pack/spec/filters/geoip/download_manager_spec.rb
[rn:skip]
Fixes 8.0 branch build to reflect changes to the default branch name in the geoip filter repository
None. Fixed build only, release artifacts unaffected.
Related: #13301
=> Master to main references 8.0

config/logstash.yml, docs/static/breaking-changes.asciidoc, docs/static/ecs-compatibility.asciidoc, logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/environment.rb, logstash-core/lib/logstash/java_pipeline.rb, logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb, logstash-core/locales/en.yml, logstash-core/spec/logstash/plugin_spec.rb
Backport PR #13391 to 8.0 branch. Original message: 
[breaking] The `pipeline.ecs_compatibility` setting now defaults to `v8`, causing all plugins that implement an ECS compatibility mode to default to operating with `ecs_compatibility => v8`.
Effectively reverts #13080, making the _default_ ECS compatibility mode `v8` for Logstash 8, and adds INFO-level logging for each pipeline to indicate in which mode its plugins will be run.
This the final step of a large and ongoing effort to provide better support for the Elastic Common Schema, detailed in #11623. In #13080 we had back-tracked making the breaking change out of an abundance of caution, but have since decided to move forward with it.
There are a number of plugins that ship with Logstash and have ECS modes, that do NOT yet have modes …
=> Backport PR #13391 to 8.0: ECS on by default for Logstash 8, again

docs/static/persistent-queues.asciidoc, docs/static/pipeline-pipeline-config.asciidoc
[rn:skip]
Expands persistent queue doc to explain how pipeline-to-pipeline configurations can benefit from PQs. 
Adds link from pipeline-to-pipeline doc to PQ doc
Related: #13173
**PREVIEW:** https://logstash_13319.docs-preview.app.elstc.co/guide/en/logstash/master/persistent-queues.html#pq-pline-pline
=> Doc: Expand PQ content for pipeline-pipeline

docs/static/releasenotes.asciidoc
Co-authored-by: Karen Metts <karen.metts@elastic.co>
Port of 7.15.1 release notes (#13295) for 7.16
[rn:skip]
=> Forward Port: Release notes for 7.15.1 (#13295)

versions.yml
Backport PR #13437 to 8.0 branch. Original message: 
None
=> Backport PR #13437 to 8.0: Update bundled JDK to 11.0.13+8

versions.yml
Backport PR #13437 to 7.16 branch. Original message: 
None
=> Backport PR #13437 to 7.16: Update bundled JDK to 11.0.13+8

docker/Makefile, qa/docker/fixtures/multiple_pipelines/pipelines/basic2.cfg, qa/docker/patches/excon/unix_socket.rb, qa/docker/shared_examples/container.rb, qa/docker/shared_examples/container_config.rb, qa/docker/shared_examples/container_options.rb, qa/docker/spec/spec_helper.rb, qa/docker/spec/ubi8/container_spec.rb
This commit contains numerous fixes to improve the stability of the docker integration tests
* Patch Excon::UnixSocket
Socket.new running on arm64 on Ubuntu 18.04, causes an immediate SIGSEGV error and crash on
that OS, and, as far as I can tell, only that OS. `TCPSocket.new`,`UDPSocket.new` and
`UNIXSocket.new` do not. This commit patches the UnixSocket of the Excon library to
do the absolute simplest thing possible to avoid this error.
* Ensure that container is deleted even if #kill fails
* Add extra waits to handle the incremental way the payload returned by the monitoring
API increases as logstash starts up and pipelines load.
* Use pyenv to ensure the same version of python is used across different jenkins workers
* Add container logs to help diagnose failed test.
* Update the …
=> Docker integration tests stability improvements

Gemfile.jruby-2.5.lock.release
NOTE: there's 3 ECS related plugins updates pending that I am aware of (imap input, http filter, )
[rn:skip]
Updates all plugin dependencies
This includes recent plugin pushes with ECS compatibility support (these were not part of beta1).
With the recent flip for 8.0 to have ECS on by default, this impacts the user xp in a positive way.
=> Deps: bump lock file for 8.0.0

logstash-core/lib/logstash/patches/puma.rb
Here we're emulating the [fallback logic](https://github.com/puma/puma/blob/v5.5.2/lib/puma/server.rb#L169-L192) just like it would happen on JRuby < 9.2.18.0.
The only consequence with the dummy `closed_socket?` implementation seems to be [stopping a request early](https://github.com/puma/puma/blob/v5.5.2/lib/puma/request.rb#L36).
Please note that the `closed_socket?` implementation [was slightly different](https://github.com/puma/puma/blob/4-3-stable/lib/puma/server.rb#L132) on Puma 4.x, however under JRuby, 4.x always uses the dummy fallback [due the `RUBY_PLATFORM =~ /linux/` check](https://github.com/puma/puma/blob/4-3-stable/lib/puma/server.rb#L105) (`RUBY_PLATFORM` returns `"java"` on JRuby).
[rn:skip]
Patches around an upstream (JNR) bug which surfaces under ARM64.
Usable AARCH64 …
=> Fix: patch Puma around a JRuby ARM64 bug

rakelib/artifacts.rake
[rn:skip]
Excludes unused testing artifacts from vendored `rubyzip` dependency, slightly reducing the size and surface-area of distributed artifacts. 
Backport targets: `8.0`, `7.16`
While the rubyzip testing fixtures are not on the load-path and inaccessible to the logstash process, some of the files they contain are occasionally picked up by automated scans. They are removed upstream in later releases of rubyzip (see: https://github.com/rubyzip/rubyzip/pull/405), but for now we can exclude them from propagating into our distributed artifacts.
- ~[ ] I have added tests that prove my fix is effective or that my feature …
=> artifacts: exclude unused rubyzip test files from distributions

logstash-core/lib/logstash/patches/puma.rb
**Backport PR #13447 to 8.0 branch.**
Here we're emulating the [fallback logic](https://github.com/puma/puma/blob/v5.5.2/lib/puma/server.rb#L169-L192) just like it would happen on JRuby < 9.2.18.0.
The only consequence with the dummy `closed_socket?` implementation seems to be [stopping a request early](https://github.com/puma/puma/blob/v5.5.2/lib/puma/request.rb#L36).
Please note that the `closed_socket?` implementation [was slightly different](https://github.com/puma/puma/blob/4-3-stable/lib/puma/server.rb#L132) on Puma 4.x, however under JRuby, 4.x always uses the dummy fallback [due the `RUBY_PLATFORM =~ /linux/` check](https://github.com/puma/puma/blob/4-3-stable/lib/puma/server.rb#L105) (`RUBY_PLATFORM` returns `"java"` on JRuby).
[rn:skip]
Patches around an upstream (JNR) bug which …
=> Backport PR #13447 to 8.0: Fix: patch Puma around a JRuby ARM64 bug

.github/ISSUE_TEMPLATE/doc-request.md
When users open issues in the logstash repo, they can choose from several issue templates. Even though there is an option to open a blank issue at the bottom of the page, it can be easily overlooked. This PR adds a github template for adding a documentation issue. 
Added benefit: We can automatically assign a `docs` label to fast track triage. 
**ToDo**
=> Add template for creating documentation issues

logstash-core/lib/logstash/patches/puma.rb
**Backport PR #13447 to 7.16 branch.**
Here we're emulating the [fallback logic](https://github.com/puma/puma/blob/v5.5.2/lib/puma/server.rb#L169-L192) just like it would happen on JRuby < 9.2.18.0.
The only consequence with the dummy `closed_socket?` implementation seems to be [stopping a request early](https://github.com/puma/puma/blob/v5.5.2/lib/puma/request.rb#L36).
Please note that the `closed_socket?` implementation [was slightly different](https://github.com/puma/puma/blob/4-3-stable/lib/puma/server.rb#L132) on Puma 4.x, however under JRuby, 4.x always uses the dummy fallback [due the `RUBY_PLATFORM =~ /linux/` check](https://github.com/puma/puma/blob/4-3-stable/lib/puma/server.rb#L105) (`RUBY_PLATFORM` returns `"java"` on JRuby).
[rn:skip]
Patches around an upstream (JNR) bug …
=> Backport PR #13447 to 7.16: Fix: patch Puma around a JRuby ARM64 bug

ci/acceptance_tests.sh, ci/docker_acceptance_tests.sh
This commits adds the value of $BUILD_JAVA_HOME to gradle opts to ensure the consistent JDK use, and not fallback to using system java during the build process
=> Use $BUILD_JAVA_HOME to control JVMs used with acceptance tests

Gemfile.jruby-2.5.lock.release, versions.yml
Version bump to next SNAPSHOT for 7.16.
[rn:skip]
=> Release: bump version to 7.16.1

logstash-core/lib/logstash/settings.rb, logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
Fix Logstash unable to start when using deprecated setting `http.enabled`
Fixes a regression introduced in https://github.com/elastic/logstash/pull/13308 when setting `http.enabled`.
Users can rename the setting (`api.enabled`) and not use the deprecated one, however need to be aware and this impacts the expectation for a smooth upgrade process in 7.x
- #13480
=> Fix: delegating from deprecated setting

logstash-core/lib/logstash/settings.rb, logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
**Backport PR #13481 to 7.16 branch, original message:**
---
Fix Logstash unable to start when using deprecated setting `http.enabled`
Fixes a regression introduced in https://github.com/elastic/logstash/pull/13308 when setting `http.enabled`.
Users can rename the setting (`api.enabled`) and not use the deprecated one, however need to be aware and this impacts the expectation for a smooth upgrade process in 7.x
- #13480
=> Backport PR #13481 to 7.16: Fix: delegating from deprecated setting

logstash-core/lib/logstash/settings.rb, logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
**Backport PR #13481 to 8.0 branch, original message:**
---
Fix Logstash unable to start when using deprecated setting `http.enabled`
Fixes a regression introduced in https://github.com/elastic/logstash/pull/13308 when setting `http.enabled`.
Users can rename the setting (`api.enabled`) and not use the deprecated one, however need to be aware and this impacts the expectation for a smooth upgrade process in 7.x
- #13480
=> Backport PR #13481 to 8.0: Fix: delegating from deprecated setting

Gemfile.jruby-2.5.lock.release
Internal plugin update for 7.16.1
[rn:skip]
Gem/plugin updates for patch version.
Having latest (patch) updates in LS.
=> Deps: bump lock file for 7.16.1

docker/templates/Dockerfile.j2, qa/docker/shared_examples/container.rb, qa/docker/spec/full/container_spec.rb, qa/docker/spec/oss/container_spec.rb
This commit updates the base image of the logstash `full` and `oss` docker images to use ubuntu 20.04 as the base image.
The `ubi8` image remains unchanged
=> Update logstash docker to use ubuntu 20.04 base image

logstash-core/build.gradle
Backport #13494 to 7.16 branch
=> Backport #13494 to 7.16. bump log4j version to 2.15.0

logstash-core/build.gradle
Backport #13494 to 8.0 branch.
=> Backport #13494 to 8.0. bump log4j version to 2.15.0

docs/static/pipeline-pipeline-config.asciidoc
The Output Isolator Pattern doesn't need a persisted queue on the input
pipeline to work. It just needs one on every output pipeline.
Sorry I didn't spot this earlier, @karenzone.
=> Doc: remove PQ on input for Output Isolator

docs/static/jvm.asciidoc
Add an anchor to info on bundled JDK for easier linking and sharing
=> Doc: Add anchor to bundled jdk info

logstash-core/build.gradle
Backport PR #13544 to 8.0 branch. Original message: 
None
=> Backport PR #13544 to 8.0: Bump log4j dependency to 2.17.0

logstash-core/build.gradle
Backport PR #13544 to 7.17 branch. Original message: 
None
=> Backport PR #13544 to 7.17: Bump log4j dependency to 2.17.0

logstash-core/build.gradle
Backport PR #13544 to 7.16 branch. Original message: 
None
=> Backport PR #13544 to 7.16: Bump log4j dependency to 2.17.0

Gemfile.jruby-2.5.lock.release, README.md, versions.yml
[rn:skip]
Bump version after 6.8.22 release
=> bump version to 6.8.23

logstash-core/build.gradle
- Bump log4j dependency to 2.17.1 (#13564)
=> [8.0] Bump log4j dependency to 2.17.1 (#13564)

logstash-core/build.gradle
- Bump log4j dependency to 2.17.1 (#13564)
=> [7.17] Bump log4j dependency to 2.17.1 (#13564)

logstash-core/build.gradle
Backports the following commits to 7.16:
- Bump log4j dependency to 2.17.1 (#13564)
=> [7.16] Bump log4j dependency to 2.17.1 (#13564)

lib/bootstrap/bundler.rb, lib/pluginmanager/install.rb, qa/integration/specs/cli/install_spec.rb
- Fix logstash-plugin install command to install non default plugin (#13405)
=> [7.17] Fix logstash-plugin install command to install non default plugin (#13405)

lib/bootstrap/bundler.rb, lib/pluginmanager/install.rb, qa/integration/specs/cli/install_spec.rb
- Fix logstash-plugin install command to install non default plugin (#13405)
=> [8.0] Fix logstash-plugin install command to install non default plugin (#13405)

docs/static/configuration.asciidoc
[rn:skip]
Add notes to the Event sprintf docs about timestamp formatting to call out the
UTC nature of the Timestamp object.
Users can be surprised when using the sprintf timestamp formatter to route to Elasticsearch indices when the resulting indices don't align with their timezone.
By calling out that the Timestamp object represents an object on the UTC timeline, and that it may not align with their machine-local timezone, we hopefully reduce confusion.
Resolves: elastic/logstash#13112
Supersedes: elastic/logstash#13571
=> docs: sprintf vs UTC nature of @timestamp field

docs/static/configuration.asciidoc
Backport PR #13576 to 8.0 branch. Original message: 
[rn:skip]
Add notes to the Event sprintf docs about timestamp formatting to call out the
UTC nature of the Timestamp object.
Users can be surprised when using the sprintf timestamp formatter to route to Elasticsearch indices when the resulting indices don't align with their timezone.
By calling out that the Timestamp object represents an object on the UTC timeline, and that it may not align with their machine-local timezone, we hopefully reduce confusion.
Resolves: …
=> Backport PR #13576 to 8.0: docs: sprintf vs UTC nature of @timestamp field

docs/static/configuration.asciidoc
Backport PR #13576 to 7.17 branch.
Cherry-pick was _NOT_ clean, since 8.x/main has modifications to support nano-granularity timestamps.
Effective word-diff applied manually.
Original message: 
[rn:skip]
Add notes to the Event sprintf docs about timestamp formatting to call out the
UTC nature of the Timestamp object.
Users can be surprised when using the sprintf timestamp formatter to route to Elasticsearch indices when the resulting indices don't align with their timezone.
By calling out that the Timestamp object represents an object on the UTC timeline, and that it may not align with their machine-local timezone, we hopefully reduce confusion.
- ~[ ] I have made corresponding change to the default configuration …
=> Backport PR #13576 to 7.17: docs: sprintf vs UTC nature of @timestamp field

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/faraday-multipart-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-retry-NOTICE.txt
[rn:skip] 
Adds licenses definitions for `farday-retry` and `faraday-multipart` dependencies that fails  `bin/dependencies-report`
=> Adds license definitions for faraday-multipart and faraday-retry

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/faraday-multipart-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-retry-NOTICE.txt
Clean backport of #13592 to `7.17`
(cherry picked from commit bc760c5c073c3162201286d42211a5c3c0448187)
=> [backport 7.17] Adds license definitions for faraday-multipart and faraday-retry (#13592)

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/faraday-multipart-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/faraday-retry-NOTICE.txt
Clean backport of #13592 to `8.0`
(cherry picked from commit bc760c5c073c3162201286d42211a5c3c0448187)
=> [backport 8.0]Adds license definitions for faraday-multipart and faraday-retry (#13592)

logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/runner.rb, x-pack/lib/filters/geoip/database_manager.rb, x-pack/lib/filters/geoip/database_metric.rb, x-pack/lib/filters/geoip/util.rb, x-pack/spec/filters/geoip/database_manager_spec.rb
- Fix unknown type warning of geoip metrics (#13382)
=> [7.17] Fix unknown type warning of geoip metrics (#13382)

docs/static/releasenotes.asciidoc
Forward port of #13598 to main branch. Original message:
* Update release notes for 8.0.0
* Updated release notes for 8.0.0-rc1
=> Forward port of #13598. Release notes for 8.0.0-rc1

logstash-core/lib/logstash/util/substitution_variables.rb
Clean backport of #13603 to branch `7.17`
(cherry picked from commit e27fdeb25221419ffd2051f77ae3e7240e6378a7)
=> [backport 7.17]Avoid to itereate with each_index (#13603)

docs/static/releasenotes.asciidoc
Forwardports release notes in #13600 to 7.17
Forwardports release notes in #13551 (through conflict resolution) to 7.17
**PREVIEW:** https://logstash_13611.docs-preview.app.elstc.co/guide/en/logstash/7.17/releasenotes.html
=> Doc: Forwardport 7.16.2 and 7.16.1 release notes to 7.17

logstash-core/lib/logstash/util/substitution_variables.rb
**Merge after 8.0.0 rc1**
Clean backport of #13603 to branch `8.0`
(cherry picked from commit e27fdeb25221419ffd2051f77ae3e7240e6378a7)
=> [backport 8.0]Avoid to itereate with each_index (#13603)

logstash-core/src/main/java/org/logstash/ConvertedMap.java, logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java, logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java, logstash-core/src/test/java/org/logstash/ext/JrubyMemoryReadClientExtTest.java, qa/integration/fixtures/monitoring_api_spec.yml, qa/integration/specs/monitoring_api_spec.rb
Fixes `events.out` metric count when there the events are dropped in filter-output section of the pipeline
Fixes the issue #8752 in `event.out` counter. When a pipeline contains a `drop` filter the total `out` events counter should count only the events that reached the out stage.
This PR changes `CompiledExecution.compute()` interface to return the number of events that effectively reached the end of the pipeline. This change is used in `WorkerLoop` to update correctly the `event.out` metric, instead of relying on the batch's size.
It fixes a long standing issue with event's metric counters,  where the event out counters in the `piepelines.<name>.plugins` doesn't matched with the one provided at pipeline level rooted at `event` in case of pipelines configured with `drop` filter.
In …
=> Avoid to increment `event.out` conter for dropped events

logstash-core/src/main/java/org/logstash/ConvertedMap.java, logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java, logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java, logstash-core/src/test/java/org/logstash/ext/JrubyMemoryReadClientExtTest.java, qa/integration/fixtures/monitoring_api_spec.yml, qa/integration/specs/monitoring_api_spec.rb
Clean backport of #13593 to `8.0`
----
Fixes the issue #8752 in event.out counter. When a pipeline contains a drop filter the total out events counter should count only the events that reached the out stage.
This PR changes CompiledExecution.compute() interface to return the number of events that effectively reached the end of the pipeline. This change is used in WorkerLoop to update correctly the event.out metric, instead of relying on the batch's size.
(cherry picked from commit b6da829f4f4cda450855a1f7918887ceb80bf593)
=> [backport 8.0] Avoid to increment `event.out` conter for dropped events (#13593)

logstash-core/spec/logstash/pipeline_pq_file_spec.rb, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
This commit fixes 2 tests
- Set queue.drain to true in pipeline pq test
- Under certain conditions the pipeline_pq_file_spec test would fail as the pipeline would exit once the generator had generated all of its events, but before the events were processed, leading to the test hanging. This commit adds `queue.drain:true` to the settings to ensure that all of the events are processed before the pipeline is shut down
- Increase the flush delay in dead letter quest testFlushAfterDelay test
- Under certain conditions, the flush delay of 1 second was insufficient, and invalidated a pre-condition assertion that no events had been flushed before the expiry of that delay.
=> Fix 2 failing tests on Windows

logstash-core/src/main/java/org/logstash/ConvertedMap.java, logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java, logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java, logstash-core/src/test/java/org/logstash/ext/JrubyMemoryReadClientExtTest.java, qa/integration/fixtures/monitoring_api_spec.yml, qa/integration/specs/monitoring_api_spec.rb
Clean backport of #13593 to `7.17` branch
----
Fixes the issue #8752 in event.out counter. When a pipeline contains a drop filter the total out events counter should count only the events that reached the out stage.
This PR changes CompiledExecution.compute() interface to return the number of events that effectively reached the end of the pipeline. This change is used in WorkerLoop to update correctly the event.out metric, instead of relying on the batch's size.
(cherry picked from commit b6da829f4f4cda450855a1f7918887ceb80bf593)
=> [backport 7.17] Avoid to increment `event.out` conter for dropped events (#13593)

logstash-core/src/main/java/org/logstash/secret/cli/SecretStoreCli.java, logstash-core/src/main/java/org/logstash/secret/store/SecretStore.java, logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java, logstash-core/src/test/java/org/logstash/secret/store/SecretStoreFactoryTest.java
It's possible that directly editing the keystore can cause secrets to become corrupted. If so, removing them is difficult if it's first necessary to retrieve the secret before purging.
This PR changes the purge action to only check if a secret exists instead of retrieving it.
=> don't retrieve the secret before purging

logstash-core/lib/logstash/runner.rb
Clean backport of #13532 to branch `7.17`
Logs the JVM flags and options used to launch Logstash.
(cherry picked from commit d4bdcc936d3f23045a4d463b3ce4902cfc8260cd)
=> [Backport 7.17]Add info log of JVM flags used to configure Logstash (#13531)

logstash-core/lib/logstash/runner.rb
Clean backport of #13531 to branch `8.0`
Logs the JVM flags and options used to launch Logstash.
(cherry picked from commit d4bdcc936d3f23045a4d463b3ce4902cfc8260cd)
=> [Backport 8.0]Add info log of JVM flags used to configure Logstash (#13531)

logstash-core/spec/logstash/pipeline_pq_file_spec.rb, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
Backport PR#13604 to 7.17 branch. Original message:
This commit fixes 2 tests
- Set queue.drain to true in pipeline pq test
- Under certain conditions the pipeline_pq_file_spec test would fail as the pipeline would exit once the generator had generated all of its events, but before the events were processed, leading to the test hanging. This commit adds `queue.drain:true` to the settings to ensure that all of the events are processed before the pipeline is shut down
- Increase the flush delay in dead letter quest testFlushAfterDelay test
- Under certain conditions, the flush delay of 1 second was insufficient, and invalidated a pre-condition assertion that no events had been flushed before the expiry of that delay.
=> [Backport PR#13604 to 7.17] Fix 2 failing tests on Windows

logstash-core/spec/logstash/pipeline_pq_file_spec.rb, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
Backport PR #13604 to 8.0 branch. Original message:
This commit fixes 2 tests
- Set queue.drain to true in pipeline pq test
- Under certain conditions the pipeline_pq_file_spec test would fail as the pipeline would exit once the generator had generated all of its events, but before the events were processed, leading to the test hanging. This commit adds `queue.drain:true` to the settings to ensure that all of the events are processed before the pipeline is shut down
- Increase the flush delay in dead letter quest testFlushAfterDelay test
- Under certain conditions, the flush delay of 1 second was insufficient, and invalidated a pre-condition assertion that no events had been flushed before the expiry of that delay.
=> [Backport PR #13604 to 8.0] Fix 2 failing tests on Windows

logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java, logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java, qa/integration/specs/cli/prepare_offline_pack_spec.rb
Backport PR #13525 to 8.0 branch. Original message: 
- Fixes a regression introduced in 7.12, in which the LS_JAVA_OPTS is ignored when a readable `jvm.options` file cannot be found.
As reported in https://github.com/elastic/logstash/issues/13472 Logstash since 7.12 has silently ignored the `LS_JAVA_OPTS` environment variable when it is unable to find a `jvm.options` file.
This change renames the relevant `JvmOptionsParser#parse(Path)` method to a more descriptive `parseAndInjectEnvironment(Optional<Path>)` and _always_ calls it, regardless of whether a `jvm.options` has been found. It also includes helpful messages to stderr so that the state can be reconstructed from logs.
A common practice with docker deployments is to mount a volume to the config directory, stomping on the default …
=> Backport PR #13525 to 8.0: fix: respect LS_JAVA_OPTS environment even when optionsfile missing

logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java, logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java, qa/integration/specs/cli/prepare_offline_pack_spec.rb
Backport PR #13525 to 7.17 branch. Original message: 
- Fixes a regression introduced in 7.12, in which the LS_JAVA_OPTS is ignored when a readable `jvm.options` file cannot be found.
As reported in https://github.com/elastic/logstash/issues/13472 Logstash since 7.12 has silently ignored the `LS_JAVA_OPTS` environment variable when it is unable to find a `jvm.options` file.
This change renames the relevant `JvmOptionsParser#parse(Path)` method to a more descriptive `parseAndInjectEnvironment(Optional<Path>)` and _always_ calls it, regardless of whether a `jvm.options` has been found. It also includes helpful messages to stderr so that the state can be reconstructed from logs.
A common practice with docker deployments is to mount a volume to the config directory, stomping on the default …
=> Backport PR #13525 to 7.17: fix: respect LS_JAVA_OPTS environment even when optionsfile missing

docs/static/running-logstash-command-line.asciidoc
Adding the `pipeline.ecs_compatibility` setting from https://www.elastic.co/guide/en/logstash/current/ecs-ls.html and https://github.com/elastic/logstash/blob/7.16/logstash-core/lib/logstash/runner.rb#L163 to the list of available command line options. This is important because with 7.16 this will lead to a lot of deprecation logging like 
````
Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
````
=> [Docs] Add pipeline.ecs_compatibility to the list

qa/integration/services/helpers.sh
When the Bash script executes the vendored Ruby it has to use to proper `GEM_HOME` avoid the overwrite that happens inside the logstash.lib.sh
https://github.com/elastic/logstash/blob/3064f7d0c3374ec0c0ff9a9b14064b7fed66309e/bin/logstash.lib.sh#L161-L165
[rn:skip] 
Kafka integration tests uses port check function to look if a port is available or less.
This function is implemented in `bash` using `netcat` or falling back to Ruby `TCPSocket.new('localhost', $1) rescue exit(1)` [script](https://github.com/elastic/logstash/blob/3064f7d0c3374ec0c0ff9a9b14064b7fed66309e/qa/integration/services/helpers.sh#L37-L51).
In OSes without `netcat` installed and without a default Ruby, the Kafka integration test uses the vendored ruby, which uses the bad `GEM_HOME` resulting in gems not found problem. …
=> Fix Ruby port check execution in kafka_setup.sh

docs/index.asciidoc
Improvements in Elastic.co docs tooling (approximately 2019) made the "Edit" links better at guessing the source URL for editing. Hard-coded links for Logstash core documentation are no longer required, and can potentially cause problems (as in the recent `master`->`main` branch renaming). Taking this opportunity to do more cleanup. 
Note that links to source files for plugin docs (in `logstash-docs`) must remain hard-coded because they live in their own repos. 
**PREVIEW:** https://logstash_13636.docs-preview.app.elstc.co/guide/en/logstash/master/introduction.html
Related: #13619
=> Doc: Remove hard-coded edit_url links where possible

rakelib/version.rake
[rn:skip]
Updates the post release `rake version:set[7.18.1]` task to also update the *Gemfile.lock.release* file
doing [the changes Bundler should pick up on next run](https://github.com/elastic/logstash/pull/13476/files#diff-127e1a3a65d315d86dbe640d9578a969da44e5226e5d9bf2de251b075c1d8b7aR5)
=> Build: update .lock.release with rake version:set

qa/integration/specs/cli/install_spec.rb
Clean backport of #13641 to `7.17`
----
Original message:
Cleanly teardown an integration test that made fall other integration tests.
In some cases the CI integration tests fails because the launched Logstash can't find a gem named `mimemagic`. This gem is installed during a CLI plugin test (install of  `logstash-input-google_cloud_storage` plugins kicks in that `mimemagic`).
(cherry picked from commit 640ba8489f857e83e6f397b349379544f992b296)
=> [Backport 7.17] Fix/gems not found in integration test after plugin install (#13641)

qa/integration/services/helpers.sh
Clean backport of #13631 to `7.17`
----
Original message:
When the Bash script executes the vendored Ruby it has to use proper `GEM_HOME` to avoid the overwrite that happens inside the logstash.lib.sh
https://github.com/elastic/logstash/blob/3064f7d0c3374ec0c0ff9a9b14064b7fed66309e/bin/logstash.lib.sh#L161-L165
(cherry picked from commit 93f37b96099328b6376a5c332cea7042d82e7974)
=> [Backport 7.17] Fix Ruby port check execution in kafka_setup.sh (#13631)

qa/integration/services/helpers.sh
Clean backport of #13631 to `8.0`
----
Original message:
When the Bash script executes the vendored Ruby it has to use proper `GEM_HOME` to avoid the overwrite that happens inside the logstash.lib.sh
https://github.com/elastic/logstash/blob/3064f7d0c3374ec0c0ff9a9b14064b7fed66309e/bin/logstash.lib.sh#L161-L165
(cherry picked from commit 93f37b96099328b6376a5c332cea7042d82e7974)
=> [Backport 8.0] Fix Ruby port check execution in kafka_setup.sh (#13631)

qa/integration/specs/cli/install_spec.rb
Clean backport of #13641 to `8.0`
----
Original message:
Cleanly teardown an integration test that made fall other integration tests.
In some cases the CI integration tests fails because the launched Logstash can't find a gem named `mimemagic`. This gem is installed during a CLI plugin test (install of  `logstash-input-google_cloud_storage` plugins kicks in that `mimemagic`).
(cherry picked from commit 640ba8489f857e83e6f397b349379544f992b296)
=> [Backport 8.0] Fix/gems not found in integration test after plugin install (#13641)

docs/static/persistent-queues.asciidoc
[rn:skip]
The `queue.*` settings apply to all pipelines if specified in `logstash.yml`.
Also, each pipeline will have its own queue.
The `pipelines.yml` file can be used to specify custom queue settings per pipeline.
Clarifies some information about queues.
To the reviewer:
=> [DOC] Clarify scope of queue settings

logstash-core/src/main/java/org/logstash/FieldReference.java, logstash-core/src/test/java/org/logstash/FieldReferenceTest.java
Reduces the scope of a memory leak that can be caused by using UUIDs or other
high-cardinality field names by preventing the ruby string _keys_ from being
held by the cache indefinitely.
Note: this may not solve the problem entirely, but certainly limits its impact.
Because ConvertedMap requires individual field names to be interned into
the global String intern pool, their eligibility for GC is JVM-specific
and high-cardinality field names should still be avoided.
Reduces the scope of a memory leak that can be caused by using UUIDs or other high-cardinality field names.
Ports the same naïve limits to caching the `FieldReference.RUBY_CACHE` (`Map<RubyString,FieldReference>`) that we have on the `FieldReference.CACHE` (`Map<String,FieldReference>`). Once the 10k limit is reached, …
=> field-reference: cap RUBY_CACHE to 10k entries

qa/integration/fixtures/es_output_how_spec.yml, qa/integration/specs/es_output_how_spec.rb
Currently, the elasticsearch integration test turns off `data_streams`
and `ecs_compatibility`, hiding the out of the box experience for
ingesting into elasticsearch
=> Add integration test for Elasticsearch using defaults

logstash-core/lib/logstash/config/pipelines_info.rb
[rn:skip]
Minor resilience improvements to pipeline stats, to resolve an edge-case where we are asked to report stats while a pipeline is in the process of starting up. There are three situations where this is relevant:
- querying pipeline stats API: could result in a 500 response, but an immediate retry would be back to a 200 OK response.
- Monitoring pipeline could fail to capture a stats snapshot, but the next tick would succeed
- test assertions could fail in not-quite relevant ways, requiring a rebuild:
> ~~~
> 13:41:46     Failures:
> 13:41:46 
> 13:41:46       1) LogStash::Inputs::Metrics::StatsEventFactory new model behaves like new model monitoring event with webserver setting should be valid
> 13:41:46          Failure/Error: "pipelines" => …
=> stats api: startup resilience when stats are partially formed

logstash-core/src/main/java/org/logstash/FieldReference.java, logstash-core/src/test/java/org/logstash/FieldReferenceTest.java
Backport PR #13642 to 7.17 branch. Original message: 
Reduces the scope of a memory leak that can be caused by using UUIDs or other
high-cardinality field names by preventing the ruby string _keys_ from being
held by the cache indefinitely.
Note: this may not solve the problem entirely, but certainly limits its impact.
Because ConvertedMap requires individual field names to be interned into
the global String intern pool, their eligibility for GC is JVM-specific
and high-cardinality field names should still be avoided.
Reduces the scope of a memory leak that can be caused by using UUIDs or other high-cardinality field names.
Ports the same naïve limits to caching the `FieldReference.RUBY_CACHE` (`Map<RubyString,FieldReference>`) that we have on the `FieldReference.CACHE` …
=> Backport PR #13642 to 7.17: field-reference: cap RUBY_CACHE to 10k entries

logstash-core/src/main/java/org/logstash/FieldReference.java, logstash-core/src/test/java/org/logstash/FieldReferenceTest.java
Backport PR #13642 to 8.0 branch. Original message: 
Reduces the scope of a memory leak that can be caused by using UUIDs or other
high-cardinality field names by preventing the ruby string _keys_ from being
held by the cache indefinitely.
Note: this may not solve the problem entirely, but certainly limits its impact.
Because ConvertedMap requires individual field names to be interned into
the global String intern pool, their eligibility for GC is JVM-specific
and high-cardinality field names should still be avoided.
Reduces the scope of a memory leak that can be caused by using UUIDs or other high-cardinality field names.
Ports the same naïve limits to caching the `FieldReference.RUBY_CACHE` (`Map<RubyString,FieldReference>`) that we have on the `FieldReference.CACHE` …
=> Backport PR #13642 to 8.0: field-reference: cap RUBY_CACHE to 10k entries

docs/static/running-logstash-command-line.asciidoc
Backport PR #13612 to 8.0 branch. Original message: 
Adding the `pipeline.ecs_compatibility` setting from https://www.elastic.co/guide/en/logstash/current/ecs-ls.html and https://github.com/elastic/logstash/blob/7.16/logstash-core/lib/logstash/runner.rb#L163 to the list of available command line options. This is important because with 7.16 this will lead to a lot of deprecation logging like 
````
Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
````
=> Backport PR #13612 to 8.0: [Docs] Add pipeline.ecs_compatibility to the list

docs/static/running-logstash-command-line.asciidoc
Backport PR #13612 to 7.17 branch. Original message: 
Adding the `pipeline.ecs_compatibility` setting from https://www.elastic.co/guide/en/logstash/current/ecs-ls.html and https://github.com/elastic/logstash/blob/7.16/logstash-core/lib/logstash/runner.rb#L163 to the list of available command line options. This is important because with 7.16 this will lead to a lot of deprecation logging like 
````
Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
````
=> Backport PR #13612 to 7.17: [Docs] Add pipeline.ecs_compatibility to the list

logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
[rn:skip]
Replaces the `\n` characters with System's line separator in unit tests to be portable across various OSes.
Make the unit test green under Windows OS.
```sh
set GRADLE_OPTS=-Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot"
.\gradlew.bat test --console=plain --no-daemon --info
```
- 
Failure example from the CI:
```
15:51:33 org.logstash.launchers.JvmOptionsParserTest > test_LS_JAVA_OPTS_isUsedWhenNoJvmOptionsIsAvailable STARTED
15:51:33 
15:51:33 org.logstash.launchers.JvmOptionsParserTest > test_LS_JAVA_OPTS_isUsedWhenNoJvmOptionsIsAvailable STANDARD_ERROR
15:51:33     Warning: no jvm.options file found.
15:51:33 
15:51:33 org.logstash.launchers.JvmOptionsParserTest > test_LS_JAVA_OPTS_isUsedWhenNoJvmOptionsIsAvailable FAILED
15:51:33 …
```
=> Fix unit test under Windows

logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Backport PR #13656 to 8.0 branch. Original message: 
[rn:skip]
Replaces the `\n` characters with System's line separator in unit tests to be portable across various OSes.
Make the unit test green under Windows OS.
```sh
set GRADLE_OPTS=-Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot"
.\gradlew.bat test --console=plain --no-daemon --info
```
- 
Failure example from the CI:
```
15:51:33 org.logstash.launchers.JvmOptionsParserTest > test_LS_JAVA_OPTS_isUsedWhenNoJvmOptionsIsAvailable STARTED
15:51:33 
15:51:33 org.logstash.launchers.JvmOptionsParserTest > test_LS_JAVA_OPTS_isUsedWhenNoJvmOptionsIsAvailable STANDARD_ERROR
15:51:33     Warning: no jvm.options file found.
15:51:33 
15:51:33 org.logstash.launchers.JvmOptionsParserTest > …
```
=> Backport PR #13656 to 8.0: Fix unit test under Windows

logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Backport PR #13656 to 7.17 branch. Original message: 
[rn:skip]
Replaces the `\n` characters with System's line separator in unit tests to be portable across various OSes.
Make the unit test green under Windows OS.
```sh
set GRADLE_OPTS=-Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot"
.\gradlew.bat test --console=plain --no-daemon --info
```
- 
Failure example from the CI:
```
15:51:33 org.logstash.launchers.JvmOptionsParserTest > test_LS_JAVA_OPTS_isUsedWhenNoJvmOptionsIsAvailable STARTED
15:51:33 
15:51:33 org.logstash.launchers.JvmOptionsParserTest > test_LS_JAVA_OPTS_isUsedWhenNoJvmOptionsIsAvailable STANDARD_ERROR
15:51:33     Warning: no jvm.options file found.
15:51:33 
15:51:33 org.logstash.launchers.JvmOptionsParserTest > …
```
=> Backport PR #13656 to 7.17: Fix unit test under Windows

Gemfile.jruby-2.5.lock.release
[rn:skip] 
Bumps the Gemfile.lock for the `8.0.0-rc2`
=> Bump Gemfile lock for 8.0.0-rc2

logstash-core/lib/logstash/config/pipelines_info.rb
Backport PR #13645 to 7.17 branch. Original message: 
[rn:skip]
Minor resilience improvements to pipeline stats, to resolve an edge-case where we are asked to report stats while a pipeline is in the process of starting up. There are three situations where this is relevant:
- querying pipeline stats API: could result in a 500 response, but an immediate retry would be back to a 200 OK response.
- Monitoring pipeline could fail to capture a stats snapshot, but the next tick would succeed
- test assertions could fail in not-quite relevant ways, requiring a rebuild:
> ~~~
> 13:41:46     Failures:
> 13:41:46 
> 13:41:46       1) LogStash::Inputs::Metrics::StatsEventFactory new model behaves like new model monitoring event with webserver setting should be valid
> 13:41:46          Failure/Error: …
=> Backport PR #13645 to 7.17: stats api: startup resilience when stats are partially formed

logstash-core/lib/logstash/config/pipelines_info.rb
Backport PR #13645 to 8.0 branch. Original message: 
[rn:skip]
Minor resilience improvements to pipeline stats, to resolve an edge-case where we are asked to report stats while a pipeline is in the process of starting up. There are three situations where this is relevant:
- querying pipeline stats API: could result in a 500 response, but an immediate retry would be back to a 200 OK response.
- Monitoring pipeline could fail to capture a stats snapshot, but the next tick would succeed
- test assertions could fail in not-quite relevant ways, requiring a rebuild:
> ~~~
> 13:41:46     Failures:
> 13:41:46 
> 13:41:46       1) LogStash::Inputs::Metrics::StatsEventFactory new model behaves like new model monitoring event with webserver setting should be valid
> 13:41:46          Failure/Error: …
=> Backport PR #13645 to 8.0: stats api: startup resilience when stats are partially formed

logstash-core/lib/logstash/environment.rb, logstash-core/lib/logstash/runner.rb
Backport PR #13221 to 8.0 branch. Original message: 
Ensures that the non-runner command line utilities like `bin/logstash-keystore`
correctly initialize the logger as-configured.
Fixed an issue where invoking the Logstash Keystore Utility (`bin/logstash-keystore`) incorrectly set up a logging directory to the literal `${sys:ls.logs}` and produced noise to the console about routing logs. This utility now correctly configures its logger using the provided settings file.
Moves logger configuration "up" into the settings post-processor, which is invoked by both the normal pipeline runner _and_ the keystore utility `bin/logstash-keystore`. Now invoking either will correctly pick up logging configuration.
Fixes an issue where invoking the Logstash Keystore Utility (`bin/logstash-keystore`) …
=> Backport PR #13221 to 8.0: logging: move init into environment's settings post-processor

logstash-core/lib/logstash/environment.rb, logstash-core/lib/logstash/runner.rb
Backport PR #13221 to 7.17 branch. Original message: 
Ensures that the non-runner command line utilities like `bin/logstash-keystore`
correctly initialize the logger as-configured.
Fixed an issue where invoking the Logstash Keystore Utility (`bin/logstash-keystore`) incorrectly set up a logging directory to the literal `${sys:ls.logs}` and produced noise to the console about routing logs. This utility now correctly configures its logger using the provided settings file.
Moves logger configuration "up" into the settings post-processor, which is invoked by both the normal pipeline runner _and_ the keystore utility `bin/logstash-keystore`. Now invoking either will correctly pick up logging configuration.
Fixes an issue where invoking the Logstash Keystore Utility (`bin/logstash-keystore`) …
=> Backport PR #13221 to 7.17: logging: move init into environment's settings post-processor

README.md
[rn:skip]
Updates dev doc to only reference java 11.
Attempting to `rake bootstrap` on java 8 just throws "The minimum required Java version is 11" for me.
- ~~My code follows the style guidelines of this project~~
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~I have added tests that prove my fix is effective or that my feature works~~
Try `rake bootstrap` on java 8, then on 11.
=> Remove java 8 from setup readme

qa/integration/specs/cli/install_spec.rb
[rn:skip]
Fixes an integration test that verifies the capabilities of CLI tool to install a not bundled plugin.
The test needs to peek a plugin that's not bundled with the Logstash distribution, the originally chosen plugin `logstash-input-google_cloud_storage` has a [dependency on](https://github.com/logstash-plugins/logstash-input-google_cloud_storage/blob/46ff388dd8c5470840b172eec92f8781aac786cb/logstash-input-google_cloud_storage.gemspec#L43) `mimemagic` gem. The required gem needs that on the target system is present the file `freedesktop.org.xml` which is shipped in OS packages named `shared-mime-info`, however this package is not present on Debian 10 used by CI, generating a test failure.
Impact only the CI integration tests.
- 
Error from the console:
```sh
1) CLI > …
```
=> Test fix, switch to plugin with less dependencies

qa/integration/specs/cli/install_spec.rb
Clean backport of #13672 to `8.0`
----
Fixes an integration test that verifies the capabilities of CLI tool to install a not bundled plugin.
Move away from logstash-input-google_cloud_storage which depends indirectly to OS's package named shared-mime-info, which is not always available.
(cherry picked from commit 7bb56e46dd0cccf9b4fc55e6d8dcc99ca325370f)
=> [Backport 8.0] Test fix, switch to plugin with less dependencies (#13672)

logstash-core/lib/logstash/pipeline.rb
Backport PR #12534 to 8.0 branch. Original message: 
[rn:skip]
This PR is a follow-up of ruby execution engine removal. It adds a better backward compatibility experience for plugins not in the support matrix
follow-up on https://github.com/elastic/logstash/pull/12517
=> Backport PR #12534 to 8.0: Add compatibility on ruby pipeline for plugins not in support matrix

logstash-core/spec/logstash/compiler/compiler_spec.rb, logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java, logstash-core/src/main/java/org/logstash/config/ir/ConfigCompiler.java, logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java, logstash-core/src/main/java/org/logstash/config/ir/expression/ExpressionSubstitution.java, logstash-core/src/main/java/org/logstash/config/ir/imperative/ComposedParallelStatement.java, logstash-core/src/main/java/org/logstash/config/ir/imperative/ComposedSequenceStatement.java, logstash-core/src/main/java/org/logstash/config/ir/imperative/IfStatement.java, logstash-core/src/main/java/org/logstash/config/ir/imperative/NoopStatement.java, logstash-core/src/main/java/org/logstash/config/ir/imperative/PluginStatement.java, logstash-core/src/main/java/org/logstash/config/ir/imperative/Statement.java, logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java, logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java, logstash-core/src/test/java/org/logstash/config/ir/ConfigCompilerTest.java, logstash-core/src/test/java/org/logstash/config/ir/EventConditionTest.java, logstash-core/src/test/java/org/logstash/config/ir/IRHelpers.java, logstash-core/src/test/java/org/logstash/config/ir/PipelineIRTest.java, logstash-core/src/test/java/org/logstash/config/ir/expression/ExpressionSubstitutionTest.java, logstash-core/src/test/java/org/logstash/config/ir/imperative/IfStatementTest.java, logstash-core/src/test/java/org/logstash/config/ir/imperative/ImperativeToGraphtest.java, logstash-core/src/test/java/org/logstash/plugins/factory/PluginFactoryExtTest.java, qa/integration/fixtures/env_variables_condition_spec.yml, qa/integration/specs/env_variables_condition_spec.rb, qa/integration/specs/secret_store_spec.rb, x-pack/spec/monitoring/inputs/metrics/state_event/lir_serializer_spec.rb
Support environment variable in condition.
Two substitutions in ruby side cause inconsistent precedence when resolving the variable.
In the past, `${VAR:default_value}` is resolved in the following precedence: secret store -> environment variable -> default value.
After two substitutions, (first substitute)  environment variable -> default value -> (second substitute) secret store
The inconsistency could confuse users.
To truly support `if` with value in secret store, this commit implement substitution in java side 
This PR substitutes ${VAR} in Expression, except RegexValueExpression, with the value in secret store, env. 
The substitution happens after syntax parsing and before graph execution.
This PR allows users to use environment variable in condition, eg. `if [app] == "${VAR}"` 
- …
=> Support env variable in condition

Gemfile.jruby-2.5.lock.release
[rn:skip]
Picks up upstream bugfixes in GeoIP filter and Puma
=> Update patch plugin versions in gemfile lock for 7.17

docs/static/configuration.asciidoc
- Revert "[DOC] Clarify the scope of environment variable expansion (#13299)" (#13679)
=> [8.0] Revert "[DOC] Clarify the scope of environment variable expansion (#13299)" (#13679)

docs/static/configuration.asciidoc
- Revert "[DOC] Clarify the scope of environment variable expansion (#13299)" (#13679)
=> [7.17] Revert "[DOC] Clarify the scope of environment variable expansion (#13299)" (#13679)

docs/static/security/es-security.asciidoc
Bulleted list requires a return after into in order to render correctly. Otherwise, the whole list renders as a paragraph.
=> Doc: Fix formatting for bulleted list

docs/static/releasenotes.asciidoc
Fixed a typo (Ubuntu instead of Ununtu) in the 7.17 Release Notes for Logstash
Typo, making new OS for images not searchable.
-
=> Doc: Fix typo in 7.17 release notes

logstash-core/build.gradle, logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
Versions of google-java-format 1.8 and above no longer depend on the gpl2 javac-shaded jar, so we can upgrade.
=> update google java format dependency

logstash-core/src/main/java/org/logstash/ackedqueue/PqCheck.java, logstash-core/src/main/java/org/logstash/ackedqueue/PqRepair.java, logstash-core/src/test/java/org/logstash/ackedqueue/PqRepairTest.java
Fixed: #11548
improve persistent queue tool to handle `.tmp` checkpoint
`pqcheck` skip checking `checkpoint.*.tmp` 
`pqrepair` delete `checkpoint.*.tmp` 
When Logstash shutdown unexpectedly, PQ could end in the middle of updating checkpoint file, and as a result, `checkpoint.*.tmp` left in the disk. Prior to the change, `pqcheck` and `pqrepair` crashed because of tmp file.
https://github.com/elastic/logstash/pull/13166
=> pqcheck pqrepair handle .tmp checkpoint

logstash-core/src/main/java/org/logstash/ackedqueue/PqCheck.java, logstash-core/src/main/java/org/logstash/ackedqueue/PqRepair.java, logstash-core/src/test/java/org/logstash/ackedqueue/PqRepairTest.java
- pqcheck pqrepair handle .tmp checkpoint (#13721)
=> [7.17] pqcheck pqrepair handle .tmp checkpoint (#13721)

logstash-core/src/main/java/org/logstash/ackedqueue/PqCheck.java, logstash-core/src/main/java/org/logstash/ackedqueue/PqRepair.java, logstash-core/src/test/java/org/logstash/ackedqueue/PqRepairTest.java
Backports the following commits to 8.1:
- pqcheck pqrepair handle .tmp checkpoint (#13721)
=> [8.1] pqcheck pqrepair handle .tmp checkpoint (#13721)

logstash-core/src/main/java/org/logstash/instrument/monitors/ProcessMonitor.java, logstash-core/src/test/java/org/logstash/instruments/monitors/ProcessMonitorTest.java
Clean backport of #13727 to branch `7.17.`
----
Original comment:
Use same technique for Unix system to extract the CPU percentage and publish to Logstash's metrics collector.
It doesn't retrieve the full set of metric of a Unix system, but the ones that are available from internal JDK class com.sun.management.OperatingSystemMXBean
(cherry picked from commit d8f4784d69ef5bda26c884e06e4c3ebec54ff6f7)
=> [backport 7.17]Publish CPU percentage also non Unix systems (#13727)

docs/static/breaking-changes-80.asciidoc
Replaces anchor-only link with full link to work across guides. 
Adds note to future authors to call out this requirement.
=> Doc: Replace short link with full link

logstash-core/src/main/java/org/logstash/instrument/monitors/ProcessMonitor.java, logstash-core/src/test/java/org/logstash/instruments/monitors/ProcessMonitorTest.java
Clean backport of #13727 to branch `8.1`
----
Original comment:
Use same technique for Unix system to extract the CPU percentage and publish to Logstash's metrics collector.
It doesn't retrieve the full set of metric of a Unix system, but the ones that are available from internal JDK class com.sun.management.OperatingSystemMXBean
(cherry picked from commit d8f4784d69ef5bda26c884e06e4c3ebec54ff6f7)
=> [backport 8.1]Publish CPU percentage also non Unix systems (#13727)

docs/static/upgrading.asciidoc
Clean backport of #13684 to branch `8.1`
----
Original comment
During the time Logstash switched from a set of Ruby files plus one fat jar to multiple jars, with configuration files
and shell scripts that also needs to be updated. It's not anymore sufficient to suggest to unpack a new distribution
over an existing one. This is problematic when we add jars from version to version because drive to the pollution
of the classpath.
This commit redefines to steps to do this, in a safer way, backing up data and config folders.
Co-authored-by: Karen Metts <35154725+karenzone@users.noreply.github.com
(cherry picked from commit 30b9ad88484c237ec8726fbcb81df63295c9628e)
=> [backport 8.1]Update the Upgrading Using a Direct Download guide section. (#13684)

docs/static/upgrading.asciidoc
Clean backport of #13684 to branch `8.0`
----
Original comment
During the time Logstash switched from a set of Ruby files plus one fat jar to multiple jars, with configuration files
and shell scripts that also needs to be updated. It's not anymore sufficient to suggest to unpack a new distribution
over an existing one. This is problematic when we add jars from version to version because drive to the pollution
of the classpath.
This commit redefines to steps to do this, in a safer way, backing up data and config folders.
Co-authored-by: Karen Metts <35154725+karenzone@users.noreply.github.com
(cherry picked from commit 30b9ad88484c237ec8726fbcb81df63295c9628e)
=> [backport 8.0] Update the Upgrading Using a Direct Download guide section. (#13684)

docs/static/getting-started-with-logstash.asciidoc, docs/static/monitoring/monitoring-mb.asciidoc, docs/static/redirects.asciidoc
[rn:skip]
As of Stack 8.0, Elastic is no longer maintaining a separate homebrew cask
with Elastic-licensed artifacts for the MacOS package manager homebrew, due to
low usage, difficulty in maintaining multiple versions, lack of team expertise,
and an existing Apache-licensed formula.
As such, we are removing instructions about setting up and running Logstash
from these formulae that are no longer available.
If the upstream casks don't exist, sending users down the path of trying to add them would be an unpleasant dead-end.
=> Docs remove homebrew

docs/static/getting-started-with-logstash.asciidoc, docs/static/monitoring/monitoring-mb.asciidoc, docs/static/redirects.asciidoc
Backport PR #13747 to 8.0 branch. Original message: 
[rn:skip]
As of Stack 8.0, Elastic is no longer maintaining a separate homebrew cask
with Elastic-licensed artifacts for the MacOS package manager homebrew, due to
low usage, difficulty in maintaining multiple versions, lack of team expertise,
and an existing Apache-licensed formula.
As such, we are removing instructions about setting up and running Logstash
from these formulae that are no longer available.
If the upstream casks don't exist, sending users down the path of trying to add them would be an unpleasant dead-end.
- ~[ ] I have added tests that prove my fix is …
=> Backport PR #13747 to 8.0: Docs remove homebrew

docs/static/getting-started-with-logstash.asciidoc, docs/static/monitoring/monitoring-mb.asciidoc, docs/static/redirects.asciidoc
Backport PR #13747 to 8.1 branch. Original message: 
[rn:skip]
As of Stack 8.0, Elastic is no longer maintaining a separate homebrew cask
with Elastic-licensed artifacts for the MacOS package manager homebrew, due to
low usage, difficulty in maintaining multiple versions, lack of team expertise,
and an existing Apache-licensed formula.
As such, we are removing instructions about setting up and running Logstash
from these formulae that are no longer available.
If the upstream casks don't exist, sending users down the path of trying to add them would be an unpleasant dead-end.
- ~[ ] I have added tests that prove my fix is …
=> Backport PR #13747 to 8.1: Docs remove homebrew

build.gradle
Build has been failing since the release of 2.3.7, this commit pins
bundler to 2.3.6 to get the build green again while the cause can be
investigated
=> Pin bundler to 2.3.6 to fix builder

docs/static/releasenotes.asciidoc
Forwardports #13711 to main 
Includes release notes for 8.0.0-rc2 and 8.0.0-GA.
**PREVIEW:** https://logstash_13750.docs-preview.app.elstc.co/guide/en/logstash/master/releasenotes.html
Co-authored-by: andsel <selva.andre@gmail.com>
Co-authored-by: Ry Biesemeyer <ry.biesemeyer@elastic.co>
=> Doc Forwardport 8.0 release notes to main

build.gradle
Backport PR #13753 to 8.0 branch. Original message: 
Build has been failing since the release of 2.3.7, this commit pins
bundler to 2.3.6 to get the build green again while the cause can be
investigated
=> Backport PR #13753 to 8.0: Pin bundler to 2.3.6 to fix builder

build.gradle
Backport PR #13753 to 8.1 branch. Original message: 
Build has been failing since the release of 2.3.7, this commit pins
bundler to 2.3.6 to get the build green again while the cause can be
investigated
=> Backport PR #13753 to 8.1: Pin bundler to 2.3.6 to fix builder

logstash-core/src/main/java/org/logstash/instrument/monitors/ProcessMonitor.java, logstash-core/src/test/java/org/logstash/instruments/monitors/ProcessMonitorTest.java
Clean backport of #13727 to branch `8.0.`
----
Original comment:
Use same technique for Unix system to extract the CPU percentage and publish to Logstash's metrics collector.
It doesn't retrieve the full set of metric of a Unix system, but the ones that are available from internal JDK class com.sun.management.OperatingSystemMXBean
(cherry picked from commit d8f4784d69ef5bda26c884e06e4c3ebec54ff6f7)
=> [backport 8.0]Publish CPU percentage also non Unix systems (#13727)

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV1.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV2.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/PageIO.java, logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
Fixed: #10855 #8480
Fix zero bytes persistent queue page which cause "Page file size is too small to hold elements" exception that block Logstash from start
When PQ is fully acked and the page size is zero byte, this PR deleted the corrupted page file and recreated checkpoint file. Also, rephase the error message to point user to `pqrepair`
The corrupted page files cause `java.io.IOException: Page file size is too small to hold elements` exception, which block Logstash start process. Prior to this change, users need to manually delete page file and check point file in order to pass the persistent queue check.
enable persistent queue and run pipeline
```
input {
heartbeat {
interval => 1
}
}
output {
stdout { codec => rubydebug }
}
```
stop logstash and remove page file `page.0`
create a …
=> handle fully acked 0 byte PQ pages

logstash-core/build.gradle, logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV1.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV2.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/PageIO.java, logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
- handle fully acked 0 byte PQ pages (#13692)
=> [7.17] handle fully acked 0 byte PQ pages (#13692)

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV1.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV2.java, logstash-core/src/main/java/org/logstash/ackedqueue/io/PageIO.java, logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
Backports the following commits to 8.1:
- handle fully acked 0 byte PQ pages (#13692)
=> [8.1] handle fully acked 0 byte PQ pages (#13692)

logstash-core/src/main/java/org/logstash/ackedqueue/PqRepair.java, logstash-core/src/test/resources/log4j2.properties
- fix pqrepair log4j setting (#13726)
=> [7.17] fix pqrepair log4j setting (#13726)

qa/README.md, qa/integration/README.md
The BUILD_JAVA_HOME setting gives developers a way to test with a Java version other than the one set in JAVA_HOME. 
Made other edits and formatting corrections while I was in there.
=> Doc:Update qa readme with BUILD_JAVA_HOME setting info

logstash-core/logstash-core.gemspec
A recent update to jruby-openssl causes a gem load error when trying to
use `bin/logstash-plugin`. This commit pins the gemspec in the
`logstash-core.gemspec` to match that in the lockfile.
=> Lock jruby-openssl in logtash-core to 0.11.0

logstash-core/logstash-core.gemspec
Dependency lock.
[rn:skip]
Locks sinatra dependency due incompatibilities.
Sinatra is used for LS's HTTP API.
This concerns LS 8.0.0 whenever a plugin update is triggered (which updates sinatra). 
Report at: https://github.com/elastic/logstash/issues/13777
Sample failure (from CI while using sinatra 2.2.0):
```
ArgumentError: wrong number of arguments (given 3, expected 1..2)
```
LS (`>=`) **8.0.1** should lock the version until the issue is resolved ...
=> Deps: pin sinatra due (2.2.0) incompatibilities

devtools/backport
Some minor usability improvements I've been using for a while.
Please double check if anything got messed up, sample usage:
`devtools/backport 7.16 13481` (without having to copy and specify commits)
sample PR created (notice the updated formatting - to visually differentiate the "copied PR desc"): https://github.com/elastic/logstash/pull/13484
[rn:skip]
=> Chore: fetch merge commit automatically with backport dev tool

logstash-core/logstash-core.gemspec
Backport PR #13784 to 7.17 branch. Original message: 
Dependency lock.
[rn:skip]
Locks sinatra dependency due incompatibilities.
Sinatra is used for LS's HTTP API.
This concerns LS 8.0.0 whenever a plugin update is triggered (which updates sinatra). 
Report at: https://github.com/elastic/logstash/issues/13777
Sample failure (from CI while using sinatra 2.2.0):
```
ArgumentError: wrong number of arguments (given 3, expected 1..2)
```
LS (`>=`) **8.0.1** should lock the version until the issue is resolved ...
=> Backport PR #13784 to 7.17: Deps: pin sinatra due (2.2.0) incompatibilities

lib/bootstrap/bundler.rb, lib/pluginmanager/install.rb, lib/pluginmanager/update.rb, spec/unit/plugin_manager/update_spec.rb
`bin/logstash-plugin install logstash-input-s3-sns-sqs`
```patch
diff --git Gemfile.lock Gemfile.lock
index b3d2b0b89..5c7742fd0 100644
--- Gemfile.lock
+++ Gemfile.lock
@@ -476,6 +476,10 @@ GEM
logstash-mixin-aws (>= 5.1.0)
logstash-mixin-ecs_compatibility_support (~> 1.2)
stud (~> 0.0.18)
+    logstash-input-s3-sns-sqs (2.1.3)
+      logstash-codec-json (~> 3.0)
+      logstash-core-plugin-api (>= 2.1.12, <= 2.99)
+      logstash-mixin-aws (>= 4.3)
logstash-input-snmp (1.3.1)
logstash-codec-plain
logstash-core-plugin-api (>= 1.60, <= 2.99)
@@ -864,6 +868,7 @@ DEPENDENCIES
logstash-input-pipe
logstash-input-redis
logstash-input-s3
+  logstash-input-s3-sns-sqs
logstash-input-snmp
logstash-input-snmptrap
logstash-input-sqs
```
```patch
diff --git Gemfile.lock Gemfile.lock
index …
```
=> Feat: conservative plugin (dependency) updates by default

logstash-core/logstash-core.gemspec
This is a backport of https://github.com/elastic/logstash/pull/13785
jruby-openssl 0.12.1 is causing gem load error when running `bin/logstash-plugin`
hence pin to 0.11.0
=> pin jruby-openssl to 0.11.0

.github/workflows/add-docs-preview-link.yml
[rn-skip]
When a pull-request is opened, or when the HEAD of an existing pull-request is changed, and the changeset modifies the docs, add a comment to the PR with a link to our docs preview.
=> action: add docs preview link when docs change.

lib/bootstrap/bundler.rb, lib/pluginmanager/install.rb, lib/pluginmanager/update.rb, spec/unit/plugin_manager/update_spec.rb
**Backport PR #13794 to 7.17 branch, original message:**
---
`bin/logstash-plugin install logstash-input-s3-sns-sqs`
```patch
diff --git Gemfile.lock Gemfile.lock
index b3d2b0b89..5c7742fd0 100644
--- Gemfile.lock
+++ Gemfile.lock
@@ -476,6 +476,10 @@ GEM
logstash-mixin-aws (>= 5.1.0)
logstash-mixin-ecs_compatibility_support (~> 1.2)
stud (~> 0.0.18)
+    logstash-input-s3-sns-sqs (2.1.3)
+      logstash-codec-json (~> 3.0)
+      logstash-core-plugin-api (>= 2.1.12, <= 2.99)
+      logstash-mixin-aws (>= 4.3)
logstash-input-snmp (1.3.1)
logstash-codec-plain
logstash-core-plugin-api (>= 1.60, <= 2.99)
@@ -864,6 +868,7 @@ DEPENDENCIES
logstash-input-pipe
logstash-input-redis
logstash-input-s3
+  logstash-input-s3-sns-sqs
logstash-input-snmp
logstash-input-snmptrap
logstash-input-sqs
``` …
=> Backport PR #13794 to 7.17: Feat: conservative plugin (dependency) updates by default

build.gradle, rakelib/vendor.rake
Detect a *Gemfile.lock* present when calling the *vendor:gems* rake task.
[rn:skip]
When preparing for running integration tests, the `gradlew :assembleTarDistribution` gets run, right after the initial bootstraping has completed (dependencies `bundle install`-ed). However, the task in some scenarios failed to respect the (copied) *Gemfile.lock* for the jruby-openssl requirement and still installed the latest version, as seen here: https://github.com/elastic/logstash/issues/13781#issuecomment-1041407935
This seems to be a Bundler bug, since the issue no longer reproduces (w Bundler 2.3.8). 
In either case, running an extra `bundle install` (from the `vendor:gems` task) which is triggered from the `:assembleTarDistribution` doing a `rake artifact:no_bundle_jdk_tar` is unnecessary and …
=> Build: avoid doing a redundant bundle install

build.gradle, rakelib/vendor.rake
**Backport PR #13820 to 7.17 branch, original message:**
The reason for this back-port is to potentially prepare for unlocking jruby-openssl which is now locked to 0.11,x in 7.17 ... this version does not support TLS 1.3 and thus some plugins won't be user update-able to a version that support latest TLS (whether the dependency unlock actually happens in 7.17 is undecided at this point).
---
Detect a *Gemfile.lock* present when calling the *vendor:gems* rake task.
[rn:skip]
When preparing for running integration tests, the `gradlew :assembleTarDistribution` gets run, right after the initial bootstraping has completed (dependencies `bundle install`-ed). However, the task in some scenarios failed to respect the (copied) *Gemfile.lock* for the jruby-openssl requirement and still installed …
=>  Backport PR #13820 to 7.17: Build: avoid doing a redundant bundle install

logstash-core/lib/logstash/api/commands/node.rb, logstash-core/lib/logstash/api/commands/stats.rb
- Fixes an issue where querying the stats API before any pipelines had been started could result in an HTTP 500 response.
Prevents an HTTP 500 response from being emitted when the event stats had not yet been populated, as is common during start-up, or when Logstash is configured to manage pipelines through Kibana Central Management and no pipelines have been defined.
Provide useful stats API output even when no pipelines are yet running.
1. Start up Logstash with Central Management configured, without any (matching) pipelines, and without …
=> api: avoid 5xx when stats/events not yet populated

tools/release/bump_plugin_versions.rb
[rn:skip]
Adds support for using a local lockfile when bumping plugin versions.
In the time between a minor release's feature freeze and its final build candidate, it is helpful to be able to bump plugin _patches_, in order to constrain the changes that go into the in-flight release, but to do so requires using the in-flight lockfile as a baseline.
This changeset empowers the release manager to use that local lockfile as a baseline, instead of the published artifact of a prior release. It was used to create #13680 and #13681
Reduces risk during release cycle, improving our confidence in releases
- ~[ ] I have …
=> tools: allow version bump to use local lockfile as baseline

docs/static/running-logstash-windows.asciidoc
At 8.0, we removed support for the JAVA_HOME variable. Users who need to use a java version other than the bundled JDK should use the `LS_JAVA_HOME` env variable instead. 
We are now bundling a JDK with Logstash. Unless users have a compelling reason to use a different version, we recommend that they use the bundled version. What documentation changes do we need to make to [Windows instructions](https://www.elastic.co/guide/en/logstash/master/running-logstash-windows.html#running-logstash-windows-validation) to align with changes/recommendations? 
Related: #13826
=> Doc: Correct name for java_home env variable in Windows section

x-pack/lib/filters/geoip/download_manager.rb, x-pack/spec/filters/geoip/download_manager_spec.rb, x-pack/spec/support/helpers.rb
Backport PR #13410 to 8.1 branch. Original message: 
- The GeoIP database lookup will respect a proxy defined with the `http_proxy` environment variable.
When instantiating the REST client for GeoIP database update lookups, a proxy specified with the `http_proxy` environment variable will now be propagated to Manticore, ensuring that the lookup traffic routes over the configured proxy. This mirrors old behavior that we got "for free" in previous releases of Logstash when we were using Faraday as our REST client, and lost when we swapped out our internals to use Manticore in #13273 
When running on a host whose outbound HTTP traffic must be routed through a proxy, the database manager now works as expected.
- ~[ ] I have made …
=> Backport PR #13410 to 8.1: geoip-db: support `http_proxy` environment variable

x-pack/lib/filters/geoip/download_manager.rb, x-pack/spec/filters/geoip/download_manager_spec.rb, x-pack/spec/support/helpers.rb
Backport PR #13410 to 7.17 branch. Original message: 
- The GeoIP database lookup will respect a proxy defined with the `http_proxy` environment variable.
When instantiating the REST client for GeoIP database update lookups, a proxy specified with the `http_proxy` environment variable will now be propagated to Manticore, ensuring that the lookup traffic routes over the configured proxy. This mirrors old behavior that we got "for free" in previous releases of Logstash when we were using Faraday as our REST client, and lost when we swapped out our internals to use Manticore in #13273 
When running on a host whose outbound HTTP traffic must be routed through a proxy, the database manager now works as expected.
- ~[ ] I have made …
=> Backport PR #13410 to 7.17: geoip-db: support `http_proxy` environment variable

logstash-core/lib/logstash/java_pipeline.rb, logstash-core/lib/logstash/outputs/base.rb, logstash-core/src/main/java/org/logstash/execution/JavaBasePipelineExt.java
Backports the following commits to 8.1:
- expose shutdown request state of pipeline (#13811)
=> [8.1] expose shutdown request state of pipeline (#13811)

rakelib/artifacts.rake
Backport PR #13715 to 8.1 branch. Original message: 
[rn:skip]
The `openssl_pkcs8_pure` gem dependency is a library for transforming key formats, and includes spec artifacts for validating its ability to transform key formats that are not useful at runtime. The presence of theses keys causes false alarms, so this PR ensures they are excluded from our built artifacts.
Allows our artifacts, or docker containers that import our artifacts, to not trigger false positives against some security policies.
=> Backport PR #13715 to 8.1: artifacts: omit openssl_pkcs8_pure specs from built artifacts

bin/benchmark.bat, bin/ingest-convert.bat, bin/logstash.bat, bin/pqcheck.bat, bin/pqrepair.bat, bin/setup.bat
Fix JVM path for Logstash CLI tools that used the JRuby launcher.
The JRuby interpreter accepts JVM selection through two environment variables:
- `JAVACMD` which points to the JVM executable
- `JAVA_HOME` which point to JDK home directory
Logstash CLI (command line) tools, like `bin\logstash-keystore.bat`, launches the JRuby interpreter directly, but while they setup the environment calling `setup.bat` the variable configured by the script is not the one expected by JRuby.
The `setup.bat` populate `JAVA` while JRuby expects `JAVACMD`.  
This PR does the rename, miming what's already done in `bash` scripts, which configures `JAVACMD`.  
Now the users that doesn't have any JVM installed, can run the CLI tools using the bundled JDK.
- ~~[ ] I have made corresponding changes to the …
=> Fix Logstash cli tools to use the selected JDK under Windows

rakelib/artifacts.rake
currently the artifact tasks compute the file listing from a list of
include regexes and exclude regexes. However this is done by hand,
taking each include regex and running it through each exclude regex.
This is quite slow as we add more exclude regexes. This PR changes to
totally relying on Rake::FileList, by feeding it the include and exclude
lists. This speeds up file listing from 150 seconds to 1 second.
Compare the speed of `rake artifact:archives` with and without this patch.
To know if this change still produces the same file list, you can add a new task under the `rakefile/artifacts.rake` file such as:
```ruby
task "test" do
puts Time.now
puts files().size
puts Time.now
end
```
Then running: `./gradlew clean installDefaultGems && rake artifact:test`
We can see it takes two …
=> speed up artifact file listing

.github/workflows/pr_backporter.yml
1. Explicitly deny content changes in the workflow
2. Move comment body to env var (GitHub's recommendation for user input sanitization https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable)
3. Restrict workflow to created comments (no updates/deletes)
4. Restrict workflow to an allowlist of users
=> Update pr backporter workflow

rakelib/artifacts.rake
**Backport PR #13862 to 8.1 branch, original message:**
---
currently the artifact tasks compute the file listing from a list of
include regexes and exclude regexes. However this is done by hand,
taking each include regex and running it through each exclude regex.
This is quite slow as we add more exclude regexes. This PR changes to
totally relying on Rake::FileList, by feeding it the include and exclude
lists. This speeds up file listing from 150 seconds to 1 second.
Compare the speed of `rake artifact:archives` with and without this patch.
To know if this change still produces the same file list, you can add a new task under the `rakefile/artifacts.rake` file such as:
```ruby
task "test" do
puts Time.now
puts files().size
puts Time.now
end
```
Then running: `./gradlew clean …
=> Backport PR #13862 to 8.1: speed up artifact file listing

rakelib/artifacts.rake
**Backport PR #13862 to 7.17 branch, original message:**
---
currently the artifact tasks compute the file listing from a list of
include regexes and exclude regexes. However this is done by hand,
taking each include regex and running it through each exclude regex.
This is quite slow as we add more exclude regexes. This PR changes to
totally relying on Rake::FileList, by feeding it the include and exclude
lists. This speeds up file listing from 150 seconds to 1 second.
Compare the speed of `rake artifact:archives` with and without this patch.
To know if this change still produces the same file list, you can add a new task under the `rakefile/artifacts.rake` file such as:
```ruby
task "test" do
puts Time.now
puts files().size
puts Time.now
end
```
Then running: `./gradlew clean …
=> Backport PR #13862 to 7.17: speed up artifact file listing

logstash-core/lib/logstash/config/pipelines_info.rb
Backport PR #13345 to 7.17 branch. Original message: 
[rn:skip]
Fixes an issue where an attempt to get pipeline info before a pipeline is fully-initialized can result in an opaque transient failure.
When a pipeline isn't fully initialized, we run the risk of attempting to
format pipeline info that isn't yet fully-shaped. By using safe-fallback
methods like `Hash#dig` and conditional-chaining, we can avoid the spurious
`NoMethodError` caused by sending `[]` to nil.
From what I can tell, there are three paths to access this:
- via Monitoring API when the issue is hit, a single monitoring event during startup fails to be emitted but the next scheduled event will fire off normally.
- via HTTP API when this  issue is hit, the request will likely result in an HTTP 500, but subsequent attempts …
=> Backport PR #13345 to 7.17: pipeline-info: increase safety of transforming stats

logstash-core/lib/logstash/api/commands/node.rb, logstash-core/lib/logstash/api/commands/stats.rb
Backport PR #13424 to 7.17 branch. Original message: 
- Fixes an issue where querying the stats API before any pipelines had been started could result in an HTTP 500 response.
Prevents an HTTP 500 response from being emitted when the event stats had not yet been populated, as is common during start-up, or when Logstash is configured to manage pipelines through Kibana Central Management and no pipelines have been defined.
Provide useful stats API output even when no pipelines are yet running.
1. Start up Logstash with Central Management …
=> Backport PR #13424 to 7.17: api: avoid 5xx when stats/events not yet populated

logstash-core/locales/en.yml
Backport PR #13244 to 7.17 branch. Original message: 
A number of plugins reach into Logstash's i18n translations to "helpfully" communicate certain configuration errors, but rely on translations that were moved in #3872 from logstash.agent to logstash.runner. Since then, it is possible to hit obtuse error messages about failing to load a translation instead of the intended helpful message:
~~~
translation missing: en.logstash.agent.configuration.invalid_plugin_register
~~~
By moving the `logstash.agent` definition to _after_ the `logstash.runner` definition, we can use YAML tooling to name the `logstash.runner.configuration` node and then merge its contents into `logstash.agent.configuration`. This effectively allows us to keep a single definition of those translations while making them …
=> Backport PR #13244 to 7.17: i18n: alias logstash.runner.configuration.* under logstash.agent.configuration

logstash-core/logstash-core.gemspec
Similarly to #13875, a recent update to jruby-openssl to 0.12.2 causes a
gem load error when trying to use `bin/logstash-plugin`. This commit pins the
gemspec in `logstash-core.gemspec` to match that in the lockfile.
=> Pin jruby-openssl in logstash-core to 0.12.1

versions.yml
Backport PR #13687 to 7.17 branch. Original message: 
https://www.oracle.com/java/technologies/javase/11-0-14-relnotes.html
=> Backport PR #13687 to 7.17: bump jdk to 11.0.14.1+1

versions.yml
**Backport PR #13687 to 8.1 branch, original message:**
---
https://www.oracle.com/java/technologies/javase/11-0-14-relnotes.html
=> Backport PR #13687 to 8.1: bump jdk to 11.0.14.1+1

lib/bootstrap/bundler.rb, lib/pluginmanager/install.rb, lib/pluginmanager/update.rb, spec/unit/plugin_manager/update_spec.rb
**NOTE: do not merge until 8.1.0 is released, this will be part of 8.1.1**
**Backport PR #13794 to 8.1 branch, original message:**
---
`bin/logstash-plugin install logstash-input-s3-sns-sqs`
```patch
diff --git Gemfile.lock Gemfile.lock
index b3d2b0b89..5c7742fd0 100644
--- Gemfile.lock
+++ Gemfile.lock
@@ -476,6 +476,10 @@ GEM
logstash-mixin-aws (>= 5.1.0)
logstash-mixin-ecs_compatibility_support (~> 1.2)
stud (~> 0.0.18)
+    logstash-input-s3-sns-sqs (2.1.3)
+      logstash-codec-json (~> 3.0)
+      logstash-core-plugin-api (>= 2.1.12, <= 2.99)
+      logstash-mixin-aws (>= 4.3)
logstash-input-snmp (1.3.1)
logstash-codec-plain
logstash-core-plugin-api (>= 1.60, <= 2.99)
@@ -864,6 +868,7 @@ DEPENDENCIES
logstash-input-pipe
logstash-input-redis
logstash-input-s3
+ …
```
=> Backport PR #13794 to 8.1: Feat: conservative plugin (dependency) updates by default

bin/benchmark.bat, bin/ingest-convert.bat, bin/logstash.bat, bin/pqcheck.bat, bin/pqrepair.bat, bin/setup.bat
**Merge after 8.1.0 is out**
Clean backport of #13839 to branch `8.1`
----
Some Logstash tools invokes directly the JRuby intepreter. The interpreter uses the JVM pointed by two environment variables:
- JAVACMD
- JAVA_HOME\bin\java.exe
The setup.bat script exported the selected JVM under the env var named JAVA, which isn't recognized by vendored jruby.
This commit fixes it renaming to JAVACMD.
(cherry picked from commit 0084492494c0629cf76aa8d955a13d01b66c84dc)
=> [Backport 8.1]Fix Logstash cli tools to use the selected JDK under Windows (#13839)

docs/static/persistent-queues.asciidoc
Explicitly say the `page_capacity` is allowed to change and the queue size checking happens at startup
Fixed: #8650, #10718
=> [Doc] update queue.max_bytes and queue.page_capacity

tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/et-orbi-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/fugit-NOTICE.txt, tools/dependencies-report/src/main/resources/notices/raabro-NOTICE.txt
[rn:skip] 
These dependencies are Rufus transitive deps, included by JDBC integration plugin v5.2.4
=> Updates license checker after inclusion of libs `et-orbi`, `fugit` and `raabro`.

logstash-core/logstash-core.gemspec
This reverts commit 887d9427d3ba7887760db1777f66c48333a1132c from #13866
Logstash 8.1.0 shipped with `~> 0.11.0` we should keep the dependency unlocked, if possible.
Keeping the version requirement non-strict allows to upgrade the jruby-openssl dependency with the 8.1.x bump gem lifecycle and also allows for manual plugin upgrades plugins with plugins that require specific versions of the library (such as TCP input).
---
The problem #13866 is trying to work-around should be resolved with https://github.com/elastic/logstash/pull/13823
=> Deps: unpin jruby-openssl in logstash-core

bin/benchmark.bat, bin/ingest-convert.bat, bin/logstash.bat, bin/pqcheck.bat, bin/pqrepair.bat, bin/setup.bat
Clean backport of #13881 to branch `8.1`
----
Updates all Windows batch scripts used as CLI tools to quotes the %JAVACMD% to avoid path problems when the path contains spaces.
(cherry picked from commit a8bd90c22de451514940cdddcd60ae4f19d80405)
=> [Backport #13881 8.1]Quotes java executable path in case it contains spaces

bin/benchmark.bat, bin/ingest-convert.bat, bin/logstash.bat, bin/pqcheck.bat, bin/pqrepair.bat, bin/setup.bat
Clean backport of #13881 to `7.17`
----
Updates all Windows batch scripts used as CLI tools to quotes the %JAVACMD% to avoid path problems when the path contains spaces.
(cherry picked from commit a8bd90c22de451514940cdddcd60ae4f19d80405)
=> [Backport #13881 7.17]Quotes java executable path in case it contains spaces

bin/logstash.lib.sh, bin/setup.bat, build.gradle, buildSrc/src/main/groovy/org/logstash/gradle/tooling/ExtractBundledJdkVersion.groovy, buildSrc/src/main/groovy/org/logstash/gradle/tooling/ToolingUtils.groovy, buildSrc/src/test/groovy/org/logstash/gradle/tooling/ExtractBundledJdkVersionTest.groovy, rakelib/artifacts.rake
[rn:skip]
Extracts the bundled JDK's version into a one-line text file which could easily read and printed from bash/batch scripts.
Updates Logstash's bash/batch launcher scripts to print the bundled JDK version when warn the user about his override.
Give information about the JDK version that is bundled with distribution, so that he can immediately compare which environment's provided one.
- checkout this branch
- build archives packs with: 
```
rake artifact:archives
```
- set an `LS_JAVA_HOME` to locally installed JDK
- unpack the archive for your OS and run 
```
bin/logstash -e "input{ stdin { } } output { stdout { …
```
=> Print bundled jdk's version in launch scripts when `LS_JAVA_HOME` is provided

.github/workflows/pr_backporter.yml
PR backports need to create branches remotely which serve as target branches for the backport pull requests.
Safety is ensured by checking that only Logstash team members can trigger the workflow.
=> Enable content write permission for pr backporter workflow

rakelib/artifacts.rake
Ruby allows methods to have default values in arguments if they're not
passed. However if a nil is passed then the default value isn't used.
The artifact:archives tasks were passing nil values to the exclusion
argument, causing all files to be included in the package.
This commit cleans the naming of the path lists and ensures the default
exclusion list is always used.
To test this the reviewer can run `rake artifact:archives` and then confirm that the produced archives don't include files such as "bin/bundle" or in the case of OSS archives, the "x-pack" folder.
=> fix default argument handling in rake artifact task

logstash-core/locales/en.yml
Backport PR #13244 to 8.1 branch. Original message: 
A number of plugins reach into Logstash's i18n translations to "helpfully" communicate certain configuration errors, but rely on translations that were moved in #3872 from logstash.agent to logstash.runner. Since then, it is possible to hit obtuse error messages about failing to load a translation instead of the intended helpful message:
~~~
translation missing: en.logstash.agent.configuration.invalid_plugin_register
~~~
By moving the `logstash.agent` definition to _after_ the `logstash.runner` definition, we can use YAML tooling to name the `logstash.runner.configuration` node and then merge its contents into `logstash.agent.configuration`. This effectively allows us to keep a single definition of those translations while making them …
=> Backport PR #13244 to 8.1: i18n: alias logstash.runner.configuration.* under logstash.agent.configuration

versions.yml, x-pack/lib/config_management/elasticsearch_source.rb, x-pack/lib/helpers/loggable_try.rb, x-pack/lib/license_checker/license_reader.rb, x-pack/qa/integration/management/read_configuration_spec.rb, x-pack/spec/license_checker/license_reader_spec.rb
Fix bug in retrieving pipeline configuration from central management and license validation which make Logstash process crash if a configured node of the Elasticsearch cluster is down.
Wraps the calls to the central management Elasticsearch cluster with the utility class `Stud::Try` to handle the remote  host error when the client used to connect hit a not available node.
Central Management Elasticsearch node list is configured in `logstash.yml` file. If any of those Elasticsearch nodes is down when Logstash starts and hits one of down nodes then it could be that the license check fails and crash Logstash or that the not handled host error exception avoid to receive the pipelines updates.
With this fix the maintenance of an configuration cluster node doesn't prevent the Logstash start.
- …
=> Update failing policy in Central Management fetcher and license checker if hit ES down node

build.gradle, config/jvm.options, logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java, logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
After #13700 updated google-java-format dependency, it is now required to add a number of `--add-export` flags in order to run on JDK17. This commit adds these flags to the jvm options for a running logstash, and to the tests running on gradle to enable tests to still work
Note: If you use custom `jvm.options`, you will need to add the following settings to `config.jvm.options` to allow Logstash to start:
```
11-:--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
11-:--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
11-:--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
11-:--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
11-:--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```
Without these additional settings, …
=> [Java17] Add `--add-export` settings to restore JDK17 compatibility

logstash-core/lib/logstash/api/commands/stats.rb
This commit guards against reading a value from a stat that may not be
populated before an attempt is made to retrieve its value, potentially causing
a `undefined method `[]' for nil:NilClass`.
[rn:skip]
This has resulted in some flaky tests lately, which should be fixed with this change
=> Improve safety of stats retrieval from queue

lib/bootstrap/rspec.rb, qa/integration/specs/cli/prepare_offline_pack_spec.rb, qa/integration/specs/command_line_spec.rb
The `prepare_offline_spec.rb` had essentially become a "canary" for discovering new JVM warnings and error messages, being the only test that would fail when they would appear due to the way the test was constructed.
This commit simplifies this regex to only test for what is expected in that test, and introduces an explicit test for discovering new JVM warnings and error messages.
[rn:skip]
=> [Test] Adds explicit unexpected JVM messages test, and simplifies regex in offline_spec

docs/static/running-logstash.asciidoc, docs/static/shutdown.asciidoc
Updates the documentation to remove sys-v init and upstart references when running Logstash as a service, given that upstart and sys-v are no longer supported.
**PREVIEWS:**
* https://logstash_13953.docs-preview.app.elstc.co/guide/en/logstash/master/running-logstash.html
* https://logstash_13953.docs-preview.app.elstc.co/guide/en/logstash/master/shutdown.html
Provides up to date information to the user.
- Relates #13922
=> [doc] Remove references to sysv and upstart scripts when running logstash as a service.

logstash-core/logstash-core.gemspec
**DE-JA-VU of https://github.com/elastic/logstash/pull/13903 as I messed up the unpinning** (~> 0.11.0 does not allow to install 0.12.x)
JOSSL pinning was introduced at https://github.com/elastic/logstash/pull/13806 ... the cause being https://github.com/elastic/logstash/pull/13785
[rn:skip]
Unlocks the jruby-openssl dependency in order to allow manual updates of plugins that require the gem.
Also, JRuby is tested/shipped with latest JOSSL, given the security nature of the library it makes sense to keep updating.
User should be able to update plugins that require newer jruby-openssl version (such as the TCP input).
=>  Deps: unpin jruby-openssl in logstash-core (for real)

logstash-core/spec/logstash/persisted_queue_config_validator_spec.rb
Fixed: #13957
windows platform fails to generate desired file size with `#truncate()`, hence failing the test.
This branch passed [window test](https://logstash-ci.elastic.co/job/elastic+logstash+main+multijob-windows-compatibility/96/)
=> Fix window CI for PQ size checking

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent_spec.rb
Certain errors during pipeline converge will emit an IllegalStateException - for example attempting
to reference an environment variable that does not exist. Attempting to add a java exception to the
converge result would result in an uncaught exception in a pipeline thread leading to an unclean
shutdown.
This had the effect of, prior to this commit, Logstash behaviour varying depending on the class of
error that caused a pipeline not to start - an invalid pipeline configuration would still enable
logstash to start other pipelines in a multiple pipeline configuration, or automatic reloading
enabling changes to the configuration to allow the pipeline to start(in multi- and single pipeline
configurations).
However, a missing environment variable would cause Logstash to crash hard no matter …
=> Convert Exception during converge to a failed action

logstash-core/lib/logstash/agent.rb, logstash-core/spec/logstash/agent_spec.rb
When logstash is run without automatic reloading, it is still possible to reload configurations
by using 'SIGHUP'. This functionality was broken in #12444, which split non-terminated pipelines
into "loading" and "running" states. The call `no_pipelines?` in agent#execute would no longer
find pipelines in a "loading" state, causing the loop to exit, and logstash to shutdown. This
commit tests for pipelines in a "loading" state to restore functionality
Fix support for reload of pipelines via `SIGHUP`
- Run Logstash with `config.reload.automatic` set to `false
- Update pipeline configuration
- `kill -1 <pid>`
- Note that …
=> Fix reload of pipelines via `SIGHUP`

logstash-core/lib/logstash/agent.rb, logstash-core/lib/logstash/pipelines_registry.rb
As pointed out in this post merge review comment, there is a window
where we could miss a pipeline transitioning from 'loading' to 'running'
in the original fix, as separate calls are made to the pipeline registry.
This commit fixes that by making a single call to the pipeline registry which
allows for also returning pipelines in the `loading` state.
Co-authored-by: Ry Biesemeyer <yaauie@users.noreply.github.com>
=> Further improve check on "running pipelines" after SIGHUP

lib/pluginmanager/util.rb, logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java, logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java, logstash-core/src/main/java/org/logstash/plugins/aliases/AliasDocumentReplace.java, logstash-core/src/main/java/org/logstash/plugins/aliases/AliasPlugin.java, logstash-core/src/main/resources/org/logstash/plugins/AliasRegistry.yml, logstash-core/src/test/resources/org/logstash/plugins/AliasRegistry.yml, spec/unit/plugin_manager/util_spec.rb
A structural change of aliased plugins declaration to support alias doc headers to replace.
When plugin reference doc generator workflow runs it generates a document for artifact plugin but not for aliased plugins. Aliased plugin docs are copy of artifact plugins with different doc headers. This PR helps to define the doc header where doc generator can use to generate the doc for alised plugins. `replaces` field especially is helpful to create a aliased plugin doc header by replacing artifact doc entries.
- Unit tests
- Build Logstash, run and check
- Closes [#69 Add alias params declarations in logstash AliasRegistry.yml and manipulate in doc-tools](https://github.com/elastic/docs-tools/issues/69)
User logger to log the `extractDefinitions() -> aliasedPlugins & defaultDefinitions vars`: …
=> A structural change for aliased plugin declarations to support alias doc headers.

docs/static/ls-ls-http.asciidoc
**PREVIEW:** https://logstash_13973.docs-preview.app.elstc.co/guide/en/logstash/master/ls-to-ls-http.html
Adds documentation showing users how to configure Logstash to Logstash using HTTP.
Because we have been recommending the use of HTTP as an alternative to using Lumberjack for Logstash to Logstash communication.
=> [doc] Add Logstash to Logstash HTTP example configuration.

docs/static/jvm.asciidoc
Fixes a typo in the docs indicating users the bundled JDK is 17, not JDK 11.
Because it is leading them to believe that 8.1 and earlier has bundled JDK17 (and not 11 as it currently is).
=> Fix Bundled JDK docs to reflect JDK 11

logstash-core/build.gradle, logstash-core/lib/logstash/plugins/registry.rb, logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java, logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java, logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java, logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
The current implementation of AliasRegistry will create an instance of the Alias Registry for each
pipeline, which appears to potentially result in situations, such as in #13996, where multiple pipelines
are simultaneously loading an alias registry from a yaml file in the jar file using getResourceAsStream, with
the potential of the first thread closing the jar file underneath subsequent threads, leading to errors when
reading the yaml file as the JarFile has been closed after the initial thread completed accessing.
This commit changes the AliasRegistry to be a singleton, as is the PluginRegistry.
Relates: #13996, #13666
=> Make AliasRegistry a singleton

logstash-core/lib/logstash/pipeline_action/stop_and_delete.rb, logstash-core/lib/logstash/state_resolver.rb, logstash-core/spec/logstash/agent/converge_spec.rb, logstash-core/spec/logstash/state_resolver_spec.rb, logstash-core/spec/support/matchers.rb
This commit makes the `stop` and `delete` pipeline action into a single action to make sure the running pipeline is deleted in registry if central pipeline management delete and recreate pipelines in short period of time
Prior to this change, when the source (central pipeline management / kibana) delete a pipeline, the Logstash pipeline state transforms from stop to delete in two converge cycles. If the source recreates the same pipeline between the cycles, the stop pipeline cannot be deleted in registry because Logstash see them as graceful finish.
1. In Kibana > Logstash pipelines, create a `test` pipeline
2. Logstash start with xpack
3. Delete `test` pipeline in Kibana. Logstash will delete `test` pipeline in the coming converge cycle. The log show `test ` in non_running_pipelines
4. …
=> Fix stopped pipeline unable to be deleted in registry

.github/workflows/add-docs-preview-link.yml
v1 seems to have started failing with: 
```
Run thollander/actions-comment-pull-request@v1
with:
message: :page_with_curl: **DOCS PREVIEW** :sparkles: https://logstash_14019.docs-preview.app.elstc.co/diff
Note: if you get a "404!" please wait until the elasticsearch ci job finishes.
GITHUB_TOKEN: ***
Error: Resource not accessible by integration
```
[rn:skip]
TESTED AT https://github.com/elastic/logstash/pull/14037 (the PR has the preview link), seems to back to :green_heart:
=> CI: try different version of GH action

docs/index.asciidoc, docs/static/management/configuring-centralized-pipelines.asciidoc
Our central management topics are split across two sections with links back and forth. The central management content needs some work (see meta issue #14049), but grouping these similar topics is a good first step. 
And then two sections later...
=> Doc: Group central mgmt and configuring central mgmt topics

logstash-core/lib/logstash/plugins/registry.rb, logstash-core/src/main/java/org/logstash/plugins/PluginClassLoader.java, qa/integration/fixtures/install_java_plugin_spec.yml, qa/integration/specs/install_java_plugin_spec.rb
Prior to this commit, attempting to use a custom java plugin installed from rubygems would
fail as the `files` field used to find jar files in the gem is not populated for such gems
This commit uses the `full_require_path` to find the jar file for a native jar plugin,
which should work regardless of where the gem was installed from, locally or via rubygems
Additionally, this commit will only attempt to locate the jar file inside the gem when it
is required (only when the experimental separate plugin class loader is used)
This commit builds on the work done in https://github.com/elastic/logstash/pull/13888
Relates: https://github.com/elastic/logstash/pull/13888, https://github.com/elastic/logstash/issues/11305
- Fixes an issue where custom java plugins were unable to be installed and run …
=> Fix plugin classloading

logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
[rn:skip]
Fix the test checking condition, deletion of DLQ tail segments files already skips the head `log.tmp` file
=> Fix flaky test, the writer head segment is not a tail segment

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java, logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
Exposes the counter of events dropped from the DLQ, and the last error reason.
Adds some metrics to the dead_letter_queue part of the monitoring endpoint `_node/stats/pipelines/`, precisely under the path `pipelines.<pipeline name>.dead_letter_queue`. The metrics added are:
- `dropped_events`: count the number of dropped events caused by "queue full condition", when `drop_newer` storage policy is enabled, happened to this DLQ since the last restart of Logstash process.
- `last_error`: a string reporting the last error registered for DLQ dropping condition.
-  `max_queue_size`: like for PQ it's the maximum size that the DLQ can reach.
The user can monitor the size of the DLQ, the counter of dropped events and the last error message string.
- ~~[ ] I have made corresponding changes to the …
=> Adds DLQ drop counter and last error metrics into management API

logstash-core/lib/logstash/java_pipeline.rb, logstash-core/lib/logstash/worker_loop_thread.rb, logstash-core/spec/logstash/shutdown_watcher_spec.rb, logstash-core/src/main/java/org/logstash/execution/ShutdownWatcherExt.java, logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java, logstash-core/src/test/java/org/logstash/execution/ShutdownWatcherExtTest.java, logstash-core/src/test/resources/shutdown_watcher_ext_pipeline_template.rb
This will backport the following commits from `main` to `7.17`:
- [Hide Shutdown Watcher stall message when PQ draining (#13934)](https://github.com/elastic/logstash/pull/13934)
=> [7.17] Hide Shutdown Watcher stall message when PQ draining (#13934)

logstash-core/lib/logstash/config/source/multi_local.rb
YAML.load should be avoided in favor of safe_load. Also IO.read accepts pipes which is an unnecessary capability, so it can be replaced by File.read:
```
irb(main):003:0> IO.read("| date")
=> "Thu Mar 10 15:18:11 WET 2022\n"
irb(main):004:0> File.read("| date")
Traceback (most recent call last):
10: from /Users/joaoduarte/tools/jruby-9.3.3.0/bin/irb:23:in `<main>'
9: from org/jruby/RubyKernel.java:1052:in `load'
8: from /Users/joaoduarte/tools/jruby-9.3.3.0/lib/ruby/gems/shared/gems/irb-1.0.0/exe/irb:11:in `<main>'
7: from org/jruby/RubyKernel.java:1237:in `catch'
6: from org/jruby/RubyKernel.java:1237:in `catch'
5: from org/jruby/RubyKernel.java:1507:in `loop'
4: from org/jruby/RubyKernel.java:1091:in `eval'
3: from (irb):4:in `evaluate'
2: from org/jruby/RubyIO.java:3986:in `read'
1: …
```
=> Ensure pipelines.yaml is loaded safely

.github/workflows/add-docs-preview-link.yml, docs/static/settings-file.asciidoc
[rn:skip]
The simple idea here is to use `on: pull_request_target` instead of `on: pull_request` - meaning the action will run with credentials as if the PR is opened from the origin (even if the source is from a fork) - the only downside should be that the *workflow.yml* will be always taken from the origin (elastic/logstash) repo, even if updated in the PR!
Second I've added a step to wait till the docs-preview CI finishes on the PR and the comment is only posted afterwards.
=> CI: improve doc-preview action

.github/workflows/add-docs-preview-link.yml, docs/static/settings-file.asciidoc
following up on https://github.com/elastic/logstash/pull/14067
this gets the wait work-flow polling the proper commit ref status -> and than (when docs CI finishes) triggers the comment action as expected!
demonstration that things worked at: https://github.com/elastic/logstash/pull/14096
(the URL does not have the docs diff and gives a 404 but that is smt with Jenkins CI)
=> CI: docs preview comment working, for real

docs/static/dead-letter-queues.asciidoc, docs/static/persistent-queues.asciidoc
- adds Tips to PQ and DLQ to suggest not to use NFS as storage
- remove `queue.max_bytes` part as size checking for multiple pipelines is released
Fixed: #12097
=> [Doc] PQ and DLQ does not support NFS

logstash-core/src/main/java/org/logstash/common/io/RecordIOReader.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java, logstash-core/src/test/java/org/logstash/common/io/RecordIOReaderTest.java
Bugfix a seek problem into the dead letter queue reader when asked to restart consuming from specific point.
Adds some tests to proof that the offset position retrieved from the `RecordIOReader` effectively point to the start of the next available event and not to the last channel position retrieved.
Adds fixes for the problem, moving the concept of `channelPosition` to `streamPosition` differentiating the position on the stream from the position on the channel. However the already published interface (method `getChannelPosition`) is not renamed to avoid the introduction of a breaking  change.
Dead letter queue input plugin stores the position of the DLQ at [`close`](https://github.com/logstash-plugins/logstash-input-dead_letter_queue/blob/9f80a84fef48a62bd0602d467cbeb02faba59c61/src/main/ …
=> Fix of DLQ stream position retrieval

logstash-core/logstash-core.gemspec
Version 2.6.2 of json will not install under jruby - https://github.com/flori/json/issues/497
This commit pins to the previous version until the issue is resolved.
=> Restrict json to avoid 2.6.2 until upstream jruby issue is solved

qa/integration/fixtures/monitoring_api_spec.yml, qa/integration/specs/monitoring_api_spec.rb
This commit ends the integration test with teardown instead of sending a signal to kill
Tested in https://github.com/elastic/logstash/pull/14103 https://github.com/elastic/logstash/pull/14102
Related: #13935
CI: https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-pq-1/5362/console
**Log**
20:17:06       1) Test Monitoring API verify global event counters when a drop filter is in the pipeline expose the correct output counter
20:17:06          Failure/Error: Unable to find matching line from backtrace
20:17:06          
20:17:06            expected: 1
20:17:06                 got: 5001
20:17:06          
20:17:06            (compared using ==)
20:17:06 
20:17:06     Finished in 26 minutes 3 seconds (files took 5.21 seconds to load)
20:17:06     35 …
=> fix monitoring api integration test with draining queue

logstash-core/lib/logstash/agent.rb, qa/integration/fixtures/monitoring_api_spec.yml, qa/integration/services/logstash_service.rb, qa/integration/specs/monitoring_api_spec.rb
This will backport the following commits from `main` to `7.17`:
- [Allow metrics update when PQ draining (#13935)](https://github.com/elastic/logstash/pull/13935)
- [fix monitoring api integration test with draining queue (#14106)](https://github.com/elastic/logstash/pull/14106)
=> [7.17] Allow metrics update when PQ draining (#13935) | fix monitoring api integration test with draining queue (#14106)

logstash-core/lib/logstash/agent.rb, qa/integration/fixtures/monitoring_api_spec.yml, qa/integration/services/logstash_service.rb, qa/integration/specs/monitoring_api_spec.rb
This will backport the following commits from `main` to `8.2`:
- [Allow metrics update when PQ draining (#13935)](https://github.com/elastic/logstash/pull/13935)
- [fix monitoring api integration test with draining queue (#14106)](https://github.com/elastic/logstash/pull/14106)
=> [8.2] Allow metrics update when PQ draining (#13935) | fix monitoring api integration test with draining queue (#14106)

config/logstash.yml, docker/data/logstash/env2yaml/env2yaml.go, docs/static/settings-file.asciidoc, logstash-core/lib/logstash/environment.rb, logstash-core/lib/logstash/runner.rb, logstash-core/spec/logstash/runner_spec.rb
Some of Logstash members missed to review the [`running Logstash as superuser` feature PR](https://github.com/elastic/logstash/pull/14046) and at a glance configuration flag for this feature brought a confusion. Changing `on_superuser` to `allow_superuser` seems better to clear the confusion as well as gives a clear message to end users.
Gives a clear message to customer with descriptive variable name.
Cases:
1. Running Logstash as a superuser with block mode
- `allow_superuser: false` in `logstash.yaml`
- run with `sudo ./bin/logstash`
- Output: `[2022-05-11T11:40:22,324][FATAL][logstash.runner] An unexpected error occurred! {:error=>#<RuntimeError: Logstash cannot be run as superuser.>, ....`
2. Running Logstash as a superuser with allow mode
- `allow_superuser: true` in `logstash.yaml` …
=> Change on_superuser to run_as_superuser to clear a confusion.

x-pack/lib/config_management/elasticsearch_source.rb, x-pack/spec/config_management/elasticsearch_source_spec.rb
Now Logstash is able to fetch pipelines from Central Pipeline Management based on its pipeline IDs, including wildcard ones.
Improves loading pipeline configurations from CPM where now Logstash loads only ROI configurations based on its pipeline IDs.
- Unit tests
```
bin/rspec x-pack/spec/config_management/elasticsearch_source_spec.rb:418 x-pack/spec/support/helpers.rb
```
- Enable CPM management in `logstash.yml` file
```
xpack.management.enabled: true
xpack.management.pipeline.id: ["main", "exampleWildcardPipe*", "*agentsPipeline*"]
```
And run Logstash (`bin/logstash`). Logstash will load `main` and any pipelines starts with `exampleWildcardPipe` (eg: exampleWildcardPipeline1) from CPM (if exists).
- Closes #13868
- ES is supposed to support wildcard search feature (see [the …
=> [CPM] Fetch pipelines with wildcard IDs from ES and apply.

logstash-core/logstash-core.gemspec
Pins our dependency on ConcurrentRuby temporarily until usage of the now-removed TimerTask can be properly replaced.
ConcurrentRuby's TimerTask is currently the method by which instrumentation and monitoring features enforce timeouts when querying unresponsive APIs, and its implementation has been removed from ConcurrentRuby v1.1.10. While we need to migrate to a different timeout solution, using a flawed TimerTask is better than no timeouts.
- ~[ ] I have added tests that prove my fix is effective or that my feature works`
- Relates: https://github.com/elastic/logstash/issues/13956
- `8.2` -> `8.2.1`
=> deps: pin concurrent-ruby pending removal of TimerTask

docs/static/settings-file.asciidoc
[rn:skip]
Adds a few missing "(`queue.type: persisted`)" from the [logstash.yml](https://www.elastic.co/guide/en/logstash/8.2/logstash-settings-file.html) documentation page
Finish explicitly indicating which settings apply to persistent queues (PQs).
N/A
- Closes #12536
Removes confusion around which `queue.*` settings apply to memory or persisted queue types.
N/A
N/A
=> Doc: Update settings file doc to call out queue type

lib/bootstrap/bundler.rb, qa/integration/specs/cli/install_spec.rb
When run in debug mode, #invoke was returning an instance of UI::Shell rather
than a string, causing the plugin to crash when `<<` was called on.
This commit ensures that a string is returned regardless of whether debug is set
Fixes: #14131
=> Fix debug output for bin/logstash-plugin

logstash-core/src/main/java/org/logstash/Valuefier.java, logstash-core/src/test/java/org/logstash/ValuefierTest.java
enhancement
This change allows Java logstash plugins to use `java.time.LocalDate`, `java.time.LocalDateTime` and `java.time.ZonedDateTime` objects in , `org.logstash.Event` classes. As the `java.time.Instant` class is already supported by `org.logstash.Timestamp`, there is no functional change required to the underlying classes. 
This improves the usability of the logstash java api for contributing plugins as it means users do not need to manually serialize java.time objects to Strings in order to add to events and can simply utilise the already available Ruby Timestamps.
- [ x ] My code follows the style guidelines of this project
~~- [ ] I have …
=> Add value converters for java.time

logstash-core/logstash-core.gemspec
[rn:skip]
As recently as Logstash 8.2.0, we have effectively shipped with a well-aged Rufus Scheduler v3.0.9, but as things stand on snapshot builds we are pulling in a much more modern Rufus 3.8.x which causes specs for plugin shutdowns to fail throughout our plugins (example: [failing when unpinned](https://app.travis-ci.com/github/logstash-plugins/logstash-input-elasticsearch/builds/251011998), vs [succeeding when pinned](https://app.travis-ci.com/github/logstash-plugins/logstash-input-elasticsearch/builds/251022115))
I am very wary of pinning the dependency in the individual plugins, and only slightly less wary about doing so here on LS core because doing so will make it significantly more difficult to migrate those plugins in the future. But I also don't want to ship a …
=> deps: pin rufus-scheduler to 3.7.x

build.gradle, versions.yml
Newer versions of the JDK are only available from api.adoptium.net, and not dual hosted on api.adoptopenjdk.net
This commit allows the use of adoptium versions of the JDK.
Relates: #14072
=> Switch adoptopenjdk url to adoptium

logstash-core/lib/logstash/settings.rb, logstash-core/lib/logstash/webserver.rb
Reverts 2 accidental commits that were pushed directly to `main`:
~~~
╭─{ yaauie@maybe:~/src/elastic/ls (✔ revert-accidental) }
╰─● git revert 67cdbb050 46b71b1cd
[revert-accidental 145379737] Revert "Improve log readability and remove extra logging."
2 files changed, 2 insertions(+), 1 deletion(-)
[revert-accidental 679ef3f93] Revert "Password policy deprecation log fixup."
1 file changed, 1 insertion(+), 10 deletions(-)
[success (00:00:12)] 
~~~
=> Revert accidental

.github/workflows/version_bumps.yml
Being a "choice" type parameter required frequent PRs every time there's a new minor. This commit changes the field to take a string instead.
=> Make version bump action "branch" parameter free form

docs/static/releasenotes.asciidoc
We missed forwardporting release notes for 8.1.1, 8.1.2, and 8.1.3 to future branches.  
This PR adds release notes from #13907, #13940, and #13984. 
Disclosure: Cherry-picking and conflict resolution got dicey, and I went with a manual copy/paste as it seemed like a safer choice. 
**PREVIEW:** https://logstash_14169.docs-preview.app.elstc.co/guide/en/logstash/master/releasenotes.html
Backports needed: 8.3, 8.2
=> Doc: Add missing release notes

docs/static/releasenotes.asciidoc
Replace url with PR number for consistency with other release notes entries
No forwardports needed.  Already corrected in #14148 and #14167
=> Doc: Add PR number as link text in release notes

Gemfile.template
[rn:skip]
Dependency restriction, due the *elasticsearch* dependency.
Elasticsearch client is used in *logstash-input-elasticsearch* and *logstash-filter-elasticsearch*.
The client has a transitive dependency on [faraday '-> 1'](https://rubygems.org/gems/elasticsearch-transport/versions/7.17.1) (even [in 8.x](https://rubygems.org/gems/elastic-transport/versions/8.0.1))
Avoids ruby unit test failures (such as [this](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-ruby-unit-tests/5508/console))
Users would not end up with latest versions of the ES plugins if we're using latest Faraday 2.x.
This mostly concerns development and users checking out the main branch atm.
- https://github.com/elastic/logstash/pull/14184
=> Deps: lock faraday to 1.x due elasticsearch-transport

Gemfile.template
**Backport PR #14185 to 8.3 branch, original message:**
---
[rn:skip]
Dependency restriction, due the *elasticsearch* dependency.
Elasticsearch client is used in *logstash-input-elasticsearch* and *logstash-filter-elasticsearch*.
The client has a transitive dependency on [faraday '-> 1'](https://rubygems.org/gems/elasticsearch-transport/versions/7.17.1) (even [in 8.x](https://rubygems.org/gems/elastic-transport/versions/8.0.1))
Avoids ruby unit test failures (such as [this](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-ruby-unit-tests/5508/console))
Users would not end up with latest versions of the ES plugins if we're using latest Faraday 2.x.
This mostly concerns development and users checking out the main branch atm.
- …
=> Backport PR #14185 to 8.3: Deps: lock faraday to 1.x due elasticsearch-transport

docs/static/setting-up-logstash.asciidoc
Removes the documentation related to startup.options and system-install. Follow-up from https://github.com/elastic/logstash/pull/12415.
The latest version of Logstash packages no longer rely on `startup.options` nor `system-install` to install and create system files. This is because Logstash used to create these files on the fly during the post-installation of the packages, which was a non-standard, policy recommended way of doing so, that was prone to failure. Instead, Logstash changed this to properly ship and install these files.
However, the documentation never got removed and users are now being confused as they think Logstash still relies on the mentioned files to create systemd units and related files.
=> Remove startup.options and system-install docs

logstash-core/lib/logstash/settings.rb, logstash-core/lib/logstash/webserver.rb
[rn:skip]
Fixes the deprecation logging of the password policy. The issue is, when we upgrade Logstash (eg. 8.3.0 to 8.3.1+) current deprecation logging will be produced even default value (`WARN`) of `api.auth.basic.password_policy.mode` changes to `ERROR`.
Does not produce the (wrong log) deprecation noise to end users.
- Enable the basic auth type and provide credentials: `api.auth.type: basic`
- Run Logstash and find the deprecation log, outcome should look like:
```
[2022-05-24T15:52:39,996][WARN ][deprecation.logstash.webserver] The default value of `api.auth.basic.password_policy.mode` will change to `ERROR` in a …
```
=> Fix deprecation logging of password policy.

NOTICE.TXT, tools/dependencies-report/src/main/resources/licenseMapping.csv, tools/dependencies-report/src/main/resources/notices/netty-NOTICE.txt
This commit adds netty to the licence mappings so that it can
get picked up by the dependency report tool.
=> Add licence mapping for netty

lib/pluginmanager/templates/codec-plugin/lib/logstash/codecs/example.rb.erb, lib/pluginmanager/templates/filter-plugin/lib/logstash/filters/example.rb.erb, lib/pluginmanager/templates/input-plugin/lib/logstash/inputs/example.rb.erb, lib/pluginmanager/templates/input-plugin/spec/inputs/example_spec.rb.erb
Fixes small issues when generating input and/or filter plugins to include the `plugin_name` rather than just `""`
Two things.
1. switches usage in the `templates/*/example.rb.erb` files from using `@plugin_name` to just `plugin_name`, as the desired value is not available as an instance variable. Most usages were already using `plugin_name`, but a few were not.
2. adds `require 'logstash/devutils/rspec/shared_examples'` to the generated input plugin spec, which is necessary for the generated spec to pass.
Without these changes, a user who generates an input plugin may think that the generation was faulty, as the tests do not pass right away, and the generated example cannot be referenced because the `config_name` ends up being `""` instead of `plugin_name`. This decreases confidence in …
=> Added necessary require, removed instance variable usage of plugin_name

logstash-core/spec/logstash/util/buftok_spec.rb, logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
[rn:skip]
The issue avoids using the 'interal' JRuby (Ruby method) impl API for doing a `String#split`.
This is expected to be safer - the Java equivalent is not expected to have side effects with global variables.
Also clarified the use-case - we never used `BufferedTokenizer.new delimiter = /regex/` which might have had consequences depending on the caller frame (e.g. setting the `$~` last match).
No impact expected.
- follow-up on the JRuby upgrade (#14114) as the API is only available with JRuby 9.3
=> Refactor: use Java API for RubyString#split

logstash-core/spec/logstash/java_integration_spec.rb, logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java
since JRuby 9.3 a useful inspect is provided out of the box
LS' inspect: `<Java::JavaUtil::ArrayList:3536147 ["some"]>`
JRuby 9.3's: `#<Java::JavaUtil::ArrayList: [\"some\"]>`
[rn:skip]
Low impact, the issue might occur if a Java `Set` type is used with logging e.g.
`logged.debug "foo", bar: some_object_containing_a_set`
`bin/logstash -i irb` and try doing a `java.util.LinkedHashSet.new [1, 2]`
- actually fixes https://github.com/elastic/logstash/issues/14209
=> Refactor: drop java.util.Collection#inspect extension

.github/workflows/gen_release_notes.yml, tools/release/generate_release_notes.rb
This change takes the existing release notes draft generator script and wraps it into a GH action workflow.
The workflow just runs the script, which is responsible for computing the draft and creating a Pull Request.
The remaining changes are niceties:
1. instead of creating a PR titled "Release notes draft", create a "Release notes" draft PR
2. assign the PR to the person that executed the workflow, to facilitate tracking
Example: https://github.com/jsvd/logstash/pull/6
=> Add Github Action workflow for release notes generation

Gemfile.jruby-2.5.lock.release
Manticore 0.9.1 includes a work-around for a JRuby 9.3 incompatibility.
Reproduced with http_poller's test suite, details: https://github.com/logstash-plugins/logstash-input-http_poller/issues/135
following up on the recent gem update: https://github.com/elastic/logstash/pull/14233
[rn:skip]
=> Deps: update manticore due JRuby 9.3 issue

logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb, qa/integration/specs/multiple_pipeline_spec.rb
This commit replaces the use of a block with a lambda as an argument for Stream.forEach.
This is to work around the jruby issue identified in https://github.com/jruby/jruby/issues/7246.
This commit also updates the multiple_pipeline_spec to update the test case for pipeline->pipeline
communication to trigger the issue - it only occurs with Streams with more than one event in it.
=> Pipeline->pipeline workaround for jruby-9.3.4.0 bug

Gemfile.jruby-2.5.lock.release
these plugin updates handled JRuby 9.3.4 warnings/problems
[rn:skip]
see https://github.com/elastic/logstash/issues/14234 **(merge on/before June 20th)**
=> Deps: plugin updates due JRuby issues/warnings

docker/Makefile, docker/data/golang/Dockerfile
Sometimes during a build the `make venv` task can fail while executing `pip install` if there's a network issue.
This change introduces 5 retries to the pip install command, each spaced by 5 seconds, in case of error.
=> improve resiliency of make venv with retrying pip install

pkg/centos/before-install.sh, pkg/debian/before-install.sh, pkg/ubuntu/before-install.sh
During upgrade, Logstash packaging removes `/etc/systemd/system/logstash.service` because Logstahs used to install the systemd unit there. However, this could have been modified by the user by overriding the systemd file. As such, the upgrade process should only remove if it is certain it wasn't installed by Logstash.
Unfortunately, there's no particular way to determine if Logstash installation process installed the file because it was done on the fly, by a script, on a postinst script of the package. 
As such, the best way to address this is to check if both the new and the old file exists. If the new one doesn't exist, we can assume we are upgrading (or installing afresh), and the old file should be removed. If the new one exists and the user-create one (old location) also exists, we …
=> Remove /etc/s/s/logstash.service if previously installed by Logstash

logstash-core/spec/logstash/legacy_ruby_timestamp_spec.rb, logstash-core/src/main/java/org/logstash/Timestamp.java, logstash-core/src/test/java/org/logstash/TimestampTest.java
Logstash 8 introduced internals for nano-precise timestamps, and began relying
on `java.time.format.DateTimeFormatter#ISO_INSTANT` to produce ISO8601-format
strings via `java.time.Instant#toString()`, resulting in a _variable length_
serialization that only includes sub-second digits when the Instant represents
a moment in time with fractional seconds.
By ensuring that a timestamp's serialization has a minimum of 3 decimal places,
we ensure that our output is backward-compatible with the equivalent timestamp
produced by Logstash 7.
Adds a backward-compatibility enhancement to ensure timestamp values are serialized with a _minimum_ of 3 decimal places, even if they refer to a whole second with no fractional part. This ensures our output for millisecond-precise timestamps is identical to …
=> Timestamp#toString(): ensure a minimum of 3 decimal places

build.gradle
without these changes doing (an in-process) `bundle install`
did not generate a *Gemfile.lock*
this is than problematic, when using git sourced gem (locally)
those gems do not not get resolved properly when running the
*qa/integration/rspec.rb* script
[rn:skip]
Improves build for integration testing.
run `./gradlew :logstash-integration-tests:integrationTests` 
check `cat qa/integration/Gemfile.lock` (`No such file or directory`)
run `./gradlew :logstash-integration-tests:integrationTests` 
check `cat qa/integration/Gemfile.lock` exists and is not empty
=> Build: make sure lock is created in integration specs

devtools/label
Adds an initial script that allows to add labels to issues/PRs. The first iteration of this script only allows users to add a version label based on the local branch version.yml.
=> devtools/label: Add initial script that can label issues/PRs

logstash-core/src/main/java/org/logstash/ObjectMappers.java
This should be followed by introducing a tighter validator
but the current one introduced in 8.3.0 was creating issues for users.
=> allow any class in CBOR deserialization

docs/static/monitoring/pipeline-viewer.asciidoc
Removes `beta` reference from pipeline viewer documentation as this feature will become GA
This feature has been beta for a significant amount of time. We're now making this feature GA. This PR just updates the documentation removing the `beta` reference from it
Relates [#130219](https://github.com/elastic/kibana/issues/130219)
=> [doc] Removes 'beta' from pipeline viewer doc

config/logstash.yml, docker/data/logstash/env2yaml/env2yaml.go, logstash-core/lib/logstash/environment.rb, logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java, logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java, logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueTestUtils.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java, logstash-core/src/test/java/org/logstash/execution/AbstractPipelineExtTest.java
Added age retention policy for messages inserted in DLQ. After a configurable period of time, expired messages are considered for deletion.
Updates DLQ writer's `writeEvent` method to clean the tail segments  older then the duration period. This happens only if setting `dead_letter_queue.retain.age` is configured.
To read the age of a segment it extract the timestamp of the last (youngest) message in the segment.
The age is defined as a `number` followed by one of `d`, `h`, `m`, `s` that stands for days, hours, minutes and seconds. If nothing is used then assumes seconds as default measure entity.
Once configured `dead_letter_queue.retain.age`, permit to the user to discard events older a certain time boundary, without processing them.
To test it need an Elasticsearch instance the return …
=> Implement DLQ age retention policy

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
Bugfix for DLQ when writer and reader with clean_consumed feature are working on same queue.
The writer side keeps the size of DLQ in memory veriable and when exceed it applies the storage policy, so essentially drop older or never events.
If on the opposite side of the DLQ there is a readed, with clean_consumed feature enabled, that delete the segments it processes then the writer side could have a not consistent information about the DLQ size.
This commit adds a filesystem check when it recognizes that "DLQ full" condition is reached, to avoid consider false positive as valid data.
As a user with a DLQ writer and reader pipelines, when the reader is configured to clean consumed segments, then the writer side can't drop events if the queue full condition is effectively met.
- ~~[ ] I …
=> Bugfix for DLQ when writer is pushing data and reader consuming.

docs/static/monitoring/monitoring-internal-legacy.asciidoc
Supersedes https://github.com/elastic/logstash/pull/14317
Fix broken link to image in docs.
1. Go to https://www.elastic.co/guide/en/logstash/current/monitoring-internal-collection-legacy.html#configure-internal-collectors-legacy
2. In step 6, there's an image that illustrates the monitoring section. (That image is shown correctly)
3. Click on that image to get see it in original size
**Expected**: the link points to the image in original size and the reader can see it.
**Current**: the link is broken and clicking on the image sends the user to a 404 page
As the changes imply, if the link were 
https://www.elastic.co/guide/en/logstash/current/images/monitoring-ui.png
instead of
https://www.elastic.co/guide/en/logstash/current/monitoring/images/monitoring-ui.png
then the image would open …
=> Fix broken link to image

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java, logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueUtils.java, logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java, logstash-core/src/main/java/org/logstash/common/io/SegmentListener.java, logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
[rn:skip]
Increments the counters of consumed events and consumed events every time a segment is completely read from the reader side.
Publish the collected data to the input plugin through the newly added method ` segmentsDeleted(numberOfSegments, numberOfEvents)` to `SegmentListener`.
Provides the base functionality to expose the consumed metrics from the DLQ input plugin.
- Relates #14173
- Relates #10493
As a user of `clean_consumed` DLQ feature I want to monitor the number of events and segments that are cleaned.
=> Expose DLQ deleted events count on reader side

logstash-core/src/main/java/org/logstash/config/ir/compiler/RubyIntegration.java, logstash-core/src/main/java/org/logstash/plugins/ConfigurationImpl.java, logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java, logstash-core/src/main/java/org/logstash/plugins/factory/RubyCodecDelegator.java, logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java, logstash-core/src/test/java/org/logstash/plugins/TestPluginFactory.java, qa/integration/fixtures/mixed_codec_spec.yml, qa/integration/services/logstash_service.rb, qa/integration/services/monitoring_api.rb, qa/integration/specs/mixed_codec_spec.rb
Open the ability to use Ruby codec inside Java plugins.
Java plugins need subclasses of Java `co.elastic.logstash.api.Codec`  class to properly work. This PR implements an adapter for Ruby codecs to be wrapped into a Java's Codec subclass.
Permits to the user to configure a Ruby codec inside  a Java plugin, like in:
```
input {
java_stdin {
codec => json
}
}
```
```
input { java_stdin {codec => json} }
```
```
input { generator {message => 'Test message' count => 1} } output {java_stdout { codec => json }}
```
```
input { java_stdin {codec => json {charset => 'UTF-8'}} }
```
Run Logstash with the different input/output …
=> Create wrapper class to bridge the calls to Ruby codec and present it self as a Java codec

logstash-core/lib/logstash/modules/logstash_config.rb, logstash-core/spec/logstash/modules/logstash_config_spec.rb, x-pack/modules/arcsight/configuration/logstash/arcsight.conf.erb, x-pack/spec/modules/arcsight/arcsight_module_config_spec.rb
* index arcsight data with document type `_doc` so it works on ES 8.x
* include Logstash version in index names to allow different document types to facilitate upgrading
* remove dangling `var.elasticsearch.index_suffix` setting
For reviewers:
1. Install Kibana and ES 6.x
2. Run Logstash 7.x Arcsight Module like so:
```
❯ bin/logstash --modules arcsight --setup -M "arcsight.var.inputs=smartconnector"  -M "arcsight.var.input.smartconnector.port=5010" -M "arcsight.var.elasticsearch.hosts=localhost:9200"  -M "arcsight.var.kibana.host=localhost:5601" -M "arcsight.var.kibana.ssl.enabled=false"
```
3. Ingest data like so:
```
echo "CEF:0|FooBar|Web Gateway|1.2.3.45.67|200|Success|2|rt=Sep 07 2018 14:50:39 cat=Access Log dst=1.1.1.1 dhost=[foo.example.com](http://foo.example.com/) suser=redacted …
```
=> ArcSight Module Broken (Invalid Type), Fixed

qa/integration/services/helpers.sh
When running certain integration tests, a test against a given port is
performed to ensure that certain dependent services are up. Currently,
these are tests are done either via `nc` or `ruby` if no `nc` is provisioned
on the build nodes. The current `ruby` implenentation attempts to use a system
ruby before using the ruby script shipped with Logstash. This commit removes the
use of the system jruby - certain build boxes are still using java8 as their system
java, which causes builds to fail, as java 11 is expected
=> Fix `test_port_ruby` on build nodes with outdated system java

ci/integration_tests.sh
A new class of build node has recently been added which appears to have fewer
memory resources than previous nodes, causing integration test failures. The
gradle task for integration tests doesn't appear to require 4gb, so this commit
reduces the -Xmx setting to 4gb
=> Reduce the amount of memory required by gradle for integration tests

logstash-core/lib/logstash/plugins/ca_trusted_fingerprint_support.rb, logstash-core/spec/logstash/plugins/ca_trusted_fingerprint_support_spec.rb
This test has been broken on Windows since the jruby 9.3 update, and is
similar to an issue we saw when referencing other classes in the
org.logstash.util namespace
=> jruby-9.3 test fix for windows CI

logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java, logstash-core/src/main/java/org/logstash/config/ir/compiler/FilterDelegatorExt.java, logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaFilterDelegatorExt.java
Prior to this commit, the java filter delegator would return "java" to the
`#threadsafe?` call when determining whether a filter is considered thread safe.
This is correct for the _outputs_, where this prefix is used to construct the
appropriate delegator object, but not for filters, where a simple true/false is
required. This commit replaces the `getCurrency` call with a `isThreadsafe` call
to make it clearer that a boolean call is required.
=> Clean up java plugin threadsafe/concurrency check

docker/data/logstash/env2yaml/env2yaml.go
Add support for CONFIG_FIELD_REFERENCE_ESCAPE_STYLE environment variable within containers
Adds support for CONFIG_FIELD_REFERENCE_ESCAPE_STYLE environment variable within containers
It allows for the config.field_reference.escape_style setting to be used within containers without having to modify logstash.yml
- [/] My code follows the style guidelines of this project
- [/] I have commented my code, particularly in hard-to-understand areas
- [/] I have made corresponding changes to the documentation
- [/] I have made corresponding change to the default configuration files (and/or docker env variables)
- [/] I have added tests that prove my fix is effective or that my feature works
NA
-
=> Add config.field_reference.escape_style to env2yaml

docs/include/plugin_header-integration.asciidoc, docs/include/plugin_header.asciidoc
The plugin headers (for both standalone and integration plugins) contain conditional processing to support both Versioned Plugin Reference (VPR) plugins and the Logstash Reference (LSR). No conditional processing is needed because the VPR header files live in the logstash-docs repo and the LSR header files live in the logstash repo. Because of the separate locations, we can use purpose-built header files for each guide and remove the conditionals that may be confusing to people.
This PR:
* Removes conditional statements and content that applies only to the Versioned Plugin Reference plugins.
* Removes conditional statements surrounding content for the Logstash Reference so that it is always present. Note that conditionals for `default_plugin` remain because they still apply. 
Related: …
=> Doc: Remove version plugin conditionals from Logstash Ref plugin headers

qa/integration/services/helpers.sh, qa/integration/services/logstash_service.rb
This PR fixes up some integration test issues where system java was being picked up, rather than the expected version of Java.
* Add `LS_JAVA_HOME` to the request to retrieve the version of logstash
* Use bash `/dev/tcp` to test ports rather than attempting to use `nc` and `ruby`, which may not be installed on CI nodes
=> Fix mismatched Java versions in integration tests

docs/static/filebeat-modules.asciidoc
Updates the example configuration in https://www.elastic.co/guide/en/logstash/current/use-ingest-pipelines.html, to reflect the fact that elasticsearch output now defaults to Datastreams.
It is important because users using defaults, will incorrectly configure their pipeline by using a 'index' setting that can only be used when datastreams is disabled.
Fixes #14008
=> [doc] Update example ES output configs to reflect DS being default

logstash-core/build.gradle
Update dependencies:
* org.reflections:reflections
* commons-codec:commons-codec
* com.google.guava:guava
* com.google.googlejavaformat:google-java-format
* org.javassist:javassist
The goal of these updates is to not fall behind and avoid surprises when an upgrade is necessary due to a security issue.
=> update some java dependencies

docs/static/dead-letter-queues.asciidoc
[rn:skip] 
Integrate the section created with #14340 to describe the `clean_consumed` setting.
- Relates #14173
=> Document the cleaning of consumed events feature

build.gradle
When using Bundler 2.3.19, doing a "bin/logstash-plugin uninstall <plugin>"
will crash, failing to find gems in the :build group.
Until we know more about why, pin bundler to 2.3.19
=> pin bundler 2.3.18 to avoid bug in .19 (for 8.4 branch)

build.gradle
When using Bundler 2.3.19, doing a "bin/logstash-plugin uninstall <plugin>"
will crash, failing to find gems in the :build group.
Until we know more about why, pin bundler to 2.3.19
=> pin bundler 2.3.18 to avoid bug in .19

.github/workflows/version_bumps.yml
Release branches are expected to have a lock file whose name is `Gemfile.jruby-X.Y.lock.release`, where `X.Y` is the Ruby language version.
This Ruby language version differs from JRuby version: for example, JRuby 9.2 is compatible with Ruby 2.5, while JRuby 9.3 is compatible with Ruby 2.6.
This commit makes the version bump agnostic to the version. Since there will be a lock file already present when the action is run, we only need to replace it, so there's no need to know the exact file name.
=> Make version bump github action work with future JRuby versions

Gemfile.jruby-2.6.lock.release
[rn:skip]
Pulls in the DLQ Input v2.0.0's transitive dependency on logstash-core 8.4.0 to prevent a build failure:
> `ERROR: Installation Aborted, message: Downloading logstash-input-dead_letter_queue-2.0.0 revealed dependencies not in the API or the lockfile (logstash-core (>= 8.4.0)).`
- The DLQ Input added a _new_ [dependency on LS-core](https://github.com/logstash-plugins/logstash-input-dead_letter_queue/commit/5d0d230b5085d1ea38bca4d88564b5721ce6362d#diff-839465c3214d299c74529c837847c27af7e07fd2b4186aaf463192ee6f50e1e5R24) for its v2.0.0 release
- We updated our lockfile to reference DLQ Input v2.0.0, but did not include the new transitive dependency declaration in https://github.com/elastic/logstash/pull/14401
This hopes to fix our build failure for the in-flight 8.4.0 branch
- ~[ ] …
=> 8.4: DLQ dependencies

docs/static/fb-ls-kafka-example.asciidoc
Starting with 8.0.0, Filebeat modules no longer have a default fileset (system), and users must explicitly enable the filesets they want to use. 
Backport targets: 8.4, 8.3, 8.2, 8.1, 8.0
Related: https://github.com/elastic/observability-docs/pull/2053
=> Doc: Fileset must be enabled in module

build.gradle, buildSrc/build.gradle
[rn:skip] 
Open the access to java.lang and java.util packages in java.base module.
With [Gradle 7.5 these packages aren't anymore implicitly opened ](https://docs.gradle.org/current/userguide/upgrading_version_7.html#removes_implicit_add_opens_for_test_workers)in test tasks. With this commit, those packages are opened for all test tasks, also on the buildSrc.
Permit to build Logstash with JDK 17 and Gradle 7.5
Download and configure a JDK 17 distribution  and run 
```
./gradlew :logstash-core:javaTest
``` 
and 
```
./gradlew …
```
=> Open java modules for gradle test after 7.5 upgrade
