Gemfile.template

CI [failed](https://internal-ci.elastic.co/blue/organizations/jenkins/elastic%2Bunified-release%2Bmaster%2Bsnapshot-build-logstash-arm-master/detail/elastic%2Bunified-release%2Bmaster%2Bsnapshot-build-logstash-arm-master/1124/pipeline/) with `bin/dependencies-report`
```
Using LS_JAVA_HOME defined java: /var/lib/jenkins/.java/adoptopenjdk11.
warning: ignoring JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Gem::LoadError: You have already activated jar-dependencies 0.4.1, but your Gemfile requires jar-dependencies 0.4.2. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version …
```

Pin jar-dependencies 0.4.1

---

docker/data/logstash/env2yaml/env2yaml.go

Fixed environment based configuration for monitoring.cluster_uuid
This commit adds `monitoring.cluster_uuid` to the env2yaml configuration whitelist and enables the user to set this configuration option via environment variable. It fixes #12211.
This PR makes the environment based configuration more usable.
N/A
Build env2yaml and validate it by providing environment variables.
Closes #12211
N/A
N/A
N/A

fix(env2yaml): Add monitoring.cluster_uuid

---

docs/static/running-logstash-command-line.asciidoc

[rn:skip] 
Fixes a typo in docs
- Superseeds #14338

Fixes typo in running logstash CLI doc

---

Dockerfile
docker/templates/Dockerfile.j2
docs/static/docker.asciidoc

[rn:skip]
Ensuring COPY instruction is used instead of ADD in all Dockerfiles (and related docs)
TL;DR - As a security best practice, COPY instruction should be used instead of ADD whenever possible
The COPY instruction simply copies files from the local host machine to the container file system.
The ADD instruction could potentially retrieve files from remote URLs and perform operations such as unpacking them. The ADD instruction, therefore, introduces security risks. For example, malicious files may be directly accessed from URLs without scanning, or there may be vulnerabilities associated with decompressing them.

Ensuring COPY instruction is used instead of ADD in Dockerfiles

---

build.gradle
qa/integration/services/logstash_service.rb
rakelib/artifacts.rake

* Adds tasks to add bundled JDK to tar file used to run integration tests
* Uses `RUNTIME_JAVA_HOME` environment variable to control whether bundled JDK or
alternative is to be used
* Updates logstash service helper to respect value of `RUNTIME_JAVA_HOME`
* Requires updates to jenkins repo to set `RUNTIME_JAVA_HOME` correctly only for
integration tests that expect to use a custom version of Java, such as the JDK
matrix tests.

Update tests to allow integration tests to use the bundled JDK

---

logstash-core/logstash-core.gemspec

Sinatra 2.2.1 fixes #13777 through https://github.com/sinatra/sinatra/pull/1750:
> Fix JRuby regression by using ruby2_keywords for delegation. #1750 by Patrik Ragnarsson

remove sinatra constraint

---

logstash-core/logstash-core.gemspec

The pinning was added [a couple of years ago](https://github.com/elastic/logstash/pull/11549) but there's no reason I can find to keep the gem at 1.x.
This pinning was preventing us from using [sinatra 2.2.2](https://rubygems.org/gems/sinatra/versions/2.2.2) which depends on mustermann 2.x

Stop pinning mustermann in logstash-core.gemspec

---

docs/static/config-details.asciidoc

Relates: https://github.com/elastic/logstash/issues/12622
Add a link to beats-input doc (https://github.com/logstash-plugins/logstash-input-beats/pull/454)
Suggest to set `-XX:MaxDirectMemorySize` to half of the heap size

[Doc] add off-heap memory session

---

docs/static/ls-ls-config.asciidoc

Adds missing reference to LS-to-LS over HTTP in the main doc section to increate visibility.
Increases visibility and links to the actual configuration steps.

[doc] Add missing reference to full config of LS-to-LS over HTTP

---

Gemfile.jruby-2.6.lock.release
versions.yml

**Merge after `8.4.1` release**
Bump version for `8.4.2`

Bump version to 8.4.2 for next development cycle

---

docker/data/logstash/env2yaml/env2yaml.go

**Backport PR #14425 to 7.17 branch, original message:**
Not clean backport
---
Fixed environment based configuration for monitoring.cluster_uuid
This commit adds `monitoring.cluster_uuid` to the env2yaml configuration whitelist and enables the user to set this configuration option via environment variable. It fixes #12211.
This PR makes the environment based configuration more usable.
N/A
Build env2yaml and validate it by providing environment variables.
Closes #12211
N/A
N/A
N/A

Backport PR #14425 to 7.17: fix(env2yaml): Add monitoring.cluster_uuid

---

Gemfile.template
NOTICE.TXT
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/csv-NOTICE.txt

The version of CSV included in jruby distributions >= `9.3.0.0` and < `9.3.8.0` include a bug that triggers a thread leak when calling `parse_line` in CSV files.
This commit updates the version of the CSV gem to the latest version, which includes fixes, and remains compatible with ruby 2.6
Relates: https://github.com/jruby/jruby/issues/7346
Fixes: #14498

Manually import CSV gem to work around thread leak

---

docs/index.asciidoc
docs/static/winlogbeat-modules.asciidoc

These are taken from the filebeat-modules doc with minor changes to
localise to winlogbeat and to remove the fully worked example.
[rn:skip]
This adds documentation to help users understand how to interface winlogbeat with logstash.
Prior to Winlogbeat 8.0 processor pipelines were run internally within Winlogbeat as js, but now are ingest pipelines. This has caused issues for some users who were previously using logstash to process/forward the js-processed documents and are now in the position of needing to perform the enrichment steps that were previously done by the js code. The documentation here is intended to help these users understand how they can obtain the ingest pipelines needed to pre-process their existing logstash pipelines, or to directly forward the documents through …

winlogbeat-modules: add docs for interfacing winlogbeat with logstash

---

bin/logstash-keystore.bat
bin/logstash-plugin.bat

The work done in #14355 to fix the keystore and plugin scripts erroneously included %JAVA_OPTS% in the command to invoke `jruby`, rather than as an environment variable, which prevented these scripts from operating correctly, due to `jruby.exe` not handling Java options, causing the scripts to crash on invocation.
This commit removes the %JAVA_OPTS% - this is already set as an environment variable, and allows the scripts to operate correctly

Fix Windows scripts

---

logstash-core/lib/logstash/instrument/collector.rb
logstash-core/lib/logstash/instrument/metric_store.rb
logstash-core/lib/logstash/instrument/metric_type/uptime.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
logstash-core/src/main/java/org/logstash/ext/JRubyWrappedWriteClientExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/AbstractMetric.java
logstash-core/src/main/java/org/logstash/instrument/metrics/FlowMetric.java
logstash-core/src/main/java/org/logstash/instrument/metrics/MetricType.java
logstash-core/src/main/java/org/logstash/instrument/metrics/UptimeMetric.java
logstash-core/src/test/java/org/logstash/instrument/metrics/FlowMetricTest.java
logstash-core/src/test/java/org/logstash/instrument/metrics/ManualAdvanceClock.java
logstash-core/src/test/java/org/logstash/instrument/metrics/UptimeMetricTest.java

[rn:skip]
This PR targets a _feature_ branch that is recently cut off of `main`, with the goal of coordinating contributions from @mashhurs and me as we iterate toward a value-providing solution for Phase 0 of #14463 (Pipeline Health API - Pipeline Flow Metrics). Our goal is to get the shared feature branch into shape and separately PR it, so the bar for accepting a partial like this one onto the feature branch is a little lower than the bar we hold for merging onto `main`. It is encouraged to merge PRs into the feature branch early, and to separately PR suggestions into the feature branch to accelerate iterating toward our goal.
This is _half_ of the implementation outlined in Phase 0, providing the `FlowMetric` data structure and UptimeMetric implementation, and registering the five …

Flow metrics: initial implementation

---

Gemfile.template
rubyUtils.gradle
versions.yml

(Manual backport)
Backport PR#14524 to 8.4 branch. Original Message:
Also remove the explicit CSV import added in #14507, jruby-9.3.8.0 includes the correct version by default

Backport PR#14524 to 8.4: Upgrade jruby to 9.3.8.0

---

logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java

the collector is absent when the pipeline is run in test with a NullMetricExt, or when the pipeline is explicitly configured to
not collect metrics using `metric.collect: false`.
[rn:skip]

metric: register flow metrics only when we have a collector

---

logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/FlowMetric.java
logstash-core/src/main/java/org/logstash/instrument/metrics/MetricType.java
logstash-core/src/main/java/org/logstash/instrument/metrics/UptimeMetric.java
logstash-core/src/test/java/org/logstash/instrument/metrics/FlowMetricTest.java
logstash-core/src/test/java/org/logstash/instrument/metrics/MetricTypeTest.java
logstash-core/src/test/java/org/logstash/instrument/metrics/UptimeMetricTest.java

[rn:skip]
add `ScaledView` with sub-unit precision to `UptimeMetric`
By presenting a _view_ of our metric that maintains sub-unit precision, we prevent jitter that can be caused by our periodic poller not running at exactly our configured cadence.
The `UptimeMetric.ScaledView` implements `Metric<Number>`, so its full lossless `BigDecimal` value is accessible to our `FlowMetric` at query time.
This is especially important as the UptimeMetric is used as the _denominator_ of several flow metrics, and a capture at 4.999s that truncates to 4s, causes the rate to be over-reported by ~25%.

metric: add ScaledView with sub-unit precision to UptimeMetric

---

docs/static/monitoring/monitoring-apis.asciidoc
logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/api/commands/stats.rb
logstash-core/lib/logstash/api/modules/node_stats.rb
logstash-core/lib/logstash/instrument/periodic_poller/flow_rate.rb

[rn:skip]
- adds flow metrics to the global top-level namespace, based on the same counterparts in the per-pipeline namespace
- adds docs for flow metrics in the API documentation for the endpoints where they will be consumed
While the top-level `flow` was not defined as in-scope for #14463, I believe users will be surprised by its absence. The metrics themselves are _more_ useful and understandable in the per-pipeline view, but they provide some high-level utility at showing a user _that_ they need to drill down to the pipelines to see what is happening and provide tuning.
1. Run a pipeline that produces significant jittery data
~~~
ruby -e '100.times.map { |j| Thread.new(j) { |k| …

Flow metrics global

---

docs/static/jvm.asciidoc

Updates the docs to correctly display JDK17 as the default JDK version.
Current docs for 8.4 show that JDK11 is the default, however JDK17 was made default for 8.4

Document JDK17 by default

---

config/jvm.options

Removing the `-Djruby.jit.threshold=0` flag, which seems to have been [introduced](https://github.com/elastic/logstash/pull/7783) due benchmarking.
Removing the force of AOT means a noticeably faster startup (we do not need to 'compile' every method we bump into). The JIT threshold default is `50` in JRuby 9.2/9.3, there might be other heuristics in the future to better determine hot methods.
[rn:skip]
Changes recommended default Logstash ships with.
Faster startup time (shaving off > 2 seconds).
```
Using LS_JAVA_HOME defined java: /opt/java/jdk-11.
STARTING RUBY runtime: 1655801953974
Bundler.setup!: 1655801956522
Bundler.setup DONE: 1655801961484 - 4963
```
**7510 millis**
```
Using LS_JAVA_HOME defined java: /opt/java/jdk-17.
STARTING RUBY runtime: 1655801845518
Bundler.setup!: …
```

Perf: use JRuby JIT defaults (improves startup)

---

ci/dra.sh
ci/dra_aarch64.sh
ci/dra_upload.sh
ci/dra_x86_64.sh

This is a **not clean backport** of the following PRs to `8.5` branch:
- Save docker images as tar.gz files move the CSV dependency report in the path that's expected by release-manager #14552 
- Split ci scripts into ARM and x86 ones #14567
- Uses the gsutil tool to upload all the generated artifacts into an intermediate collector bucket. #14568 
- Collect all artifacts created and upload to GCP with release-manager #14584

Backport dra 8.5

---

ci/dra.sh
ci/dra_aarch64.sh
ci/dra_upload.sh
ci/dra_x86_64.sh

This is a **not clean backport** of the following PRs to `8.5` branch:
- Introduces a bash script to build all the artifacts and dependencies report. #14522
- Save docker images as tar.gz files move the CSV dependency report in the path that's expected by release-manager #14552 
- Split ci scripts into ARM and x86 ones #14567
- Uses the gsutil tool to upload all the generated artifacts into an intermediate collector bucket. #14568 
- Collect all artifacts created and upload to GCP with release-manager #14584

Backport dra 7.17

---

ci/dra_upload.sh

[rn:skip]
Avoid to upload not created artifacts for `7.17` for Darwin `aarch64`.

Avoid to upload not created artifacts for Darwin AARCH64 in 7.17

---

ci/dra_upload.sh

[rn:skip]
Extracts the branch release name from the `version.yml` and not from current `git`  branch
Verify that, running the  regexp, like
```bash
cat versions.yml | sed -n 's/^logstash\:\s\([[:digit:]]*\.[[:digit:]]*\)\.[[:digit:]]*$/\1/p'
```
on console, it extracts the expected `major.minor` for the release branches and `main`

Extract the branch name passed to release-manager from version file

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueUtils.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java

Fix DLQ fails to start due to read 1 byte file
This commit ignores DLQ files that contain only the version number. These files have no content and should be skipped. 
Mapping 1 byte DLQ files to buffer causes java.lang.IllegalArgumentException: newPosition < 0: (-1 < 0)
User is unable to start the pipeline using dead_letter_queue input
follow the reproducer of #14599
- Fixed: #14599

Fix DLQ fails to start due to read 1 byte file

---

logstash-core/src/main/java/org/logstash/Timestamp.java
logstash-core/src/test/java/org/logstash/TimestampTest.java

Uses the locale-defined decimal style first.
When encountering a failure and the locale-defined decimal style is NOT the "standard" decimal style, retry the parse operation with the "standard" decimal style.
Fixes a locale-related issue where timestamps that included comma-style decimals could not be parsed even when Logstash was configured to run in a locale that supported comma-style decimals. The timestamp-parser now correctly attempts the locale-defined decimal style first, and falls back to the "standard" decimal style.
Java's `DateTimeFormatterBuilder#toFormatter` always uses the "standard" decimal style, ignoring the one that is provided by the locale. In order to get it to correctly parse with a specific decimal-style, we need to get a modified formatter with that decimal style. …

timestamp: respect locale's decimal-style when parsing

---

logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java
logstash-core/src/test/java/org/logstash/config/ir/PipelineIRTest.java

During graph composition vertices may be copied. This caused
getPostQueue to malfunction as the QueueVertex object stored in the
PipelineIR isn't the one present in the graph once it's fully generated.
This object mismatch caused Graph.getSortedVerticesBetween to not find
the QueueVertex since it takes Objects instead of ids.
This commit waits for the graph to be built and then retrieves the
QueueVertex from the graph and sets it in PipelineIR.
```
❯ git pr 13621
❯ ./gradlew assemble javaTests --tests org.logstash.config.ir.PipelineIRTest.testGetPostQueue
--------------------------------------------------------------------
|  Results: SUCCESS (1 tests, 1 successes, 0 failures, 0 skipped)  |
--------------------------------------------------------------------
❯ git co main …
```

fix PipelineIR.getPostQueue by accounting for vertex copies

---

ci/dra_upload.sh

Leaves the built artifacts under the 'build/' directory to ensure the upload doesn't break as per https://logstash-ci.elastic.co/job/elastic+logstash+8.5+multijob-dra-upload_snapshot/1/console

dra_upload.sh: Leave artifacts under build/

---

ci/dra_upload.sh

[rn:skip] 
The version passed to the `release-manager` doesn't need the SNAPSHOT particle because already handled by the `--workflow="snapshot"`, if inserted make the release manager to search for artifacts named as `8.5.0-SNAPSHOT-SNAPSHOT`

Avoid to pass SNAPSHOT particle to the version passed to release-manager

---

ci/dra_upload.sh

[rn:skip] 
This is a follow up PR #14645, adds the missed `version_qualifier` to the plain version variable

Follow up PR of #14645, adds version qualifier to the plain version

---

ci/dra_aarch64.sh
ci/dra_x86_64.sh

Fixes the source of dra_common.sh. It will now first check the directory of the file from which this dra_common.sh script is being called. This allows the common script to be sourced regardless of where the sourcing script is being called from.

Fix dra_common sourcing

---

rakelib/artifacts.rake

Exclude's all bundler that come from Jruby, from the artifacts, as we install our own.
User shouldn't have any impact.
Closes #14666

Exclude jruby's bundler from artifacts

---

ci/dra_upload.sh

[rn:skip]
Version `7.17` doesn't generate Darwin  aarch64 artifacts. Don't download these artifacts from the GCS bucket, given that we don't build Darwin for that release.
- Superseeds #14676

[DRA] Don't download Darwin arrch64 for 7.17

---

ci/dra_upload.sh

Fix dra_upload.sh syntax that's breaking the build.

DRA - fix dra_upload syntax, breaking builds

---

ci/dra_docker.sh
ci/dra_x86_64.sh

When rake fails to build, the error doesn't seem to bubbled up all the way to script that calls it or Jenkins. This tries to workaround the issue.
Closes #14697

DRA - Fix error reporting

---

ci/dra_docker.sh

[rn:skip] 
Updates the `dra_docker.sh` script to upload also docker-build-context.tar.gz, like 
```
build/logstash-7.17.8-SNAPSHOT-docker-build-context.tar.gz
build/logstash-ironbank-7.17.8-SNAPSHOT-docker-build-context.tar.gz
build/logstash-oss-7.17.8-SNAPSHOT-docker-build-context.tar.gz
build/logstash-ubi8-7.17.8-SNAPSHOT-docker-build-context.tar.gz
```
- Relates #14670

Adds upload of missed docker docker-build-context.tar.gz artifacts

---

ci/dra_docker.sh
ci/dra_upload.sh

Fixes the docker image build process and ensure that:
* Builds and uploads ubi8 for x86_64 only.
* Uploads the ironbank context when running x86_64 builds only.

DRA - Fix docker image build

---

logstash-core/lib/logstash/config/source/multi_local.rb
logstash-core/locales/en.yml
qa/integration/specs/multiple_pipeline_spec.rb

Fixes the reporting of configuration errors in multiple-pipeline setup to make them more actionable
Fixes several related issues with the loading of multiple pipelines in which useful context is lost before presenting the user with an error message:
1. in which a readable-but-unparseable yaml file produces a generic error about not being able to read the file (https://github.com/elastic/logstash/issues/14712)
2. in which a required-but-effectively-empty yaml file produces a generic error about not being able to read the file (unfiled; regression from https://github.com/elastic/logstash/pull/13883)
3. in which a required-but-unreadable yaml file produces a generic error about not being able to read the file (unfiled)
In cases where the `pipelines.yml` is required (that is: neither …

Fix pipelines yaml loading

---

ci/dra_common.sh
ci/dra_docker.sh

Uploads missing docker-build-context files when building x86_64 images only, otherwise this will be overwritten when the build processes aarch64.

DRA: uploading missing docker-build-context files

---

docs/static/releasenotes.asciidoc

This PR adds a known issue to the Logstash release notes. Details are in https://github.com/elastic/observability-docs/issues/2306.
Based on the `static` dir, I'm guessing this isn't correct... but I'm not sure where else to look 😅

Add known issue to 8.5.0

---

versions.yml

[rn:skip] 
Updates `7.17` branch  to the latest JDK 11.0.17+8
- Closes #14734

7.17 - Update bundled JDK to 11.0.17+8

---

versions.yml

[rn:skip] 
Updates `8.5` and `main` branches to the latest JDK.
- Closes #14734

8.5 - Update bundled JDK to 17.0.5+8

---

logstash-core/src/main/java/org/logstash/log/LogstashMessageFactory.java

Bugfix to avoid warning log from status log4j logger when new codecs are created by clone.
Starting with Log4j2  2.6 if a subclass of MessageFactory associated with an Logger instance is not subclass of MessageFactory2, then it's wrapped with MessageFactory2Adapter.
This trigger a log4j warn log that, when a class subclasses LogStash::Plugin for example, is noisy and report about a Logger is not associated with the default MessagedFactory (LogstashMessageFactory) every time a subclass of Plugins is instantiated.
This commit adapt LogstashMessageFactory to implement the MessagedFactory2 instead of the older MessageFactory to avoid the wrapping with the adapter class.
Avoid pollution of loggers when a the log4j status logger is set at `warn` level.
- ~~[ ] I have made corresponding changes …

Avoid the wrapping of LogstashMessageFactory with log4j's MessageFactory adapter

---

docs/static/releasenotes.asciidoc

[rn:skip] 
Forward port release notes from `8.5.0` and `8.5.1` to `main`

Forward port releasenotes from `8.5.0` and `8.5.1`

---

build.gradle

[rn:skip] 
Fixes the `fileBeat` artifact not found issue when running integration tests on Mac M1.
Not impacted.
- Pull the changes
- Run `ci/integration_tests.sh specs/monitoring_api_spec.rb` to test single integration test.
- Closes #14753 
```
// issue case
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/mashhur/Dev/elastic/logstash/build.gradle' line: 464
* What went wrong:
Execution failed for task ':downloadFilebeat'.
> java.io.FileNotFoundException: https://artifacts-api.elastic.co/v1/versions/8.6.0-SNAPSHOT/builds/8.6.0-9a0f87a9/projects/beats/packages/filebeat-8.6.0-SNAPSHOT-darwin-arm64.tar.gz
```
```
// after fix
> Task :downloadFilebeat
Caching disabled for task ':downloadFilebeat' because:
Build cache is disabled
Task ':downloadFilebeat' is not up-to-date …
```

Use `aarch64` artifact arch for integration tests on Mac M1 (darwin) OS.

---

logstash-core/spec/logstash/pipeline_reporter_spec.rb
logstash-core/spec/support/mocks_classes.rb
logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java

- fixes an issue during process shutdown in which the stalled shutdown watcher incorrectly reports `inflight_count` as `0` even when there are events in-flight.
During stalled shutdowns after inputs have been closed and while waiting for in-flight batches to complete, our shutdown watcher emits helpful information about what work is in flight, including the actual threads and plugins that are still executing.
Since ~6.3.0, the `inflight_count` metric in this log message has always been `0`, in part because of two somewhat-overlapping bugs:
- elastic/logstash#8987 and elastic/logstash#9056 (7.0, back-ported to 6.3) changed the `inflight_batches` map provided by the queue read clients to index batches by native thread id, but pipeline reporter continued to attempt to extract by ruby thread …

fix: calculated inflight_count from in-flight batches

---

docs/static/releasenotes.asciidoc

[rn:skip] 
Forward port `8.5.2` release notes to `main`

Forward port 8.5.2 release notes

---

ci/dra_common.sh

[rn:skip] 
Avoid to pipe the output of `docker save` to `gzip` because if docker save terminates with error code 2 and its stdout has the value:
```
Error response from daemon: reference does not exist
```
This command generated a gzip file with the content above and error code set to 0.
This commit uses the `-o` option of `docker save` to avoid using stdout and in case of exit code other than 0, exit the bash script immediately.
As a release manager I want that any intermediate command that has non zero exit code terminate immediately the bash script.
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env …

[DRA] Avoid to loose err code on docker save

---

rakelib/artifacts.rake

Not clean backport of #14782, the main reason for not clean was conflicts to due to `bundle_jdk` variable not present because `7.17` doesn't bundle JDK.
----
Backport PR #14782 to 7.17: Cover all #system invokation with exit code checking, eventually failing the execution of Rake task
Covers all invocations of system Ruby method inside artifcts.rake script to check the exit status and eventually raise an exception.
(cherry picked from commit 720996fa7cbb71071ae93683a6eff5754d6c8486)
Co-authored-by: Andrea Selva <selva.andre@gmail.com>

Backport PR #14782 to 7.17: Cover all #system invokation with exit code checking, eventually failing the execution of Rake task

---

config/logstash.yml
docker/data/logstash/env2yaml/env2yaml.go
x-pack/lib/filters/geoip/database_manager.rb
x-pack/lib/filters/geoip/database_metadata.rb
x-pack/lib/filters/geoip/extension.rb
x-pack/spec/filters/geoip/database_manager_spec.rb

Added a `logstash.yml` setting `xpack.geoip.downloader.enabled` to disable the GeoIP databases auto-update feature.
This PR adds a config `xpack.geoip.downloader.enabled` to globally disable the database auto-update, applying the following rules:
auto_update: true, database: nil, same as current behavior trying to update the database.
auto_update: true, database: path, same as current behavior using the user-provided database.
auto_update: false, database: nil, use the CC database, and delete all EULA databases.
auto_update: false, database: path, same as current behavior using the user-provided database.
If users want to disable the GeoIP database auto-update, they need to set the geoip `database => "/PATH/TO/DB"` option to a file path. As this method is not very intuitive, providing a …

Add setting to disable the GeoIP database downloader

---

Gemfile.template

[rn:skip]
Pins the  `murmurhash3` to the last version that provided Java version
Avoid errors in compiling latest `main`
- Fixes #14831
```
Error Bundler::InstallError, retrying 1/10
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/murmurhash3-0.1.7/ext/murmurhash3
/home/andrea/.sdkman/candidates/java/11.0.15-tem/bin/java -cp :/home/andrea/.gradle/caches/jars-9/4b7ea7ee921889f32773847de07d0ab6/snakeyaml-1.29.jar:/home/andrea/.gradl …
```

Pins murmurhash3 to last version with java library

---

docs/static/releasenotes.asciidoc

[rn:skip]
Update release notes to include recent changes for `8.6` and `8.5.3`

Forward port of 8.6 and 8.5.3 release notes to main

---

docs/static/releasenotes.asciidoc

Backport of the commit 4b020631f3a3ee12af0c31ecc7398058e83bd59b to release notes for `8.6`.
Relates #14762

Backport release notes updates to `8.6`

---

bin/logstash.lib.sh
bin/setup.bat

[rn:skip]
Set the full path to retrieve the `JVM_VERSION` file instead of relying on the `pwd`.
A developer that would launch the some integration tests directly from his environment, for example with:
```
./gradlew clean runIntegrationTests -PrubyIntegrationSpecs=specs/es_output_how_spec.rb
```
would hit a problem in specs execution, which kept the process hang, and reporting on the console as:
```
cat: JDK_VERSION: No such file or directory
```
this is because the `pwd` is `<project checkout>/qa/integration` which obviously doesn't contain the expected file.
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker …

Retrive JVM_VERSION from Logstash's home directory

---

docs/static/getting-started-with-logstash.asciidoc

Updates debian/ubuntu instructions due to the deprecation of apt-key. Uses gpg instead to install the keyring.
Users following our instructions will see deprecation notice when using apt-key to install the Elastic Archive GPG keyring.
Closes: #14758

[doc] update Debian/Ubuntu instructions following apt-key deprecation

---

versions.yml

[rn:skip] 
Updated bundled JDK to 11.0.18+10

Updates bundled JDK to 11.0.18+10

---

versions.yml

[rn:skip] 
Updated bundled JDK to 17.0.6+10

Update bundeld JDK to 17.0.6+10

---

Gemfile.jruby-2.5.lock.release

Not clean backport of #14832 to `7.17`

[Backport 7.17] Pin Murmursh3 to 0.1.6 #14832

---

Gemfile.jruby-2.5.lock.release

Fix PR after #14856 to ping the Murmurhash3 for version for Java.

Fix version lock for Murmurhash3 to the gem for Java runtime

---

versions.yml

* upgrade jruby to 9.3.10.0 addressing a regex performance regression 
This JRuby version fixes a regression which caused longer strings to match slower https://github.com/jruby/jruby/issues/7484
This issue would impact any regexp maching, especially in grok: https://github.com/logstash-plugins/logstash-filter-grok/issues/185

update jruby to 9.3.10.0

---

rakelib/artifacts.rake

set rpm_digest to sha256 instead of default md5 to allow installation on FIPS enabled OS
Set "rpm_digest" in fpm to SHA256 instead of the default MD5. This effectively sets `_binary_filedigest_algorithm` `_build_binary_file_digest_algo` to "8" in the rpm spec for building Logstash RPM packages.
This allows FIPS enabled Operating Systems to validate the RPM package. 
On RHEL w/ FIPS enabled, without this PR:
```
[joaoduarte@jsvd-fips ~]$ sudo rpm -Uvh logstash-8.6.1-x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
1:logstash-1:8.6.1-1               ################################# [100%]
error: unpacking of archive failed on file …
```

set rpm_digest to sha256 instead of default md5

---

logstash-core/benchmarks/build.gradle
logstash-core/build.gradle
rubyUtils.gradle
tools/benchmark-cli/build.gradle
tools/dependencies-report/build.gradle
tools/ingest-converter/build.gradle

ensure logstash-core picks up 1.33 as well from jackson-dataformat-yaml's transititive dependency
Since the current version of jackson-dataformat-yaml has its own dependency of snakeyaml 1.30, logstash-core will have 1.30 instead of 1.33 unless it's overriden in `logstash-core/build.gradle`'s dependency section

bump snakeyaml to 1.33 in logstash-core

---

Gemfile.jruby-2.6.lock.release
versions.yml

8.6 is currently at 8.6.3 but needs to be 8.6.2 until it's out.

Revert "Bump to 8.6.2 (#14879)"

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java

Bugfix on DLQ age policy not executed if the current head segment haven't receives any write
This PR fixes a bug on DLQ age policy not executed if the current head segment haven't receives any write.
The change update the `flushCheck` method, executed both on DLQ writer close and also by the scheduled flusher, so that the `executeAgeRetentionPolicy` is invoked also when the current writer hasn't received any writes.
Adds some test, and to separate the testing of the close from the scheduled flush a new constructor's parameter is added, and consequently updated builder utility.
Fixes a  bug that prohibited the execution of the age retention policy when the current head segment doesn't receive any event.
This could happen if the DLQ ends in a situation that doesn't receive any event for …

Fix DLQ age retention policy to be applied also in case head segment is untouched

---

rakelib/artifacts.rake

[rn:skip] 
Excludes dependency Gemfile.lock files (example `./vendor/bundle/jruby/2.6.0/gems/http_parser.rb-0.6.0-java/Gemfile.lock`) during the artifact creation. This will help vulnerability scanners not to pick up while scanning.
N.A
- Clone current change and create any artifact (example: `./gradlew assembleTarDistribution`)
- Check that if created artifact contains vendor Gemfile.lock files (`find vendor -name Gemfile.lock`).
- Closes #14877

Skip dependency `Gemfile.lock` during the artifact creation.

---

logstash-core/src/main/java/org/logstash/common/AbstractDeadLetterQueueWriterExt.java
logstash-core/src/test/java/org/logstash/common/AbstractDeadLetterQueueWriterExtTest.java

Fixes a bug in the DLQ writer, which inverted the pluginId and pluginType attributes.
Pass the argument in correct order when calls `DeadLetterQueueWriter.writeEntry` from `PluginDeadLetterQueueWriterExt`.
Adds a unit test to verify the DLQ writer-read interaction.
When the DLQ input receives an event now `pluginId` and `pluginType` are properly valued.
Executes the suggested steps in [original issue](https://github.com/logstash-plugins/logstash-input-dead_letter_queue/issues/48#issuecomment-1427687540).
- Fixes #https://github.com/logstash-plugins/logstash-input-dead_letter_queue/issues/48

Fix inversion of pluginId and pluginType parameteres in DLQ entry creation

---

docs/static/releasenotes.asciidoc

Forwardporting `8.6.2` release notes to `main`

[Forwardport] `8.6.2` release notes to `main`.

---

build.gradle
lib/bootstrap/bundler.rb
spec/unit/bootstrap/bundler_spec.rb

Unpin bundler to allow 2.4

---

rakelib/artifacts.rake

Reverts a partial change introduced in c99a7b2f4 that's breaking the package (deb and rpm) builds. c99a7b2f4 is mean to change docker builds, not package builds.
```
Task :downloadPreviousJRuby UP-TO-DATE
Download https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.3.9.0/jruby-dist-9.3.9.0-bin.tar.gz
> Task :downloadJRuby UP-TO-DATE
Download https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.3.10.0/jruby-dist-9.3.10.0-bin.tar.gz
> Task :downloadJdk
Downloaded to /home/multipass/logstash/build/jdk-17.0.6-linux-x64.tar.gz
BUILD SUCCESSFUL in 47s
44 actionable tasks: 4 executed, 40 up-to-date
rake aborted!
FPM::InvalidPackageConfiguration: Cannot package the path '/home/multipass/logstash/rakelib/../config/log4j2.file.properties', does it exist? …
```

Revert partial change in c99a7b2f4 that broke packaging builds

---

config/pipelines.yml
logstash-core/lib/logstash/settings.rb
logstash-core/spec/logstash/config/source/multi_local_spec.rb

Fixes and issues that prevented the usage of `dead_letter_queue.retain.age` in pipelines.yml
Allows the usage of `dead_letter_queue.retain.age` in pipelines.yml
Its important because it prevented the user from using it per pipeline.
- Closes #14951

Allow usage of dead_letter_queue.retain.age in pipeline settings

---

build.gradle
lib/bootstrap/bundler.rb
spec/unit/bootstrap/bundler_spec.rb

This reverts commit 6d08a7c1cd9657c4336367c2195fcc002ebefc9b and #14894
Bundler 2.4 is accumulating memory during the `generateDocsVersion` task outside of the known Bundler 2.3 DepProxy class.
Until the memory mitigation patch is adapted to Bundler 2.4 it's best to revert 6d08a7c1cd.

Revert "Unpin bundler to allow 2.4 (#14894)"

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java

Fixed the DLQ writer to bypass 1 byte entry during the search of the oldest segment timestamp
When DLQ writer is initializing and the content of DLQ entry has only 1 byte (version number), the search of the oldest segment timestamp return `-1` [block](https://github.com/elastic/logstash/blob/v8.6.2/logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java#L398), hence, [seek](https://github.com/elastic/logstash/blob/v8.6.2/logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java#L403) the wrong position.
This PR skips 
- segments with size == 1 byte
- seeking the block if blockId < 0. Empty timestamp returns to the caller.
Pipelines are unable to start when DLQ entry is 1 byte.
- Fix #14969

Fixed the DLQ writer to bypass 1 byte entry

---

pkg/centos/after-install.sh
pkg/debian/after-install.sh
pkg/ubuntu/after-install.sh

Starting from systemd 229, `TimeoutStopSec` supports using 'infinity' to prevent the service manager from sending a SIG Kill when stopping the service. This effectively allows logstash to shutdown gracefully including possibly long-running operations such as draining the queue (or other operations).
However, on Operating Systems with older versions of Systemd, such as CentOS7 or Debian Jessie, the setting didn't support the infinity option, and instead used the number 0.
As such, this PR introduces a post-installation change in which it fixes the Systemd Unit in the event of it being installed in an older, soon to be deprecated operating system.
This change is important because otherwise, users who stop the Logstash service using a very old service manager would potentially loose data.
- …

Fix system unit TimeoutStopSec on older version. 

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/src/main/java/org/logstash/execution/AbortedBatchException.java
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

Let worker threads be interrupted without consuming the in flight batch.
Modify the `WorkerLoop` to catch the newly introduced exception `org.logstash.execution.AbortedBatchException` so that an inflight batch could be negatively ACK-ed. This feature is used in combination with PQs to let exit plugins without completing the processing. Any filter and output already executed for the batch will be executed again next time the batch is picked by the persistent queue.
In combination with some plugins that leverages its, let the plugins to restart without acknowledging the current batch. In cases, like api key expiration used by an Elasticsearch output, the pipeline can be restarted without forcing it and loosing events.
- Relates https://github.com/logstash-plugins/logstash-output-elasticsearc …

Negative ack of batch aborted by plugin

---

build.gradle
lib/bootstrap/bundler.rb
rakelib/plugins-metadata.json
rakelib/plugins_docs_dependencies.rake
spec/unit/bootstrap/bundler_spec.rb

1. reintroduce bundler 2.4 and remove tweaks for 2.3
2. avoid memory leak during generatePluginsVersion
3. skip logstash-input-cloudwatch to avoid bundler 2.4 struggling with dependency resolution

Reintroduce bundler 2.4

---

Gemfile.template

follow up from https://github.com/elastic/logstash/pull/14856, that only edited the lock file but not the Gemfile.template

pin murmurhash3 to 0.1.6 until 0.1.7-java is out

---

logstash-core/lib/logstash/pipeline.rb

Fixed ruby engine pipeline crash during shutdown
This PR adds the missing method `worker_threads_draining?` to ruby pipeline which is added in #13934 to java pipeline for log msg improvement.
As ruby engine is deprecated in Logstash 8, this method is added for backward compatibility.
Logstash runs in ruby engine and enables `queue.drain` got `NoMethodError` during shutdown. The ruby pipeline crashes.
1. logstash.yml
queue.type: persisted
queue.drain: true
2. run the pipeline with ruby engine `bin/logstash --java-execution false`
```
input { stdin {} }
output {
tcp {
host => "localhost"
port => "3000"
ssl_enable => false
}
}
```
3. no need to start tcp server
4. send event to stdin, eg "asdf" to accumulate events in PQ
5. send `SIGINT` to shutdown logstash
6. Logstash should not show …

fix missing method in ruby pipeline

---

config/logstash.yml
config/pipelines.yml

[rn:skip]
With PR #13923 was described how the DLQ `storage_policy` behaves. With PR #14261 was introduced a duplication of the description in logstash.yml.
This commit resolves the duplication and keeps the latest description that seems more direct expressive.
It rationalize the description of a setting.
- relates #14261
- relates 13923

Fix duplicate description for storage_policy in yaml config files

---

versions.yml

[rn:skip] 
Bumps `versions.yml` for `8.9`

Bumped versions.yml for 8.9 cycle

---

docs/static/deploying.asciidoc

PR https://github.com/elastic/beats/pull/35271 removes a page about load balancing which appears only in the Filebeat docs. This fixes the link from the Fleet and Agent docs to point to the load balancing description under the Filebeat Elasticsearch output type.
Rel: https://github.com/elastic/beats/pull/35271

[DOCS] Fix link to loadbalance in Filebeat ref

---

docs/static/monitoring/monitoring-apis.asciidoc

[rn:skip]
Improves docs for flow metrics in several distinct ways:
- use correct syntax declaration for example responses
- fix truncations of trailing `}` that resulted in syntax errors
- provide hints for tables to prevent wrapping in the middle of metric names
- refresh example responses to ones that math correctly (the existing ones have been appended to piecemeal, and the math didn't add up), and include only the GA flow windows `current` and `lifetime` in the examples to reduce noise
Users have a better experience when our docs make sense :)
- …

Plugin flow docs fixes

---

docs/static/docker.asciidoc

This updates the [Running Logstash on Docker](https://www.elastic.co/guide/en/logstash/8.7/docker.html) page to add steps to verify the Docker image.
Rel: https://github.com/elastic/dev/issues/2002
Preview
---

[Docs] Add instructions to verify Docker install images

---

docs/static/docker.asciidoc

This will backport the following commits from `main` to `8.8`:
- [[Docs] Add instructions to verify Docker install images (#15058)](https://github.com/elastic/logstash/pull/15058)

[8.8] [Docs] Add instructions to verify Docker install images (#15058)

---

logstash-core/lib/logstash/config/mixin.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/plugin_spec.rb

Removes obsolete plug-in version notice that conveys a plugin under 1.0.0 is badly or not supported.
Closes #15012

Remove obsolete plugin version notice

---

rubyUtils.gradle

When building a Logstash, we were getting `ERROR: Installation Aborted, message: uninitialized constant Bundler::SolveFailure` error. It turned out Logstash pulls 2.4.14 bundler version and we have a definition using mismatch bundler version. With this change we are updating bundler to `2.4.14`
```diff
- jruby.setLoadPaths(["${projectDir}/vendor/bundle/jruby/2.6.0/gems/bundler-2.4.13/lib".toString(), "${projectDir}/vendor/jruby/lib/ruby/stdlib".toString()])
+ jruby.setLoadPaths(["${projectDir}/vendor/bundle/jruby/2.6.0/gems/bundler-2.4.14/lib".toString(), "${projectDir}/vendor/jruby/lib/ruby/stdlib".toString()])
```

Upgrade bundler version used in ruby utils.

---

.buildkite/scripts/snyk/report.sh
.buildkite/snyk_report_pipeline.yml

By default, Buildkite Agents do not have Java installed. With this script change I have included the script which installs the Java. For the long term, building Logstash image for Buildkite CI/CDs would be better. The image would also include ruby tools and dynamically build based on `versions.yml`.

Install Java on Buildkite Agent.

---

.buildkite/serverless_pipeline.yml

Create a placeholder for serverless test in buildkite
https://github.com/elastic/ci/pull/2081 PR to create serverless pipeline is merged in CI repo. Buildkite is expecting `serverless_pipeline.yml`. This commit fixes the red CI due to missing the yml file.
Relates: #https://github.com/elastic/ingest-dev/issues/2158

placeholder for serverless test in buildkite

---

build.gradle
lib/bootstrap/bundler.rb
rakelib/artifacts.rake
rakelib/plugins_docs_dependencies.rake
rubyUtils.gradle
spec/unit/bootstrap/bundler_spec.rb

Instead of relying on external bundler because JRuby flutuated between including and not including bundler for a while, now that bundler is part of rubygems, unless there's a CVE afecting the shipped version of bundler there's no need to have a custom one any more.
This simplifies our code and bootstrapping tasks, so this PR removes the need to install bundler during bootstrap.
As side effect this PR reintroduces the older patches to not go OOM during plugin docs generation.
TODO: find a way to not require installing bundler for the QA tests. We can deal with that in a follow up PR

Remove custom bundler

---

lib/pluginmanager/settings.xml.erb

When using a proxy with the plugin manager, this template is written to `~/.m2/settings.xml`. The license header is also copied, which generates invalid XML which maven cannot parse.
Fixes: https://github.com/elastic/logstash/issues/15130

Remove license header from settings.xml template

---

rubyUtils.gradle

This will no longer be necessary in main (8.10) since it relies on the bundler from jruby.

Update rubyUtils.gradle to use bundler 2.4.15

---

docs/static/releasenotes.asciidoc

[rn:skip]
Add a release note explaining the monitoring/management xpack SSL regression fixed by: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1142

[Doc] Add monitoring/management SSL regression note on release 8.8.0

---

logstash-core/lib/logstash/patches/puma.rb
logstash-core/lib/logstash/webserver.rb
logstash-core/logstash-core.gemspec
logstash-core/spec/logstash/patches/puma_spec.rb

Updated the puma gem from version 5 to the latest version 6.3.
This PR updates the puma gem from version 5 to the latest version 6.3. 
A few breaking changes were introduced in Puma [6.0.0](https://github.com/puma/puma/releases/tag/v6.0.0), which required some refactoring on the Logstash side, especially to adapt it to the _Extracted LogWriter from Events_ [#2798](https://github.com/puma/puma/pull/2798) changes.
Before this PR, all the logs generated by Puma were using the `debug` level, even the ones that were actually errors and needed attention/action from the users. 
Log level changes:
- `#error` changed from `debug` to `error` 
- `#unknown_error` changed from `debug` to `error`
In addition to other fixes and features, the latest puma versions >= `6` have added support to `TLSv1.3`, …

Update puma to version 6.3

---

docs/static/persistent-queues.asciidoc

Adds documentation with general guidance in sizing a Persistent Queue.
Users don't have a general mechanism to guide them on how to size their persistent queues. Providing one will allow them to better size and serve their use cases.
Closes #14871

Add initial PQ sizing doc

---

.buildkite/scripts/snyk/report.sh
.buildkite/scripts/snyk/resolve_stack_version.sh
catalog-info.yaml

This change mainly focuses on two things:
- utilizes Snyk CLI to scan and report docker container vulnerabilities;
- docker images are pulled from https://www.docker.elastic.co/r/logstash. Sometimes the process may fail due to image miss. It happens when DRA didn't run but release planned with new branch.
- simplifies the script. Some part of simplification is suggested by https://github.com/elastic/logstash/pull/15098 and this swallows the suggested PR to test and edits.
- Closes #15165

Snyk scans Logstash container vulnerabilities.

---

.rubocop.yml
Gemfile.template
Rakefile
build.gradle
rakelib/lint.rake

This PR adds BASIC integration with a Ruby Linter (Rubycop), and adds a Gradle task and two rake tasks.
Usage:
Running the linter with Gradle will install the required dependencies and run a listing report rake task.
`./gradlew lint `
We can also run the linter report with rake.
`rake lint:report`
Lastly, you can also ask Rubocop to automatically update the code for FORMAT changes only with:
`rake lint:format`
Please note: I've intentionally disable all Style formatters, as they will need to be reviewed on case by case basis and enabled as we make the code changes.

Add basic ruby linter

---

rakelib/lint.rake

Adds a rake task that allows users to autocorrect an enabled Cop. This can be any type of code.
`rake lint:correct["Lint/DeprecatedClassMethods"]`

Add rake lint correct

---

build.gradle

Fixed Java 8 compatibility issues
This PR adds the [--release](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:release) ([JEP 247](https://openjdk.org/jeps/247)) option to the Gradle's `CompileJava` task, with the same `targetCompatibility` major version value. 
The motivation to add this flag is to avoid compatibility issues when the code is compiled using a newer Java version but it's meant to be executed in older JVMs. This issue is explained well in the [blog post](https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/).
Using this PR source code:
- Download the JDK 8 and set the `LS_JAVA_HOME` to its path
- Enabled the PQ in `config/logstash.yml` by setting the `queue.type: persisted` …

Fix Java 8 compatibility issues

---

.rubocop.yml
lib/pluginmanager/proxy_support.rb
logstash-core/spec/logstash/event_spec.rb
logstash-core/spec/logstash/legacy_ruby_timestamp_spec.rb
qa/integration/framework/fixture.rb
tools/logstash-docgen/lib/logstash/docgen/asciidoc_format.rb
tools/logstash-docgen/lib/logstash/docgen/index.rb
x-pack/lib/monitoring/monitoring.rb

Fixes deprecated instances of ERB.new( <params> ) and deprecated use of BigDecimal.new

Fix deprecated ERB and BigDecimal instances

---

docs/static/releasenotes.asciidoc

8.9 release note mentions about `snakeyaml => 2.0` (similarly with `jackson` & `commons`) dependency update which will happen in 8.10 version.

8.9 Release notes updated.

---

docs/static/breaking-changes-80.asciidoc
docs/static/breaking-changes.asciidoc

[rn:skip]
Removes tags for notable breaking changes and related comments.
With https://github.com/elastic/stack-docs/pull/2495 merged, we no longer need tags to reuse breaking changes in the Stack Install/Upgrade guide.
https://github.com/elastic/platform-docs-team/issues/143

doc: remove breaking change tags

---

docs/static/breaking-changes-80.asciidoc
docs/static/breaking-changes.asciidoc

This will backport the following commits from `main` to `8.9`:
- [doc: remove breaking change tags (#15231)](https://github.com/elastic/logstash/pull/15231)

[8.9] doc: remove breaking change tags (#15231)

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java

Fixed `DeadLetterQueueWriter` unable to finalize segment - `java.nio.file.NoSuchFileException`
For more details about the error, please check the https://github.com/elastic/logstash/issues/15227.
This PR moves the `Files.size(...)` call into the try catch [block](https://github.com/elastic/logstash/pull/15233/files#diff-a0ee6ca8e72a830020520ea556f56e46ec1326e48593d9dfd1f252b70d3af45aR449), that way, when the oldest segment is deleted by the `DeadLetterQueueReader`, no `NoSuchFileException` will be thrown up, and the writter will gracefully  update the oldest segment on the next `updateOldestSegmentReference` invocation (scheduled flush, entry write, delete expired, etc).
It also adds the `volatile` keyword to the shared mutable variables, making sure that all the changes will be instantly …

Fix DeadLetterQueueWriter unable to finalize segment error

---

logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb
logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/main/java/org/logstash/ackedqueue/QueueExceptionMessages.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java
logstash-core/src/main/java/org/logstash/ext/JRubyAbstractQueueWriteClientExt.java
logstash-core/src/main/java/org/logstash/ext/JRubyWrappedWriteClientExt.java
logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java
logstash-core/src/main/java/org/logstash/ext/JrubyMemoryWriteClientExt.java
logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/plugins/pipeline/PipelineBusTest.java
logstash-core/src/test/java/org/logstash/util/ExceptionMatcher.java
logstash-core/src/test/java/org/logstash/util/SetOnceReferenceTest.java

Resolves upstream pipeline termination when using pipeline to pipeline communication if writing to a closed queue.
Adresses number of Pipeline to Pipeline upstream issues including abnormal termination issues:
- `"Tried to write to a closed queue." IllegalStateException` exception, terminates upstream pipeline
Resolution: ideally locking `input` in the pipeline bus while sending the inflight event would be a synchronized task to prevent such cases and we have [this option](https://gist.github.com/yaauie/5bf4db9f7f7bd17d6b0b84741940a9a1) (big thanks @yaauie) to consider. However, blocking mechanism would be an expensive and expected behavior is to catch exception (failed inflight send position) and let process retry as we have a logic in pipeline bus.
- Inflight events duplicate while …

Pipeline to pipeline communication acked queue improvements.

---

.buildkite/serverless_integration_pipeline.yml
ci/serverless/README.md
ci/serverless/common.sh
ci/serverless/cpm_tests.sh
ci/serverless/dlq_rspec_tests.sh
ci/serverless/elastic_integration_filter_tests.sh
ci/serverless/es_output_tests.sh
ci/serverless/metricbeat/metricbeat.yml
ci/serverless/metricbeat_monitoring_tests.sh
ci/serverless/monitoring_tests.sh
qa/integration/specs/dlq_spec.rb
qa/integration/specs/spec_helper.rb

This commit makes changes on serverless tests.
- disabled Kibana API test as it is not available in QA
- disabled Metricbeats stack monitoring test as the latest version of Metricbeats calls `/_ilm` and fails
- fixed DLQ test that use legacy template API
- fixed minor script issues
Fixes: https://github.com/elastic/ingest-dev/issues/2308

Fix serverless test for api protection

---

rakelib/plugins_docs_dependencies.rake

As `Bundler::DepProxy` is removed in [Bundler 2.4.0](https://github.com/rubygems/rubygems/commit/eb697fb827db8e280f2b43bc06e4cc0aa3dc1bbd), this commit removes the patch.
Fixes https://github.com/elastic/docs-tools/issues/91

Remove DepProxy patch

---

Gemfile.template
logstash-core/logstash-core.gemspec

[rn:skip]
Revert PR #15267 which updated Puma in Gemfile.template and correctly place it in logstash-core.gemspec, beeing a dependency of Logstash core.

Fix the update of Puma

---

config/logstash.yml

This is a small patch to remove a trailing whitespace from the default config file.
Removes the red when the config file is viewed through a diff tool like `git diff`
~~- [ ] My code follows the style guidelines of this project~~

Remove unnecessary whitespace from logstash.yml

---

x-pack/lib/config_management/elasticsearch_source.rb
x-pack/lib/license_checker/license_manager.rb
x-pack/lib/license_checker/license_reader.rb
x-pack/lib/license_checker/licensed.rb
x-pack/lib/license_checker/x_pack_info.rb
x-pack/lib/modules/module_license_checker.rb
x-pack/lib/monitoring/internal_pipeline_source.rb
x-pack/lib/monitoring/monitoring.rb
x-pack/spec/config_management/elasticsearch_source_spec.rb
x-pack/spec/license_checker/license_manager_spec.rb
x-pack/spec/license_checker/license_reader_spec.rb
x-pack/spec/modules/module_license_checker_spec.rb
x-pack/spec/monitoring/internal_pipeline_source_spec.rb
x-pack/spec/support/helpers.rb

Added support for Elasticsearch serverless. 
* Added support for central pipeline management
* Disabled legacy monitoring pipeline as serverless does not support monitoring API
Serverless made some changes to API
1. `/_xpack` is for internal users with service account. Logstash does not have permission to call it. xpack features are affected.
2. `/_monitoring/bulk?` is not available which causes Logstash legacy monitoring unable to send metrics
This commit adds a call to identify serverless cluster before fetching `/_xpack` to verify the license and supported features. 
When it is serverless, the license checker uses hardcoded xpack info instead of calling xpack API. The internal pipeline of monitoring is disabled and logs error when configured to use legacy monitoring.
One concern about …

disable xpack API and monitoring pipeline for serverless

---

ci/serverless/README.md
ci/serverless/common.sh
ci/serverless/config/logstash.yml
ci/serverless/cpm_tests.sh
ci/serverless/elastic_integration_filter_tests.sh
ci/serverless/es_output_tests.sh
ci/serverless/kibana_api_tests.sh
ci/serverless/metricbeat_monitoring_tests.sh
ci/serverless/pipeline/001_es-output.conf
ci/serverless/pipeline/002_es-filter.conf
ci/serverless/pipeline/003_es-input.conf
ci/serverless/pipeline/004_integration-filter.conf
ci/serverless/test_data/index_template.json

- split the privileges per use case
- remove ilm in template
- update readme
This PR is blocked until Logstash removes `/_xpack` checking for serverless as it is not ready to test CPM now.

serverless test use minimum privileges per case

---

README.md

The instructions to build from source in README.md were outdated. This
commit updates and simplifies them, preferring the use of `gradle`.

[Docs] Update build from source instructions in README.md

---

catalog-info.yaml
qa/integration/specs/dlq_spec.rb

switch the testing branch to `main` and fix variable name PLUGIN_API_KEY.
Tests are green locally and should be green on buildkite

buildkite serverless test against main

---

logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java

Fix:  #15300, #14961
The tests fail to shutdown old pipeline when the native thread returns null. It throws [NPE](https://github.com/elastic/logstash/blob/v7.17.12/logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java#L164) when constructing pipeline report

Fix NPE when getting native thread id

---

build.gradle
ci/docker_run.sh
ci/docker_unit_tests.sh
ci/unit_tests.sh
logstash-core/build.gradle

Enables sonarqube code scanning and coverage reports for logstash-core. 
[Sonar project for logstash](https://sonar.elastic.dev/dashboard?id=elastic_logstash_AYm_nEbQaV3I-igkX1q9) is already created.
This configuration provides:
**Pull request analysis**: Analyses newly added code for a particular pull request
SonarQube automatically adds a comment with digest information. If no java files were changed in a pull request we will see “No coverage/duplication information” labels
**Branch analysis**: Runs on branches like main and analyzes the entire codebase. Associates received code coverage with the branch
Continuous static analysis and solid code coverage help us maintain well-designed and reliable code.
Furthermore we can setup desired quality gates for our [logstash sonar …

Sonar integration with Java Tests code coverage

---

docs/static/releasenotes.asciidoc

Since the DRA build for 8.10.1 was made with 82daae80bbaf8b1e62cde93bcf518b88a417193c , this fix didn't get in.

Fix releasenotes.asciidoc for 8.10.1

---

.buildkite/scripts/dra/generatesteps.py

We've spotted network flakiness downloading artifacts with gradle (connection resets) when using GCP/t2a on us-central1.
This commit switches to AWS Graviton instance types for building the aarch64 artifacts.

[DRA,buildkite] Use AWS aarch64 instance type

---

.buildkite/scripts/dra/generatesteps.py

We seem to be hitting a weird issue with the psych gem when running in a container:
```
> Task :bootstrap
2023-09-27T15:13:23.844Z [Execution worker Thread 5] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
Error Errno::ENOENT, retrying 1/10
No such file or directory - /buildkite/builds/bk-agent-prod-k8s-1695827479442731913/elastic/logstash-dra-pipeline-ci/vendor/bundle/jruby/3.1.0/gems/psych-5.1.0-java/deps.lst
```
This commit works around this problem by running inside a VM. The underlying root cause (and that gradle should be erroring in this case) will be investigated separately.

[DRA, buildkite] Use GCP vms for package build step

---

build.gradle

[rn:skip]
Replaces the Xerces version shipped with Nokogiri
Run the `installDefaultGems` and verify the version `xercesImpl`:
```sh 
./gradlew clean installDefaultGems
cp vendor/bundle/jruby/2.5.0/gems/nokogiri-1.12.5-java/lib/xercesImpl.jar /tmp
cd /tmp
jar xf xercesImpl.jar
grep -B1 "org.apache.xerces.impl.Version" META-INF/MANIFEST.MF
```
- Closes #15325

Updates installDefaultGems task to replace Xerces

---

rakelib/plugins-metadata.json

We have developed [Logstash integration](https://github.com/logstash-plugins/logstash-integration-logstash) plugin which is recommended when using ls-to-ls communication. With this PR, we are embedding the plugin into the core that by default plugin will be available to use.
- Clean install with default gems will create a `Gemfile` which includes logstash integration plugin.
`./gradlew clean bootstrap assemble installDefaultGems`
- Closes #15335

Bundle `logstash-integration-logstash` plugin.

---

NOTICE.TXT
lib/pluginmanager/util.rb
logstash-core/logstash-core.gemspec
rubyUtils.gradle
spec/unit/plugin_manager/util_spec.rb
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/bigdecimal-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/cgi-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/date-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/ffi-binary-libfixposix-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/io-console-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/mini_mime-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/net-http-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/net-imap-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/net-pop-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/net-protocol-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/net-smtp-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/reline-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/time-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/timeout-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/uri-NOTICE.txt
versions.yml

forward-ports non-release-branch components of #15283 to `main`
* deps: downgrade jruby, keep updated default-gem dependencies
By downgrading JRuby to 9.4.2.0 we avoid the silent global crash of the scheduler backing `Concurrent::TimerTask` that occurs when Jruby 9.4.3.0's invokedynamic promotes a method to run natively, incorrectly.
Upstream bug: https://github.com/jruby/jruby/issues/7904
Along with the downgrade of JRuby itself to 9.4.2.0, we cherry-pick the updates to gems that were included in the latest JRuby 9.4.3.0 to ensure we don't back out relevant fixes to stdlib.
We also remove a pinned-dependency on `racc` that is no longer relevant.
Resolves: https://github.com/elastic/logstash/issues/15282
* Imported the licenses for some gems
- cgi
- date
- ffi-binary-libfixposix
- …

deps: downgrade jruby, keep updated default-gem dependencies (forward-port #15283)

---

Gemfile.jruby-3.1.lock.release

To release the 8.11 version, we need to copy the `Gemfile.lock` from prev minor 8.10 release. This PR copies `Gemfile.jruby-3.1.lock.release` without any change into 8.11 branch.

Copy `Gemfile.lock` from 8.10 branch.

---

Gemfile.template

During the bump minor workflow run, somehow `bigdecimal` old `1.4.4` version is resolved it cannot be installed.
This PR adds proper `bigdecimal` dependency to template file make sure what version we need.
```
checking RUBY_BIGDECIMAL_VERSION... 1.4.4
checking for labs() in stdlib.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
...
In Gemfile:
logstash-integration-jdbc was resolved to 5.4.6, which depends on
sequel was resolved to 5.73.0, which depends on
bigdecimal
Error: Process completed with exit code 5.
```
Run the following command which is same with workflow.
```
./gradlew clean installDefaultGems
./vendor/jruby/bin/jruby …
```

Add bigdecimal > 3.1 dependency.

---

.buildkite/dra_pipeline.yml
.buildkite/scripts/dra/common.sh

DRA artifact builds support two optional parameters `VERSION_QUALIFIER_OPT` and `DRA_DRY_RUN`.
The most important is `VERSION_QUALIFIER_OPT` which should be provided when `alpha1` or similar versions need to be built.
Currently, after clicking new build, the pipeline takes ~20s to assemble the steps and pauses the job waiting for these options to be filled (or just accept the empty defaults) and press continue.
I feel that this could be trappy behavior because the majority of the use cases don't need it, and it's likely that a user manually clicks build and forgets that they'd need to confirm these parameters later on, left with a hanging build.
This commit makes the parameters optional. If needed, they should be defined explicitly in the New Build prompt, after expanding the Options …

[DRA] Remove wait step in buildkite

---

.buildkite/scripts/dra/generatesteps.py

We discovered[^1] that JRuby 9.2 and 9.3 have an issue when using FileUtils with Glibc >2.34 (e.g. on Ubuntu 22.04).
This commit switched to Ubuntu 20.04 VM images for building DRA artifacts with branch 7.17.
Relates: https://github.com/elastic/ingest-dev/issues/1720
[^1]: https://github.com/jruby/jruby/pull/7611#issuecomment-1750387837

[ci] Build 7.17 DRA using Ubuntu 20.04

---

.buildkite/pull-requests.json
.buildkite/pull_request_pipeline.yml
.buildkite/scripts/common/container-agent.sh
catalog-info.yaml

[rn:skip]
This commit adds a Buildkite resource for pull requests and associated the first two jobs, license checking and ruby unit tests.
As this is WiP, slack notifications aren't enabled.
https://github.com/elastic/ingest-dev/issues/1721

[ci] Initial pull request jobs for buildkite

---

catalog-info.yaml

[rn:skip]
PR #15402 missed the required repository property for the Buildkite pull request resource.
- #15402

[ci] Add missing repository in Buildkite PR

---

catalog-info.yaml

[rn:skip]
Currently while PR jobs get triggered as expected in Buildkite via the bot, they also get re-triggered after something gets pushed, including e.g. the squash merge commit when the PR is merged.
This commit disables this behavior as documented in Buildkite[^1].
- #15402
- https://github.com/elastic/ingest-dev/issues/1721
[^1]: https://buildkite.com/docs/apis/rest-api/pipelines

[ci] Don't trigger BK PR jobs on pushes

---

Gemfile.template

The new [psych 5.1.1 gem](https://rubygems.org/gems/psych/versions/5.1.1-java) seems to not work when installed in JRuby 9.4 (used in main).
This change pins the version back to 5.1.0 until ruby/psych#655 is sorted.
Closes #15427

pin psych 5.1.0 due to ruby/psych#655

---

.buildkite/pull_request_pipeline.yml
.buildkite/scripts/common/container-agent.sh

This is a backport of the initial Pull Request pipeline for Buildkite.
While currently we haven't migrated all PR jobs from Jenkins, this is needed so PRs against non `main` branches don't fail this check (also giving us the possibility to test functionality against non `main` branches).
Relates:
- #15402
- #15413
- #15415
- #15421
- https://github.com/elastic/ingest-dev/issues/1721
[rn:skip]

[ci] Backport Buildkite PR pipeline to 8.11

---

.buildkite/pull_request_pipeline.yml
.buildkite/scripts/pull-requests/sonar-env.sh

[rn:skip]
This commit adds Java unit tests (including sonar scans) to the Buildkite pull request pipeline.
- https://github.com/elastic/ingest-dev/issues/1721
- https://github.com/elastic/logstash/pull/15279

[ci] Commit PR based Java unit tests for Buildkite

---

.buildkite/pull_request_pipeline.yml
.buildkite/scripts/common/container-agent.sh

[rn:skip]
This commit adds the remaining steps for the Buildkite pull request pipeline i.e.
- `IT Persistent Queues / part 1`
- `IT Persistent Queues / part 2`
- `x-pack unit tests`
- `x-pack integration`
Once merged we will be able to retire the corresponding Logstash pull request multijob.
- https://github.com/elastic/logstash/pull/15438
- https://github.com/elastic/logstash/pull/15437
- https://github.com/elastic/ingest-dev/issues/1721
- https://github.com/elastic/logstash/pull/15279

Migrate remaining PR jobs to Buildkite

---

catalog-info.yaml

[rn:skip]
This commit enables automatically updated comments from Buildkite for PRs. It posts comments to PRs whenever a Buildkite build finishes or encounters its first failing step and keeps the comment updated.
https://github.com/elastic/ingest-dev/issues/1721
The result will be a commit in every PR like this ([internal link](https://github.com/elastic/package-storage-infra/pull/573#issuecomment-1764082444)):
including a cc to the author of the PR

[ci] Enable Buildkite PR comments

---

.buildkite/supported_plugins_test_pipeline.yml

Change buildkite pipeline to run all tests in parallel

---

docs/static/releasenotes.asciidoc

* Update release notes for 8.10.4
Co-authored-by: Karen Metts <karen.metts@elastic.co>

Release notes for 8.10.4 (#15435)

---

catalog-info.yaml

[rn:skip]
This commit adds an initial Buildkite resource definition for aarch64 exhaustive tests.
- https://github.com/elastic/ingest-dev/issues/1724
**NOTE**: The actual pipeline is committed separately in a follow up PR to facilitate easy backporting
via the logstashmachine PR bot.

[ci] Initial aarch64 Buildkite resource

---

.buildkite/aarch64_pipeline.yml

[rn:skip]
This commit adds a skeleton Buildkite pipeline for aarch64 exhaustive tests.
- https://github.com/elastic/logstash/pull/15459
- https://github.com/elastic/ingest-dev/issues/1724

[ci] Initial aarch64 Buildkite pipeline

---

Gemfile.template

https://github.com/ruby/psych/issues/655 has been fixed with the release of 5.1.1.1

Remove pinning of psych 5.1.0

---

.buildkite/aarch64_pipeline.yml
.buildkite/scripts/common/vm-agent.sh

[rn:skip]
This commit is the first part of migrating away the aarch64 Jenkins jobs to Buildkite. It adds a group of exhaustive steps in the aarch64 pipeline.
https://github.com/elastic/ingest-dev/issues/1724

[ci] aarch64 Buildkite pipeline part 1

---

docker/templates/hardening_manifest.yaml

Update the hardening manifest UBI8 base image version to `8.7`

Update ubi8 base image to 8.7

---

.buildkite/aarch64_pipeline.yml

[rn:skip]
PR #15466 skipped the Java unit tests as on the `main` and `8.11` branches they attempted to run sonar scans (which are only meant to run for PRs).
This commit re-enables the Java unit tests, taking advantage of #15486, disabling the sonar scan part of the test suite.
Java unit tests are an important part of the aarch64 suite and should not be disabled because sonar scans can't work outside PRs.
- #15466 
- #15486 
- https://github.com/elastic/ingest-dev/issues/1724#event-10551685937

[ci] re-enable Java unit tests on aarch64 pipeline

---

.buildkite/aarch64_pipeline.yml
.buildkite/scripts/common/vm-agent.sh
ci/docker_acceptance_tests.sh

[rn:skip]
This commit is the follow up PR after #15466, which migrates away
the remaining aarch64 acceptance test Jenkins jobs to Buildkite.
- #15466
- https://github.com/elastic/ingest-dev/issues/1724

[ci] aarch64 Buildkite pipeline part 2

---

catalog-info.yaml

[rn:skip]
This commit enables slack notifications for aarch64 Buildkite pipeline failures.
https://github.com/elastic/ingest-dev/issues/1724#event-10551685937

[ci] Slack notifications for aarch64 pipeline

---

build.gradle

[rn:skip]
Adapted the JDK's download URL creation to intereact with Elastic catalog to get metadata, and return the catalog download link instead of directly pointing to Adoptium API
Let the CI work smoothly, using the unified source of JDKs.
Use Gradle task:
```sh
./gradlew copyJdk -Pjdk_bundle_os=windows -Pjdk_arch=x86_64
```
using differn OSes (`windows`, `linux`, `darwin`) and different CPU architectures (`x86_64`,`arm64`).
`arm64` is valid only for MacOS (Darwin).
- Closes #15513

Download of JDK from the Elastic catalog instead of Adoptium

---

catalog-info.yaml

[rn:skip]
This commit adds an initial Buildkite resource definition for JDK matrix tests.
**NOTE**: The actual pipeline is committed separately in the follow up PR #15520 to facilitate easy backporting
via the logstashmachine PR bot.

[ci] Initial jdk matrix Buildkite resource

---

.buildkite/jdk_matrix_pipeline.yml

[rn:skip]
This commit adds a skeleton Buildkite pipeline for the JDK matrix tests.
- https://github.com/elastic/logstash/pull/15519

[ci] Initial JDK matrix Buildkite pipeline

---

ci/test_plugins.rb

Properly exit 1 on error. This would properly allow the buildkite pipeline to fail.

Plugin Tests: Exit 1 on error

---

docs/static/ls-ls-config.asciidoc
docs/static/ls-ls-native.asciidoc

Update the Logstash to Logstash Native doc to reflect the multiple hosts usage.

---

catalog-info.yaml

[rn:skip]
This commit splits the generic Buildkite catalog resource introduced in #15519 for JDK tests to separate resources for Linux and Windows.
- https://github.com/elastic/logstash/pull/15520

[ci] Split JDK matrix resources per OS

---

qa/integration/specs/command_line_spec.rb

[rn:skip]
Adds filtering on Logstash output message in an integration tests when setting LS_JAVA_HOME environment variable.
As a developer I want to run integration tests customizing the JDK and not using the bundled one.
```sh
export LS_JAVA_HOME=/path/to/JDK
./gradlew runIntegrationTests -PrubyIntegrationSpecs="specs/command_line_spec.rb"
```
- Closes #15529

Fixed functional test in case the LS_JAVA_HOME is configured

---

catalog-info.yaml

[rn:skip]
This commit removes 8.10 from the automated builds of DRA artifacts, and should be merged once 8.11.0 is out.
- https://github.com/elastic/ingest-dev/blob/main/.github/ISSUE_TEMPLATE/logstash-release-checklist-minor.md#post-release-tasks

[ci] Remove 8.10 scheduled builds for DRA

---

.buildkite/scripts/jdk-matrix-tests/generate-steps.py
.buildkite/scripts/jdk-matrix-tests/launch-command.ps1
.buildkite/windows_jdk_matrix_pipeline.yml
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java

[rn:skip]
This commit adds JDK matrix Buildkite pipelines for Windows 2022, 2019 and 2016.
It also makes the groups easier to read (on both Linux and Windows pipelines) by removing the os-jdk prefix from the job labels.
`testDLQWriterFlusherRemovesExpiredSegmentWhenCurrentHeadSegmentIsEmpty` fails on Windows Buildkite agents and it's a test issue tracked in https://github.com/elastic/logstash/issues/15562.
<details><summary>Screenshot</summary>
</details>
This run demonstrates two failures (Windows 2022 + 2019) due to https://github.com/elastic/logstash/issues/15562 , as well a success (Windows 2019).
<details><summary>Screenshot</summary>
</details>
Note that we also collect [archived build artifacts](https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/27#018bb941-22 …

[ci] JDK matrix Buildkite pipelines (pt 2/Windows)

---

catalog-info.yaml

[rn:skip]
Buildkite Build's `maximum_timeout_in_minutes` and `default_timeout_in_minutes` are available now through the **catalog-info.yaml** file. As this change was made manually before we implemented this in RRE/Terrazzo, they got reverted to the default value (0); thus, I am raising this PR to get it as it was specified before the upgrade ([120 mins.](https://buildkite.com/elastic/terrazzo/builds/30112#018bbb61-1140-42c2-a482-f4db1245f449/6-3480))
- https://elasticco.atlassian.net/browse/ENGPRD-355 
- https://elasticco.atlassian.net/browse/CI-322

[Buildkite] Add pipeline max timeout property

---

.buildkite/linux_jdk_matrix_pipeline.yml

[rn:skip]
Fix typo for image name of Rocky Linux 8 for JDK matrix jobs.
- https://github.com/elastic/ingest-dev/issues/1725#event-10694112459

[ci] Fix image name for Rocky Linux 8

---

catalog-info.yaml

[rn:skip]
This commit adds a global max timeout of 90min for the supported plugins Buildkite pipeline. This prevents hanging builds (for 24hrs, which is the default).
- #15380
- https://elasticco.atlassian.net/browse/ENGPRD-355

[ci] Add 90min timeout for supported plugins test

---

.buildkite/aarch64_pipeline.yml
.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/dra/generatesteps.py
.buildkite/scripts/jdk-matrix-tests/generate-steps.py
.buildkite/windows_jdk_matrix_pipeline.yml

Add missing yaml-language-server definition to Buildkite pipeline files (static and dynamic generated) for consistency and to ease spotting errors with editors.
(cherry picked from commit cd01abb1c7cbcb3cfbbc1bc2e09e1e54b9f7d7dc)
Backport of #15590

[ci] Add yaml language server to pipelines (#15590)

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/jdk-matrix-tests/generate-steps.py

[rn:skip]
The last part of the Logstash JDK matrix CI migration from Jenkins to Buildkite is AmazonLinux 2023.
While we have a working image[^1], this is the only step that requires a agent that runs on AWS.
This commit refactors the builder to support GCP or AWS agents depending on the OS.
[^1]: https://github.com/elastic/ci-agent-images/pull/441

[ci] Support amazonlinux for JDK matrix pipeline

---

.buildkite/scripts/jdk-matrix-tests/generate-steps.py

[rn:skip]
So far we've been using images from the -qa GCP image project throughput the development of the Logstash Linux + Windows JDK matrix pipeline for quicker iteration.
As we have scheduled weekly builds of those images that promote to prod[^1] we can now switch to the prod version of the GCP images.
- https://github.com/elastic/ingest-dev/issues/1725#event-10694112459
[^1]: https://buildkite.com/elastic/ci-vm-images/builds/2888

[ci] Use GCP prod image for JDK matrix jobs

---

catalog-info.yaml

[rn:skip]
This commit enables scheduled runs of the JDK matrix pipelines for both Windows and Linux, once a week, Tuesdays at 1am UTC, using the pipeline defaults for OS and JDK.
- https://github.com/elastic/ingest-dev/pull/2647

[ci] Enable auto runs of JDK matrix pipelines

---

logstash-core/build.gradle
logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
logstash-core/src/main/java/org/logstash/plugins/aliases/AliasDocumentReplace.java
logstash-core/src/main/java/org/logstash/plugins/aliases/AliasPlugin.java

This removes the dependency on jackson's dataformat-yaml. Since there's only a single place where this library is used in core: to load the plugin alias definition, the code can be replaced by the underlying snakeyaml.

swap dataformat-yaml with snakeyaml

---

catalog-info.yaml

[rn:skip]
This commit adds a maximum default (global) timeout for every pipeline definition (now that it's possible to define this programmatically in an RRE).
The default values have been chosen arbitrarily based on intuition about how much (in the worst case) we should wait for each job to run until we consider them stuck/failed.
While at it, we update the yaml schema for RREs to point to the latest commit (rather than a pinned commit that doesn't reflect the latest changes, e.g. `maximum_default_timeout`).
Relates #15380

[ci] Explicit maximum timeout for pipelines

---

catalog-info.yaml

[rn:skip]
This commit enables slack alerts for the Linux part of the JDK matrix pipeline, which was missed in the previous PR#15593.
- #15593

[ci] Fix slack alerts for Linux JDK matrix pipeline

---

catalog-info.yaml

[rn:skip]
This commit adds a new resource for the Exhaustive tests Buildkite pipeline.
- https://github.com/elastic/ingest-dev/issues/1722
- https://github.com/elastic/logstash/pull/15607

[ci] Initial Exhaustive tests Buildkite resource

---

.ci/java-versions.properties

[rn:skip]
The last remaining Jenkins job prior to BK migration is for exhaustive tests. The compatibility phase seems to be failing since https://github.com/elastic/logstash/commits/57dc14c92 with Java 17.0.2
This commit switches from OpenJDK 17 (whose last release was 17.0.2) to AdoptiumJDK 17 which actively receives updates and is bundled in the custom images used by Jenkins. With this change compatibility tests should work again.
The issue with Java 17.0.2 can also be replicated with the JDK matrix BK pipeline: https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/57
- https://github.com/elastic/logstash/commits/57dc14c92
- https://github.com/elastic/ingest-dev/issues/1722

[ci] Switch to Adoptium JDK 17 for Jenkins CI

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/windows_jdk_matrix_pipeline.yml

[rn:skip]
AdoptOpenJDK is nowadays Adoptium, so we replace it in favor of the latter which is actively maintained.
- Relates https://github.com/elastic/logstash/pull/15628

[ci] Switch to Adoptium distro for JDK 11

---

.ci/java-versions.properties

This commit is a manual backport of #15628 on the 7.17 branch. Since 7.17 uses Java 11, we switch to the adoptium variant, which is still receiving updates (latest available is `11.0.21+9` as of now.)

[ci] Switch to Adoptium JDK 11 for Jenkins CI

---

docs/static/keystore.asciidoc
lib/secretstore/cli.rb
logstash-core/src/main/java/org/logstash/secret/cli/SecretStoreCli.java
logstash-core/src/test/java/org/logstash/secret/cli/SecretStoreCliTest.java

- Added support to add and remove multiple keystore keys in a single operation
- Fixed the empty value validation for editing existing key values
- Added ASCII validation for key values
- Added support to add and remove multiple keys in a single operation, example:
```shell
bin/logstash-keystore add FOO BAR
bin/logstash-keystore remove FOO BAR 
```
- Fixed the empty value validation for editing existing key values
- Added ASCII validation for key values
Currently, adding keys to the keystore need to call [command](https://www.elastic.co/guide/en/logstash/current/keystore.html#add-keys-to-keystore) `logstash-keystore add YOUR_KEY` one by one for each key, which is very time-consuming because it starts and stops JVM each time.
- Add and remove multiple keys
- Closes: …

Add support to add and remove multiple keystore keys in a single operation

---

logstash-core/lib/logstash/patches/puma.rb

Fix node stats API when the API path is invalid
The PR adds the missing method `debug?` in DelegatingLogWriter
Puma uses stderr to log error. DelegatingLogWriter takes IOWrappedLogger as [stderr](https://github.com/elastic/logstash/blob/v8.11.1/logstash-core/lib/logstash/patches/puma.rb#L60) and  IOWrappedLogger takes DelegatingLogWriter as logger. IOWrappedLogger checks logger level [here](https://github.com/elastic/logstash/blob/v8.11.1/logstash-core/lib/logstash/patches/puma.rb#L41).
The change allow node state to return meaningful error message
Run this branch and `curl -XGET 'localhost:9600/_node/stats/invalid_path'`. The response should not throw exception.
- Fixes: #15639
- Relates: https://github.com/elastic/logstash/pull/15158

Added missing method of logger wrapper for puma

---

.buildkite/exhaustive_tests_pipeline.yml
.buildkite/scripts/common/vm-images.json
.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
This commit adds the compatibility tier for the Exhaustive tests suite.
Specifically, we introduce two new groups (running in parallel) for Linux and Windows compat tests.
Linux picks one OS per family from https://github.com/elastic/logstash/blob/4d6bd955e6ae8e7c2758c75776670fdcc5480de2/.buildkite/scripts/common/vm-images.json and likewise Windows one of the three choices from the same file.
We also support manual override, if user chooses to, by setting `LINUX_OS` or `WINDOWS_OS` as env vars in the Buildkite build prompt (in this case, there is no randomization and only one OS can be defined for Linux and Windows respectively).
For example:
```
LINUX_OS=rhel-9
WINDOWS_OS=windows=216
```
Example run with defaults: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/ …

[ci] Compatibility tests for Exhaustive suite

---

.buildkite/pull-requests.json

[rn:skip]
Changes made under `docs/` are unrelated to the PR tests triggered from this repo[^1]
Note that the current docs-specific Jenkins Job is getting migrated at an org level[^2] and this change will be merged soon.
[^1]: via `.buildkite/pull_requests_pipeline.yml`
[^2]: https://github.com/elastic/docs/blob/master/.buildkite/pull-requests.org-wide.json
- https://github.com/elastic/ingest-dev/issues/2703

[ci] Skip Logstash PR checks when docs change

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java

[rn:skip]
In DLQ unit testing sometime the DLQ writer is started explicitly without starting the segments flushers. In such cases the test 's logs contains exceptions which could lead to think that the test fails silently.
Avoid to invoke scheduledFlusher's shutdown when it's not started (**such behaviour is present only in tests**).
The developer that looks at unit test output is not fooled by unrelated exceptions.
Run the 
```
./gradlew :logstash-core:javaTests --tests "org.logstash.common.io.DeadLetterQueueWriterAgeRetentionTest" …
```

Shutdown DLQ segments flusher only if it has been started

---

catalog-info.yaml
ci/branches.json

[rn:skip]
Now that we have a new 8.12 branch[^1], add it to CI definitions.
[^1]: https://github.com/elastic/logstash/tree/8.12

Add new 8.12 branch to CI

---

rubyUtils.gradle

[rn:skip]
We upgraded JRuby version to 9.4.5.0 and it seems `rubyUtils.gralde` was missed.
N.A
-

Update JRuby core to 9.4.5.0 of rubyUtils.gralde

---

catalog-info.yaml

Don't remove 8.11 yet as we may have 8.11.x maintenance releases until 8.12.0 is GA.

Update catalog-info.yaml to include testing for 8.12 branch

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java

[rn:skip]
Introduces a new interface named `SchedulerService` to abstract from the `ScheduledExecutorService` to execute the DLQ flushes of segments. Abstracting from time provides a benefit in testing, where the test doesn't have to wait for things to happen, but those things could happen synchronously.
The user in this case is the developer of test, which doesn't have to put wait conditions or sleeps in test code, resulting in more stable (less flaky tests, avoid time variability) and deterministic tests.
The local test just assures …

Separate scheduling of segments flushes from time

---

.buildkite/scripts/common/trigger-pipeline-generate-steps.sh
.buildkite/trigger_pipeline.yml

[rn:skip]
This commit fixes a bug introduced in #15668 related to the path of the script triggered by the trigger pipeline pipeline.
- https://github.com/elastic/logstash/pull/15668

Bug fix for trigger pipeline Buildkite pipeline

---

.buildkite/scripts/common/trigger-pipeline-generate-steps.sh
.buildkite/trigger_pipelines.yml
catalog-info.yaml

[rn:skip]
This commit enhances the functionality introduced in #15668 and #15700 by allowing a single Buildkite scheduling job to trigger several pipelines, in addition to multiple branches which it already does.
We rename the env var PIPELINE_TO_TRIGGER to PIPELINES_TO_TRIGGER which now supports comma separate values.
This enhancement can be useful for pipelines like JDK matrix which have variants (Linux and Windows) that we want to trigger with a single scheduling job, thus reducing unnecessary entries in catalog-info.
- Relates #15668 #15700

[ci] Allow schedule to trigger several pipelines

---

catalog-info.yaml

[rn:skip]
As an improvement from #15668 / #15700, rather than having one dedicated side-car scheduling job per pipeline, we move to a single scheduling job. Various pipelines that need triggering with different schedules now live under each schedule in the new pipeline.
This reduces the amount of jobs we have to maintain in yaml.
- Relates #15668 / #15700
- Supersedes #15704

Common scheduler pipeline for Buildkite

---

logstash-core/build.gradle

[rn:skip]
Replaces the usage of deprecated Gradle setting.
The reporting `enabled` setting flag has been deprecated by `required` property flag.
With this change we fix a deprecation warning that would transform in an error when moving to Gradle 8.5
Run Gradle with diagnostic flags enabled and check no warning is raised:
```sh
./gradlew  assemble --warning-mode all
```
- 
As a developer I want the upgrade to next Gradle 8.5 is smooth as possible.
``` …
```

Replace Gradle's report.enabled setting to report's required property

---

.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
This is the second part of the migration of the exhaustive/main Jenkins Job to Buildkite. So far we've migrated the "compatibility phase" and this commit adds the "testing phase"[^1], which is essentially the same amount of tests that we ran on PR jobs.
For more details, refer to the sequence diagram in https://github.com/elastic/ingest-dev/issues/1722#issuecomment-1824378635
This runs the usual set of unit + IT tests in the [exhaustive test pipeline](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline), e.g. triggered by push events.
See triggered BK job: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/41#_
Once triggered e.g. [in this link](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/41#_) in the structure looks …

[ci] Add testing phase to exhaustive tests suite

---

catalog-info.yaml

[rn:skip]
As a follow up to #15705, this commit shushes Slack alerts for the common Buildkite scheduling pipeline.
While at it, we also change the target slack channel to the proper one, in case we want to re-enable alerts in the future.
This is because the pipeline scheduler just triggers other pipelines which have their own dedicated alerts setup, therefore we want to avoid duplicate alerts when there is a failure with one of the triggered pipelines. An example of this kind of situation can be seen in [slack](https://elastic.slack.com/archives/C0D8VG3ND/p1704025480123649).

[ci] No Slack alerts for pipeline scheduling job

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/windows_jdk_matrix_pipeline.yml

[rn:skip]
The recent PRs #15668 and #15705 refactored jobs with a custom schedule to leverage a centralized trigger job.
An unexpected sideffect of this is that the conditional for the wait step doesn't work anymore.
This commit skips the wait step when the JDK matrix pipelines get triggered from another pipeline.
- #15668
- #15705

Don't block triggered JDK matrix Buildkite jobs

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/windows_jdk_matrix_pipeline.yml

[rn:skip]
This commit also skips the input step when the job is triggered from the scheduler pipeline.
PR#15729 missed the input step. As a result when the job is triggered the steps are executed, but the pause icon still shows in the job requiring manual unblock[^1]
[^1] https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/86

Skip input step when triggering JDK matrix jobs

---

.buildkite/pull_request_pipeline.yml
logstash-core/src/test/java/org/logstash/ackedqueue/CheckpointTest.java

[rn:skip]
This commit adds annotations for Java unit tests (in the pull request pipeline) allowing quickly scanning for failures.
An example of how annotations look can be seen in https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/617 (I introduced a deliberate bug in https://github.com/elastic/logstash/pull/15741/commits/ad4041629206f938a1ef81b466f7fd83681de509 to trigger it)
Otherwise, successful builds look like: https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/619
In a follow up PR we can duplicate the functionality for other pipelines that run the java unit tests (e.g. JDK matrix).
We'll also explore doing something similar with tests producing RSpec style output (e.g. Ruby tests); https://github.com/buildkite/rspec-buildkite may be useful.

JUnit result annotation for Buildkite PR jobs

---

qa/integration/integration_tests.gemspec

[rn:skip]
This commit pins the `childprocess` gem for integration tests to major version `4`.
- Closes https://github.com/elastic/logstash/issues/15757
Co-authored-by: Joao Duarte <jsvduarte@gmail.com>

Pin `childprocess` gem to major version `4`

---

.buildkite/exhaustive_tests_pipeline.yml
.buildkite/scripts/common/check-files-changed.sh

**Backport PR #15738 to 7.17 branch, original message:**
---
[rn:skip]
As we are close to sunsetting Jenkins by completing the exhaustive tests Buildkite pipeline, it makes sense to start already running the existing phases (testing and compatibility).
This commit defines the trigger to be code events, i.e. direct pushes and merge commits, similar to what we currently have in Jenkins.
It allows us to gradually remove the corresponding phases from Jenkins to reduce CI duplication.
This will be especially useful when merging https://github.com/elastic/logstash/pull/15696 as the change is incompatible with Jenkins.
An example build triggered manually can be found in https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/49#_
Unfortunately Windows tests will fail due to …

Backport PR #15738 to 7.17: Run BK exhaustive pipeline when code is pushed

---

catalog-info.yaml

[rn:skip]
Having enabled branch pushes as triggers for the exhaustive test pipeline, we have an unwanted sideeffect, that when using PR automation (@logstashmachine) to create backports, the temporary branches also triggered exhaustive tests.
This commit skips triggering this pipeline when upstream branches starting with `backport` get pushed.
I've tested this by manually editing the pipeline (via the UI):
and then triggering a [backport PR](https://github.com/elastic/logstash/pull/15792); notice that the exhaustive pipeline got skipped without issues:
Also tested that this filter (applied with the above UI modification in place) doesn't block jobs that should run, by triggering the exhaustive suite via this PR, which started as expected: …

Don't trigger exhaustive tests with backports

---

docs/static/troubleshoot/ts-kafka.asciidoc

add instructions to enable kerberos debug log
Fixes: https://github.com/elastic/logstash/issues/15802

[Doc] kerberos debug instructions

---

.buildkite/scripts/common/vm-agent-multi-jdk.sh
.buildkite/scripts/exhaustive-tests/generate-steps.py
.ci/java-versions.properties

**Backport PR #15781 to 7.17 branch, original message:**
---
[rn:skip]
This commit adds the packaging tests (that were refactored in #15696 to not rely on Vagrant) in a new "acceptance" group.
Once merged, we will have covered the biggest hurdle in migrating from Jenkins providing coverage for package testing. This PR coupled with https://github.com/elastic/logstash/pull/15748 concludes the migration.
Example triggered runs: TBD
- Depends https://github.com/elastic/logstash/pull/15696
- Relates https://github.com/elastic/ingest-dev/issues/1722

Backport PR #15781 to 7.17: Enable packaging tests in exhaustive pipeline #15806

---

.buildkite/scripts/dra/publish.sh

[rn:skip]
This commit makes the generated DRA URL easily accessible via a Buildkite annotation.
As explained in the [linked issue](https://github.com/elastic/ingest-dev/issues/2608), currently the link is buried under a lot of release manager generated output and can be difficult to spot.
This commit improves accessibility and readability.
Example DRA build triggered from this PR: https://buildkite.com/elastic/logstash-dra-snapshot-pipeline/builds/425
resulting in a clickable link (screenshot):
- Relates/Closes https://github.com/elastic/ingest-dev/issues/2608

Annotate successful DRA builds with summary URL

---

qa/acceptance/helpers.rb

[rn:skip]
The current mechanism of discovering the latest released version per branch (via ARTIFACTS_API) isn't foolproof near the time of a new release, as it may be pick a version that hasn't been released yet. This leads to failures of the packaging upgrade tests, as we attempt to download a package file that doesn't exist yet.
This commit switches to an API that that is more up to date regarding the release version truth.
Note that branch `7.17` isn't affected by this issue as we are attempting an upgrade from the previous minor (which is guaranteed to be released): https://github.com/elastic/logstash/blob/c0f13dfe3f8738b0c64c23c9b8ca722d56fa92bc/qa/acceptance/spec/shared_examples/updated.rb#L36
[^1]: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/125#018d319b- …

Fix acceptance/packaging upgrade test near a release

---

build.gradle
buildSrc/src/main/groovy/org/logstash/gradle/tooling/SnapshotArtifactURLs.groovy

**Backport PR #15827 to 7.17 branch, original message:**
---
[rn:skip]
This commit fixes IT failures that frequently occur after version bumps due to missing unified release snapshot builds for the new version.
This commit uses project specific DRA snapshot URLs for ES and Filebeat
in all cases apart from release builds.
This is a very important to fix as several pipelines (PR, exhaustive, JDK matrix, aarch64) run IT tests as a prerequisite and produce unnecessary failures shortly
after version bumps, possibly blinding us from genuine issues.
See CI from backporting this PR to `8.12`: 
- https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/747
- https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/743
and compare to …

Backport PR #15827 to 7.17: Fix IT tests after version bumps #15838

---

Gemfile.jruby-2.5.lock.release
versions.yml

[rn:skip]
Bumps version on 7.17 branch after 7.17.17 release so that upcoming snapshots builds will be tagged 7.17.18

Bump 7.17.18

---

logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java

[rn:skip]
This commit mutes the DLQ test:
`testDLQWriterFlusherRemovesExpiredSegmentWhenCurrentHeadSegmentIsEmpty` when running on Windows.
Using this PR:
Example windows build: https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/82#_
Example Linux build: https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/754#018d376b-b614-4fa2-9a63-d8433bcc1207
- Closes https://github.com/elastic/logstash/issues/15768

Mute DLQ test on Windows

---

.buildkite/serverless_integration_pipeline.yml

[rn:skip]
This commit adds (up to 3) retries for all steps of the
serverless-integration-testing pipeline as a stop-gap measure to prevent network related transient failures.
We want to reduce transient CI noise until we fix this in gradle (see https://github.com/elastic/logstash/issues/14286).
Example build: https://buildkite.com/elastic/logstash-serverless-integration-testing/builds/264#018d40f7-c2cd-44c6-a820-c671412c57fa (no failure observed)
- Relates: https://github.com/elastic/logstash/issues/14286

Retries for serverless-integration-testing pipeline

---

docs/static/ea-integrations.asciidoc

Fixes: #15740 
Topic: https://www.elastic.co/guide/en/logstash/master/ea-integrations.html
* Update the feature docs to link to the plugin docs rather than the plugin repo
* Add ECS compliance to list of benefits of starting with an integration
* Explain the reasoning behind the recommendation that `filter-elastic_integration` should be the first filter in your pipeline
**PREVIEW:** https://logstash_15747.docs-preview.app.elstc.co/guide/en/logstash/master/ea-integrations.html

Doc: Update extending integrations docs to point to plugin

---

docs/static/monitoring/monitoring-ea-dashboards.asciidoc
docs/static/monitoring/monitoring-ea-serverless.asciidoc
docs/static/monitoring/monitoring-ea.asciidoc
docs/static/monitoring/monitoring-mb.asciidoc
docs/static/monitoring/monitoring-prereq-disable-default.asciidoc

[rn:skip] 
Our [enable Logstash monitoring doc](https://www.elastic.co/guide/en/logstash/current/monitoring-with-metricbeat.html#disable-default) has a discrepancy. It sounds a message that if we remove `#` in front of `monitoring.enabled: false` setting, the monitoring will be enabled.
This PR adds "set it to `true`" followed message so that entire statement will be clearer.
It also suggests to change _false-positive_ title message (Disable default collection of Logstash monitoring metrics) to simply saying _**Enable Logstash monitoring**_, because guide page's goal is to bring customer to collect Logstash monitoring data with Metricbeat.
Some users are getting confused with a statement.
-

[docs] Simplify and improve Logstash monitoring docs.

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/common/vm-images.json

[rn:skip]
Remove Ubuntu 18.04 from CI jobs.
- Relates https://github.com/elastic/ingest-dev/issues/2849

Remove Ubuntu 18.04 from CI jobs

---

.buildkite/scripts/common/trigger-pipeline-generate-steps.sh
catalog-info.yaml

[rn:skip]
This commit adds a schedule to run non-main branches of the exhaustive pipeline (biweekly, every other Wednesday @2AM UTC)
and all branches of the aarch64 (weekly, every Monday@2AM UTC).
As described in https://github.com/elastic/ingest-dev/issues/2852:
- exhaustive is currently triggered with push events, and for branches with low traffic e.g. `7.17` we also want to get coverage on a regular basis to have a regular baseline and catch potential external issues (unpinned gem updates, packaging/os issues etc.)
- `aarch64` is currently manually triggered, and we'd like coverage on all branches for similar reasons.
The main thing to test is the enhancement of the shell script to exclude branches:
```
$ PIPELINES_TO_TRIGGER="logstash-exhaustive-tests-pipeline" …
```

Scheduled runs of exhaustive and aarch64 pipelines

---

NOTICE.TXT
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/base64-NOTICE.txt

the new version of dalli gem now explicitly depends on "base64" gem. this commit introduces base64's entry to the licenseMapping.
Also updates the generated NOTICE.txt

add base64 notice and update generated NOTICE.txt

---

catalog-info.yaml

[rn:skip]
Currently for pipelines that have steps with auto retries, if there is a failure of a step, even if the subsequent retry succeeds, we receive Slack alerts.
This commits uses new functionality[^1] available in the Buildkite PR Bot to avoid Slack notifications in those cases and changes the settings for all pipelines where we have, or expect to have, retries.
Reduce alert noise for non-actionable events in the Slack channel.
Can't be tested, needs to be merged for the change to get picked up by terrazzo.
[^1]: https://github.com/elastic/kibana-buildkite-build-bot/commit/95102e37dd14e95cf8c5eb32a4027d6b14f3fb73

[ci] Skip slack alerts if retried tasks succeeded

---

catalog-info.yaml

[rn:skip]
This commit fixes a bug instroduced in PR#15850 and uses the correct pipeline name when triggering the aarch64 pipeline on schedule.
- Relates https://github.com/elastic/ingest-dev/issues/2852

Fix typo with aarch64 pipeline name to trigger

---

.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
As a follow up to #15787 we also add Buildkite retries for the exhaustive pipeline / compatibility group steps to prevent failures due to flakiness.
Reduce build noise/improve OKRs esp. since most of the errors, e.g. https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/166#018d596b-b946-4971-b522-e00e2ddbe1ff/48-55
are due to transient network related timeouts while gradle downloads from remote repositories/artifactories.

Add BK retries to exhaustive/compat steps

---

.buildkite/scripts/jdk-matrix-tests/generate-steps.py

[rn:skip]
This commit adds retries to the steps of the Linux + Windows JDK matrix pipeline steps.
Helps prevent unnecessary CI failures/notification noise due to transient network errors.
Just run something like:
`MATRIX_OSES="ubuntu-1804" MATRIX_JDKS="adoptiumjdk-17" python3 .buildkite/scripts/jdk-matrix-tests/generate-steps.py | yq .`
to see the `retry: ` section added in the Linux steps e.g.
```
- label: x-pack integration
key: windows-2022_adoptiumjdk-17-x-pack-integration
depends_on: windows-2022-adoptiumjdk-17-initialize-annotation
...
retry:
automatic:
- limit: 3
```
Likewise for the Windows pipeline:
`MATRIX_OSES="windows-2022" MATRIX_JDKS="adoptiumjdk-17" python3 .buildkite/scripts/jdk-matrix-tests/generate-steps.py | yq .`
See also triggered PR jobs:
- …

Add retries to JDK matrix pipeline steps

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/common/vm-images.json

[rn:skip]
This commit adds Debian 12 (Bookworm) to the
Linux JDK matrix pipeline and Compat Phase of the
exhaustive pipeline respectively.
This is important to ensure we have coverage for Debian 12.
Link:
- JDK matrix: https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/123
- Relates https://github.com/elastic/ingest-dev/issues/2871

Add Debian 12 to CI

---

.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
Similarly to #15874, this commit adds retries
to another group `acceptance/docker` to reduce
build noise from transient issues.
Reduces alert noise for transient failures.
Test: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/195 (see the entry like https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/195#018d7df9-183c-4231-bcde-79eec2de45a1/101-719)

Add retries to acceptance/docker steps in BK

---

qa/acceptance/spec/shared_examples/installed.rb
qa/acceptance/spec/shared_examples/installed_with_jdk.rb
qa/rspec/commands.rb
qa/rspec/commands/base.rb

**Backport PR #15900 to 7.17 branch, original message:**
---
[rn:skip]
This commit fixes the startup of the Logstash service during packaging tests by adding a minimal pipeline config.
Without it, the service was flapping from start to start and vice versa causing test flakiness.
Test link: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/199
- Relates https://github.com/elastic/logstash/issues/15784

Backport PR #15900 to 7.17: Fix service startup with acceptance tests #15905

---

Gemfile.jruby-3.1.lock.release
versions.yml

[rn:skip]
Bumps the version of 8.12 branch to 8.12.2
Non user facing change.

Version bump to 8.12.2

---

Gemfile.jruby-2.5.lock.release
versions.yml

[rn:skip]
Bumps version of 7.17 branch to 7.17.19.
Non user facing change.

Version bump 7.17.19

---

docker/Makefile
docker/data/golang/Dockerfile
docker/data/logstash/env2yaml/go.mod
docker/data/logstash/env2yaml/go.sum

Updated the env2yaml to have a go.mod instead of relying on disabling go modules, otherwise building with golang 1.22 will fail.
This change also directly uses the golang image to build the binary removing the need for an intermediate image.
Tested locally and also with buildkite build docker image:
```
> curl https://artifacts-snapshot.elastic.co/logstash/8.13.0-37a00f62/downloads/logstash/logstash-8.13.0-SNAPSHOT-docker-image-aarch64.tar.gz | docker load
❯ docker run -e PIPELINE_WORKERS -it  docker.elastic.co/logstash/logstash:8.13.0-SNAPSHOT grep build_sha logstash-core/lib/logstash/build.rb
BUILD_INFO = {"build_date"=>"2024-02-08T11:58:19+00:00", "build_sha"=>"7465a35f681caa57b60d49512b0d22111e36bad6", "build_snapshot"=>true}
❯ PIPELINE_WORKERS=2  docker run -e PIPELINE_WORKERS -it …
```

introduce go.mod for env2yaml

---

tools/jvm-options-parser/build.gradle
tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
tools/jvm-options-parser/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java

Updates Netty's configuration of maxOrder to a previously proven value, if not already customised by the user.
Adds a step to the JvmOption parsing tool, which is used to compose the JVM options string to pass down to Logstash at startup.
The added step rework the parsed options to set  the allocator max order `-Dio.netty.allocator.maxOrder=11` so that the maximum pooled buffer is up to 16MB and not 4MB. 
This option is added iff it's not yet specified by the user
It brings back the performance of Netty based plugins to the same as of Logstash previous of `8.7.0`, which introduced an update of Netty library.
With messages bigger then 2Kb each it triggered a problem of using unpooled buffers, which kills performance. With this change it moved back to 8Kb.
- ~~[ ] I have made corresponding …

Set Netty's maxOrder options to previous default

---

docker/Makefile
docker/templates/Dockerfile.erb
rakelib/artifacts.rake

Logstash on ECK requires `openssl` command to  build TLS keystore. logstash-ubi:8.12.0 has openssl command, but 8.12.1 and 8.12.2 don't.
This commit adds `microdnf install -y openssl` to ensure the command exists in ubi image
relates: https://github.com/elastic/cloud-on-k8s/issues/7544

add openssl to ubi image

---

lib/pluginmanager/remove.rb
rakelib/artifacts.rake
rakelib/default_plugins.rb
rakelib/plugin.rake
rakelib/plugins-metadata.json

[rn:skip]
- Introduces a feature (based on `oss-skip` flag of the plugin metadata) to exclude plugins in OSS distributions
- Sets `elastic_integration` plugin as a default plugin
CI fails were due to https://github.com/elastic/logstash-filter-elastic_integration/pull/114
- We face error if make the plugin as a default now because the `TarWriter` (in `assembleOssTarDistribution` gradle task) complains on the path which cannot be longer than 256. The workaround is to shorten the JAR path in th plugin, the PR: https://github.com/elastic/logstash-filter-elastic_integration/pull/114. We need to merge the PR and release new version of the plugin.
Non-user affected.
- [] ~~I have made corresponding changes to the documentation~~
Before merging:
- [DRA …

Package `elastic_integration` plugin.

---

qa/rspec/commands/system_helpers.rb

[rn:skip]
This commit tightens the checks for the status
output of the Logstash OS service to specifically
scan for `org.logstash.Logstash` rather than
only the jdk path.
The reason is that the startup script first runs
an options parser, and then the logstash process
itself, both referencing the JDK path.
Currently packaging tests can be flaky (esp. on RPM distros) which we circumvent with Buildkite native retries (which doesn't always help).
BK link to exhaustive job: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/245
I also ran it in several iterations of loops like below on a rhel-8 VM and didn't get any failure, whereas I'd always get a failure without the PR:
```
for i in {1..30}; do echo ">>> Iteration $i"; bundle exec rspec acceptance/spec -e 'behaves like …
```

Fix packaging service check failures

---

qa/acceptance/spec/lib/artifact_composition_spec.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/generate.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/integration_plugin.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb
qa/acceptance/spec/shared_examples/cli/logstash/version.rb
qa/acceptance/spec/shared_examples/running.rb
qa/acceptance/spec/shared_examples/updated.rb

[rn:skip]
PR #15900 missed a few more places where Logstash is installed but a working minimal pipeline config is added.
This commit adds the missing config in all remaining places.
It reduces the time spent for [with_running_logstash_service](https://github.com/elastic/logstash/blob/3c9db658bc7c64eb0da2ed40936382535a84ff21/qa/acceptance/spec/spec_helper.rb#L23-L33) -- for example [here](https://github.com/elastic/logstash/pull/15907/files#diff-8e95d7180ce6b86912a0dc5f958958c60bc6e5831ab8b55fd123720b081c9644L48) -- to succeed (or maybe even fail, after 40 retries).
Example run:
- Relates https://github.com/elastic/logstash/issues/15784

Follow up to #15900 -- fix remaining acceptance tests

---

sonar-project.properties

Explicitly specifies test sources for sonar
We can't use `sonar-grade-plugin` due to multilanguage support.  Hence we need to narrow the coverage scope and explicitly specify the test sources using a glob pattersn

[CI] [Sonar] Explicitly specified test sources for sonar

---

build.gradle
tools/jvm-options-parser/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java

[rn:skip]
Adds a global new task named `javaTests` which groups  both `:logstash-core:javaTests` and `:jvm-options-parser:test` to include the JvmOptionParser unit test in javaTests phase.
The submodule `jvm-options-parser` is used in the Logstash JVM bootstrap process, so has to be part of the continuous integration test suites.
- Closes #15927

Added :jvm-options-parser subproject to the javaTests task

---

rubyUtils.gradle
versions.yml

- test run of all plugins resulted in https://github.com/logstash-plugins/logstash-output-http/pull/141
- exhaustive test suite https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/266

bump jruby to 9.4.6.0 and remove ffi workaround

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java

[rn:skip]
Adds a burning of time condition to avoid a collision of time which, under certain circumstances, would fail the test.
The sealing of a segment happens if the segment is considered as `stale`, which requires 2 conditions:
- the segment must have received a write
- the time of the last write must exceed the flush interval.
In this failing test, the flush interval is set to `ZERO` because of the synchronicity of the test, to avoid time dependency. However, with coarse grain timer resolution, could happen that the last write coincide with the time of the stale check, so fail the seal condition.
As a developer the test should work the same way on multiple OSes, independently of time schedules.
- ~~[ ] I have made …

Fix failing DLQ test due to time scheduling

---

rakelib/plugins-metadata.json

[rn:skip]
Sets the imap plugin as a non-default plugin, so that Logstash will not carry it with its distribution.
We will try our best to keep the plugin up-to date.
- Pull the changes
- `./gradlew clean bootstrap assemble installDefaultGems` will install the default plugins where imap plugin will not be under vendor
- 
When running Logstash without installing imap plugin:
```
➜  logstash …
```

Set Imap plugin as a non-default plugin.

---

docker/Makefile
docker/templates/Dockerfile.erb

This commit builds env2yaml in arm64 and amd64 flavors, and uses $TARGETARCH in the Dockerfile to ensure that the correct version is used when building for alternative architectures
Fixes: #15913

Add arm64 support for env2yaml

---

x-pack/lib/geoip_database_management/manager.rb
x-pack/spec/geoip_database_management/manager_spec.rb

Fixes an issue in which the GeoIP filter could fail to start when the GeoIP Database Manager was disabled and had never been configured.
Resolves: logstash-plugins/logstash-filter-geoip#222
When a user does not have GeoIP Database Management enabled, they are unlikely to have a managed directory so we should not crash trying to clean up something that doesn't exist.
- Resolves: logstash-plugins/logstash-filter-geoip#222

geoip: avoid crash cleaning non-existing managed dbs

---

docs/static/monitoring/monitoring-ea-dashboards.asciidoc

The preview for #15981 on the `current` branch doesn't have the problem I'm trying to fix in `main`. The problem still exists in built docs, but not the preview. 
The unnecessary `+` needs to be removed from the source file anyway, so I'm using it as a test so that I can check out the preview.

Doc Test: Remove extra `+` to force page to rebuild

---

Gemfile.template
logstash-core/logstash-core.gemspec
rakelib/artifacts.rake
rubyUtils.gradle
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/ruby-maven-libs-NOTICE.txt

~~Given Logstash doesn't ship with any gems that download jars at install time we can exclude the ruby maven lib jars~~
Upgrade ruby-maven-libs to 3.8.9

upgrade ruby-maven-libs to 3.8.9

---

Gemfile.jruby-2.5.lock.release

Updates the Elasticsearch output to include a fix for situations where events containing non-unicode strings could be serialized incorrectly when sending to Elasticsearch with http compression enabled
Updates ES output to consume https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1171
When compression is enabled and events contain non-unicode characters, without this fix invalid payloads could be sent to Elasticsearch resulting in indexing rejections.
- ~~[ ] I have added tests that prove my fix is effective or that my …

Bump ES output to include unicode-vs-compression fix

---

docker/data/logstash/env2yaml/env2yaml.go

This PR fixes the historical bug: when running Logstash in a docker container with ENV variables, `env2yaml` tool saves ENV `${KEY}=${VALUE}` by resolving its _actual value_. This will be an issue when keystore has a same ${KEY} where the expected behavior is to be keystore precedence.
If users are using same ${KEY} in both keystore and docker ENV, they may see the behavior where keystore  ${KEY}=VALUE will be used.
- pull this PR
- run `rake artifact:docker` -> creates an docker image (see the logs below)
- run the container with …

Save  name came through ENV vars to let Logstash decide using value from either keystore or ENV.

---

docker/templates/Dockerfile.erb
docker/templates/hardening_manifest.yaml.erb

- remove golang assets (go1.17.8.linux-amd64.tar.gz)
- remove yaml lib assets (v2.3.0.tar.gz)
- use go container to build env2yaml
- remove unnecessary layers
- remove HEALTHCHECK
- switch yum to dnf
I have made some changes from the suggested Dockerfile
- remove `COPY v2.3.0.tar.gz /tmp/env2yaml.tar.gz`
- remove `mkdir -p /usr/local/src/vendor/gopkg.in && \
tar -zxf /tmp/env2yaml.tar.gz -C /go && \`
- add `mv config/* /usr/share/logstash/config && \
mv pipeline /usr/share/logstash/pipeline && \`
- add `rmdir config && \`
Fixes: https://github.com/elastic/ingest-dev/issues/3008
- run `rake artifact:dockerfile_ironbank`
- take `Dockerfile` and `hardening_manifest.yaml` from logstash/build/logstash-ironbank-8.14.0-SNAPSHOT-docker-build-context.tar.gz
- create a test PR in GitLab with those …

Modernize ironbank Dockerfile

---

.github/workflows/critical_vulnerability_scan.yml

Change trigger from pull_request_target to pull_request, as the former uses the base branch instead of the PR source code. This allows simplification of the checkout action (also took the opportunity to bump from v2 to v4).

Fix github checkout for critical_vulnerability_scan action

---

build.gradle
lib/bootstrap/rspec.rb
logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb
logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java
logstash-core/src/main/java/org/logstash/config/ir/expression/RegexValueExpression.java
logstash-core/src/main/java/org/logstash/config/ir/graph/Edge.java
logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java
logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
logstash-core/src/main/java/org/logstash/instrument/monitors/HotThreadsMonitor.java
logstash-core/src/main/java/org/logstash/plugins/inputs/Stdin.java
logstash-core/src/main/java/org/logstash/util/UtilExt.java
logstash-core/src/test/java/org/logstash/ext/JrubyMemoryReadClientExtTest.java
logstash-core/src/test/java/org/logstash/log/TestingDeprecationPlugin.java
logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
logstash-core/src/test/java/org/logstash/secret/store/SecretStoreFactoryTest.java

Adaptations to run Logstash on JDK 21
Adaptations to JDK 21:
- Java 8 support is obsolete and will be removed.
- Thread's `getId` (not final) replaced by final `threadId` https://bugs.openjdk.org/browse/JDK-8017617
- Verify the warnings "this-escape" when a constructor use other method or pass around `this` reference to other methods https://bugs.openjdk.org/browse/JDK-8015831
- URL constructor is deprecated, use `<uri_instance>.toURL()` (since JDK 20)
-  Manages new (since JDK 20) `G1 Concurrent GC` MX Bean, [ref](https://github.com/elastic/logstash/pull/15719#issuecomment-1946367785)
As a developer I want that all the blockings to use JDK 21 are removed before effectively switching the bundled JDK to version 21
- ~~[ ] I …

JDK 21 move

---

docker/templates/Dockerfile.erb

This commit adds logic to copy the appropriate env2yaml file to the Docker image

Update Dockerfile to select appropriate architecture on build box

---

.buildkite/scripts/snyk/report.sh

[rn:skip]
Replaces `git show-ref` with `git checkout` to fix the issue where show-ref is not showing the branch needs to be checked out.
Not user impacted.
- 
- when branch exists
```
➜  logstash git:(upstream-main) ✗ ./.buildkite/scripts/snyk/report.sh
08e2162ee8a00616f207ce7797e1bee477d4e7bf
Reporting 8.13 branch.
0600ff98bbd54918c8d18d2e4372f96c71dc235c
Reporting main branch.
```
- when branch doesn’t exist
```
➜  logstash git:(upstream-main) ✗ …
```

Fix the git branch check.

---

tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
tools/jvm-options-parser/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java

Bugfix to parse correctly Java options when the environment variable LS_JAVA_OPTS contains multiple definitions separated by space character.
Adapt the parsing of `LS_JAVA_OPTS` environment variable to split by space various definitions it can contains.
Permit the user insert multiple space separated options in `LS_JAVA_OPTS`, fixing a bug that created duplicated maxOrder option when used by Docker.
```sh
export LS_JAVA_OPTS=" -Xmx4g -Dio.netty.allocator.maxOrder=6" && bin/Logstash -e "input{stdin{}} output{stdout{codec => rubydebug}}"
```
In Logstash's logs shouldn't appear both `-Dio.netty.allocator.maxOrder=6` and …

Split LS_JAVA_OPTS content when contains multiple options

---

docs/static/monitoring/monitoring-ea-dashboards.asciidoc
docs/static/tab-widgets/install-agent.asciidoc

Fixes: #15882 
Screenshots are not rendering properly inside widgets. The widgets are documenting guided flows, and the screenshots are not critical for understanding.  Note that I am not deleting the image files. They're still in place for when/if we decide to find a workaround and reimplement them. 
**PREVIEW:** https://logstash_bk_15981.docs-preview.app.elstc.co/guide/en/logstash/master/dashboard-monitoring-with-elastic-agent.html

Doc: Remove include statements for screenshots not rendering properly

---

Gemfile.template

follow up to https://github.com/jruby/ruby-maven-libs/pull/5

force ruby-maven-libs constraint to >= 3.9.6.1

---

logstash-core/lib/logstash/compiler/lscl/lscl_grammar.rb
logstash-core/lib/logstash/compiler/lscl/lscl_grammar.treetop
logstash-core/lib/logstash/config/grammar.rb
logstash-core/lib/logstash/config/grammar.treetop
logstash-core/spec/logstash/config/config_ast_spec.rb

Fixed the syntax rules to allow comments between hash entries and immediately before the end of a file. Comments in these places would previously give syntax errors.
In the grammer definitions for hashes, `whitespace` was replaced with `cs` to allow either whitespace _or_ comments. 
Additionally, the grammar definition for comments was previously required to end with a newline, now it can end with a newline _or_ EOF, using the "not anything" treetop rule `!.`.
Users get surprised when they find out that comments are not allowed in hashes or at the end of a file.
This is allowed in practically all other languages, including ruby.
This PR thus aligns Logstash syntax with user expectations.
- AFAICT, no automated check for this? I believe it follows the guide though.
- I only added syntax, …

feat(syntax): allow comments in hashes and before EOF

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/api/commands/default_metadata.rb
logstash-core/spec/logstash/webserver_spec.rb
logstash-core/src/main/java/org/logstash/health/HealthObserver.java
logstash-core/src/main/java/org/logstash/health/Status.java
logstash-core/src/test/java/org/logstash/health/StatusTest.java

[rn:skip]
- Introduces `org.logstash.health.HealthObserver` that is accessible via `Agent#health_observer`
- Introduces `org.logstash.health.Status` with facilities for combining statuses
- Populates API-common top-level `status` with `HealthObserver#status`. In bootstrap form, the value is controlled by system property `logstash.apiStatus`, but will be derived from indicators once they are added in a subsequent PR.
These are steps toward delivering the health report API as RFC'd in #16056
To prove that the value of API response's `status` is no longer hard-coded to green, 
this bootstrap contains a hidden feature flag …

[health] bootstrap HealthObserver from agent to API

---

docs/static/config-details.asciidoc
docs/static/settings-file.asciidoc

[rn:skip] 
**PREVIEW:** https://logstash_bk_16083.docs-preview.app.elstc.co/guide/en/logstash/master/jvm-settings.html
Adds section to describe the intended usage of  and impact on memory sizing.
Give better insights when to use the `pipeline.buffer.type` and which is the expected impact on performance and memory consumption.
- Relates #16054

Adds section to describe intended usage of `pipeline.buffer.type`

---

logstash-core/src/main/java/org/logstash/config/ir/DSL.java

Replaces unnecessary trace loggings with logger in the DSL.
No need to log with trace.
- Closes #16103

Replace stack traces with logger in DSL.

---

versions.yml

Update bundled JDK to 21
Updated bundled JDK to 21.
Seems all plugins are fine: https://buildkite.com/elastic/logstash-supported-plugins-test-pipeline/builds/51.
-

Update bundled JDK to 21

---

docs/static/config-management.asciidoc

As the module is not maintained since 2018 and it was community supported, I would like to remove it from the documentation.
If possible, please backport it to previous versions.
FYI @karenzone please reach me out if you have any question.

[DOC] Remove reference to puppet LS module

---

logstash-core/lib/logstash/json.rb
logstash-core/lib/logstash/util/unicode_normalizer.rb
logstash-core/lib/logstash/util/unicode_trimmer.rb
logstash-core/spec/logstash/json_spec.rb
versions.yml

Handle non-unicode payload in Logstash.

---

rakelib/plugins-metadata.json

Adding `integration-snmp` to plugins-metadata.json so that it will be picked up for the Logstash Reference plugin docgen
After the VPR job ran and picked up `integration-snmp`, I kicked off a docgen for Logstash Reference on `main`.  It didn't pick anything up, and I believe that's because we need this piece added to plugins-metadata.json. 
@jsvd, what changes should I make to `input-snmp` and `input-snmp-trap` settings in [https://github.com/elastic/logstash/blame/main/rakelib/plugins-metadata.json](https://github.com/elastic/logstash/blame/main/rakelib/plugins-metadata.json)? 
At 8.15 I believe that we'll want to set the individual plugins to `"skip-list": true`. Is the current config acceptable in the interim?

Update plugins-metadata.json with integration-snmp: set skiplist to false

---

logstash-core/lib/logstash/json.rb
logstash-core/lib/logstash/util/unicode_normalizer.rb
logstash-core/lib/logstash/util/unicode_trimmer.rb
logstash-core/spec/logstash/json_spec.rb
versions.yml

Automatic backport didn't work due to conflict (attaching following logs) in `versions.yml` file. Manually cherry picking https://github.com/elastic/logstash/pull/16072
```
INFO: Checkout of 8.14 to backport to...
INFO: Creating backport branch backport_16072_8.14...
INFO: Merge commit detected from PR: 979d30d7016db6f0df8150f794a74d[37](https://github.com/elastic/logstash/actions/runs/9116832148/job/25066303742#step:12:38)85199fb2
INFO: Cherry-picking 979d30d7016db6f0df8150f794a74d3785199fb2
INFO: Looks like you have cherry-pick errors.
INFO: Fix them, then run: 
INFO:     git cherry-pick --continue
INFO:     devtools/backport 8.14 16072 --remote=origin --yes --continue
```
-

Handle non-unicode payload in Logstash. (#16072)

---

docs/static/persistent-queues.asciidoc
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

Fixes an issue in which an input writing to a PQ could become blocked indefinitely after writing an event that _precisely_ fit the remaining capacity of a PQ configured to handle a single PQ-page of events.
A PQ is considered full (and therefore needs to block before releasing the
writer) when its persisted size on disk _exceeds_ its `queue.max_bytes`
capacity.
This removes an edge-case preemptive block when the persisted size after
writing an event _meets_ its `queue.max_bytes` precisely AND its current
head page has insufficient room to also accept a hypothetical future event.
A block formed in this way would only be broken the next time a tail page
is fully-acked, which cannot occur when the `queue.max_bytes` is configured
to match `queue.page_capacity`.
Users who configure their …

PQ: avoid blocking writer when precisely full

---

rakelib/plugins-metadata.json

[rn:skip] to leave this PR out of release notes 
This PR moves `logstash-integration-internal` and `logstash-integration-zeromq` plugins to [plugins-metadata.json](https://github.com/elastic/logstash/blob/main/rakelib/plugins-metadata.json ) and configure them as `default-plugins: false` and `"skip-list": true` to set us up to make the next set of changes to docs tooling. 
- ToDo:  Change docs tooling to remove skip logic for integration plugins. 
Related: https://github.com/elastic/docs-tools/issues/106

Add incomplete integration plugins to metadata.json as skip

---

rakelib/plugins-metadata.json

The new [snmp-integration-plugin](https://github.com/logstash-plugins/logstash-integration-snmp) combines the [logstash-input-snmp](https://github.com/logstash-plugins/logstash-input-snmp) and [logstash-input-snmptrap](https://github.com/logstash-plugins/logstash-input-snmptrap) plugins into one, and is meant to replace the individual plugins. This PR makes it a default plugin, and removes the individual ones from the default and docs listing.
Clean install with default gems will create a `Gemfile` which includes the SNMP integration plugin:
```shell
./gradlew clean bootstrap assemble installDefaultGems
```

Bundle integration-snmp and remove input-snmp and input-snmptrap from default plugins/docs

---

config/log4j2.properties
docs/static/logging.asciidoc

**Docs PREVIEW:** https://logstash_bk_16179.docs-preview.app.elstc.co/guide/en/logstash/master/logging.html#log4j2
Update logging configuration to remove rolled files older than seven days.
Updates the plain, json and pipeline appenders in default `config/log4j2.properties` to define a delete rule executed during the rollover strategy, which deletes compressed log archives older than 7 days.
Updates the documentation that the describe the logging configuration to explain how the rollover file works, how to configure the strategy in particular how also update to have space limitation condition on the rollover.
With this commit the user doesn't have anymore problems of disk space exhaustion due to aged log files.
- …

Update log4j rollover to configure time retention

---

logstash-core/lib/logstash/config/source/multi_local.rb
logstash-core/spec/logstash/config/source/multi_local_spec.rb

Revert pr #16050, which avoided to replace environment variables (${VAR}) inside config.string in the pipelines.yml file, but that created a regression, because env vars is expected to be replaced in all the other yaml keys.
- Relates #16199
- Relates #16008
- Relates #16050

Revert pr #16050

---

Gemfile.template

[rn:skip]
Pin `rexml` gem version to 3.2.6 as the newst releases are breaking the build/CI (to be investigated):
```
checking for onig_region_memsize() in ruby.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
--with-opt-dir
--without-opt-dir
--with-opt-include
--without-opt-include=${opt-dir}/include
--with-opt-lib
--without-opt-lib=${opt-dir}/lib
--with-make-prog
--without-make-prog
--srcdir=.
--curdir
--ruby=/home/runner/work/logstash/logstash/vendor/jruby/bin/jruby
RuntimeError: The compiler failed to generate an executable file.
You have to install development tools first.
try_do at …
```

Pin rexml gem version to 3.2.6

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java

Bugfixes DLQ's `queue_size_in_bytes` on the writer side when the reader uses `clean_consumed` and purge consumed segments.
Updates the DLQ reader to create a notification file (`.deleted_segment`) which signal when a segment is deleted in consequence of `clean_consumed` set. Updates the DLQ writer to have a filesystem watch so that can receive the reader's signal and update the exposed metric loading the size by listing FS segments occupation.
Fixes the metric under `pipelines.<piepeline name>.dead_letter_queue.queue_size_in_bytes`
1. Create the `test_index` index in an ES cluster and [close …

Introduce filesystem signalling from DLQ read to writer to update byte size metric accordingly when the reader uses `clean_consumed`

---

logstash-core/build.gradle
logstash-core/lib/logstash/agent.rb
logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb
logstash-core/src/main/java/org/logstash/plugins/pipeline/AbstractPipelineBus.java
logstash-core/src/main/java/org/logstash/plugins/pipeline/AddressState.java
logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBusV1.java
logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBusV2.java
logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineInput.java
logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineOutput.java
logstash-core/src/test/java/org/logstash/plugins/pipeline/PipelineBusTest.java

- Improves the performance of pipeline-to-pipeline in some configurations where a single pipeline output sends to many downstream pipelines
Adds a currently opt-in implementation of the pipeline bus that eliminates synchronizing on the sending pipeline so that a pipeline with many workers that is sending to multiple downstream pipelines can better use the resources available to it.
It does so by:
1. Extracting an interface from the existing `PipelineBus` and renaming the current implementation to `PipelineBusV1`, along with a minor refactor to allow the implementation to make its internals queryable for tests
2. Extracting the bulk of the complexity for retries and event transmission to `AbstractPipelineBus#doSendEvents` so that `PipelineBusV1` could be solely focused on _routing_
3. Adds …

p2p: adds opt-in pipeline bus with less synchronization

---

x-pack/lib/filters/geoip/database_manager.rb
x-pack/spec/filters/geoip/database_manager_spec.rb

Resolves a regression from 8.12.0 in GeoIP Database Management in which a new instance of a Geoip Filter can be provided with a stale path for a database that no longer exists on disk, causing its pipeline to crash.
Updates the Geoip Filter's x-pack extension to properly invalidate its cached database path when receiving notifications of the database being updated or expired.
Prevents a situation where a pipeline containing a GeoIP filter cannot be reloaded until the process has been restarted.
- Resolves #16221

Geoip database management cache invalidation

---

logstash-core/spec/logstash/java_pipeline_spec.rb

[rn:skip] 
This a refactoring of test fixture.
Avoid mocking the value returned in global SETTINGS constant. Use instead the local setting map instance used in subject creation.
As a developer I want to leverage as less as possible mocking on objects that just carry values.
The spirit is mock behaviour not data.
-

[Test]Avoid mocking the value returned in global SETTINGS constant

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java

Bugfix, avoid to log file not found errors when DLQ segments are removed concurrently between writer and reader.
Rework the logic to delete DLQ eldest segments to be more resilient on file not found errors and avoid to log warn messages that hasn't any actionable job for the user to solve.
This commit reimplement the comparator used on DLQ reader side to identify the fully consumed segments when `clean_consumed` is enabled to avoid logging warn messages of file not found exception. That condition could manifest  when also the writer side deletes segments to satisfy the `drop_older` storage policy.
It also updates the `deleteSegment`method so that in case of removal of not existing file, no warning logs are emitted, being a condition that could happen during the execution.
This PR avoid to …

Avoid to log file not found errors when DLQ segments are removed concurrently between writer and reader.

---

logstash-core/lib/logstash/json.rb

- reduces overhead of serializing data to JSON slightly
Eliminates an unnecessary `Object#dup` and `Object#freeze` pair during JSON serialization, eliminating a very small amount of overhead. The method we are calling produces a mutated _copy_ when necessary already, and the resulting object does not need to be frozen because it is passed to a library that does not mutate its input.
Eliminates overhead
- Relates: #16702

json: remove unnecessary dup/freeze in serialization

---

.buildkite/benchmark_pipeline.yml
.buildkite/scripts/benchmark/config/filebeat.yml
.buildkite/scripts/benchmark/main.sh
.buildkite/scripts/benchmark/util.sh

Add a buildkite pipeline to do benchmark.
The script does benchmark by running Filebeats (docker) -> Logstash (docker) -> ES Cloud.
Logstash metrics and benchmark results are sent to the same ES Cloud.
- Secrets store in vault `secret/ci/elastic-logstash/benchmark`
- Use flog (docker) to generate ~2GB logs
- Pull the snapshot docker image of the main branch every day
- Logstash runs two pipelines, main and node_stats
- The main pipeline handles beats ingestion, sending data to the data stream `logs-generic-default`
- It runs for all combinations. (pq + mq) x worker x batch size
- Each test runs for ~7 minutes
- The node_stats pipeline retrieves /_node/stats API every 30s and sends it to the data stream `metrics-nodestats-logstash`
- The script sends a summary of EPS and resource usage to …

[CI] Benchmark pipeline

---

Gemfile.template
NOTICE.TXT
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/fileutils-NOTICE.txt

[rn:skip]
Pins the `fileutils` to 1.7+ version to apply the [file removal logic updates](https://github.com/ruby/fileutils/commit/ec5d3b84ea1e1d1b13c7dcb5bbe6cd5208c20a49).
Refer to the issue Logstash is facing: 
- https://github.com/logstash-plugins/logstash-integration-aws/issues/28
- https://github.com/ruby/fileutils/issues/111
The users who are on Windows OS and using `aws-integration` plugin S3 output feature, are having an issue that many temporary files are left that fileutil couldn't remove. With this change, temp dirs will be removed properly.
_Testing this behavior is very hard_. In order to reproduce, as I remember, I did run for 2-3 days to get following exception (see [the details](https://github.com/logstash-plugins/logstash-integration-aws/issues/28)):
```
An error occurred …
```

Pin fileutils version to 1.7+

---

bin/pqcheck.bat

There was a tiny oversight in the Windows batch file, resulting in the `pqcheck.bat` file not working when Logstash is installed in a path with a space. 
This PR fixes an issue that was preventing the `pqcheck.bat` file from running if it's in a path with a space, for example: `C:\Program Files\logstash-8.8.2`

Adding quotes in pqcheck.bat to support spaces in path

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/spec/logstash/java_pipeline_spec.rb

Fixed the configuration reload process to clean up the pipeline's metric store, so it does not retain references to failed pipelines components.
Ensure the pipeline's metrics are cleaned on the shutdown, so failed config reloads does not leak metrics from old pipeline reloads attempts.
Those stale metrics are consuming memory and are being returned on the stats API, causing confusion and huge payloads.
- Closes: https://github.com/elastic/logstash/issues/16202

Ensure pipeline metrics are cleared on the shutdown

---

.buildkite/aarch64_pipeline.yml

Add retries in the aarch64 CI pipeline
to reduce noise from transient network failures.
Example failure: https://buildkite.com/elastic/logstash-aarch64-pipeline/builds/143#01906c06-a2a0-4c18-b6c6-7ff7c2e979fc/120-5006
BK Link: https://buildkite.com/elastic/logstash-aarch64-pipeline/builds/146
Closes https://github.com/elastic/ingest-dev/issues/3510

Add retries to aarch64 CI pipeline

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/common/vm-images.json
.buildkite/scripts/exhaustive-tests/generate-steps.py

This reverts commit a0bcd61ad3d164b5928f073ee28cd1c7656db44e.
We're clearly still missing something to have ubuntu 24.04 testable on buildkite

Revert "add ubuntu 24.04 to CI (#16263)"

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/common/vm-images.json
.buildkite/scripts/exhaustive-tests/generate-steps.py
logstash-core/logstash-core.gemspec
rakelib/artifacts.rake
rubyUtils.gradle
versions.yml

https://www.jruby.org/2024/07/02/jruby-9-4-8-0.html
> Fixed a bug in the bytecode JIT causing patterns to execute incorrect branches. #8283, #8284
> jruby-openssl is updated to 0.15.0, with updated Bouncy Castle libraries to avoid CVEs in older versions.
> uri is updated to 0.12.2, mitigating CVE
> net-ftp is updated to 0.3.7 with restored functionality on JRuby.
Exhaustive test suite: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/580

update jruby to 9.4.8.0

---

Gemfile.template
docker/Makefile
docker/bin/pytest
docker/requirements.txt
docker/templates/Dockerfile.erb
docker/templates/hardening_manifest.yaml.erb
docker/tox.ini

This should simplify CI infrastructure by not requiring python.
Exhaustive test suite with docker acceptance tests passing here: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/576

move j2 template to erb in 7.17

---

Gemfile.jruby-3.1.lock.release
versions.yml

To be merged immediately following the release of 8.14.2

Bump 8.14.3

---

.buildkite/linux_jdk_matrix_pipeline.yml

[rn:skip]
CentOS 7 is EOL since June 30 2024[^1]. All repositories and mirrors are now unreachable.
This commit removes CentOS 7 from CI jobs using it.
BK link: https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/235
https://github.com/elastic/ingest-dev/issues/3520
[^1]: https://www.redhat.com/en/topics/linux/centos-linux-eol

Remove CentOS 7 from CI

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/common/vm-images.json
.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
Now that we have custom VM images for Ubuntu 24.04, this commit adds CI for Ubuntu 24.04.
This is a revert of #16279
BK Link:
- exhaustive job: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/605
- jdk matrix job: https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/236
Unfortunately some steps in the above jobs fail as there is no 8.16.0 Elasticsearch artifact yet.

Add Ubuntu 24.04 to CI

---

.buildkite/scripts/benchmark/main.sh

Fixes: #16307
benchmark script [fails](https://buildkite.com/elastic/logstash-benchmark-pipeline/builds/66#0190909c-074f-45f4-93bf-21654e6886e5) because it takes the version 8.15.0 rather than 8.15.0-SNAPSHOT, hence, unable to download the nightly build image

[CI] fix benchmark to pull snapshot version 

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/common/vm-images.json
.buildkite/scripts/exhaustive-tests/generate-steps.py

**Backport PR #16300 to 7.17 branch, original message:**
---
[rn:skip]
This commit removes Debian 10 (Buster) which is EOL since July 1 2024[^1] from CI.
Relates https://github.com/elastic/ingest-dev/issues/2872
[^1]: https://wiki.debian.org/LTS

Backport PR #16300 to 7.17: Remove Debian 10 from CI (#16300)

---

.buildkite/linux_jdk_matrix_pipeline.yml
.buildkite/scripts/common/vm-images.json
.buildkite/scripts/exhaustive-tests/generate-steps.py

**Backport PR #16300 to 8.14 branch, original message:**
---
[rn:skip]
This commit removes Debian 10 (Buster) which is EOL since July 1 2024[^1] from CI.
Relates https://github.com/elastic/ingest-dev/issues/2872
[^1]: https://wiki.debian.org/LTS

Backport PR #16300 to 8.14: Remove Debian 10 from CI (#16300)

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

A couple of thoughts on the way this is implemented:
1. There should be a first barrier to handle pipelines that are too large based on the PipelineIR compilation. The barrier would use the detection of Xss to determine how big a pipeline could be. This however doesn't reduce the need to still handle a StackOverflow if it happens.
2. The catching of StackOverflowError could also be done on the WorkerLoop. However I'd suggest that this is unrelated to the Worker initialization itself, it just so happens that `compiledPipeline.buildExecution` is computed inside the WorkerLoop class for performance reasons. So I'd prefer logging to not come from [the existing `catch`](https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/java_pipeline.rb#L601-L606), but from a dedicated …

make pipeline resilient to stack overflow during compilation

---

logstash-core/lib/logstash/settings.rb
logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
logstash-core/spec/logstash/settings_spec.rb

Because logging configuration occurs after loading the `logstash.yml` settings, deprecation logs from `LogStash::Settings::DeprecatedAlias#set` are effectively emitted to a null logger and lost.
By re-emitting these deprecations after the post-process hooks, we can ensure that they make their way to the deprecation log. This change adds support for any setting that responds to `Object#observe_post_process` to receive it after all post-processing hooks have been executed.
Fixes an issue where the deprecation log does not contain entries related to providing deprecated settings by ensuring that they are re-emitted after the logger has been configured.
Fixes an issue where the deprecation log does not contain entries related to providing deprecated settings by ensuring that they are …

settings: add support for observing settings after post-process hooks

---

x-pack/qa/integration/support/helpers.rb

Before we waited for the condition /license.*valid/, that matched:
```
[2024-07-24T15:03:23,157][INFO ][o.e.l.ClusterStateLicenseService] [arkham.local] license [8a5c66ef-1863-4d24-845a-339d8ad755a5] mode [basic] - valid
```
But now it can match:
```
[2024-07-24T15:03:16,331][INFO ][o.e.f.FeatureService     ] [arkham.local] Registered local node features [data_stream.auto_sharding, data_stream.lifecycle.global_retention, data_stream.rollover.lazy, desired_node.version_deprecated, esql.agg_values, esql.async_query, esql.base64_decode_encode, esql.casting_operator, esql.counter_types, esql.disable_nullable_opts, esql.from_options, esql.metadata_fields, esql.metrics_counter_fields, esql.metrics_syntax, esql.mv_ordering_sorted_ascending, esql.mv_sort, esql.resolve_fields_api, …
```

fix line used to determine ES is up

---

.buildkite/snyk_report_pipeline.yml

Sometimes network instability can cause the build to fail. for example:
```
HEAD is now at 5b13f973d bump lock file for 7.17 (#16341)
--
  | Checking out 8.14 branch.
  | Branch '8.14' set up to track remote branch '8.14' from 'origin'.
  | Switched to a new branch '8.14'
  | Downloading https://services.gradle.org/distributions/gradle-8.5-bin.zip
  | ............10%.............20%............30%.............40%.....
  | Exception in thread "main" java.net.SocketException: Connection reset
  | at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328)
  | at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
  | at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
  | at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
```

add retries to snyk buildkite job

---

logstash-core/lib/logstash/util/substitution_variables.rb
qa/docker/shared_examples/xpack.rb

A bug (introduced in 8.13.1) fix to use array value with docker environment variables (such as `XPACK_MANAGEMENT_PIPELINE_ID`, `XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS`).
Fixes the bug introduced by #16026. After 8.13.1, running Logstash on docker with list environment variable (example: `-e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS='[es.host.1, es.host.2:9500]'`) doesn't work. Current change fixes this issue.
- run `rake artifact:docker` to build docker image
- use the hash value created by rake and replace `b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874` with your hash value
- ENV var carries list:
```
docker run --rm --name=local-ls-docker -p 9600:9600 -e API_ENABLED=true -e XPACK_MANAGEMENT_ENABLED=true -e XPACK_MANAGEMENT_PIPELINE_ID="['*']" -e …
```

[Bugfix] Resolve the array and char (single | double quote) escaped values of ${ENV}

---

logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/src/main/java/org/logstash/util/JavaVersion.java

In a future major release of Logstash, Java 11 will not be supported. While most distributions of Logstash bundle a supported Java 17+, we now emit a deprecation warning for users who provide an outdated JDK of their own, guiding to either use the bundled JDK or to provide an updated one.
Emits a deprecation warning at startup if-and-only-if Logstash is being run on Java < 17, so that users who provide a JDK that will not be supported in the near-to-medium future can address the issue separately from upgrading Logstash.
Nobody likes being surprised by breaking changes :)
- ~~[ ] I have added tests that prove my fix is …

deprecate java less-than 17

---

logstash-core/lib/logstash/config/mixin.rb
logstash-core/lib/logstash/settings.rb
logstash-core/lib/logstash/util/substitution_variables.rb
qa/integration/specs/multiple_pipeline_spec.rb

Continues a work of https://github.com/elastic/logstash/pull/16365 which fixed the bug of using array value with docker environment variables (such as `XPACK_MANAGEMENT_PIPELINE_ID`, `XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS`). However, if `config.string` contains ${VAR}s substituted its origin value, refinement logic cleans up the quotes used on configs, for example `output { elasticsearch { hosts => "my.host:9200"} }`, `my.host:9200` loses double quotes.
With this PR, we are excluding `pipelines.yml` and only applying refinement on ENV ${VAR}s.
Users who are using `config.string` should have a consistent user experience.
- Pull the PR
- Use `config.string` in `pipelines.yml` with containing ${VAR} and es-output with hosts option.
- Without this change, pipeline start fails
- With this …

Exclude substitution refinement on pipelines.yml

---

.buildkite/scripts/dra/common.sh

Increase Jruby -Xmx to avoid OOM during zip task in DRA
Fix: https://github.com/elastic/logstash/issues/16406

[CI] Increase Jruby -Xmx for DRA

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/ClassFields.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/FieldDefinition.java

[rn:skip]
Updates `FieldDefinition` to receive the name of the field from construction methods, so that it can be used during the code generation phase, instead of the existing incremental `field%n`.   
Updates `ClassFields` to propagate the explicit field name down to the `FieldDefinition`s.
Update the `DatasetCompiler` that add fields to `ClassFields` to assign a proper name to  generated Dataset's fields.
This PR is intended to help Logstash developers or users that want to better understand the code that's autogenerated to model a pipeline, assigning more meaningful names to the fields.
- ~~[ ] I have added tests …

Generate Dataset code with meaningful fields names

---

rakelib/z_rubycheck.rake

This allows the environment variable JRUBY_OPTS to be used for setting properties like Xmx
Fixes https://github.com/elastic/logstash/issues/16406

Update z_rubycheck.rake to no longer inject Xmx1g

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/ConditionalEvaluationError.java

[rn:skip]
Make inner field of `ConditionalEvaluationError` transient to be avoided during serialization.
Fix ConditionalEvaluationError to do not include the event that errored in its serialiaxed form, because it's not expected that this class is ever serialized.
Sets your default JDK to a 21 version and run
```
./gradlew clean assemble
```
- 
```
andrea:logstash_andsel (main) % ./gradlew clean assemble
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to …
```

Exclude inner event field from ConditionalEvaluationError serialization

---

Gemfile.template
rakelib/artifacts.rake

Using VERSION_QUALIFIER when building the tarball will fail since Ruby's TarWriter implements the older POSIX88 version of tar.
For the long paths being used in Logstash's plugins, mainly due to nested folders from jar-dependencies, we need the tarball to follow either the 2001 ustar format or gnu tar, which is implemented by the minitar gem.
To test, run: `VERSION_QUALIFIER=beta1 ./gradlew assembleTarDistribution`, which will fail on main but work on this PR
Kicked off exhaustive test suite: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/726

use gnu tar compatible minitar to generate tar artifact

---

.buildkite/scripts/dra/publish.sh

The current DRA publishing task computes the branch from the version contained in the version.yml
This is done by taking the major.minor and confirming that a branch exists with that name.
However this pattern won't be applicable for 8.x, as that branch currently points to 8.16.0 and there is no 8.16 branch.
The problem was that, when DRA was run for 8.x branch, the branch lookup would fail and default to "main", overriding the "main" branch dra builds.
This commit fixes the issue by falling back to reading the buildkite injected BUILDKITE_BRANCH variable instead of immediately defaulting to "main" if there's no branch match.

account for the 8.x branch in DRA publishing task

---

docs/static/releasenotes.asciidoc

DOC/RN Change
**PREVIEW:** https://logstash_bk_16455.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-8-15-1.html
Adds a known issue section to 8.15.1 referring to https://github.com/elastic/logstash/issues/16437
IT might be useful to link the issue itself https://github.com/elastic/logstash/issues/16437

Known issue for 8.15.1 related to env vars references

---

.buildkite/scripts/benchmark/marathon.sh

QTYPE is set to "memory" after doing the benchmark of the first version. This commit preserves the original QTYPE

[CI] fix wrong queue type in benchmark marathon

---

.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
BK Agent recently added a jruby-9.4.8.0 support and we need to use this version in the CI pipelines. This change adds a change to reflect into exhaustive pipeline.
N.A
-

Use jruby-9.4.8.0 in exhaustive CIs.

---

docs/static/dead-letter-queues.asciidoc
logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java

When a conditional evaluation encounter an error in the expression the event that triggered the issue is sent to pipeline's DLQ, if enabled for the executing pipeline.
This PR engage with the work done in #16322, the `ConditionalEvaluationListener` that is receives notifications about if-statements evaluation failure, is improved to also send the event to DLQ (if enabled in the pipeline) and not just logging it.
Let the user that encounter errors in the evaluation of conditional statements to enqueue in DLQ for a subsequent processing.
Use a pipeline that would trigger an error in conditional evaluation, like:
```
input {
generator {
message => '{"path":{"to":{"value": 101}}}'
codec …
```

DLQ-ing events that trigger an conditional evaluation error.

---

logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
logstash-core/src/main/java/org/logstash/settings/BaseSetting.java
logstash-core/src/main/java/org/logstash/settings/Coercible.java
logstash-core/src/main/java/org/logstash/settings/SettingWithDeprecatedAlias.java

[rn:skip] 
Suppress some warnings compared with JDK 21
- `this-escape` uses this before it is completely initialised.
- avoid a non serialisable `DeadLetterQueueWriter` field from serialisable instance.
**Don't need backports**
It's the forward port of a 2 fixes added in already present backports:
- #16490
- #16493

Fix jdk21 warnings

---

.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
A recent PR (elastic/ci-agent-images/pull/932) modernized the VM images and removed JRuby 9.4.5.0 and some older versions.
This ended up breaking exhaustive test on Oracle Linux 7 that hard coded JRuby 9.4.5.0.
PR https://github.com/elastic/logstash/pull/16489 worked around the problem by pinning to the new JRuby, but actually we don't need the conditional anymore since the original issue https://github.com/jruby/jruby/issues/7579#issuecomment-1425885324 has been resolved and none of our releasable branches (apart from 7.17 which uses `9.2.20.1`) specify `9.3.x.y` in `/.ruby-version`.
Therefore, this commit removes conditional setting of JRuby for OracleLinux 7 agents in exhaustive tests (and relies on whatever `/.ruby-version` defines).
Removes tech debt and simplifies the CI …

Don't use an older JRuby with oraclelinux-7

---

.buildkite/pull_request_pipeline.yml
.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
This commit pins the CI container images to the older version to fix failures like https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/760
This problem started happening after https://github.com/elastic/ci-agent-images/pull/932 where CI images got updated to Java 21 which breaks CI for the 7.17 branch.
https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/767

Pin CI container images to v0.4 for 7.17 branch

---

catalog-info.yaml

[rn:skip]
With this commit we shush slack alerts for JDK matrix CI jobs that succeed after (automatic) retries.
Reduces notification fatigue for non-actionable events.

[ci] Skip slack for retries JDK matrix jobs

---

logstash-core/lib/logstash/settings.rb
logstash-core/spec/logstash/settings_spec.rb

[rn:skip]
Update Settings to_hash method to also skip Java DeprecatedAlias and not just the Ruby one.
With PR #15679 was introduced `org.logstash.settings.DeprecatedAlias` which mirrors the behaviour of Ruby class `Setting::DeprecatedAlias`. The equality check at `Logstash::Settings`, as descibed in #https://github.com/elastic/logstash/issues/16505#issuecomment-2391679610, is implemented comparing the maps.
The conversion of `Settings` to the corresponding maps filtered out the Ruby implementation of DeprecatedAlias but not the Java one.
This PR adds also the Java one to the list of filter.
When the user run Logstash using `pipelines.yml` and enable autoreloading, avoid to continuously log a warn message that's unrelated to the context of configuration change checking.
- ~~[ ] I have …

Avoid to access Java DeprecatedAlias value other than Ruby's one

---

logstash-core/lib/logstash/patches/clamp.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/runner_spec.rb

The flag `--event_api.tags.illegal` is deprecated and will be removed in version 9. This flag remains available throughout all version 8.x releases. Users who rely on this flag to allow non strings assignment to `tags` field should update their pipeline.
- move `--event_api.tags.illegal` from option to deprecated_option
- add deprecation log when the flag is explicitly used.
- run `bin/logstash -e "input { stdin {} } output { stdout {} }" --event_api.tags.illegal warn`
- logstash-deprecation.log should show related log
- relates: #16461
- relates: https://github.com/elastic/logstash/issues/16356

add deprecation log for `--event_api.tags.illegal`

---

qa/Gemfile
qa/docker/spec/spec_helper.rb

[rn:skip]
Addresses two issues:
1. Rspec 3.1.7 cannot properly transform the errors happened while testing. Upgrades rspec dependency of the QA package to resolve the issue;
2. Node stats API status now reflects Health report. One test case was failing due to the change, fixes it.
No impact to end users.
- 
- Before change: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/795#019272ae-7194-4467-91ae-d07708d6e85b/6424-7571
- After the change: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/796#019272e9-3f2d-43c6-af5e-e6cc0a2793c2

Fix QA failure introduced by Health API changes and update rspec dependency of the QA package.

---

.buildkite/health_report_tests_pipeline.yml
.buildkite/scripts/health-report-tests/bootstrap.py
.buildkite/scripts/health-report-tests/main.sh
.buildkite/scripts/health-report-tests/util.py
qa/docker/shared_examples/container.rb

[rn:skip]
- After delivering https://github.com/elastic/logstash/pull/16520 Health API, CI didn't run with reason of either python or Java missed. This PR uses Ubuntu BK Agent and manually installs the pip module.
- Fixes the flaky test sometimes failing after status reflected into node stats API.
- Cannot manually test, so run the https://buildkite.com/elastic/logstash-health-report-tests-pipeline by merging this PR.
-

Health api minor followups

---

logstash-core/src/main/java/org/logstash/health/HealthObserver.java
logstash-core/src/test/java/org/logstash/health/HealthObserverTest.java

- Adds an escape hatch to prevent the new health API's status from affecting the status field of other API responses; by setting the `logstash.forceApiStatus` system property to `green`, you can force the other APIs to continue to use hard-coded green value.
Observes a new system property `logstash.forceApiStatus`, and avoids propagating the detected health status if the user sets the property value to `green`.
Because external tooling may rely on the previously-hard-coded `green` status in Logstash API responses, we add a way to force API responses to continue using the hard-coded `green` instead of propagating the actual health status.
1. Add the following to your `config/jvm.options`:
~~~
-Dlogstash.forceApiStatus=green
~~~
2. Start Logstash with a pipeline that will take a while to …

health: add `logstash.forceApiStatus: green` escape hatch

---

logstash-core/lib/logstash/patches/clamp.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/runner_spec.rb

[rn:skip]
Use `obsoleted_version` to replace `deprecated_msg` to form a consistent warning message
Make the warning consistent with other flags
- relates: https://github.com/elastic/logstash/issues/16356
- relates: https://github.com/elastic/logstash/pull/16507

refactor deprecation log event_api.tags.illegal

---

docs/static/releasenotes.asciidoc

Now that `main`=`9.0`, the 8.x series release notes will be replaced with 9.x series release notes.  In the meantime, modifying or deleting section anchors for `main` can cause broken links when the referenced section can't be found. 
This PR is a workaround until we remove 8.x series release notes. 
/No backports needed

Doc: Update 8.15.0 release notes to future proof link

---

config/logstash.yml
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/runner.rb

Logs a deprecation warning if users doesn't explicitly select a value a for `pipeline.buffer.type` and resort to the default setting.
On 8.x series log a deprecation log if the user didn't explicitly specify a selection for  `pipeline.buffer.type`. Before this change the default was silently set to `direct`, after this change if not explicitly defined, the default is still `direct` but log a deprecation log.
A user which uses the default value for `pipeline.buffer.type` is nudged to take an explicit selection of the flag, because in the next major this setting will switch to `heap` by default and the JVM `Xmx` has to be properly adjusted to avoid  OutOfMemory errors.
- ~~[ ] I have …

Log deprecation warn if memory buffer type not defined

---

.buildkite/scripts/health-report-tests/bootstrap.py
.buildkite/scripts/health-report-tests/config_validator.py
.buildkite/scripts/health-report-tests/main.py
.buildkite/scripts/health-report-tests/scenario_executor.py
.buildkite/scripts/health-report-tests/tests/abnormal-termination.yaml
.buildkite/scripts/health-report-tests/tests/backpressure-1m.yaml
.buildkite/scripts/health-report-tests/tests/backpressure-5m.yaml
.buildkite/scripts/health-report-tests/tests/multipipeline.yaml
.buildkite/scripts/health-report-tests/tests/normal-termination.yaml
.buildkite/scripts/health-report-tests/tests/slow-start.yaml

[rn:skip]
Adds 1min, 5min and multi-pipeline integration tests for the health API
- Validates further iteration changes.
- No impact for end users.
- Follow the `.buildkite/scripts/health-report-tests/README.md`
- CI test with this PR: https://buildkite.com/elastic/logstash-health-report-tests-pipeline/builds/58
- Continues https://github.com/elastic/ingest-dev/issues/3926

[Health API] Add 1-min, 5-min backpressure and multipipeline test cases.

---

logstash-core/lib/logstash/config/modules_common.rb
x-pack/modules/arcsight/configuration/logstash/arcsight.conf.erb

Add deprecation log when ArcSight module is used.
Logs a deprecation when Logstash 8.x is started with ArsSight module.
The module will be removed in a future version, this is a warning that user should consider.
- test when module is enabled on command line:
```sh
bin/logstash --module arcsight
```
- test when the module is configured in `config/logstash.yml`:
```yaml
modules:
- name: arcsight
var.elasticsearch.hosts: "http://localhost:9200"
var.elasticsearch.api_key: "secret key"
var.kibana.host: "http://localhost:5601"
var.kibana.username: "elastic" …
```

Deprecate for removal ArcSight module

---

Gemfile.template
logstash-core/logstash-core.gemspec

Logstash now expects minitar to be 1.x since https://github.com/elastic/logstash/pull/16432, but the dependency wasn't constrained correctly in the Gemfile or logstash-core.gemspec.
This fixes the issue by pinning to "~> 1"

ensure minitar 1.x is used instead of 0.x

---

logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtTest.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithDelimiterTest.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java

[rn:skip] 
Updates `BufferedTokenizerExt` so that can accumulate token fragments coming from different data segments. When a "buffer full" condition is matched, it record this state in a local field so that on next data segment it can consume all the token fragments till the next token delimiter.
Updated the accumulation variable from `RubyArray` containing strings to a StringBuilder which contains the head token, plus the remaining token fragments are stored in the `input` array.
Port the tests present at https://github.com/elastic/logstash/blob/f35e10d79251b4ce3a5a0aa0fbb43c2e96205ba1/logstash-core/spec/logstash/util/buftok_spec.rb#L20 in Java. 
Fixes the behaviour of the tokenizer to be able to work properly when buffer full conditions are met.
- ~~[ ] I have made corresponding changes …

Bugfix for BufferedTokenizer to completely consume lines in case of lines bigger then sizeLimit

---

logstash-core/benchmarks/build.gradle
logstash-core/benchmarks/src/main/java/org/logstash/benchmark/BufferedTokenizerExtBenchmark.java

[rn:skip]
Adds a JMH benchmark to measure the peformances of `BufferedTokenizerExt`.
Update also Gradle build script to remove CMS GC flags and fix deprecations for  Gradle 9.0.
As a developer I want to have benchmark measure of `BufferedTokenizerExt`.
Run with:
```sh
./gradlew jmh -Pinclude="org.logstash.benchmark.BufferedTokenizerExtBenchmark.*"
```

Adds a JMH benchmark to test BufferedTokenizerExt class

---

logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtTest.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithDelimiterTest.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java

**Non clean backport** of #16482 
The differences are:
- usage of `data.convertToString().split(context, delimiter, MINUS_ONE);` instead of `data.convertToString().split(delimiter, -1);`
- avoid to extend BuffererdTokenir test cases from `org.logstash.RubyTestBase` which was introduced in #13159
- JDK 8 compatibilities:
- `Arrays.asList` vs `List.of`
- `assertThrows` method from JUnit5 not available in JUnit4 so reimplemented in the test
----
Fixes the behaviour of the tokenizer to be able to work properly when buffer full conditions are met.
Updates BufferedTokenizerExt so that can accumulate token fragments coming from different data segments. When a "buffer full" condition is matched, it record this state in a local field so that on next data segment it can consume all the token …

Backport #16482 to 7.17: Bugfix for BufferedTokenizer to completely consume lines in case of lines bigger then sizeLimit 

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline_resource_usage_validator.rb
logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/spec/logstash/pipeline_resource_usage_validator_spec.rb

```yml            
- pipeline.id: test_01
config.string: "input { heartbeat {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
- pipeline.id: test_02
config.string: "input { heartbeat {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
- pipeline.id: test_03
config.string: "input { heartbeat {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
```
```
~/elastic/logstash improve_max_inflight_warning ❯ bin/logstash -r -b 125 --debug | grep resource                 
[2024-10-24T11:44:44,941][DEBUG][logstash.pipelineresourceusagevalidator] For a baseline of 2KB events, the maximum heap memory consumed across 3 pipelines may reach up to 0.72% of the entire heap (more if the events are bigger).
```
```
~/elastic/logstash …
```

make max inflight warning global to all pipelines

---

.buildkite/jdk_availability_check_pipeline.yml
catalog-info.yaml

[rn:skip]
Switch execution agent of JDK availability check pipeline from vm-agent to container-agent.
Moves the schedule definition from the `Logstash Pipeline Scheduler` pipeline into the pipeline definition, adding a schedule also for `8.x` branch.

[CI] Change agent for JDK availability check and add schedule also for 8.x

---

.buildkite/pull_request_pipeline.yml
docs/static/settings-file.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/runner.rb
logstash-core/spec/logstash/runner_spec.rb

Running as superuser is disabled by default.  To continue running Logstash as superuser temporarily after the upgrade, set 'allow_superuser' to true.
- set allow_superuser as false by default for v9
- change the buildkite image of ruby unit test to non-root
- relates: https://github.com/elastic/logstash/issues/16355
-

set `allow_superuser` to false as default

---

ci/acceptance_tests.sh
ci/docker_acceptance_tests.sh
docker/Makefile

both gradle and docker build use outputs that are not CI friendly.
These default tty optimized outputs lead to many MB outputs in CI jobs, so a suggestion is to make some of these "plain" instead, where the information is still shown but won't clob CI job outputs.

make docker build and gradle tasks more friendly towards ci output

---

rakelib/artifacts.rake

there's no need to build jdk-less and windows tarballs for docker images so this change simplifies the build process.
It should reduce the time spent needed to build docker images.

reduce effort during build of docker images

---

qa/acceptance/spec/shared_examples/cli/logstash-plugin/generate.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/integration_plugin.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb
qa/rspec/commands.rb
qa/rspec/commands/base.rb

Acceptance tests run install, uninstall and other commands as root. Starting from v9 #16558, `allow_superuser` is default to `false`, hence the existing tests fail.
This commit fixes the acceptance tests to run logstash as non-root
red acceptance test: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/869
green acceptance test: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/875
window unit test is still failing

[CI] Fix acceptance test permission issue

---

bin/setup.bat

Running logstash from source code in Windows, the log points user to setup JAVA_HOME, which should be LS_JAVA_HOME since v8
Log
```
$ bin\logstash
"Using system java: "C:\Program Files\Common Files\Oracle\Java\javapath\java.exe""
The system cannot find the path specified.
could not find java; set JAVA_HOME or ensure java is in PATH
```
Fix: https://github.com/elastic/logstash/issues/16596

fix Windows java not found log

---

rubyUtils.gradle
versions.yml

the .ruby-version will be upgraded once the ci images are upgraded as well
[edit] exhaustive test run: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/892

bump jruby to 9.4.9.0

---

lib/pluginmanager/pack_installer/pack.rb
spec/unit/plugin_manager/pack_installer/pack_spec.rb

Fix offline plugin install of java plugins that contain`-java` in the name.
Anchor the `-java` match pattern at the end of the string.  This fixes the offline install problem of the logstash-input-java_filter_example plugin.
If a user uses the example Java plugins, for example the [logstash-input-java_filter_example](https://github.com/logstash-plugins/logstash-filter-java_filter_example), to demo or test a custom off-line package install, it will fail.
The process is to reproduce the bug is: 
1. Clone, build, and install custom plugin as documented at [How to write a Java filter plugin](https://www.elastic.co/guide/en/logstash/current/java-filter-plugin.html)
2. Pack the plugin for off-line install as documented at [Offline Plugin …

Anchor the `-java` match pattern at the end of the string

---

config/logstash.yml
logstash-core/lib/logstash/runner.rb
logstash-core/spec/logstash/runner_spec.rb

[rn:skip]
As Process.euid() is always zero in Windows,
this commit excluded the checking of running as root in Windows.
- relates: https://github.com/elastic/logstash/pull/14089 , https://github.com/elastic/logstash/pull/16558

skip `allow_superuser` in Windows OS

---

logstash-core/lib/logstash/config/modules_common.rb
x-pack/modules/arcsight/configuration/logstash/arcsight.conf.erb

[rn:skip]
Updates the deprecation log for ArcSight module to notify it's removed in version 9, like in netflow, fb_apache and azure
Follow the same description in #16551
- Relates #16551 
- - Relates #16548
```
[2024-11-06T09:37:06,453][WARN ][deprecation.logstash.config.modulescommon] The arcsight module has been deprecated and will be removed in version 9.
```

Update deprecation warning to provide the version the ArcSight modue is removed.

---

logstash-core/lib/logstash/config/modules_common.rb
x-pack/modules/arcsight/configuration/logstash/arcsight.conf.erb

Non clean backport of #16648 to `8.16` branch.
----
[rn:skip]
Updates the deprecation log for ArcSight module to notify it's removed in version 9, like in netflow, fb_apache and azure
Follow the same description in #16551
- Relates #16551 
- - Relates #16548
```
[2024-11-06T09:37:06,453][WARN ][deprecation.logstash.config.modulescommon] The arcsight module has been deprecated and will be removed in version 9.
```

[Backport 8.16] Update deprecation warning to provide the version the ArcSight modue is removed (#16648)

---

docs/static/releasenotes.asciidoc

[rn: skip]
Adds release notes for the #16657 known issue in v2 of the pipeline bus which can prevent shutdown.

Add known issue for PipelineBusv2 to 8.15.x release notes

---

docs/static/releasenotes.asciidoc

[rn: skip] (it'd be too self-referential)
Workaround documented in #16661 should reference `config/jvm.options`, not `config/jvm.properties` :facepalm:
Give them a _useful_ workaround for a known issue.

Fix: 8.15 release notes workaround ref to set system property

---

config/logstash.yml
docs/static/config-details.asciidoc
docs/static/settings-file.asciidoc
logstash-core/lib/logstash/environment.rb
x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb

Switch the default value of `pipeline.buffer.type` to use the heap memory instead of direct one.
Change the default value of the setting `pipeline.buffer.type` from `direct` to `heap` and update consequently the documentation.
It's part of the work to make more explicit the usage of memory used by Netty based plugins. Using heap instead of direct for Netty buffers, make easier the debug of memory issues at the cost of bigger heap size.
- Relates #16353 
As a developer of Netty based plugin I want to have better insight in memory usage patterns.

Default buffer type to 'heap' for 9.0

---

docs/static/releasenotes.asciidoc

Updates release notes for 8.14.x to call for an update to a subsequent minor for fix performance regression in JSON decoding.

Updates release notes for 8.14.x to call for an update.

---

logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBusV2.java
logstash-core/src/test/java/org/logstash/plugins/pipeline/PipelineBusTest.java

- Fixes an issue where Logstash shutdown could stall in some cases when using pipeline-to-pipeline.
- Adds tests to detect deadlock betweeen `PipelineBus#unlisten` and `PipelineBus#unregisterSender`
- Eliminates a deadlock that can occur in `PipelineBusV2`
Failing to shut down is not good.
- Resolves #16657

PipelineBusV2 deadlock proofing

---

tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/logger-NOTICE.txt

[rn:skip]
A new transative dependency on the `logger` gem has been added. Update the license checker to ensure this is accounted for.
This should have no direct impact to the user other than ensuring all licenses are transparent for vendored code. 
WIthout this patch the command (show successfull after this patch) will fail:
```
➜  logstash git:(update-license-for-logger) ✗ ./bin/dependencies-report --csv report.csv
Using system java: …
```

Update license checker with new dependency

---

docker/data/logstash/env2yaml/env2yaml.go

[rn:skip]
In https://github.com/elastic/logstash/pull/16586 the module include was removed. This causes failures in the script when the module is referenced. This commit re-enables the include for the yaml module.
~~- [ ] My code follows the style guidelines of this project~~
Example failed test: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/949#01934968-b66c-4455-ad70-1778cc13def3

Replace removed yaml module

---

.buildkite/scripts/health-report-tests/main.sh
catalog-info.yaml

[rn:skip]
Fixes the CI hang caused by installing pip. This change aligns on python installed on BK agent.
Health API E2E run: https://buildkite.com/elastic/logstash-health-report-tests-pipeline/builds/99
No impact.
- It cannot be tested locally since it is an agent specific.
- 
```
buildkite-agent@mst-logstash-ubuntu-2204:~/logstash$ ./gradlew clean bootstrap assemble installDefaultGems
Downloading https://services.gradle.org/distributions/gradle-8.7-bin.zip …
```

[Health API E2E] Align on agent python version and avoid pip install.

---

docs/static/breaking-changes-60.asciidoc
docs/static/breaking-changes-pre63.asciidoc
docs/static/breaking-changes.asciidoc

Related: #16613
Move the pre-6.3 PQ issue under 6.0-series breaking changes for consistency and ease of use. 
**PREVIEW:** https://logstash_bk_16706.docs-preview.app.elstc.co/guide/en/logstash/master/breaking-6.0.html

Doc: Roll 6.3 breaking changes under 6.0 series

---

.github/workflows/add-docs-preview-link.yml

Update the timeout from 15 minutes to 30 minutes to try and fix the inline docs previews feature

Increase timeout for docs PR link action

---

docs/static/troubleshoot/ts-logstash.asciidoc

**PREVIEW:** https://logstash_bk_16721.docs-preview.app.elstc.co/guide/en/logstash/master/ts-logstash.html
[rn:skip]
Adds troubleshooting item for when cgroup v2 is not enabled
Document an issue that has been encountered by mulitple users.
Docs-only
n/a
n/a
n/a
n/a

Docs: Troubleshooting update

---

logstash-core/logstash-core.gemspec

Pin jar-dependencies to `0.4.1`, until https://github.com/jruby/jruby/issues/7262 is resolved.

Pin `jar-dependencies` to `0.4.1`

---

logstash-core/logstash-core.gemspec

Backport PR #16747 to 7.17 branch, original message:
Pin jar-dependencies to 0.4.1, until jruby/jruby#7262 is resolved.
This was not a clean backport. `jar-dependencies` version verified against version of jruby shipped with `7.17`
https://github.com/jruby/jruby/blob/9.2.20.1/pom.rb#L82

Backport PR #16747 to 7.17: Pin jar-dependencies to 0.4.1

---

docs/static/ls-ls-lumberjack.asciidoc
docsk8s/quick-start/sample-configuration-files.asciidoc
docsk8s/setting-up/ls-k8s-secure.asciidoc
qa/integration/fixtures/beats_input_spec.yml

[rn:skip]
Recently, some of SSL params of beats-input obsoleted. We need update usage of those params which this PR does.
N.A
-

Update usage of beats-input obsoleted SSL params in the core.

---

Gemfile.template

A number of plugins include breaking changes in 9.x, which, without restriction, will be included in development `8.x` branches that do not include a lockfile.
This commit adds these to the Gemfile.template to avoid being introduced in 8.x development branches

Pin plugins that incorporate breaking changes in 9.0

---

logstash-core/spec/logstash/util/buftok_spec.rb
logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java

The BufferedTokenizer.flush must reset the inputSize value back to zero on flush, otherwise it will grow until a buffer full exception is thrown if the buffer has a size limit.
We can see the test fails if the `inputSize = 0` is not present:
```
❯ bin/rspec logstash-core/spec/logstash/util/buftok_spec.rb -fd -e flush
[...]
FileWatch::BufferedTokenizer
flush
emits the contents of the buffer
resets the state of the buffer
with decode_size_limit_bytes
resets the state of the buffer (FAILED - 1)
emits the contents of the buffer
Failures:
1) FileWatch::BufferedTokenizer flush with decode_size_limit_bytes resets the state of the buffer
Failure/Error: expect(subject).to be_empty
expected `#<FileWatch::BufferedTokenizer:0x35977ba7>.empty?` to be truthy, got false
```
But with it tests pass:
```
❯ …
```

ensure inputSize state value is reset during buftok.flush

---

logstash-core/lib/logstash/modules/kibana_client.rb
logstash-core/spec/logstash/modules/kibana_client_spec.rb

Include a special product origin header for requests to Kibana so that Upgrade Assistant can avoid calling out deprecations that are not user-actionable.
Update the Kibana client with an additional HTTP header, so that Upgrade Assistant can reduce noise from non-user-actionable deprecation warnings potentially generated by the requests in Kibana.
Often Stack-internal communication may include usage of deprecated API's in one major, with upstream fixes already present in the next major's branch. This can result in non-user-actionable deprecations flooding the Upgrade Assistant. By adding the `x-elastic-product-origin` header with value Logstash, we empower the Upgrade Assistant to isolate Stack-internal communication from the user-facing messaging …

Add `x-elastic-product-origin` header to Kibana requests

---

ci/serverless/common.sh
ci/serverless/cpm_tests.sh
ci/serverless/elastic_integration_filter_tests.sh
ci/serverless/es_output_tests.sh
ci/serverless/kibana_api_tests.sh
ci/serverless/metricbeat_monitoring_tests.sh
ci/serverless/monitoring_tests.sh

[rn:skip]
This commit updates the curl scripts that interact with Kibana's
`api/logstash/pipeline/*` endpoints.

Update serverless tests to include product origin header

---

docs/static/breaking-changes-90.asciidoc

[rn:skip]
Adds information about the SSL setting obsolescence for the Elasticsearch output plugin to the `9.0` breaking changes doc

Document obsolete settings for elasticsearch output plugin

---

docs/static/security/es-security.asciidoc

Related: 
* Issue:  https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1190
* PR: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1197
The "**Secure your connection to Elasticsearch > [Configure the elasticsearch output](https://www.elastic.co/guide/en/logstash/current/ls-security.html#es-sec-plugin)**" topic contains inaccurate info (and link) in light of obsolete SSL setttings.  
This PR updates the content to point to replacement setting and fixes the example.  
**PREVIEW:** https://logstash_bk_16798.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#es-sec-plugin

Doc: Update security docs to replace obsolete cacert setting

---

docs/static/docker.asciidoc

relates: https://github.com/elastic/ingest-dev/issues/3648
Since v9, the Docker base image has been changed from Ubuntu to UBI.

[Doc] use UBI8 as base image

---

logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb

- Improves concurrent performance of some plugins when they are instantiated with an explicit `ecs_compatibility` directive.
Properly memoizes an explicitly-given `ecs_compatibility` directive on first access so that it can be retrieved _without_ lock contention.
Because a `break` escapes a `begin`...`end` block, we must not use a `break` in order to ensure that the explicitly set value gets memoized to avoid lock contention.
> ~~~ ruby
> def fake_sync(&block)
>   puts "FAKE_SYNC:enter"
>   val = yield
>   puts "FAKE_SYNC:return(#{val})"
>   return val
> ensure
>   puts "FAKE_SYNC:ensure"
> end
> 
> returned = fake_sync do
>   @ivar = begin
>     puts("BE:begin")
>     break :break # expectation: break the current `begin`...`end` block
>   	
>     val = :returned
> …

Avoid lock when ecs_compatibility is explicitly specified

---

docs/static/releasenotes.asciidoc

Related: #16821
Closes: #16822 
**PREVIEW:** https://logstash_bk_16831.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-8-17-0.html

Doc: Add json_lines known issue to release notes

---

logstash-core/src/main/java/org/logstash/jackson/StreamReadConstraintsUtil.java
logstash-core/src/test/java/org/logstash/jackson/StreamReadConstraintsUtilTest.java

Ensure that the Jackson read constraints defaults (Maximum Number value length, Maximum String value length, and Maximum Nesting depth) are applied at runtime if they are absent from `jvm.options`. 
When Logstash 8.12.0 added increased Jackson stream read constraints to jvm.options, assumptions about the existence of that file's contents were invalidated. This led to issues like #16683.
This change ensures Logstash applies defaults from config at runtime:
- MAX_STRING_LENGTH: 200_000_000
- MAX_NUMBER_LENGTH: 10_000
- MAX_NESTING_DEPTH: 1_000
These match the jvm.options defaults and are applied even when config is missing. Config values still override these defaults when present.
Users who have custom `jvm.options` files or have files that are not being updated with defaults in latest …

Apply Jackson stream read constraints defaults at runtime

---

docs/static/monitoring/monitoring-apis.asciidoc
logstash-core/lib/logstash/api/commands/stats.rb
logstash-core/spec/logstash/api/commands/stats_spec.rb

Added three pipeline metrics, workers, batch size and batch delay, to the Node Stats API
Add pipeline metrics to Node Stats API
This commit introduces three new metrics under each pipeline in the Node Stats API: 
- Number of workers
- Batch size
- Batch delay
Example response from `curl localhost:9600/_node/stats/`
```
{
...
pipelines: {
main: {
events: {...}, 
flow: {...}, 
plugins: {...}, 
reloads: {...}, 
queue: {...}, 
pipeline: {
workers: 12,
batch_size: 125,
batch_delay: 5,
}, 
}
}
...
}
```
Prior to this change, the /_node/stats only displayed the default pipeline configuration in the global namespace. Pipelines with custom configurations were not represented.
case 1
- bin/logstash
- curl localhost:9600/_node/stats/
- each pipeline should report workers, batch_size, batch_delay …

Add pipeline metrics to Node Stats API

---

config/jvm.options
tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
tools/jvm-options-parser/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java

Add support for `${VAR:default}` syntax in jvm.options file
JvmOptionsParser adds support for `${VAR:default}` syntax when parsing jvm.options
- allow dynamic resolution of environment variables in the jvm.options file
- enables fallback to default value when the environment variable is not set
`jvm.options` lost support for resolving env var using $VAR syntax since https://github.com/elastic/logstash/pull/12530, Logstash 8.0, where $VAR was interpreted as bash script syntax. This PR proposes aligning the syntax with the Logstash [convention](https://www.elastic.co/guide/en/logstash/current/environment-variables.html) for env var ${VAR:default}
- Fixes: https://github.com/elastic/logstash/issues/16444

Respect environment variables in jvm.options

---

logstash-core/lib/logstash/config/mixin.rb
logstash-core/spec/logstash/config/mixin_spec.rb

Log messages for configuration options marked as `:deprecated` in plugin config are now routed to the deprecation logger instead of the main logger. 
Previously when the `:deprecated` modifier was used in the plugin config DSL a
log message was sent at `:warn` level to the main logger. This commit updates
that message to be routed *only* to the deprecation logger.
Instead of needing to check the main logger for deprecation messages logged at `WARN` level, users can now expect to find the messages at the expected deprecation logger location. This allows them to find the complete set in the designated/expected destination. 
- ~[ ] I have made …

Ensure plugin config marked `:deprecated` logs to deprecation logger

---

docs/static/azure-module.asciidoc

Related: #16590 
We have better alternatives for the Logstash Azure module than we did when we first marked it for deprecation. 
This PR updates 8.x and 7.17 branches with a better alternative: https://www.elastic.co/guide/en/integrations/current/azure-events.html.
Backport targets:
* 8.17
* 8.16
* 7.17
**PREVIEW:** https://logstash_bk_16856.docs-preview.app.elstc.co/guide/en/logstash/8.x/azure-module.html

Doc: Add appropriate alternate for deprecated module in 8.x

---

logstash-core/lib/logstash/config/mixin.rb
logstash-core/spec/logstash/config/mixin_spec.rb

Log messages for configuration options marked as `:deprecated` in plugin config are now routed to the deprecation logger in addition to the main logger. In the next major version (9.0.0) these messages will *only* go to the deprecation logger. 
Ensure plugin config marked :deprecated logs to deprecation logger
Previously when the `:deprecated` modifier was used in the plugin config DSL a
log message was sent at `:warn` level ONLY to the main logger. This commit updates
that message to be routed *both* to the deprecation logger as well as the main
logger. In 9.x this will *only* go to the deprecation logger.
Instead of needing to check the main logger for deprecation messages logged at `WARN` level, users can now expect to find the messages at the expected deprecation logger location. This …

Ensure plugin config marked :deprecated logs to deprecation logger

---

logstash-core/src/main/java/org/logstash/jackson/StreamReadConstraintsUtil.java
logstash-core/src/test/java/org/logstash/ObjectMappersTest.java
logstash-core/src/test/java/org/logstash/jackson/StreamReadConstraintsUtilTest.java

- [rn:skip]
cleans up tests related to jackson stream read constraints configuration
- no user impact

Test touchups

---

logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java

Avoid pipeline level flow metrics initialization if pipeline level metric collection is disabled.
LS has node and pipeline level metric collection control (`metric.collect: true/false`) signal. Regardless of disabling metric collection, now flow metrics are initialized and when client requests flow stats, it faces an error. This PR adds a change which considers  `metric.collect` config when initializing pipeline flow metric.
Fixes the error when users disable pipeline metric collection.
- ~~[ ] I have added tests that prove my fix is effective …

Avoid flow metrics initialization if pipeline `metric.collect` is disabled.

---

logstash-core/benchmarks/src/main/java/org/logstash/benchmark/BufferedTokenizerExtBenchmark.java
logstash-core/spec/logstash/util/buftok_spec.rb
logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java

[rn:skip]
Currently, `BufferedTokenizer` doesn't validate size limit. That means any negative or zero value can lead `input buffer full` exception. This PR adds a safeguard validation on size limit to allow only positive number. 
As it is a public interface, this enhancement improves interface experience.
- Closes #16824

Validate the size limit in BufferedTokenizer.

---

docs/static/env-vars.asciidoc
docs/static/pipeline-configuration.asciidoc

[rn:skip]
Adds a limitation where environment `${VAR}`s cannot be used in `config.string`. To avoid pipeline run config failure, `$` can be removed.
From functional point of view, users are not impacted.
- Closes #16625 
- Closes #16008

Doc: Environment variables cannot be in config.string comments.

---

docs/static/breaking-changes-90.asciidoc

[rn:skip]
Adds SSL params obsoletion to the LS core 9.0 breaking change doc.
Improves visibility and guides to successful upgrade when users upgrade from 8.x stack to 9.0
- Closes https://github.com/logstash-plugins/logstash-input-beats/pull/508

Add beats and es-agent SSL breaking changes to 9.0 breaking change doc.

---

logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
logstash-core/src/test/java/org/logstash/log/LoggingSpyResource.java
logstash-core/src/test/java/org/logstash/plugins/pipeline/PipelineBusTest.java

- Deprecates v1 of the pipeline bus; the v2 implementation has been the default since its introduction in Logstash 8.15.0
Adds a deprecation warning if Logstash is configured to use the legacy v1 pipeline bus. The legacy implementation was replaced with a more-performant one in 8.15.0, and v1 was only left in place as an "escape hatch".
~~The ability to select v1 implementation is set to be removed on `main` in advance of 9.0 via https://github.com/elastic/logstash/pull/16644~~
It guides users away from the original lock-heavy implementation, which was previously only available as an escape hatch and is no longer necessary.
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env …

deprecate pipeline bus v1

---

README.md
lib/pluginmanager/templates/codec-plugin/README.md
lib/pluginmanager/templates/filter-plugin/README.md
lib/pluginmanager/templates/input-plugin/README.md
lib/pluginmanager/templates/output-plugin/README.md
logstash-core/lib/logstash/config/mixin.rb
logstash-core/spec/logstash/config/mixin_spec.rb

**Backport PR #16873 to 8.x branch, original message:**
[rn:skip]
Remove references to defunct freenode IRC and replace with preferred discussion forum. 
Point folks at the preferred public discussion forum. 
Closes https://github.com/elastic/logstash/issues/16851

Replace/remove references to defunct freenode instance (#16873)

---

docs/static/event-data.asciidoc
logstash-core/src/main/java/org/logstash/StringInterpolation.java
logstash-core/src/test/java/org/logstash/StringInterpolationTest.java

Add support of `%{{TIME_NOW}}` syntax to sprinf format to generate a new current timestamp
This commit added `%{{TIME_NOW}}` syntax to `event.sprintf()` to generate a fresh timestamp as string
Example
```
input {
heartbeat {
add_field => { "heartbeat_time" => "%{{TIME_NOW}}" }
}
}
filter {
mutate {
add_field => { "mutate_time" => "%{{TIME_NOW}}" }
}
}
```
It gives two different timestamps.
When the incoming event has value in `@timestamp`, eg. event from agent, Logstash use the provided value instead of generating a new timestamp. Prior to the change, there is no way to force a new timestamp to generate during the execution of input plugins. 
Previously, users often generate timestamp with ruby-filter `code => "event.set('ruby_time', Time.now());"`, but this approach requires events to …

Add %{{TIME_NOW}} pattern for sprintf

---

.buildkite/scripts/dra/common.sh

[rn:skip]
Increase to 4Gb the max heap memory used by JVM to run JRuby's Rake during DRA.

Increase Xmx used by JRuby during Rake execution to 4Gb

---

.buildkite/dra_pipeline.yml
.buildkite/scripts/dra/build_docker.sh
.buildkite/scripts/dra/build_packages.sh
.buildkite/scripts/dra/common.sh
.buildkite/scripts/dra/generatesteps.py
.buildkite/scripts/dra/publish.sh

[rn:skip]
This commit uses the new --qualifier parameter in the release manager for publishing dra artifacts. Additionally, simplifies the expected variables to rely on a simple `VERSION_QUALIFIER`.
Finally, we skip snapshot builds when VERSION_QUALIFIER is set.
Enables prerelease staging builds
To test via this PR supply the following BK options to the staging pipeline:
```
DRA_VERSION="main"
VERSION_QUALIFIER="alpha1"
```
which results in a successful build -> https://buildkite.com/elastic/logstash-dra-staging-pipeline/builds/177
Once it's merged, manual staging builds need to be triggered using only `VERSION_QUALIFIER`; docs will be updated for https://docs.elastic.dev/ingest-dev-docs/logstash/dra#usage-of-version_qualifier_opt via a follow up PR.
Also tested a snapshot build to ensure …

Use --qualifier in release manager

---

.buildkite/dra_pipeline.yml
.buildkite/scripts/dra/build_docker.sh
.buildkite/scripts/dra/build_packages.sh
.buildkite/scripts/dra/generatesteps.py
.buildkite/scripts/dra/publish.sh

**(cherry picked from commit 9385cfac5a4edb7a7a7038151b77a379426f96e0)**
Automated backport had conflicts in `.buildkite/scripts/dra/build_docker.sh` where before main we also build ubi8.
--- 
[rn:skip]
This commit uses the new --qualifier parameter in the release manager for publishing dra artifacts. Additionally, simplifies the expected variables to rely on a simple `VERSION_QUALIFIER`.
Finally, we skip snapshot builds when VERSION_QUALIFIER is set.
Enables prerelease staging builds
To test via this PR supply the following BK options to the staging pipeline:
```
DRA_VERSION="main"
VERSION_QUALIFIER="alpha1"
```
which results in a successful build -> https://buildkite.com/elastic/logstash-dra-staging-pipeline/builds/177
Once it's merged, manual staging builds need to be triggered using …

Backport 16907 to 8.x: Use --qualifier in release manager (#16907)

---

docs/static/releasenotes.asciidoc

forward port [8.16.3](https://github.com/elastic/logstash/pull/16879) and [8.17.1](https://github.com/elastic/logstash/pull/16880) release notes

Forward 8.17.1 release notes

---

Gemfile.jruby-3.1.lock.release

fixes: https://github.com/elastic/logstash/issues/16903
Rather than waiting for the 8.18.0 release, we should ship this functionality in the next release in the 8.17 series by updating the lockfile to include 4.21.x of the plugin, rather than be pinned to 4.20.x.

Update 8.17 Lockfile to include 4.21.x of the Elasticsearch input 

---

Gemfile.template
lib/bootstrap/bundler.rb
lib/bootstrap/patches/jar_dependencies.rb

handle maven output that can carry "garbage" information after the jar's name. this patch deletes that extra information, also pins psych to 5.2.2 until jruby ships with snakeyaml-engine 2.9 (upcoming in 9.4.10.0)
exhaustive test run: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1155 🟢 
backport to 8.x: https://github.com/elastic/logstash/pull/16920
closes https://github.com/elastic/logstash/issues/16921

fix jars installer for new maven and pin psych to 5.2.2

---

docs/static/ls-to-cloud.asciidoc

Extra symbol doesn't cause problems in classic docs, but will for V3 docs.

Doc: Remove extra symbol to fix formatting error

---

docs/static/security/api-keys.asciidoc
docs/static/security/grant-access.asciidoc
docs/static/settings/configuration-management-settings.asciidoc

This commit updated the instructions of using central pipeline management with the necessary privileges
fixes: https://github.com/elastic/logstash/issues/16905
relates: https://github.com/elastic/ingest-dev/issues/4812

[doc] fix the necessary privileges of central pipeline management

---

docs/static/security/api-keys.asciidoc
docs/static/security/logstash.asciidoc
docs/static/settings/configuration-management-settings.asciidoc

backport https://github.com/elastic/logstash/pull/16902
This commit updated the instructions of using central pipeline management with the necessary privileges

Backport [doc] fix the necessary privileges of central pipeline management 

---

.buildkite/dra_pipeline.yml
.buildkite/scripts/dra/build_docker.sh
.buildkite/scripts/dra/build_packages.sh
.buildkite/scripts/dra/generatesteps.py
.buildkite/scripts/dra/publish.sh

**(cherry picked from commit 9385cfac5a4edb7a7a7038151b77a379426f96e0)**
Automated backport had conflicts in `.buildkite/scripts/dra/build_docker.sh` where before main we also build ubi8.
--- 
[rn:skip]
This commit uses the new --qualifier parameter in the release manager for publishing dra artifacts. Additionally, simplifies the expected variables to rely on a simple `VERSION_QUALIFIER`.
Finally, we skip snapshot builds when VERSION_QUALIFIER is set.
Enables prerelease staging builds
To test via this PR supply the following BK options to the staging pipeline:
```
DRA_VERSION="main"
VERSION_QUALIFIER="alpha1"
```
which results in a successful build -> https://buildkite.com/elastic/logstash-dra-staging-pipeline/builds/177
Once it's merged, manual staging builds need to be triggered using …

Backport 16907 to 8.17: Use --qualifier in release manager (#16907)

---

.buildkite/dra_pipeline.yml
.buildkite/scripts/dra/build_docker.sh
.buildkite/scripts/dra/build_packages.sh
.buildkite/scripts/dra/generatesteps.py
.buildkite/scripts/dra/publish.sh

**(cherry picked from commit 9385cfac5a4edb7a7a7038151b77a379426f96e0)**
Automated backport had conflicts in `.buildkite/scripts/dra/build_docker.sh` where before main we also build ubi8.
--- 
[rn:skip]
This commit uses the new --qualifier parameter in the release manager for publishing dra artifacts. Additionally, simplifies the expected variables to rely on a simple `VERSION_QUALIFIER`.
Finally, we skip snapshot builds when VERSION_QUALIFIER is set.
Enables prerelease staging builds
To test via this PR supply the following BK options to the staging pipeline:
```
DRA_VERSION="main"
VERSION_QUALIFIER="alpha1"
```
which results in a successful build -> https://buildkite.com/elastic/logstash-dra-staging-pipeline/builds/177
Once it's merged, manual staging builds need to be triggered using …

Backport 16907 to 8.16: Use --qualifier in release manager (#16907)

---

lib/pluginmanager/proxy_support.rb
spec/unit/plugin_manager/proxy_support_spec.rb

URI::Generic expects that JRuby will use http.proxyUser and http.proxyPass instead of http.proxyUsername and http.proxyPassword.
This misalignment breaks plugin manager's ability to use an authenticated proxy.
This commit fixes the alignment and confirms that the proxy configuration fetched from a URI object has the user and password set correctly.

fix user and password detection from environment's uri

---

docker/templates/Dockerfile.erb

This commit added `openssl` command to logstash-wolfi image
Fixes: #16965 
I have built local image and run in minikube successfully.

add openssl command to wolfi image

---

docs/static/plugin-manager.asciidoc
lib/bootstrap/bundler.rb
lib/pluginmanager/update.rb
spec/unit/bootstrap/bundler_spec.rb
spec/unit/plugin_manager/update_spec.rb

- By default, the plugin manager will no longer consume breaking changes in plugins, and will instead only consume minor revisions. If you wish to consume breaking changes, you must now explicitly add the `--level=major` flag.
Adds `--level=[major|minor|patch]` to the `bin/logstash-plugin update` command, with default value `minor`, and propagates it to the underlying bundler's `--major`, `--minor`, or `--patch` flags, to ensure users can upgrade while avoiding breaking changes.
Users are currently being surprised when their `bin/logstash-plugin update` consumes breaking changes in plugins, causing their currently-valid pipeline configurations to fail to load. This removes the element of surprise, while still allowing users to upgrade across the major version of the plugins if they …

plugin manager: add `--level=[major|minor|patch]` (default: `minor`)

---

docker/templates/Dockerfile.erb

Backport of https://github.com/elastic/logstash/pull/16966
This commit added openssl command to logstash-wolfi image

[Backport 8.x] add openssl command to wolfi image

---

docker/templates/Dockerfile.erb

Backport of https://github.com/elastic/logstash/pull/16966
This commit added openssl command to logstash-wolfi image

[Backport 8.17] add openssl command to wolfi image

---

docker/templates/Dockerfile.erb

Backport of https://github.com/elastic/logstash/pull/16966
This commit added openssl command to logstash-wolfi image

[Backport 8.16] add openssl command to wolfi image

---

qa/integration/specs/beats_input_spec.rb

log input has been deprecated in filebeat 9.0.0 and throws an error if it's present in the configuration.
This commit switches the configuration to the "filestream" input.
exhaustive test suite run: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1205

integration tests: switch log input to filestream in filebeat

---

logstash-core/spec/logstash/util/buftok_spec.rb
logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java

(cherry picked from commit a215101032e0441701eaa779b102b7443b9af12a)
[Backport tool](https://github.com/elastic/logstash/actions/runs/12700618738/job/35403640695) conflicted with #16882 where 8.16 doesn't have `BufferedTokenizerExtBenchmark.java` class.
-

Backport PR #16882 to 8.16: Validate the size limit in BufferedTokenizer.

---

docs/static/breaking-changes-90.asciidoc

This commit removes the "sample changes" example from the breaking changes documentation

Remove sample breaking change from breaking changes doc

---

docs/static/upgrading.asciidoc

This commit updates the Logstash upgrade docs to refer to `9.0`/`9.x` instead of `8.0`/`8.x`

Changing upgrade docs to refer to `9.0` instead of `8.0`

---

docs/static/upgrading.asciidoc

[rn:skip]
Adds an upgrade guidelines and details about `elastic_integration` plugin.
Explains the upgrade order and details to the `elastic_integration` plugin users

Adding elastic_integration upgrade guidelines.

---

versions.yml

exhaustive test suite: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1178

upgrade jdk to 21.0.6+7

---

versions.yml

Manual backport of https://github.com/elastic/logstash/pull/16932 to 8.16

Backport #16932: Upgrade JDK to 21.0.6+7

---

.buildkite/dra_pipeline.yml
.buildkite/scripts/dra/generatesteps.py

[rn:skip]
To avoid manual invocations specifying the version qualifier for prereleases in this commit we leverage a centralized version of truth for the version qualifier.
We also honor the `DRA_BRANCH` BK var for the generated step names (the functionality was already there, it's just a cosmetic improvement).
Removes the need to specify VERSION_QUALIFIER when building DRA (staging) artifacts entirely.
Can only be tested in BK. Links to be provided:
**NOTE** This is raised against 9.0 because it's the immediate need, and should be **forward** ported to `main`, as well as backported to all 8.x branches.

Use centralized version qualifier

---

.buildkite/dra_pipeline.yml
.buildkite/scripts/dra/generatesteps.py

Reverts elastic/logstash#16995
As mentioned in https://github.com/elastic/logstash/pull/16995#issuecomment-2626811054 testing revealed
that even an empty VERSION_QUALIFIER env var currently gets honored for snapshot builds (resulting in an unnecessary empty "-" suffix)
so there's a little more prerequisite work needed.

Revert "Use centralized version qualifier"

---

logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtTest.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithDelimiterTest.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java

[rn:skip]
This is a second take to fix the processing of tokens from the tokenizer after a buffer full error. The first try #16482 was rollbacked to the encoding error #16694.
The first try failed on returning the tokens in the same encoding of the input.
This PR does a couple of things:
- accumulates the tokens, so that after a full condition can resume with the next tokens after the offending one.
- respect the encoding of the input string. Use `concat` method instead of `addAll`, which avoid to convert RubyString to String and back to RubyString. When return the head `StringBuilder` it enforce the encoding with the input charset.
Permit to use effectively the tokenizer also in context where a line is bigger than a limit. …

Fix BufferedTokenizer to properly resume after a buffer full condition respecting the encoding of the input string

---

tools/release/generate_release_notes.rb

[rn:skip]
Modifies release note generator in a way that notes might be empty, parsing should be nil tolerant.
Before, generator was failing with following error:
```
Switched to a new branch '9.0'
./tools/release/generate_release_notes.rb:[5](https://github.com/elastic/logstash/actions/runs/13162596537/job/36734882969#step:6:6)1:in `block in <main>': undefined method `match' for nil:NilClass (NoMethodError)
from ./tools/release/generate_release_notes.rb:51:in `any?'
from ./tools/release/generate_release_notes.rb:51:in `<main>'
Error: Process completed with exit code 1.
```
- ~~[ ] I have made corresponding changes to the …

Release note placeholder might be empty, make parsing lines nil tolerant.

---

build.gradle

[rn:skip]
Opens the IO modules in Gradle test task to let the `7.17` tested without IO access errors on Windows OS.
Permit to keep the `7.17` tested with JDK 17.
Spawn a WinOS image used by BK after checkout of `7.17` run
```
C:\Users\buildkite\logstash\.buildkite\scripts\jdk-matrix-tests\launch-command.ps1  -JDK adoptiumjdk_17  -CIScript "ci\unit_tests.ps1 ruby"
```
Because the failure seems not to be always consistent you can loop with this script
```
for ($i = 0; $i -lt 10; $i++) {
Write-Host "Running script for iteration $i"
try { …
```

Open modules to test also with jdk17 under Windows OS

---

logstash-core/src/main/java/org/logstash/secret/cli/Terminal.java
qa/integration/specs/secret_store_spec.rb

Fix logstash-keystore to accept spaces in values when added via stdin
`logstash-keystore` incorrectly handled values containing spaces, causing only the first word to be stored.
For example, a value like "Hello, world!" was split, resulting in "Hello," as the stored value instead of the full string.
This commit preserves spaces in values, ensuring that multi-word strings are stored as intended.
This issue mainly affected ECK users who followed best practices for managing secure settings, leading to incorrect value assignments.
```yaml
apiVersion: v1
kind: Secret
metadata:
name: logstash-secure-settings
namespace: logstash-sample
stringData:
hello: "Hello, world!"
bye: "bye"
```
Users who use stdin to add value are impacted as well. For example, `echo "somevalue" | bin/logstash-keystore …

Fix logstash-keystore to accept spaces in values when added via stdin

---

.buildkite/pull_request_pipeline.yml
ci/get-test-half.sh
ci/integration_tests.sh
ci/run-fips-integration-tests.sh

[rn:skip]
The integration tests suite takes about 40 minutes. This is far too slow for reasonable feedback on a PR. This commit follows the pattern for the non-fips integration tests whereby the tests are split into two sections that can run in parallel across two steps. This should halve the feedback time.
This reduces feedback time on PR tests by a factor of 2. 
```
docker build -t test-runner-image -f x-pack/distributions/internal/observabilitySRE/docker/Dockerfile .
docker run test-runner-image ci/run-fips-integration-tests.sh 1
``` …

Split fips integration tests into two steps

---

Gemfile.jruby-2.5.lock.release
build.gradle
config/jvm.options
logstash-core/build.gradle
logstash-core/src/main/java/org/logstash/ObjectMappers.java
logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
tools/ingest-converter/build.gradle
versions.yml

Plugins
* logstash-input-azure_event_hubs: 1.5.1
* logstash-input-beats: 6.4.3-java
Jars
* jackson: 2.14.1
* jackson-databind: 2.14.1
* guava: 32.1.3
* org.yaml:snakeyaml: 2.2 (ingest converter)
Gems
* march_hare: 4.6.0-java
* jrjackson: 0.4.17
Other changes:
* tweak add-exports/add-opens to accomodate newer dependencies
* serialization changes to ObjectMappers.java to accommodate jackson 2.13
exhaustive test suite run: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1297

Bump versions for 7.17.28

---

.buildkite/scripts/common/trigger-pipeline-generate-steps.sh

**Backport PR #17063 to 8.16 branch, original message:**
---
[rn:skip]
This commit simplifies the DRA process in Logstash by removing the need to maintain a separate file for the active branches, and instead rely on a centrally maintained file containing source of truth.
While at it, we refactor/simplify the creation of an array with the versions in `.buildkite/scripts/snyk/resolve_stack_version.sh`.
Removes a manual step required when new branches get cut.
```yaml
$ PIPELINES_TO_TRIGGER="test-pipeline" .buildkite/scripts/common/trigger-pipeline-generate-steps.sh 
--- Printing generated steps
steps:
- trigger: test-pipeline
label: ":testexecute: Triggering test-pipeline / 7.17"
build:
branch: "7.17"
message: ":testexecute: Scheduled build for 7.17"
- trigger: test-pipeline
label: …
```

Backport PR #17063 to 8.16: Use centralized source of truth for active branches

---

.buildkite/scripts/common/trigger-pipeline-generate-steps.sh

**Backport PR #17063 to 8.18 branch, original message:**
---
[rn:skip]
This commit simplifies the DRA process in Logstash by removing the need to maintain a separate file for the active branches, and instead rely on a centrally maintained file containing source of truth.
While at it, we refactor/simplify the creation of an array with the versions in `.buildkite/scripts/snyk/resolve_stack_version.sh`.
Removes a manual step required when new branches get cut.
```yaml
$ PIPELINES_TO_TRIGGER="test-pipeline" .buildkite/scripts/common/trigger-pipeline-generate-steps.sh 
--- Printing generated steps
steps:
- trigger: test-pipeline
label: ":testexecute: Triggering test-pipeline / 7.17"
build:
branch: "7.17"
message: ":testexecute: Scheduled build for 7.17"
- trigger: test-pipeline
label: …
```

Backport PR #17063 to 8.18: Use centralized source of truth for active branches

---

.buildkite/scripts/common/trigger-pipeline-generate-steps.sh

**Backport PR #17063 to 8.x branch, original message:**
---
[rn:skip]
This commit simplifies the DRA process in Logstash by removing the need to maintain a separate file for the active branches, and instead rely on a centrally maintained file containing source of truth.
While at it, we refactor/simplify the creation of an array with the versions in `.buildkite/scripts/snyk/resolve_stack_version.sh`.
Removes a manual step required when new branches get cut.
```yaml
$ PIPELINES_TO_TRIGGER="test-pipeline" .buildkite/scripts/common/trigger-pipeline-generate-steps.sh 
--- Printing generated steps
steps:
- trigger: test-pipeline
label: ":testexecute: Triggering test-pipeline / 7.17"
build:
branch: "7.17"
message: ":testexecute: Scheduled build for 7.17"
- trigger: test-pipeline
label: …
```

Backport PR #17063 to 8.x: Use centralized source of truth for active branches

---

.buildkite/scripts/common/trigger-pipeline-generate-steps.sh

**Backport PR #17063 to 8.17 branch, original message:**
---
[rn:skip]
This commit simplifies the DRA process in Logstash by removing the need to maintain a separate file for the active branches, and instead rely on a centrally maintained file containing source of truth.
While at it, we refactor/simplify the creation of an array with the versions in `.buildkite/scripts/snyk/resolve_stack_version.sh`.
Removes a manual step required when new branches get cut.
```yaml
$ PIPELINES_TO_TRIGGER="test-pipeline" .buildkite/scripts/common/trigger-pipeline-generate-steps.sh 
--- Printing generated steps
steps:
- trigger: test-pipeline
label: ":testexecute: Triggering test-pipeline / 7.17"
build:
branch: "7.17"
message: ":testexecute: Scheduled build for 7.17"
- trigger: test-pipeline
label: …
```

Backport PR #17063 to 8.17: Use centralized source of truth for active branches

---

.buildkite/scripts/dra/common.sh
.buildkite/scripts/dra/generatesteps.py

[rn:skip]
This commit allows Buildkite to capture any heap dumps produced during DRA builds.
Eases investigating failing builds like https://buildkite.com/elastic/logstash-dra-snapshot-pipeline/builds/2231#0194fd28-acc5-4f24-9f06-66e52b3f0567

Allow capturing heap dumps in DRA BK jobs

---

build.gradle
qa/integration/framework/settings.rb
qa/integration/services/logstash_service.rb
qa/integration/specs/logstash_to_logstash_spec.rb

[rn: skip]
Ensures that Logstash integration tests are run against a _clean_ expansion of the built tarball.
Because QA tests can _modify_ the Logstash installation (e.g. those that invoke the plugin manager), it is important that the service wrapper begins with a clean expansion of the logstash tarball.
Run integration tests that invoke the Logstash service (or any of its sub-command features like the plugin manager):
~~~ sh
ci/integration_tests.sh specs/cli/remove_spec.rb
~~~
see `expunging`, indicating that the old was removed
see …

qa: use clean expansion of LS tarball per fixture instance

---

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java

currently the deserialization is behind the readBatch's lock, so any large batch will take time deserializing, causing any other Queue writer (e.g. netty executor threads) and any other Queue reader (pipeline worker) to block.
This commit moves the deserialization out of the lock, allowing multiple pipeline workers to deserialize batches concurrently.
To test, edit the generator input to produce 100kb messages, and run:
`bin/logstash -e "input { generator { threads => 5 } } output { null {} }"` with PQ enabled.
This PR should shows about a 4-5x performance improvement for 10 worker pipeline:
| Metric                  | v8.15.5 | v8.15.5+pr17050 |
|-------------------------|---------:|-----------------:|
| Events per Second                    |    1031     |           4971      |
| CPU …

move Batch deserialization out of the lock

---

qa/integration/fixtures/logstash_to_logstash_spec.yml
qa/integration/specs/logstash_to_logstash_spec.rb

[rn:skip]
- fixes upstream/downstream convention
- upstream: the sending logstash (has an LS output)
- downstream: the receiving logstash (has an LS input)
- helper `run_logstash_instance` yields the `LogstashService` instance and handles the teardown (prevents teardown getting skipped when an exception occurs before it).
- pass the pipeline id and node name to the LS instances via command line flags to make logging easier to differentiate
- use the generator input's sequence id to ensure that the _actual_ events generated are received by the downstream pipeline
No user impact; better tests same basic coverage.

spec: improve ls2ls spec

---

lib/pluginmanager/bundler/logstash_uninstall.rb
lib/pluginmanager/remove.rb
qa/integration/fixtures/plugins/generate-gems.sh
qa/integration/fixtures/plugins/logstash-filter-four_depends_on_one_and_three.gemspec
qa/integration/fixtures/plugins/logstash-filter-one_no_dependencies.gemspec
qa/integration/fixtures/plugins/logstash-filter-three_no_dependencies.gemspec
qa/integration/fixtures/plugins/logstash-filter-two_depends_on_one.gemspec
qa/integration/fixtures/plugins/logstash-filter-zero_no_dependencies.gemspec
qa/integration/services/logstash_service.rb
qa/integration/specs/cli/remove_spec.rb
rakelib/plugin.rake

The plugin manager `bin/logstash-plugin`'s `remove` command now allows multiple plugins to be removed in a single call. This simplifies removing plugins that depend on other plugins, so that the caller no longer needs to perform the removals in dependency order.
Removal works by _optimistically_ removing all specified plugin-gems from a mutable gemspec, then validating that doing so does not leave plugin-gems with orphaned runtime dependencies, saving the result and succeeding only if no conflicts were created.
> ~~~
> ╭─{ rye@perhaps:~/src/elastic/logstash@main (pluginmanager-remove-multiple ✘) }
> ╰─● bin/logstash-plugin remove logstash-input-syslog logstash-filter-grok
> Using system java: /Users/rye/.jenv/shims/java
> Resolving dependencies......
> Successfully removed …

plugins: improve `remove` command to support multiple plugins

---

qa/acceptance/spec/shared_examples/cli/logstash-plugin/integration_plugin.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb

[rn:skip]
This commit updates the acceptance tests to expect messages in the updated format for removing plugins. See https://github.com/elastic/logstash/pull/17030 for change.
No user impact, this is fixing acceptance test assertions
- Relates to https://github.com/elastic/logstash/pull/17030
Example failures:
https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1359#01951fe3-2f12-46d5-872e-0af111c463ba
```console
1) CLI operation behaves like …
```

Fix acceptance test assertions for updated plugin `remove`

---

qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb

[rn:skip]
This commit updates the acceptance tests to expect messages in the updated format for removing plugins. See https://github.com/elastic/logstash/pull/17030 for change.
No user impact, this is fixing acceptance test assertions
- Relates to https://github.com/elastic/logstash/pull/17030
- Completes https://github.com/elastic/logstash/pull/17122
Example failures:
https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1361#01952103-6591-43cf-a364- …

Fix acceptance test assertions for updated plugin remove

---

qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb

**Backport PR #17126 to 8.x branch, original message:**
---
[rn:skip]
This commit updates the acceptance tests to expect messages in the updated format for removing plugins. See https://github.com/elastic/logstash/pull/17030 for change.
No user impact, this is fixing acceptance test assertions
- Relates to https://github.com/elastic/logstash/pull/17030
- Completes https://github.com/elastic/logstash/pull/17122
Example failures: …

Backport PR #171226 to 8.x: Fix acceptance test assertions for updated plugin remove

---

bin/logstash.bat
bin/logstash.lib.sh

[rn:skip]
routes output from setup-related bits in the entrypoint scripts to stderr, so that stdout can include only the output of the actual program.
This change makes it possible to use the stdout of entrypoints like `bin/logstash-plugin` without the setup-related pollution:
> ~~~
> Using system java: /Users/rye/.jenv/shims/java
> ~~~
For example, with https://github.com/elastic/logstash/pull/17124's addition of `--no-expand`, and given an `allowlist` containing the names of plugins to keep,
~~~
comm -1 -2 <(cat allowlist | sort) <(bin/logstash-plugin list --no-expand | sort) | xargs bin/logstash-plugin remove 
~~~
The above is not possible if the stdout of `bin/logstash-plugin` invocation is littered with info about the JVM.
- ~~[ ] I have commented my code, particularly in …

entrypoint: avoid polluting stdout

---

qa/docker/shared_examples/container.rb

[rn:skip]
In https://github.com/elastic/logstash/pull/17125 jvm setup was redirected to stderr to avoid polluting stdout. This test was actually having to do some additional processing to parse that information. Now that we have split the destinations the tests can be simplified to look for the data they are trying to validate on the appropriate stream.
No user impact, just a test fix. 
- https://github.com/elastic/logstash/pull/17125
```console
Failures:
--
  |  
  | …
```

Update container acceptance tests with stdout/stderr changes

---

qa/acceptance/spec/shared_examples/cli/logstash-plugin/integration_plugin.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb

**Backport PR #17126 to 8.x branch, original message:**
---
[rn:skip]
This commit updates the acceptance tests to expect messages in the updated format for removing plugins. See https://github.com/elastic/logstash/pull/17030 for change.
No user impact, this is fixing acceptance test assertions
- Relates to https://github.com/elastic/logstash/pull/17030
Example failures:
https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1359#01951fe3-2f12-46d5-872e …

Backport PR #171222 to 8.x: Fix acceptance test assertions for updated plugin remove

---

lib/pluginmanager/list.rb
lib/pluginmanager/util.rb
qa/integration/fixtures/list_spec.yml
qa/integration/specs/cli/list_spec.rb

* The plugin manager `bin/logstash-plugin`'s  `list` command now supports a `--no-expand` flag to avoid expanding plugin aliases and the individual plugins within integration plugins.
Adds `--[no-]expand` flag (default: true) to the plugin manager's `list` command, so that a caller can avoid expanding the integration plugins and aliases to get only a list of the plugin _packages_ installed.
- ~~[] I have made corresponding change to the default configuration files (and/or docker env variables)~~
~~~
bin/logstash-plugin list --no-expand
~~~
~~~
bin/logstash-plugin list --verbose --no-expand
~~~
~~~
bin/logstash-plugin list --no-expand logstash-integration-aws
~~~
~~~
bin/logstash-plugin list --no-expand --verbose …

plugin manager: add --no-expand flag for list command

---

spec/spec_helper.rb
spec/unit/plugin_manager/offline_plugin_packager_spec.rb

[rn:skip] 
This commit introduces a pattern for skipping tests we do not want to run in fips mode. In this case the plugin manager tests rely on using bundler/net-http/openssl which is not configured to be run with bouncycastle fips providers.
- Closes https://github.com/elastic/ingest-dev/issues/5070

Skip offline pack manager tests when running in fips mode

---

ci/docker_acceptance_tests.sh
docker/Makefile
rakelib/artifacts.rake

ensure env2yaml files are included in the dockerfiles tarball
Also builds full image from dockerfiles during docker acceptance testing to ensure the dockerfiles work.
exhaustive test run: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1394
fixes https://github.com/elastic/logstash/issues/17147

add env2yaml source files to build context tarball

---

.buildkite/scripts/exhaustive-tests/generate-steps.py
NOTICE.TXT
docker/templates/Dockerfile.erb
docs/static/docker.asciidoc
logstash-core/lib/logstash/dependency_report.rb
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/test/resources/expectedNoticeOutput.txt
tools/dependencies-report/src/test/resources/expectedOutput.txt
tools/dependencies-report/src/test/resources/licenseMapping-conflicting.csv
tools/dependencies-report/src/test/resources/licenseMapping-good.csv
tools/dependencies-report/src/test/resources/licenseMapping-missing.csv
tools/dependencies-report/src/test/resources/licenseMapping-missingNotices.csv
tools/dependencies-report/src/test/resources/licenseMapping-missingUrls.csv
tools/dependencies-report/src/test/resources/licenseMapping-unacceptable.csv
tools/dependencies-report/src/test/resources/rubyDependencies.csv

unclean backport of https://github.com/elastic/logstash/pull/17156 to 9.0 due to doc migration

[Backport 9.0] use UBI9 as base image

---

docker/Makefile

Exhaustive test run: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1412
Don't merge until exhaustive test run shows docker acceptance tests passing.

add missing Makefile tasks to build oss and wolfi images from build context tarballs

---

logstash-core/lib/logstash/api/commands/stats.rb
qa/integration/services/monitoring_api.rb
x-pack/qa/integration/monitoring/direct_shipping_spec.rb

Fixed an issue where the `/_node/stats` API displayed empty pipeline metrics when X-Pack monitoring was enabled
When monitoring is enabled, the metrics store does not initialise data for monitoring pipeline. The api has null pointer when fetching the pipeline config like workers, batch_size. 
`/_node/stats`  gives empty `pipelines: {}`
- closes: https://github.com/elastic/logstash/issues/17180
-

Fix empty node stats pipelines

---

docs/release-notes/index.md

I revisited the IA inventory to make sure nothing slipped through the cracks during the most recent move. This just adds one URL to an existing page's `mapped_pages` for tracking purposes.

[docs] Add missing `mapped_page`

---

.buildkite/pull_request_pipeline.yml
logstash-core/spec/logstash/patches_spec.rb
logstash-core/spec/logstash/persisted_queue_config_validator_spec.rb
qa/integration/fixtures/plugins/generate-gems.sh
qa/integration/rspec.rb
qa/integration/specs/cli/prepare_offline_pack_spec.rb
qa/integration/specs/cli/remove_spec.rb
qa/integration/specs/install_java_plugin_spec.rb
qa/integration/specs/webserver_spec.rb
spec/unit/bootstrap/bundler_spec.rb
x-pack/distributions/internal/observabilitySRE/docker/Dockerfile

[rn:skip]
This PR is broken up into commits that track the sub tasks in https://github.com/elastic/ingest-dev/issues/5048. Many of the test failures in the integration test suite for running under fips mode are actually due to tools required by tests being missing in the runtime. Similarly the tests assume they are not run as root user. This PR fixes those issues by adding required packages and configuring a non root user. By fixing those issues some of the other more test specific failures can be seen. By collecting the modifications in a single PR we can show incremental progress on total test failures and eventually get to fully green.
Closes https://github.com/elastic/ingest-dev/issues/5074
Closes https://github.com/elastic/ingest-dev/issues/5088
Closes …

Get tests running in FIPS environment

---

lib/pluginmanager/command.rb
lib/pluginmanager/gemfile.rb
lib/pluginmanager/install.rb
lib/pluginmanager/remove.rb
lib/pluginmanager/update.rb
qa/integration/fixtures/update_spec.yml
qa/integration/services/logstash_service.rb
qa/integration/specs/cli/install_spec.rb
qa/integration/specs/cli/pluginmanager_spec_helper.rb
qa/integration/specs/cli/remove_spec.rb
qa/integration/specs/cli/update_spec.rb

- FIX: The plugin manager now correctly cleans up plugins and gem dependencies that are no longer needed after invoking `install`, `remove`, or `update`.
- FIX: The plugin manager's `update` command no longer fails to upgrade plugins that were initially installed with `--version` flag
- Takes the previously-reviewed guts of https://github.com/elastic/logstash/pull/16998 and attaches the `clean` operation to the successful completions of the `update`, `remove`, and `install` commands _instead of_ as its own stand-alone command.
- Fixes https://github.com/elastic/logstash/issues/17196, in which the `update` command fails to update plugins that were initially installed with a `--version` flag
- For users who update, install, or remove plugins, cleaning out deactivated dependencies can reduce …

Pluginmanager clean after mutate

---

logstash-core/lib/logstash/persisted_queue_config_validator.rb
logstash-core/spec/logstash/persisted_queue_config_validator_spec.rb

[Release Notes] Improve warning message for insufficient disk space when configuring persistent queues for pipelines.
This commit refactors the `PersistedQueueConfigValidator` class to provide a
more detailed, accurate and actionable warning when pipeline's PQ configs are at
risk of running out of disk space. See
https://github.com/elastic/logstash/issues/14839 for design considerations. The
highlights of the changes include accurately determining the free resources on a
filesystem disk and then providing a breakdown of the usage for each of the
paths configured for a queue.
The user will now have a much more detailed and accurate warning they can meaninfully take action with. Here is an example output (as generated using test mocks in the unit tests)
```
Persistent queues require more …
```

Improve warning for insufficient file resources for PQ max_bytes

---

qa/integration/fixtures/logstash_to_logstash_spec.yml

From: Mashhurs  https://github.com/yaauie/logstash/pull/5
Adds heartbeat-input to the LS to LS integration test config to keep upstream Logstash alive.

[test] ls2ls spec adds heartbeat to keep alive

---

build.gradle

Fixes: https://github.com/elastic/ingest-dev/issues/5165
The artifacts-api.elastic.co is deprecated. This commit migrates gradle task to the new artifacts-api
- remove dependency on staging artifacts
- all builds use snapshot artifacts
- resolve version from current branch, major.x, previous minor,
with priority given in that order.
Take branch 8.x as example, the version first try to take from [8.19](https://storage.googleapis.com/artifacts-api/snapshots/8.19.json), then fallback to [8.x](https://storage.googleapis.com/artifacts-api/snapshots/8.x.json), and finally fallback to [8.18](https://storage.googleapis.com/artifacts-api/snapshots/8.18.json)
For 9.0, the order is 9.0, then 9.x, and finally 8.x

gradle task migrate to the new artifacts-api

---

.mergify.yml

this should help with backporting to the current active branches
without knowing the active minor but using the major one
> Maybe this is solved already, but is there a way we can get an automatically kept up to date “backport-active-minors” label that auto backports to the set of minor releases that are still supported? I’d want this in Beats, Elastic Agent, and Fleet Server if it already exists. I’ve noticed an increase in forgotten backports because there are more releases to keep track of. If we can abstract this it’d make life easier, I think Kibana does something like this
We, observability robots team, are responsible for keeping those aliases in sync - we are working on the automation for that.
Enable `backport-active-all`, `backport-active-8` and `backport-active-9` GitHub labels …

mergify: support for some backport aliases

---

bin/pqcheck.bat
bin/pqrepair.bat

A recent change to pqcheck, attempted to address an issue where the pqcheck would not on Windows mahcines when located in a folder containing a space, such as "C:\program files\elastic\logstash". While this fixed an issue with spaces in folders, it introduced a new issue related to Java options, and the pqcheck was still unable to run on Windows.
This PR attempts to address the issue, by removing the quotes around the Java options, which caused the option parsing to fail, and instead removes the explicit setting of the classpath - the use of `set CLASSPATH=` in the `:concat` function is sufficient to set the classpath, and should also fix the spaces issue
Fixes: #17209

Fix pqcheck and pqrepair on Windows

---

lib/pluginmanager/install.rb
qa/integration/specs/cli/install_spec.rb
qa/integration/specs/cli/pluginmanager_spec_helper.rb

[rn:skip]
Fixes a regression introduced in https://github.com/elastic/logstash/pull/17203 that caused the `bin/logstash-plugin install --preserve` flag to not preserve.
- When a plugin is installed with `--version`, the `Gemfile` is amended to add the plugin and its version requirement.
- When this version requirement is present, installing it again with the `--preserve` flag should preserve the requirement.
- A fix to allow plugins installed with `--version` to be _upgraded_ had the side-effect of making the install command's `--preserve` not work.
This PR comes with tests and a fix separately. The tests can be used …

Pluginmanager install preserve

---

.buildkite/scripts/health-report-tests/bootstrap.py

relates: https://github.com/elastic/ingest-dev/issues/5165
This commit replaced the deprecated artifacts-api by the new API

Health report integration test migrate to the new artifacts-api

---

lib/pluginmanager/command.rb
lib/pluginmanager/gemfile.rb
lib/pluginmanager/install.rb
lib/pluginmanager/remove.rb
lib/pluginmanager/update.rb
qa/integration/fixtures/update_spec.yml
qa/integration/services/logstash_service.rb
qa/integration/specs/cli/install_spec.rb
qa/integration/specs/cli/pluginmanager_spec_helper.rb
qa/integration/specs/cli/remove_spec.rb
qa/integration/specs/cli/update_spec.rb

From #17203:
>  - FIX: The plugin manager now correctly cleans up plugins and gem dependencies that are no longer needed after invoking `install`, `remove`, or `update`.
>  - FIX: The plugin manager's `update` command no longer fails to upgrade plugins that were initially installed with `--version` flag
Combined clean backports of #17203 and #17267 to 8.x
#17203 includes a regression to the behavior of `bin/logstash-plugin install`'s `--preserve` flag, which was addressed in #17267.
>   - For users who update, install, or remove plugins, cleaning out deactivated dependencies can reduce the disk footprint of the logstash installation
>   - For building Logstash artifacts, this allows us to build a true subset of the dependency graph after removing plugins that are not needed in a …

Backport 17203 and 17267 8.x

---

lib/pluginmanager/command.rb
lib/pluginmanager/gemfile.rb
lib/pluginmanager/install.rb
lib/pluginmanager/remove.rb
lib/pluginmanager/update.rb
qa/integration/fixtures/update_spec.yml
qa/integration/services/logstash_service.rb
qa/integration/specs/cli/install_spec.rb
qa/integration/specs/cli/pluginmanager_spec_helper.rb
qa/integration/specs/cli/remove_spec.rb
qa/integration/specs/cli/update_spec.rb

From #17203:
>  - FIX: The plugin manager now correctly cleans up plugins and gem dependencies that are no longer needed after invoking `install`, `remove`, or `update`.
>  - FIX: The plugin manager's `update` command no longer fails to upgrade plugins that were initially installed with `--version` flag
Combined clean backports of #17203 and #17267 to 9.0
#17203 includes a regression to the behavior of `bin/logstash-plugin install`'s `--preserve` flag, which was addressed in #17267.
>   - For users who update, install, or remove plugins, cleaning out deactivated dependencies can reduce the disk footprint of the logstash installation
>   - For building Logstash artifacts, this allows us to build a true subset of the dependency graph after removing plugins that are not needed in a …

Backport 17203 and 17267 9.0

---

lib/pluginmanager/command.rb
lib/pluginmanager/gemfile.rb
lib/pluginmanager/install.rb
lib/pluginmanager/remove.rb
lib/pluginmanager/update.rb
qa/integration/fixtures/update_spec.yml
qa/integration/services/logstash_service.rb
qa/integration/specs/cli/install_spec.rb
qa/integration/specs/cli/pluginmanager_spec_helper.rb
qa/integration/specs/cli/remove_spec.rb
qa/integration/specs/cli/update_spec.rb

From #17203:
>  - FIX: The plugin manager now correctly cleans up plugins and gem dependencies that are no longer needed after invoking `install`, `remove`, or `update`.
>  - FIX: The plugin manager's `update` command no longer fails to upgrade plugins that were initially installed with `--version` flag
Combined backports of #17203 and #17267 to `feature/fedramp-high-8.x`
#17203 includes a regression to the behavior of `bin/logstash-plugin install`'s `--preserve` flag, which was addressed in #17267.
CONFLICTS: `:skip_fips` flags were added
>   - For users who update, install, or remove plugins, cleaning out deactivated dependencies can reduce the disk footprint of the logstash installation
>   - For building Logstash artifacts, this allows us to build a true subset of the dependency graph …

Backport 17203 and 17267 fedramp8x

---

.mergify.yml

This commit removes the automatic creation of the `backport-8.x` label on any commit

Remove automatic `backport-8.x` label creation

---

.buildkite/pull_request_pipeline.yml
x-pack/ci/integration_tests.sh
x-pack/ci/unit_tests.sh

[rn:skip]
Add automated x-pack tests for LS configured in FIPS mode. 
N/A: CI addition
- https://github.com/elastic/ingest-dev/issues/5047

Run x-pack tests with FIPS configuration

---

build.gradle
docker/Makefile
docker/templates/Dockerfile.erb
rakelib/artifacts.rake
rakelib/plugin.rake
x-pack/distributions/internal/observabilitySRE/plugin-allow-list.txt

[rn:skip]
- Adds various `observabilitySRE` rake, make, and gradle tasks for creating docker artifacts
- Includes rejection-point for filtering out files, and an injection-point for adding files to the tarball.
- Fairly significant delta from how this patch would apply to main since main has a major refactor -> https://github.com/elastic/logstash/pull/16599/files
~~~
./gradlew --stacktrace artifactDockerObservabilitySRE
~~~
NOTE: until https://github.com/elastic/logstash/pull/17271 is merged, the docker image will include the files …

observabilitySRE: docker rake tasks

---

docker/Makefile

[rn:skip]
The `build-from-local-observability-sre-artifacts` task depends on the `env2yaml` task. This was easy to miss in local development if other images had been built. This commit updates the makefile to properly define that dependency.
N/A
- Discovered in https://github.com/elastic/logstash/pull/17298 while trying to build image on fresh VM
- Relates to https://github.com/elastic/logstash/pull/17272

Ensure env2yaml dep is properly expressed in observabilitySRE task

---

Gemfile.template
logstash-core/logstash-core.gemspec
logstash-core/spec/logstash/webserver_spec.rb
qa/integration/specs/dlq_spec.rb
x-pack/qa/integration/management/multiple_pipelines_spec.rb
x-pack/qa/integration/monitoring/es_documents_structure_validation_spec.rb
x-pack/qa/integration/support/helpers.rb
x-pack/qa/integration/support/shared_examples.rb

[rn:skip]
Upgrades es-ruby client, especially moves to new elastic-transport ruby client.
Also check the plugins which use older elasticsearch-transport client
- https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/223
- https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/191
Exhaustive CI run :running: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1496
No user impact
- 7.x ES client: https://github.com/elastic/elasticsearch-ruby/tree/7.17/elasticsearch-transport
- 8.x+: https://github.com/elastic/elastic-transport-ruby
- Note: no breaking changes, mostly …

Upgrade elasticsearch-ruby client.

---

rakelib/artifacts.rake

[rn:skip]
The https://github.com/elastic/logstash/pull/17310 PR changed the rake task for artifact creation to use shellwords from standard library. The acceptance tests need to explitily load that library. This commit updates the rake file to handle loading the required code.
failing cell https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1515#01959199-086d-4bb5-8922-161dc535f3e0
```
2025-03-13 16:10:03 PDT | [docker] Building docker image
-- | --
  | 2025-03-13 16:10:03 PDT | rake aborted!
  | 2025-03-13 16:10:04 PDT | NameError: uninitialized constant Shellwords
  | 2025-03-13 16:10:04 PDT | /opt/buildkite-agent/builds/bk-agent-prod-gcp-1741906760078483547/elastic/logstash-exhaustive-tests-pipeline/rakelib/artifacts.rake:143:in `block in safe_system'
  | 2025-03-13 …
```

Require shellwords in artifact rake task

---

docker/templates/Dockerfile.erb

[rn:skip]
This commit establishes a pattern for configuring the container to run in fips mode.
- Use chainguard-fips
- Copy over java properties from ls tar archive
- Convert default jks to BC keystore
- Configure logstash to use java properties and FIPS config
NOTE: this assumes bouncycastle jars are in the tarball. The
https://github.com/elastic/ingest-dev/issues/5049 ticket will address that.
- Closes  https://github.com/elastic/ingest-dev/issues/5050

Configure observability SRE container for FIPS

---

docs/static/spec/openapi/logstash-api.yaml

Migrate API doc to OpenAPI spec
- break down the share part to components
- add the missing fields for Plugins info, Node stats, Node Info, Hot threads and Health report
- expand Node Info `/_node/<types>` to `/_node/jvm`, `/_node/pipelines` and `/_node/os`
- expand Node Stats to `/_node/stats`, `/_node/stats/pipelines`, `/_node/stats/pipelines/{pipeline_name}`, `/_node/stats/jvm`, `/_node/stats/flow`, `/_node/stats/events`, `/_node/stats/process`, `/_node/stats/reloads`
- CLoses: https://github.com/elastic/logstash/issues/16967

[Doc] OpenAPI spec

---

docs/static/spec/openapi/logstash-api.yaml

Update intro content to align with left nav order in [published API docs](https://www.elastic.co/docs/api/doc/logstash/): 
- Health report.
- Hot threads.
- Logstash node info, like pipeline settings, OS info, and JVM info.
- Node stats, like JVM stats, process stats, event-related stats, and pipeline runtime stats.
- Plugins info, including a list of installed plugins.|

Doc: Update intro to match TOC order in API docs

---

docs/reference/monitoring-internal-collection-legacy.md

[rn:skip]
Adds new param (`xpack.monitoring.allow_legacy_collection: true`) introduced in 9.0 stack for internal collection.
Most users copy and paste the sources provided. If they copy current code example for 9.0, they will face an error says to include `allow_legacy_collection`. So, this PR reduces the path to successfully run internal monitoring in 9.0 stack.
-

Internal collection doc update to reflect enabling legacy collection.

---

.buildkite/scripts/common/qualified-version.sh
.buildkite/scripts/dra/build_docker.sh
.buildkite/scripts/dra/build_packages.sh
.buildkite/scripts/dra/common.sh
.buildkite/scripts/dra/publish.sh

[rn: skip]
Adds a shareable script for buildkite to get a fully-qualified version, including:
- the base version from `${LOGSTASH_HOME}/versions.yml`
- the qualifier from optional `VERSION_QUALIFIER` environment variable
- the `SNAPSHOT` tag from either `WORKFLOW_TYPE` or `RELEASE` environment variables
In https://github.com/elastic/logstash/pull/17298 we are adding tasks to smoke-test built artifacts, so we need the qualified version. Instead of duplicating the logic yet again, I extracted it to a share-able helper. I plan to backport this and reuse it elsewhere.
- ~~[ ] I have added tests that prove my fix is …

add ci shared qualified-version script

---

logstash-core/build.gradle
logstash-core/src/main/java/org/logstash/common/Util.java
logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
logstash-core/src/main/java/org/logstash/util/EscapeHandler.java
tools/benchmark-cli/build.gradle

Rationalize the usage internal hashing method and default to SHA-256
Removes the usage fo Apache Commons Codec  MessgeDigest to use internal Util class with embodies hashing methods.
N/A
Use the automatic reload config as in guide https://www.elastic.co/guide/en/logstash/current/reloading-config.html, update the pipeline definition and notice in the logs that's reloaded.
- Closes #17330

Use org.logstash.common.Util to hashing by default to SHA256

---

rakelib/artifacts.rake

[rn:skip]
Excludes the `logstash-plugin` and `logstash-keystore` entrypoints from the observabilitySRE artifact
These entrypoints cannot be invoked in a FIPS-compliant manner, so they are being excluded until a separate effort can make them so.

Exclude plugin manager and keystore cli from observabilitySRE artifact

---

.buildkite/pull_request_pipeline.yml
ci/run-fips-integration-tests.sh
logstash-core/build.gradle
rubyUtils.gradle
x-pack/ci/integration_tests.sh
x-pack/ci/unit_tests.sh
x-pack/distributions/internal/observabilitySRE/build-ext.gradle
x-pack/distributions/internal/observabilitySRE/docker/Dockerfile

[rn:skip]
This commit implements a pattern for performing specific gradle tasks based on a newly named "fedrampHighMode" option. This option is used to configure tests to run with additional configuration specific to the observabilitySRE use case. Similarly the additional jar dependencies for bouncycastle fips providers are conditionally installed gated on the "fedrampHighMode" option.
N/A
- Closes https://github.com/elastic/ingest-dev/issues/5248

Conditionally install bcfips jars when building/testing observabilitySRE

---

docs/reference/secure-connection.md

Replace removed Elasticsearch output SSL settings with the latest values

[Doc] Fix Elasticsearch output SSL settings

---

logstash-core/build.gradle
logstash-core/src/main/java/org/logstash/util/JavaVersion.java
logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java

[rn:skip]
Updates only test code to be able to run a test that consumes big memory if:
- the physical memory is bigger than the requested Java heap
- JDK version is greater than or equal to 21.
The reason to limit the JDK version is that on 16GB machine the G1GC is more efficient than the one on previous JDKs and so let complete the test with 10GB heap, while in JDK 17 it consistently fails with OOM error.
N/A
- failing exhaustive: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1564
- success exhaustive: ~~https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1569~~ …

Limit memory consumption in test on overflow

---

Gemfile.template

[rn:skip]z
The rubocop-ast gem just introduced a new dependency on prism.
- https://rubygems.org/gems/rubocop-ast/versions/1.43.0
In our install default gem rake task we are seeing issues trying to build native extensions. I see that in upstream jruby they are seeing a similar problem (at least it is the same failure mode https://github.com/jruby/jruby/pull/8415
This commit pins rubocop-ast to 1.42.0 which is the last version that did not have an explicit prism dependency.
NA
- https://github.com/jruby/jruby/pull/8415
- …

Pin rubocop-ast development gem due to new dep on prism

---

rakelib/artifacts.rake

[rn:skip]
Adds `logstash-filter-age` to internal observaibilitySRE artifact
The observaibilitySRE artifact will initially not have the plugin manager entrypoints, so we need to install this filter before packaging.
~~~
./gradlew bootstrap artifactDockerObservabilitySRE -PfedrampHighMode=true
~~~
Observe:
~~~
[plugin:install] Installing plugin: logstash-filter-age
Installing logstash-filter-age
Installation successful
~~~
Observe that it is still present in the …

Add age filter fedramp

---

.buildkite/pull_request_pipeline.yml
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/org.bouncycastle!bc-fips-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/org.bouncycastle!bcpkix-fips-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/org.bouncycastle!bctls-fips-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/org.bouncycastle!bcutil-fips-NOTICE.txt

[rn:skip]
This commit adds licences for bouncycastle jars that are added for the observability SRE container artifact. It re-enables the previously disabled license check and adds a new one running in fips mode.
N/A
- Closes https://github.com/elastic/ingest-dev/issues/5295

Add licenses for bouncycastle fips jars

---

.buildkite/scripts/jdk-matrix-tests/generate-steps.py

BK test https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/401

Minor, added missed bracket

---

docs/release-notes/breaking-changes.md

Breaking changes document for `9.0`, 
Closes: #16722

Breaking changes for 9.0

---

docs/reference/dashboard-monitoring-with-elastic-agent.md
docs/reference/monitoring-with-elastic-agent.md
docs/reference/serverless-monitoring-with-elastic-agent.md

[rn:skip]
Removes the tech preview from the agent driven LS monitoring pages.
This feature is GAed and corresponding pages need to be updated not to confuse users.
-

Remove tech preview from agent driven LS monitoring pages.

---

Gemfile.template

Jruby 9.4.9.0 or the latest 9.4.12.0 come with cgi 0.3.6. This commit pins cgi to 0.3.7

Update cgi to 0.3.7

---

docs/static/monitoring/monitoring-ea-dashboards.asciidoc
docs/static/monitoring/monitoring-ea-serverless.asciidoc
docs/static/monitoring/monitoring-ea.asciidoc
docs/static/monitoring/monitoring-view.asciidoc

[rn:skip]
Removes technical preview label from the agent driven monitoring pages.
Agent driven monitoring was GAed and this change updates the pages to deliver upto date info.
-

[8.x] Remove technical preview from agent driven monitoring pages.

---

Gemfile.template

Jruby 9.4.9.0 or the latest 9.4.12.0 come with uri 0.12.2 This commit pins uri to 0.12.3

Update uri gem required by Logstash

---

docs/reference/event-dependent-configuration.md

Related: #17322
Pulls ["field reference deep dive"](https://www.elastic.co/guide/en/logstash/current/field-references-deepdive.html) content into [Field Reference](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#logstash-config-field-references) topic.

Doc: Incorporate field ref deep dive content

---

.buildkite/pull_request_pipeline.yml
.buildkite/scripts/common/qualified-version.sh
.buildkite/scripts/dra/build-and-push-observability-sre.sh
.buildkite/scripts/dra/generatesteps.py
.buildkite/scripts/dra/multi-architecture-observability-sre.sh

[rn:skip]
Add pipelines for building and shipping the observability SRE image. Specifically this adds a step to the DRA pipeline that largely follows the existing patterns and steps for doing artifact publishing. The noteable difference is that currently we directly do a docker build and docker push workflow instead of the existing build/staging workflow with the release manager. A design goal for this iteration is to ensure that this new step does not interfere with any existing DRA steps. As such we ensure this happens after DRA is published and that failures are marked with a soft_fail option so as to not interrupt any artifact publishing while we stabilize and iterate on this workflow. 
N/A
- ~[ ] I have added tests that …

Publish Observability SRE images to internal container registry

---

docs/reference/dashboard-monitoring-with-elastic-agent.md
docs/reference/monitoring-with-elastic-agent.md
docs/reference/monitoring-with-metricbeat.md
docs/reference/serverless-monitoring-with-elastic-agent.md

[rn:skip]
Recommends collecting metricsets to fully visualize metrics on dashboards, as disabling some of metricsets may cause dashboards partially display some metrics.
No impact.
- https://github.com/elastic/logstash/issues/17477

[Monitoring LS] Recommends collecting metricsets to fully visualize metrics on dashboards.

---

qa/integration/services/elasticsearch_setup.sh

[rn:skip]
With a recent change in ES https://github.com/elastic/elasticsearch/pull/125449
configuring path.data or path.logs to directories that do not exist cause ES to
not be able to start up. This commit ensures those directories exist. The
teardown script already ensures they are removed https://github.com/elastic/logstash/blob/712b37e1df333e8d156cb5d26fbc24aafcbfd2cd/qa/integration/services/elasticsearch_teardown.sh#L26-L27
N/A
- Commented on ES pr …

 Ensure elasticsearch logs and data dirs exist before startup

---

docs/docset.yml
docs/reference/docker.md
docs/reference/installing-logstash.md

Install docs were migrated with unreleased config.
This work adds correct info. 
I pulled the content from pre-migration files, and compared the output to a similar page for a current release: https://www.elastic.co/guide/en/logstash/current/installing-logstash.html

Doc: Update installation info

---

.github/workflows/backport-active.yml
.mergify.yml

Adding new github workflow for creating backports to active branches.

New way of backporting to active branches using gh action

---

docs/reference/advanced-pipeline.md
docs/reference/dashboard-monitoring-with-elastic-agent.md
docs/reference/dead-letter-queues.md
docs/reference/deploying-scaling-logstash.md
docs/reference/first-event.md
docs/reference/logstash-centralized-pipeline-management.md
docs/reference/logstash-monitoring-ui.md
docs/reference/logstash-pipeline-viewer.md
docs/reference/monitoring-internal-collection-legacy.md
docs/reference/monitoring-with-elastic-agent.md
docs/reference/serverless-monitoring-with-elastic-agent.md
docs/reference/tuning-logstash.md

Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable. 
* Can you please add the appropriate labels needed for backporting?

[docs] Fix image paths for docs-assembler

---

catalog-info.yaml

[rn:skip]
The 8.x branch has been renamed 8.19. Reflect this in jdk test config.
N/A

Track 8.19 branch instead of 8.x for jdk compat tests

---

versions.yml

Fixes: https://github.com/elastic/logstash/issues/17590
CI failed: https://buildkite.com/elastic/logstash-jdk-availability-check-pipeline/builds/51#01965613-71ec-4c14-8b5a-cd12cb7c4ce7

upgrade jdk to 21.0.7+6

---

qa/rspec/commands/redhat.rb

[rn:skip]
We are seeing a frequent issue in CI where tests are failing to install via package manager on rhel8. It looks like the issue may be due to processes that are being terminated and leaving behind lock files on the rpm database. This commit udpates the install method to try to do a database rebuild routine which will force lock files to be removed. This fix assumes that at the time of testing, our tests should take priority over any package manager operation and we can prioritize our command over anything else that may be interacting with the package manager.
N/A
- ~[ ] I have added tests that prove my fix is …

Make redhat exhaustive test install command more robust

---

qa/docker/shared_examples/container_options.rb
qa/docker/shared_examples/xpack.rb
qa/docker/spec/spec_helper.rb

[rn:skip]
There appears to be a race condition in tests whereby log messages are not observed with a single interogation of the container logs. This commit adds a helper method to wait for log messages. This should make the tests more resilient when there is a delay in log messages being captured.
NA
```
➜  logstash git:(more-resilient-log-assertion) ✗ ci/docker_acceptance_tests.sh oss
```
Example failure:
https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1776#_
```
2025-04-23 23:45:53 PDT | Failures:
-- | --
  | 2025-04-23 23:45:53 PDT |  
  | 2025-04-23 23:45:53 PDT | 1) A container running the oss …
```

Add helper method to wait for log message to be observed

---

ci/serverless/README.md
ci/serverless/metricbeat_monitoring_tests.sh

update metricbeat `.monitoring-logstash-8-mb` to `.monitoring-logstash-9-mb`
wait until [[1]](https://github.com/elastic/beats/pull/42823), [[2]](https://github.com/elastic/elasticsearch/pull/123106) get merged

[CI] update serverless test index

---

.github/workflows/gen_release_notes.yml
tools/release/generate_release_notes.rb
tools/release/generate_release_notes_asciidoc.rb

This commit adds support for generating release notes in markdown format.
The existing script moves to `generate_release_notes_asciidoc.rb` to support asciidoc.
The workflow generates asciidoc format for major version smaller than 9, 
otherwise, uses MD
Fixes: #16853

[chore] Update release notes generator tool

---

tools/release/generate_release_notes_md.rb

This commit fixes markdown release notes url generation
Fixes: https://github.com/elastic/logstash/issues/16853

[chore] fix release note url generation

---

docs/release-notes/index.md

- forward port https://github.com/elastic/logstash/pull/17620 to main for 9.0.1 release. The doc only publish change from `main`, not `9.0` branch
- update ID format from `-901-` to `-9.0.1-` as per [new doc release requirement](https://github.com/elastic/docs-content/issues/1152)

Release notes for 9.0.1 (#17620)

---

tools/release/generate_release_notes_md.rb

The new release procedure requires the ID format of release version as `-9.0.1-` instead of `-901-`.
This commit updates release note generation tool.
Relates: https://github.com/elastic/docs-content/issues/1152

[chore] update ID format of release notes tool

---

docs/release-notes/index.md

Release notes for 9.0.1 updated to main branch.
@karenzone : I'm not totally sure if this is the right branch for this release notes in docs V3, and how to publish this after the change is made.

release notes 9.0.1 updated with security advisor

---

docs/static/releasenotes.asciidoc

Release notes updated.
@karenzone : In this case I've added the message in the release notes asciidoc file for both 8.18.1 and 8.17.6, as the file include both.
Let me know if this is correct. Thanks!

security advisory message added to 8.18.1 release notes

---

docs/reference/using-logstash-with-elastic-integrations.md

[rn:skip]
This PR fixes a typo in https://www.elastic.co/docs/reference/logstash/using-logstash-with-elastic-integrations
- Closes [#1395](https://github.com/elastic/docs-content/issues/1395)

Fix typo in Logstash docs

---

x-pack/distributions/internal/observabilitySRE/qa/smoke/docker/docker-compose.yml

[rn:skip]
The ES team has started publishing a purpose built image for the fedramp high project. Update our smoke test stack to use this container.
N/A

Use dedicated elasticsearch image for observabilitySRE smoke testing

---

.buildkite/pull_request_pipeline.yml
x-pack/build.gradle
x-pack/distributions/internal/observabilitySRE/qa/smoke/docker/logstash/pipeline/logstash.conf

[rn:skip]
Some code review comments from https://github.com/elastic/logstash/pull/17486 were committed via the github UI but when locally rebased they were excluded due to a missed sync. This PR restores them. 
N/A
- Relates to https://github.com/elastic/logstash/pull/17486

Restore code review changes

---

Gemfile.template
logstash-core/lib/logstash/agent.rb
rakelib/artifacts.rake

[rn:skip]
Avoid hard pins on gem versions in the Gemfile.template and remove some duplicated gems which are already vendored to an upper version

Fixes to the bundles gems and jars versions

---

logstash-core/logstash-core.gemspec

backport of https://github.com/elastic/logstash/pull/17646

[8.17] update jruby-openssl to 0.15.4

---

.github/workflows/docs-build.yml

Ensures that the docs are built for version branches ([see docs](https://docs-v3-preview.elastic.dev/elastic/docs-builder/tree/main/migration/versioning#ci-configuration)), which is needed to start onboarding `9.0` to the documentation build.

Docs: Ensure docs are built for version branches

---

Gemfile.jruby-3.1.lock.release
versions.yml

Do not merge it before releasing `8.18.3`

Bump to 8.18.4 version

---

Gemfile.jruby-3.1.lock.release

9.1 was cut from main and is now ready for managing the lockfile in source.
NOTE: this file was generated with:
```
git checkout upstream/8.19
./gradlew clean installDefaultGems
./vendor/jruby/bin/jruby -S bundle update --all --patch --strict
cp  Gemfile.lock Gemfile.jruby-3.1.lock.release
```

Add lockfile for newly created 9.1 branch

---

.mergify.yml

Update mergify data to add the newly created 9.1 branch

 Update mergify with new 9.1 branch

---

config/logstash.yml

This commit fixes the comment of `allow_superuser` in `logstash.yml`.
The default value should be `false`.
relates: https://github.com/elastic/logstash/pull/16558

Fix allow_superuser comment

---

.buildkite/scripts/exhaustive-tests/generate-steps.py
rakelib/plugin.rake

This commit removes the UBI acceptance test. 
The default base image is UBI. Full flavour test has covered UBI flavour
Fixes: #17830
~This commit removes the unwanted warning which pollutes the plugins list~
~[installed_plugins](https://github.com/elastic/logstash/blob/main/rakelib/plugin.rake#L118) is polluted with  ["pass JVM parameters via LS_JAVA_OPTS", "logstash-codec-avro", "logstash-codec-cef", ... ]~

[CI] Remove UBI docker acceptance test

---

docs/docset.yml
docs/reference/docker.md
docs/reference/first-event.md
docs/reference/installing-logstash.md
docs/reference/running-logstash-command-line.md
docs/reference/working-with-plugins.md

Related to https://github.com/elastic/docs-projects/issues/519
Update the docs to use centrally-managed [version variables](https://elastic.github.io/docs-builder/syntax/version-variables/) from docs-builder's [`version.yml` configuration file](https://github.com/elastic/docs-builder/blob/main/config/versions.yml). The Docs team is responsible for updating these version numbers for each release. These version variables will replace `docset`-level version-related `subs` so we don't have to update those values in this repo for every release.

[docs] Use centrally maintained version variables

---

.github/workflows/critical_vulnerability_scan.yml

This commit updates the grype action to log what components it is scanning (including any that are critical which will cause the action to fail). Previously the default sarif file was generated and nothing was logged. Without this commit it is impossible to tell from a failed action *what* is causing the failure.
See https://github.com/anchore/scan-action?tab=readme-ov-file#action-inputs which indicates this option should do what we want.

Log *what* components trigger a grype scan

---

docs/static/releasenotes.asciidoc

I think we are missing a blank line to fix this rendering problem:
cc: @andsel & @jsvd

8.19 release notes rendering fix

---

logstash-core/lib/logstash/java_pipeline.rb

- Improves logging while handling exceptions in the pipeline, ensuring that chained exceptions propagate enough information to be actionable.
Adds a helper to normalize an exception _and its cause chain_ for logging, and uses that helper to add context whenever logging an exception from the pipeline implementation
Often an exception is caught and a _wrapper_ of that exception is re-thrown; logging only the outermost exception can make it difficult to chase down the root cause.
Before:
Log entries context contains:
- `error`: a string …

pipeline logging: add cause chain when logging

---

build.gradle

[rn: skip]
Updates the source/target java for the main project to Java 17
No _user_ impact; we already enforce Java17 as a runtime minimum via the JVM Options Parser, which is still compiled with a source/target of Java11.
For _developers_, this will allow us to use features from Java 17.
- build it
- try to run it with Java 17, and observe that it works
- set LS_JAVA_HOME to Java 11, and observe the _same_ clear refusal to run

Update source/target to Java17

---

docker/templates/Dockerfile.erb
x-pack/distributions/internal/observabilitySRE/config/fips-jvm.options

[rn:skip]
In addition to setting `LS_JAVA_OPTS` we now include the fips config java options in the `/usr/share/logstash/config/jvm.options` file. This ensures that if consumers of the image overwrite `LS_JAVA_OPTS` the fips config is still respected from `jvm.options`.
- https://github.com/elastic/ingest-dev/issues/5972

Add fips config to jvm.options for observabilitySRE

---

Gemfile.jruby-3.1.lock.release
versions.yml

Update patch version for logstash 9.1.3 
Merge after 9.1.2 release.

Bump logstash to 9.1.3

---

.buildkite/scripts/exhaustive-tests/generate-steps.py

[rn:skip]
Previously the package based tests would be blocked on the pull request suite. Given those tests MUST have be run to even get code in to a branch this results in the exhaustive test suite taking roughly 30 mins to even start the unique tests. In practice when we want to reproduce or test a failure in the exhaustive suite we DONT want to be blocked on seeing the PR tests. This commit removes the depends-on condition for the package based tests on the pull request tests. It does not seem like any protection from doing unncessary package based tests if a pull request test fails is worth the extra wall time in practice. This should significantly decrease the total time needed for the exhaustive test pipeline.
- https://github.com/elastic/ingest-dev/issues/5579

Start all exhastive tests in parallel

---

logstash-core/src/main/java/org/logstash/settings/SettingInteger.java
logstash-core/src/test/java/org/logstash/settings/SettingIntegerTest.java

[rn:skip] 
Recently https://github.com/elastic/logstash/pull/17460 the implementation for integer/postive integer settings was moved from jruby to pure java. The ruby implementation was leinient with whitespace in string values. This commit updates the java implementation to replicate this by stripping whitespace from string values before trying to parse them as int.

Preserve coerce behavior from Ruby Integer/PositiveInteger Settings impl

---

.buildkite/scripts/health-report-tests/bootstrap.py

[rn:skip]
Places back the full start requirement flag `full_start_required` which can be controlled by a driver. For the scenarios such as slow start this can be not required as it needs to confirm pipeline start taking longer. And for other backpressure test cases it is required to check full pipeline start
N/A
-

[health-report ci] Put back the full start requirement.

---

docs/static/spec/openapi/logstash-api.yaml

This PR updates the OpenAPI spec to add the x-metatags extension. This extension adds product_name metadata which during docs build time is converted to a meta tag on the HTML page, this tag is then parsed by our internal site search to add the API docs pages to the product facets on search.
This allows users to filter their search by logstash and only see logstash apis
-

adding x-metatags to openapi spec

---

docs/static/spec/openapi/logstash-api.yaml
docs/static/spec/openapi/redocly.yaml

[rn:skip] 
This PR addresses the following linting errors reported 
```
[1] redocly.yaml:29:3 at #/rules/path-excludes-patterns
Property `path-excludes-patterns` is not expected here.
27 | no-ambiguous-paths: warn
28 | no-identical-paths: error
29 | path-excludes-patterns:
30 |   severity: error
31 |   patterns:
Warning was generated by the configuration struct rule.
[2] redocly.yaml:37:3 at #/rules/spec
Property `spec` is not expected here.
35 |  operation-2xx-response: off
36 | # Schema
37 |  spec: off
38 |  spec-strict-refs: off
39 | # Tags
Warning was generated by the configuration struct rule.
...
[2] logstash-api.yaml:2267:15 at #/components/schemas/PipelineReloadStats/properties/reloads/properties/last_error/nullable
Property `nullable` is not expected here.
2265 | last_error:
2266 …
```

[DOCS] Fix nullable type linting error in OpenAPI document

---

.buildkite/pull_request_pipeline.yml

The junit annotation previously would wait for EVERY step to finish before running. It takes a non trivial amount of time and was consistenly adding several minute to the total run time. The only artifacts it annotates are emmited by the java unit tests. This commit updates the buildkite manifest to properly define that relationship such that it will start as soon as the java tests step is done instead of waiting for ALL steps.
Relates to https://github.com/elastic/ingest-dev/issues/5579

Stop waiting on ALL steps before staring junit annotation

---

Gemfile.jruby-3.1.lock.release
versions.yml

[rn:skip] 
Bumps version to 9.0.7

Bump to 9.0.7

---

.buildkite/scripts/dra/generatesteps.py

Previously as the pipeline for publishing observabilitySRE artifacts was being developed that part of the pipeline only executed after the rest of the DRA artifacts had been prepared. This sacrificed build time for ensuring that failures did not disrupt the rest of the DRA process. Now that the workflow has been stabilized it is no longer necessary to wait. This commit removes the deps for the DRA build to complete before starting the observabilitySRE artifact creation. This should decrease the total time for the DRA pipeline to complete.

Start observabilitySRE container builds immediately on DRA

---

.buildkite/pull_request_pipeline.yml
.buildkite/scripts/dra/generatesteps.py
rakelib/artifacts.rake

[rn:skip]
Previously when doing platform specific builds (x86_64, arm) BOTH sets of artifacts were produced regarless of host. This increases CI run times and is needless resource consumption. This commit makes the rake tasks compile artifacts for only the host arch it is being run on.
N/A
- https://github.com/elastic/ingest-dev/issues/5994
- https://github.com/elastic/ingest-dev/issues/5579

Build artifacts only for those that match host arch

---

docs/reference/configuring-geoip-database-management.md

Contributes to https://github.com/elastic/docs-content/issues/1734, https://github.com/elastic/docs-content/issues/1801
Replaces placeholder URLs with those reserved by the Internet Engineering Task Force (IETF) in RFC 2606 and RFC 6761 (e.g. `example.com`, `example.net`, `example.org`, `example.edu`,  `.example`).

[docs] Replace placeholder URLs

---

.mergify.yml

[rn:skip]
This change is part of https://github.com/elastic/docs-builder/issues/1433.
In order to make the porting of documentation changes to `main` more straightforward, a new rule specific to changes inside the `docs` folder is being added.
Documentation writers will have a smoother workflow with automated forwardporting, and code owners can then decide whether to merge the changes or not.

Add Mergify rule for forwardporting documentation changes

---

docker/templates/Dockerfile.erb
docker/templates/IronbankDockerfile.erb

Exhaustive test suite: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/2405/steps/canvas

upgrade golang to 1.25

---

logstash-core/lib/logstash/config/pipelines_info.rb

A fix to receive gauge metric types in pipeline info which appears in pipeline vertex of node stats API.
- pull this change and build Logstash
- Use elastic-agent input plugin (whose [`current_connections`](https://github.com/logstash-plugins/logstash-input-beats/blob/main/lib/logstash/inputs/beats/message_listener.rb#L208) and [`peak_connections`](https://github.com/logstash-plugins/logstash-input-beats/blob/main/lib/logstash/inputs/beats/message_listener.rb#L …

Fix gauge type correctly where requesting pipeline metrics in condition.

---

docs/reference/lookup-enrichment.md

Closes: https://github.com/elastic/docs-content/issues/2782

Doc: Provide accurate post-geoip lookup example

---

rakelib/artifacts.rake

Improvement to logstash release artifacts file metadata: mtime is preserved when buiilding tar archives 
When building tar archives, explicitly set mtime. This avoids losing that information in the minitar `Writer.add_file_simple` method
https://github.com/halostatue/minitar/blob/a531136b17b9efdddf0a0f39537845b454c2371e/lib/minitar/writer.rb#L139
Files containing mtime 0 lead to undesireable behavior in some use cases https://github.com/elastic/logstash/issues/17925 and do not show any clues to modification time. Avoiding setting mtime to 0 in many cases will help provide artifacts with the least amount of surprise to users. 
- https://github.com/elastic/logstash/issues/17925
- https://github.com/elastic/sdh-logstash/issues/1695

Preserve mtime explicitly when creating tar artifacts

---

rakelib/artifacts.rake

Following up on https://github.com/elastic/logstash/pull/18091, when minitar writes a directory or symlink it also needs explicit mtime. After inspecting artifacts built from #18019 we see some other missing mtimes. This commit ensures that information is explicitly passed to the minitar writer.

Ensure any file object in a tar archive has an mtime

---

logstash-core/src/main/java/org/logstash/ObjectMappers.java
logstash-core/src/test/java/org/logstash/EventTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
logstash-core/src/test/resources/org/logstash/stringref-disabled.annotated-cbor.txt
logstash-core/src/test/resources/org/logstash/stringref-enabled.annotated-cbor.txt

- Persisted Queue: improved serialization to be more compact by default
When serializing a non-primitive value, CBOR encodes a two-element tuple containing the class name and the class-specific serialized value, which results in a significant amount of overhead in the form of frequently-repeated strings.
Jackson CBOR supports the [stringref][] extension, which allows it to avoid repeating the actual bytes of a string, and instead keeps track of the strings it has encountered and _referencing_ those strings by the index in which they occur.
For example, the first `org.jruby.RubyString` looks like:
~~~
74                                            # text(20)
6f72672e6a727562792e52756279537472696e67   #   "org.jruby.RubyString"
~~~
While each subsequent string looks like:
~~~
d8 19 …

pq: activate stringref extension for more-compact PQ representation

---

logstash-core/src/test/java/org/logstash/EventTest.java
logstash-core/src/test/resources/org/logstash/stringref-disabled.annotated-cbor.txt
logstash-core/src/test/resources/org/logstash/stringref-enabled.annotated-cbor.txt

[rn: skip]
Adds tests to prove that enabling the CBOR stringref extension in https://github.com/elastic/logstash/pull/17849 does not create a rollback barrier.
We want to ensure that a user who has begun using LS 9.x (in which we plan to activate the CBOR stringref extension) can safely roll back to LS 9.1, even if stringref-enabled events are left behind in the PQ.
- Dependency of: https://github.com/elastic/logstash/pull/17849 (tests must pass on 9.1 without modification of code)

compat: add test for deserializing stringref enabled and disabled

---

Gemfile.template
versions.yml

https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/2423/steps/canvas
```
projects/jruby ❯ git diff --color=always --minimal --unified=0 -w 9.4.13.0..9.4.14.0 lib/pom.rb | grep --color=never -E "\['.+?',.+?'\],?"
```
```diff
-    ['cgi', '0.3.6'],
+  ['cgi', '0.3.7'],
-    ['strscan', '3.1.0'],
+  ['strscan', '3.1.5'],
-    ['uri', '0.12.3'],
+  ['uri', '0.12.4'],
-    ['yaml', '0.2.0'],
+  ['yaml', '0.2.0']
-    ['net-smtp', '0.3.1'],
+  ['net-smtp', '0.3.1.1'],
-    ['rss', '0.2.9'],
-    ['test-unit', '3.5.3'],
+  ['rss', '0.3.1'],
+  ['test-unit', '3.5.3']
```

Update JRuby version to 9.4.14.0

---

docs/static/jvm.asciidoc

Update Java version requirements and default
Related: https://github.com/elastic/logstash/issues/16608
**PREVIEWS:**
- https://logstash_bk_18129.docs-preview.app.elstc.co/guide/en/logstash/8.18/getting-started-with-logstash.html#ls-jvm
- https://logstash_bk_18129.docs-preview.app.elstc.co/guide/en/logstash/8.18/getting-started-with-logstash.html#jdk-upgrade

Doc: Update Java version requirements for 8.18

---

.github/workflows/version_bumps.yml

When handling multiple releases on the same schedule it is common to kick off this action across multiple branches. Using *only* the time for a branch name to create a PR for to update lock file results in a race condition where a target branch can conflict. In order to fix this we now include the target branch (logstash stream) in the branch name to raise the PR from.

Fix race condition with version bump action

---

docs/reference/connecting-to-serverless.md
docs/reference/toc.yml

Related: https://github.com/elastic/docs-content-internal/issues/176
Add page with details about sending Logstash output to Elasticsearch Serverless
**PREVIEW:** https://docs-v3-preview.elastic.dev/elastic/logstash/pull/18034/reference/connecting-to-serverless

Doc: Add Logstash-to-serverless page

---

docs/static/spec/openapi/logstash-api.yaml

[rn:skip] 
Adds required `type` for open API spec in logstash-yaml.
N.A
- Closes #18022

Adds a required type tag to the open API spec of Logstash APIs.

---

logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb
logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb
logstash-core/spec/logstash/util/wrapped_acked_queue_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/QueueFactoryExt.java
logstash-core/src/main/java/org/logstash/ackedqueue/Settings.java
logstash-core/src/main/java/org/logstash/ackedqueue/SettingsImpl.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java

[rn: skip]
This is an internal no-net-change refactor to pull upward the use of the `org.logstash.ackedqueue.Settings` into the JRuby queue extension classes, pared off of the existing PR #18121.
There is no net change to the user.
The changes here underly code that is also going to need changes in @andsel 's current in-flight work. Paring it off as a separate PR unblocks his work.
No net change. Rely on existing test coverage and usage.
- Relates: #18121 
- Relates: #18000

PQ settings refactor: propagate builder upward

---

docs/static/modules.asciidoc
docs/static/settings/geoip-database-management-settings.asciidoc

Contributes to https://github.com/elastic/docs-content/issues/1734, https://github.com/elastic/docs-content/issues/1801
Replaces placeholder URLs with those reserved by the Internet Engineering Task Force (IETF) in RFC 2606 and RFC 6761 (e.g. `example.com`, `example.net`, `example.org`, `example.edu`,  `.example`).

Replace placeholder URLs

---

logstash-core/lib/logstash/api/commands/stats.rb
logstash-core/spec/logstash/api/modules/node_stats_spec.rb
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
logstash-core/src/main/java/org/logstash/execution/QueueReadClientBatchMetrics.java
logstash-core/src/main/java/org/logstash/instrument/metrics/MetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/MetricKeys.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/gauge/LazyDelegatingGauge.java
logstash-core/src/test/java/org/logstash/instrument/metrics/MockNamespacedMetric.java
qa/integration/specs/monitoring_api_spec.rb

Implements current batch event count and byte size metrics.
Introduce a new gauge metric to collect list of values, used a a couple, the first element count of events in the batch and the second one is the estimated memory occupation of the batch.
This list is later grabbed in the API layer to populate the two `current` values for `event_count` and `batch_size`.
Exposes the current batch size in terms of events and estimated memory consumption.
Start Logstash with `pipeline.batch.metrics.sampling_mode` set to `full` running an HTTP input pipeline, load it with `wrk` and verify that the metric API …

Measure current batch byte size and event count

---

docs/release-notes/index.md

Related: #18224 
We didn't get a clean backport because we have more backport work to catch up on.

Doc: Attribute fixes in release notes 9.1.0

---

logstash-core/lib/logstash/instrument/collector.rb
logstash-core/src/main/java/co/elastic/logstash/api/NamespacedMetric.java
logstash-core/src/main/java/co/elastic/logstash/api/UserMetric.java
logstash-core/src/main/java/org/logstash/instrument/metrics/AbstractNamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/AbstractSimpleMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/MetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/MetricType.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NullMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NullNamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/UserMetric.java
logstash-core/src/main/java/org/logstash/plugins/NamespacedMetricImpl.java
logstash-core/src/test/java/org/logstash/instrument/metrics/MetricTypeTest.java
logstash-core/src/test/java/org/logstash/instrument/metrics/MockNamespacedMetric.java
logstash-core/src/test/java/org/logstash/plugins/NamespacedMetricImplTest.java

[rn: skip]
Provides a way for registering non-standard metrics, without needing to wire them through publicly.
It does so by introducing an API `UserMetric<VALUE_TYPE>` marked as Logstash-internal, a companion `UserMetric.Factory<USER_METRIC>` to encapsulate the logic for its type and a null implementation, and introducing `NamespacedMetric#register(String metric, UserMetric.Factory<USER_METRIC> userMetricFactory)`.
Together, these methods and the wiring through to the metric collector allow anything with an `api.NamespacedMetric` to provide its own metric implementation.
This is necessary ground-work for #18107 which will add ratio and relative-spend metrics from within the Logstash code-base.
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env …

metrics: add support for user-defined metrics

---

.buildkite/scripts/dra/build_docker.sh
ci/docker_acceptance_tests.sh
docker/Makefile
rakelib/artifacts.rake

[rn:skip]
Previously we would build an image (which would not actually be used), build dockerfiles, modify dockerfiles to curl from
`https://snapshots.elastic.co/downloads/logstash'` then build the image used for testing based on the modified dockerfile. This resulted in testing the last published image to `snapshots`. This presents two problems 1. The test is running against the last published image (not the tip of the branch being tested) 2. this carries a dependency on both a DRA and unified stack release having been run. Therefor acceptance tests will fail in between the time we bump logstash version and a successful run of unified release.
For docker acceptance tests three steps were performed: 
1. Build container images (based on local artifacts) 
2. Build "public" dockerfiles 
3. …

Remove redundant testing and circular dependency from docker acceptance testing

---

Gemfile.jruby-3.1.lock.release

[rn:skip]
This commit vendors the 9.2.0 version of elastic_integration for the new 9.2 stream of logstash.

Take up 9.2 version of elastic_integration plugin

---

docs/reference/tips-best-practices.md

Fixes: #14422 
**PREVIEW:** https://docs-v3-preview.elastic.dev/elastic/logstash/pull/18271/reference/tips-best-practices#tip-check-field

Doc: Update docs for testing for boolean fields
