elastic/logstash

- docs/asciidoc/static/command-line-flags.asciidoc
- docs/asciidoc/static/configuration.asciidoc
- docs/asciidoc/static/example-add-a-new-filter.asciidoc
- docs/asciidoc/static/getting-started-with-logstash.asciidoc
- docs/asciidoc/static/life-of-an-event.asciidoc
- docs/index-codecs.asciidoc.erb
- docs/index-filters.asciidoc.erb
- docs/index-outputs.asciidoc.erb
Changes from my review of the Logstash docs. I fixed some bad links, did some light editing, and reorganized the config file topic a bit.
> Editing/cleanup pass through the Logstash docs.

- ci/ci_setup.sh
- logstash.gemspec
Simple fixes for:
* Having the ci reporter used in jenkins.
* Having coveralls and simplecov installed as development dependencies.
> Testing fixes

- README.md
> Add JAVA_HOME as an extra step for windows

- lib/logstash/java_integration.rb
- spec/core/event_spec.rb
- spec/filters/base_spec.rb
- spec/lib/logstash/java_integration_spec.rb
> add Java Collection delete support with specs & more java_integration specs

- lib/logstash/java_integration.rb
- spec/lib/logstash/java_integration_spec.rb
fixes logstash-plugins/logstash-filter-multiline#10
related to JRuby issue jruby/jruby#1249
> fix for Java 8 Map merge method conflict

- lib/logstash/pluginmanager/uninstall.rb
> bundler refactor leftover

- lib/logstash/pluginmanager/uninstall.rb
- lib/logstash/pluginmanager/update.rb
from @jsvd suggestion, remove all setup! and add :clean to uninstall
this replaces #3081 and #3079 
fixes #3075
> remove setup! and add :clean to uninstall

- Gemfile
- Gemfile.jruby-1.9.lock
- lib/logstash/version.rb
also catched logstash-input-s3 update.
> logstash-core v1.5.0

- docs/asciidoc/static/managing-multiline-events.asciidoc
http://multilion.divshot.io/multiline
> Adds new section on managing multiline events.

- lib/logstash/version.rb
- logstash-core.gemspec
Our versioning scheme is x.y.z-pre1
> Update version to 2.0 beta1

- lib/logstash/agent.rb
- lib/logstash/config/cpu_core_strategy.rb
- lib/logstash/config/defaults.rb
- lib/logstash/pipeline.rb
- lib/logstash/util/defaults_printer.rb
- lib/logstash/util/worker_threads_default_printer.rb
- spec/core/config_cpu_core_strategy_spec.rb
- spec/core/config_defaults_spec.rb
- spec/util/defaults_printer_spec.rb
- spec/util/worker_threads_default_printer_spec.rb
WIP
add basic defaults module and spec.  use defaults in pipeline and agent
> Support added for filter_workers default to cpu-cores

- docs/asciidoc/static/contributing-to-logstash.asciidoc
- docs/asciidoc/static/maintainer-guide.asciidoc
> Plugin Maintainer's Guide

- Rakefile
- rakelib/artifacts.rake
this fixed the build artifacts bug introduced by #4123
> fix version path, relates to #4123

- docs/asciidoc/static/offline-plugins.asciidoc
- docs/asciidoc/static/plugin-manager.asciidoc
- docs/asciidoc/static/private-gem-repo.asciidoc
- Offline Plugins for managing offline packs
- Private Rubygem repos
> Adds new material to Managing Plugins

- integration/plugin_manager/logstash_spec.rb
- integration/spec_helper.rb
Integration test are currently broken, this PR fix the missing parts of it.
> Fix broken integration test

- CHANGELOG.md
- Gemfile
- Gemfile.jruby-1.9.lock
- lib/logstash/version.rb
* Changelog
* Bump version and lock file changes
> Prepare for v2.1.1

- logstash-core/lib/logstash/agent.rb
- logstash-core/lib/logstash/agent.rb.orig
- logstash-core/lib/logstash/pipeline.rb
- logstash-core/lib/logstash/pipeline.rb.orig
- logstash-core/lib/logstash/runner.rb
- logstash-core/lib/logstash/runner.rb.orig
- logstash-core/lib/logstash/shutdown_controller.rb
- logstash-core/lib/logstash/shutdown_controller.rb.orig
- logstash-core/locales/en.yml
- logstash-core/locales/en.yml.orig
- logstash-core/spec/logstash/agent_spec.rb
- logstash-core/spec/logstash/agent_spec.rb.orig
- logstash-core/spec/logstash/runner_spec.rb
- logstash-core/spec/logstash/runner_spec.rb.orig
- logstash-core/spec/logstash/shutdown_controller_spec.rb
This takes over from #4342 which no longer is a clean merge to master. This is fully rebased off feature/management.
@jsvd feel free to force push this branch (after checking a diff!) and close this PR if that makes sense.
> Rebased reload config from files

- logstash-core-event-java/src/main/java/com/logstash/Event.java
this improves the Event json serialization speed by 10x
> use static Jackson mapper

- Gemfile
- Gemfile.jruby-1.9.lock
- logstash-core-event/lib/logstash-core-event/version.rb
- logstash-core/lib/logstash-core/version.rb
- logstash-core/lib/logstash/version.rb
- logstash-core/logstash-core.gemspec
Bump versions, update lock file
> Release a 2.2.1.snapshot1 version

- rakelib/vendor.rake
fixes #4977 until fixed upstream in JRuby jruby/jruby#3670
> revert to jruby 1.7.23 for regex regression

- docs/static/releasenotes.asciidoc
Fixed a couple of asciidoc tagging issues in the release notes.
> Fix minor formatting issues

- README.md
- docs/plugin-doc.asciidoc.erb
- docs/static/include/pluginbody.asciidoc
- docs/static/offline-plugins.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/submitting-a-plugin.asciidoc
- docs/static/upgrading.asciidoc
- lib/bootstrap/environment.rb
- lib/pluginmanager/install.rb
- lib/pluginmanager/list.rb
- lib/pluginmanager/unpack.rb
- lib/pluginmanager/update.rb
- rakelib/package.rake
> Rename occurances of bin/plugin in docs

- logstash-core/logstash-core.gemspec
- rakelib/vendor.rake
upgrade to JRuby 1.7.25 and  jruby-openssl 0.9.16
> upgrade to JRuby 1.7.25 and required jruby-openssl 0.9.16 to match JRuby

- Gemfile.jruby-1.9.lock
> Actually update lock file for 2.3.2.snapshot1

- docs/static/maintainer-guide.asciidoc
cherry pick of changes added in PR #5167
> Make structural changes to the plugin maintainer guide in 2.x

- docs/static/maintainer-guide.asciidoc
cherry pick of changes added in PR #5167
> Make structural changes to the plugin maintainer guide in 2.3

- CHANGELOG.md
- Gemfile
- Gemfile.jruby-1.9.lock
- logstash-core-event-java/lib/logstash-core-event-java/version.rb
- logstash-core-event/lib/logstash-core-event/version.rb
- logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb
- logstash-core-plugin-api/logstash-core-plugin-api.gemspec
- logstash-core/lib/logstash-core/version.rb
- logstash-core/lib/logstash/version.rb
- logstash-core/logstash-core.gemspec
> Release 2.3.2

- Gemfile.jruby-1.9.lock
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
> 2.3.2: Regenerate the lock file for Kafka

- CHANGELOG.md
- Gemfile
- Gemfile.jruby-1.9.lock
- logstash-core-event-java/lib/logstash-core-event-java/version.rb
- logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb
- logstash-core-plugin-api/logstash-core-plugin-api.gemspec
- logstash-core/lib/logstash-core/version.rb
- logstash-core/lib/logstash/version.rb
- logstash-core/logstash-core.gemspec
> Release 5.0 alpha2

- logstash-core/locales/en.yml
fixes https://github.com/elastic/logstash/issues/4921
> better error message for reload incompatible pipelines

- logstash-core-event/lib/logstash/event.rb
- logstash-core-event/spec/logstash/event_old_api_spec.rb
- logstash-core-event/spec/logstash/event_spec.rb
> Add get and set to 2.x branch but leaving [] and []=

- README.md
> fix CONTRIBUTING.md link in README.md

- logstash-core/lib/logstash/agent.rb
- logstash-core/lib/logstash/api/app_helpers.rb
- logstash-core/lib/logstash/api/command_factory.rb
- logstash-core/lib/logstash/api/commands/base.rb
- logstash-core/lib/logstash/api/commands/default_metadata.rb
- logstash-core/lib/logstash/api/commands/node.rb
- logstash-core/lib/logstash/api/commands/system/basicinfo_command.rb
- logstash-core/lib/logstash/api/modules/base.rb
- logstash-core/lib/logstash/runner.rb
- logstash-core/lib/logstash/webserver.rb
- logstash-core/spec/api/lib/api/node_spec.rb
- logstash-core/spec/api/lib/api/support/resource_dsl_methods.rb
- logstash-core/spec/api/spec_helper.rb
> Add stats default fields (hostname, http_address, version)

- docs/static/performance-checklist.asciidoc
This is a guide to help users quickly ascertain performance problems without getting their hands too dirty with internals knowledge.
Still need to figure out where to link to this from.
> Add quicktune guide

- docs/static/performance-checklist.asciidoc
@andrewvc @suyograo Here are my edits to the troubleshooting guide. In addition to the edits, I've made quite a few changes to formatting. 
Here's where I'm planning to put this in the TOC:
> Edit performance troubleshooting guide

- logstash-core/lib/logstash/pipeline.rb
- logstash-core/lib/logstash/pipeline_reporter.rb
- logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb
- logstash-core/spec/logstash/pipeline_spec.rb
- logstash-core/spec/logstash/util/wrapped_synchronous_queue_spec.rb
Following discussion, this is WrappedSynchronousQueue Client support classes proposal.
> Add queue client support (and batch object) to pipeline

- logstash-core-event/lib/logstash/event.rb
- logstash-core-event/spec/logstash/event_spec.rb
> Implement deep-clone properly with metadata

- docs/static/command-line-flags.asciidoc
- docs/static/setting-up-logstash.asciidoc
- docs/static/settings-file.asciidoc
couldn't get #5713 to merge into 5.0, some I'm a-cherry-picking it instead.
Already got an "LGTM" so I'm merging, too.
> cherry pick setting file updates into 5.0

- lib/bootstrap/environment.rb
- lib/bootstrap/patches/jar_dependencies.rb
> Silence `require_jar` warning

- logstash-core/build.gradle
- logstash-core/src/test/java/org/logstash/log/CustomLogEventTests.java
> check versions.yml for correct project version

- Gemfile.jruby-1.9.lock
> Fix JDBC logger issue

- Gemfile.jruby-1.9.lock
> Add new lock file for 5.0

- docs/static/breaking-changes.asciidoc
- docs/static/upgrading.asciidoc
This adds extra details to the Breaking Changes document so that users can hopefully better understand what is necessary to change in order to get around breaking changes.
/cc @acchen97 @suyograo @dedemorton
> Update Breaking Changes to provide extra details

- Gemfile.jruby-1.9.lock
> Use latest pleaserun 0.0.27

- logstash-core/logstash-core.gemspec
This needs back-porting to 2.X, 2.4, 5.X, 5.1 and 6.X
> Use JrJackson 0.4.2 - update logstash-core.gemspec

- logstash-core/src/main/java/org/logstash/FileLockFactory.java
- logstash-core/src/test/java/org/logstash/FileLockFactoryTest.java
add support to release a lock.
> support releaseLock

- docs/static/monitoring-apis.asciidoc
> Cherrypick #6658 into 5.1 branch

- logstash-core/src/main/java/org/logstash/common/io/FileCheckpointIO.java
- logstash-core/src/main/java/org/logstash/common/io/MemoryCheckpointIO.java
- logstash-core/src/test/java/org/logstash/common/io/MemoryCheckpointTest.java
namespace the in-memory checkpoint by dir path to support multiple instances of memory acked queues.
> memory checkpoint namespace

- logstash-core/src/main/java/org/logstash/common/io/MmapPageIO.java
merge conflicts diffs sneaked in.
> fix merge diff leftovers

- docs/static/getting-started-with-logstash.asciidoc
Cherrypicks #6775 into 5.x branch.
> Add conditional coding for install instructions (cherrypicks 6775)

- docs/static/getting-started-with-logstash.asciidoc
Cherry-picks #6775  into 5.3 branch.
> Add conditional coding for install instructions (cherrypick 6775)

- docs/index.asciidoc
@suyograo I created a PR to bump the versions for the doc.
> Bump versions to 5.3

- logstash-core/lib/logstash/output_delegator.rb
fixes https://github.com/elastic/logstash/issues/6889
> pass namespaced metric to output plugin instance

- docs/index.asciidoc
- docs/static/filebeat-modules.asciidoc
- docs/static/filebeat_modules/apache2/access/filebeat.yml
- docs/static/filebeat_modules/apache2/error/filebeat.yml
- docs/static/filebeat_modules/mysql/error/filebeat.yml
- docs/static/filebeat_modules/mysql/slowlog/filebeat.yml
- docs/static/filebeat_modules/nginx/access/filebeat.yml
- docs/static/filebeat_modules/nginx/error/filebeat.yml
- docs/static/filebeat_modules/system/auth/filebeat.yml
- docs/static/filebeat_modules/system/syslog/filebeat.yml
> Cherrypick #6832 5.3

- docs/index.asciidoc
- docs/static/filebeat-modules.asciidoc
- docs/static/filebeat_modules/apache2/access/filebeat.yml
- docs/static/filebeat_modules/apache2/error/filebeat.yml
- docs/static/filebeat_modules/mysql/error/filebeat.yml
- docs/static/filebeat_modules/mysql/slowlog/filebeat.yml
- docs/static/filebeat_modules/nginx/access/filebeat.yml
- docs/static/filebeat_modules/nginx/error/filebeat.yml
- docs/static/filebeat_modules/system/auth/filebeat.yml
- docs/static/filebeat_modules/system/syslog/filebeat.yml
> Cherrypick #6832 into 5.4

- bin/setup.bat
after exit the echo Done is not reached (and even if it would, it would not make sense)
> removed unreachable code

- config/logstash.yml
- logstash-core/lib/logstash/bootstrap_check/default_config.rb
- logstash-core/lib/logstash/config/source/modules.rb
- logstash-core/lib/logstash/config/source_loader.rb
- logstash-core/lib/logstash/environment.rb
- logstash-core/lib/logstash/modules.rb
- logstash-core/lib/logstash/modules_cli_parser.rb
- logstash-core/lib/logstash/plugins/registry.rb
- logstash-core/lib/logstash/runner.rb
- logstash-core/locales/en.yml
No tests yet.  Just for code review for now
> First upstream PR commit

- docs/index.asciidoc
> Backport to 5.0: Add edit URLs back into index.asciidoc

- docs/index.asciidoc
> Fix bad edit link

- logstash-core-plugin-api/logstash-core-plugin-api.gemspec
- logstash-core/lib/logstash-core/version.rb
- logstash-core/lib/logstash/version.rb
- versions.yml
Bump master version to 6.0.0-beta1
> bump version to 6.0.0-beta1

- logstash-core/lib/logstash/config/mixin.rb
for #7449, the req was missing as pointed out by @ph.
WIP: file too is missing will fix in like 8h
> WIP: #7449 5.4 fix missing req

- logstash-core/lib/logstash/modules/kibana_config.rb
- logstash-core/spec/logstash/modules/scaffold_spec.rb
> MODULES: Add maxbuckets to the kibana config json

- docs/static/advanced-pipeline.asciidoc
Fixed FB config examples for changes in 6.0.0-alpha2. Plus added a few other blurbs to clarify stuff that might be confusing due to other recent changes in LS and Beats.
> Fix example and add couple of usage notes

- modules/README.md
The folders layouts were both broken
> Fixed folder layout

- Gemfile.jruby-1.9.lock.release
> Bump plugin versions for docs generation

- docs/index-shared1.asciidoc
- docs/static/advanced-pipeline.asciidoc
- docs/static/configuration.asciidoc
- docs/static/transforming-data.asciidoc
Cherry-picks #7545 into 5.x branch.
> Backport: Add links to grok debugger

- logstash-core/spec/logstash/pipeline_dlq_commit_spec.rb
- logstash-core/spec/logstash/pipeline_pq_file_spec.rb
> Reset pipeline_settings_obj as explained in the issue 7551

- docs/index-shared1.asciidoc
- docs/index.asciidoc
- docs/static/advanced-pipeline.asciidoc
- docs/static/managing-multiline-events.asciidoc
- docs/static/upgrading.asciidoc
This pull request is related to https://github.com/elastic/docs/pull/202
It updates the Logstash Reference documentation build to use the list of shared attributes that is found in the elastic/docs repo.
> [DOCS] Update Logstash Reference to use shared attribute file

- docs/static/advanced-pipeline.asciidoc
- docs/static/breaking-changes.asciidoc
- docs/static/configuration.asciidoc
- docs/static/deploying.asciidoc
- docs/static/monitoring.asciidoc
- docs/static/transforming-data.asciidoc
This pull request fixes additional broken links related to https://github.com/elastic/logstash/pull/7541
> [DOCS] Fixed broken links

- logstash-core/lib/logstash/modules/logstash_config.rb
> make credentials optional in logstash modules

- docs/index-shared1.asciidoc
This needs to be merged the day of the release.
> Set release state for 5.5 docs

- docs/static/plugin-manager.asciidoc
Cherrypicks #7618 into master branch.
> Forward port into master: #7618

- docs/static/plugin-manager.asciidoc
> Forward port to 5.x: #7618

- logstash-core/spec/logstash/pipeline_spec.rb
> 5.x Backport - Test Failure Fix: Retry pipeline metrics

- logstash-core/lib/logstash/pipeline_settings.rb
- qa/integration/fixtures/multiple_pipeline_spec.yml
- qa/integration/specs/multiple_pipeline_spec.rb
* also adds `config.support_escapes` to list of pipeline settings
> test multiple pipelines using RATS

- config/jvm.options
>  #7766 turn off invokedynmic

- docs/static/introduction.asciidoc
> [Docs] Backport: Remove table formatting to fix build issues

- docs/index-shared1.asciidoc
- docs/index-shared2.asciidoc
@suyograo This needs to be merged for the install instructions to show up in the 5.6 docs.
> [Docs] Set release state to released

- Gemfile.jruby-2.3.lock.release
- versions.yml
I don't think this PR is necessary, we already have the versions.yml set to 6.0.0-rc1
> WIP Version bump to 6.0.0-rc1

- Gemfile.jruby-2.3.lock.release
This makes `6.0` build for me, let's see what Jenkins says ...
>  #8236 fix .lockfile

- Gemfile.jruby-2.3.lock.release
- ci/travis_integration_run.sh
- qa/integration/Gemfile
- qa/integration/integration_tests.gemspec
It's in the title, backporting #8181  to fix  #8236
>  #8236 backport of #8181 to 6.0 and revert of accidentally merged #8244

- bin/logstash-plugin.bat
we forgot to update `bin/logstash-plugin.bat` following the changes in  #8178
> update plugin manager script following setup.bat changes

- docs/index-shared1.asciidoc
- docs/static/releasenotes.asciidoc
Nothing changed, just test fixes and some very minor non-user-facing other fixes.
> 5.6.2 Release notes

- versions.yml
Fixes #8439 - Null JSON with JSON filter can halt a pipeline
See guyboertje/jrjackson/pull/65
> upgrade JrJackson to 0.4.4 to fix #8439

- docs/index-shared1.asciidoc
- docs/index-shared2.asciidoc
- docs/index-shared3.asciidoc
> Fix edit url links

- docs/static/filebeat_modules/nginx/access/pipeline.conf
Fixes broken example. 
This code example change has already been reviewed in https://github.com/elastic/logstash/pull/8490/files#diff-c9d3a237eb7622f34543f441c3b92b4bR15, so I am merging without review.
I tested to verify that the fix works.
> Fix nginx example 

- docs/static/netflow-module.asciidoc
Fixes https://github.com/elastic/logstash/issues/8734
> Fix filename error in netflow module docs

- docs/static/netflow-module.asciidoc
Cherrypicks #8737 into 6.0 branch.
> Update netflow-module.asciidoc (backports #8737 into 6.0)

- docs/index-shared1.asciidoc
WARNING: MERGE ONLY **ONE HOUR BEFORE** 6.1.0 RELEASE
> bump docs for 6.1.0 release

- README.md
- versions.yml
bumps version variables to 6.1.3 for next 6.1 release
> bump versions for next 6.1 release

- Gemfile.jruby-1.9.lock.release
- logstash-core-plugin-api/logstash-core-plugin-api.gemspec
- versions.yml
bumps version variables to 5.6.7 for next 5.6 release
> bump versions for next 5.6 release

- docs/static/persistent-queues.asciidoc
- docs/static/settings-file.asciidoc
> Backport 8927 to 6.0

- docs/static/persistent-queues.asciidoc
- docs/static/settings-file.asciidoc
Cherry-picks #8927 into 6.1 branch.
> Backport #8927 to 6.1

- docs/static/introduction.asciidoc
fix for broken links in the build
> Remove broken links

- docs/static/life-of-an-event.asciidoc
> Revert "Introduce file conflict"

- docs/static/life-of-an-event.asciidoc
will revert this shortly. for testing purposes only.
> Test change to introduce file conflict

- docs/static/life-of-an-event.asciidoc
> Soften text around data loss

- Gemfile.jruby-1.9.lock.release
> bump dissect version to avoid yanked gem in 5.6

- Gemfile.jruby-2.3.lock.release
> Bump dissect version for 6.2

- Gemfile.jruby-2.3.lock.release
> bump dissect version for 6.1

- CONTRIBUTING.md
Per action item from retrospective.
> Update Contribution Guidelines

- docs/static/upgrading.asciidoc
This PR updates the "Upgrading Logstash" topic to include an X-Pack monitoring tip. That information was originally found in https://www.elastic.co/guide/en/x-pack/master/xpack-upgrading.html
> [DOCS] Added X-Pack monitoring upgrade details

- docs/index-shared1.asciidoc
- docs/static/advanced-pipeline.asciidoc
- docs/static/deploying.asciidoc
- docs/static/filebeat-modules.asciidoc
> Cleanup cross references in docs

- docs/static/releasenotes.asciidoc
This should be merged to 6.2 and 6.x
> Release notes for 6.2.4

- docs/index-shared1.asciidoc
to be merged one hour before release
> bump docs version to 6.2.4

- docs/index-shared1.asciidoc
to be merged one hour before release
> bump docs version to 5.6.9

- rakelib/version.rake
Updates README artifact links regex to update version in OSS-only artifact links as well
> Update version in OSS-only artifacts as well

- logstash-core/benchmarks/src/main/java/org/logstash/benchmark/QueueRWBenchmark.java
- logstash-core/benchmarks/src/main/java/org/logstash/benchmark/QueueWriteBenchmark.java
- logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
- logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
- logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
- logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java
- logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java
- logstash-core/src/main/java/org/logstash/ackedqueue/io/PageIO.java
- logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java
- logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
- logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
- logstash-core/src/test/java/org/logstash/ackedqueue/io/FileMmapIOTest.java
Part of the meta issue for batches + timeouts across all queues https://github.com/elastic/logstash/issues/9389
Moved from: https://github.com/elastic/logstash/pull/8942 to target this feature branch
---
This is the initial work to support timeouts + batches.
It has one issue, however, which is that if the PQ page size is smaller than a batch it will break, we'll leave that to a future PR.
> PQ Batching queue timeouts

- docs/static/breaking-changes.asciidoc
6.2 backport of #9550 
Also backports a phrasing fix for future versions
> Fix sections breaking changes 62

- logstash-core/lib/logstash/config/pipeline_config.rb
- logstash-core/spec/logstash/config/pipeline_config_spec.rb
- x-pack/lib/config_management/elasticsearch_source.rb
- x-pack/lib/monitoring/inputs/metrics/state_event_factory.rb
Fixes partially #9566. 
This reverts commit dc168a10b55b8a59be6734fca04789f60d8ea153.
> Revert "[X-Pack Monitoring] Report pipeline protocol (#9516)"

- modules/netflow/configuration/logstash/netflow.conf.erb
If statement should be checking [geoip_dst][asn] not [geoip][asn].
> [geoip_dst][asn] should be tested by if statement

- docs/index.asciidoc
> bump docs for 6.3.1

- docs/index.asciidoc
6.4 brach was just created from 6.x and this updates the branch info to 6.4
> set 6.4 branch in docs

- rakelib/bump_plugin_versions.rake
> add rake task to bump plugin versions

- docs/static/releasenotes.asciidoc
> changelog for 6.4.1

- docs/index-shared1.asciidoc
DO NOT MERGE UNTIL 1 HOUR BEFORE RELEASE
> docs bump to 5.6.12

- logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb
- logstash-core/spec/logstash/instrument/periodic_poller/cgroup_spec.rb
and Kibana
This should go out as soon as possible and backport to 5.6
> Make cgroups more robust and provide the override similar to ES

- docs/index.asciidoc
DO NOT MERGE UNTIL 1 HOUR BEFORE RELEASE
> bump docs version to 6.4.2

- docs/index.asciidoc
This PR updates the release-state attribute for the Logstash Reference
> [DOCS] Changes release state for 650

- docs/index.asciidoc
DO NOT merge until 1 hour before 6.5.1 release
> bump docs version to 6.5.1

- Gemfile.jruby-1.9.lock.release
- logstash-core/logstash-core.gemspec
avoid issue https://github.com/jruby/jruby-openssl/issues/150 in logstash 5.x
> bump jruby-openssl dependency

- Gemfile.jruby-1.9.lock.release
- versions.yml
This reverts commit 4cb1546bb1decef1f9eae983f12108805f3326cc.
> Revert "Version bump to 5.6.15"

- docs/static/releasenotes.asciidoc
Placeholder for alpha2 release notes
> Add placeholder for alpha2 release notes

- logstash-core/src/main/java/co/elastic/logstash/api/PluginHelper.java
- logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java
- logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
- logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
- logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/ClasspathHelper.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Configuration.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/ConfigurationBuilder.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/FilterBuilder.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/ReflectionUtils.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Store.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Utils.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Vfs.java
- logstash-core/src/main/java/org/logstash/plugins/pipeline/AddressState.java
- logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
- logstash-core/src/main/java/org/logstash/secret/store/SecretStoreFactory.java
Amends https://github.com/elastic/logstash/pull/10241.
> Resolve javadoc warnings not seen on 1.8.0_181

- logstash-core/src/main/java/co/elastic/logstash/api/PluginHelper.java
- logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java
- logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
- logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
- logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/ClasspathHelper.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Configuration.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/ConfigurationBuilder.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/FilterBuilder.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/ReflectionUtils.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Store.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Utils.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/Vfs.java
- logstash-core/src/main/java/org/logstash/plugins/pipeline/AddressState.java
- logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
- logstash-core/src/main/java/org/logstash/secret/store/SecretStoreFactory.java
Back-port of https://github.com/elastic/logstash/pull/10244 to `6.x`
> Resolve javadoc warnings

- docs/static/settings-file.asciidoc
- logstash-core/lib/logstash/environment.rb
- logstash-core/lib/logstash/pipeline_settings.rb
- logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb
- logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb
- logstash-core/spec/logstash/queue_factory_spec.rb
- logstash-core/spec/logstash/util/wrapped_acked_queue_spec.rb
- logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
- logstash-core/src/main/java/org/logstash/ackedqueue/QueueFactoryExt.java
- logstash-core/src/main/java/org/logstash/ackedqueue/Settings.java
- logstash-core/src/main/java/org/logstash/ackedqueue/SettingsImpl.java
- logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
- logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java
- logstash-core/src/main/java/org/logstash/ackedqueue/io/FileCheckpointIO.java
This is a clean back-port of https://github.com/elastic/logstash/pull/10234 to the `6.6` branch.
> Add option for PQ checkpoint retry

- logstash-core/lib/logstash/pipeline_action/create.rb
- logstash-core/lib/logstash/pipeline_action/reload.rb
- logstash-core/lib/logstash/pipeline_action/stop.rb
> [6.5 clean backport of #10331] correctly handle pipeline actions

- config/pipelines.yml
- logstash-core/lib/logstash/environment.rb
- logstash-core/lib/logstash/pipeline_settings.rb
fixes https://github.com/elastic/logstash/issues/10237
> remove pipeline output workers setting

- logstash-core/lib/logstash/agent.rb
- logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
- logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
- logstash-core/lib/logstash/instrument/periodic_pollers.rb
- logstash-core/lib/logstash/java_pipeline.rb
- logstash-core/lib/logstash/pipeline.rb
- logstash-core/lib/logstash/pipeline_action/base.rb
- logstash-core/lib/logstash/pipeline_action/create.rb
- logstash-core/lib/logstash/pipeline_action/reload.rb
- logstash-core/lib/logstash/pipeline_action/stop.rb
- logstash-core/lib/logstash/pipelines_registry.rb
- logstash-core/lib/logstash/state_resolver.rb
- logstash-core/spec/logstash/agent/converge_spec.rb
- logstash-core/spec/logstash/agent_spec.rb
- logstash-core/spec/logstash/pipeline_action/create_spec.rb
- logstash-core/spec/logstash/pipeline_action/reload_spec.rb
- logstash-core/spec/logstash/pipeline_action/stop_spec.rb
- logstash-core/spec/logstash/pipelines_registry_spec.rb
- logstash-core/spec/logstash/state_resolver_spec.rb
- logstash-core/spec/support/matchers.rb
- logstash-core/spec/support/shared_contexts.rb
- logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
- x-pack/lib/monitoring/inputs/metrics.rb
- x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
- x-pack/spec/monitoring/inputs/metrics_spec.rb
- x-pack/spec/support/helpers.rb
> [6.x clean backport of #10346] fix agent silent exit upon pipelines reloading

- logstash-core/lib/logstash/agent.rb
- logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
- logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
- logstash-core/lib/logstash/instrument/periodic_pollers.rb
- logstash-core/lib/logstash/java_pipeline.rb
- logstash-core/lib/logstash/pipeline.rb
- logstash-core/lib/logstash/pipeline_action/base.rb
- logstash-core/lib/logstash/pipeline_action/create.rb
- logstash-core/lib/logstash/pipeline_action/reload.rb
- logstash-core/lib/logstash/pipeline_action/stop.rb
- logstash-core/lib/logstash/pipelines_registry.rb
- logstash-core/lib/logstash/state_resolver.rb
- logstash-core/spec/logstash/agent/converge_spec.rb
- logstash-core/spec/logstash/agent_spec.rb
- logstash-core/spec/logstash/pipeline_action/create_spec.rb
- logstash-core/spec/logstash/pipeline_action/reload_spec.rb
- logstash-core/spec/logstash/pipeline_action/stop_spec.rb
- logstash-core/spec/logstash/pipelines_registry_spec.rb
- logstash-core/spec/logstash/state_resolver_spec.rb
- logstash-core/spec/support/matchers.rb
- logstash-core/spec/support/shared_contexts.rb
- logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
- x-pack/lib/monitoring/inputs/metrics.rb
- x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
- x-pack/spec/monitoring/inputs/metrics_spec.rb
- x-pack/spec/support/helpers.rb
> [6.6 clean backport of #10346] fix agent silent exit upon pipelines reloading

- tools/dependencies-report/src/test/resources/expectedNoticeOutput.txt
> update test fixture to reflect NOTICES format

- docs/index.asciidoc
- docs/static/contributing-java-plugin.asciidoc
- docs/static/include/javapluginpkg.asciidoc
- docs/static/include/javapluginsetup.asciidoc
- docs/static/java-codec.asciidoc
- docs/static/java-filter.asciidoc
- docs/static/java-input.asciidoc
- docs/static/java-output.asciidoc
Java plugins to LS Ref
Merge target: 7.x
> Cherrypick to 7.x: Convert instructions for Java plugins to asciidoc

- docs/index.asciidoc
- docs/static/contributing-java-plugin.asciidoc
- docs/static/include/javapluginpkg.asciidoc
- docs/static/include/javapluginsetup.asciidoc
- docs/static/java-codec.asciidoc
- docs/static/java-filter.asciidoc
- docs/static/java-input.asciidoc
- docs/static/java-output.asciidoc
Java plugin instructions to LS Ref
Merge target: 7.0
> Cherrypick to 7.0: Convert instructions for Java plugins to asciidoc 

- docs/static/contributing-java-plugin.asciidoc
- docs/static/include/javapluginpkg.asciidoc
- docs/static/include/javapluginsetup.asciidoc
- docs/static/java-codec.asciidoc
- docs/static/java-filter.asciidoc
- docs/static/java-input.asciidoc
- docs/static/java-output.asciidoc
- Changed doc tags from `experimental` to `beta`
- Added codec file, includes, links
- Changed name of API package to `co.elastic.logstash.api`
Rendered docs are here:
https://java-pi.firebaseapp.com/contributing-java-plugin.html
> [Docs] Update java plugin docs for beta

- build.gradle
> [7.0 clean backport of #10555] correctly handle unexecuted downloadEs task

- build.gradle
[7.x clean backport of #10555]
> [7.x clean backport of #10555] correctly handle unexecuted downloadEs task

- Gemfile.jruby-1.9.lock.release
- versions.yml
Bump versions in lock file and versions.yml
> Bump version to 5.6.17

- docs/static/releasenotes.asciidoc
Also adds release notes from 6.6 branch
> Release notes for 6.7.0

- docs/static/getting-started-with-logstash.asciidoc
I wanted to get a PR started so we can iterate.  This issue is related to install packages and Java 11, so I'm putting it in the Installation section for now.  We can move or duplicate as appropriate. Wording is also up for discussion.
> [WIP] Add note about issues with Java 11 and Debian or RPM

- docs/static/breaking-changes.asciidoc
Backports https://github.com/elastic/logstash/pull/10654
> [DOCS] Adds tagged region for notable breaking changes (#10654)

- docs/static/releasenotes.asciidoc
I did not include notes for changes that were also include in v6.
> 7.0.0 alpha1, alpha2 and beta1 release notes

- docs/static/upgrading.asciidoc
> [WIP] Refine upgrade instructions for 7.0

- Dockerfile
- Dockerfile.base
- build.gradle
- docker/templates/Dockerfile.j2
experimenting docker testing with jdk 11. do not merge
> bump openjdk 11 in docker testing

- Gemfile.jruby-2.5.lock.release
- README.md
- versions.yml
This should only be merged after 7.0.1 is released.
> bump version to 7.0.2

- docs/static/advanced-pipeline.asciidoc
- docs/static/azure-module.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/monitoring-apis.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/running-logstash.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/transforming-data.asciidoc
Cherrypicked #10744 into 6.5 and resolved conflicts.
Fixed asciidoc formatting in old content.
> Cherrypick #10744 - Fix asciidoc formatting into 6.5

- docs/static/advanced-pipeline.asciidoc
- docs/static/azure-module.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/monitoring-apis.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/running-logstash.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/transforming-data.asciidoc
Related PR: https://github.com/elastic/logstash-docs/pull/692
> Fix asciidoc formatting for conversion to asciidoctor

- docs/static/advanced-pipeline.asciidoc
- docs/static/azure-module.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/monitoring-apis.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/running-logstash.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/transforming-data.asciidoc
Cherrypick from 10744
Resolved conflicts
Fixed asciidoctor formatting in old content
> Fix asciidoc formatting for conversion to asciidoctor - 6.4

- docs/static/advanced-pipeline.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/monitoring-apis.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/running-logstash.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/transforming-data.asciidoc
Cherrypick from #10758 
Remove changes for azure-module file
> [Doc] Cherrypick asciidoctor formatting changes for 6.3

- logstash-core/lib/logstash/patches/resolv.rb
- logstash-core/lib/logstash/patches/resolv_9270.rb
- logstash-core/spec/logstash/jruby_version_spec.rb
> [7.x clean backport of #10734] fix JRuby resolv.rb leak

- logstash-core/lib/logstash/patches/resolv.rb
- logstash-core/lib/logstash/patches/resolv_9270.rb
- logstash-core/spec/logstash/jruby_version_spec.rb
7.1 clean backport of #10734
This should be merged **after** the release of 7.1
> [7.1 clean backport of #10734] fix JRuby resolv.rb leak

- logstash-core/lib/logstash/patches/resolv.rb
- logstash-core/lib/logstash/patches/resolv_9270.rb
- logstash-core/spec/logstash/jruby_version_spec.rb
6.8 clean backport of #10734
This should be merged **after** the release of 6.8
> [6.8 clean backport of #10734] fix JRuby resolv.rb leak

- docs/static/advanced-pipeline.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/monitoring-apis.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/running-logstash.asciidoc
Backport of #10760 with conflict resolutions
> [Docs][Backport]Asciidoctor fixes for LS ref 6.1

- docs/static/advanced-pipeline.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/monitoring-apis.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/running-logstash.asciidoc
> [Doc][Backport]Asciidoctor fixes for ls ref 6.0

- docs/static/advanced-pipeline.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/running-logstash.asciidoc
Backport of #10762 with conflict resolution
> [Doc][Backport]Asciidoctor formatting changes for ls ref 5.6

- docs/static/advanced-pipeline.asciidoc
- docs/static/dead-letter-queues.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/running-logstash.asciidoc
Backport of #10764 with conflict resolution
> [Doc][Backport]Asciidoctor formatting changes for ls ref 5.5

- docs/static/advanced-pipeline.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/running-logstash.asciidoc
Backport of #10765 with conflict resolution to remove dead-letter-queues
> [Doc][Backport]Asciidoctor formatting changes for ls ref for 5.4

- docs/static/advanced-pipeline.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/running-logstash.asciidoc
> [Doc][Backport]Asciidoctor formatting changes for ls ref 5.3

- docs/static/advanced-pipeline.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/running-logstash.asciidoc
> [Docs][Backport]Asciidoctor formatting changes for ls ref

- docs/static/advanced-pipeline.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/running-logstash.asciidoc
> [Doc][Backport]Asciidoctor formatting changes for ls ref

- docs/static/advanced-pipeline.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
Backport of #10766 with conflict resolution to remove running-logstash
> [Doc][Backport]Asciidoctor formatting changes for 5.0

- logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb
Clean backport of https://github.com/elastic/logstash/pull/10728
> Include G1 in JVM heap metrics

- docs/static/advanced-pipeline.asciidoc
- docs/static/maintainer-guide.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
Backport of #10770 with conflict resolution in advanced-pipeline.asciidoc
> [Docs][Backport]Asciidoctor formatting changes 2.4

- docs/static/advanced-pipeline.asciidoc
- docs/static/maintainer-guide.asciidoc
Backport of #10774 with conflict resolution
> [Doc][Backport]Asciidoctor formatting and file changes for 2.3

- docs/index-shared1.asciidoc
- docs/index.asciidoc
- docs/static/advanced-pipeline.asciidoc
- docs/static/contributing-patch.asciidoc
- docs/static/plugin-manager.asciidoc
Backport of #10775 with conflict resolution
> [Doc][Backport]Asciidoctor formatting changes 2.2

- docs/asciidoc/static/advanced-pipeline.asciidoc
- docs/index-shared1.asciidoc
- docs/index.asciidoc
> [Doc][Backport]Asciidoctor formatting changes 2.1

- docs/asciidoc/static/advanced-pipeline.asciidoc
- docs/asciidoc/static/plugin-manager.asciidoc
- docs/index-shared1.asciidoc
- docs/index.asciidoc
Backport #10776 with conflict resolution
> [Doc][Backport]Asciidoctor formatting fixes 2.0

- docs/asciidoc/static/plugin-manager.asciidoc
- docs/index-shared1.asciidoc
- docs/index.asciidoc
Backport asciidoctor fixes for callouts
> [Docs][Backport]Asciidoctor formatting changes 1.5

- docs/static/plugin-manager.asciidoc
> [Doc]More asciidoctor formatting fixes

- logstash-core/lib/logstash/api/commands/node.rb
* Restore UUID lookup to node
* Fix incorrect merge
* Move private method to bottom
* Change method name per review suggestion
* Update method description
> [BACKPORT] Restore UUID lookup to node (#10884)

- logstash-core/lib/logstash/api/commands/default_metadata.rb
* Add workers and batch_size to root request
* Add batch delay per review recommendation
> [BACKPORT] Add workers and batch_size to root request (#10853)

- docs/static/running-logstash-windows.asciidoc
Rendered content on Firebase:  https://preview-docs.firebaseapp.com/ls-windows-svc/running-logstash-windows.html
> [Doc]Fix formatting for nested version attributes

- docs/include/plugin_header-core.asciidoc
- docs/static/core-plugins/codecs/java_dots.asciidoc
- docs/static/core-plugins/codecs/java_line.asciidoc
- docs/static/core-plugins/codecs/java_plain.asciidoc
- docs/static/core-plugins/filters/java_uuid.asciidoc
- docs/static/core-plugins/inputs/java_generator.asciidoc
- docs/static/core-plugins/inputs/java_stdin.asciidoc
- docs/static/core-plugins/outputs/java_sink.asciidoc
- docs/static/core-plugins/outputs/java_stdout.asciidoc
> [Doc]Prep core plugins for inclusion in LS Ref

- docs/include/plugin_header.asciidoc
- docs/include/version-list-intro.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/setup/configuring-xls.asciidoc
- docs/static/setup/installing-xls.asciidoc
These are required for Asciidoctor and were already in every other
branch.
> Docs: Add missing subs

- docs/static/releasenotes.asciidoc
> Updated release notes for 7.2.1

- logstash-core/spec/logstash/api/commands/default_metadata_spec.rb
- logstash-core/spec/logstash/api/commands/node_spec.rb
- logstash-core/spec/logstash/api/commands/stats_spec.rb
- logstash-core/spec/logstash/api/modules/node_spec.rb
- logstash-core/spec/logstash/api/modules/node_stats_spec.rb
This enhances the test framework to support recent changes to the API.
PRs which this covers:
It also covers a few missing cases found along the way.
Refs: https://github.com/elastic/kibana/issues/33706
> Enhanced API testing

- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
Backports https://github.com/elastic/logstash/pull/11166
> [7.x][DOCS] Fixes links to monitoring content (#11166)

- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
Backports https://github.com/elastic/logstash/pull/11166
> [7.4][DOCS] Fixes links to monitoring content (#11166)

- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
Backports https://github.com/elastic/logstash/pull/11166
> [7.3][DOCS] Fixes links to monitoring content (#11166)

- docs/static/breaking-changes.asciidoc
- docs/static/upgrading.asciidoc
Remove `coming` tags in master
> [Doc]Remove leftover tags

- docs/jp/static/getting-started-with-logstash.asciidoc
- docs/jp/static/introduction.asciidoc
- docs/kr/static/introduction.asciidoc
Mostly just adds zero width spaces to the Japanese translation to make asciidoctor happy.
> Docs: Fix links in translation

- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.x][DOCS] Replaces occurrences of xpack-ref (#11366)

- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [6.8][DOCS] Replaces occurrences of xpack-ref (#11366)

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/monitoring-internal.asciidoc
- docs/static/monitoring/monitoring-mb.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.5][DOCS] Replaces occurrences of xpack-ref

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/monitoring-internal.asciidoc
- docs/static/monitoring/monitoring-mb.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.4][DOCS] Replaces occurrences of xpack-ref

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/monitoring-internal.asciidoc
- docs/static/monitoring/monitoring-mb.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.3][DOCS] Replaces occurrences of xpack-ref 

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/intro.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.2][DOCS] Replaces occurrences of xpack-ref

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/intro.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.1][DOCS] Replaces occurrences of xpack-ref

- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/intro.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.0][DOCS] Replaces occurrences of xpack-ref

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/intro.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
Backports https://github.com/elastic/logstash/pull/11360
> [6.6][DOCS] Fixes occurrences of xpack-ref attribute (#11360)

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/intro.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
Backports https://github.com/elastic/logstash/pull/11360
> [6.5][DOCS] Fixes occurrences of xpack-ref attribute (#11360)

- docs/static/azure-module.asciidoc
- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/intro.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
Backports https://github.com/elastic/logstash/pull/11360
> [6.4][DOCS] Fixes occurrences of xpack-ref attribute (#11360)

- docs/static/deploying.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/monitoring/configuring-logstash.asciidoc
- docs/static/monitoring/intro.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
Backport https://github.com/elastic/logstash/pull/11360
> [6.3][DOCS] Fixes occurrences of xpack-ref attribute (#11360)

- docs/static/page_header.html
Backports EOL notice from https://github.com/elastic/logstash/pull/11410.
> [DOCS] Add EOL notice. 

- logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
- logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java
> [7.5 clean backport of #11482] cache compiled datasets

- logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
- logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java
> [7.6 clean backport of #11482] cache compiled datasets

- docs/static/releasenotes.asciidoc
Forward port #11448 to 7.x branch in preparation for 7.6 FF
> [Doc] Forward port 7.5.1 release notes to 7.x (#11448)

- logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
- logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java
> [7.5 backport of #11564] revert #11482 and fix redundant code generation

- logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
- logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java
> [7.7 backport of #11564] revert #11482 and fix redundant code generation #11574

- docs/static/monitoring/monitoring-internal.asciidoc
- docs/static/monitoring/monitoring-mb.asciidoc
**PREVIEW:** http://logstash_11625.docs-preview.app.elstc.co/guide/en/logstash/7.6/configuring-logstash.html
> [DOC]Remove deprecation notice for 7.6

- docs/static/security/logstash.asciidoc
Backports https://github.com/elastic/logstash/pull/10752
> [7.x][DOCS] Updates security API examples (#10752)

- docs/static/security/logstash.asciidoc
Backports https://github.com/elastic/logstash/pull/10752
> [7.6][DOCS] Updates security API examples (#10752)

- CONTRIBUTING.md
> [DOC]Add more references to contributing issues

- CONTRIBUTING.md
> [DOC]Add more references to contributing issues to 7.6

- logstash-core/lib/logstash/compiler/lscl.rb
- logstash-core/spec/logstash/compiler/compiler_spec.rb
> [7.7 clean backport of #11688] support quoted plugin option key

- docs/static/releasenotes.asciidoc
**PREVIEW:**  http://logstash_11704.docs-preview.app.elstc.co/guide/en/logstash/6.8/releasenotes.html
> Release Notes for 6.8.8

- docs/static/releasenotes.asciidoc
**PREVIEW:**  http://logstash_11705.docs-preview.app.elstc.co/guide/en/logstash/current/releasenotes.html
> 7.6.2 Release notes

- Dockerfile
- build.gradle
- ci/license_check.sh
- ci/unit_tests.sh
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- logstash-core/benchmarks/build.gradle
- logstash-core/build.gradle
- qa/integration/build.gradle
- rubyUtils.gradle
- tools/benchmark-cli/build.gradle
- tools/dependencies-report/build.gradle
- tools/ingest-converter/build.gradle
- x-pack/build.gradle
Gradle versions prior to 6.3 cannot run under JDK14.
> Update gradle version to 6.3

- .ci/matrix-unix-runtime-javas.yml
- .ci/matrix-windows-runtime-javas.yml
- ci/unit_tests.bat
This PR adds 2 yml files which defines the JDKs to be used by CI during JDKs compatibility assement jobs
> Ci build with matrix jdks

- logstash-core/lib/logstash/java_pipeline.rb
resolves https://github.com/elastic/logstash/issues/10886
> remove :cluster_uuids gauge

- config/logstash.yml
- docs/static/breaking-changes.asciidoc
- docs/static/reloading-config.asciidoc
- docs/static/running-logstash-command-line.asciidoc
- docs/static/settings-file.asciidoc
> [Doc][Backport] Unit qualifier is required 7.6

- config/logstash.yml
- docs/static/breaking-changes.asciidoc
- docs/static/reloading-config.asciidoc
- docs/static/running-logstash-command-line.asciidoc
- docs/static/settings-file.asciidoc
> [Doc][Backport] Unit qualifier is required 6.8

- docs/static/releasenotes.asciidoc
This PR is based off of the work in #11721 and incorporates additional review comments. 
**PREVIEW:** http://logstash_11762.docs-preview.app.elstc.co/guide/en/logstash/7.7/logstash-7-7-0.html
> Release Notes for 7.7 (continued)

- docs/static/releasenotes.asciidoc
Backports #11762 to the 7.x branch
> [Doc][Backport]Release Notes 7.7 to 7.x (#11762)

- docs/static/releasenotes.asciidoc
Replace info about monitoring internal collection with known issue.
**PREVIEW:** http://logstash_11816.docs-preview.app.elstc.co/guide/en/logstash/7.7/logstash-7-7-0.html
> [Doc]Release notes: Add known issue for monitoring settings

- docs/static/releasenotes.asciidoc
Backport #11816 to 7.x branch
* Add known issue for monitoring settings
* Incorporate review comments
> [Doc]Release notes: Add known issue for monitoring settings (#11816)

- .ci/matrix-unix-runtime-javas.yml
- .ci/matrix-windows-runtime-javas.yml
- ci/unit_tests.bat
Clean backport of #11768 and #11801
> [7.x] Backport JDK Unit Testing Matrices

- ci/unit_tests.bat
Added test to avoid inserting and empty space in GRADLE_OPTS, and moved echo command outside of if to make it effective
> Fix: chaining of GRADLE_OPTS

- .ci/matrix-windows-runtime-javas.yml
Added Zulu 14 for JDK compatibility testing under Windows OS
> Add: Zulu 14 for JDK testing under Windows OS

- docs/static/releasenotes.asciidoc
**PREVIEW:**  http://logstash_11851.docs-preview.app.elstc.co/guide/en/logstash/6.8/releasenotes.html
> Release notes draft for 6.8.9

- bin/benchmark.bat
- bin/ingest-convert.bat
- bin/pqcheck.bat
- bin/pqrepair.bat
> [7.7 clean backport of #11754] tools convert to batch files

- docs/static/azure-module.asciidoc
- docs/static/modules.asciidoc
Fixes: #11863 
**PREVIEW:**  http://logstash_11892.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-modules.html
> Doc:Add deprecation notice for azure module

- logstash-core/src/test/java/org/logstash/plugins/NamespacedMetricImplTest.java
> [Tests] Ignore flaky `testTimeCallable` test

- .ci/matrix-unix-compatibility-linux-distros.yml
- .ci/matrix-unix-linux-distros.yml
- .ci/matrix-unix-runtime-javas.yml
- .ci/matrix-windows-compatibility-versions.yml
- .ci/matrix-windows-runtime-javas.yml
- ci/acceptance_tests.sh
- ci/docker_run.sh
- ci/integration_tests.sh
- ci/unit_tests.bat
- ci/unit_tests.sh
- qa/integration/services/logstash_service.rb
- x-pack/ci/docker_integration_tests.sh
- x-pack/ci/docker_unit_tests.sh
- x-pack/ci/integration_tests.sh
- x-pack/ci/unit_tests.sh
Backport to `7.x` branch of all the rJDK testing related changes
> Backport jdk testing to 7.x

- .ci/matrix-unix-compatibility-linux-distros.yml
- .ci/matrix-unix-linux-distros.yml
- .ci/matrix-unix-runtime-javas.yml
- .ci/matrix-windows-compatibility-versions.yml
- .ci/matrix-windows-runtime-javas.yml
- ci/acceptance_tests.sh
- ci/docker_run.sh
- ci/integration_tests.sh
- ci/unit_tests.bat
- ci/unit_tests.sh
- qa/integration/services/logstash_service.rb
- x-pack/ci/docker_integration_tests.sh
- x-pack/ci/docker_unit_tests.sh
- x-pack/ci/integration_tests.sh
- x-pack/ci/unit_tests.sh
Backport to `7.8` branch of all the rJDK testing related changes
> Backport jdk testing to 7.8

- docs/static/security/logstash.asciidoc
Replaced `/_xpack/security/...` with `/_security/...`
> Removed deprecated `/_xpack/security` paths

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_11954.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-7-7-1.html
> Update release notes for 7.7.1

- docs/static/releasenotes.asciidoc
- qa/integration/services/kafka_setup.sh
**PREVIEW:** https://logstash_11955.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-10.html
> Update release notes 6.8.10

- logstash-core/src/test/java/org/logstash/config/ir/compiler/OutputDelegatorTest.java
> Disable flaky multiReceiveRecordsDurationInMillis test

- docs/static/settings/configuration-management-settings.asciidoc
- docs/static/settings/monitoring-settings-legacy.asciidoc
- x-pack/lib/config_management/elasticsearch_source.rb
- x-pack/lib/config_management/extension.rb
- x-pack/lib/helpers/elasticsearch_options.rb
- x-pack/lib/monitoring/internal_pipeline_source.rb
- x-pack/lib/monitoring/monitoring.rb
- x-pack/lib/template.cfg.erb
- x-pack/spec/config_management/elasticsearch_source_spec.rb
- x-pack/spec/helpers/elasticsearch_options_spec.rb
- x-pack/spec/license_checker/license_reader_spec.rb
- x-pack/spec/monitoring/inputs/metrics_spec.rb
- x-pack/spec/monitoring/internal_pipeline_source_spec.rb
> [7.x clean backport of #11864] add support for api_key authentication in xpack management and monitoring

- docs/static/releasenotes.asciidoc
> Forwardport: 7.7.1 release notes to 7.x branch

- logstash-core/src/main/java/org/logstash/log/DeprecationLoggerExt.java
- logstash-core/src/main/java/org/logstash/log/LoggableExt.java
- logstash-core/src/main/java/org/logstash/log/SlowLoggerExt.java
**MERGE ONLY after 7.7 release**
Backport of https://github.com/elastic/logstash/pull/11874
> Fix: avoid gsub (frame dependent) usage from Java

- docs/static/security/api-keys.asciidoc
- docs/static/security/logstash.asciidoc
**PREVIEW:**  https://logstash_11974.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#ls-api-keys
> Doc:Add section to security docs for API key information

- ci/docker_integration_tests.sh
- qa/integration/fixtures/persistent_queues/log4j2.properties
This is a cumulative backport to 7.8 for:
-  #11922
-  #11929
> Backport fixes to enable feature flag 7.8

- docs/static/releasenotes.asciidoc
Forwardports:  #11954
**PREVIEW:**  https://logstash_12014.docs-preview.app.elstc.co/guide/en/logstash/7.8/releasenotes.html
> Doc:Add 7.7.1 release notes to 7.8 branch

- docs/static/jvm.asciidoc
PREVIEW: https://logstash_12013.docs-preview.app.elstc.co/guide/en/logstash/master/getting-started-with-logstash.html#ls-jvm
> Doc:Add link to JVM section of support matrix

- docs/gs-index.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.8][DOCS] Fixes Stack Overview links (#12025)

- docs/gs-index.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.7][DOCS] Fixes Stack Overview links (#12025)

- docs/gs-index.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.x][DOCS] Fixes Stack Overview links (#12025)

- docs/gs-index.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.5][DOCS] Fixes Stack Overview links (#12025)

- docs/gs-index.asciidoc
- docs/static/docker.asciidoc
- docs/static/getting-started-with-logstash.asciidoc
- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
- docs/static/setup/setting-up-xpack.asciidoc
> [7.6][DOCS] Fixes Stack Overview links (#12025)

- lib/pluginmanager/templates/codec-plugin/lib/logstash/codecs/example.rb.erb
> Added a missing reference.

- docs/static/security/api-keys.asciidoc
**PREVIEW:** https://logstash_11990.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#ls-api-keys
> Doc:Add info on using api keys for access

- docs/static/monitoring/monitoring-internal-legacy.asciidoc
- docs/static/monitoring/monitoring-overview.asciidoc
Deprecated at 7.9
**PREVIEW:** https://logstash_12046.docs-preview.app.elstc.co/guide/en/logstash/master/configuring-logstash.html
Resolves: #11979
> Doc:Add deprecation notice to legacy collection

- logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
- logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
Once the `FileLockFactory` dir lock has been obtained, make sure to always release that lock upon catching any exception while opening the queue. 
**NOTE** The diff looks big but it is not; I essentially took the bulk of the `open` method and moved it into a new `openPages` method which created the big diff, and just enclosed that new `openPages` call into a try/catch  ensure the lock is released upon exception in `openPages` which is the real diff here.
> release queue dir lock upon exceptions while opening queue

- docs/static/processing-info.asciidoc
- docs/static/reserved-fields.asciidoc
Fixes: #11946
Co-authored-by: Ry Biesemeyer <yaauie@users.noreply.github.com>
> [Doc]Add info on reserved fields in events

- logstash-core/lib/logstash/agent.rb
- logstash-core/lib/logstash/java_pipeline.rb
- logstash-core/lib/logstash/pipeline.rb
- logstash-core/lib/logstash/pipelines_registry.rb
- logstash-core/spec/logstash/java_pipeline_spec.rb
- logstash-core/spec/logstash/pipelines_registry_spec.rb
- logstash-core/spec/support/matchers.rb
- logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java
> [7.8 clean backport of #12019] Fix pipeline state logic and worker thread error handling

- docs/static/releasenotes.asciidoc
Forwardports 7.8 release notes (#12033) to 7.x branch
> [Doc][forwardport]Release notes for 7.8 to 7.x branch

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12091.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-11.html (pending build)
> Release notes draft for 6.8.11

- docs/static/releasenotes.asciidoc
Tag release notes with a "Coming in..." tag.
Tag will be removed after release.
**PREVIEW:** https://logstash_12119.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-11.html
> Doc:Add coming tag for 6.8.11 release notes

- docs/static/releasenotes.asciidoc
Bring forward review comments and incorporate review comments from #12033 
Address:
Take-aways going forward:
* PR numbers only in changelog section
**PREVIEW:** https://logstash_12050.docs-preview.app.elstc.co/guide/en/logstash/7.8/logstash-7-8-0.html
> Doc:Finetune 7.8 release notes

- docs/static/releasenotes.asciidoc
Forwardport 7.8.0 release notes updates in #12050 to 7.x branch
> Doc:Fine tune 7.8 release notes 

- docs/static/releasenotes.asciidoc
DO NOT MERGE until after 6.8.11 release.
> Doc:Remove coming tag from 6.8.11 release notes after release

- docs/static/releasenotes.asciidoc
DO NOT MERGE until after 7.8.1 release
> Doc:Remove coming tag from 7.8.1 release notes after release

- docs/static/releasenotes.asciidoc
Forwardports 7.8.1 release notes (#12092) to 7.9 branch
> [DOC]Forwardport 7.8.1 release notes (#12092) to 7.9

- docs/static/releasenotes.asciidoc
Forwardports 7.8.1 release notes (#12092) to 7.x branch
> [DOC]Forwardport 7.8.1 release notes (#12092) to 7.x

- docs/static/releasenotes.asciidoc
Forwardport final 7.8.0 release notes updates (#12050) to 7.9 branch
> Doc:Forwardport final 7.8.0 release notes (#12050) to 7.9

- docs/asciidoc/static/deploying.asciidoc
- docs/index-shared1.asciidoc
This URL will be changing soon. See elastic/docs#1918
> Remove Shield link

- docs/static/releasenotes.asciidoc
Forwardport 7.9 release notes #12179 to 7.x branch
> Doc:Forwardport Release notes 7.9.0 to 7.x 

- docs/static/reloading-config.asciidoc
**PREVIEW:** https://logstash_12191.docs-preview.app.elstc.co/guide/en/logstash/master/reloading-config.html#reloading-config
> Doc:Add note that stdin input doesn't allow config reloading

- docs/static/redirects.asciidoc
> [Backport]Doc:Add redirect from multiline filter to multiline codec for 7.x

- docs/static/redirects.asciidoc
> [Backport]Doc:Add redirect from multiline filter to multiline codec to 7.9

- docs/static/releasenotes.asciidoc
Fix formatting in release notes before forwardporting to 7.x branch.
> Doc:Fix release notes formatting for consistency

- docs/static/releasenotes.asciidoc
Forwardports 7.9.1 release notes (#12220 and #12224) to 7.x branch
> Doc:Forwardport Release notes 7.9.1 to 7.x

- docs/static/troubleshooting.asciidoc
Logging settings can affect performances
> [DOC] Logging settings can affect performances

- docs/static/troubleshooting.asciidoc
Logging settings can affect performances
Backports #12246 to 7.x branch
> [DOC][Backport-7.x] Logging settings can affect performances

- docker/templates/Dockerfile.j2
> [7x backport] Update ubi8-minimal to pull from elastic docker registry

- docs/static/dead-letter-queues.asciidoc
**PREVIEW:**  https://logstash_12209.docs-preview.app.elstc.co/guide/en/logstash/master/dead-letter-queues.html
> Doc:Clarify how Bulk API interacts with DLQ

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12256.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-7-9-2.html
> 7.9.2 Release Notes

- docs/static/releasenotes.asciidoc
* Add JDK 15 compatibility notice
* Add more information to app_search missed dependency fixed issue
> 7.9.2 Release Notes (#12256)

- bin/logstash
- bin/logstash.lib.sh
- bin/setup.bat
- bin/system-install
- build.gradle
- docker/templates/Dockerfile.j2
- qa/acceptance/spec/lib/artifact_operation_spec.rb
- qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
- qa/acceptance/spec/shared_examples/installed_with_jdk.rb
- qa/docker/shared_examples/container.rb
- qa/docker/spec/spec_helper.rb
- qa/integration/specs/cli/prepare_offline_pack_spec.rb
- qa/rspec/commands.rb
- qa/rspec/commands/base.rb
- qa/rspec/commands/debian.rb
- qa/rspec/commands/redhat.rb
- qa/rspec/commands/suse.rb
- qa/rspec/commands/system_helpers.rb
- qa/rspec/matchers/be_running.rb
- rakelib/artifacts.rake
- versions.yml
Backport PR of #11845 to `7.x`
> Bundle JDK (AdoptOpenJDK 11) in Logstash artifacts (x86_64)

- build.gradle
- qa/rspec/commands/debian.rb
- qa/rspec/commands/redhat.rb
- rakelib/artifacts.rake
Backport PR of #12267 to `7.x`
> Bundle JDK (AdoptOpenJDK 11) in Logstash artifacts (ARM64)

- NOTICE.TXT
Update the NOTICE.txt file with the latest versions of the gems included with Logstash
> Update license information

- NOTICE.TXT
> [7x] Update license information

- NOTICE.TXT
- logstash-core/lib/logstash/dependency_report.rb
- tools/dependencies-report/src/main/resources/acceptableLicenses.csv
- tools/dependencies-report/src/main/resources/licenseMapping.csv
- tools/dependencies-report/src/main/resources/notices/Red Hat Universal Base Image minimal-NOTICE.txt
> Add RedHat Univeral Base Image license information

- logstash-core/logstash-core.gemspec
> fix dependency issue, jruby-openssl, of integration test

- devtools/backport
- devtools/create_pr
Adds devtools/create_pr and devtools/backport scripts to ease automatic creation of PRs.
> Add devtools to ease auto-creation of new PRs and Backport PRs

- build.gradle
- logstash-core/logstash-core.gemspec
- qa/integration/integration_tests.gemspec
**backport** https://github.com/elastic/logstash/pull/12361
> Build: properly isolate integration (test) env setup (#12361)

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12353.docs-preview.app.elstc.co/guide/en/logstash/7.9/logstash-7-9-3.html
> Release notes for version 7.9.3

- docs/static/releasenotes.asciidoc
> Forward of 7.9.3 release notes

- qa/rspec/commands/redhat.rb
> Fix in QA test, Backport PR of #12372

- versions.yml
Updates jrackson to latest version and jackson-databind to `2.9.10.6`
> Update jrjackons and databind versions

- versions.yml
> [7x backport] Update jrjackson and databind versions

- docs/static/jvm.asciidoc
Documents options and impacts of bundled JDK
**PREVIEW:**  https://logstash_12369.docs-preview.app.elstc.co/guide/en/logstash/master/getting-started-with-logstash.html#ls-jvm
> Doc: Add bundled JDK info

- docs/static/jvm.asciidoc
Document options and impacts of bundled JDK
Backports: #12369
> [Backport] Doc: Add bundled JDK info

- logstash-core/lib/logstash/pipeline_action/delete.rb
- logstash-core/lib/logstash/pipelines_registry.rb
- logstash-core/lib/logstash/state_resolver.rb
- logstash-core/spec/logstash/pipelines_registry_spec.rb
- logstash-core/spec/logstash/state_resolver_spec.rb
https://github.com/elastic/logstash/pull/12414
> [backport 7x] delete pipeline in registry (#12414)

- logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java
- logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
- logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java
- x-pack/lib/config_management/elasticsearch_source.rb
- x-pack/qa/integration/management/multiple_pipelines_spec.rb
- x-pack/qa/integration/support/helpers.rb
https://github.com/elastic/logstash/pull/12389
> [backport 7x] fix delete and recreate pipeline with same pipeline ID and config string (#12389)

- Gemfile.jruby-2.5.lock.release
- README.md
- versions.yml
> Bump version 7.10.1

- docs/static/releasenotes.asciidoc
Forwardports #12420 to 7.x branch
> [Forward] Doc:Release notes 7.10.0 to 7.x

- docs/static/logging.asciidoc
Backport of #12467 to `7.x`
(cherry picked from commit 7db4692044213f1b5d464712b1d73400be143583)
-
> [Doc] expanded the description of how to obtain the logger's names form Java and Ruby class names

- Gemfile.jruby-2.5.lock.release
on top of the previous update: https://github.com/elastic/logstash/pull/12475 (from last week)
> Update (patch) gem versions for 7.10.1 again

- docs/static/releasenotes.asciidoc
Forward port of 7.10.1 release notes (#12489)
> Forward port of 7.10.1 release notes to 7.x

- Gemfile.jruby-2.5.lock.release
- README.md
- versions.yml
> bumped version to 7.10.2

- CONTRIBUTING.md
Inform community/contributors about [Elastic Contributor Program](https://www.elastic.co/community/contributor).
Fixes: #12431
> Doc: Add info on contributor program

- CONTRIBUTING.md
> Doc: Add info on contributor program 

- logstash-core/src/main/java/org/logstash/Logstash.java
- qa/integration/fixtures/fatal_error_spec.yml
- qa/integration/specs/fatal_error_spec.rb
(clean) **BACK-PORT https://github.com/elastic/logstash/pull/12470** for 7.x
>  Fix: make sure LS exits when running into fatal errors

- bin/logstash
- bin/logstash.bat
- bin/logstash.lib.sh
- config/jvm.options
- docs/static/config-details.asciidoc
- logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java
- logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Clean packport of #12530 to `7.x`
commit: 7ba8c754585c32bf1c7a35932a7c6ff108b2691c
> Introduction of conditional in jvm.options file (#12530)

- docs/static/security/logstash.asciidoc
> Doc: Clarify minimum privileges for logstash_writer role

- docs/static/security/logstash.asciidoc
Backports: #12613
Fixes: #12612
> [Doc] Clarify minimum privileges for logstash_writer role 7.x

- docs/static/security/logstash.asciidoc
Backports: #12613
Fixes: #12612
> [Doc] Clarify minimum privileges for logstash_writer role 7.11

- docs/static/security/logstash.asciidoc
Backports:  #12613
Fixes: #12612
> [Doc] Clarify minimum privileges for logstash_writer role 7.10

- build.gradle
Ckean backport or PR #12586 to `7.x` branch
commit: dd9f2b7a0ad17d2f31ba6ea69a695283d2dbbf07
> Fix the run of copyEs and downloadEs gradle task. (#12586)

- docs/static/releasenotes.asciidoc
**PREVIEW:**  https://logstash_12596.docs-preview.app.elstc.co/guide/en/logstash/7.11/logstash-7-11-0.html
> Release notes draft for 7.11.0

- docs/static/releasenotes.asciidoc
Follow up to https://github.com/elastic/logstash/pull/12596
**PREVIEW:** https://logstash_12648.docs-preview.app.elstc.co/guide/en/logstash/7.11/logstash-7-11-0.html
> Doc: Add kafka confluent support to release notes

- docs/static/releasenotes.asciidoc
Forward port of #12596 and #12648 to 7.x branch
> Forward port of release notes to 7.x (#12596)

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12595.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-14.html
> Release notes draft for 6.8.14

- Gemfile.jruby-2.5.lock.release
- README.md
- versions.yml
Update version of Logstash to 7.11.1
> bump version to 7.11.1

- Gemfile.jruby-2.5.lock.release
- README.md
- versions.yml
> bump version to 6.8.15

- .ci/matrix-runtime-javas.yml
Invalidate commit 8c3ff551ede17e23102b6857bb8cb233969ccfd9 of of PR #12537 , moves from OpenJDK 15 to AdoptOpenJDK 15
-
> Switch to AdoptOpenJDK15 from OpenJDK15

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12674.docs-preview.app.elstc.co/guide/en/logstash/7.11/logstash-7-11-1.html
> Release notes draft for 7.11.1

- docs/static/releasenotes.asciidoc
> Doc: Forwardport Release notes for 7.11.1  to 7.x

- versions.yml
Update adoptopenjdk version to 11.0.10+9
> update jdk to 11.0.10+9

- docs/index.asciidoc
> Doc: Replace relative paths with docs-root attributes for 7.x

- docs/index.asciidoc
> Doc: Replace relative paths with docs-root attributes for 7.11

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12726.docs-preview.app.elstc.co/guide/en/logstash/7.11/logstash-7-11-2.html
> Release notes draft for 7.11.2

- Gemfile.jruby-2.5.lock.release
- README.md
- versions.yml
> Bump version 7.11.3

- docs/static/security/logstash.asciidoc
> Doc: Change protocol to https for 7.11

- docs/static/security/logstash.asciidoc
> Doc: Change protocol to https for 7.x

- docs/static/security/logstash.asciidoc
> Doc: Change protocol to https for 7.12

- docs/static/releasenotes.asciidoc
Forwardports release notes for 7.11.1 (#12674) and 7.11.2 (#12742) to 7.12 branch
> Forwardport release notes for 7.11.1 and 7.11.2 to 7.12 branch

- docs/static/releasenotes.asciidoc
> Doc: Add placeholder and coming tag for 6.18.15 release notes

- docs/static/releasenotes.asciidoc
> Doc:Add placeholder and coming tag for 7.12.0 release notes

- docs/static/releasenotes.asciidoc
**Preview:** https://logstash_12683.docs-preview.app.elstc.co/guide/en/logstash/7.12/logstash-7-12-0.html
> Release notes for 7.12.0

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12757.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-15.html
> Release notes for 6.8.15

- docs/static/releasenotes.asciidoc
> Doc: Remove stray tag in release notes header

- docs/static/releasenotes.asciidoc
https://logstash_12768.docs-preview.app.elstc.co/guide/en/logstash/7.12/logstash-7-12-0.html
[rn:skip]
> Doc: Rework security update in 7.12.0 release notes

- docs/static/releasenotes.asciidoc
https://logstash_12769.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-15.html
[rn:skip]
> Doc: Rework security update in 6.8.15 release notes

- docs/static/releasenotes.asciidoc
Forwardports 7.11.2 release notes  (#12726) to 7.x branch
> Forwardport release notes for 7.11.2 to 7.x branch

- docs/static/releasenotes.asciidoc
Forwardports #12762, #12683, #12768 to 7.x branch
[rn:skip]
> Forwardport release notes for 7.12.0 to 7.x branch

- tools/benchmark-cli/README.md
- tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/BenchmarkMeta.java
- tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/Main.java
- tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/cases/CustomTestCase.java
- tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/ui/UserInput.java
Adds another flag to the Benckmark CLI to allow passing a data file to the custom test case.
This allows to run the Benchmark CLI in a custom test case with a custom config and a custom dataset.
Updated the readme to reflect the current state of command line arguments.
This allows for test cases with previously captured data.
You can use the Apache dataset manually and provide apache config and dataset to a custom testcase.
-
> Adds option to pass custom data to the benchmark CLI

- docs/static/pipeline-pipeline-config.asciidoc
The conditionals in the distributor pattern section are not correct, as string comparisons require quotes around the value being compared against. Added quotes around them to fix this.
[rn:skip]
fixes a typo in the distributor pattern section of the pipeline-to-pipeline docs
The example in our docs is incorrect, and can misguide a user trying to use the example. 
There are no code changes with this PR, it is strictly for the docs
-
> updated distributor pattern section

- docs/static/pipeline-pipeline-config.asciidoc
Backport PR #12810 to 7.x branch. Original message: 
The conditionals in the distributor pattern section are not correct, as string comparisons require quotes around the value being compared against. Added quotes around them to fix this.
[rn:skip]
fixes a typo in the distributor pattern section of the pipeline-to-pipeline docs
The example in our docs is incorrect, and can misguide a user trying to use the example. 
There are no code changes with this PR, it is strictly for the docs
-
> Backport PR #12810 to 7.x: updated distributor pattern section

- logstash-core/lib/logstash/plugins/registry.rb
- logstash-core/spec/logstash/java_pipeline_spec.rb
- logstash-core/spec/logstash/plugins/registry_spec.rb
- logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
- logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java
- logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
- logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
This PR is backport of 2 PRs related to plugin alias usage:
- #12799 is a refactoring for the following
- #12796 usage of aliased plugins
Relates to #12793
> [Backport 7.x] plugin alias handling in logstash-core

- Gemfile.jruby-2.5.lock.release
make elasticsearch output to 11.0.1
> bump version for 7.13.0

- versions.yml
> bump core version to 7.14.0

- docs/static/releasenotes.asciidoc
to be merged 1 day before release (~ Apr 27th)
> Update release notes for 7.12.1

- Gemfile.jruby-2.5.lock.release
- versions.yml
> Version Bump to 7.12.1

- x-pack/lib/filters/geoip/database_manager.rb
- x-pack/lib/filters/geoip/database_metadata.rb
- x-pack/lib/filters/geoip/download_manager.rb
- x-pack/lib/filters/geoip/util.rb
- x-pack/spec/filters/geoip/database_manager_spec.rb
- x-pack/spec/filters/geoip/database_metadata_spec.rb
- x-pack/spec/filters/geoip/download_manager_spec.rb
- x-pack/spec/filters/geoip/test_helper.rb
Backports the following commits to 7.13:
- change download path for geoip plugin (#12863)
> [7.13] change download path for geoip plugin (#12863)

- x-pack/lib/filters/geoip/database_manager.rb
- x-pack/lib/filters/geoip/database_metadata.rb
- x-pack/lib/filters/geoip/download_manager.rb
- x-pack/lib/filters/geoip/util.rb
- x-pack/spec/filters/geoip/database_manager_spec.rb
- x-pack/spec/filters/geoip/database_metadata_spec.rb
- x-pack/spec/filters/geoip/download_manager_spec.rb
- x-pack/spec/filters/geoip/test_helper.rb
- change download path for geoip plugin (#12863)
> [7.x] change download path for geoip plugin (#12863)

- versions.yml
Updates bundled `AdoptopenJDK` to `11.0.11+9`
> Update bundled JDK to 11.0.11+9

- docs/index.asciidoc
- docs/static/contrib-acceptance.asciidoc
- docs/static/contribute-core.asciidoc
- docs/static/contributing-java-plugin.asciidoc
- docs/static/contributing-patch.asciidoc
- docs/static/contributing-to-logstash.asciidoc
- docs/static/doc-for-plugin.asciidoc
- docs/static/include/pluginbody.asciidoc
- docs/static/listing-a-plugin.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/submitting-a-plugin.asciidoc
**Preview:** https://logstash_12879.docs-preview.app.elstc.co/guide/en/logstash/master/contributing-to-logstash.html
[rn:skip]
Clarifies ways to contribute to Logstash and adds acceptance criteria
> Doc: Update contributing steps and guidelines

- x-pack/lib/filters/geoip/database_manager.rb
- x-pack/lib/filters/geoip/database_metadata.rb
- x-pack/lib/filters/geoip/util.rb
- x-pack/spec/filters/geoip/database_manager_spec.rb
- x-pack/spec/filters/geoip/database_metadata_spec.rb
Backports the following commits to 7.13:
- Geoip use cc indefinitely (#12888)
> [7.13] Geoip use cc indefinitely (#12888)

- x-pack/lib/filters/geoip/database_manager.rb
- x-pack/lib/filters/geoip/database_metadata.rb
- x-pack/lib/filters/geoip/util.rb
- x-pack/spec/filters/geoip/database_manager_spec.rb
- x-pack/spec/filters/geoip/database_metadata_spec.rb
- Geoip use cc indefinitely (#12888)
> [7.x] Geoip use cc indefinitely (#12888)

- docs/index.asciidoc
- docs/static/contrib-acceptance.asciidoc
- docs/static/contribute-core.asciidoc
- docs/static/contributing-java-plugin.asciidoc
- docs/static/contributing-patch.asciidoc
- docs/static/contributing-to-logstash.asciidoc
- docs/static/doc-for-plugin.asciidoc
- docs/static/include/pluginbody.asciidoc
- docs/static/listing-a-plugin.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/submitting-a-plugin.asciidoc
Backports  #12879 to 7.13
[rn:skip]
> Doc: Update contributing steps and guidelines (backport to 7.13)

- docs/index.asciidoc
- docs/static/contrib-acceptance.asciidoc
- docs/static/contribute-core.asciidoc
- docs/static/contributing-java-plugin.asciidoc
- docs/static/contributing-patch.asciidoc
- docs/static/contributing-to-logstash.asciidoc
- docs/static/doc-for-plugin.asciidoc
- docs/static/include/pluginbody.asciidoc
- docs/static/listing-a-plugin.asciidoc
- docs/static/plugin-generator.asciidoc
- docs/static/plugin-manager.asciidoc
- docs/static/submitting-a-plugin.asciidoc
Backports  #12879 to 7.12
[rn:skip]
> Doc: Update contributing steps and guidelines (backport to 7.12)

- docker/templates/Dockerfile.j2
Backport of 
- d0e79553b5d77695825faa493c039682b3277e64 from #12891
- d1b12ded1d94de0b9441285530d4a07525f31693 from #12902
to `7.12`
> [Backport 7.12][Build] 12891 12902 7.12

- Gemfile.jruby-2.5.lock.release
remove GeoIP database service doc
> pin geoip 7.1.2

- docs/static/releasenotes.asciidoc
Forward port PR#12825 to 7.13 branch. Original message:
* Update release notes for 7.12.1
* Docs: cleanup release notes draft
* Docs: extract 2 notable issues
> Forward Port PR #12825 to 7.13:Update release notes for 7.12.1

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12843.docs-preview.app.elstc.co/guide/en/logstash/7.13/logstash-7-13-0.html
> Update release notes for 7.13.0

- Gemfile.jruby-2.5.lock.release
- README.md
- versions.yml
Release: bump version to 6.8.17
> Release: bump version to 6.8.17

- Gemfile.jruby-2.5.lock.release
- versions.yml
Release: bump version to 7.13.1
> Release: bump version to 7.13.1

- docs/static/releasenotes.asciidoc
Forwardports #12843 to 7.x branch
**PREVIEW:** https://logstash_12932.docs-preview.app.elstc.co/guide/en/logstash/7.x/logstash-7-13-0.html
[rn:skip]
> Forwardport release notes for 7.13.0 to 7.x branch

- tools/release/generate_release_notes.rb
Backports #12949 to 7.x
[rn:skip]
> Internal: Update messaging in release notes script

- tools/release/generate_release_notes.rb
> Internal: Update messaging in release notes script 

- docs/static/listing-a-plugin.asciidoc
Improves the List your Plugin section by providing a template on how to file an issue.
> Add a template on how to create an issue when requesting to list a plugin in docs

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12946.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-7-13-1.html
> Release notes for 7.13.1

- logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
[rn:skip]
This PR is refactoring of if conditions in https://github.com/elastic/logstash/blob/2e413c6e9245cd1be35cdde49f6785cd82656519/logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java#L191-L218 to streamline the "good path" and make evident which are the error conditions.
Doesn't impact the user.
> Refactoring of JavaKeyStore.getKeyStorePassword method to simplify ifs conditions

- Gemfile.jruby-2.5.lock.release
in preparation for the next 7.13.2 release
> Deps: update lock file for 7.13.2

- Gemfile.jruby-2.5.lock.release
pin the gem to the version fixed illegal field value
> Update lock file for 7.13.2

- docs/static/monitoring/monitoring-mb.asciidoc
> Doc: Remove unused tagged regions

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_12981.docs-preview.app.elstc.co/guide/en/logstash/7.13/logstash-7-13-2.html
> Release notes draft for 7.13.2

- docs/static/releasenotes.asciidoc
> Forwardport 7.13.2 release notes draft to 7.x

- logstash-core/logstash-core.gemspec
- x-pack/lib/filters/geoip/database_manager.rb
- x-pack/lib/filters/geoip/database_metadata.rb
- x-pack/lib/filters/geoip/download_manager.rb
- x-pack/lib/filters/geoip/util.rb
- x-pack/spec/filters/geoip/database_manager_spec.rb
- x-pack/spec/filters/geoip/database_metadata_spec.rb
- x-pack/spec/filters/geoip/download_manager_spec.rb
- x-pack/spec/filters/geoip/fixtures/normal_resp.json
- x-pack/spec/filters/geoip/test_helper.rb
- fix database manager with multiple pipelines (#12862)
> [7.x] fix database manager with multiple pipelines (#12862)

- docs/static/monitoring/monitoring-apis.asciidoc
[rn:skip] 
Backports #13019 to 7.x
> Doc: Add geoip database API to node stats 

- logstash-core/lib/logstash/plugin.rb
- logstash-core/lib/logstash/plugins/event_factory_support.rb
- logstash-core/lib/logstash/util/thread_safe_attributes.rb
- logstash-core/spec/logstash/event_spec.rb
- logstash-core/spec/logstash/plugins/event_factory_support_spec.rb
- logstash-core/src/main/java/org/logstash/Event.java
- logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
- logstash-core/src/main/java/org/logstash/plugins/BasicEventFactory.java
- logstash-core/src/main/java/org/logstash/plugins/ContextImpl.java
- logstash-core/src/main/java/org/logstash/util/UtilExt.java
- Feat: event factory support (#13017)
> [7.x] Feat: event factory support (#13017)

- build.gradle
This reverts commit 149ee41a8b07b318eb17e1e72af5c743a5002468.
Original PR: #12847 
[rn:skip]
The Gradle `runIntegrationTests` has to download the necessary ES and Fielbeats and then launch the task `:logstash-integration-tests:integrationTests`.
`:logstash-integration-tests:integrationTests` is not intended to be launched directly.
Impacts the developer that launched `./gradlew :logstash-integration-tests:integrationTests ` but to run integration test it has to run `runIntegrationTests `
-
> Revert #12847 

- docs/static/releasenotes.asciidoc
Forwardports #13031 to 7.x branch
> Forwardport 7.13.3 release notes to 7.x 

- docs/static/getting-started-with-logstash.asciidoc
[rn:skip] 
Backports #12706 and #12714 to 7.x
> Doc: Include Windows and Unix commands to run basic pipeline

- docs/static/troubleshoot/ts-kafka.asciidoc
[rn:skip] 
Backports #13073 to 7.x
> Doc: Add kafka schema registry setting to troubleshooting to 7.x

- Gemfile.jruby-2.5.lock.release
[rn:skip] - changes will be included in generated release notes
performs patch-level upgrades of our plugins, in preparation for the in-flight 7.14.0. Since we are post-FF and already have build candidates, this is patch-level only and uses the current lockfile as its baseline.
Ensures upstream fixes in plugins make their way into the next minor release of Logstash
> bump patch level dependencies for 7.14.0

- Gemfile.jruby-2.5.lock.release
[rn:skip] - plugin changes will show in generated release notes
Ensures we pull in all released patch-level fixes to the plugins that are distributed with Logstash in advance of the 7.14.0 release.
This changeset also includes one minor-level change, which includes a low-risk configuration option in the Kafka input to allow a user to opt out of a behaviour that is known to not work; when left unspecified, the plugin behaves exactly as before.
We have fixed plugins, and this makes sure our users get the fixes instead of outdated versions :)
- ~[ ] I …
> bump plugins for 7.14 release

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13061.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-7-13-4.html
> Release notes for 7.13.4

- Gemfile.jruby-2.5.lock.release
- versions.yml
> Bump version to 7.13.5

- docs/static/keystore.asciidoc
Backports #12779 to 7.x
[rn:skip]
> Doc: Fix typo and adjust keystore text 7.x

- docs/static/keystore.asciidoc
Backports #12779 to 7.14
[rn:skip]
> Doc: Fix typo and adjust keystore text 7.14

- docs/static/dead-letter-queues.asciidoc
- docs/static/persistent-queues.asciidoc
- docs/static/resiliency.asciidoc
Backports: #12959
Fixes: #12923
Related: #10493
[rn:skip]
> Doc: Enhance and expand DLQ docs 7.x

- docs/static/dead-letter-queues.asciidoc
- docs/static/persistent-queues.asciidoc
- docs/static/resiliency.asciidoc
Backports: #12959
Fixes: #12923
Related: #10493
[rn:skip]
> Doc: Enhance and expand DLQ docs 7.14

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13089.docs-preview.app.elstc.co/guide/en/logstash/7.14/logstash-7-14-0.html
> Release notes for 7.14.0

- docs/static/java-filter.asciidoc
Fixes #11519
[rn:skip]
Documentation fix, which is confusing users - on master already.
- https://github.com/elastic/logstash/pull/13114
> Backport Docs: fix java filter unit test link

- docs/static/releasenotes.asciidoc
Forwardports 7.14.0 release notes (#13089) to 7.x branch
> Doc: Forwardport release notes for 7.14.0 to 7.x branch

- build.gradle
- logstash-core/benchmarks/build.gradle
- logstash-core/build.gradle
- rubyUtils.gradle
- tools/benchmark-cli/build.gradle
- tools/dependencies-report/build.gradle
- tools/ingest-converter/build.gradle
[rn:skip]
Updates all the Gradle usages of `snakeyaml` to version `1.29`
Doesn't impact the user
- Fixes #13127
> Update Snakeyaml version to 1.29

- docs/static/releasenotes.asciidoc
> Doc: Forwardport Aarch64 support to 7.14.0 release notes to 7.15

- docs/static/releasenotes.asciidoc
Add placeholder, section titles, and `coming` tag for 7.15.0 release notes
> Doc: Add placeholder for 7.15.0 release notes

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- logstash-core/benchmarks/build.gradle
- qa/integration/build.gradle
- tools/benchmark-cli/build.gradle
- tools/dependencies-report/build.gradle
- tools/ingest-converter/build.gradle
[rn:skip] 
Switch to Gradle 7, this PR has to be applied on top of #13182 and #13183.
- Updates the Gradle wrapper to version `7.2`
- Remove the deprecated `jcenter` and where it was used to retrieve Gradle's plugins it switches to `gradlePluginPortal`
- insert an explicit dependency from test task to the log4j.properties manipulation task used in integration
The user is not influenced by this change
Simply run a build  task using the wrapped `./gradlew build`
- Relates #13177
- Requires #13182
- Requires #13183
> Switched to Gradle 7

- Dockerfile
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/logstash/gradle/tooling/ListProjectDependencies.groovy
- buildSrc/src/test/groovy/org/logstash/gradle/tooling/ListProjectDependenciesTest.groovy
- gradle/wrapper/gradle-wrapper.properties
- logstash-core/benchmarks/build.gradle
- qa/integration/build.gradle
- tools/benchmark-cli/build.gradle
- tools/dependencies-report/build.gradle
- tools/dependencies-report/src/main/resources/licenseMapping.csv
- tools/dependencies-report/src/main/resources/notices/com.fasterxml.jackson.dataformat!jackson-dataformat-yaml-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-1.2-api-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-jcl-NOTICE.txt
- tools/ingest-converter/build.gradle
This backport PR bring to branch `7.x` all the PRs related to migrating to Gradle 7, #13182 #13183 #13184 
The user is not directly impacted
-  Relates #13177
> [backport 7.x] Gradle 7 updates, issue #13177

- .ci/matrix-runtime-javas.yml
[rn:skip] 
Updates the supported Java versions list to test in CI to JDK 11 and JDK 15
-
> Updates JDKs available to test only to versions 11 and 15

- tools/dependencies-report/src/main/resources/licenseMapping.csv
- tools/dependencies-report/src/main/resources/notices/rexml-NOTICE.txt
Clean backport of #13209 to branch `7.14`
(cherry picked from commit 6ed2eea890e9af334af39ba63541ab58c9f8e7bc)
> [backport 7.14] Added rexml notice to license list (#13209)

- Gemfile.jruby-2.5.lock.release
[rn:skip]
Updates all plugins at patch level. The update of `xml-simple ` from version `1.1.8` to `1.1.9` adds transitively the `rexml`.
This needs a backport of #13209 to branch `7.14`, present in #13220
Brings in latest bugfixes for plugins.
> Bump plugins for 7.14.2 release

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13228.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-8-0-0-alpha2.html
> Release notes for 8.0.0-alpha2

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13222.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-7-14-2.html
> Release notes for 7.14.2

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13230.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-19.html
> Release notes for 6.8.19

- docs/static/releasenotes.asciidoc
[rn:skip]
Forward port the release notes of `7.14.2` to `7.x` branch.
- Relates #13222
> [forwardport] 7.14.2 release notes to 7.x

- docs/static/configuration.asciidoc
[rn:skip] 
Updates docs with info about date math in conditionals and provides a workaround example.
Brings topic up to current documentation standards for heading capitalization and tagging
**PREVIEW:** https://logstash_13199.docs-preview.app.elstc.co/guide/en/logstash/master/event-dependent-configuration.html#conditionals
> Doc: Add note and example for date math in conditionals

- docs/static/releasenotes.asciidoc
[rn:skip]
Forward port the release notes of `7.15.0` to `7.x` branch.
> Forward port of 7.15.0 release notes to 7.x

- docker/data/golang/Dockerfile
- x-pack/spec/filters/geoip/download_manager_spec.rb
[rn:skip] 
Update golang image from 1.8 to 1.17.1 to get rid of SSL verification issue
Disable geoip download manager test to silent Faraday::SSLError certificate verify failed
A follow issue will replace Faraday lib with Manticore in download_manager
Allow jenkins to build snapshot image
-
> update golang image

- docs/include/attributes-ls.asciidoc
- docs/include/attributes-lsplugins.asciidoc
- docs/index.asciidoc
> Doc: Add shared attribute for messaging ecs default info 7.x

- docs/include/attributes-ls.asciidoc
- docs/include/attributes-lsplugins.asciidoc
- docs/index.asciidoc
> Doc: Add shared attribute for messaging ecs default info 7.15

- docs/include/attributes-ls.asciidoc
- docs/include/attributes-lsplugins.asciidoc
- docs/index.asciidoc
> Doc: Add shared attribute for messaging ecs default info 7.14

- docs/index.asciidoc
- docs/static/mem-queue.asciidoc
- docs/static/resiliency.asciidoc
[rn:skip]
Backports #13246 to 7.x
> Doc: Add topic and expand info for in-memory queue

- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
[rn:skip]
**PREVIEW:** https://logstash_13368.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-centralized-pipeline-management.html
> Doc: Update central management subscription info

- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
> Doc: Update central management license info 8.0

- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
> Doc: Update central management license info 7.15

- docs/static/management/centralized-pipelines.asciidoc
- docs/static/management/configuring-centralized-pipelines.asciidoc
> Doc: Update central management license info 7.16

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13390.docs-preview.app.elstc.co/guide/en/logstash/7.15/logstash-7-15-2.html
> Release notes for 7.15.2

- docs/static/breaking-changes.asciidoc
> Doc: Add breaking changes 8.0

- docs/static/persistent-queues.asciidoc
- docs/static/pipeline-pipeline-config.asciidoc
> Doc: Expand PQ content for pipeline-pipeline 8.0

- docs/static/persistent-queues.asciidoc
- docs/static/pipeline-pipeline-config.asciidoc
> Doc: Expand PQ content for pipeline-pipeline 7.16

- docs/static/persistent-queues.asciidoc
- docs/static/pipeline-pipeline-config.asciidoc
> Doc: Expand PQ content for pipeline-pipeline 7.15

- docs/static/releasenotes.asciidoc
Port of 7.15.2 release notes (#13390) for 7.16
[rn:skip]
> Forward Port: Release notes for 7.15.2 (#13390)

- docs/static/releasenotes.asciidoc
PREVIEW: https://logstash_13436.docs-preview.app.elstc.co/guide/en/logstash/7.16/logstash-7-16-0.html
> Release notes for 7.16.0

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13513.docs-preview.app.elstc.co/guide/en/logstash/7.16/logstash-7-16-1.html
> Doc: Add filter known issue to 7.16.1 release notes

- docs/static/releasenotes.asciidoc
Add content from #13513 to 7.15.2 release notes (not a true backport)
> Doc: Add filter known issue to 7.15.2 release notes

- logstash-core/build.gradle
To err on the side of caution it'd be preferable to use log4j 2.16.0 due to CVE-2021-45046
-
> Bump log4j version to 2.16.0 per CVE-2021-45046

- README.md
leftover from 6.8.22 version bumping
> update readme wrt 6.8.22

- logstash-core/build.gradle
Backport PR #13518 to 7.16 branch. Original message: 
To err on the side of caution it'd be preferable to use log4j 2.16.0 due to CVE-2021-45046
-
> Backport PR #13518 to 7.16: Bump log4j version to 2.16.0 per CVE-2021-45046

- logstash-core/build.gradle
Backport PR #13518 to 8.0 branch. Original message: 
To err on the side of caution it'd be preferable to use log4j 2.16.0 due to CVE-2021-45046
-
> Backport PR #13518 to 8.0: Bump log4j version to 2.16.0 per CVE-2021-45046

- Gemfile.jruby-2.5.lock.release
- versions.yml
[rn:skip]
Update version info for the (new) 7.17 branch (branched from 7.16).
> Chore: bump version to 7.17.0 (snapshot)

- docs/static/pipeline-pipeline-config.asciidoc
> Doc: remove PQ on input for Output Isolator 8.0

- docs/static/pipeline-pipeline-config.asciidoc
> Doc: remove PQ on input for Output Isolator 7.17

- docs/static/pipeline-pipeline-config.asciidoc
> Doc: remove PQ on input for Output Isolator 7.16

- docs/static/jvm.asciidoc
> Doc: Add anchor to bundled jdk info 8.0

- docs/static/jvm.asciidoc
> Doc: Add anchor to bundled jdk info 7.17

- docs/static/jvm.asciidoc
> Doc: Add anchor to bundled jdk info 7.16

- Gemfile.jruby-2.5.lock.release
> update lock file for 7.17.0

- Gemfile.jruby-2.5.lock.release
> update lock file for 7.16.2

- Gemfile.jruby-2.5.lock.release
- versions.yml
[rn:skip]
Bump version to next development SNAPSHOT.
> bump version to 7.16.3

- Gemfile.jruby-2.5.lock.release
> update lock file for 8.0.0

- logstash-core/lib/logstash/agent.rb
- logstash-core/lib/logstash/runner.rb
- x-pack/lib/filters/geoip/database_manager.rb
- x-pack/lib/filters/geoip/database_metric.rb
- x-pack/lib/filters/geoip/util.rb
- x-pack/spec/filters/geoip/database_manager_spec.rb
- Fix unknown type warning of geoip metrics (#13382)
> [8.0] Fix unknown type warning of geoip metrics (#13382)

- logstash-core/lib/logstash/util/substitution_variables.rb
- logstash-core/src/main/java/org/logstash/execution/JavaBasePipelineExt.java
Fix a crash of Logstash in initialization when using the `logstash-input-azure_eventhub`.
Sometime the deep_replace could be invoked by plugins, using the LogStash::Config::Mixin#validate.
This method receives a Ruby hash which could contains Java ArrayList instead of Ruby Array.
The iteration method `each_index` is not available for ArrayList, so resort to someform of plain old way.
Fixes problem with some plugins, like `input-azure_eventhub` liek described in #12760
- Closes #12760
> Avoid to itereate with each_index

- logstash-core/lib/logstash/runner.rb
[rn:skip]
Logs the JVM flags and options used in starting Logstash.
The user can immediately know which JVM options are effectively used to start Logstash. 
- Relates #13525
> Add info log of JVM flags used to configure Logstash

- config/logstash.yml
- docs/static/ecs-compatibility.asciidoc
[rn:skip]
Syncs ECS-related docs with our intent prior to the 7.last release
- adds entry for `pipeline.ecs_compatibility` to `config/logstash.yml`, which we failed to backport.
- removes caveats intended for pre-7.last
Makes our ECS compatibility effort more easily discoverable, especially for those upgrading to 7.last in advance of an upcoming 8.x upgrade.
- ~[x] I have commented my code, particularly in hard-to-understand areas~
-
> ecs: docs and comments syncing for 7.last

- docs/index.asciidoc
> Doc: Remove hard-coded edit_url links where possible 8.0

- Gemfile.jruby-2.5.lock.release
[rn:skip]
Updates plugins and dependencies
Include features and fixes from plugins and their dependencies
> bump dependencies for 7.17.0

- docs/static/persistent-queues.asciidoc
> [DOC] Clarify scope of queue settings 8.0

- docs/static/persistent-queues.asciidoc
> [DOC] Clarify scope of queue settings 7.17

- docs/static/persistent-queues.asciidoc
> [DOC] Clarify scope of queue settings 7.16

- docs/static/persistent-queues.asciidoc
> Backport pq setting info to 6.8

- logstash-core/spec/logstash/compiler/compiler_spec.rb
- logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
- logstash-core/src/main/java/org/logstash/config/ir/ConfigCompiler.java
- logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java
- logstash-core/src/main/java/org/logstash/config/ir/expression/ExpressionSubstitution.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/ComposedParallelStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/ComposedSequenceStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/IfStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/NoopStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/PluginStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/Statement.java
- logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
- logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
- logstash-core/src/test/java/org/logstash/config/ir/ConfigCompilerTest.java
- logstash-core/src/test/java/org/logstash/config/ir/EventConditionTest.java
- logstash-core/src/test/java/org/logstash/config/ir/IRHelpers.java
- logstash-core/src/test/java/org/logstash/config/ir/PipelineIRTest.java
- logstash-core/src/test/java/org/logstash/config/ir/expression/ExpressionSubstitutionTest.java
- logstash-core/src/test/java/org/logstash/config/ir/imperative/IfStatementTest.java
- logstash-core/src/test/java/org/logstash/config/ir/imperative/ImperativeToGraphtest.java
- logstash-core/src/test/java/org/logstash/plugins/factory/PluginFactoryExtTest.java
- qa/integration/fixtures/env_variables_condition_spec.yml
- qa/integration/specs/env_variables_condition_spec.rb
- qa/integration/specs/secret_store_spec.rb
- x-pack/spec/monitoring/inputs/metrics/state_event/lir_serializer_spec.rb
- Support env variable in condition (#13608)
> [7.17] Support env variable in condition (#13608)

- logstash-core/spec/logstash/compiler/compiler_spec.rb
- logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
- logstash-core/src/main/java/org/logstash/config/ir/ConfigCompiler.java
- logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java
- logstash-core/src/main/java/org/logstash/config/ir/expression/ExpressionSubstitution.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/ComposedParallelStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/ComposedSequenceStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/IfStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/NoopStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/PluginStatement.java
- logstash-core/src/main/java/org/logstash/config/ir/imperative/Statement.java
- logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
- logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
- logstash-core/src/test/java/org/logstash/config/ir/ConfigCompilerTest.java
- logstash-core/src/test/java/org/logstash/config/ir/EventConditionTest.java
- logstash-core/src/test/java/org/logstash/config/ir/IRHelpers.java
- logstash-core/src/test/java/org/logstash/config/ir/PipelineIRTest.java
- logstash-core/src/test/java/org/logstash/config/ir/expression/ExpressionSubstitutionTest.java
- logstash-core/src/test/java/org/logstash/config/ir/imperative/IfStatementTest.java
- logstash-core/src/test/java/org/logstash/config/ir/imperative/ImperativeToGraphtest.java
- logstash-core/src/test/java/org/logstash/plugins/factory/PluginFactoryExtTest.java
- qa/integration/fixtures/env_variables_condition_spec.yml
- qa/integration/specs/env_variables_condition_spec.rb
- qa/integration/specs/secret_store_spec.rb
- x-pack/spec/monitoring/inputs/metrics/state_event/lir_serializer_spec.rb
- Support env variable in condition (#13608)
> [8.0] Support env variable in condition (#13608)

- docs/static/configuration.asciidoc
remove the doc that mentions environment variable is not support in condition
> Revert [DOC] Clarify the scope of environment variable expansion

- docs/static/releasenotes.asciidoc
Add placeholder, section titles, and coming tag for 7.17.0 release notes
> Doc: Add placeholder for 7.17.0 release notes

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13690.docs-preview.app.elstc.co/guide/en/logstash/7.17/logstash-7-17-0.html
> Release notes draft for 7.17.0

- docs/static/security/es-security.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/security/ls-monitoring.asciidoc
- docs/static/security/tls-encryption.asciidoc
**Related:** #13573
**Follow-up issue:** #13620
Purpose: Capture and track valuable comments that we need to address, but are out of scope for this PR. 
**PREVIEW:** https://logstash_13597.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#es-security-on
> Doc: Add topic and content for es security on by default

- docs/static/security/es-security.asciidoc
- docs/static/security/logstash.asciidoc
- docs/static/security/ls-monitoring.asciidoc
- docs/static/security/tls-encryption.asciidoc
> Doc: Add topic and content for es security on by default 8.0

- docs/static/security/es-security.asciidoc
> Doc: Fix formatting for bulleted list 8.0

- Gemfile.jruby-2.5.lock.release
- versions.yml
Bump version for `7.17.1` development
> Bump for next 7.17.1

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13669.docs-preview.app.elstc.co/guide/en/logstash/8.0/logstash-8-0-0-rc2.html
> Release notes for 8.0.0-rc2

- versions.yml
> bump version to 8.2.0

- docs/static/breaking-changes-80.asciidoc
> Doc: Replace short link with full link 8.1

- docs/static/breaking-changes-80.asciidoc
> Doc: Replace short link with full link 8.0

- docs/static/breaking-changes-70.asciidoc
> Doc: Remove links to beats 7.x content 8.1

- docs/static/breaking-changes-70.asciidoc
> Doc: Remove links to beats 7.x content 8.0

- docs/static/upgrading.asciidoc
**PREVIEW:** https://logstash_13684.docs-preview.app.elstc.co/guide/en/logstash/master/upgrading-using-direct-download.html
[rn:skip]
During the time Logstash switched from a set of Ruby files plus one fat jar to multiple jars, with configuration files
and shell scripts that also needs to be updated. It's not anymore sufficient to suggest to unpack a new distribution
over an existing one. This is problematic when we add jars from version to version because drive to the pollution
of the classpath.
This commit redefines to steps to do this, in a safer way, backing up data and config folders.
-
> Update the Upgrading Using a Direct Download guide section.

- docs/static/breaking-changes-pre63.asciidoc
- docs/static/upgrading.asciidoc
Backports #13705 to the 8.0 branch
> Doc: Update upgrade info for 8.0 (backport to 8.0 branch)

- docs/static/breaking-changes-pre63.asciidoc
- docs/static/upgrading.asciidoc
> Doc: Update upgrade info for 8.0 (backport to 8.1 branch) 

- docs/static/releasenotes.asciidoc
Forward port of #13750 to `8.1`
> [Forwarport 8.1] release notes 8.0.0 rc2 and ga

- versions.yml
**Merge after `8.0.0` is out**
> Bump versions.yml for 8.0.1

- qa/README.md
- qa/integration/README.md
> Doc:Update qa readme with BUILD_JAVA_HOME setting info [8.1]

- qa/README.md
- qa/integration/README.md
> Doc:Update qa readme with BUILD_JAVA_HOME setting info [8.0]

- qa/README.md
- qa/integration/README.md
> Doc:Update qa readme with BUILD_JAVA_HOME setting info [7.17]

- README.md
> Add reference to java 17 to README.md

- versions.yml
https://www.oracle.com/java/technologies/javase/11-0-14-relnotes.html
> bump jdk to 11.0.14.1+1

- docs/static/getting-started-with-logstash.asciidoc
- docs/static/redirects.asciidoc
**PREVIEWS:** 
* https://logstash_13772.docs-preview.app.elstc.co/guide/en/logstash/master/brew.html
* https://logstash_13772.docs-preview.app.elstc.co/guide/en/logstash/master/upgrading-logstash-pqs.html
This PR sets up links to deleted pages so that we don't give our users a bad 404 experience (if they come into docs from a saved link or from a web search).
> Doc: Set up redirects for deleted pages

- docs/static/getting-started-with-logstash.asciidoc
- docs/static/redirects.asciidoc
> Doc: Set up redirects for deleted pages [8.0]

- Gemfile.jruby-2.5.lock.release
> Bump Gemfile lock for 7.17.1

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13802.docs-preview.app.elstc.co/guide/en/logstash/8.0/logstash-8-0-1.html
> Docs: release notes for 8.0.1

- Gemfile.jruby-2.5.lock.release
- versions.yml
DO NOT merge until `7.17.1` is released
> bump core version

- logstash-core/lib/logstash/java_pipeline.rb
- logstash-core/lib/logstash/outputs/base.rb
- logstash-core/src/main/java/org/logstash/execution/JavaBasePipelineExt.java
[rn:skip] 
Expose the pipeline shutdown request state to plugin
This PR goes with https://github.com/logstash-plugins/logstash-output-http/pull/129
-
> expose shutdown request state of pipeline

- docs/static/running-logstash-windows.asciidoc
> Doc: Correct name for java_home env variable for Windows [8.1]

- docs/static/running-logstash-windows.asciidoc
> Doc: Correct name for java_home env variable for Winddows [8.0]

- config/logstash.yml
- config/pipelines.yml
- docs/static/settings-file.asciidoc
[rn:skip] 
Reformats pipeline order options for better readability
**PREVIEW:** https://logstash_13084.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-settings-file.html
> Doc: Improve formatting and readability for pipeline ordering

- Gemfile.jruby-2.5.lock.release
- versions.yml
**Merge after `8.1.0` is out**
> Bump version to next 8.1.1

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13867.docs-preview.app.elstc.co/guide/en/logstash/8.1/logstash-8-1-0.html
> Add plugin uninstall release note

- docs/static/monitoring/monitoring-internal-legacy.asciidoc
Co-authored by: Dan Roscigno <dan@roscigno.com>
Move content from #10940 into updated file/file structure
**PREVIEW:**  https://logstash_13871.docs-preview.app.elstc.co/guide/en/logstash/master/monitoring-internal-collection-legacy.html#configure-internal-collectors-legacy
> Doc: Clarify monitoring settings

- tools/ingest-converter/build.gradle
Update Jackson databind in ingest-converter tool
> Update Jackson databind in ingest-converter tool

- qa/integration/services/logstash_service.rb
[rn:skip]
Sets the `LS_JAVA_HOME` environment variable for the environments used to spawn Logstash process in integration tests.
The JDK matrix testing is based on selecting the desired JDK to run the tests, through the `BUILD_JAVA_HOME`.
However, when the integration tests spawn a Logstash process this setting is missed
Impacts the developer that want to run the full test suite with a specific JDK, also the spawned processes.
- set JDK 8 in a shell
```sh
sdk use java 8.0.322-tem
```
- configure the env vars as done in test shell …
> Updates the LogstashService launcher to use the JDK specified

- docs/static/releasenotes.asciidoc
**PREVIEW:**  https://logstash_13932.docs-preview.app.elstc.co/guide/en/logstash/7.17/logstash-7-17-2.html
> Release notes for 7.17.2

- docs/static/releasenotes.asciidoc
**PREVIEW:** https://logstash_13940.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-8-1-2.html
> Release notes for 8.1.2

- logstash-core/lib/logstash/api/commands/node.rb
- logstash-core/lib/logstash/api/commands/stats.rb
Fixes an issue where querying the stats API before any pipelines had been started could result in an HTTP 500 response. Second try, due to bad error's class reference.
In #13424 the problem was fixed, but re-appears due to bad class reference. From 
```
Instrument::MetricStore::MetricNotFound
```
to
```
LogStash::Instrument::MetricStore::MetricNotFound
``` 
Provide useful stats API output even when no pipelines are yet running.
-  Fixes #12919
-  Relates #13424
> Correct the class reference to the MetricNotFound exception

- docs/static/security/es-security.asciidoc
Co-authored-by: Ry Biesemeyer <ry.biesemeyer@elastic.co>
Incorporates content suggestions surfaced during review of #13693 into the main ES security section. 
Related issue: #13573
**PREVIEW:** https://logstash_13834.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#es-security-on
> Doc: Refine content for generated CA in LS-ES security section

- logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
- logstash-core/src/main/java/org/logstash/ackedqueue/io/FileCheckpointIO.java
- logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV1.java
- logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV2.java
[rn:skip]
Internal logging for PQ troubleshooting.
N/A
> Refactor: more logging of PQ behavior

- logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
- logstash-core/src/main/java/org/logstash/common/io/RecordIOReader.java
[rn:skip]
This PR is a refactoring of `open` invocation inside `RecordIOReader` of DLQ segments from the reader side.
After PR #13923, which when  `storage_policy` `drop_older` mode is active delete segment files from the tail, it could happen that, also after a file existence check, the opening operation throw a `NoSuchFileException`. 
It could happen in unlucky concidences, where the file existence check return a positive response, but in the meanwhile the upstream process decides to delete the file. This event has to be recognized as a "deletion of a segment", and managed.
Avoid the users of DLQ to encounter IOExceptions due to bad timing between the DLQ producer and consumer processes.
- ~~[ ] I have made corresponding …
> Protected FileChannel open of segment files against NoSuchFileException

- docs/static/jvm.asciidoc
Fix document issue on https://github.com/elastic/logstash/issues/13561
> Update JVM document to fix issue 13561

- build.gradle
[rn:skip] 
Updates the `SignAliasDefinitionsTask` Gradle task to express as input dependency the Aliases registry yaml file, so that when the input changes then a new signed registry is created.
As developer when I update the `logstash-core/[src|test]/main/resources/org/logstash/plugins/AliasRegistry.yml` I need that the next invocation of  `assemble` task (or test run) works on the modified data.
- modify the …
> Fixed SignAliasDefinitionsTask task to depend on input yaml registry file

- docs/static/persistent-queues.asciidoc
Bring back the details that remove in https://github.com/elastic/logstash/pull/14095
> [Doc] queue.max_bytes for all queues

- logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
Fixed: #6801
Improve persistent queue full state handling
The definition of full is 
(1) the byte size of queue >= `queue.max_bytes` and/or
(2) the number of unread event >= `queue.max_events`
Prior to the change, when PQ is full, workers wake up writer thread in every read.
if queue is full due to the number of unread, it is right to wake up write thread.
But if queue is full due to byte size, without removing a fully acked page, the queue is still full. 
[notFull.signalAll()](https://github.com/elastic/logstash/blob/8.2/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L652-L654) cause unnecessary thread sync.
This commit changes the condition of sending notFull signal. 
Send the signal in readPageBatch() if queue is full by the number of unread.
Another …
> Avoids unnecessary thread sync of PQ notFull state

- Gemfile.jruby-2.5.lock.release
- versions.yml
**Merge after `8.2.1` is out**
> Bump version to next 8.2.2

- docs/static/releasenotes.asciidoc
Adding 8.3 release notes placeholder to establish links and framework so we can start adding content
> Doc: Add placeholder for 8.3 release notes

- docs/static/releasenotes.asciidoc
Preview won't be available until we add 8.3 doc builds to conf file.
> Doc: Add pipeline improvements to release notes

- build.gradle
- versions.yml
Backport PR #14098 to 8.2 branch. Original Message:
* Switch adoptopenjdk url to adoptium
Newer versions of the JDK are only available from api.adoptium.net, and not dual hosted on api.adoptopenjdk.net
This commit allows the use of adoptium versions of the JDK.
Relates: #14072
-
> Backport PR #14098 to 8.2. Switch adoptopenjdk url to adoptium

- logstash-core/src/main/java/org/logstash/FileLockFactory.java
[rn:skip] 
Proposes a code cleanup of the `FileLockFactory.obtainLock` method. It removes the nesting of  `if`s using a "precondition style" check. For example:
```java
if (some condition) {
// do something
} else {
throw
}
```
Lift up the error condition, and checking on top of the code flow, like in:
```java
if (! some condition) {
throw
}
// do something
```
So the "happy path" become immediately clear.
It removed a `throw` exception from the clean-up finally block.
If an exception is raised from that point it hides the original cause of the problem.
This commit switches the `finally` block, used in obtaining a file lock, to a `catch` and re-throw.
- ~~[ ] I have made corresponding changes to the …
> Avoid to throw an exception from a finally block

- Gemfile.jruby-2.5.lock.release
- versions.yml
After this PR is merged please merge https://github.com/elastic/logstash/pull/14253
> bump to 8.2.4

- config/logstash.yml
[rn:skip] 
Updates the `logstash.yml` with the description of `dead_letter_queue.storage_policy` which was missed in PR #13923 
Help the user to see the configuration settings into the `łogstash.yml`
> Added description into logstash.yml for sotrage_policy, missed in #13923

- logstash-core/src/main/java/org/logstash/execution/ShutdownWatcherExt.java
- logstash-core/src/test/resources/shutdown_watcher_ext_pipeline_template.rb
[rn:skip] 
Log also the pipeline_id of the draining queue when the shutdown watcher is monitoring the shutdown of pipelines
In case of multi pipelines it makes evident the pipeline that's draining.
- 
```
[2022-06-17T14:36:32,046][INFO ][org.logstash.execution.ShutdownWatcherExt] The queue is draining before shutdown.
```
> Print the pipeline id of the queue that's draining

- .gitignore
- docker/Makefile
- docker/ironbank/LICENSE
- docker/ironbank/README.md
- docker/ironbank/go/src/env2yaml/go.mod
- docker/ironbank/go/src/env2yaml/go.sum
- docker/ironbank/go/src/env2yaml/vendor/modules.txt
- docker/templates/Dockerfile.j2
- docker/templates/hardening_manifest.yaml
- rakelib/artifacts.rake
[rn:skip]
This commit adds a rake task to generate ironbank docker build context. 
Run `rake artifact:dockerfile_ironbank`. The output can be found in build/logstash-ironbank-$VERSION-docker-build-context.tar.gz
- I have tested `make public-dockerfiles_full`, `make public-dockerfiles_oss`, `make public-dockerfiles_ubi8` and `rake artifact:dockerfile_ironbank` to generate build context and run `docker build -t` to build four images successfully
Run `rake artifact:dockerfile_ironbank` to generate `build/logstash-ironbank-$VERSION-docker-build-context.tar.gz`
The content of .gz should be the same as GitLab [repository](https://repo1.dso.mil/dsop/elastic/logstash/logstash)
The `sha512` of `logstash-$VERSION-linux-x86_64.tar.gz` in `hardening_manifest.yaml` should be empty
- Relates: …
> Support ironbank docker build

- docs/static/releasenotes.asciidoc
No user facing changes in this release
> Release Notes for 8.3.1

- docs/static/releasenotes.asciidoc
Forward port of release notes for `8.3.1` `8.3.0.` `8.2.3` to `main`
> Forward port of release notes for `8.3.1` `8.3.0.` `8.2.3` to `main`

- docs/static/plugin-manager.asciidoc
[rn:skip] 
Fix typo in docs already solved by a PR proposed by open source contributor but no CLA has been signed.
Closes #13432
> [Docs] Fixes a typo in the docs

- docs/static/advanced-pipeline.asciidoc
- docs/static/java-codec.asciidoc
- docs/static/java-input.asciidoc
- docs/static/java-output.asciidoc
follow up of https://github.com/elastic/logstash/pull/12276
update url from master to main
> [DOC] update link from master to main

- docs/index.asciidoc
- docs/static/env-vars.asciidoc
- docs/static/event-data.asciidoc
- docs/static/ls-to-cloud.asciidoc
- docs/static/pipeline-config-exps.asciidoc
- docs/static/pipeline-configuration.asciidoc
- logstash-core/logstash-core.gemspec
Rework content to emphasize pipeline to improve search performance
Replaces #13878
**PREVIEW:** https://logstash_14032.docs-preview.app.elstc.co/guide/en/logstash/master/configuration.html
* Tracked as part of meta issue: #14262
* Capture and track issues and ideas surfaced during writing/review: https://github.com/elastic/logstash/issues/14264
> Doc: Migrate terminology to emphasize pipeline for better seo

- Gemfile.jruby-2.6.lock.release
[rn:skip]
Adds a gemlock file for new `8.4.0` release.
> Introduce 8.4.0 gemlock file.

- Gemfile.jruby-2.6.lock.release
[rn:skip] 
Pin the version of `logstash-input-dead_letter_queue` plugins to version `2.0.0` to be released in lockstep with Logstash `8.4.0` because it uses functionalities available from this version onward.
Permit to the user to leverage latest enhancements on DLQ automatic cleaning and retention policy.
- Relates #10493 (phase 3)
- Relates #14173
> Updates gems lockfile with DLQ input to compatible version

- docs/static/releasenotes.asciidoc
Adding 8.4.0 release notes placeholder to establish links, framework, anchors and add `coming` tag
> Doc: Add placeholder and coming tag for 8.4.0 release notes

- docs/static/releasenotes.asciidoc
[rn:skip] 
Forward port release notes for 8.4.0 and 8.4.1
- Relates #14458
- Relates #14473
> Forward port release notes for 8.4.0 and 8.4.1

- logstash-core/src/main/java/org/logstash/ackedqueue/SettingsImpl.java
- logstash-core/src/test/java/org/logstash/ackedqueue/SettingsImplTest.java
Fix the issue of `queue.checkpoint.retry` not taking the config
[SettingsImpl.checkpointRetry](https://github.com/elastic/logstash/blob/v8.4.1/logstash-core/src/main/java/org/logstash/ackedqueue/SettingsImpl.java#L172) is hardcoded to false in builder.
This commit removes the hardcode boolean 'false'
Prior to this change, users are unable to set `queue.checkpoint.retry` to true to enable Windows retry on PQ AccessDeniedException in checkpoint
- Relates: #12345
- Closes: #14486
> fix SettingsImpl to remove hardcoded checkpointRetry

- logstash-core/lib/logstash/api/commands/stats.rb
- logstash-core/lib/logstash/api/modules/node_stats.rb
- logstash-core/lib/logstash/config/pipelines_info.rb
- logstash-core/lib/logstash/instrument/periodic_poller/flow_rate.rb
- logstash-core/lib/logstash/instrument/periodic_pollers.rb
- logstash-core/spec/logstash/api/commands/stats_spec.rb
- logstash-core/spec/logstash/api/modules/node_stats_spec.rb
- logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb
- tools/benchmark-cli/src/test/resources/org/logstash/benchmark/cli/metrics.json
[rn:skip] 
Introduces controller and service layer implementation for the [flow metrics core](https://github.com/elastic/logstash/pull/14509).
To provide a better visibility for the customer on Logstash back-pressure case.
- Make sure [dependant PR](https://github.com/elastic/logstash/pull/14509) is merged.
- pull the changes and run LS after compiling
- call the `/node/stats` API to fetch the metrics flows (eg.: `localhost:9600/_node/stats/pipelines/main`)
-
> Controller and service layer implementation for flow metrics.

- ci/dra.sh
[rn:skip] 
Introduces a bash script to build all the artifacts and dependencies report.
- ~~ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
run the artifact creation script with 
```
ci/dra.sh
``` 
and check all artifacts and dependencies report is created
-
> Created DRA shell script to create artifacts and dependency report

- logstash-core/spec/logstash/agent/metrics_spec.rb
- logstash-core/spec/logstash/agent_spec.rb
- logstash-core/spec/logstash/api/commands/stats_spec.rb
- logstash-core/spec/logstash/api/modules/node_stats_spec.rb
[rn:skip]
- Adds unit test cases flow top-level flow metrics introduced by [this PR](https://github.com/elastic/logstash/pull/14539). 
- Ensures that API responses for flow metrics are valid. Eg. includes the desired keys: `input_throughput`, `output_throughput`, `filter_throughput`, `queue_backpressure`, `worker_concurrency`.
- No user impact
- pull the changes and run following unit test commands.
```
$bin/rspec logstash-core/spec/logstash/agent/metrics_spec.rb:77
$bin/rspec logstash-core/spec/logstash/api/commands/stats_spec.rb:78
$bin/rspec logstash-core/spec/logstash/api/modules/node_stats_spec.rb
$bin/rspec …
```
> Top level flow metrics unit tests added.

- ci/dra.sh
- save docker images as `tar.gz` files
- move the CSV dependency report in the path that's expected by release-manager 
-
> [DRA] Save docker images as tar.gz files

- ci/dra_aarch64.sh
- ci/dra_x86_64.sh
[rn:skip]
Uses the `gsutil` tool to upload all the generated artifacts into an intermediate collector bucket.
-
> Upload DRA artifacts to collector GCS bucket 

- ci/dra_upload.sh
[rn:skip]
Downloads all artifacts generated for ARM and x86 by `ci/dra_x86_64.sh` `ci/dra_aarch64.sh`, position in locations expected by the `release-manager` and invokes it to upload to the global bucket.
Doesn't impact the user.
-
> Collect all artifacts created and upload to GCP with release-manager

- docs/static/java-filter.asciidoc
- logstash-core/src/main/java/co/elastic/logstash/api/Filter.java
- logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaFilterDelegatorExt.java
- logstash-core/src/main/java/org/logstash/plugins/filters/Uuid.java
Adds new `close` method to Java's Filter API to be used to clean shutdown resources allocated by the filter during registration phase.
- Adds a new method to the public API interface
- Pass the call through the `JavaFilterDelegatorExt`
- Closes #14367
> Adds method and pass the invokation through Java's filter delegator

- ci/dra_aarch64.sh
- ci/dra_upload.sh
- ci/dra_x86_64.sh
[rn:skip] 
Handle the `WORKFLOW_TYPE` enviroment variable used to select the kind of artifacts to generate and consequently adapt the version name.
If the `WORKFLOW_TYPE` has a value assigned other then empty string it's assumed to be `snapshot` and so it generates snapshot artifacts else the release ones.
-
> Updates DRA scripts to build snapshot artifacts

- ci/dra_upload.sh
[rn:skip]
Switches the selection of --branch name from deducting from release version to read from directly from git.
In this way the snapshots built from `main` are 
-
> Switch branch slector from major.minor to read the current branch name

- ci/dra_aarch64.sh
- ci/dra_upload.sh
- ci/dra_x86_64.sh
Enable debug for DRA shell scripts
> Enable debug for DRA

- ci/dra_aarch64.sh
- ci/dra_x86_64.sh
Disable -x in dra build scripts
> Disable -x in dra build scripts

- ci/dra_aarch64.sh
- ci/dra_common.sh
- ci/dra_upload.sh
- ci/dra_x86_64.sh
This PR improves the implementation of the DRA scripts:
- Reduces duplicate code, using a common code path and functions that are re-usable.
- Improves debuggability by adding better information and error comments.
TODO: As a follow up to this PR, the desire would be to:
- Implement a retry logic in which if an artifact fails to build, it retries once.
- Deduce code in dra_upload.sh
> DRA: Improve shell scripts for debuggability

- ci/dra_upload.sh
Fixes sources for dra_upload.sh
> Fix sourcing on dra_upload

- ci/dra_aarch64.sh
- ci/dra_common.sh
- ci/dra_upload.sh
- ci/dra_x86_64.sh
Manually backport #14654 #14657 #14659, as automated job fails.
> Manually backport #14654, #14657, #14659

- qa/integration/specs/monitoring_api_spec.rb
[rn:skip]
Fixes a precondition assertion in a flaky spec
N/A
Closes: #14632
> specs: assert presence of logging without risking NoMethodError

- ci/dra_docker.sh
Ensure docker files are also built for the release.
> DRA: Build dockerfiles for release

- docsk8s/setting-up/ls-k8s-secure.asciidoc
Fixes: #14580 14580
- Using certificates
- Using Kubernetes secrets
- Using the logstash keystore
- Securing ES on ECK
> [doc] Logstash Kubernetes - Securing Logstash  

- docs/static/config-details.asciidoc
[rn:skip] 
Update the guide section where it's described how to configure Logstash to document the `LS_JAVA_OPTS` environment variabl eand its usage
Let the user to discore documentation about `LS_JAVA_HOME`
-
> [Doc] Document the usage of LS_JAVA_OPTS environment variable

- versions.yml
> Bump to 8.7.0

- docs/static/releasenotes.asciidoc
[rn:skip] 
Forward port release notes from `8.5.0` and `8.5.1` to `8.6`
> Forward port release notes of 8.5.0 and 8.5.1 to 8.6

- ci/dra_common.sh
- ci/dra_docker.sh
[rn:skip]
On ARM architecture UBI8 Docker images aren't created, so avoid to create empty tar.gz files.
As a CI user I don't want that non expected artifacts blocks the job.
-
> Avoid to create and upload AARCH64 Docker images for UBI8

- docs/static/releasenotes.asciidoc
Adds placeholder for 8.6.0 release notes to establish links, framework, anchors and add coming tag
> Doc: Add placeholder and coming tag for 8.6.0 release notes

- Gemfile.jruby-2.6.lock.release
- versions.yml
**Merge after `8.6.0` is out**
> Bump version to next 8.6.1

- versions.yml
[rn:skip] 
Upgrades the `jackson` and `jackson-databind` versions after updating [`jrjackson` (v0.4.17)](https://github.com/guyboertje/jrjackson/pull/90).
New version of `jackson` addresses several CVEs, visit [jackson release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13) for more information.
- run `./ci/unit_tests.sh` unit test cases to prove that change doesn't break
- Closes #14672
```
BUILD SUCCESSFUL in 15m 18s
58 actionable tasks: 9 executed, 49 up-to-date
```
> jrjackson and jackson versions bump.

- build.gradle
Update Snakeyaml,
container vulnerabilities
-
> Update build.gradle - update snakeyaml

- versions.yml
Version bump to `8.8.0`. `8.7` branch is created.
> Bump to 8.8.0

- Gemfile.jruby-2.6.lock.release
- versions.yml
> Bump to 8.6.3

- docs/static/releasenotes.asciidoc
Forwardporting `8.6.2` release notes to `8.7`.
> [Forwardport] `8.6.2` release notes to `8.7` (#14896)

- .github/workflows/platform_ingest_project_board.yml
> Rework project actions

- build.gradle
- logstash-core/benchmarks/build.gradle
- logstash-core/build.gradle
- rubyUtils.gradle
- tools/benchmark-cli/build.gradle
- tools/dependencies-report/build.gradle
- tools/ingest-converter/build.gradle
[rn:skip] 
Create a variable in the Gradle's `ext` map to store the versions of libraries and plugins used across the various `.gradle` files.
As a developer, when updating a version of a dependency, I would like to change in just one place so that all the parties aremains aligned.
-
> Centralized version definition for snakeyaml and shadow plugin used in buildscripts

- build.gradle
- logstash-core/benchmarks/build.gradle
- logstash-core/build.gradle
- rubyUtils.gradle
- tools/benchmark-cli/build.gradle
- tools/dependencies-report/build.gradle
- tools/dependencies-report/src/main/resources/licenseMapping.csv
- tools/dependencies-report/src/main/resources/notices/org.yaml!snakeyaml-NOTICE.txt
- tools/ingest-converter/build.gradle
backport #14881 and #14886
pin snakeyaml to 1.33 and update license information
> pin snakeyaml to 1.33

- Gemfile.jruby-2.6.lock.release
- versions.yml
Version bump after `8.7.0` release.
> Version bump from 8.7.0 to 8.7.1

- docs/static/releasenotes.asciidoc
cherry-pick [6ab14e4e8a8c25ab8b6229b19923564e735a6fa0](https://github.com/elastic/logstash/commit/6ab14e4e8a8c25ab8b6229b19923564e735a6fa0)
> [Forwardport] release note 8.7.0

- Gemfile.jruby-2.6.lock.release
- versions.yml
> Bump 8.8.1

- docs/static/releasenotes.asciidoc
rn:skip] 
Forward port release notes of `8.8.0` to `main`
> Forward port release notes for 8.8.0

- docs/static/releasenotes.asciidoc
Clean forward-port of #15085 from `8.8` to `main`
> Forward-port Release notes for 8.8.1 (#15085)

- .buildkite/scripts/snyk/report.sh
- .buildkite/scripts/snyk/resolve_stack_version.sh
- .buildkite/snyk_report_pipeline.yml
[rn:skip]
Integrates with Snyk to monitor regularly the security vulnerabilities.
_The details of the PR:_
- adds pipeline steps, each step proceeds one branch report job
- includes a script to resolve current (and previous release bas on job stack version) latest branches from the release URL. Noting that it considers the branches from snapshots where upcoming releases will be our interest.
- adds logics to clone Logstash repo, build and report to Snyk. It also uses the Buildkite Vault to fetch Snyk auth token.
To deliver risk free, safe Logstash distributor to the customers.
- ~~[ ] I have made corresponding change to the default configuration files (and/or …
> Snyk Integration

- .buildkite/scripts/snyk/report.sh
Read and use Snyk token stored in logstash repo scoped vault.
> Read Snyk token from logstash repo scoped vault.

- build.gradle
- logstash-core/benchmarks/build.gradle
- logstash-core/build.gradle
- tools/benchmark-cli/build.gradle
- tools/dependencies-report/build.gradle
- tools/ingest-converter/build.gradle
- versions.yml
multiple dependency updates to ensure Logstash is using the latest version
> update commons-io commons-compress jrjackson databind

- docs/static/releasenotes.asciidoc
* Update release notes for 8.8.2
> [8.9] Forward Port Release notes for 8.8.2 (#15116)

- docs/static/releasenotes.asciidoc
* Update release notes for 8.8.2
> Forward port Release notes for 8.8.2 (#15116)

- rakelib/plugins-metadata.json
Bundles the ESF forwarder.
Users wont have to manually install the plugin
> Bundle ESF forwarder

- .rubocop.yml
- lib/bootstrap/bundler.rb
- lib/bootstrap/environment.rb
- lib/pluginmanager/generate.rb
- lib/pluginmanager/prepare_offline_pack.rb
- logstash-core/lib/logstash/agent.rb
- logstash-core/lib/logstash/config/mixin.rb
- logstash-core/lib/logstash/runner.rb
- logstash-core/lib/logstash/settings.rb
- logstash-core/spec/logstash/agent_spec.rb
- qa/integration/services/service.rb
- qa/integration/specs/deprecation_log_spec.rb
- qa/integration/specs/env_variables_config_spec.rb
- qa/integration/specs/fatal_error_spec.rb
- qa/integration/specs/kafka_input_spec.rb
- qa/integration/specs/mixed_codec_spec.rb
- qa/integration/specs/pipeline_log_spec.rb
- qa/integration/specs/plugin_name_log_spec.rb
- qa/integration/specs/settings_spec.rb
- qa/integration/specs/slowlog_spec.rb
- rakelib/artifacts.rake
- rakelib/vendor.rake
- x-pack/qa/integration/support/helpers.rb
Fixes instances of Rubocop Lint/DeprecatedClassMethods.
Also documents that we enabled this Lint/DeprecatedClassMethods cop.
> Fix instances of deprecated class methods

- docs/static/persistent-queues.asciidoc
Fixes a typo that caused subtitle not to show up.
> Fix typo that caused subtitle not to show

- docs/static/releasenotes.asciidoc
Contains the following PRs
Release notes for 8.9.0 (#15162)
8.9 Release notes updated. (#15221)
> Forward port of release notes from 8.9.0

- Gemfile.jruby-3.1.lock.release
- NOTICE.TXT
- lib/pluginmanager/util.rb
- logstash-core/build.gradle
- logstash-core/logstash-core.gemspec
- rubyUtils.gradle
- spec/unit/plugin_manager/util_spec.rb
- tools/dependencies-report/src/main/resources/licenseMapping.csv
- tools/dependencies-report/src/main/resources/notices/cgi-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/date-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/ffi-binary-libfixposix-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/io-console-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/net-http-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/net-protocol-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/reline-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/time-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/timeout-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/uri-NOTICE.txt
- versions.yml
[rn:skip] (the current PR for 8.10's release notes https://github.com/elastic/logstash/pull/15265/files contains no reference to the Jruby upgrade, so mentioning this downgrade which is still a net-upgrade from the one we shipped in LS 8.9 series doesn't make sense)
Downgrades JRuby to 9.4.2.0 to avoid the silent global crash of the scheduler backing `Concurrent::TimerTask` that occurs when Jruby 9.4.3.0's invokedynamic promotes a method to run natively, incorrectly.
Upstream bug: https://github.com/jruby/jruby/issues/7904
Along with the downgrade of JRuby itself to 9.4.2.0, we cherry-pick the updates to default gems that were included in the latest JRuby 9.4.3.0 to ensure we don't back out relevant fixes to stdlib.
We also remove a pinned-dependency on `racc` that is no longer relevant, …
> deps: downgrade jruby, keep updated default-gem dependencies

- docs/static/config-details.asciidoc
[rn:skip]
Expands the description of memory used by Logstash, dividing the heap and non-heap; describing in details which parts composes the non-heap, how to size it and list the JVM settings that can be used to properly define this space.
Describe an important factor of Logstash execution. Many user think that the only memory used is the JVM heap, but using memory mapped files and direct buffer Logstash could need a lot of non heap memory. This update helps to user to understand better how it's composed the memory and how to size it.
- ~~[ ] I have added tests that prove my fix is effective or that my …
> Expanded the description how to size the memory of the JVM

- versions.yml
> Bump core version to 8.12

- catalog-info.yaml
[rn:skip]
Adds a definition for the plugin's tests pipeline to the Buildkite catalog.
> Add definition for plugin's test pipeline to Buildkite catalog

- .buildkite/dra_pipeline.yml
- .buildkite/scripts/dra/build_docker.sh
- .buildkite/scripts/dra/build_packages.sh
- .buildkite/scripts/dra/common.sh
- .buildkite/scripts/dra/docker-env-setup.sh
- .buildkite/scripts/dra/docker-env-teardown.sh
- .buildkite/scripts/dra/generatesteps.py
- .buildkite/scripts/dra/publish.sh
[rn:skip]
This is a backport of the DRA pipeline and related scripts to enable buildkite DRA jobs for the 7.17 branch.
- #15366
- #15365
- #15356
- #15352
- #15344
- #15343
- #15337
- #15312
> [ci] Backport Buildkite DRA pipeline+scripts to 7.17

- .buildkite/dra/build_docker.sh
- .buildkite/dra/build_packages.sh
- .buildkite/dra/common.sh
- .buildkite/dra/docker-env-setup.sh
- .buildkite/dra/docker-env-teardown.sh
- .buildkite/dra/generatesteps.py
- .buildkite/dra/publish.sh
- .buildkite/dra_pipeline.yml
[rn:skip]
This is a backport of the DRA pipeline and related scripts to enable buildkite DRA jobs for the 8.10 branch.
- #15366
- #15365
- #15356
- #15352
- #15344
- #15343
- #15337
- #15312
> [ci] Backport Buildkite DRA pipeline+scripts to 8.10

- logstash-core/build.gradle
[rn:skip]
Update Guava dependency to 32.1.2
> Update Guava dependency to 32.1.2

- Gemfile.jruby-3.1.lock.release
- versions.yml
Bump Logstash core version to 8.10.4
> Update core to 8.10.4

- Gemfile.jruby-2.5.lock.release
- versions.yml
Bump Logstash core version to 7.17.15
> Bump core to 7.17.15

- .buildkite/pull_request_pipeline.yml
[rn:skip]
This commit shortens the descriptions of the PR Buildkite steps for better readability on the UI.
https://github.com/elastic/ingest-dev/issues/1721
> [ci] Improve PR step names for Buildkite

- .buildkite/supported_plugins_test_pipeline.yml
[rn:skip]
Define a Buildkite pipeline to execute all rspec tests on an all tier1 and tier2 supported plugins. The first take precedence on the others.
It should reveal asap some incompatibilities between Logstash, JRuby and the supported plugins.
-
> Defines a pipeline to run specs tests on supported plugins

- docs/static/releasenotes.asciidoc
* Update release notes for 8.10.4
Co-authored-by: Karen Metts <karen.metts@elastic.co>
> Release notes for 8.10.4 (#15435)

- ci/unit_tests.sh
[rn:skip]
This commit introduces a way to optionally disable SonarQube scanning and coverage reports when running Java unit tests.
Disabling can be achieved by setting the env var `ENABLE_SONARQUBE` to `false`.
The integration was introduced in #15279, however, there are cases (e.g. running Java unit tests outside of PRs) where we don't want this integration.
```shell
ci/unit_tests.sh java
```
should fail by default as it expects sonarqube credentials.
```shell
export ENABLE_SONARQUBE=false
ci/unit_tests.sh java
```
should succeeed.
We will also test this …
> Option to disable SonarQube with Java Tests

- .buildkite/supported_plugins_test_pipeline.yml
- ci/test_plugins.rb
- ci/test_plugins.sh
- ci/test_unsupported_plugins.sh
Adds support to also test some unsupported plugins that are actively used by our community.
> Add support to test unsupported plugins

- Gemfile.jruby-3.1.lock.release
- versions.yml
> Bump version to 8.11.1

- NOTICE.TXT
- tools/dependencies-report/src/main/resources/licenseMapping.csv
- tools/dependencies-report/src/main/resources/notices/diff-lcs-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/elastic-transport-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/rspec-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/rspec-collection_matchers-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/rspec-core-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/rspec-expectations-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/rspec-mocks-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/rspec-support-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/rspec-wait-NOTICE.txt
- tools/dependencies-report/src/main/resources/notices/webrick-NOTICE.txt
[rn:skip]
Update some dependency's licenses definitions.
> Fixed definitions of licenses for some dependencies

- ci/logstash_releases.json
Once 8.11 was cut, snapshot build for 8.x should be 8.12
[rn: skip]
Bumps reference for 8.x snapshot to 8.12 so that plugins testing against snapshot builds can properly target `main` instead of a stale snapshot from the 8.11 series.
No user impact
This PR modifies a mapping on `main` that plugins use when resolving `ELASTIC_STACK_VERSION=8.x SNAPSHOT=true` to a concrete docker resource. Plugins can _bypass_ the indirect version resolution by specifying the …
> build meta: bump 8.x snapshot to 8.12

- docs/index.asciidoc
- docs/static/running-logstash-kubernetes.asciidoc
- docs/static/setting-up-logstash.asciidoc
Fixed: #15471
Logstash doc add reference to ECK
> [Doc] add reference to ECK

- .buildkite/aarch64_pipeline.yml
- .buildkite/linux_jdk_matrix_pipeline.yml
- .buildkite/scripts/dra/generatesteps.py
- .buildkite/scripts/jdk-matrix-tests/generate-steps.py
- .buildkite/supported_plugins_test_pipeline.yml
- .buildkite/windows_jdk_matrix_pipeline.yml
[rn:skip]
Add missing yaml-language-server definition to Buildkite pipeline files (static and dynamic generated) for consistency and to ease spotting errors with editors.
- PR jobs: https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/375
- JDK matrix: https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/32
- aarch64 tests: https://buildkite.com/elastic/logstash-aarch64-pipeline/builds/32
- dra snapshot (main): https://buildkite.com/elastic/logstash-dra-snapshot-pipeline/builds/173
- https://github.com/elastic/ingest-dev/issues/1720
> [ci] Add yaml language server to pipelines

- .buildkite/scripts/snyk/report.sh
- .buildkite/snyk_report_pipeline.yml
- catalog-info.yaml
[rn:skip]
This change adds following simplifies to the Snyk report pipeline:
- ~~use Java installed BK agent;~~ - still requires since we use docker operations
- use proper agent to utilize the less resources;
- remove unnecessary git clone operation since repo is already cloned;
Optimizes pipeline run time and aligns with standard BK CI agent
Pull locally and run `sh .buildkite/scripts/snyk/report.sh`. Note that you need to have a proper access to the vault to utilize Snyk token.
> Use proper BK agent and simplify some operations in Snyk report pipeline.

- docs/static/monitoring/monitoring-ea-dashboards.asciidoc
- docs/static/monitoring/monitoring-ea.asciidoc
- docs/static/monitoring/monitoring-view.asciidoc
> Doc: Housekeeping changes to monitoring with agent docs

- docs/static/monitoring/monitoring-ea-dashboards.asciidoc
- docs/static/monitoring/monitoring-ea.asciidoc
- docs/static/monitoring/monitoring-view.asciidoc
> Doc: Improvements to monitoring with agent (#15619) to 8.11

- docs/index.asciidoc
- docs/static/security/es-security.asciidoc
[rn:skip]
* Closes https://github.com/elastic/ingest-dev/issues/2401
* Closes https://github.com/elastic/ingest-dev/issues/2406
* Related: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1164
https://logstash_15313.docs-preview.app.elstc.co/guide/en/logstash/master/introduction.html
https://logstash_15313.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#es-security-on
> Doc: Update Logstash intro and security overview for serverless

- Gemfile.jruby-3.1.lock.release
- rubyUtils.gradle
- versions.yml
* update lockfile template's BUNDLED WITH to match jruby's bundler
> Update JRuby to 9.4.5.0 (#15531)

- docs/index.asciidoc
- docs/static/ea-integrations.asciidoc
Fixes:  #15172
Replacement for #15225
**PREVIEW:** https://logstash_15518.docs-preview.app.elstc.co/guide/en/logstash/master/ea-integrations.html
> Doc: Add docs for extending integrations with filter-elastic_integrations

- config/logstash.yml
- 8.7
- enhancement
Adds the 'log.format' to the logstash.yml and the different options log.format can have.
This PR fixes the issue with a missing option in the logstash.yml which is described in the docs.
- Closes #11290 
This PR introduces the option to change the format on the logs from logstash.
> Add log.format to the logstash.yml

- .buildkite/scripts/snyk/report.sh
[rn:skip]
So far we are practicing Snyk scan of docker images. Now we can comment docker scan logic to address collected issues later with more experiments.
We need to address soon multiple improvements:
N.A
-
> Comment docker scan logic to address collected issues later with more experiments.

- .buildkite/supported_plugins_test_pipeline.yml
- ci/test_plugins.rb
[rn:skip] 
Re-enabled `logstash-filter-json` and `logstash-codec-netflow` plugins into the test_plugins BK pipeline.
This change enable the execution of unit test in the context of actual Logstash of the listed plugin.
-
> Re-enable json filter and netflow codec plugins

- logstash-core/src/main/java/org/logstash/secret/cli/SecretStoreCli.java
- logstash-core/src/test/java/org/logstash/secret/cli/SecretStoreCliTest.java
[rn:skip] 
Since `logstash-keystore` command supports multiple key (https://github.com/elastic/logstash/pull/15612), it has broken the following command in [ECK](https://github.com/elastic/cloud-on-k8s/blob/bcc1888a7c3c6e8bec7624c86a3541be74138570/pkg/controller/logstash/keystore.go#L26) as `logstash-keystore` takes `--stdin` - and any other possible flag - as the second key, and not as a command option:
```
echo 'y' | bin/logstash-keystore add HELLO --stdin < HELLO
```
This PR fixes how the keystore tool handle command's options, including validation for unknown options, and adding the `--stdin` flag to the `add` command.
The following command should include a key named `FOO` with password `FOO_PASSWORD`:
```shell
> echo 'FOO_PASSWORD' > test.txt 
> echo 'y' | bin/logstash-keystore add …
```
> Fix logstash-keystore multiple keys operations with command flags

- ci/test_plugins.rb
[rn:skip]
Add the `logstash-filter-elasticsearch_integration` plugin to the list of test_plugins pipeline.
In doing so, reworked the definition of plugins, by not just specifying a plugin name but also adding support leve, type and organization. This necessary for plugins which repository is not part of `logstash-plugins` Github organization but at the same time permit an easier management of the different axes that partitions the plugin landscape.
Permit to the integration to test also this plugin against a specific Logstash branch. …
> Add filter elastic_integration to be tested in test_plugins script

- ci/test_plugins.rb
[rn:skip]
Fixes a typo in string definition for Logstash's plugins organization.
- Relates #15723
> Fixes a typo in plugin's organization name

- rakelib/plugins-metadata.json
[rn:skip]
Onboards `elastic_integration` plugin as a non default plugin. This will be so far enough doc tools to pick up the plugin changes.
N.A
- Closes #15611
> Add elastic_integration plugin to the plugin meta list.

- logstash-core/logstash-core.gemspec
[rn:skip]
Bump Puma to newer version
> Bump Puma to newer version

- docs/static/monitoring/monitoring-ea-intro.asciidoc
- docs/static/monitoring/monitoring-ea-serverless.asciidoc
Closes: #15622
**PREVIEW:** 
* https://logstash_15636.docs-preview.app.elstc.co/guide/en/logstash/master/monitoring-with-ea.html
* https://logstash_15636.docs-preview.app.elstc.co/guide/en/logstash/master/serverless-monitoring-with-elastic-agent.html
> Doc: Add monitoring for serverless

- docker/templates/hardening_manifest.yaml
> Remove Nassim Kammah from list of Ironbank maintainers

- versions.yml
Update JDK 
Updates the bundled JDK
> Updates bundled JDK

- docs/static/troubleshoot/ts-azure.asciidoc
- docs/static/troubleshoot/ts-plugins.asciidoc
[rn:skip]
Adds a new section in the troubleshooting plugins documentation part, related to Azure Event Hub storage connection.
Describes how to configure the Java Util Logging (JUL) inside Logstash to grab more details of what happens at HTTP level.
This logging enablements let the user understand which could be the source of problem when the Blob Storage connection hits some connectivity problems. 
Enables the user which experience problem with Azure Blob Storage (used by Event Hub) to grab more details on what's happening at HTTP connectivity layer.
- ~~[ ] I have added tests that prove my fix is effective or that my …
> Describe how to troubleshoot connectivity problems in  Azure Blob Storage at HTTP level

- ci/test_plugins.rb
[rn:skip]
Decomment the definition related to collectd codec.
Bring back the collectd codec into testing.
- Closes #15856
> Re-enabled collectd codec in test_plugins script

- docs/static/monitoring/monitoring-ea-dashboards.asciidoc
- docs/static/monitoring/monitoring-ea-serverless.asciidoc
- docs/static/monitoring/monitoring-ea.asciidoc
- docs/static/monitoring/monitoring-mb.asciidoc
- docs/static/monitoring/monitoring-prereq-disable-default.asciidoc
[rn:skip]
This reverts commit 9317052088f86ee05bd7972cde57e72c092ca68f.
We need to carefully address monitoring Logstash with Metricbeat and itself (historically called internal or self monitoring).
-
> Revert "[docs] Simplify and imrove Logstash monitoring docs. (#15847)"

- catalog-info.yaml
[rn:skip]
Fixes typo in yaml schema of the exhaustive tests pipeline.
Allows the editor to properly validate the section, preventing accidental bugs.
> Fix typo in catalog-info with exhaustive schema

- .github/workflows/add-docs-preview-link.yml
Following the migration from Jenkins to Buildkite, docs previews are now available at <repo>_bk_<PR>.
More context in https://github.com/elastic/docs/pull/2898
Note - it looks like the docs status checks are not required on the logstash repo.
-
> Update docs-preview link

- versions.yml
[rn:skip]
Updates bundled JDK
- Close #15848
> Updates JDK bundled in Logstash

- ci/logstash_releases.json
[rn:skip]
Our shared CI infrastructure relies on this file being here with a specific format, expanding a given `ELASTIC_STACK_VERSION` environment variable and an optional `SNAPSHOT` environment variable into the information necessary to target either the most recent published release or a snapshot representing a candidate for the _next_ possible release in a given major series.
When we cut a new minor branch from `main` (at feature freeze), the tip of that branch contains unreleased code that is in-flight for the next release. We need to have a way to reference artifacts from this in-flight release, instead of skipping over them while a minor release is in flight.
This change affects the _semantics_ of what is tested during a minor stack release's feature-freeze period, ensuring that …
> ci: provide metadata about releases that are in-flight

- .buildkite/linux_jdk_matrix_pipeline.yml
Adds Alma 8, Alma 9 and Rocky Linux 9.
> Add Alma 8, Alma 9, and Rocky Linux 9 to the JDK matrix

- logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
- logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
[rn:skip]
This PR adds a `shutdown` method to the `SchedulerService` class used to handle actions to be executed on a certain cadence. In particular is used to execute scheduled finalization of DLQ head segment.
Updates the `close` method of the DLQ writer to invoke this additional shutdown on the service instance.
Time to time in unit tests an error related to segment finalization happend.
It's mostly likely:
```
[WARN ] 2024-02-21 12:46:44.723 [dlq-flush-check] DeadLetterQueueWriter - Unable to finalize segment
java.nio.file.NoSuchFileException: /var/folders/f2/6ln9srr13hsdp3kwfz68w3940000gn/T/junit3045222654236224377/junit12477847196935554659/2.log.tmp -> /var/folders/f2/6ln9srr13hsdp3kwfz68w3940000gn/T/junit3045222654236224377/junit12477847196935554659/2.log
at …
```
> Add shutdown step of DLQ flusher scheduled service

- docs/static/dead-letter-queues.asciidoc
- docs/static/security/basic-auth.asciidoc
- logstash-core/lib/logstash/instrument/metric_store.rb
- logstash-core/spec/logstash/state_resolver_spec.rb
- logstash-core/src/main/java/org/logstash/config/ir/ConfigCompiler.java
- logstash-core/src/main/java/org/logstash/execution/QueueReadClient.java
- tools/logstash-docgen/README.md
> remove repetitive words

- Gemfile.jruby-2.5.lock.release
- versions.yml
> Bump 7.17.20

- docs/static/ea-integrations.asciidoc
> Doc: Remove beta tag from integrations filter doc

- qa/docker/shared_examples/xpack.rb
[rn:skip]
Fix integration tests caused by #16026, [exhaustive pipeline](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline) complained.
Test: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/343
N.A
-
> Fix integration tests caused by #16026.

- Gemfile.jruby-3.1.lock.release
- versions.yml
> Bump 8.13.2

- Gemfile.jruby-3.1.lock.release
- versions.yml
> Bump 8.13.5

- build.gradle
- tools/jvm-options-parser/build.gradle
[rn:skip]
Updated target and source Java definitions in build.gradle because deprecated and planned for removal in next major.
Ad a developer I want the update to next Gradle major is smooth as possible.
- Relates #16125
> Remove Gradle deprecations warning related to usage of source and target Java versions

- catalog-info.yaml
> Update catalog-info.yaml to properly define dependencies type.

- Gemfile.jruby-3.1.lock.release
- versions.yml
> Bump 8.14.2

- .buildkite/scripts/exhaustive-tests/generate-steps.py
- ci/docker_acceptance_tests.sh
- docker/Makefile
- docker/templates/Dockerfile.erb
- qa/docker/shared_examples/container.rb
- qa/docker/spec/spec_helper.rb
- qa/docker/spec/wolfi/container_spec.rb
- qa/docker/spec/wolfi/image_spec.rb
- rakelib/artifacts.rake
On top of #16116, this PR:
* fixes uid of logstash user on the wolfi image (1000, not 10000);
* adds docker acceptance tests for the wolfi image;
* changes how tests are done on the java process, due to "ps -C" not being available on wolfi
replaces and closes https://github.com/elastic/logstash/pull/16116
> Carry fwd pr #16116: add wolfi to exhaustive tests

- Gemfile.template
revert https://github.com/elastic/logstash/pull/16209
> remove version pinning from rexml

- docker/templates/Dockerfile.j2
- docker/templates/hardening_manifest.yaml
update to newest ubi version 8.10
Fixes: https://github.com/elastic/logstash/issues/16248
> Update ironbank UBI version

- Gemfile.template
- NOTICE.TXT
- tools/dependencies-report/src/main/resources/licenseMapping.csv
- tools/dependencies-report/src/main/resources/notices/fileutils-NOTICE.txt
see #16250, includes resync of license notices by invoking `./ci/license_check.sh`
> Backport 16250 8.14

- .buildkite/scripts/dra/build_docker.sh
- .buildkite/scripts/dra/common.sh
Produced artifacts can be observed in https://buildkite.com/elastic/logstash-dra-snapshot-pipeline/builds/1072#01904a87-b393-416e-85b9-52c81747539a/74-76
> produce wolfi docker image in ci

- logstash-core/spec/logstash/event_spec.rb
- logstash-core/spec/logstash/json_spec.rb
- logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
[rn:skip]
Covers two areas:
- Adds a support `RubyEvent#dup` additional to `RubyEvent#clone`. It is a safety guard when we use duplicate `dup` methods on the Logstash event object;
- Without `RubyEvent#dup` we got `NullPointerException`. To make sure we don't break `Json#dump` which internally duplicated the event before (it wasn't necessary so we removed) on any future changes, this PR also adds a small unit test.
`JrubyEventExtLibrary.java` changes are code formatting (couldn't close my 👁️ ) except 157L.
Exhaustive CI run: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/551
-
> Add `RubyEvent#dup` support and unit test case to keep `Json#dump(Event)` safe.

- docs/static/ea-integrations.asciidoc
Related: https://github.com/elastic/logstash-filter-elastic_integration/issues/151
> Doc: Add ecs and datastream requirement for intg filter

- .buildkite/linux_jdk_matrix_pipeline.yml
- .buildkite/scripts/common/vm-images.json
- .buildkite/scripts/exhaustive-tests/generate-steps.py
similar to https://github.com/elastic/logstash/commit/fedcf58c4888c959ce1f7f7e6cec3b457fd16eb8
> Add Ubuntu 24.04 to CI

- docs/static/performance-checklist.asciidoc
[rn: skip]
Improves Tuning docs to use flow-metrics to inform intuition about how and why to tune what.
Increases visibility to Flow metrics so that those seeking to tune LS pipeline performance can find a useful tool.
Wait for the docs gen link to be generated :)
> add flow-informed tuning guidance

- docs/static/releasenotes.asciidoc
clean forward-port of #16266 to `main`
> Forwardport Release notes for 8.14.2 to main (#16266)

- docs/static/releasenotes.asciidoc
clean forward-port of #16266 to `8.15`
> Forwardport Release notes for 8.14.2 to 8.15 (#16266)

- Gemfile.jruby-3.1.lock.release
> Revert 8.14.3 lock

- docs/include/filter.asciidoc
- docs/include/input.asciidoc
- docs/include/output.asciidoc
- docs/include/plugin_header-core.asciidoc
- docs/include/plugin_header-integration.asciidoc
- docs/include/plugin_header.asciidoc
Issue: https://github.com/elastic/logstash/issues/16276
VPR fix: https://github.com/elastic/logstash-docs/pull/1687
Apply Elastic standards to content in order to provide good examples for contributors to follow.
> Doc: Update headers for plugins (LSR)

- Gemfile.jruby-3.1.lock.release
- versions.yml
> Bump 8.14.4

- docs/static/monitoring/monitoring-apis.asciidoc
Fixes: #16275 
**PREVIEW:** https://logstash_bk_16335.docs-preview.app.elstc.co/guide/en/logstash/master/node-stats-api.html
> Doc: Reposition worker-utilization in doc

- docs/static/releasenotes.asciidoc
make a note of the fix that went to 8.13.1: https://github.com/elastic/logstash/pull/16026
> Fix 8.13.1 release notes

- docs/static/breaking-changes.asciidoc
Reference: https://www.elastic.co/guide/en/logstash/master/plugins-integrations-snmp.html
Fixes: #16373
**PREVIEW:** https://logstash_bk_16374.docs-preview.app.elstc.co/guide/en/logstash/master/breaking-changes.html
> Doc: Add SNMP integration to breaking changes

- versions.yml
> Update bundled JDK

- logstash-core/lib/logstash/util/substitution_variables.rb
[rn:skip]
The `LogStash::Util::SubstitutionVariables#replace_placeholders` was recently [changed](https://github.com/elastic/logstash/pull/16375), and starting from Logstash `8.15.1` it requires a new argument (`refine`).
Considering plugins might be using this method internally (e.g: [logstash-input-azure_event_hubs](https://github.com/logstash-plugins/logstash-input-azure_event_hubs)), we should make the new argument optional, so existing usages won't break due this change.
- Relates https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues/91
> Change SubstitutionVariables.replace_placeholders `refine` argument to optional

- x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
[rn:skip] 
Set the 'api.enabled' setting to reflect the flag webserver_enabled and consequently test for http_address presence in settings iff the web server is enabled.
This PR is related to a failure that happens only in #16500 in particular it fails without this change:
https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1563#019257d1-c7bb-496c-81bd-c6c33dd56f07/70-2468 . With this change the setup of the test verify the presence of `http_address` in stats API if and only if the webserver is enabled,  verified by https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1603.
How ever it's not clear why it didn't fail on `main` but only in the branch of #16500 which switched the default Netty allocation type from `direct` to `heap`.
- ~~[ ] I have made …
> [test] Fix xpack test to check for http_address stats only if the webserver is enabled

- docs/static/monitoring/monitoring-apis.asciidoc
[rn: skip]
Documents the added `indicators.pipeline.<pipeline_id>.details.flow` node for the health report API
As users on-board to the health report, presenting the schema will help them :)
Relates: #16532
> docs: add health details for flow/worker_utilization

- logstash-core/lib/logstash/config/modules_common.rb
- modules/netflow/configuration/logstash/netflow.conf.erb
- x-pack/modules/azure/configuration/logstash/azure.conf.erb
Add deprecation logs for modules netflow, fb_apache and azure
Updated the deprecation log to send a clear message that netflow, fb_apache and azure modules will be removed in next major update.
```yaml
modules:
- name: netflow
```  
- relates: https://github.com/elastic/logstash/issues/16357
> add modules deprecation log for netflow, fb_apache and azure

- docs/static/arcsight-module.asciidoc
[rn:skip]
Updates guide for ArcSight Module to deprecate it.
Deprecating the module for future removal in guide and provide an action to switch to Elastic CEF Integration.
- Relates #16551
> Marked ArcSight Module as deprecated in documentation.

- Gemfile.jruby-3.1.lock.release
- versions.yml
> Bump 8.15.4

- versions.yml
> Bump version to 8.17.0

- build.gradle
[rn:skip]
Fix bad reference to a variable
> Fix bad reference to a variable

- versions.yml
Update JDK to version 21.0.5+11
Updates the version.yml to align to latest JDK 21
> Update JDK to latest in versions.yml

- .github/ISSUE_TEMPLATE/test-failure.md
Context: https://groups.google.com/a/elastic.co/g/dev/c/bheizuM6WVk/m/jJcG41z3AQAJ
> Remove link to deleted cluster

- Gemfile.jruby-3.1.lock.release
- versions.yml
[rn:skip]
Bumps the version to 8.16.1
> Bump version to 8.16.1

- docs/static/releasenotes.asciidoc
Adds these PRs to 8.16 branch (effectively a forwardport): 
- https://github.com/elastic/logstash/pull/16611
- https://github.com/elastic/logstash/pull/16661 (with minor formatting changes)
- https://logstash_bk_16663.docs-preview.app.elstc.co/guide/en/logstash/8.16/logstash-8-16-0.html
- https://logstash_bk_16663.docs-preview.app.elstc.co/guide/en/logstash/8.16/logstash-8-15-4.html
- https://logstash_bk_16663.docs-preview.app.elstc.co/guide/en/logstash/8.16/logstash-8-15-3.html
- https://logstash_bk_16663.docs-preview.app.elstc.co/guide/en/logstash/8.16/logstash-8-15-2.html
- https://logstash_bk_16663.docs-preview.app.elstc.co/guide/en/logstash/8.16/logstash-8-15-1.html
- https://logstash_bk_16663.docs-preview.app.elstc.co/guide/en/logstash/8.16/logstash-8-15-0.html
> Doc: Realign release notes and add known issue

- build.gradle
- rakelib/lint.rake
- rubyUtils.gradle
[rn:skip]
This commit extends the gradle and rake tasks to pass through a list of files for rubocop to lint. This allows more specificity and fine grained control for linting when the consumer of the tasks only wishes to lint a select few files.
This is an internal modification for the tasks developers use to build and test logstash, there will be no user facing changes. 
~~- [ ] My code follows the style guidelines of this project~~
Here are some of the ways …
> Extend ruby linting tasks to handle file inputs

- Gemfile.template
> Pin `date` dependency to `3.3.3`

- Gemfile.jruby-3.1.lock.release
- versions.yml
don't merge until 8.17.0 is GA
> bump to 8.17.1

- docker/templates/IronbankDockerfile.erb
- docker/templates/hardening_manifest.yaml.erb
update the base image to 9.5
need to backport to all branches
> update ironbank image to ubi9/9.5

- docs/static/breaking-changes-90.asciidoc
[rn:skip]
This PR aggregates all the modifications across the following PRs in to a single PR. This is meant to reduce friction from rebasing and allow the reviewer to see all the proposed changes in a single place. 
https://github.com/elastic/logstash/pull/16777
https://github.com/elastic/logstash/pull/16778
https://github.com/elastic/logstash/pull/16790
https://github.com/elastic/logstash/pull/16791
https://github.com/elastic/logstash/pull/16792
https://github.com/elastic/logstash/pull/16815
https://github.com/elastic/logstash/pull/16820
> Ssl standardization breaking changes docs

- Gemfile.jruby-3.1.lock.release
[rn:skip]
Updates the `elastic_integration` plugin version
-
> Update `elastic_integration` plugin versions in 8.16.

- Gemfile.jruby-3.1.lock.release
[rn:skip] 
Updates `elastic_integration` plugin version to 8.17.0
-
> Update `elastic_integration` plugin version in 8.17.

- docs/static/breaking-changes-90.asciidoc
Modify messaging for WPS integration deprecation
> Doc: WPS integration

- docs/static/releasenotes.asciidoc
forwardport the release note of 8.16.3 #16879
> Forward port release notes for 8.16.3

- Gemfile.template
- lib/bootstrap/bundler.rb
- lib/bootstrap/patches/jar_dependencies.rb
exhaustive test run for 8.x https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/1156 🟢
> fix jars installer for new maven and pin psych to 5.2.2

- Gemfile.jruby-3.1.lock.release
> Copy Gemfile from 8.17 to 9.0

- ci/branches.json
[rn:skip]
Adds 9.0 branch to the CI branches.
-
> Add 9.0 branch to the CI branches definition

- versions.yml
> Core version bump to 9.1.0

- ci/logstash_releases.json
[rn:skip]
Adds 9.0 snapshot to CI release definitions.
-
> Add short living 9.0 next and update main in CI release version definition.

- Gemfile.jruby-3.1.lock.release
[rn:skip]
Updates `elastic_integration` plugin version with 9.0 pre-release.
No impact
-
> Update elastic_integration version with 9.0 pre-release.

- docs/static/releasenotes.asciidoc
forward-ports 8.16.4 release notes to 8.17 branch
> docs: forward-port 8.16.4 release notes to 8.17

- docs/static/releasenotes.asciidoc
forward-ports 8.16.4 and 8.17.2 release notes to 8.18
> docs: forward-port 8.16.4 and 8.17.2 release notes to 8.18

- Gemfile.jruby-3.1.lock.release
[rn:skip]
Upgrades net-imap to 0.5.6
-
> [8.18] Upgrade net-imap to 0.5.6

- Gemfile.jruby-3.1.lock.release
[rn:skip]
Upgrades net-imap to 0.5.6
-
> [9.0] Upgrade net-imap to 0.5.6

- Gemfile.jruby-3.1.lock.release
[rn:skip]
Upgrades filter-xml plugin and its nokogori dependency.
N.A
-
> Upgrade filter-xml and its nokogori dependency.

- docker/templates/Dockerfile.erb
as per guidance https://github.com/elastic/logstash/pull/16063#discussion_r1577000627
> Update Dockerfile.erb to set eux on RUN command with semicolons

- docs/release-notes/breaking-changes.md
Currently stalling https://github.com/elastic/search-ui/pull/1116
> [DOCS] Fix doc link

- .mergify.yml
Add support for the two existing active branches 8.18 and 9.0 when using Mergify
First PR didn't actually add them
-
> mergify: add backport rules for 8.18 and 9.0

- docs/reference/running-logstash-kubernetes.md
Fixes: #17045 
Replaces: #17175
> Doc: Running LS in ECK

- qa/integration/fixtures/logstash_to_logstash_spec.yml
- qa/integration/fixtures/persistent_queues/logstash.yml
- qa/integration/specs/logstash_to_logstash_spec.rb
[rn:skip] 
Follows up on https://github.com/elastic/logstash/pull/17228
Replaces heartbeat-input with reload option, set queue drain to get consistent result.
It now passes with 1st try:
- https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/417#019567b3-3a73-436f-8582-c4e28375649f/1521-1994
- https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/418#019567e0-27ae-4714-b4bb-8ac878a174dc/3039-4606
-
> Additional cleanify changes to ls2ls integ tests

- .mergify.yml
[rn:skip] 
Mergify is commenting under old PRs, disabling conflict comment process for now.
-
> Temporarily disable mergify conflict process.

- docs/static/releasenotes.asciidoc
Forward Port of Release notes for `8.16.5` and `8.17.3`
* Update release notes for 8.17.3
* Update release notes for 8.16.5
> Forward Port of Release notes for `8.16.5` and `8.17.3` (#17187), (#17188)

- docs/static/releasenotes.asciidoc
* Update release notes for 8.16.5
> Forward Port of 8.16.5 release notes (#17188)

- ci/get-test-half.sh
- ci/integration_tests.sh
[rn:skip]
For the fedramp high work https://github.com/elastic/logstash/pull/17038/files a use case for multiple scripts consuming the partitioning functionality emerged. As we look to more advanced partitioning we want to ensure that the functionality will be consumable from multiple scripts.
See https://github.com/elastic/logstash/pull/17219#issuecomment-2698650296
NA, test setup only. 
- Relates to https://github.com/elastic/logstash/pull/17038/files
- Requested from https://github.com/elastic/logstash/pull/17219
> Shareable function for partitioning integration tests

- rakelib/artifacts.rake
- rubyUtils.gradle
[rn:skip]
Previously when rake would shell out the output would be lost. This made debugging CI logs difficult. This commit updates the stack with improved message surfacing on error.
N/A
- https://github.com/elastic/logstash/pull/17298
> Surface failures from nested rake/shell tasks

- docs/reference/ecs-ls.md
- docs/reference/getting-started-with-logstash.md
- docs/reference/index.md
First pass at refining MD content in `logstash` repo
Pull in intro file from raw-migrated-content.  (ToDo: Delete donor file.)
Correct some formatting errors.
Update JVM default info for 9.0
Related: #17322
To see a preview, click "View deployment" on the line after the most recent commit.
> Doc: Refine new MD docs (WIP)

- logstash-core/spec/logstash/pipeline_action/reload_spec.rb
- logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
[rn:skip]
Removed unused configHash computation happening in AbstractPipeline and used only in tests replaced by PipelineConfig.configHash() invocation
No user facing changes
-
> Removed config hash computation from pipeline

- logstash-core/build.gradle
- logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
- logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java
Avoid possible integer overflow in string tokenization.
Use long instead of int type to keep the length of the first token.
The size limit validation requires to sum two integers, one with the length of the accumulated chars till now plus the next fragment head part. If any of the two sizes is close to the max integer it generates an overflow and could successfully fail the test https://github.com/elastic/logstash/blob/9c0e50faacc4700da3dc84a3ba729b84bff860a8/logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java#L123.
To fall in this case it's required that sizeLimit is bigger then 2^32 bytes (2GB) and data fragments without any line delimiter is pushed to the tokenizer with a total size close to 2^32 bytes.
Avoid to miss the notification of buffer full condition when …
> Added test to verify the int overflow happen

- .buildkite/linux_jdk_matrix_pipeline.yml
Disable support of OpenJDK 17.  For official OpenJDK 17 releases the latest version is 17.0.2+8 that not supported anymore. We will continue to support adoptiumjdk 17 from adoptium/temurin17-binaries repo.
See this [build](https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/416#annotation-ubuntu-2204_openjdk_17) that failed
> Remove OpenJDK 17 from jdk test matrix

- docs/reference/docker.md
- docs/reference/toc.yml
- docs/reference/upgrading-logstash.md
- docs/release-notes/breaking-changes.md
- docs/release-notes/index.md
More work refining MD content in `logstash` repo
Restructure Upgrade content
Correct broken links and formatting errors.
Related: #17322
Followup to: #17325
> Doc: Fix upgrade TOC structure

- .buildkite/scripts/common/check-files-changed.sh
> Do not pipe Git output into a pager.

- .github/dependabot.yml
[rn:skip]
Add dependabot to bump the GH actions
Help us to keep the GH actions ecosystem up to date.
That's something we also do in other places
-
> github-actions: enable dependabot

- docs/static/persistent-queues.asciidoc
> Fix persistent-queues.asciidoc PQ sizing multiplication factors

- docs/release-notes/index.md
Moves 9.0.0 pre-release notes over for 9.0.0
Are there any new items that we need to add?
> Doc: Move 9.0 pre-release notes to release notes

- docs/static/monitoring/monitoring-ea-dashboards.asciidoc
- docs/static/monitoring/monitoring-ea-serverless.asciidoc
- docs/static/monitoring/monitoring-ea.asciidoc
- docs/static/monitoring/monitoring-mb.asciidoc
[rn:skip]
Add recommendations to collect all metrics 
Provides a tip to get the best experience with monitoring dashboards.
-
> [8.x][Docs] Add recommendations to collect all metrics for the best dashboard experience.

- ci/logstash_releases.json
> Update logstash_releases.json after 8.18.0

- Gemfile.jruby-3.1.lock.release
- versions.yml
Version bump to 9.0.1 after release.
> Bump to 9.0.1

- Gemfile.jruby-3.1.lock.release
- versions.yml
Version bump to 8.17.6 after release.
> Update version to 8.17.6

- .ci/Makefile
- .mergify.yml
[rn:skip]
Remove support for `8.x` with Mergify and enable support for `8.19`. I also updated the mergify template to use the default values to help with the simplicity.
-
> mergify: support 8.19 and remove support 8.x

- .buildkite/scripts/benchmark/marathon.sh
[rn:skip]
Updates LS versions in marathon CI.
N.A
-
> Update marathon CI pipeline to reflect recent LS released versions.

- docs/include/plugin_header-nonstandard.asciidoc
Related: https://github.com/elastic/logstash-filter-elastic_integration/issues/286
> Doc: Add non-standard header file

- docs/static/releasenotes.asciidoc
> security advisory message added to 8.17.6 release notes

- .github/workflows/critical_vulnerability_scan.yml
> Update Grype GH action to v6

- ci/logstash_releases.json
> Update logstash_releases.json after 8.18.2

- .github/workflows/docs-build.yml
- .github/workflows/docs-cleanup.yml
Related:
- #17701
- #17700 
- Backport #17704 failed because the file to be updated was missing
> Doc: Add docs-build.yml for 9.0

- docker/README.md
- docker/templates/Dockerfile.erb
- docs/static/docker.asciidoc
- qa/docker/spec/full/container_spec.rb
- qa/docker/spec/oss/container_spec.rb
exhaustive tests: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/2024/steps/canvas
> Upgrade OSS and Full docker image to Ubuntu 24.04

- .buildkite/scripts/benchmark/util.sh
This commit uses standardize docker name for new versions
> [CI] fix benchmark docker name

- docs/reference/index.md
Add a whitespace edit to help troubleshoot an issue with the doc build.
> [docs] Whitespace edit for testing the doc build

- docs/static/transforming-data.asciidoc
Added sample output structure for geoip filter
**PREVIEW:** https://logstash_bk_18101.docs-preview.app.elstc.co/guide/en/logstash/8.19/lookup-enrichment.html#geoip-def
Related:
- https://github.com/elastic/docs-content/issues/2782
- https://github.com/elastic/logstash/pull/18092
> Doc: Refine geoip filter example for 8.19

- docs/reference/connecting-to-cloud.md
- docs/reference/connecting-to-serverless.md
Related: https://github.com/elastic/docs-content-internal/issues/176
Followup to #18034
> Doc: Refine serverless and hosted content

- logstash-core/spec/logstash/settings_spec.rb
[rn:skip]
Cover with test the warn policy in ValidatedPassword.
N/A
- Relates #18182
- Relates #18199
> Cover the warn password policy usage of ValidatedPassword setting
