Gemfile.defaults
Gemfile.jruby-1.9.lock.defaults
rakelib/artifacts.rake

the 1.5 package is not clean, here are some fixes:
- the Gemfile.defautls contained reference to the local gemspec for logstash-core. it need to be referring to the gem from the source
- we don't want to include the `.bundle/config`, `Gemfile*.defaults` and the `logstash-core.gemspec` in the package
Note that the `Gemfile` can still use the reference to the gemspec but when creating the `.defaults` files we need to chage the `Gemfile` to
```ruby
source "https://rubygems.org"
gem "logstash-core"
```
and then:
```sh
rm -rf .bundle Gemfile.jruby-1.9.lock vendor/bundle
rake bootstrap
rake plugin:install-default
```
```sh
cp Gemfile Gemfile.default
cp Gemfile.jruby-1.9.lock  Gemfile.jruby-1.9.lock.defaults
```
and finally do 
```sh
rake artifact:tar
```

clean 1.5 package generation

---

rakelib/artifacts.rake
rakelib/plugin.rake

rake artifact:tar will either build the local `logstash-core` gem and embed it in the package if the `Gemfile` contains
gem "logstash-core", :path => "."
or othewise rely on the Rubygems  `logstash-core` if there is no :path specification

support remote or local gem packaging

---

lib/logstash/environment.rb

this fixes the issue where executing `bin/bundle rspec` in a dev plugin dir with the new logstash-core code aborts with 
ERROR: missing LOGSTASH_HOME environment variable

environment when not in package context

---

Gemfile
Gemfile.jruby-1.9.lock
rakelib/artifacts.rake

Fixes #3176 by using the same strategy as the one used to fix the other packages, adding the rubyzip in this case to the build group in the Gemfile.

Make rubyzip a dependency installed via the Gemfile, so the artifact:zip task works as expected

---

lib/logstash/outputs/file.rb
spec/outputs/file.rb

Before this Fix, people were able to use the string interpolation of the event (Event#sprintf)
to generate files outside the defined path. This pull request try to extract a document
root from the configuration and sandbox the creation of new file in that environment.

[1.4] Dont allow creating new files outside the document root

---

lib/logstash/util/accessors.rb
logstash-core.gemspec
spec/util/accessors_spec.rb

while working on a Java implementation of the `Accessors` class, I realized commit b7ba48d393f9d17a8a4f377d8739af4fdf9c0343 introduced errors with the `@lut` usage resulting in less efficient code and also some unnecessary code complexity. 
the slowdown is really dependant of the type of config used but a config doing multiple lookups on the same field reference will benefit from this fix. 
benchmarks are showing 10-30% better performance. the following test results in a ~28% improvement.
- using fix/accessors at 320607aa04c9459c692e0238045d9001737241a6
```sh
bin/logstash -e 'input { generator { } } filter { mutate { add_field => { "[foo][bar][baz]" => "foo" "[fancy][pants]" => "bar" } } if [foo][bar][baz] == "baz" {} if [fancy][pants] == "baz" {} if [foo][bar][baz] == "baz" {} if …
```

Accessors: correct use of @lut and cleanups	

---

Gemfile
Gemfile.jruby-1.9.lock
ci/ci_setup.sh
rakelib/test.rake
spec/core/conditionals_spec.rb
spec/core/event_spec.rb
spec/core/pipeline_spec.rb
spec/lib/logstash/java_integration_spec.rb
spec/util/json_spec.rb

The motivation of this PR is to upgrade the test runner in place to rspec 3.x branch, so we can leverage all the nice features it has.
Related PRs:
https://github.com/elastic/logstash-devutils/pull/29
https://github.com/logstash-plugins/logstash-input-s3/pull/43
Upstream issue (https://github.com/rspec/rspec-mocks/issues/964) created because of the jrjackson error when using the ```and_call_original``` expectations in rspec3.

Update to use rspec3 as test runner 

---

Gemfile.jruby-1.9.lock
logstash-core.gemspec

JrJackson cannot encode objects inheriting from RubyBasicObject, which is blocking a fix for https://github.com/logstash-plugins/logstash-input-twitter/issues/15

Bump JrJackson gem to 0.2.9 to fix RubyBasicObject bug

---

lib/logstash/agent.rb
lib/logstash/environment.rb
spec/core/environment_spec.rb
spec/logstash/agent_spec.rb

restore the `--pluginpath` option to support bare/ungemified local plugins
solves #3580

support for bare/ungemified local plugins using --pluginpath option

---

docs/asciidoc/static/include/pluginbody.asciidoc
lib/logstash/codecs/base.rb
lib/logstash/filters/base.rb
lib/logstash/inputs/base.rb
lib/logstash/pipeline.rb
lib/logstash/plugin.rb
logstash-core.gemspec
spec/core/pipeline_spec.rb
spec/filters/base_spec.rb

This is a PR reboot of #3812 from a shared branch to facilitate collaboration.
Currently, during shutdown, the pipeline loops through input workers
and calls Thread.raise on each input thread. Plugins rescue that
exception to exit the `run` loop. Afterwards, `teardown` is called for
any additional bookkeeping.
This proposal exposes a `stop` call on the input plugin class to alert
an input that it should shutdown. It is the plugin job to frequently
poll an internal `stop?` method to know if it's time to exit and
terminate if so.
The `teardown` method remains to do the additional bookkeeping, and it
will be called by the inputworker when `run` terminates.
resolves #3210 and replaces #3211

pipeline shutdown OOB plugins stop

---

bin/bundle

invoking `bin/bundle` does not use the correct logstash vendor path. 
with this fix invoking `bin/bundle` will work as intended using the correct `Gemfile`, `Gemfile.jruby-1.9.lock` and `vendor/bundle/...` path

fix bin/bundle command

---

spec/coverage_helper.rb

new paths from #4123 were not updated for coverage support and results in builds breaking

fix coverage paths for new structure by #4123

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/util/defaults_printer.rb
logstash-core/lib/logstash/util/worker_threads_default_printer.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/spec/logstash/util/defaults_printer_spec.rb
logstash-core/spec/logstash/util/worker_threads_default_printer_spec.rb

**Notes to reviewers:**
- Allow the default to be set as a function of cores without checking thread safety of filters. 
- Allow the command line setting of `-w 6` without checking as above.
- Move the check and alteration of thread_count into the `start_filters` because this allows for dynamic changes to the config. Before, it was only checked at pipeline start.
After PH and Colin initial review:
- override logic from -w command line args refactored, see agent.rb and pipeline.rb
Fixes #4130

Add provision for worker threads based on threadsafe workers

---

logstash-core-event/spec/logstash/event_spec.rb

this fixed intermittent core specs failures depending if `Event#to_s` was called before the `Event` specs.

clean cache to empty previous entries

---

logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/pipeline_spec.rb

initializes @filter_threads to be an empty array so that the Shutdown controller can deal with no filters gracefully.
this needs to be merged into master, 2.x and 2.1
fixes #4271

fix shutdown controller when using no filters

---

logstash-core-event-java/spec/event_spec.rb
logstash-core-event-java/src/main/java/com/logstash/ext/JrubyEventExtLibrary.java
logstash-core-event/spec/logstash/event_spec.rb

this PR builds on top of #4263 
and also add related missing spec in Ruby Event
this relates to #4264 and #4191 and is required to have the filter grok specs pass with the Java Event.

fix nil value field reference assignment in Java Event

---

logstash-core-event-java/src/main/java/com/logstash/Timestamp.java
logstash-core-event-java/src/main/java/com/logstash/ext/JrubyTimestampExtLibrary.java
logstash-core-event/spec/logstash/timestamp_spec.rb

this PR builds on top of #4265
- add missing `utc`, `gmtime` and `to_f` methods in the Java `Timestamp`
- add missing specs for these methods in the Ruby `Timestamp` specs to prevent future regressions
this relates to #4264 and #4191 and fixes sqs input specs under Java `Event`.

fix missing methods in Java Timestamp

---

logstash-core/lib/logstash/pipeline.rb

because lots of plugins monkeypatch the pipeline and `output_func` returns nil we need to check for this until we properly refactor this specs as discussed in #4382 
Replaces #4373

fix to support legacy plugins specs monkeypatching pipelines

---

Gemfile
Gemfile.jruby-1.9.lock
logstash-core-event/lib/logstash-core-event/version.rb
logstash-core/lib/logstash-core/version.rb
logstash-core/lib/logstash/version.rb
logstash-core/logstash-core.gemspec

Bump version, update gem and lock file to point to RubyGems.org
in preperation for 2.2.0 release

Bump version to 2.2.0.snapshot2

---

logstash-core-event/spec/logstash/event_spec.rb

specs for nil values in `Event` array fields.
this relates to discussion in Java Event implementation #4494

add specs for nil values in array fields

---

logstash-core-event-java/build.gradle
logstash-core-event-java/lib/logstash-core-event-java/logstash-core-event-java.rb

- attach jar copy hook to the jar generation and not build
- change location of jar into `lib/logstash-core-event-java/`
- simplify jar `require`
fixes #4578

fix jar generation for artifact packaging

---

logstash-core-event-java/logstash-core-event-java.gemspec

as of Feb 3rd 2016, the ruby-maven gem is resolved to version 3.3.3 and that version has an rdoc problem that causes a bundler exception. 3.3.9 is the current latest version which does not have this problem.
/cc @purbon @ph

force ruby-maven version

---

logstash-core-event-java/build.gradle
logstash-core-event-java/lib/logstash-core-event-java_jars.rb
logstash-core-event-java/logstash-core-event-java.gemspec
logstash-core-event-java/spec/event_spec.rb
logstash-core-event-java/src/main/java/com/logstash/Event.java
logstash-core-event-java/src/main/java/com/logstash/KeyNode.java
logstash-core-event-java/src/main/java/com/logstash/TemplateNode.java
logstash-core-event-java/src/main/java/com/logstash/Timestamp.java
logstash-core-event-java/src/main/java/com/logstash/TimestampSerializer.java
logstash-core-event-java/src/main/java/com/logstash/ext/JrubyEventExtLibrary.java
logstash-core-event-java/src/main/java/com/logstash/ext/JrubyTimestampExtLibrary.java
logstash-core-event-java/src/test/java/com/logstash/EventTest.java
logstash-core/spec/logstash/json_spec.rb

will fix #4595 
This introduces `Event#from_json` which takes as argument a json string and returns a new `Event` object. The idea here is to update the json_lines codec to use this method to avoid double type conversion by first parsing the json to a Ruby structure then passing that structure to the Java Event and go through unnecessary type conversions. the POC has shown a ~50% performance increase using this. 
Note that this PR adds specs for the input corner cases behaviour of the current deserialization behaviour to make sure `from_json` behaves the same way.

add Event#from_json method

---

logstash-core-event-java/spec/event_spec.rb
logstash-core-event-java/src/main/java/com/logstash/Event.java
logstash-core-event-java/src/test/java/com/logstash/EventTest.java

`Event#from_json` was previously generating empty `Event` on blank/empty json input but it should just ignore it and not generate empty event.
This complements logstash-plugins/logstash-codec-json_lines/pull/22

from_json should not generate new Event on blank/empty json input

---

logstash-core-event-java/src/main/java/com/logstash/ext/JrubyTimestampExtLibrary.java

Fixes a typo discovered in #4565 discussion. 
Note that this typo is currently harmless since its definition and all usages/calls are consistently using the incorrectly typed identifier :P

renamed newTimetsamp to newTimestamp

---

logstash-core-event-java/spec/event_spec.rb
logstash-core-event-java/src/main/java/com/logstash/Rubyfier.java
logstash-core-event-java/src/test/java/com/logstash/RubyfierTest.java

The Java BigDecimal type conversion to a proper Ruby BigDecimal is not handled by the default JRuby type converter and it must be handled in the `Rubyfier` class. Also added tests.
This problem has been spotted while working on the GELF input logstash-plugins/logstash-input-gelf#35 and running specs against master with the Java `Event`.
It was also reported by @guyboertje in a discussion earlier today but I can't recall it was about what :grimacing: 
Prior to this patch the GELF input specs were not passing against master.

correctly handle BigDecimal Rubyfying

---

logstash-core-event-java/spec/event_spec.rb
logstash-core-event-java/src/main/java/com/logstash/Javafier.java
logstash-core-event-java/src/test/java/com/logstash/JavafierTest.java
logstash-core-event-java/src/test/java/com/logstash/RubyfierTest.java

fixes #4898 
Add support for  RubyBignum in `Javafier` class + tests.

support RubyBignum in Javafier

---

docs/static/breaking-changes.asciidoc
docs/static/releasenotes.asciidoc
docs/static/submitting-a-plugin.asciidoc
docs/static/upgrading.asciidoc

The link issues were fixed in the logstash-docs repo, but not the logstash repo.
Also adding content changes that were made in the logstash-docs repo, but not the logstash repo.

Fix links causing build errors and add missing files

---

docs/static/deploying.asciidoc

Product name update for 5.0. I didn't update the corresponding doc link for alpha 1 (it still points to current) because the location of security content is currently in flux. 
The following variable will be added to the index.asciidco in logstash-docs:
:security:              X-Pack Security

Update terminology used for security product

---

docs/static/command-line-flags.asciidoc
logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/spec/logstash/runner_spec.rb

We now hide this because displaying it is dangerous. Generated code
and other AST data may contain plaintext copies of 'password' type fields.
Users can force this to appear with the --debug-config flag.
Fixes https://github.com/elastic/logstash/issues/4964

Hide sensitive AST/config data unless --debug-config argument passed

---

logstash-core-event/lib/logstash/timestamp.rb

required to pass specs under #5023

fix jruby bigdecimal handling in Time.at

---

Gemfile
Gemfile.jruby-1.9.lock
logstash-core-event/logstash-core-event.gemspec
logstash-core/logstash-core.gemspec

logstash-core-event-java introduces backward compatibility problems with ruby filter scripts and custom plugins.
before merging, these 2 specs errors need to be addressed
```
1) LogStash::Timestamp at with BigDecimal epoch should return usec with a minimum of millisec precision
Failure/Error: expect(LogStash::Timestamp.at(BigDecimal.new("946702800.123456")).usec).to be_within(1000).of(123456)
expected 0 to be within 1000 of 123456
2) LogStash::Timestamp at with BigDecimal epoch should convert to correct date
Failure/Error: expect(LogStash::Timestamp.at(BigDecimal.new("946702800.123456")).to_iso8601).to eq("2000-01-01T05:00:00.123Z")
expected: "2000-01-01T05:00:00.123Z"
got: "2000-01-01T05:00:00.000Z"
(compared using ==)
Finished in 16.5 seconds (files took 3.21 seconds to load)
1441 …
```

revert to logstash-core-event 

---

logstash-core-event-java/src/main/java/com/logstash/Accessors.java
logstash-core-event-java/src/test/java/com/logstash/AccessorsTest.java
logstash-core-event/lib/logstash/util/accessors.rb
logstash-core-event/spec/logstash/event_spec.rb

This is a fix for the Accessors fieldref cache invalidation in the Ruby Event only. Before considering merging this we should assess the performance impact and see if using a hierarchical cache would provide better performance. Depending on the direction we choose for the fix, the same idea will have to be applied to the Java Event.
A stale cache spec has been added. 
Fixes #5127 
**[edit 04/20]**
Per comments below, we agreed that this fix is acceptable performance-wise and the same fix has been applied to the Java Event. Doing so uncovered another bug that resulted in a `expecting List or Map ` ClassCastException, also fixed and related test added.

fix for accessors lut invalidation

---

CHANGELOG.md

Remove Kafka changes because of https://github.com/logstash-plugins/logstash-output-kafka/pull/60

Remove Kafka changes from changelog

---

rakelib/artifacts.rake

Some users may have scripted the download location, so I don't
feel right in breaking this name in a bug fix version. This change should
be documented as breaking, IMO
#5125 introduced:
logstash-2.3.2_all.deb
logstash-2.3.2.tar.gz
logstash-2.3.2.zip
logstash-2.3.2.noarch.rpm
v2.3.1 files:
logstash_2.3.1-1_all.deb
logstash-2.3.2.tar.gz
logstash-2.3.2.zip
logstash-2.3.1-1.noarch.rpm

Revert #5125 from 2.3

---

lib/pluginmanager/gemfile.rb
lib/pluginmanager/install.rb
rakelib/plugin.rake

Allow using the `--preserve` option to the plugin install command to preserve any current gem options in the `Gemfile` for the installation of a plugin gem which is already in the `Gemfile`.
This is required by #5170 to support specifying plugin gems from a github repo/branch in the `Gemfile`. I believe this will also help avoiding the unnecessary publication of core plugins snapshots.
Ultimately this allows running the rake test:install* command by keeping current `Gemfile` gems options, for example a custom in-dev `:path` option, instead of overwriting them and forcing the use of the published gem.

add --preserve option to plugin install

---

docs/static/monitoring-apis.asciidoc

Changed so that the source uses a variable rather than hard coding version info.

Update alpha note to use variable for version

---

docs/static/command-line-flags.asciidoc
docs/static/configuration.asciidoc
logstash-core/lib/logstash/config/mixin.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/config/mixin_spec.rb
logstash-core/spec/logstash/runner_spec.rb

allow-env flag was introduced because of a backwards incompatible
change, this flag is no longer needed for 5.0 and onwards.
Closes #5263.

undo allow_env flag

---

CONTRIBUTING.md

* Move Contributors from `.github` to root for more visibility
* Added note about priority labels - P1 to P4

Move and edit contributors.md

---

logstash-core-event-java/spec/event_spec.rb
logstash-core-event-java/src/main/java/com/logstash/ext/JrubyEventExtLibrary.java

I fixed the Event initialize for the Java Map parameter case. the initialize method cannot receive a pure Java object parameter but only a proxied Java object and the only one we support is actually the `MapJavaProxy` and we can efficiently get to the original Map object instead of going through the hoops of `to_java`.

optimize Java Map initialization

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/pipeline_reporter_spec.rb
logstash-core/spec/logstash/pipeline_spec.rb

This PR make sure that all the tests using the agent or the pipeline are
correctly shutting down their pipelines to make sure the metrics state
are coherent with the config defined in the test.
Fixes: #5291

Fixing the faillings metrics tests

---

logstash-core/spec/logstash/agent_spec.rb
spec/unit/license_spec.rb

License tests was failing because of GPL2 in mime-types.Added an
exception for this gem because v2.6.2 is triple-licensed and we pick
MIT.
Metrics test is failing because of address in use which is fixed in
PR #5307. Skipping this test for now. @ph is ok with this.

Fix failing tests on master and 5.0

---

Gemfile.jruby-1.9.lock

Previous update had included 3.x of geoip filter which was a rewrite for GeoIP2. This should not be included in a bug fix release, so reverting to 2.x

Revert geoip filter to 2.x

---

bin/logstash
qa/acceptance/spec/shared_examples/cli/logstash/version.rb

```
/tmp/logstash-5.0.0 % time bin/logstash -V
logstash 5.0.0
bin/logstash -V  27.79s user 1.34s system 270% cpu 10.773 total
/tmp/logstash-5.0.0 % patch -p1 < /tmp/patch
patching file bin/logstash
/tmp/logstash-5.0.0 % time bin/logstash -V
logstash 5.0.0
bin/logstash -V  0.01s user 0.02s system 101% cpu 0.029 total
```
Still figuring out how to do the same in Windows BAT scripts..

make -V/--version fast on *nix

---

logstash-core/lib/logstash/agent.rb
logstash-core/spec/logstash/agent_spec.rb

Fixes #5549 by not masquerading  reported errors that happen during bootstrap time inside the agent class, this is not the right place to do the reporting as it should happen in runner, but all this is already properly refactored for 5.0 branch. In this PR I tried to keep the same style and logic when proposing a fix.

Make sure errors are reported also to terminal if show_startup_errors is true

---

rakelib/artifacts.rake

Previously we only built zip and tar for all-plugins. Fixes #4361

Add rake task to build rpm and deb all-plugins

---

logstash-core/lib/logstash/pipeline.rb

Inputs were not namespaced properly for the metrics, api, this PR fixes this so each inputs is namespaces like
being consistent with filters and outputs.
@ph @andrewvc your thoughts here are very welcome.

Add namespaced metrics for inputs

---

docs/static/plugin-manager.asciidoc

... otherwise it may pick up some real file name in the current working directory - which is not what's intended!

Doc: quote shell glob pattern

---

docs/static/plugin-manager.asciidoc

The plugin manager `--path.plugins` (old --pluginpath) is completely wrong in the documentation. It cost me FOUR hours to find the bug and I hope this fix will remove pain for other developers.
This change should be backported to the current documentation.

Update plugin manager --path.plugins

---

docs/static/upgrading.asciidoc

Logstash can be invoked this way: "bin/logstash -w 1", so the example should be made to look like that.

Doc: fix quoting in shell source.

---

rakelib/artifacts.rake

To test this PR is necessary to build a package and see this files are not there anymore. Reasoning why this should be removed can be found at #5666.
Fixes #5666

Add bin/rspec and bin/rspec.bat to the packaging exclude list

---

pkg/centos/after-install.sh
pkg/debian/after-install.sh
pkg/ubuntu/after-install.sh

When installing Logstash (after previous removal of the Logstash RPM), there is a chance that there are old log files without proper owner.
Running Logstash as service, it may want to append data to these log files. Consequently, the logstash service does not start because it doesn't have write permissions to that files. This patch sets the (new) user logstash to own these historic files.

Update after-install.sh - fix log file permissions

---

logstash-core/lib/logstash/outputs/base.rb
logstash-core/spec/logstash/outputs/base_spec.rb

This is the 2.4 version of https://github.com/elastic/logstash/pull/5795 which targeted 2.x
This is a backport of https://github.com/elastic/logstash/pull/5752 to
the 2.x branch targetting the 2.4 release.
The changes here are more minimal since the pipeline code is simpler and we need to support
some other legacy constructs such as the instance level version of Outputs::Base#workers_not_supported.

Backport of Outputs#base.concurrency to 2.4 branch

---

logstash-core/lib/logstash/outputs/base.rb
logstash-core/spec/logstash/outputs/base_spec.rb

This is a backport of https://github.com/elastic/logstash/pull/5752 to
the 2.x branch targetting the 2.4 release.
The changes here are more minimal since the pipeline code is simpler and we need to support
some other legacy constructs such as the instance level version of Outputs::Base#workers_not_supported.

Backport of Outputs#base.concurrency to 2.x branch

---

logstash-core-event-java/lib/logstash/event.rb
logstash-core-event/lib/logstash/event.rb
logstash-core-event/spec/logstash/event_spec.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb

- introduces a `SignalEvent` base class and both `ShutdownEvent` and `FlushEvent` classes define the `flush?` and `shutdown?` method. This makes the checking for a signal event a bit faster and will help cleanup signal handling in the PQ branch.
- this previous modification revealed a namespacing problem: 
- the `LogStash::LogStash::SHUTDOWN` and `LogStash::LogStash::FLUSH` constants were defined.
- this problem was partially hidden by the fact that within the `Pipeline` class:
```
module LogStash; class Pipeline
...
end end
```
All constants were prefixed by `Logstash::` which is both unnecessary and inefficient since the lookups would start by trying to lookup `LogStash::Foo` within the `LogStash` module (`LogStash::LogStash::Foo`) and not find it.

base SignalEvent class and cleanup LogStash namespace

---

qa/integration/services/filebeat_setup.sh
qa/integration/specs/beats_input_spec.rb

changes.
In beta1, some options changes occurred in filebeat with the name of the
ssl options.
Like theses:
tls=>ssl
certificate_key => key

Update the configuration to make it work with the latest libbeat

---

logstash-core-event-java/lib/logstash-core-event-java_jars.rb

This file was incorrectly checked-in with a jackson-annotations
dependency of `2.7.3`. jackson-databind depends on `2.7.0` of the
annotations library.

Fix generated jar dependencies for ls-event-java

---

Gemfile
Gemfile.jruby-1.9.lock

Looks like we don't need the docker API gems after this PR: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/486

Update to new ES output

---

docs/static/breaking-changes.asciidoc
docs/static/deploying.asciidoc

These changes have already been pushed to 5.x in logstash-docs.

Fix messed up links in 5.x branch

---

docs/static/breaking-changes.asciidoc
docs/static/deploying.asciidoc

Minor tweak to paths for links. I've already pushed this change to logstash-docs.

Make vars used for doc links consistent

---

docs/static/breaking-changes.asciidoc
docs/static/event-api.asciidoc

Added new Event API doc to support breaking changes

[Doc] Rearrange breaking changes docs

---

logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/spec/logstash/util/wrapped_synchronous_queue_spec.rb
logstash-core/spec/support/mocks_classes.rb

Solves the bug described in issue #6055 where dropped events are still being output.
The problem is that Event cancellation is done by mutating the Event itself by calling Event#cancel and thus the Batch object is not informed of this change and cannot keep an internal state of the cancelled events as the events are processed through the `filter_func`. 
Ultimately the proper fix will be to surface the Batch object as the main container for keeping tabs on the Events lifecycle (originals, generated, cancelled, etc).

fix for cancelled events issue #6055

---

logstash-core-event-java/src/main/java/org/logstash/Event.java
logstash-core-event-java/src/test/java/org/logstash/EventTest.java
logstash-core/lib/logstash/filters/base.rb
logstash-core/lib/logstash/util/decorators.rb
logstash-core/spec/logstash/filters/base_spec.rb

This fixes #6142 and #6173 
it includes fixes for the following tagging bugs:
- adding tags using `Event#tag` over pre-existing bare `String` value in the `tags` field
- adding tags using config `add_tag` over pre-existing bare `String` value in the `tags` field
- removing tags over pre-existing bare `String` value in the `tags` field
- inefficient `add_tag` and `remove_tag` implementations

fix tagging edge cases

---

qa/integration/services/kafka_setup.sh

in master (6.0.0-alpha1), the kafka plugins are targeted towards Kafka `0.10.1.0`, integration tests need to be updated to reflect this.

bump kafka setup for integration tests to 0.10.1.0

---

bin/cpdump
config/logstash.yml
logstash-core-queue-jruby/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/util/wrapped_acked_queue.rb
logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/Checkpoint.java
logstash-core/src/main/java/org/logstash/ackedqueue/FileSettings.java
logstash-core/src/main/java/org/logstash/ackedqueue/HeadPage.java
logstash-core/src/main/java/org/logstash/ackedqueue/MemorySettings.java
logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/main/java/org/logstash/ackedqueue/Settings.java
logstash-core/src/main/java/org/logstash/ackedqueue/TailPage.java
logstash-core/src/main/java/org/logstash/common/io/CheckpointIO.java
logstash-core/src/main/java/org/logstash/common/io/FileCheckpointIO.java
logstash-core/src/main/java/org/logstash/common/io/MemoryCheckpointIO.java
logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

this PR adds support for these new queue settings
- `queue.checkpoint.acks`
- `queue.checkpoint.writes`
We decided to postpone `queue.checkpoint.interval` to validate the need for it since queue is now checkpointed on both acks and writes.

[WIP] add queue.max_acked_checkpoint and queue.checkpoint_rate settings

---

logstash-core-queue-jruby/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java
logstash-core-queue-jruby/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueMemoryExtLibrary.java
logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/api/commands/stats.rb
logstash-core/lib/logstash/api/modules/node_stats.rb
logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
logstash-core/lib/logstash/instrument/periodic_pollers.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/util/wrapped_acked_queue.rb
logstash-core/spec/api/lib/api/node_stats_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/TestSettings.java
qa/integration/services/service.rb
qa/integration/specs/monitoring_api_spec.rb

example queue section:
```javascript
"queue" : {
"type" : "persisted",
"capacity" : {
"page_capacity_in_bytes" : 262144000,
"max_queue_size_in_bytes" : 1073741824,
"max_unread_events" : 0
},
"data" : {
"free_space_in_bytes" : 33851523072,
"current_size_in_bytes" : 262144000,
"storage_type" : "hfs",
"path" : "/logstash/data/queue"
},
"events" : {
"acked_count" : 0,
"unread_count" : 0,
"unacked_count" : 0
}
}
```
When retrieving node stats for a logstash instance that is not running with `queue.type: persisted`, the output of this section will simply be:
```javascript
{ "type" : "memory_acked"}
or
{ "type" : "memory"}
```
as discussed in the comments below, this information will be per pipeline and under the `pipeline` section of the stats. All of these stats will be stored in the metrics …

add queue stats to node/stats api

---

LICENSE
NOTICE.TXT
rakelib/artifacts.rake
rakelib/license.rake

Adjust our existing NOTICE.txt file to be built every time. This ensures
we collect LICENSE and NOTICE information of all bundled Logstash and non-Logstash
dependencies.
Changes:
* if NOTICE file is present in gems, include that text in our own NOTICE.TXT file.
* we also need to include the whole copyright block in NOTICE (meaning copyright + license)

Generate notice file during artifact build

---

bin/lock
logstash-core/src/main/java/org/logstash/FileLockFactory.java
logstash-core/src/main/java/org/logstash/LockException.java
logstash-core/src/test/java/org/logstash/FileLockFactoryTest.java
rakelib/artifacts.rake

This is a Java class based on Lucene FSLockFactory and friends to support same and  cross-jvm/process exclusive file locking to implement #6604 and #6505.
Included are tests for same process/jvm and `bin/lock` to test cross jvm locking.

exclusive file locking class and tests

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/agent_spec.rb

this fixes #6605 
- refactor agent reload sequence to make sure a pipeline is shutdown before a new one is started with same settings.
- the goal here as stated in https://github.com/elastic/logstash/issues/6605#issuecomment-276751216 is to introduce the minimum changes to fix the dual pipeline problem for the next minor release, knowing that @ph is working on a deeper refactor of the whole config change management.

refactor agent pipeline reloading to avoid double live pipelines with same settings

---

pkg/logstash.default
pkg/logstash.sysv

When doing heaving lifting the current 10 seconds may not be sufficient to gracefully stop LS. Make the check period configurable, with 10 being the default (no change to current behaviour).

make wait time on stop configurable

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/runner.rb
logstash-core/spec/conditionals_spec.rb
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/spec/logstash/queue_factory_spec.rb
logstash-core/src/main/java/org/logstash/FileLockFactory.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/stress/Concurent.java

This fixes #6604 by implementing exclusive access to the queue at Pipeline initialization. 
The `sample` spec helper in **devutils** `logstash_helpers.rb`does not close the pipeline after instantiating it. I decided to explicitly close the pipelines in all tests using `sample` instead of modifying **devutils** because I am afraid of potential dependency conflicts if we update **devutils** at this point also knowing that it will be refactored into the main source tree soon.
I am not sure if this is the best idea, I am open to suggestions.

PQ exclusive access to path.queue using file locking

---

logstash-core/lib/logstash-core_jars.rb
logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/compiler/lscl.rb
logstash-core/lib/logstash/instrument/metric_store.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/compiler/compiler_spec.rb
logstash-core/src/main/java/org/logstash/common/Util.java
logstash-core/src/main/java/org/logstash/config/ir/IHashable.java
logstash-core/src/main/java/org/logstash/config/ir/Pipeline.java
logstash-core/src/main/java/org/logstash/config/ir/expression/BinaryBooleanExpression.java
logstash-core/src/main/java/org/logstash/config/ir/expression/Expression.java
logstash-core/src/main/java/org/logstash/config/ir/expression/UnaryBooleanExpression.java
logstash-core/src/main/java/org/logstash/config/ir/graph/BooleanEdge.java
logstash-core/src/main/java/org/logstash/config/ir/graph/Edge.java
logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java
logstash-core/src/main/java/org/logstash/config/ir/graph/IfVertex.java
logstash-core/src/main/java/org/logstash/config/ir/graph/PlainEdge.java
logstash-core/src/main/java/org/logstash/config/ir/graph/PluginVertex.java
logstash-core/src/main/java/org/logstash/config/ir/graph/Vertex.java
logstash-core/src/main/java/org/logstash/config/ir/imperative/IfStatement.java
logstash-core/src/test/java/org/logstash/config/ir/IRHelpers.java
logstash-core/src/test/java/org/logstash/config/ir/graph/GraphTest.java
logstash-core/src/test/java/org/logstash/config/ir/imperative/ImperativeToGraphtest.java
rakelib/compile.rake

This PR does three things:
1. It adds hooks for pipeline lifecycle events (and adds an LIR object to all pipeline objects)
2. It fixes a bug where sometimes if statements would create invalid graph objects during their construction.
3. It also fixes a bug where configs using strings as regex rvalues would break. Ex: `[foo] =~ "bar"`

Pipeline register hooks + hash fix

---

logstash-core/lib/logstash/pipeline.rb

Fixes #6688 
This basically catched plugins initialization exceptions in `start_workers` and cleanup/stop/close any partially initialized plugins before bubbling up exception. This way `start_workers` should not exit and leave any partially initialized pipeline, it either succeed or cleanup state upon error.
- move `start_inputs` at the end of the `start_workers` sequence
- catch exceptions in input, output and filter plugins registration and close those that were registered
- catch exception in `start_inputs` and call `shutdown_workers` before re-raising
- start input threads only once all inputs plugins have been successfully registered

cleanup partially initialized pipeline

---

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/main/java/org/logstash/common/io/AbstractByteBufferPageIO.java
logstash-core/src/main/java/org/logstash/common/io/MmapPageIO.java
logstash-core/src/test/java/org/logstash/common/io/ByteBufferPageIOTest.java

This fixes a problem found while testing #6691 where recovery would fail with 
```
[2017-02-13T10:37:56,505][WARN ][org.logstash.ackedqueue.Queue] recovered head data page 1 is different than checkpoint, using recovered page information.
```
- The problem is in the head page positioning after recovery. The head needs to be update only after a fully valid recovered element. 
- Added tests for this case. Tests are failing without fix and passing with fix.
- I also left some debug traces used to diagnose the problem. 
- I also added an explicit fsync on close.

fix bad head positioning on recovery & tests

---

tools/logstash-docgen/templates/plugin-doc.asciidoc.erb

Remove the default column in the plugin doc page to give space to the sidebar

---

logstash-core/lib/logstash/queue_factory.rb

fixes #6732 
simply pass the namespaced queue path to the memory acked queue constructor so that exclusive lock places the `.lock` file in that dir.

use queue path in memory acked queue to namespace .lock file

---

bin/lock
logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/runner.rb
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/src/main/java/org/logstash/FileLockFactory.java
logstash-core/src/main/java/org/logstash/LockException.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/FileLockFactoryTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/stress/Concurent.java
rakelib/artifacts.rake

This backports the 5.3 PQ exclusive locking into 5.2, which also required backporting:
- pipeline reloading fixes to avoid double opened pipelines
- pipeline workers start to properly clean state upon errors
- all related specs

PQ exclusive locking backport in 5.2

---

logstash-core/src/main/java/org/logstash/common/io/MmapPageIO.java
logstash-core/src/test/java/org/logstash/common/io/FileCheckpointIOTest.java

Fixes #6646 
Under Windows, sometimes PQ throws and exception when trying to purge a page with something like:
```
java.nio.file.FileSystemException: page.0: The process cannot access the file
because it is being used by another process.
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
at java.nio.file.Files.delete(Files.java:1126)
at org.logstash.common.io.MmapPageIO.purge(MmapPageIO.java:99)
at …
```

memory mapped buffer cleaner

---

.gitignore
build.gradle
logstash-core-event-java/build.gradle
logstash-core-event-java/settings.gradle
logstash-core-queue-jruby/build.gradle
logstash-core-queue-jruby/settings.gradle
rakelib/compile.rake
settings.gradle

Currently, there are three separate gradle projects in this repository.
These gradle files unify them so that one can call `gradle build` from the parent `logstash` directory and build all of the projects together. This also allows one to run `gradle idea` to generate an intellij `.ipr` project for more seamless development between the three projects.

unify gradle projects

---

docs/static/plugin-manager.asciidoc

Fixing this in 5.0 (we've already fixed this in the other 5.x branches, so it doesn't require a review). 
We can close PR #6267 because this fixes the problem.

Fix incorrect command syntax

---

logstash-core-queue-jruby/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java
logstash-core-queue-jruby/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueMemoryExtLibrary.java
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/util/wrapped_acked_queue.rb
logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb
logstash-core/spec/logstash/pipeline_pq_file_spec.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/spec/logstash/util/wrapped_synchronous_queue_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java

This is in [WIP] state because the metrics on empty batch/queue need to be assessed - The creation of an empty final batch to handle the final flush upon shutdown which did not contain metrics yielded some errors so I added metrics to empty batches. There was originally a check for empty batches read to not start metrics but I believe this was bug because if this empty batch got used in a flush signal (slim chance) it would have crashed because of unstarted metrics for that batch. 
Core tests/specs are passing locally.
This PR adds support for a queue drain option. It relates to issue #6085 and it is necessary for the upcoming BatchedQueue implementation. The goal is to be able to signal logstash to drain the queue before exiting on a normal shutdown.  It is necessary for in-memory …

[WIP] queue drain option support

---

docs/static/logging.asciidoc

Hello,
I was reading through the documentation and found a missing g from Logstash! Also, my first contribution ever to open source!
Thank you for a great product by the way

Typo in logging.asciidoc

---

docs/index.asciidoc
docs/static/breaking-changes.asciidoc
docs/static/releasenotes.asciidoc

We usually avoid breaking changes in point releases, but unfortunately, there is one in PQ -- which is a beta feature, so breaking change is OK. Second, there is a breaking change in a plugin (again, this is something we avoid at best). Hence, I added breaking changes section per release.

Release notes and breaking changes for 5.3

---

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

The `Queue.write()` method need a new `seqNum` and this operation was done outside the synchronized section so concurrent writes could result in being assigned invalid `seqNum` since it is not volatile. 
This solves #6829 using @jordansissel provided reproduction spec (https://gist.github.com/jordansissel/518667ab4bd2df9d41244427917c9160)
This is an "early" PR and would like to review all reported problems in #6829 to make sure it fixes all. Also I would like to include a spec/test for this, should we include @jordansissel one as it is quite long to run?

fix seqNum concurrency issue in Queue.write

---

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java

On o.l.ackedqueue.Queue#close() method the
lock.unlock() call might not execute, leaving
a mutex locked.
This change ensure that lock.unlock() is always
execute by moving its call to the sibling
try/catch's finally block.

Queue: fix unlock mutex on close()

---

logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb
rakelib/test.rake

fixes #6917 
includes PQ threaded/concurrent stress tests in the default specs.
introduces two new test rake tasks:
- `rake test:core-fast` 
- `rake test:core-slow`
where `rake test:core` actually calls `rake test:core-slow` which runs all specs (excepted those excluded in dev-utils).
`rake test:core-fast` excludes the specs tagged with `:stress_test => true`. 
This PR does not clean the current more-or-less deprecated tagging and configured in dev-utils.

acked queue concurrent stress spec

---

logstash-core/lib/logstash/agent.rb

Fixes #6575 
All `Pipeline.new` exceptions are reported by the `Agent` as 
```
[logstash.agent           ] Cannot load an invalid configuration
```
but Pipeline instantiation exceptions are not only configuration errors. 
Since this is now fixed in master for 6.0 with the `Agent` refactor in #6632, In 5.x I do not think we should yak shave the `Pipeline.new` exception handling and simply print a more generic message instead of `Cannot load an invalid configuration`. 
This PR simply rephrase the exception message to `Cannot create pipeline`. 
In the case of a Queue exception the output will look like this:
```
[2017-04-25T16:29:27,878][ERROR][logstash.pipeline        ] Logstash failed to create queue {"exception"=>"SOME QUEUE ERROR", …
```

rephrase pipeline creation error message

---

docs/index.asciidoc
docs/static/filebeat-modules.asciidoc
docs/static/filebeat_modules/apache2/access/filebeat.yml
docs/static/filebeat_modules/apache2/error/filebeat.yml
docs/static/filebeat_modules/mysql/error/filebeat.yml
docs/static/filebeat_modules/mysql/slowlog/filebeat.yml
docs/static/filebeat_modules/nginx/access/filebeat.yml
docs/static/filebeat_modules/nginx/error/filebeat.yml
docs/static/filebeat_modules/system/auth/filebeat.yml
docs/static/filebeat_modules/system/syslog/filebeat.yml

@suyograo Here's what I'm planning to say about Filebeat modules in the 5.3 Logstash docs. I have the LS configs commented out, but will add them after you merge your PR. Let me know if the messaging here is in line with what you expect for 5.3. 
IMO the manual configuration experience would be a lot easier if Filebeat allowed Logstash as an output. Instead of generating an error and closing, Filebeat should generate a warning when Logstash is configured as the output.  Of course, if  `-setup` is specified and ES is not configured as the output, Filebeat should generate an error.
Right now, FBM users who want to use Logstash instead of ingest node miss out on the benefit that FBMs provide for setting up the Filebeat config automatically. The only real benefit of using Filebeat modules at …

Add docs about configuring LS for use with Filebeat modules

---

docs/index.asciidoc

Changes the release state to "released" for 5.4 (required for the installation instructions to show in the docs).

Set release-state to released

---

docs/static/docker.asciidoc

- Document the new mechanism for mapping environment variables to setttings in `logstash.yml` when using the Docker image
- Add comments about Docker base image and source repo
Applies to 5.4.

Add docs for settings via env vars on Docker

---

logstash-core/lib/logstash/bootstrap_check/default_config.rb
logstash-core/lib/logstash/config/source/local.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/config/source/local_spec.rb
qa/integration/specs/01_logstash_bin_smoke_spec.rb

makes -e and -f mutually exclusive, which also eliminates concatenation between the two
this is part of the changes described in https://github.com/elastic/logstash/issues/6926

make e and f flags mutually exclusive

---

logstash-core/lib/logstash/config/source/local.rb
logstash-core/spec/logstash/config/source/local_spec.rb

this was the behaviour in 1.x and 2.x and 5.x introduced auto completion of path.config
this PR goes back to 1.x and 2.x behaviour.
This is part of a list of changes described in https://github.com/elastic/logstash/issues/6926

only auto complete config.string

---

config/logstash.yml
docs/static/settings-file.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/execution_context.rb
logstash-core/lib/logstash/inputs/base.rb
logstash-core/lib/logstash/outputs/base.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/plugin.rb
logstash-core/lib/logstash/util/dead_letter_queue_manager.rb
logstash-core/spec/logstash/agent/converge_spec.rb
logstash-core/spec/logstash/execution_context_spec.rb
logstash-core/spec/logstash/inputs/base_spec.rb
logstash-core/spec/logstash/output_delegator_spec.rb
logstash-core/spec/logstash/outputs/base_spec.rb
logstash-core/spec/logstash/pipeline_dlq_commit_spec.rb
logstash-core/spec/logstash/runner_spec.rb
logstash-core/spec/support/shared_contexts.rb
logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java
logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/test/java/org/logstash/common/DeadLetterQueueFactoryTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java

DeadLetterQueueFactory is a static class that keeps
a static collection of DeadLetterQueueWriteManagers per
pipeline that has plugins requesting to use it.
DeadLetterQueueFactory.close is run on pipeline shutdown to
safely close and remove the open writer in the pipeline

Introduce a DeadLetterQueueFactory

---

qa/integration/specs/01_logstash_bin_smoke_spec.rb
qa/integration/specs/env_variables_config_spec.rb
qa/integration/specs/monitoring_api_spec.rb
qa/integration/specs/settings_spec.rb

increase the number of tries and rely more on `@logstash_service.wait_for_logstash`

make integration specs a bit more resilient

---

.travis.yml

We have decided to increase the verbosity of the test on travis to help debug some weird errors in the suite
backport of #7064

Use `--format documentation` when tests are running on travis

---

logstash-core/lib/logstash/modules/cli_parser.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/modules/cli_parser_spec.rb

Add tests for the `LogStash::Modules:CLIParser` class in `cli_parser.rb`
Fix a typo in `cli_parser.rb` (`uparsed` vs `unparsed`)
Fix a bad variable name found by testing in `cli_parser.rb` and update the error message accordingly in `en.yml`

Fixes and tests

---

logstash-core/logstash-core.gemspec

With the merge of https://github.com/elastic/logstash/pull/7284, Logstash
now depends on elasticsearch client to setup modules.
To be usable under jruby we also need to depends on manticore, this
problem is only show when try to use the logstash-core gem directly and
not in the Logstash project since it bundle the elasticsearch output
with the manticore dependency.

Add missing dependency on manticore

---

tools/ingest-converter/src/main/java/org/logstash/ingest/JsUtil.java
tools/ingest-converter/src/main/java/org/logstash/ingest/Set.java
tools/ingest-converter/src/main/resources/ingest-grok.js
tools/ingest-converter/src/main/resources/ingest-pipeline.js
tools/ingest-converter/src/main/resources/ingest-set.js
tools/ingest-converter/src/main/resources/ingest-shared.js
tools/ingest-converter/src/test/java/org/logstash/ingest/PipelineTest.java
tools/ingest-converter/src/test/java/org/logstash/ingest/SetTest.java
tools/ingest-converter/src/test/resources/org/logstash/ingest/ingestComplexCase3.json
tools/ingest-converter/src/test/resources/org/logstash/ingest/ingestComplexCase4.json
tools/ingest-converter/src/test/resources/org/logstash/ingest/ingestDotsInSetField.json
tools/ingest-converter/src/test/resources/org/logstash/ingest/ingestSet.json
tools/ingest-converter/src/test/resources/org/logstash/ingest/ingestSetNumber.json
tools/ingest-converter/src/test/resources/org/logstash/ingest/logstashComplexCase3.conf
tools/ingest-converter/src/test/resources/org/logstash/ingest/logstashComplexCase4.conf
tools/ingest-converter/src/test/resources/org/logstash/ingest/logstashDotsInSetField.conf
tools/ingest-converter/src/test/resources/org/logstash/ingest/logstashSet.conf
tools/ingest-converter/src/test/resources/org/logstash/ingest/logstashSetNumber.conf

Ingest `on_failure` processor allows to define a new sub-piplene when a failure
happens in the current processor. Logstash does not have an on_failure but this can
be emulated using the tag and conditional.
Also added a set processor converter which is typically used in `on_failure`.

Handle ingest on_failure processor

---

config/pipelines.yml

The `config.string` option was not correctly closed with a double quote

Small typo in the pipelines.yml

---

Gemfile.jruby-1.9.lock.release
logstash-core/logstash-core.gemspec
rakelib/vendor.rake

this solves https://github.com/elastic/logstash/issues/7477
Also fixes https://github.com/elastic/logstash/issues/5507: from the jruby changelog "Backport securerandom" https://github.com/jruby/jruby/pull/4149"
This should be merged to 5.x 5.5 and 5.4

upgrade jruby to 1.7.27

---

config/logstash.yml
docs/static/configuration.asciidoc
docs/static/releasenotes.asciidoc
docs/static/settings-file.asciidoc
logstash-core/lib/logstash/compiler.rb
logstash-core/lib/logstash/compiler/lscl.rb
logstash-core/lib/logstash/compiler/treetop_monkeypatches.rb
logstash-core/lib/logstash/config/config_ast.rb
logstash-core/lib/logstash/config/string_escape.rb
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/compiler/compiler_spec.rb
logstash-core/spec/logstash/config/config_ast_spec.rb
logstash-core/spec/logstash/config/string_escape_spec.rb

This PR adds a new boolean setting `config.support_escapes` which defaults to false (the historical behavior). When set to true, the following escapes are handled:
* backslash doublequote -> doublequote
* backslash quote -> quote
* backslash n -> newline (ascii 10)
* backslash r -> carriage return (ascii 13)
* backslash backslash -> backslash
* backslash t -> tab (ascii 9)
This will solve #1645.

Add setting to enable string escaping in Logstash pipeline config

---

logstash-core/spec/logstash/legacy_ruby_timestamp_spec.rb
logstash-core/spec/logstash/timestamp_spec.rb

Fix Timestamp.new(now) != now, out by 0.999999 milliseconds
Fixes #7463

Fix for: Unreliable logstash-core/spec/logstash/timestamp_spec under JRuby 9000

---

logstash-core/logstash-core.gemspec

There was a Errno::ENOENT while loading logstash-core.gemspec: 
No such file or directory - /var/lib/jenkins/workspace/elastic+logstash+2.x+multijob-intake/logstash-core/gemspec_jars.rb
Fixes #7506

Previous commit incorrectly added a dependency on gradle building gemspec_jars.rb 

---

lib/pluginmanager/templates/codec-plugin/logstash-codec-example.gemspec.erb
lib/pluginmanager/templates/filter-plugin/logstash-filter-example.gemspec.erb
lib/pluginmanager/templates/input-plugin/logstash-input-example.gemspec.erb
lib/pluginmanager/templates/output-plugin/logstash-output-example.gemspec.erb

The current value issues a warning when building: 
```
WARNING:  license value 'Apache License (2.0)' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean 'Apache-2.0'?
```

Update default license

---

logstash-core/lib/logstash/modules/util.rb
logstash-core/lib/logstash/runner.rb

Now in LogStash::Modules::Util, this allows it to be used where modules
are defined in external gems like logastash-x-pack.

Move the global method `register_local_modules` to a Ruby Module

---

logstash-core/lib/logstash/modules/util.rb
logstash-core/lib/logstash/runner.rb

Now in LogStash::Modules::Util, this allows it to be used where modules
are defined in external gems like logastash-x-pack.

Move the global method `register_local_modules` to a Ruby Module (#7555)

---

logstash-core/lib/logstash/modules/logstash_config.rb
logstash-core/lib/logstash/settings.rb
logstash-core/spec/logstash/modules/logstash_config_spec.rb
logstash-core/spec/logstash/modules/scaffold_spec.rb
logstash-core/spec/logstash/settings/splittable_string_array_spec.rb

This commits add the following new features:
Allow users to use the internal settings classes to have better handling
over the primitives values that a user can use in the modules templates,
by default we are using a `NullableString` which is the more flexible
type.
This change open the way to have more strict validation on the module
templates and will allow us to preprocess configuration to retrieve the
list of the settings and their settings types.
We also add a new type of settings called `SplittableStringArray`, this
class is a subclass or `ArrayCoercible` but target module CLI
configuration. It will take the following form `-M
"arcsight.var.input.hosts=127.0.0.1:3333,192.168.1.23:9999"` and
transform it into a ruby array of string.
We can also add alias of settings values in the …

Add more options for the modules templates

---

ci/ci_test.bat

this requires jruby to be unpacked into ~~`C:\Program Files\jruby\src\jruby-<version>`~~ %JRUBYSRCDIR%
The actual version will be read from the `.ruby-version` file.
fixes #7553 
REMINDER: for backporting this to 5.x it's necessary to include the .ruby-version file in the PR too, since the 5.x and 5.6.0 branches do not contain this file

add ci_test.bat file so windows can run tests like other OS do

---

logstash-core/spec/logstash/legacy_ruby_event_spec.rb
logstash-core/src/main/java/org/logstash/Event.java
logstash-core/src/test/java/org/logstash/EventTest.java

Fixes #6756 
The problem is the missing `@timestamp` handling which produces this exception when `Event.toString()` is called.
```
org.logstash.bivalues.StringBiValue cannot be cast to java.lang.String
```
Will also followup with an issue to review the `Event.getTimestamp()` behaviour in #7613
To manually repro this bug
```sh
bin/logstash -e 'filter{mutate{rename => {"@timestamp" => "foo"}}} output{stdout{}}'
```

broken Event.toString() when missing @timestamp

---

README.md
docs/index-shared1.asciidoc
docs/static/releasenotes.asciidoc
logstash-core-plugin-api/logstash-core-plugin-api.gemspec
logstash-core/lib/logstash-core/version.rb
logstash-core/lib/logstash/modules/kibana_client.rb
logstash-core/lib/logstash/modules/kibana_settings.rb
logstash-core/lib/logstash/version.rb
versions.yml

Following ES's lead : elastic/elasticsearch@c084542
Find/replace for all instances of alpha3 to beta1 (since alpha3 was never released).

VERSION BUMP: 6.0.0-alpha3 -> 6.0.0-beta1

---

config/logstash.yml
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/util/dead_letter_queue_manager.rb
logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java
logstash-core/src/test/java/org/logstash/common/DeadLetterQueueFactoryTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java

Add setting for dead_letter_queue.max_bytes to allow a user
to set the maximum possible size of a dead letter queue on disk.
Resolves #7633
Fixes #7638
Fixes #7652

Cherry-Pick from 5.x: Add dead_letter_queue.max_bytes setting

---

logstash-core/lib/logstash/elasticsearch_client.rb
logstash-core/lib/logstash/modules/kibana_client.rb
logstash-core/lib/logstash/modules/logstash_config.rb
logstash-core/spec/logstash/modules/scaffold_spec.rb

This allows modules to connect to kibana and elasticsearch through SSL.
NOTE: this PR also changes the setting `var.output.elasticsearch.user` to `var.output.elasticsearch.username` so both username settings are consistent (and also consistent with monitoring/management username settings)

implement ssl in modules

---

Gemfile.jruby-1.9.lock.release

This should fix the issue where DLQ input 1.0.4 was missing the jars.

Update lock file with fixed DLQ input

---

logstash-core/src/main/java/org/logstash/instrument/metrics/AbstractMetric.java
logstash-core/src/main/java/org/logstash/instrument/metrics/Metric.java

Outside code should be able to access these properties of metrics, namely in x-pack.

adds key and namespace getters to Java Metric classes

---

rakelib/artifacts.rake

When a file is listed as a configuration file the package manager will ask the user about what to do about local modifications when the package is upgraded and the file has changed upstream. If not listed as a configuration file any local modifications will silently be lost.

rakelib: List log4j2.properties as a config file in RPM/Deb

---

rakelib/artifacts.rake

When a file is listed as a configuration file the package manager
will ask the user about what to do about local modifications when
the package is upgraded and the file has changed upstream. If not
listed as a configuration file any local modifications will silently
be lost.

rakelib: List log4j2.properties as a config file in RPM/Deb (#7688)

---

logstash-core/lib/logstash/elasticsearch_client.rb
logstash-core/lib/logstash/modules/logstash_config.rb

an x-pack-logstash PR will be reliant on the csv_string method.

Correct ES_client to only split strings + add csv_string(array) method

---

bin/cpdump

fixes #7695
At some point the queue classes namespace was changed but `cpdump` was not updated. 
Manually tested locally using (after running logstash with PQ enabled)
```sh
bin/cpdump main/checkpoint.head
```

reference correct class path

---

logstash-core/lib/logstash/util/wrapped_acked_queue.rb
logstash-core/spec/logstash/util/wrapped_acked_queue_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueMemoryExtLibrary.java
logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

This is a proposal to fix the second item of #7568 which aim at an acceptable fix to satisfy `ReadClient#empty?` without changing the semantic of `Queue.isFullyAcked()`
The current implementation of `isFullyAcked()` for both the `Queue` and `Page` classes does not work to satisfy the `ReadClient#empty?` condition, see #7570.

fix empty queue condition for queue shutdown drain

---

logstash-core/lib/logstash/config/modules_common.rb
logstash-core/lib/logstash/config/source/modules.rb
logstash-core/lib/logstash/modules/settings_merger.rb
logstash-core/locales/en.yml

As discussed between Suyog, Alvin Joao and Guy.
- In 5.x if the user specifies more than one module in either YML or CLI, detect and error ASAP.
- Allow the user to specify YML module settings and then override them with the CLI.
After PR merge to master and 5.x change the MODULES_MAX_PIPELINES constant to a reasonable value for multiple pipelines - 16, 32, 64 ????

Merge CLI into YML settings + limit user specified modules to 1 for 5.x

---

logstash-core/src/main/java/org/logstash/ackedqueue/Batch.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

fixes #7809 
This fixes the condition upon opening the queue, a page file of zero byte with a fully acked checkpoint would generate this exception:
```
Logstash failed to create queue {"exception"=>"Page file size 0 different to configured page capacity xxx
```
I also added a test to reproduce that problem. Without this fix the test fails with the above exception and passes with this PR.
This condition should not prevent LS from starting since fully acked page are simply purged in the open process. Here we just do the purge before checking on the file size. 
Now, the condition which leads to having a zero byte page file is still unknown. 
followup issue #7811 to DRY the code. This seems to be an acceptable fix for now.

handle fully acked zero byte page at queue open

---

logstash-core/lib/logstash/config/modules_common.rb
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/runner_spec.rb

Without the `--setup` flag, the index template for elasticsearch, and the index-pattern, saved searches, visualizations, and dashboards for Kibana will not be published.
fixes #7959

Add --setup phase for modules

---

docs/static/deploying.asciidoc

A separate pull request moved the "Logstash and Security" content from the X-Pack Reference (https://www.elastic.co/guide/en/x-pack/master/logstash.html) to the Logstash Reference.
This pull request updates a link to that content

[DOCS] Update link to Logstash security

---

logstash-core-plugin-api/logstash-core-plugin-api.gemspec
logstash-core/lib/logstash-core/version.rb
logstash-core/lib/logstash/version.rb
versions.yml

bump version to 6.0.0-beta2
this will also fix the currently failing x-pack build on 6.0 branch.
tested locally:
`rake test:core` on logstash
`clean check integTest` on x-pack

bump to 6.0.0-beta2

---

logstash-core/lib/logstash/modules/kibana_config.rb

PR #7451 introduced a way to set metrics max bucket settign in Kibana. This ain't good because
it can destabilize Kibana and ES as well

Remove metrics max bucket setting

---

lib/pluginmanager/gemfile.rb

fixes #7768
Under Windows, the read string encoding was set to `Windows-1252` which was breaking the `DSL` `instance_eval` on that string.
It is probably worth exploring if that encoding problem is actually a JRuby specific bug and report it if it is.  The fact that there is no exception when doing the`instance_eval` but instead the object becomes invalid is certainly a bug worth digging and reporting. 
tested on OSX for regression and Windows where previously the plugins installation would fail and now correctly works.

force UTF-8 encoding for gem file reading

---

logstash-core/spec/logstash/legacy_ruby_event_spec.rb

fixes #8028 
This expectation was using `be_within(1)`. It seems unlikely it should be beyond 1s interval but it happened so increasing to `2` seems even more unlikely to happen and still provide a correct assessment IMO. 
This is not the ideal fix but since the `Event` class is ultimately a Java class, it is somewhat more difficult to use mocks for time in the Ruby specs. I think this is an acceptable modification to avoid potential future rare failures with this.

relax time gap constrain in expectation

---

lib/pluginmanager/utils/downloader.rb
logstash-core/lib/logstash/config/source/local.rb
logstash-core/lib/logstash/pipeline_action/stop.rb
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/api/modules/node_stats_spec.rb
logstash-core/spec/logstash/config/source/local_spec.rb
logstash-core/spec/logstash/pipeline_action/create_spec.rb
logstash-core/spec/logstash/pipeline_action/reload_spec.rb
logstash-core/spec/logstash/pipeline_dlq_commit_spec.rb
logstash-core/spec/logstash/settings/writable_directory_spec.rb
spec/unit/plugin_manager/pack_fetch_strategy/uri_spec.rb
spec/unit/plugin_manager/prepare_offline_pack_spec.rb
spec/unit/plugin_manager/utils/downloader_spec.rb

Modifications to have a green build on Windows.
Tested for successful `rake test:core` locally on Windows Server 2012 and on OSX. 
These are mostly spec fixes. 
The only non-spec significant change which should prevent potential problems on all platforms is in `logstash-core/lib/logstash/pipeline_action/stop.rb` where after issuing a pipeline shutdown, we were not waiting on the pipeline thread to complete.

Windows build fixes

---

logstash-core/logstash-core.gemspec
rakelib/fetch.rake
rakelib/vendor.rake
versions.yml

Add support for an optional `jruby-runtime:` key in `versions.yml`. 
If `jruby-runtime:` is specified it will override the **runtime** JRuby version installed in `vendor/jruby`. 
Note that the `jruby:` key will still be used to reference the compile-time *provided* jars in `build.gradle`. 
This is useful to be able to use a JRuby pre-relase/snapshot version for the builds & specs or measure performance. 
This PR also sets the `jruby-runtime:` to  9.1.13.0-SNAPSHOT so we can start testing against the fix  for the JRuby JIT problem #8006

add option for different jruby runtime version

---

rakelib/z_rubycheck.rake

per discussion with @ph - I tested that this code is not needed anymore. everything builds and all tests passes without it on Windows.

remove unsued windows code

---

logstash-core/src/main/java/org/logstash/RubyUtil.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedBatchExtLibrary.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueMemoryExtLibrary.java

solves #7759 
This PR correctly provides the Java stack trace in the rethrown Ruby exception.
For example, this is an example of the stack trace we were getting for a Java exception within the Queue open method, note that the stack trace stopped at Queue open Ruby method from the JRuby extension wrapper:
```
Logstash failed to create queue {:pipeline_id=>"main", "exception"=>"Checkpoint checksum mismatch, expected: 1228426236, actual: 1228426236", "backtrace"=>["org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java:145:in `open'", "/Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:41:in `with_queue'", "/Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:30:in `create_file_based'", …
```

bubble up java stack trace from wrapped exception

---

bin/logstash.bat
bin/setup.bat
logstash-core/lib/logstash/runner.rb

fixes #8126 
This is mostly a rewrite of the windows launching batch files, inspired by the ES windows launch batch files.
The initial goal was to add support for the `config/jvm.options` in its default location or in `--path.settings` if specified on the command line. 
Here are the differences from the linux launching logic:
- existing `JAVA_OPTS` env var is now ignored, [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L37-L42)
- `JAVA_TOOL_OPTIONS` env var is cleared,  [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L31-L35)
- now only `LS_JAVA_OPTS` …

windows launch scripts

---

bin/rspec.bat

windows `bin/rspect.bat` should pickup `jvm.options` just like when launching `bin/logstash` so that the specs run in the same JVM environment.
This has already been back-introduced in 5.5 in #8354
I would like to merge this to master, 6.x & 6.0.

pick jvm.options for rspec.bat

---

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

BUG: Purging headpages needs to reflect in the currentByteSize of the Queue

---

Gemfile.jruby-1.9.lock.release

This was accidentally removed in #8390 , this bumps it correctly.
You will want to diff it against 03287b4ee63874f94b997a199097ccff2144d848 (right before #8390) to see what changed.

Correct the lockfile for 5.6.3

---

logstash-core/src/main/java/org/logstash/ObjectMappers.java
logstash-core/src/test/java/org/logstash/EventTest.java

Revert the custom serializers that are not required anymore with Jackson version 2.8+ now that #7615 #8373  is in. 
Relates to #8379, #8205, #8131
Fixes #8387

revert to Jackson BigInteger and BigDecimal serialization

---

docs/static/breaking-changes.asciidoc
docs/static/releasenotes.asciidoc

This pull request adds links to the corresponding X-Pack information from the Logstash "Breaking Changes" and "Release Notes" sections.

Added links to X-Pack release notes

---

ci/unit_tests.bat

Try to assign a drive letter to the `WORKSPACE` env var to shorten the current path to avoid hitting the 260 chars limits in Windows.
Strategy:
- first loop through the list of `subst` drives to see if `WORKSPACE` was already assigned to a drive and reuse it
- otherwise try to `subst` the first free drive letter to `WORKSPACE`
The idea is to avoid just assigning new drive letters blindly since this is a long-running server. The number of used drive letters will top at the number of unique `WORKSPACE` paths which shoud avoid depletion. 
Relates to #7767

[WIP] dynamically assign drive letter to WORKSPACE env var

---

docs/static/releasenotes.asciidoc

Relnotes for 5.6.0 and 5.6.1 were accidentally deleted. Adding them back in.
These have already been reviewed, so I am adding without review.

Add relnotes for 5.6.0 and 5.6.1

---

rakelib/test.rake

fix for the `rake test:plugins` command to run all installed plugins specs. 
This command is really useful to test core changes on all installed plugins in one go.

fix the test:plugins execution

---

logstash-core/lib/logstash/modules/kibana_client.rb
logstash-core/lib/logstash/modules/settings_merger.rb
logstash-core/lib/logstash/util/cloud_setting_id.rb
logstash-core/spec/logstash/modules/kibana_client_spec.rb
logstash-core/spec/logstash/modules/settings_merger_spec.rb
logstash-core/spec/logstash/settings/modules_spec.rb
logstash-core/spec/logstash/util/cloud_setting_id_spec.rb

This is a blocker for the combination of x-pack feature config management and or monitoring when using cloud id or specifying host(s) urls in logstash.yml
I did get 2 wait timeout converge_spec.rb failures on my laptop - only when running rake test:core though, the individual spec file passed.
Jenkins tests pass.

Fix 'https' scheme in ES hosts setting when set from Cloud ID.

---

docs/static/introduction.asciidoc

these plugins were removed from the plugin documentation so the links here must be removed too
see failure in https://elasticsearch-ci.elastic.co/job/elastic+docs+master+build/7926/console

fix broken links in docs

---

docs/index-shared1.asciidoc
docs/index-shared2.asciidoc
docs/index-shared3.asciidoc

Adds missing edit URL links and fixes the edit URL so that the links point to the correct version for the static docs. (For the plugin docs, the edit URL always points to master.)
The old way of sending users to master for all fixes made it easier for us but confusing to users, especially for content that was refactored between releases.  This way, the user will always find the expected content at the URL, and the burden is on us to cherry-pick edits into master.

Fix edit url links

---

docs/static/monitoring-apis.asciidoc

This PR moves the "Monitoring APIs" section of the Logstash Reference documentation so that it is no longer nested under "Monitoring Logstash".  Instead, those two sections are now peers.

[DOCS] Moved Monitoring APIs in Logstash Reference

---

docs/static/docker.asciidoc
docs/static/getting-started-with-logstash.asciidoc

* Document Docker image "flavours"
* Fix up section hierarchy
* Capture Docker config default
* Warn about default "masking" when replacing logstash.yml

Update Docker docs for v6

---

logstash-core/src/main/java/org/logstash/ackedqueue/io/AbstractByteBufferPageIO.java
logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/io/MmapPageIOTest.java

This PR fixes #7581 
It removes the strict check for a configured page capacity to necessarily equal the the capacity of an existing page file. The problem with this is that a page capacity change in the configuration while there is an existing non-empty queue would prevent logstash from starting. 
It seems reasonable that someone would want to tweak a page capacity for new pages moving forward while old pages would still exist at their original capacity until all purged.

support page capacity change on existing queue

---

docs/index-shared1.asciidoc
docs/static/breaking-changes.asciidoc
docs/static/releasenotes.asciidoc

This has a variety of changes. I rolled up more breaking plugin changes in here.
I also rolled up all 6.0 release notes and diffed them with 5.6.3. I removed release notes
that only dealt with improvements across 6.0 pre-release versions

Bump docs + release notes for 6.0.0 GA

---

logstash-core/src/main/java/org/logstash/common/LsQueueUtils.java

Followup of #8632 and related to #8633 I think the decreasing timeout is unnecessary WRT to the eager reading & batch maximization strategy. We agreed that the idea of the timeout is that it should be applied per blocking read so fixing a global & fixed timeout *deadline* here should not be required. Also this avoids a call to `System.nanoTime()` in the read loop.
Let me know if I am missing something here @original-brownbear ?

replace decreasing timeout with fixed timeout

---

logstash-core/src/main/java/org/logstash/ackedqueue/Batch.java
logstash-core/src/main/java/org/logstash/ackedqueue/HeadPage.java
logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

This is a cleanup to move the page read deserialization out of the Page and into the Batch. Now Page classes do not have knowledge of the Batch which happen at the Queue level. 
Part of #8674 for the PQ Batch size maximization

[CLEANUP] refactor page read deserialization out of the page into batch

---

logstash-core/src/main/java/org/logstash/ackedqueue/Page.java

`<` broke the javadoc generation and thus broke the build 😿

[MINOR] bad bad javadoc

---

logstash-core/lib/logstash/compiler/lscl.rb
logstash-core/spec/logstash/compiler/compiler_spec.rb
logstash-core/src/main/java/org/logstash/config/ir/expression/ValueExpression.java

(backport of elastic/logstash#8750 to 6.0 for next patch release)
A regression was introduced in the new LSCL/LIR implementation in 6.0, in
which configurations that had nested hashes produced valid treetop-ASTs that
could not produce a valid LIR; the values in an `LSCL::AST::Hash` were
assumed to implement `ValueExpression`, but `LSCL::AST::Hash#expr` produced
an unwrapped `RubyHash`.
By making `LSCL::AST::Hash#expr` emit a `ValueExpression` _representing_ a
`RubyHash`, and relying on the existing code that deals with `ValueExpression`
appropriately, we can re-enable deeply-nested hashes in configs.

LSCL/LIR: enable plugins to have nested hash directives (backport to 6.0)

---

Gemfile.jruby-2.3.lock.release

includes elasticsearch output plugin fix https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/712

bump es output dependency to 9.0.2

---

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java

Fixes #8769 
This removes the insertion of dummy pages in the `tailPages` collection for in-between fully acked pages in the `open()` on an existing queue. This is completely unnecessary since the `ack()` method actually removes these pages in the normal process. 
Added a new tests to harness this edge case. Also validated manually with existing queue data which surfaced this problem.
This is pretty severe and should be prioritized for merging into 6.0.1 and downto 5.6.

fix queue open bug for fully acked in-between pages plus new test

---

logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java

This is basically a cleanup of `Queue` `open()` and and DRYing of `addIO()` and `addPage()`. 
The logic is easier to follow in the `open()` method. It is a **long** method but the steps are relatively straight forward plus I added comments for the tricky part.

cleanup & DRY Queue open(), addIO() and addPage()

---

logstash-core/benchmarks/src/main/java/org/logstash/benchmark/QueueRWBenchmark.java
logstash-core/src/main/java/org/logstash/ackedqueue/Batch.java
logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/main/java/org/logstash/ackedqueue/io/LongVector.java
logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/io/LongVectorTest.java
logstash-core/src/test/java/org/logstash/stress/Concurrent.java

This PR is based and depends on #8690 
💥  NOTE that this PR also includes Javadoc cleanups, particularly in the `Queue` class.
Work in this PR is about doing batch size maximization on read per #8674. The main logic is located in the `Queue` `_readPageBatch()` method. 
A simple test for this has been added in `QueueTest` `maximizeBatch()`. 
TODOs:
I write this simple output plugin to show output batch sizes on *stdout*:
```
require "logstash/outputs/base"
require "logstash/namespace"
class LogStash::Outputs::BatchStatsOut < LogStash::Outputs::Base
config_name "batch_stats_out"
def register; end # must be overriden
def multi_receive_encoded(encoded)
$stdout.puts(encoded.size)
end
end
```
- I noticed that batches were **not** always maximized using the default `pipeline.batch.delay: 5`. …

maximize PQ read batch size

---

config/logstash.yml
config/pipelines.yml
docs/static/persistent-queues.asciidoc
docs/static/running-logstash-command-line.asciidoc
docs/static/settings-file.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/util/wrapped_acked_queue.rb
logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb
logstash-core/spec/logstash/queue_factory_spec.rb

Fixes #8707 
Relates to #8702, #8674 
Change the default values for `pipeline.batch.delay` from `5ms` to `50ms` and `queue.page_capacity` from `250mb` to `64mb`.
Also fixes documentation & comments inconsistencies.

change batch delay to 50ms and page size to 64mb

---

docs/static/releasenotes.asciidoc

This list was compiled from https://github.com/elastic/logstash/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Av6.1.0+is%3Aclosed+ and the plugin's changelogs bumped since 6.0.0/6.0.1

Add release notes for 6.1.0

---

bin/pqcheck

`bin/pqcheck` new tool to verify a PQ dir files structure. 
This is based on the original one-liner script @jordansissel produced as part of a diagnostic thread.
This tool can take dir path as parameter or use the default `data/queue/main` and will look into each checkpoint files and print it content. Il also prints the corresponding page file size and prints if it is fully acked or not. 
example output:
```
$ bin/pqcheck
checking queue dir: data/queue/main
checkpoint.head, FA, 67108864, {:version=>1, :page=>141, :firstUnackedPage=>141, :firstUnackedSeq=>17075891, :minSeq=>16974637, :elementCount=>101254, :crc32=>3485132876}
checkpoint.1, FA, NA, {:version=>0, :page=>0, :firstUnackedPage=>0, :firstUnackedSeq=>0, :minSeq=>0, :elementCount=>0, :crc32=>0}
```

added new PQ checking tool bin/pqcheck

---

Gemfile.jruby-2.3.lock.release

This is the result of running `rake artifact:tar`, and copying the resulting `Gemfile.jruby-1.9.lock` to overwrite the existing `Gemfile.jruby-1.9.lock.release`.

bump for 6.1.2 release

---

Gemfile.jruby-1.9.lock.release
Gemfile.template
NOTICE.TXT
logstash-core/lib/logstash-core_jars.rb

This is the result of running `rake artifact:tar`, and copying the resulting `Gemfile.jruby-1.9.lock` to overwrite the existing `Gemfile.jruby-1.9.lock.release`.

bump gems for 5.6.6 release

---

bin/logstash.bat
bin/rspec.bat
bin/setup.bat
logstash-core/lib/logstash/runner.rb

Solves #8901 
- Windows startup scripts did not correctly handled paths with spaces.
- The logger configuration was buggy by using a useless `join` and not escaping the path as as URI.

correctly handle paths with spaces

---

docs/index-shared1.asciidoc

This PR upgrades the "branch" attribute value in the new 6.2 branch.

[DOCS] Updated version to 6.2

---

bin/logstash.lib.sh
bin/ruby
build.gradle

This is reboot of #8914 and it introduces the following changes:
- Allow overriding the `GEM_HOME` and `GEM_PATH` in `logstash.lib.sh`. This is useful when launching the integration tests through `bin/ruby` to make sure `GEM_HOME` and `GEM_PATH` will not be inherited by any local shell initialization.
- Adds a few missing clean paths
- Directly invoke `gem` and `bundler` in the integration tests setups.
- Invoke the integration specs through `bin/ruby` and not `vendor/jruby/bin/jruby` to avoid any `GEM_HOME` and `GEM_PATH` problem

fix integration tests build

---

logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/bootstrap_check/persisted_queue_config_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/main/java/org/logstash/common/FsUtil.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/common/FsUtilTest.java

This is a reboot of #6998 originally by @original-brownbear.
Fixes #6552 
* Implemented free disk space check in Java
* Added JUnit test for the Java file system logic
* Added new bootstrap check to checks against the max of (`queue.max_bytes` and `queue.page_capacity`)
* `Queue.open()` will throw an exception if there is not enough disk space to allocate  `queue.max_bytes`  minus existing pages sizes.

verify available disk space for PQ.

---

logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java
logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
logstash-core/src/test/java/org/logstash/ackedqueue/QueueTestHelpers.java

Relates to #8936
This removes `currentByteSize` handling in PQ which computes queue size based on page capacity times the number of live pages. 
Per #6508, #6518 and #7010 we have settled to using the sum of the actual persisted bytes (head position) for each sparsely allocated page of the queue to compute the queue disk size. There is no reason to keep this `currentByteSize` around. 
**IMPORTANT** This PR introduces an inefficiency in the `isFull()` method which now needs to call `getPersistedByteSize()`  instead of using the `volatile long currentByteSize`. Calling `getPersistedByteSize()` is clearly less efficient because it needs to iterate through all the tail pages to sum the head position but it is now a "correct" implementation. I suggest we move forward with this change here and …

remove currentByteSize

---

docs/static/deploying.asciidoc

The information about monitoring Logstash has moved from the X-Pack Reference to the Logstash Reference.  This PR fixes a link to that content.

[DOCS] Fixed broken link to monitoring info

---

README.md
docs/index.asciidoc
docs/index.open.asciidoc

This PR updates the index.asciidoc files such that both versions of the Logstash Reference (with and without X-Pack pages) are built from the same repository (elastic/logstash).  It also updates the README with info about building the documentation.

[DOCS] Build Logstash Reference from logstash repo

---

docs/static/keystore.asciidoc

Cleaned up the keystore description based on review comments from @jordansissel.
Moved the description of how LS keystore compares to ES to appear later in the document because it's not the main idea here and shouldn't be covered so early in the topic.

Resolve review comments

---

docs/static/life-of-an-event.asciidoc

Please ignore. This change is for testing purposes and will be reverted shortly.

Introduce file conflict

---

logstash-core/src/main/java/org/logstash/common/FsUtil.java

Fixes #9123 
On Windows, SUBST'ed drives report `0L` as `getFreeSpace()`. 
API doc says:
```
The number of unallocated bytes on the partition or 0L if the abstract pathname does not name a partition [...]
```
There is no straightforward fix for this and it seems a fix is included in Java 9. 
One alternative is to launch and parse a DIR command and look at the reported free space.
This is a temporary fix to get the CI tests going which relies on SUBST'ed drives to manage long paths.

Windows freespace on SUBST'ed drives

---

bin/logstash.bat

Do not run logstash when checking version on windows
Fixes #5526

make -V/--version fast on Windows

---

Gemfile.jruby-1.9.lock.release

Supersedes https://github.com/elastic/logstash/pull/9175 as that one had a bad Gemfile.

bump gems for 5.6.9

---

Gemfile.jruby-2.3.lock.release

Supersedes https://github.com/elastic/logstash/pull/9174 as that one had a bad Gemfile.

bump gems for 6.2.3

---

README.md

* Use `cat .ruby-version` in the rvm install command, so that it doesn't
get out of date when changing `.ruby-version`
* Added small clarification for running rspec

Small changes to the build instructions

---

logstash-core/lib/logstash/filters/base.rb
logstash-core/spec/logstash/filters/base_spec.rb

See Issue #7859 
PR #6177 Introduced a change where the value of the `tags` field is always converted to an Array even if no filters added or removed tags at all.
Users want a mechanism to have a tags field that comes from, say JSON, rename it early, allow other filters to add tags (grok), use logic on the tags to process failures and then rename their external tags field back to tags just before the outputs.

Fix: Tags collision with user-defined tags and built-in tags

---

logstash-core/src/main/java/org/logstash/execution/inputs/Stdin.java

I missed this commented-out code in my previous PR.

Clean up stdin plugin to use config, remove unused variables

---

docs/index-shared3.asciidoc
docs/static/ls-ls-config.asciidoc
docs/static/pipeline-pipeline-config.asciidoc

Implement doc for pipeline-to-pipeline communication.
@andrewvc  Fantastic job on the doc structure and content (#9225)
Included in this PR:
- Updated index file to pull the new doc into the ref guide
- Tweaked asciidoc to get a clean build (pipeline-pipeline-config.asciidoc)
- Minor edits, change to active voice, etc. to the main topic, (pipeline-pipeline-config.asciidoc)
- Updated LS-to-LS Config topic to cross-reference new content

Doc for pipeline-to-pipeline communication

---

docs/static/arcsight-module.asciidoc

This PR removes X-Pack installation text from the Logstash Arcsight Module documentation(https://www.elastic.co/guide/en/logstash/master/arcsight-module.html), since that step is no longer required.

[DOCS] Removes X-Pack installation info

---

x-pack/docs/en/management/centralized-pipelines.asciidoc

This PR fixes a broken link to the License Management page.

[DOCS] Fixes broken link

---

docs/static/configuration.asciidoc

Single kv hashes look like Ruby hashes, and people get confused.
Let's make the example more explicit.

Give an example of a single line Hash.

---

x-pack/docs/en/index.asciidoc

This PR enables the "edit" links at the top of all the pages in the x-pack folder.

[DOCS] Enables editing links for X-Pack pages

---

logstash-core/lib/logstash/config/pipeline_config.rb
logstash-core/spec/logstash/config/pipeline_config_spec.rb
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/lib/monitoring/inputs/metrics/state_event_factory.rb

Resolves #9470.
Each pipeline can have a single origin (file, x-pack centralized management, string, etc.). This origin is internally represented via a `protocol` field in pipeline metadata.
This PR makes it so that a pipeline's protocol is reported to X-Pack Monitoring as part of `logstash_state` documents.
1. Setup X-Pack Monitoring for Logstash.
2. Start one pipeline via the `-e` option.
3. Start another pipeline via the `-f` option.
4. Setup X-Pack Management for Logstash.
5. Create and deploy a third pipeline from the Logstash Centralized Management UI.
6. Query the Logstash Monitoring indices with the query below:
```
GET .monitoring-logstash-*/_search?q=type:logstash_state&filter_path=hits.hits._source.logstash_state.pipeline.id,hits.hits._source.logstash_state.pipeline.protocol …
```

[X-Pack Monitoring] Report pipeline protocol

---

logstash-core/lib/logstash/config/pipeline_config.rb
logstash-core/spec/logstash/config/pipeline_config_spec.rb
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/lib/monitoring/inputs/metrics/state_event_factory.rb

This is because the backport of #9516 from `master` to `6.x` broke unit tests on `6.x`.

Revert #9516 ([X-Pack Monitoring] Report pipeline protocol) from 6.x

---

docs/index-shared3.asciidoc
x-pack/docs/en/management/configuring-centralized-pipelines.asciidoc
x-pack/docs/en/monitoring/configuring-logstash.asciidoc
x-pack/docs/en/security/logstash.asciidoc
x-pack/docs/en/setup/setting-up-xpack.asciidoc

Related to https://github.com/elastic/logstash/issues/9596
This PR removes the "Set Up X-Pack" section from the highest level of the Kibana User Guide's table of contents.  Instead, that content is moved under the existing "Setting Up and Running Logstash" and "Configuring Logstash" sections.  For example:
and 
This is a superficial change, but sets the stage for ultimately moving those source files into the logstash/docs folder. In the long run, I expect the "Set up X-Pack" page to be removed when its contents are merged into the appropriate Logstash page.
P.S.  These pages are just about one-time setup of these features, but you could definitely make a case for putting some of them under appropriate "Managing Logstash", "Monitoring Logstash", and "Securing Logstash" sections instead. …

[DOCS] Moves X-Pack configuration pages in table of contents

---

docs/static/management/centralized-pipelines.asciidoc

Resolves https://github.com/elastic/logstash/issues/9475.
Starting with 6.3.0, users of the Logstash Central Management UI have the ability to see — as read-only — non-centrally-managed Logstash pipelines in the UI as well. This requires users to have the `monitoring_user` role assigned to them. This PR adds a note about this to our docs.

Encourage central management UI users to add the `monitoring_user` role as well

---

Gemfile.jruby-2.3.lock.release

From #9816:
> Since the release of `jruby-openssl` `v0.10.1` on 2018-06-22, invocations of `bin/logstash-plugin update` have pulled in an updated `jruby-openssl` dependency, but have failed to update the dependency entry in the lockfile.
> 
> Subsequent invocations of `bin/logstash-plugin` produce an obscure error message, which isn't helpful since our `bin/bundle` executable doesn't replicate the `bundle exec` functionality and users don't necessarily have `bundle` on their paths:
> 
> ~~~
> Gem::LoadError: You have already activated jruby-openssl 0.10.1, but your Gemfile requires jruby-> openssl 0.10.0. Prepending `bundle exec` to your command may solve this.
> ~~~
This patch updates the `jruby-openssl` gem in our release template lockfile to `0.10.1`, the latest available as of this …

fix: jruby-openssl conflict after running bin/logstash-plugin update

---

docs/static/docker.asciidoc

This PR removes the alternative "docker pull" command so that the instructions are focused on the default path.
cc'ing @jarpy, who added this information in https://github.com/elastic/logstash/pull/8587
Related to https://github.com/elastic/kibana/pull/20624 and https://github.com/elastic/elasticsearch/pull/31934

[DOCS] Removes alternative docker pull example

---

docs/static/shutdown.asciidoc

I was linking to this page from a Getting Started tutorial in the Stack Overview and I noticed that it didn't mention that you could stop Logstash by using Ctrl-C. 
This PR therefore adds Ctrl-C to the list of methods in shutdown.asciidoc.  It also clarifies that the first options apply only when you're running Logstash as a service.

[DOCS] Clarify methods for stopping Logstash

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/event_spec.rb
logstash-core/src/main/java/org/logstash/FieldReference.java
logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
logstash-core/src/test/java/org/logstash/FieldReferenceTest.java

The existing `FieldReference#parse(CharSequence)` is susceptible to crashes on specific pathological inputs (elastic/logstash#9524), and expands ambiguous input in surprising ways (identified in elastic/logstash#9531).
In elastic/logstash#9531 (which _replaced_ the existing parser with a strict-mode parser that does not expand ambiguous-syntax inputs), we determined that there was too much risk of breaking real-world pipelines that have ambiguous syntax, and agreed to:
>  - in 6.x, illegal syntax falls back to _existing_ behaviour (modified only to prevent crashes) with a memoized log message; user can opt into strict field-reference parsing with a command-line flag or configuration option.
>  - in 7.x, field-reference parsing is strict by default
*[EDIT: strict-mode now raises runtime …

FieldReference: strict mode

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml
logstash-core/spec/logstash/event_spec.rb
logstash-core/src/main/java/org/logstash/FieldReference.java
logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
logstash-core/src/test/java/org/logstash/FieldReferenceTest.java

This is a backport to 6.x of a chain of commits from elastic/logstash#9543 (which covers the transition from the current `FieldReference` parser to something more strict); as discussed in the full transition PR, this backport to 6.x:
- fixes inputs that currently crash Logstash by preemptively moving these specific inputs to strict-mode
- warns when strict-mode would expand a field reference differently than the legacy-mode, and includes the ability for a user to opt-in to strict-mode in advance of their migration to 7.x where strict-mode will be the default:
> ## 6.x
> 
> For 6.x, the first _four_ commits in this PR can safely be backported.
> 
> We add an opt-in strict-mode parser, and implement a compat-mode parser that will always produce the same path and key as if we were using the …

FieldReference: add opt-in strict-mode for 6.x

---

rakelib/version.rake

the `docs/` index file has been renamed from `index-shared1.asciidoc` to `index.asciidoc` in 6.3+ 
This should be merged in 6.x and master.

docs index file renamed to docs/index.asciidoc

---

logstash-core/src/main/java/org/logstash/FieldReference.java
logstash-core/src/test/java/org/logstash/FieldReferenceTest.java

Backport of #8823 for 5.6 (1f7116a461d2df51284e4e6e445e241704b1c5b2)
Attempting to get this in before the 2018-08-14 feature freeze for the 5.6.11 release.

fix ArrayIndexOutOfBoundsException from empty String field reference

---

logstash-core/src/main/java/org/logstash/common/io/RecordIOWriter.java

this is currently causing ci failures:
```
11:48:05 :logstash-core:javadoc/opt/logstash/logstash-core/src/main/java/org/logstash/common/io/RecordIOWriter.java:39: error: unmappable character for encoding ASCII
11:48:05  * | ??? magic number (4bytes) --|
11:48:05      ^
11:48:05 /opt/logstash/logstash-core/src/main/java/org/logstash/common/io/RecordIOWriter.java:39: error: unmappable character for encoding ASCII
11:48:05  * | ??? magic number (4bytes) --|
11:48:05       ^
```
example of failed job: https://logstash-ci.elastic.co/job/elastic+logstash+5.6+multijob--ruby-unit-tests/lastBuild/console

replace non ascii character failing javadoc compilation

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/FilterDelegatorExt.java
logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
logstash-core/src/main/java/org/logstash/instrument/metrics/AbstractNamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NullNamespacedMetricExt.java

This fixes a metrics concurrency issue when using multiple pipeline, the node stats events metrics would sometimes be initialized concurrently upon initializing the multiple pipelines and the wrong events metrics instance would be used in the pipeline to increment the global node stats `events.filtered` and `events.out` metrics.
The witnessed behaviour is that querying for `_node/stats` would result in the `events` field to contain something similar to :
```
{
"in": 10023,
"filtered": 0,
"out": 0,
...
}
```
But in fact all events are being filtered and output correctly and the per-pipelines metrics shows the correct counts.
To reproduce, create a `config/logstash.yml` similar to this:
```
- pipeline.id: '1'
pipeline.workers: 1
pipeline.batch.size: 1
config.string: "input { generator {} } …
```

avoid race condition when initializing events and pipelines metrics

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/FilterDelegatorExt.java
logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
logstash-core/src/main/java/org/logstash/instrument/metrics/AbstractNamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NullNamespacedMetricExt.java

This is a backport of #9950 on the 6.4 branch for inclusion in 6.4.1
There were no conflict in creating this backport.

[6.4 backport of #9950] avoid race condition when initializing events and pipelines metrics

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/FilterDelegatorExt.java
logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
logstash-core/src/main/java/org/logstash/instrument/metrics/AbstractNamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NamespacedMetricExt.java
logstash-core/src/main/java/org/logstash/instrument/metrics/NullNamespacedMetricExt.java

This is a backport of #9950 on the 6.x branch for inclusion in 6.5
There were no conflict in creating this backport.

[6.x backport of #9950] avoid race condition when initializing events and pipelines metrics

---

docs/static/releasenotes.asciidoc

Started with #9960 as base, fixed formatting, and made minor wording changes.

Fix formatting for Kafka release note for 6.4

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java

Fixes #9978 
The [`BasePipeline`/`JavaBasePipeline`  is used to validate configurations](https://github.com/elastic/logstash/blob/234add03dc5bcd1f8f673862457022f74b39caf0/logstash-core/lib/logstash/pipeline_action/reload.rb#L32-L36) prior to [initializing the actual `Pipeline`/`JavaPipeline`](https://github.com/elastic/logstash/blob/234add03dc5bcd1f8f673862457022f74b39caf0/logstash-core/lib/logstash/pipeline_action/create.rb#L35-L39) and the validation process should not open the queue.
The queue opening code which was part of the `AbstractPipeline` constructor is now move out into an `open_queue` method which is now called only from the `Pipeline`/`JavaPipeline` constructor. 
To reproduce the problem:
- enable PQ `queue.type: persisted`
- enable reloading `config.reload.automatic: true` …

move queue opening bits from constructor to open_queue method

---

logstash-core/src/main/java/org/logstash/Valuefier.java

logstash-plugins/logstash-input-rabbitmq#112 Fixes most cases of MissingConverterException when receiving data with the rabbitmq input plugin.
This is adding support for Byte, Short and (most importantly) Date. But to decrease verbosity I use the functionality in fallbackConvert to decode subclasses of the given classes.
See method ValueReader.readFieldValue in java package amqp-client for which types can appear over AMQP (except that LongString is changed to String by March Hare).

Fixes MissingConverterException when receiving data with the rabbitmq input plugin

---

logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb
logstash-core/spec/logstash/instrument/periodic_poller/cgroup_spec.rb

* Make cgroups more robust and provide the override similar to ES
and Kibana
This should go out as soon as possible and backport to 5.6
* refactor as per comments

Backport: Make cgroups more robust and provide the override similar to ES (#9999)

---

logstash-core/spec/logstash/agent_spec.rb
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java

Fixes #9979 
Run all `Agent` specs as `shared_examples` and run them all using both the memory and persisted queue. This is important to make sure we don't introduce regressions in the queue/pipeline initialization sequence which typically surfaces in agent tests and in particular around config reloading.
Also includes a trivial fix of a useless `throws IOException` declaration which I stumbled upon when verifying this PR.
I tested by re-introducing the bug in #9985 and making sure this patch did catch the problem. 
**Note to reviewer:** the diff is large because the whole file needed re-indentation, but the actual changes are rather simple - In the "Diff setting"  use:  ✅ Hide whitespace changes.

run Agent specs using both memory and persisted queue

---

logstash-core/spec/logstash/agent_spec.rb
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java

Unclean backport - trivial adjustements.
Use  "Diff setting"  ✅ Hide whitespace changes.

[6.x backport of #10009] run Agent specs using both memory and persisted queue

---

Gemfile.jruby-2.3.lock.release

this is related to https://github.com/elastic/logstash/issues/10017
version 3.2.3 updates the regular expressions and introduces many changes in how strings are parsed, which may be too disruptive for the typical user.

Skip 3.2.3 user agent filter

---

docs/index.asciidoc

Related to https://github.com/elastic/docs/issues/382, https://github.com/elastic/kibana/pull/22939,  and https://github.com/elastic/elasticsearch/pull/33588
This PR moves the "Breaking Changes" section nearer the "Release Notes" section, to synchronize the location of this information across the library.

[DOCS] Synchronize location of Breaking Changes

---

config/logstash.yml
docs/static/arcsight-module.asciidoc
logstash-core/lib/logstash/modules/logstash_config.rb
x-pack/lib/x-pack/logstash_registry.rb
x-pack/modules/arcsight/configuration/logstash/arcsight.conf.erb
x-pack/modules/arcsight/lib/arcsight_module_config_helper.rb
x-pack/spec/modules/arcsight/arcsight_module_config_helper_spec.rb
x-pack/spec/modules/arcsight/yaml/event_broker_with_security.yml
x-pack/spec/modules/arcsight/yaml/smart_connector_with_ssl.yml

I added the ssl for the smart connector (tcp) and ssl and sasl for the
event broker.
Needs verification on a current stack.

Add SC and EB input TLS support for the Logstash ArcSight module

---

Gemfile.jruby-2.3.lock.release

Computed from 6.4.2's lock file and allowing minor version bumps with: `rake bump_versions[6.4.2,minor]` 
<details>
<summary>Click here to see the diff compared to 6.4.2</summary>
```diff
diff --git a/Gemfile.jruby-2.3.lock.release b/Gemfile.jruby-2.3.lock.release
index b72be0db6..8555a56d4 100644
--- a/Gemfile.jruby-2.3.lock.release
+++ b/Gemfile.jruby-2.3.lock.release
@@ -1,7 +1,7 @@
PATH
remote: ./logstash-core
specs:
-    logstash-core (6.4.2-java)
+    logstash-core (6.5.0-java)
chronic_duration (= 0.10.6)
clamp (~> 0.6.5)
concurrent-ruby (~> 1.0, >= 1.0.5)
@@ -26,7 +26,7 @@ PATH
remote: ./logstash-core-plugin-api
specs:
logstash-core-plugin-api (2.1.16-java)
-      logstash-core (= 6.4.2)
+      logstash-core (= 6.5.0)
GEM
remote: https://rubygems.org/
@@ -38,13 +38,13 @@ GEM …
```

updated lock file for 6.5.0

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb

This solves a concurrency problem when using multiple pipelines. The Ruby pipeline configuration compilation code is not thread safe and uses a shared state in the `LogsStash::Config::AST` module. This compilation is done in the pipeline constructor which gets called simultaneously in multiple threads when using multiple pipelines resulting in sometimes corrupted generated pipeline code and eventually resulting exceptions such as
- `undefined method 'multi_filter' for nil:NilClass` ... `in block in filter_func'"`
- `undefined method 'call' for nil:NilClass` ... `in block in filter_func'"`
I validated this fix by first inspecting the compiled code of each pipeline when using multiple pipelines  all using the same config. I noticed that the number of `@generated_objects[:cond_func_XX] = …

synchronize ruby pipeline initialization to fix concurrency bug

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/spec/logstash/pipeline_action/create_spec.rb
logstash-core/spec/logstash/pipeline_action/reload_spec.rb

clean  backport of #10113 on 6.5

[6.5 clean backport of #10113] synchronize ruby pipeline initialization to fix concurrency bug

---

config/log4j2.properties
logstash-core/lib/logstash/runner.rb
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/lib/license_checker/license_manager.rb
x-pack/lib/license_checker/license_reader.rb
x-pack/lib/license_checker/x_pack_info.rb
x-pack/lib/modules/module_license_checker.rb
x-pack/lib/monitoring/inputs/metrics.rb
x-pack/lib/monitoring/internal_pipeline_source.rb
x-pack/lib/monitoring/monitoring.rb
x-pack/spec/license_checker/license_reader_spec.rb
x-pack/spec/modules/module_license_checker_spec.rb
x-pack/spec/monitoring/inputs/metrics_spec.rb
x-pack/spec/monitoring/internal_pipeline_source_spec.rb

currently the monitoring pipeline starts up even if the elasticsearch monitoring cluster isn't available and license can't be checked.
Starting the monitoring pipeline w/o ES generates a large amount of error messages that confuses users so this PR delays the pipeline generation by moving the license checking from the metrics input plugin to the InternalPipelineSource that provides the monitoring pipeline.
This pipeline source then waits from the license checker to give an OK about the license and executes a pipeline reload on the agent.
The xpack information object was modified to distinguish between a failed license check (if ES is unavailable) vs an unknown license (ES response doesn't contain the license information).
Logging messages have been reduced to avoid fatigue.

start monitoring pipeline after valid license

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/spec/logstash/pipeline_action/create_spec.rb
logstash-core/spec/logstash/pipeline_action/reload_spec.rb

clean backport of #10113 on 6.4
fixed related specs.

[6.4 clean backport of #10113] synchronize ruby pipeline initialization to fix concurrency bug

---

logstash-core/logstash-core.gemspec

[6.x clean backport of #10148] upgrade rack to version 1.6.11 

---

logstash-core/logstash-core.gemspec

[6.4 clean backport of #10148] upgrade rack to version 1.6.11

---

Gemfile.jruby-2.3.lock.release

this should address CI failures such as https://logstash-ci.elastic.co/job/elastic+logstash+6.4+multijob-legacy/3/console

update lock file for the 6.4 branch

---

logstash-core/logstash-core.gemspec

6.5 clean backport of #10148
**do not merge until 6.5.1 is out**

[6.5 clean backport of #10148] upgrade rack to version 1.6.11

---

build.gradle
lib/bootstrap/bundler.rb
lib/pluginmanager/bundler/logstash_injector.rb
qa/integration/specs/cli/remove_spec.rb
rakelib/artifacts.rake
rakelib/dependency.rake
rakelib/vendor.rake
spec/unit/bootstrap/bundler_spec.rb
spec/unit/license_spec.rb

This reverts commit ab20b40e478ce818cecef5720a4875bdbb099e8a.
Due to failing tests like https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob--ruby-unit-tests/86/

Revert "remove forced dependency on old bundler (#9395)"

---

Gemfile.template
build.gradle
lib/bootstrap/bundler.rb
lib/pluginmanager/bundler/logstash_injector.rb
lib/pluginmanager/bundler/logstash_uninstall.rb
qa/integration/specs/cli/remove_spec.rb
rakelib/artifacts.rake
rakelib/dependency.rake
rakelib/vendor.rake
spec/unit/bootstrap/bundler_spec.rb
spec/unit/license_spec.rb

- Re-adds previously-reverted work to unpin bundler #9395
- Updates plugin management's helpers to use Bundler 1.17.x-compatible APIs
- Resolves dependency conflicts

JRuby 9.2 bundler shenanigans

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb

@guyboertje recently ran through me a bug he discovered in the workers thread naming which was introduced in #9973. I decided to submit this PR because I'd like to get this fix in before I go ahead and rebase and make progress with #9991.
The problem is that the call to `Util.set_thread_name` was made outside the newly created thread context and the `Util.set_thread_name` method set the passed name to the current thread context. 
The problem is that none of the worker threads were given a name and the pipeline thread name was set to the last worker thread name. 
This problem was present on both Ruby and Java pipelines and for both cases using the hot thread API to gather the thread names this is the before/after:
```
curl -XGET 'localhost:9600/_node/hot_threads?human=true&ignore_idle_threa …
```

properly set thread name in thread context

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb

[6.x clean backport of #10269] properly set thread name in thread context

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb

[6.4 clean backport of #10269]

[6.4 clean backport of #10269] properly set thread name in thread context

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb

[6.5 clean backport of #10269]

[6.5 clean backport of #10269] properly set thread name in thread context

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb

[6.6 clean backport of #10269]

[6.6 clean backport of #10269] properly set thread name in thread context

---

Gemfile.jruby-2.3.lock.release

This is the result of running `jruby ./tools/release/bump_plugin_versions.rb 6.6 6.5.4 minor` on the 6.6 branch

Update lock file for 6.6

---

Gemfile.jruby-2.3.lock.release

this plugin was bumped to 1.0.0 to avoid clashing with the 0.5.4 versions of the rest filter of which this plugin was based on.

Bump http filter to 1.0.0

---

logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/lib/logstash/pipeline_action/stop.rb

Fixes #10330 
While investigating #10330 I noticed that there were actual bugs in the pipeline actions implementation around the usage the pipelines `ConcurrentHashMap` `compute` method. I refactored and cleaned all actions.
In particular the reload method was very problematic and I believe the cause of the thread context errors; 
https://github.com/elastic/logstash/blob/ce80262d02fd55d9a948f7e02aa65f226464ea08/logstash-core/lib/logstash/pipeline_action/reload.rb#L52-L61
This code calls `compute` on the `pipelines` `ConcurrentHashMap` and the block passed to `compute` should return a new value or nil to update the `ConcurrentHashMap` accordingly but here the block was actually calling `return` which actually returned from the method and was probably the cause of the frame errors. I …

correctly handle pipeline actions

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/spec/logstash/pipeline_action/create_spec.rb
logstash-core/spec/logstash/pipeline_action/reload_spec.rb

[6.6 clean backport of #10113] synchronize ruby pipeline initialization to fix concurrency bug (#10113)

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/spec/logstash/pipeline_action/create_spec.rb
logstash-core/spec/logstash/pipeline_action/reload_spec.rb

[6.x clean backport of #10113] synchronize ruby pipeline initialization to fix concurrency bug (#10113)

---

logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/lib/logstash/pipeline_action/stop.rb

[6.x clean backport of #10331] correctly handle pipeline actions

---

build.gradle
logstash-core/build.gradle
versions.yml

Updates the following Java dependencies:
* snakeyaml: 1.17 -> 1.23
* log4j: 2.9.1 -> 2.11.1
* jackson: 2.9.5 -> 2.9.8
* janino: 3.0.8 -> 3.0.11
* javassist: 3.22.0-GA -> 3.24.0-GA
* json-unit: 1.9.0 -> 2.3.0
* assertj-core: 3.8.0 -> 3.11.1

Update java dependencies

---

logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/lib/logstash/pipeline_action/stop.rb

6.6 clean backport of #10331
**Merge AFTER 6.6.0 release.**

[6.6 clean backport of #10331] correctly handle pipeline actions

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
logstash-core/lib/logstash/instrument/periodic_pollers.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/pipeline_action/base.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/lib/logstash/pipeline_action/stop.rb
logstash-core/lib/logstash/pipelines_registry.rb
logstash-core/lib/logstash/state_resolver.rb
logstash-core/spec/logstash/agent/converge_spec.rb
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/pipeline_action/create_spec.rb
logstash-core/spec/logstash/pipeline_action/reload_spec.rb
logstash-core/spec/logstash/pipeline_action/stop_spec.rb
logstash-core/spec/logstash/pipelines_registry_spec.rb
logstash-core/spec/logstash/state_resolver_spec.rb
logstash-core/spec/support/matchers.rb
logstash-core/spec/support/shared_contexts.rb
logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
x-pack/lib/monitoring/inputs/metrics.rb
x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
x-pack/spec/monitoring/inputs/metrics_spec.rb
x-pack/spec/support/helpers.rb

Fixes #10345
This PR introduces a new `PipelinesRegistry` class to encapsulate the old `Agent` `@pipelines` `ConcurrentHashMap`.  
One of the problem was the termination condition of the agent which was checking if all pipelines threads were **not** `Threah#alive?` and assumed it could exit. The problem is that the reload action did shutdown a pipeline to later on restart a new one, and in that period, all pipelines thread could have been seen as **not** `Threah#alive?`. This PR solves this condition by taking into account the reloading sequence as a period where a pipeline is not considered dead regardless if shutdown part of the reload accured or not.
-  new `PipelinesRegistry` is an abstraction for the registration a management of the pipeline states which replaces the old `@pipelines` …

fix agent silent exit upon pipelines reloading

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
logstash-core/lib/logstash/instrument/periodic_pollers.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/pipeline_action/base.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb
logstash-core/lib/logstash/pipeline_action/stop.rb
logstash-core/lib/logstash/pipelines_registry.rb
logstash-core/lib/logstash/state_resolver.rb
logstash-core/spec/logstash/agent/converge_spec.rb
logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/pipeline_action/create_spec.rb
logstash-core/spec/logstash/pipeline_action/reload_spec.rb
logstash-core/spec/logstash/pipeline_action/stop_spec.rb
logstash-core/spec/logstash/pipelines_registry_spec.rb
logstash-core/spec/logstash/state_resolver_spec.rb
logstash-core/spec/support/matchers.rb
logstash-core/spec/support/shared_contexts.rb
logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
x-pack/lib/monitoring/inputs/metrics.rb
x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
x-pack/spec/monitoring/inputs/metrics_spec.rb
x-pack/spec/support/helpers.rb

[6.5 clean backport of #10346] fix agent silent exit upon pipelines reloading

---

logstash-core/src/test/java/org/logstash/TimestampTest.java

targets: `master`, `6.x` (same targets as Java Plugin API that introduced these tests).
In Java 8, `java.lang.Instant#now()` used the system clock, which only had millisecond-level precision, but [starting with Java 9](https://bugs.openjdk.java.net/browse/JDK-8068730), the system clock is much more precise.
Since we create our `org.logstash.Timestamp` with `long epoch_milliseconds`, it cannot represent a time more precisely than milliseconds.
Ensure that the output of `Timestamp#usec` is rounded before comparing it with milliseconds, in order to avoid asserting greater precision than we can create.

tests: support more-precise clocks in Java 11

---

logstash-core/spec/logstash/runner_spec.rb

Fixes a scenario where one or more specs that attempt to connect to an unmocked kibana on localhost, _AFTER_ a spec or spec group has been run that configures Webmock to intercept all connections, fails because the request has not been mocked.
Resolves #10274 
This is a cherry-pick of a commit that has already landed in `master` and `6.x`. Merge target is `6.6`.

QA: prevent webmock from intercepting http calls to localhost

---

Gemfile.template

this prevents childprocess 1.x to be installed as it contains native
extensions which we don't need and create troubles in CI

bump fpm dependency

---

logstash-core/lib/logstash/runner.rb
x-pack/lib/config_management/extension.rb
x-pack/lib/monitoring/monitoring.rb

This PR adds on top of #10380/#10391 to support the older config names and add deprecation warning.

 support old config options and add deprecation warnings

---

Gemfile.template

childprocess 1.x causes builds to fail like https://logstash-ci.elastic.co/job/elastic+logstash+7.x+multijob-unix-compatibility/os=centos&&immutable/1/console

pin childprocess to 0.9

---

Gemfile.jruby-2.5.lock.release
Gemfile.template

childprocess 1.x causes builds to fail like https://logstash-ci.elastic.co/job/elastic+logstash+7.x+multijob-unix-compatibility/os=centos&&immutable/1/console
backport of #10410

pin childprocess to 0.9 (backport to 7.0)

---

Gemfile.jruby-2.5.lock.release

this bump makes `clones` parameter of the clone filter a required field

bump clone filter in lock file

---

docs/index.asciidoc

The field references deep dive topic uses the `role="exclude"` attribute so that the topic appears and can be linked in the LS Ref, but doesn't appear in the main TOC.  The `exclude`attribute was carrying forward for all subsequent topics in the `configuration.asciidoc` file. 
This PR moves the include statement for `field-reference.asciidoc` so that the `role="exclude"` attribute will not affect other topics. 
Targets: `master` `7.x` `7.0` `6.7` `6.6` `6.5` `6.4`

[Doc] Reorder files in index to expose topics

---

docs/index.asciidoc

The `role=exclude` setting in the field-reference.asciidoc file is hiding more entries than intended.  This PR moves the include statement for field-reference.asciidoc below all other content in Configuring Logstash. 
Continuation of #10429

[Docs]  Move field-ref include below xpack content

---

docs/static/fb-ls-kafka-example.asciidoc
docs/static/filebeat-modules.asciidoc

Adds docs that show how to load ingest pipelines and use them with Filebeat modules. I think some users may want to define their own configurations in LS, so I've kept the configuration examples (and tested them). 
Sorry...no link to a review copy of the built docs because firebase is not playing nice. :-/
This PR addresses a few open issues in the Beats docs. I've added the fix to the existing LS docs since we already have a section there about using Filebeat modules with Logstash.
https://github.com/elastic/beats/issues/9037
https://github.com/elastic/beats/issues/6280

Improve docs about using Filebeat modules with Logstash

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb

Following up on @yaauie config AST thread safety #10415 and deferred refactoring per #10406.
this removes the Agent exclusive lock put in place to serialize initialization of the Pipeline object to prevent a thread safety issue in the config AST which is not needed anymore per above.

remove exclusive lock for Ruby pipeline initialization

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb

[7.0 clean backport of #10431] remove exclusive lock for Ruby pipeline initialization

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/pipeline_action/create.rb
logstash-core/lib/logstash/pipeline_action/reload.rb

[7.x clean backport of #10431] remove exclusive lock for Ruby pipeline initialization

---

docs/static/releasenotes.asciidoc

Adds CVE-2019-7612 and link to Security Issues to 6.6.1 release notes

Update to 6.6.1 release notes

---

docs/static/releasenotes.asciidoc

Adds CVE-2019-7612 and link to Security Issues to 5.6.15 release notes

Update to 5.6.15 release notes

---

docs/index.asciidoc

Currently the docs reference to the old alpha2 version, for example here
https://www.elastic.co/guide/en/logstash/7.0/docker.html

Fix version in docs, fixes also docker image url

---

logstash-core/lib/logstash/agent.rb

Clean backport of #10537 for 6.7
There are several scenarios in which we can trigger concurrent convergence in
the agent, resulting in two or more threads working to perform interleaved and
potentially conflicting or overlapping pipeline actions. Notably, our trap on
`SIGHUP` will be resolved in its own thread, so if we are sent `SIGHUP` while
in the process of converging, the second in-flight convergence may get its
starting state before, during, or after the effects of the first convergence.
By mutually excluding execution of the convergence cycle, we eliminate the
class of bugs in which one convergence acquires actions that cannot succeed due
to the prior success of actions given to the other convergence.

Clean Backport of #10537 for 6.7

---

build.gradle

This problems solves the RC1 stack build failure where the downloadEs task is not called but the download url setup was done at the top level and was failing with missing version information.

move download setup code inside the downloadEs task

---

build.gradle

[7.0 clean backport of #10547] move download setup code inside the downloadEs task

---

build.gradle

- This sets dummy parameters for the downloadEs task when the required version is not found in the versions API which is necessary because the a task parameters are always evaluated regardless if the task is executed or not.
- The downloadEs doFirst will check if the required version was not found and throw and exception but this will happen only if the task is actually executed.

correctly handle unexecuted downloadEs task

---

build.gradle

[7.x clean backport of #10547] move download setup code inside the downloadEs task

---

docs/static/releasenotes.asciidoc

release notes written from `git log v7.0.0-beta1..v7.0.0-rc1`

Release notes for 7.0.0-rc1

---

logstash-core/lib/logstash/settings.rb
logstash-core/spec/logstash/settings/deprecated_and_renamed_spec.rb

We should only throw an error if the value is set. By also failing on `value` logstash terminates at startup even if the setting isn't set:
```
% bin/logstash -e ""
Sending Logstash logs to /Users/joaoduarte/elastic/logstash/logs which is now configured via log4j2.properties
[2019-04-05T10:01:43,198][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: The setting `xpack.management.elasticsearch.url` has been deprecated and removed from Logstash>, :backtrace=>["/Users/joaoduarte/elastic/logstash/logstash-core/lib/logstash/settings.rb:605:in `value'", "/Users/joaoduarte/elastic/logstash/logstash-core/lib/logstash/settings.rb:96:in `block in format_settings'", "org/jruby/RubyHash.java:1419:in `each'", …
```

prevent DeprecatedRemovedSetting from fatally stopping logstash

---

lib/systeminstall/pleasewrap.rb

This workaround is only executed during pkging tasks so doesn't influence normal execution.
fixes #10593

work around jruby-5642 during package installation on jdk11

---

docs/static/breaking-changes.asciidoc

This PR adds a tagged region in the Logstash Reference > Breaking Changes page (https://www.elastic.co/guide/en/logstash/master/breaking-changes.html), such that content can be re-used in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-breaking-changes.html).
At least one tagged region must exist to prevent build errors in the Installation and Upgrade Guide, though as is the case now for V8.0.0 it can be an empty tagged region.
At this time, the Installation and Upgrade Guide for version X only lists the breaking changes specific to that version. If this Logstash page will contain information about multiple versions, we either need to (1) ensure that only the items that are specific to the appropriate version are tagged as "notable" …

[DOCS] Adds tagged region for notable breaking changes

---

docs/static/releasenotes.asciidoc

Also added core and plugin headings per review comments in #10655 
Merge targets: 7.0 7.x  *after* #10665 is merged.  If there's a delay for some reason, merging into 7.0 only will be fine. I'll backport to 7.x later.

Combine plugins from alphas, betas, and rcs to make 7.0 release notes

---

docs/static/upgrading.asciidoc

Added links to specific breaking changes rather than duplicating content. 
Merge targets: 7.0 7.x master

Add links to breaking changes for beats-ecs, java work, and field refs changes

---

build.gradle

when  `RELEASE=1` or  `VERSION_QUALIFIER` is set, assume this is a release build and the exact version match ES artifact will be downloaded, otherwise download a `-SNAPSHOT` artifact.

download exact version artifact for release build otherwise download snapshot

---

docs/static/advanced-pipeline.asciidoc
qa/integration/specs/beats_input_spec.rb

In filebeat prospectors settings have been renamed to inputs. When
prospectors is used a deprecation warning is printed. With 7.0
`filebeat.prospectors` will be removed.
This change updates all uses of prospectors with inputs. For now
filebeat events report `prospector.type` and `input.type` for
compatibility reasons.
This replaces https://github.com/elastic/logstash/pull/10048

Rename filebeat.prospectors to filebeat.inputs

---

logstash-core/lib/logstash/api/commands/default_metadata.rb

Add the following fields:
*   status: Status of node (green, etc.)
*   ephemeral_id: Ephemeral ID of node
*   name: Name of node, could be different from host
*   snapshot: Whether the node is working off a snapshot build
Note that `uuid` was requested in [the issue](https://github.com/elastic/logstash/issues/10121) but this data seems to be available already in `id`.
Closes https://github.com/elastic/logstash/issues/10121

 Enhance `GET /` API for Metricbeat

---

docs/include/input.asciidoc
docs/include/plugin_header.asciidoc
docs/include/version-list-intro.asciidoc

Ports elastic/logstash-docs#688 to this repo. Asciidoctor doesn't quite
work on this repo, but it comes closer with these changes.

[Docs] Asciidoctor support

---

logstash-core/lib/logstash/patches/resolv.rb
logstash-core/lib/logstash/patches/resolv_9270.rb
logstash-core/spec/logstash/jruby_version_spec.rb

This is essentially the same patch as logstash-plugins/logstash-filter-dns#52 
- It fixes a leak in the provided `resolv.rb` in JRuby version starting at 9.2.7.0 which result in timing out all DNS resolutions under some circumstances.
- It adds a temporary spec that will break upon JRuby version change to force the manual verification of the inclusion of the fix in JRuby, see jruby/jruby#5722 and removal of the patch in logstash-core.

JRuby resolv.rb leak

---

logstash-core/src/main/java/co/elastic/logstash/api/Codec.java

fixes the following:
```
13:25:38 logstash-core/src/main/java/co/elastic/logstash/api/Codec.java:51: warning: no @throws for java.io.IOException
13:25:38     void encode(Event event, OutputStream output) throws IOException;
13:25:38          ^
13:25:44 1 warning
13:25:44 Problems generating Javadoc.
```
[edit] running `./gradlew :logstash-core:javadoc` is enough to test

fix javadoc warning for Codec.java

---

logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb

Fixes #10726.
Only cause for concern I've seen is the output of the max fields for the young gen since in G1 it's unbounded:
```
"mem": {
"heap_used_percent": 22,
"heap_committed_in_bytes": 1073741824,
"heap_max_in_bytes": 1073741822,
"heap_used_in_bytes": 241172480,
"non_heap_used_in_bytes": 139341592,
"non_heap_committed_in_bytes": 160690176,
"pools": {
"survivor": {
"used_in_bytes": 22020096,
"committed_in_bytes": 22020096,
>         "peak_max_in_bytes": -1,
"peak_used_in_bytes": 35651584,
>         "max_in_bytes": -1
},
"young": {
"used_in_bytes": 119537664,
"committed_in_bytes": 537919488,
>         "peak_max_in_bytes": -1,
"peak_used_in_bytes": 343932928,
>         "max_in_bytes": -1
},
"old": {
"used_in_bytes": 99614720,
"committed_in_bytes": 513802240,
"peak_max_in_bytes": …
```

Include G1 in JVM heap metrics

---

logstash-core/build.gradle
logstash-core/src/main/java/co/elastic/logstash/api/Context.java
logstash-core/src/main/java/co/elastic/logstash/api/CounterMetric.java
logstash-core/src/main/java/co/elastic/logstash/api/Metric.java
logstash-core/src/main/java/co/elastic/logstash/api/NamespacedMetric.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaCodecDelegator.java
logstash-core/src/main/java/org/logstash/plugins/ContextImpl.java
logstash-core/src/main/java/org/logstash/plugins/CounterMetricImpl.java
logstash-core/src/main/java/org/logstash/plugins/NamespacedMetricImpl.java
logstash-core/src/main/java/org/logstash/plugins/PluginFactoryExt.java
logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java
logstash-core/src/main/java/org/logstash/plugins/RootMetricImpl.java
logstash-core/src/test/java/org/logstash/config/ir/compiler/JavaCodecDelegatorTest.java
logstash-core/src/test/java/org/logstash/plugins/CounterMetricImplTest.java
logstash-core/src/test/java/org/logstash/plugins/MetricTestCase.java
logstash-core/src/test/java/org/logstash/plugins/NamespacedMetricImplTest.java
logstash-core/src/test/java/org/logstash/plugins/TestContext.java
logstash-core/src/test/java/org/logstash/plugins/TestPluginFactory.java
logstash-core/src/test/java/org/logstash/plugins/filters/UuidTest.java

Resolves #10733.
Exposes:
- `MetricExt` as `co.elastic.logstash.api.Metric`,
- `NamespacedMetricExt` as `co.elastic.logstash.api.NamespacedMetric`,
- `LongCounter` as `co.elastic.logstash.api.CounterMetric`
and migrates the `JavaCodecDelegator` to use the public API so integration tests cover the code.
Plugins can retrieve a `NamespacedMetric` instance scoped to their plugin via `co.elastic.logstash.api.Context#getMetric(Plugin)`.

Expose Metrics API to Java plugins

---

logstash-core/build.gradle
logstash-core/src/main/java/co/elastic/logstash/api/Context.java
logstash-core/src/main/java/co/elastic/logstash/api/CounterMetric.java
logstash-core/src/main/java/co/elastic/logstash/api/Metric.java
logstash-core/src/main/java/co/elastic/logstash/api/NamespacedMetric.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaCodecDelegator.java
logstash-core/src/main/java/org/logstash/plugins/ContextImpl.java
logstash-core/src/main/java/org/logstash/plugins/CounterMetricImpl.java
logstash-core/src/main/java/org/logstash/plugins/NamespacedMetricImpl.java
logstash-core/src/main/java/org/logstash/plugins/PluginFactoryExt.java
logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java
logstash-core/src/main/java/org/logstash/plugins/RootMetricImpl.java
logstash-core/src/test/java/org/logstash/config/ir/compiler/JavaCodecDelegatorTest.java
logstash-core/src/test/java/org/logstash/plugins/CounterMetricImplTest.java
logstash-core/src/test/java/org/logstash/plugins/MetricTestCase.java
logstash-core/src/test/java/org/logstash/plugins/NamespacedMetricImplTest.java
logstash-core/src/test/java/org/logstash/plugins/TestContext.java
logstash-core/src/test/java/org/logstash/plugins/TestPluginFactory.java
logstash-core/src/test/java/org/logstash/plugins/filters/UuidTest.java

Expose Metric API to Java plugins and migrate JavaCodecDelegator to new Metric API.
This is a clean backport of #10761.

Expose Metrics API to Java plugins (#10761)

---

logstash-core/lib/logstash/api/commands/stats.rb

Resolve this comment: https://github.com/elastic/logstash/issues/10120#issuecomment-504671395
This was lost during the review process for https://github.com/elastic/logstash/pull/10576/ and simply needed to be included inserted into the API return as we parse the extended_stats data structure.

Inject hash and ephemeral_id into stats

---

logstash-core/lib/logstash/api/commands/default_metadata.rb

Adds request made by @ycombinator [here](https://github.com/elastic/logstash/issues/10121#issuecomment-477960900).
Adds the following fields to `GET /`:
```
"pipeline" : {
"batch_size" : 125,
"workers" : 8
}
```

Add workers and batch_size to root request

---

logstash-core/lib/logstash/api/commands/node.rb

Fixes https://github.com/elastic/logstash/issues/10883
During the review process, @yaauie wisely suggested that we move the UUID lookup out of the LIR serializer to avoid mutating the structure and to safeguard against future bugs. In doing so, though, I neglected to note that the `node` endpoint was relying on this functionality as well. This PR moves the lookup functionality into the API layer at the `node` endpoint.
@yaauie You will see some code duplication here between the `node` endpoint and the `stats` endpoint. (Note also that I explicitly marked this version as private.) 
I briefly considered moving the vertex decorator into `base.rb` but wasn't certain whether or not it fit into the paradigm for that file. Please let me know if you think we should keep the duplication as-is or …

Restore UUID lookup to node

---

logstash-core/lib/logstash/api/commands/node.rb
logstash-core/lib/logstash/api/commands/stats.rb
logstash-core/lib/logstash/api/modules/node.rb
logstash-core/lib/logstash/api/modules/node_stats.rb
logstash-core/lib/logstash/config/lir_serializer.rb
logstash-core/lib/logstash/config/pipelines_info.rb
x-pack/lib/monitoring/inputs/metrics/state_event_factory.rb
x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb

* parent 8c5697c7485eeabb85ab00e972660d6190e6dae7
author Guy Boertje <guy@elastic.co> 1556806171 +0100
committer Mike Place <mike.place@elastic.co> 1557234770 +0200
Bump JrJackson to 0.4.8
Fixes #10748
LIR serializer refactor
Remove commented code
Remove more commented code
Remove license and add encoding
Style change to make code more vertical.
eid and hash
Use pipelines_info to construct the stats
Add tests for new fields
Add queue stats
* bad merge resolution
* bad merge resolution
* Don't merge if nil
* Better merge strategy
* add vertex gate
* Guard against nil
* Use extended queue stats in pipeline report
* Add cluster uuids to Elasticsearch outputters in pipeline output
* move uuid
* remove old uuid lookup
* Only populate cluster_uuids when present
* remove print
* cluster_uuids -> …

[BACKPORT] Enhance GET _node/stats/pipelines API for Metricbeat monitoring (#10576)

---

rakelib/plugins-metadata.json

This simply sets `"default-plugins": true` on the `logstash-input-twitter`.
This is a followup on #10928 where setting logstash-input-twitter as a default plugin resulted in a build failure. It was reverted for the sake of moving forward the BC builds.
We can now deal with build issues here separately.

logstash-input-twitter as a default plugin

---

Gemfile.template
build.gradle
rakelib/plugin.rake
rakelib/plugins_docs_dependencies.rake

- have `bootstrap` task do as little as possible: install gems in Gemfile.template that don't belong to groups
- have test tasks depend on the `installTestGems` task instead of `bootstrap`
- logstash es output is now a dependency because of license checking
- fix out of memory problem in SharedHelpers.trap
Also use release lockfile during installDefaultGems
The release lockfile is only copied to Gemfile.lock if
it doesn't exist. During the `installDefaultGems` task other
plugin installation tasks already occurred, generating a lock file.
This commit removes it before running the plugin installation.

Cleanup gradle tasks around dependency installation

---

tools/release/bump_plugin_versions.rb

By removing the default plugins from the Gemfile.template
the current task that modified the template was not working correctly.
This commit either replaces the dependency entry if it exists or
otherwise creates it.
This can be tested by running `./tools/release/bump_plugin_versions.rb 7.2 7.2.0 patch` in the 7.2 branch. You can verify that some plugins are bumped by minors and majors (not just patches).
Applying this patch and rerunning the command will yield only patch bumps as expected.

fix plugin version bump rake task

---

rakelib/plugins-metadata.json

[7.3 clean backport of #10934] logstash-input-twitter as a default plugin

[7.3 clean backport of #10934] logstash-input-twitter as a default plugin

---

rakelib/plugins-metadata.json

[7.x clean backport of #10934] logstash-input-twitter as a default plugin

[7.x clean backport of #10934] logstash-input-twitter as a default plugin

---

docs/index.asciidoc
docs/static/running-logstash-windows.asciidoc
docs/static/setting-up-logstash.asciidoc

Backport of #10809 that was missed for 6.6 branch. 
This PR adds the file structure required to merge #10805/#10946

[Doc][Backport]Add structure for new windows topic

---

docs/static/releasenotes.asciidoc

Adds `Coming` tag to release notes. Should be removed on day of release.

Add coming tag to 7.2.1 release notes

---

docs/static/monitoring/configuring-logstash.asciidoc
docs/static/security/logstash.asciidoc
docs/static/setup/configuring-xls.asciidoc

Adds a few missing `[attributes="subs"]` clauses for asciidoctor.

Docs: Add more missing subs for asciidoctor

---

docs/static/releasenotes.asciidoc

Includes a cherry-pick of the 7.2.0 release notes

Release notes 7.3.0

---

docs/index.asciidoc

Doc version was set to `7.3.0` when we cut the branch. This PR sets the docs release state to `released`.

[Doc]Set docs release state to released

---

docs/include/filter.asciidoc

The filter docs were using markdown syntax for code listings and those
cause trouble in Asciidoctor. This switches it to standard Asciidoc
syntax which works in both AsciiDoc and Asciidoctor.

Docs: Standard Asciidoc for filter

---

logstash-core/build.gradle
versions.yml

Also splits out jackson and jackson databind versions to allow separate revisions
for databind.
Backport of #11040

Update jrjackson, jackson versions

---

logstash-core/lib/logstash/api/commands/stats.rb
logstash-core/spec/logstash/api/commands/stats_spec.rb
logstash-core/spec/support/shared_contexts.rb

avoid variable collision in pipeline stats api

---

docs/static/codec.asciidoc
docs/static/filter.asciidoc
docs/static/input.asciidoc
docs/static/output.asciidoc

In the "methods" sections of the how to develop a plugin docs
Asciidoctor as incorrectly passing backticks into the output when it
should have marked the words surrounded by backticks as code. I'm not
100% sure why it did that. The fix is to force macro evaluation
immediately on attribute assignment.

Docs: Fix backticks in how to docs

---

docs/static/monitoring/collectors.asciidoc

Fixes formatting in a table cell in `logstash-monitoring-overview.html`.
A `+` which was required by AsciiDoc was leaking into the output when
the doc is built with Asciidoctor.

Docs: Fix formatting in table

---

config/jvm.options
config/log4j2.properties
logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaInputDelegatorExt.java
qa/integration/fixtures/pipeline_id_log_spec.yml
qa/integration/specs/pipeline_id_log_spec.rb

Add tag fish with pipeline.id to log lines

Add pipeline.id to log lines

---

docs/index.asciidoc

[Doc]Update logstash to use shared version files for 6.8

---

docs/static/monitoring/configuring-logstash.asciidoc
docs/static/monitoring/monitoring-overview.asciidoc

Related to https://github.com/elastic/elasticsearch/issues/46718
This PR updates links to monitoring content that has moved from the Stack Overview to the Elasticsearch Reference. 
It also removes a link to the "troubleshooting" content, since the most recent versions of the destination page no longer covers the described problem.

[DOCS] Fixes links to monitoring content

---

NOTICE.TXT
logstash-core/logstash-core.gemspec

we're using quite an old version of Puma (2.x) although ci failures like https://logstash-ci.elastic.co/job/elastic+logstash+7.5+multijob--ruby-unit-tests/7/console may not be solved by in 4.x, it's still desirable to keep this dependency updated.

upgrade puma to 4.x

---

logstash-core/logstash-core.gemspec

Currently, the version of the elasticsearch gem bundled with Logstash requires the type
field to be set, which is incompatible Elasticsearch 8.x after types were removed.

Update elasticsearch gem dependency requirements

---

rakelib/plugins_docs_dependencies.rake

The rake task that generates a json manifest of installed plugin versions for [doc generation's `plugindocs.rb`](https://github.com/elastic/docs-tools/blob/2291ca1feab8835383e54c1d31a222e8aaa80d55/plugindocs.rb#L18) selects the subset of logstash dependencies matching a specific pattern, but this pattern does not include the new integration plugins that are set to ship with Logstash 7.5.
This PR first refactors the list of acceptable plugin types out of a regular expression into a more readable array, and then adds `integration` to the mix.
Merge targets: `master`, `7.x`, `7.5`

Integration plugin docs support

---

docs/static/azure-module.asciidoc
docs/static/deploying.asciidoc
docs/static/monitoring/configuring-logstash.asciidoc
docs/static/monitoring/intro.asciidoc
docs/static/monitoring/monitoring-overview.asciidoc
docs/static/security/logstash.asciidoc

Backports https://github.com/elastic/logstash/pull/11341 and adds additional link fixes.

[DOCS] Fixes security and monitoring links

---

docs/static/azure-module.asciidoc
docs/static/deploying.asciidoc
docs/static/docker.asciidoc
docs/static/getting-started-with-logstash.asciidoc
docs/static/management/configuring-centralized-pipelines.asciidoc
docs/static/monitoring/configuring-logstash.asciidoc
docs/static/monitoring/intro.asciidoc
docs/static/monitoring/monitoring-overview.asciidoc
docs/static/setup/setting-up-xpack.asciidoc

This PR fixes links that are incorrectly sending users to the X-Pack Reference or Stack Overview.
It also fixes the following links that will break in elastic/docs#1490
> 12:47:37 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.3/deploying-and-scaling.html:
12:47:37 INFO:build_docs:   - en/x-pack/6.2/xpack-security.html
12:47:37 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.4/deploying-and-scaling.html:
12:47:37 INFO:build_docs:   - en/x-pack/6.2/xpack-security.html
12:47:37 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.5/deploying-and-scaling.html:
12:47:37 INFO:build_docs:   - en/x-pack/6.2/xpack-security.html
12:47:37 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.6/deploying-and-scaling.html:
12:47:37 …

[DOCS] Fixes occurrences of xpack-ref attribute

---

docs/static/docker.asciidoc
docs/static/getting-started-with-logstash.asciidoc
docs/static/management/configuring-centralized-pipelines.asciidoc
docs/static/setup/setting-up-xpack.asciidoc

Related to https://github.com/elastic/docs/pull/1490 and https://github.com/elastic/logstash/pull/11360
This PR replaces usage of the {xpack-ref} shared attribute in the Logstash Reference

[DOCS] Replaces occurrences of xpack-ref

---

settings.gradle

Since Logstash may not be cloned into a “logstash” directory (e.g. on Windows ci we mount it as A:/) gradle needs to be told the name of the top level project. 
CI failure example can be seen here: https://logstash-ci.elastic.co/blue/organizations/jenkins/elastic%2Blogstash%2Bmaster%2Bmultijob-windows-compatibility/detail/elastic%20logstash%20master%20multijob-windows-compatibility/101/pipeline#log-75

[gradle] add rootProject.name

---

docs/static/page_header.html

Explicitly set page_header.html for 6.8 so that the default notice can be updated for OOM versions.
Prerequisite for: elastic/docs#1528

[DOCS] Added older release notice.

---

docs/static/page_header.html

Related to elastic/docs#1426
Applies to 6.2 and earlier. Version needs to be updated for each branch.

[DOCS] Add EOL notice.

---

docs/static/page_header.html

Backports EOL notice from https://github.com/elastic/logstash/pull/11410.

[DOCS] Add EOL notice. 

---

Gemfile.jruby-2.5.lock.release

4.2.0 includes support for `timeout_scope => event`

update grok filter to 4.2.0 (for LS 7.5.1)

---

docs/static/releasenotes.asciidoc

Created from the goodness in @andsel's  work in #11445, with formatting changes and minor additions. 
To do: 
PREVIEW: http://logstash_11446.docs-preview.app.elstc.co/guide/en/logstash/6.8/releasenotes.html

[Doc] Release Notes 6.8.6

---

docs/static/releasenotes.asciidoc

Created from the goodness in @andsel's  work in #11444, with formatting changes and minor additions. 
To do: 
PREVIEW:  http://logstash_11448.docs-preview.app.elstc.co/guide/en/logstash/7.5/releasenotes.html

[Doc] Release notes 7.5.1

---

logstash-core/lib/logstash/api/modules/node_stats.rb

The method was added in https://github.com/elastic/logstash/pull/5381/files#diff-5b309943da7f980637d1fb663cacd01a.
AFAICT it's not used at the moment.
```
$ git grep mem_payload
logstash-core/lib/logstash/api/modules/node_stats.rb:        def mem_payload
```

Remove unused NodeStats#mem_payload

---

rakelib/plugins_docs_dependencies.rake

backport the Signal.trap leak from #10942 (commit 15fb308)
This fixes failed doc builds such as https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+logstash-plugin-docs/56/console when running `./gradlew generatePluginsVersion` on the 6.8 branch.

backport SharedHelpers.trap memleak fix to 6.8

---

rakelib/plugins-metadata.json

One of the java plugin examples showed up in the latest plugin docgen for 6.8. Looks like they all should be added to the skiplist.

Add java plugin examples to skiplist for 6.8

---

docs/static/include/javapluginpkg.asciidoc

Hi there,
The command to compile to JAR file is missing from the doc. Let me add it for clarification.
Should I also create similar PR for every other branch or do you have another way to backport this easily?

[Documentation] Add the "Compile to JAR file" build command

---

logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java

Fixes #11105
Relates to #11175
This is an alternate implementation of #11479 where the compiles class caching is kept per-pipeline into the `CompiledPipeline` class. 
See #11479 for the problem details.
This approach has the following benefits:
- Solves a potential leak for a global cache upon pipeline reloads.
- Solves a potential class name collision for identical plugins IDs across multiple pipelines.
- Avoids dealing with cache invalidation altogether because the cache is cleared every time a pipeline is created/reloaded.

Move class caching from ComputeStepSyntaxElement to CompiledPipeline

---

config/logstash.yml
docs/static/settings/configuration-management-settings.asciidoc
docs/static/settings/monitoring-settings.asciidoc
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/lib/config_management/extension.rb
x-pack/lib/helpers/elasticsearch_options.rb
x-pack/lib/monitoring/monitoring.rb
x-pack/lib/template.cfg.erb
x-pack/spec/config_management/elasticsearch_source_spec.rb
x-pack/spec/config_management/extension_spec.rb
x-pack/spec/helpers/elasticsearch_options_spec.rb

depends on recent ES output plugin (https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/906)
resolves https://github.com/elastic/logstash/issues/11488

Feat: x-pack cloud id/auth for monitoring/management

---

logstash-core/lib/logstash/java_pipeline.rb

Fixes #11170 
Relates to #11175
This PR separate the `WorkerLoop` *construction* and *run* parts  in 2 so that we can wait on the completion of all the `WorkerLoop` construction before ultimately starting the inputs. 
This solves the problem where inputs were started before the `WorkerLoop` were ready to process events which resulted in either accumulating a backlog in PQ or creating backpressure.   
**Question**: Should we make that behaviour optional?

start inputs only when all WorkerLoop are fully initialized

---

Gemfile.jruby-2.5.lock.release

v6.0.5 has compatibility issues with the lumberjack output, due to
the removal of CBC ciphers from that version of the beats input

Pin beats version to earlier version (6.0.4)

---

config/logstash.yml
docs/static/running-logstash-command-line.asciidoc
docs/static/settings-file.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/runner.rb
logstash-core/lib/logstash/settings.rb
logstash-core/locales/en.yml
logstash-core/spec/conditionals_spec.rb
logstash-core/spec/logstash/filters/base_spec.rb
logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/spec/support/pipeline/pipeline_helpers.rb
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

Fixes #10938
Followup from abandoned PRs #11020 and #11099
TODO:
This PR adds the `pipeline.ordered` option that when used under the Java execution and only when `pipeline.workers` is set to 1 will preserve the batched events order throughout the filters+output execution. 
Under this PR both the example in #11099 description and the aggregate filter scenario 
https://github.com/elastic/logstash/pull/11099#issuecomment-526378147 are working correctly. 
The Java execution model is created from a graph representation of the configuration and under that model, each conditional evaluation is splitting the batch events is two, for the events evaluating on the `true` side and the `false` side of the condition and then moving down the computation path on each side in turns. This means that all …

Add support for pipeline.ordered setting for java execution

---

config/logstash.yml
docs/static/running-logstash-command-line.asciidoc
docs/static/settings-file.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/runner.rb
logstash-core/lib/logstash/settings.rb
logstash-core/locales/en.yml
logstash-core/spec/conditionals_spec.rb
logstash-core/spec/logstash/filters/base_spec.rb
logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/spec/logstash/pipeline_spec.rb
logstash-core/spec/support/pipeline/pipeline_helpers.rb
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

[7.7 clean backport of #11524] add support for pipeline.ordered setting for java execution

---

logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java

Fixes #11560 
The fix for the Java execution slowdown relative to the number of worker in #11482 introduced a regression when using multiple pipelines. By analyzing the regression we realized that although the fix was solving the problem for the single pipeline with multiple workers it actually did not correctly solve the root cause of the problem. By removing the global class cache it prevented cross-pipelines class caching, which resulted in the regression.
This PR reverts the previous fix and correctly address the root cause. The real problem was that the  configuration Java code was being generated multiple times through the `hashCode()` and `equals()` methods which were calling the `normalizedSource()` method multiple times.  The fix addresses this by memoizing the `hashCode()` and …

revert #11482 and fix redundant code generation

---

logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java

7.6 backport of #11564
The log4j pluginid changes were conflicting, but the merge was straightforward.

[7.6 backport of #11564] revert #11482 and fix redundant code generation

---

Gemfile.jruby-2.5.lock.release

More can be read about here: https://github.com/logstash-plugins/logstash-input-http/blob/master/CHANGELOG.md#333

Upgrade http input to skip tcnative upgrade

---

docs/static/monitoring/monitoring-internal.asciidoc
docs/static/monitoring/monitoring-overview.asciidoc

We wanted to alert users that internal collectors would be deprecated in 7.7.  The current tagging is misleading, and this PR is an attempt to clarify. 
PREVIEW:  http://logstash_11607.docs-preview.app.elstc.co/guide/en/logstash/7.6/configuring-logstash.html

[DOC]Clarify internal collectors deprecation status for 7.6

---

NOTICE.TXT
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/jruby-openssl-0.10.4-NOTICE.txt

We are automatically pulling in a patch-level update to jruby-openssl as a part of the `installDefaultGems` task, and need to update our notices to reflect the version we are including.

update jruby-openssl license notice for 7.6.x

---

NOTICE.TXT
tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/jruby-openssl-0.10.4-NOTICE.txt

We are automatically pulling in a patch-level update to jruby-openssl as a part of the `installDefaultGems` task, and need to update our notices to reflect the version we are including.

update jruby-openssl license notice for 6.8.x

---

Gemfile.jruby-2.5.lock.release

In the release reference docs, plugin documentation files aren't version, only their content is.
Because if this, any updates to the documentation overwrites the existing files, as we can't know that the existing file is "more up to date".
So to fix the continuous broken memcache ttl field reference link, I've released a new version of the 0.1.x series of the memcache filter, and bumping it here.
Newer logstash branches already have the 1.x version of this plugin where the fix has been published since 1.0.1.

Bump memcache filter version to fix reference documentation

---

CONTRIBUTING.md

See https://github.com/elastic/logstash/issues/11543: add the label "good first issue" and a link to https://github.com/elastic/logstash/contribute in the [contributing.md](https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md) file

Add more references to contributing issues

---

logstash-core/lib/logstash/compiler/lscl.rb
logstash-core/spec/logstash/compiler/compiler_spec.rb

Fixes #11222
This makes sure that parsed plugins option keys are stripped of their quotes so that the actual key string does not contain quotes. Added related spec (which breaks without the patch).

support quoted plugin option keys

---

logstash-core/lib/logstash/compiler/lscl.rb
logstash-core/spec/logstash/compiler/compiler_spec.rb

[7.6 clean backport of #11688]  support quoted plugin option key

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/EventCondition.java

back-port of https://github.com/elastic/logstash/pull/11653 (for 7.6)

Fix: use 'light' match-ing (not depending on scope)

---

logstash-core/lib/logstash/util/unicode_trimmer.rb
logstash-core/spec/logstash/util/unicode_trimmer_spec.rb

this is used by the SNS output:
https://github.com/logstash-plugins/logstash-output-sns/blob/5b796a00959946ea3ef8acf6d16617f8ef58b09d/lib/logstash/outputs/sns.rb#L98
fixes test failure such as https://travis-ci.org/github/logstash-plugins/logstash-output-sns/jobs/665031056#L501

bring back unicode trimmer for LogStash::Util

---

Gemfile.jruby-2.5.lock.release

Since version 4.17.0 was yanked: https://github.com/octokit/octokit.rb/releases/tag/v4.17.0, this PR bumps the version to 4.18.0.

Bump octokit to 4.18.0 due to gem yanking

---

logstash-core/lib/logstash/config/lir_serializer.rb
logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java
logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java
logstash-core/src/main/java/org/logstash/execution/MemoryReadBatch.java
logstash-core/src/main/java/org/logstash/execution/QueueBatch.java
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

Fixes #11550
Relates to #11175
When using `pipeline.ordered` the batch events are sent 1 by 1 down the filters and output. This PR rebatches after the filters so that full batches can be sent to the outputs. It does that by separating the filters and output execution with the introduction of a separator vertex in the pipeline graph between the filters and outputs and compiling both sections separately and in the worker_loop calling both compute separately which provides the possibility to rebatch after the filters.

Rebatch after filters when using pipeline.ordered

---

logstash-core/lib/logstash/config/lir_serializer.rb
logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java
logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java
logstash-core/src/main/java/org/logstash/execution/MemoryReadBatch.java
logstash-core/src/main/java/org/logstash/execution/QueueBatch.java
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

[7.8 clean backport of #11710] separate filter & output execution, rebatch after filter when ordered

---

logstash-core/lib/logstash/config/lir_serializer.rb
logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java
logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java
logstash-core/src/main/java/org/logstash/execution/MemoryReadBatch.java
logstash-core/src/main/java/org/logstash/execution/QueueBatch.java
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

[7.7 clean backport of #11710] separate filter & output execution, rebatch after filter when ordered

---

logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/pipeline_pq_file_spec.rb
logstash-core/spec/logstash/util/wrapped_synchronous_queue_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/AckedBatch.java
logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
logstash-core/src/main/java/org/logstash/common/LsQueueUtils.java
logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/execution/MemoryReadBatch.java
logstash-core/src/main/java/org/logstash/execution/QueueBatch.java
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java
logstash-core/src/main/java/org/logstash/ext/JrubyAckedReadClientExt.java
logstash-core/src/main/java/org/logstash/ext/JrubyMemoryReadClientExt.java
logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
logstash-core/src/test/java/org/logstash/config/ir/EventConditionTest.java
x-pack/spec/monitoring/inputs/metrics_spec.rb

This is a followup to #11710 with some cleanups.
- cleanup `RubyArray`  "rawtypes" and "unchecked"  `@SuppressWarnings` 
- simplify `AckedReadBatch`
- change `CompiledExecution#compute` methods signature to use a `Collection` instead of `RubyArray`. 
- optimize/eliminate conversions to `RubyArray` in a few places. 
- avoid processing empty batches in `WorkerLoop` which happens when the queue read reaches the timeout. 
- remove `QueueBatch#merge` method
- change `LinkedHashSet` to `ArrayList` in `MemoryReadBatch` and `AckedReadBatch`
- refactor Ruby pipeline to use same strategy as Java pipeline which does not require `merge`

 simplify batch classes, do not compute JE empty batches, refactor RE worker loop

---

logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/pipeline_pq_file_spec.rb
logstash-core/spec/logstash/util/wrapped_synchronous_queue_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/AckedBatch.java
logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
logstash-core/src/main/java/org/logstash/common/LsQueueUtils.java
logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/execution/MemoryReadBatch.java
logstash-core/src/main/java/org/logstash/execution/QueueBatch.java
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java
logstash-core/src/main/java/org/logstash/ext/JrubyAckedReadClientExt.java
logstash-core/src/main/java/org/logstash/ext/JrubyMemoryReadClientExt.java
logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
logstash-core/src/test/java/org/logstash/config/ir/EventConditionTest.java
x-pack/spec/monitoring/inputs/metrics_spec.rb

[7.x clean backport or #11737] simplify batch classes, do not compute JE empty batches, refactor RE worker loop

---

Dockerfile
build.gradle
ci/license_check.sh
ci/unit_tests.sh
gradle.properties
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
logstash-core/benchmarks/build.gradle
logstash-core/build.gradle
qa/integration/build.gradle
rubyUtils.gradle
tools/benchmark-cli/build.gradle
tools/dependencies-report/build.gradle
tools/ingest-converter/build.gradle
x-pack/build.gradle

* Backport of #11742. Not a clean backport as `7.x` had not previously been upgraded to `5.6.4` as `master` had been.
* Update gradle version to 6.3
Gradle versions prior to 6.3 cannot run under JDK14.
This commit upgrades the version of Gradle to 6.3, and removes all deprecation warnings that can currently be removed.
Changes include:
* Increase gradle memory to 2g
* Increase gradle memory in the license check job to 2g
* Replace use of `testCompile`
* Replace `runtime` with `runtimeOnly`
* Remove`compile` depedencies from gradle files
* Replace deprecated archive methods
* Fix dependencies report build
* Make jruby dependencies 'api', fix archiveVersion
* Set `duplicatesStrategy` for all tasks of type Copy
* Use `configureEach` for global 'withType' calls
** Use the recommended Tasks …

Update gradle version to 6.3 (#11742)

---

tools/benchmark-cli/build.gradle

use same jackson version in benchmark-cli
update benchmark cli dependencies

use same jackson version in benchmark-cli

---

config/logstash.yml
docs/static/breaking-changes.asciidoc
docs/static/reloading-config.asciidoc
docs/static/running-logstash-command-line.asciidoc
docs/static/settings-file.asciidoc

Alert users that `s` is a required part of the value. If seconds `s` is not specified, nanoseconds is assumed.  
**DOC PREVIEWS:**
* http://logstash_11771.docs-preview.app.elstc.co/guide/en/logstash/master/breaking-6.0.html
* http://logstash_11771.docs-preview.app.elstc.co/guide/en/logstash/master/logstash-settings-file.html
* http://logstash_11771.docs-preview.app.elstc.co/guide/en/logstash/master/reloading-config.html
* http://logstash_11771.docs-preview.app.elstc.co/guide/en/logstash/master/running-logstash-command-line.html

[Doc]Note that unit qualifier is required for config.reload.interval

---

logstash-core/lib/logstash/util/substitution_variables.rb
logstash-core/spec/logstash/config/mixin_spec.rb

Improves upon #10583 by adding specs.
> I'm not sure if this functionality was left out deliberately, but Logstash does not currently attempt interpolate variables of type `LogStash::Util::Password` with values from the environment or Logstash secret store; this seems odd to me as those are the variables one would most wish to protect and keep out of a plain text pipeline definition.
> 
> This PR resolves this by pulling the original value from the Password object and attempting to interpolate that.
>
> -- @01100010011001010110010101110000 in https://github.com/elastic/logstash/pull/10583

support Environment and Keystore substitutions in password-type plugin options

---

docs/index.asciidoc
docs/static/redirects.asciidoc

Adds a redirects page to help prevent broken links and to make fixing them easier and quicker. The page is coded so that it won't appear in the Table of Contents.
**PREVIEW:** http://logstash_11790.docs-preview.app.elstc.co/guide/en/logstash/master/redirects.html

[Doc]Add redirects page

---

docs/static/monitoring/monitoring-internal.asciidoc
docs/static/monitoring/monitoring-output.asciidoc
docs/static/settings/monitoring-settings.asciidoc

Work continued from #11714 
**PREVIEW:** http://logstash_11789.docs-preview.app.elstc.co/guide/en/logstash/master/configuring-logstash.html

[Doc]Doc updates for internal collectors

---

x-pack/lib/license_checker/license_reader.rb
x-pack/spec/license_checker/license_reader_spec.rb

This reverts commit 76dc55f463e51a9a64fe0fd39921bd302d9353b0 in the 7.7 branch
The reason for this revert is that the fix will be implemented by
having the ES output set up credentials/hosts and cloud.id during
build_client method. With this there will be no need for changing
code on the Logstash core side.
We will later reintroduce the spec part of this commit.

Revert "Fix: cloud_id not propagating from monitoring config"

---

Gemfile.jruby-2.5.lock.release

This bumps ES output dependency on v10.4.2 which includes the authentication validation and `cloud_id` fix. 
Relates to #11830

[7.6] bump elasticsearch output dependency to 10.4.2

---

docs/static/management/configuring-centralized-pipelines.asciidoc
docs/static/settings/configuration-management-settings.asciidoc

Backports # 10341 
logstash_admin role is not enough.
As the ls-security page mentions correctly:
"The user you specify here must have the built-in logstash_admin role as well as the logstash_writer role that you created earlier"
Updates static settings for extra role needed

[doc] missing role for config management integration

---

docs/static/management/configuring-centralized-pipelines.asciidoc
docs/static/settings/configuration-management-settings.asciidoc

Backports: #10341 
logstash_admin role is not enough.
As the ls-security page mentions correctly:
"The user you specify here must have the built-in logstash_admin role as well as the logstash_writer role that you created earlier"
Updates static settings for extra role needed

[doc] missing role for config management integration (#10341)

---

logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java

In time comparison of LocalDateTime the isBefore is strict, so in case two instants has the same millisecond fails in test (happens in [Windows tests](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-matrix-jdk-windows-java-unit-tests/LS_RUNTIME_JAVA=zulu11,nodes=windows-2016/3/consoleFull))

Fix: missed 'equal' part in time comparison test

---

qa/integration/services/service.rb

Currently when integration test fixture setup fails, the tests proceed as usual,
resulting in noisy logs where the source of the error is not easy to discover.
This commit will raise an exception and log the exit status if the script fails to
setup.
It will also log but not raise if the teardown script fails to run correctly,
preferring to inform rather than fail tests when teardown scripts return error
exit codes.

Fail fast when integration test fixtures cannot be setup.

---

ci/unit_tests.bat

To run unit tests with specific JDKs under Windows OS we have to check for the existence of BUILD_JAVA_HOME. The test logic was inverted

Fix: condition to check environment variable was inverted

---

x-pack/qa/integration/support/helpers.rb

https://github.com/elastic/elasticsearch/pull/56211 removed the ability
to turn off certain features in Elasticsearch. This commit removes
the setting of `xpack.monitoring.enabled`, as this is now
obsolete.

Remove obsolete setting from Elasticsearch integration test

---

docs/static/config-details.asciidoc
docs/static/performance-checklist.asciidoc
docs/static/setting-up-logstash.asciidoc

Change fixed heap size recommendation to a percentage.
Note that large configs may require more stack space
Fixes: #11605 #11842

[Doc]Expand and clarify guidance for jvm settings

---

ci/unit_tests.bat

In batch shell to assign a variable we need `set`

Fix: missed 'set' to assign environment variable and log it

---

.ci/matrix-unix-runtime-javas.yml

This PR removes the Zulu JDKs from Linux from testing matrix

Zulu is Windows's preferred JDK, removed Zulu from Unix JDK matrix

---

logstash-core/lib/logstash/pipeline.rb
logstash-core/spec/logstash/pipeline_pq_file_spec.rb
logstash-core/spec/logstash/util/wrapped_synchronous_queue_spec.rb
logstash-core/src/main/java/org/logstash/ackedqueue/AckedBatch.java
logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
logstash-core/src/main/java/org/logstash/common/LsQueueUtils.java
logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
logstash-core/src/main/java/org/logstash/execution/MemoryReadBatch.java
logstash-core/src/main/java/org/logstash/execution/QueueBatch.java
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java
logstash-core/src/main/java/org/logstash/ext/JrubyAckedReadClientExt.java
logstash-core/src/main/java/org/logstash/ext/JrubyMemoryReadClientExt.java
logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
logstash-core/src/test/java/org/logstash/config/ir/EventConditionTest.java
x-pack/spec/monitoring/inputs/metrics_spec.rb

[7.7 clean backport or #11737] simplify batch classes, do not compute JE empty batches, refactor RE worker loop

---

logstash-core/lib/logstash/util/lazy_singleton.rb
logstash-core/lib/logstash/util/substitution_variables.rb
logstash-core/spec/logstash/settings_spec.rb

Loading a Java Keystore can take anywhere from ~0.3s to upwards of 3s, so the
pattern of loading one per variable we need to replace adds a significant
amount of overhead on pipelines that use these variables, whether or not they
are provided by the keystore.
By providing a private, constant, lazy singleton, we ensure that we don't
incur the cost of repeatedly building the keystore.

performance: share a single secret store (7.7. backport of #10794)

---

Gemfile.jruby-2.5.lock.release

**MERGE ONLY after 7.7 release.**
This bumps ES output dependency on v10.4.2 which includes the authentication validation and `cloud_id` fix. 
Relates to #11830

[7.7] bump elasticsearch output dependency to 10.4.2

---

x-pack/lib/license_checker/license_reader.rb
x-pack/spec/license_checker/license_reader_spec.rb

**MERGE ONLY after 7.7 release.**
This re-applies #11800 and #11818 onto 7.7.

re-introduce ES output authentication validation fix

---

versions.yml

Update the versions of JrJackson and jackson databind to the
latest available versions

[7.7 clean backport of #11844] Update JrJackson and Jackson Databind versions

---

docs/static/advanced-pipeline.asciidoc

Replaces free text with an attribute to help keep content up-to-date and consistent across documents.
**PREVIEW:** http://logstash_11881.docs-preview.app.elstc.co/guide/en/logstash/master/advanced-pipeline.html#indexing-parsed-data-into-elasticsearch
DO NOT MERGE until after https://github.com/elastic/docs/pull/1815 has been merged.

Doc:Replace cloud trial notice with attribute

---

qa/integration/services/kafka_teardown.sh

Kafka teardown script can exit with failure, typically when trying to
stop the broker. This commit logs the error code if the scripts fail
rather than crash out causing build failure.
Fixes #11905

Quieten down kafka teardown script

---

.ci/matrix-unix-compatibility-linux-distros.yml
.ci/matrix-unix-linux-distros.yml
.ci/matrix-windows-compatibility-versions.yml

To be unlinked from infra and made the selection of OSes that Logstash is tested against, the list is moved .ci specific yaml files.
By now the OSes are distinguished by Windows platform and by Linux distributions.

Added OSes definitions files to be used in compatibility test phases

---

qa/integration/services/logstash_service.rb
qa/integration/services/service.rb

Escape test fixture service scripts to avoid test failures when run in
Jenkins using multiple yaml configuration files, which causes directories
to be constructed like `centos-7&&immutable` which cause issues with
the service runners cutting off directory locations before '&&'

Escape test fixture service scripts

---

qa/integration/specs/cli/prepare_offline_pack_spec.rb

The 'prepare_offline_spec.rb' is failing due to a change in the warning message
from JDK11 to JDK14, and JAVA_TOOL_OPTIONS being passed in as an environment
variable by Jenkins, which was not happening before due to the dockerized
environment.

Fix prepare_offline_spec.rb test

---

qa/integration/fixtures/persistent_queues/log4j2.properties

Updated log4j definitions used when FEATURE_FLAG=persistent_queue is used.
Fixes fails 1, 3,4,5 in issue #11924 while the 2 is solved by PR #11923

Fix integration tests related to logs when persistent_queue FEATURE_FLAG is enabled

---

tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LsMetricsMonitor.java

Conversion to seconds of values under 1_000_000_000 nanoseconds translates to value 0, and this led to NaN when used as denominator in a division.
A value of 996_920_400 nanoseconds once converted to seconds is not rounded to 1 second but to 0, this manifest on Windows OS when we read the nanosecond and we expected to wait for 1 second.

Fix: rounded to 1 second in nanos to avoid random NaN error

---

build.gradle
logstash-core/benchmarks/build.gradle
logstash-core/build.gradle
qa/integration/build.gradle
rubyUtils.gradle
x-pack/build.gradle

This commit uses the task avoidance api (tasks.register vs task.create/
task DSL), as recommended since Gradle 5.1
This should reduce the execution of unnecessary tasks in build jobs, and
hopefully improve build resiliency and execution time.
This commit updates the main build.gradle

Use task avoidance API in gradle scripts

---

logstash-core/lib/logstash/modules/logstash_config.rb
modules/netflow/configuration/logstash/netflow.conf.erb
x-pack/modules/azure/configuration/logstash/azure.conf.erb

To test start logstash `bin/logstash --modules netflow`
To test the azure notice you'll need to start an elasticsearch instance on localhost.

emit deprecation entry for netflow and azure modules

---

build.gradle
logstash-core/benchmarks/build.gradle
logstash-core/build.gradle
qa/integration/build.gradle
rubyUtils.gradle
x-pack/build.gradle

7.x backport of #11914
This commit uses the task avoidance api (tasks.register vs task.create/
task DSL), as recommended since Gradle 5.1
This should reduce the execution of unnecessary tasks in build jobs, and
hopefully improve build resiliency and execution time.

[7.x backport] Use task avoidance API in gradle scripts (#11914)

---

qa/integration/services/helpers.sh

Fixture test scripts use `nc` to wait for the port to determine
whether a test fixture is up and running. This commit adds a fall
back option to sleep if `nc` is not available - it is not installed
on Jenkins centos worker nodes.

[Test] Enable fallback to sleep if nc not installed

---

qa/integration/services/logstash_service.rb
qa/integration/services/service.rb

A previous commit attempted to fix this issue by adding `Shellwords.escape` to `setup_script` and `teardown_script` locations, but `File.exists?` returns false when called against a filename escaped by `Shellwords.escape`. This commit localizes the escaping to where the
file is executed.
This commit also adds `Shellwords.escape` to teardown script runner and the method used to execute logstash to retrieve version. This is to enable tests to run correctly when Jenkins creates execution environments with folders named with `&&`, eg `centos-7&&immutable`

[Test] Fix service script execution when path includes `&&`

---

qa/integration/services/filebeat_service.rb

When running filebeats integration tests on centos-7, the tests
fail due to permsisions checks on the temporary configuration file
created for the test. This commit sets strict permissions checks
to false in order for the tests to be able to succeed.

[Test] Set beats permission checking to strict=false

---

qa/integration/services/logstash_service.rb
qa/integration/services/service.rb

Backport of #11944
A previous commit attempted to fix this issue by adding Shellwords.escape to setup_script and teardown_script locations, but File.exists? returns false when called against a filename escaped by Shellwords.escape. This commit localizes the escaping to where the
file is executed.
This commit also adds Shellwords.escape to teardown script runner and the method used to execute logstash to retrieve version. This is to enable tests to run correctly when Jenkins creates execution environments with folders named with &&, eg centos-7&&immutable

[7.x backport] Fix service script execution when path includes `&&`

---

docs/static/settings/configuration-management-settings.asciidoc
docs/static/settings/monitoring-settings-legacy.asciidoc
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/lib/config_management/extension.rb
x-pack/lib/helpers/elasticsearch_options.rb
x-pack/lib/monitoring/internal_pipeline_source.rb
x-pack/lib/monitoring/monitoring.rb
x-pack/lib/template.cfg.erb
x-pack/spec/config_management/elasticsearch_source_spec.rb
x-pack/spec/helpers/elasticsearch_options_spec.rb
x-pack/spec/license_checker/license_reader_spec.rb
x-pack/spec/monitoring/inputs/metrics_spec.rb
x-pack/spec/monitoring/internal_pipeline_source_spec.rb

Add support for api_key authentication in xpack monitoring and management. 
Relates to #11788
TODO

add support for api_key in xpack monitoring and management 

---

logstash-core/lib/logstash/api/commands/stats.rb

Avoid to reassign the subdocument for queue metrics preferring a merge
With PR #10576 the PluginsStats.report(stats) overwrites the subsection related to queue instead of merge with newly created entries.
With the overwriting of `queue` subdocument the HTTP with `extended_stats` return something like 
```json
"queue": {
"type": "persisted",
"events_count": 0,
"queue_size_in_bytes": 1,
"max_queue_size_in_bytes": 1073741824 
}
```
instead of the original form:
```json
"queue": {
"type": "persisted",
"capacity": {
"max_queue_size_in_bytes": 1073741824,
"page_capacity_in_bytes": 67108864,
"queue_size_in_bytes": 1, 
"max_unread_events": 0
},
"events": 0,
"data": {
"path": "/home/andrea/workspace/logstash_andsel/data/queue/main",
"storage_type": "ext4",
"free_space_in_bytes": 57728352256
}
} …
```

Exposed again the pipelines queue.data and queue.capacity subdocuments for _node/stats

---

ci/docker_integration_tests.sh

Some QA tests reads the FEATURE_FLAG environment variable, for example to test PQ functionality.
This PR passthrough the environement variable inside the Docker instance.
To run it locally use:
```
bash> FEATURE_FLAG=persistent_queues ci/docker_integration_tests.sh specs/monitoring_api_spec.rb
```

Pass FEATURE_FLAG as Docker environment variable

---

x-pack/ci/integration_tests.sh

JDK xpack integration tests not using docker images are failing, as latest versions of Elasticsearch require java 11+ to run, whereas the default java on the worker nodes is java 8. 
This commit sets `JAVA_HOME` to be the same as `BUILD_JAVA_HOME` to mimic likely scenarios where elasticsearch and logstash use the same installed version of Java.

Set `JAVA_HOME` to `BUILD_JAVA_HOME` in xpack integration tests

---

.ci/matrix-windows-runtime-javas.yml

openjdk14 appears to be the only version of java14 installed on jenkins windows
worker nodes, so use this instead of zulu14 and adoptopenjdk14

Add openjdk14 to windows build matrix

---

docs/static/settings/monitoring-settings-legacy.asciidoc

This PR is document the work done in #11799 to expose the `proxy` setting when Logstash and monitoring Elasticsearch cluster are separated by a forward proxy.

[Doc] added description of xpack.monitoring.elasticsearch.proxy

---

docs/static/configuration.asciidoc

This PR is intended to try to describe better the behavior of `in` operator used in conditionals inside pipeline configurations. It translates to Ruby's `include?` method and in some cases could not be clear that it does an exact match (like in collections) or a regexp match (like substring in a string)

[Doc] better specification of the behaviour of in operator in various contexts

---

.ci/matrix-runtime-javas.yml

This adds the .ci/matrix-runtime-javas.yml file that defines all
the JDKs logstash could be tested against. This is meant to be
used for the Matrix Combinations Jenkins plugin to be able to
select which JDK to test against dynamically.

Adds matrix-runtime-javas.yml

---

.ci/matrix-runtime-javas.yml

This adds the .ci/matrix-runtime-javas.yml file that defines all
the JDKs logstash could be tested against. This is meant to be
used for the Matrix Combinations Jenkins plugin to be able to
select which JDK to test against dynamically.

Backport: Adds matrix-runtime-javas.yml

---

qa/integration/services/logstash_service.rb
qa/integration/services/service.rb

Backport of #11944
A previous commit attempted to fix this issue by adding Shellwords.escape to setup_script and teardown_script locations, but File.exists? returns false when called against a filename escaped by Shellwords.escape. This commit localizes the escaping to where the
file is executed.
This commit also adds Shellwords.escape to teardown script runner and the method used to execute logstash to retrieve version. This is to enable tests to run correctly when Jenkins creates execution environments with folders named with &&, eg centos-7&&immutable

[7.8 backport] Fix service script execution when path includes `&&`

---

qa/integration/services/helpers.sh

Try system ruby, then LS_HOME/bin/ruby, then relative path from
script to LS_HOME/bin/ruby. Use LS_RUBY_HOME variable to avoid
testing again on subsequent attempts to wait for port.

Give more options for testing with ruby while waiting for port

---

qa/integration/services/logstash_service.rb

Backport of #11931
Escape test fixture service scripts to avoid test failures when run in
Jenkins using multiple yaml configuration files, which causes directories
to be constructed like `centos-7&&immutable` which cause issues with
the service runners cutting off directory locations before '&&'
This commit deviates from the original commit by not setting @setup_script
and @teardown_script variable with the Shellwords escape, as this was removed
in a subsequent commit (#11944)

[7x backport] Escape test fixture service scripts

---

logstash-core/lib/logstash/api/commands/stats.rb

This is a backport PR of #11923 to `7.8` to fix `_node/stats` JSON response

Expose again the pipelines queue.data and queue.capacity subdocument

---

logstash-core/build.gradle

Historically we haven't upgraded from 1.1 since newer versions depended on javac-shaded which is gpl-2.0.
[google-java-format 1.8](https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format/1.8) drops this dependency.

upgrade google-java-format to 1.8

---

logstash-core/lib/logstash/plugins/registry.rb

ruby produces a LocalJumpError: unexpected return
error if there's a return in a block so this changes just uses
the value of the last expression as the value of the block

remove explicit return from Mutex#synchronize in Plugin Registry

---

logstash-core/build.gradle

This reverts commit 2229468f112134b1c7d6102e989e0c0ef057c74f.
google-java-format 1.8 is Java 11 only, so we can't use it as Logstash is supported on Java 8.

Revert "upgrade google-java-format to 1.8"

---

docs/index.asciidoc
docs/static/life-of-an-event.asciidoc
docs/static/processing-info.asciidoc

Important info that customers need can be buried way down in the details. This PR adds a section for bubbling up and curating that information.
Replaces #11581 
**PREVIEW:** http://logstash_11715.docs-preview.app.elstc.co/guide/en/logstash/master/processing.html

[Doc]Add section for conceptual info

---

build.gradle
qa/integration/services/filebeat_service.rb
qa/integration/services/filebeat_setup.sh
qa/integration/specs/beats_input_spec.rb

This commit changes the download to pull the version of beats based on the version pulled from the branch rather than from an environment variable, or `6.5.4`.
This commit moves the download logic of Filebeat from`filebeat_setup.sh` to `build.gradle` in order to use the artifacts API in the same way as the `downloadEs` task, and does some refactoring to DRY up the artifact download tasks.
This commit also fixes the beats integration test to replace the use of a removed setting.

Retrieve branch version of Filebeat via gradle

---

logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java

`PipelineConfig.equals` was calling `Settings#eql` but should be using `Settings#equals` which wires on the overloaded `Settings#==` method. 
The symptom was that when pipeline reloading was triggered, the pipeline would always be reloaded regardless if it changed or not.

fix Settings equality test which broke the PipelineConfig equality

---

Dockerfile

fixes temporary network failures like https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-pq-2/1648/console

retry on failed gradlew wrapper command in Dockerfile

---

build.gradle
qa/integration/services/filebeat_service.rb
qa/integration/services/filebeat_setup.sh
qa/integration/specs/beats_input_spec.rb

Clean backport of #11958
This commit changes the download to pull the version of beats based on the version pulled from the branch rather than from an environment variable, or 6.5.4.
This commit also moves the download logic of Filebeat fromfilebeat_setup.sh to build.gradle in order to use the artifacts API in the same way as the downloadEs task, and does some refactoring to DRY up the artifact download tasks.
This commit also fixes the beats integration test to replace the use of a removed setting.
This commit also sets retries to 3 for the download tasks, using 'retries' functionality from gradle download task plugin

[7x_backport] Retrieve branch version of Filebeat via gradle

---

qa/integration/specs/reload_config_spec.rb
rakelib/default_plugins.rb
rakelib/modules.rake

JSON.load allows the creation of complex objects, and should not
be given untrusted input. This commit changes the only three uses
of JSON.load in the codebase. These aren't user facing or present
in bundled product therefore not really an attack vector, so this is just
a cleanup to establish this best practice.

remove uses of JSON.load in favor or JSON.parse

---

build.gradle
qa/integration/services/elasticsearch_setup.sh
qa/integration/services/elasticsearch_teardown.sh
qa/integration/specs/dlq_spec.rb
qa/integration/specs/es_output_how_spec.rb
qa/integration/specs/spec_helper.rb

Carrying on from the work done in #11958, update the gradle build to download the same version of Elasticsearch as is specified in the logstash version.yml file.
This commit updates the standard integration tests to use the same version of Elasticsearch that is already downloaded for x-pack integration tests, and also fixes integration tests to allow for the different responses around hits generated by different versions of Elasticsearch.

Use branch appropriate version of Elasticsearch

---

build.gradle

Enable filebeat and elasticsearch downloads to pull different
architectures, Filebeat and Elasticsearch use different suffixes
to denote their aarch64 architectures, with beats using arm64 and
elasticsearch aarch64

Tests: Add support for alternative architectures

---

docs/gs-index.asciidoc
docs/static/docker.asciidoc
docs/static/getting-started-with-logstash.asciidoc
docs/static/management/centralized-pipelines.asciidoc
docs/static/management/configuring-centralized-pipelines.asciidoc
docs/static/setup/setting-up-xpack.asciidoc

Related to https://github.com/elastic/docs/pull/1870
This PR removes out-dated links to the Stack Overview, which is no longer used.
https://logstash_12025.docs-preview.app.elstc.co/diff

[DOCS] Fixes Stack Overview links

---

tools/release/generate_release_notes.rb

Backport of #11508 to convert links from Markdown to AsciiDoctor while generating
release notes.

[7x_backport] Add link conversion from Markdown to AsciiDoctor (#11508)

---

config/log4j2.properties
logstash-core/build.gradle

Having the jar around would allow us to fine tune logging for libraries
such as manticore's http-client (4.5) using LS's `log4j2.properties`
e.g.
```
logger.http_headers.name = org.apache.http.headers
logger.http_headers.level = DEBUG
```
... to log http headers for each request : 
```
[2020-04-30T14:17:42,977][DEBUG][org.apache.http.headers  ][main][920ea2400ec23952b1af206783db2c10e025c753ac595bfe3fc0947d9e065bb6] http-outgoing-0 >> POST /_bulk HTTP/1.1
[2020-04-30T14:17:42,978][DEBUG][org.apache.http.headers  ][main][920ea2400ec23952b1af206783db2c10e025c753ac595bfe3fc0947d9e065bb6] http-outgoing-1 >> POST /_bulk HTTP/1.1
[2020-04-30T14:17:42,984][DEBUG][org.apache.http.headers  ][main][920ea2400ec23952b1af206783db2c10e025c753ac595bfe3fc0947d9e065bb6] http-outgoing-0 >> Connection: …
```

Feat: ship log4j2 commons-logging bridge with LS

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
logstash-core/src/test/java/org/logstash/config/ir/IRHelpers.java
logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline1.conf
logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline2.conf

Fixes #12031 
This PR fixes the regression introduced in 7.7.0 where the plugin id was set in the thread context  by hard coding the unique plugin id in the generated class resulting in generating non cacheable classes that all contained a unique id. 
The fix is to dynamically get the plugin id from the plugin instance field which result in non-unique generated code and thus allowing the reuse of equivalent generated classes. 
- Before this PR the generated filter and output classes would contain code similar to 
```
org.apache.logging.log4j.ThreadContext.put("plugin.id", "ce80c1c692c7fd1664e67aa37b9b5ee8f6d7fa336b22bad5b14684ca44132adc");
```
- This PR make that code be like:
```
org.apache.logging.log4j.ThreadContext.put("plugin.id", field1.getId().toString());
```

dynamically get the plugin id instead of hardcoding it in the generated classes

---

logstash-core/lib/logstash/util/substitution_variables.rb
logstash-core/spec/logstash/config/mixin_spec.rb

Clean backport to 7.x of #11774

support Env+Keystore substitutions in password-type plugin options (7.x backport)

---

logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java

Backport #12009 to 7.x branch, bugfix in pipeline reload
fix Settings equality test which broke the PipelineConfig equality

Backport #12009 to 7.x branch, bugfix in pipeline reload

---

logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline1.conf
logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline2.conf

This change forces the test to check that compiling a pipeline twice but with different ids doesn't produce more classes.
@andsel I know you wrote this recently, but I ended up doing this refactor as I prepare to add new tests for the speed improvement in https://github.com/elastic/logstash/pull/12047

narrow scope of testCacheCompiledClassesWithDifferentId

---

docs/static/cross-plugin-concepts.asciidoc
docs/static/plugin-manager.asciidoc
logstash-core/lib/logstash/config/mixin.rb
logstash-core/lib/logstash/util/safe_uri.rb
logstash-core/spec/logstash/config/mixin_spec.rb

Since whitespace is illegal in URIs, we can safely use it as a delimiter when
validating `list`-type `URI` params, enabling the expansion of an arbitrary
list of URIs from a single Environment- or Keystore-variable.
TODO:
Resolves: https://github.com/elastic/logstash/issues/8157
Resolves: https://github.com/elastic/logstash/issues/6366

plugin config: support space-deliminated URIs on list-type params

---

logstash-core/lib/logstash/agent.rb
x-pack/lib/monitoring/internal_pipeline_source.rb

This removes the call to `converge_state_and_update` from `InternalPipelineSource` where it was done from the `after_agent` event which means before `agent#execute` which is useless.
This code is **extremely** hard to understand and follow so I will need a second pair of eyes from someone with experience in this code to make sure I haven't overlooked anything. In particular I had to disable the related specs and I am not sure how valid these were in the first place and actually testing for the right thing.

do not call agent.converge_state_and_update before agent.execute

---

qa/integration/services/elasticsearch_teardown.sh

Integration tests may fail during elasticsearch teardown, as currently
the stop_es function sends a `SIGTERM` to Elasticsearch, but does not
wait for the process to exit. That can lead to issues when deleting
data directories from a still running process. This commit adds
wait functionality to `stop_es` to wait for a short period of time,
sending a `SIGKILL` if Elasticsearch does not terminate in time.

Add wait functionality to `stop_es` integration test helper function

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
logstash-core/src/main/java/org/logstash/config/ir/compiler/VariableDefinition.java
logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline_reuse_baseline.conf
logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline_reuse_test.conf

Continuing from https://github.com/elastic/logstash/pull/12047.
Also adds with a new `testReuseCompiledClasses` that tests the tremendous save in class generation, and fixes `compilerBenchmark` since compilation can now easily be sub second.
> Generated implementations of `BaseDataset` often have fields referencing
> other specifically-generated `BaseDataset`, despite only using public methods
> defined on the `BaseDataset` abstract class.
> 
> By allowing the code generation to reference the abstract class instead of
> the specific implementation, we eliminate the need for the compiler to chain
> parent class loaders indefinitely, thereby eliminating the need for a global
> mutual exclusion when compiling.
> 
> This chage moves the locking semantics from the compiler to the non-evicting …

JEE: nix global compiler lock by normalizing to Dataset interface #12047

---

logstash-core/spec/logstash/java_pipeline_spec.rb

This test relies on the generator input sending 10 events and observing
the output. Calling shutdown immediately after start can cause the
plugin to abort earily.
This change waits for the execution to finish before performing the
test assertions.
This fixes tests failures such as https://logstash-ci.elastic.co/job/elastic+logstash+7.x+multijob--ruby-unit-tests/312/console:
```
21:37:10       1) LogStash::JavaPipeline with multiple outputs correctly distributes events
21:37:10          Failure/Error: expect(output.events.size).to eq(60)
21:37:10          
21:37:10            expected: 60
21:37:10                 got: 0
21:37:10          
21:37:10            (compared using ==)
21:37:10          # ./logstash-core/spec/logstash/java_pipeline_spec.rb:907:in `block in <main>'
21:37:10 …
```

ensure pipeline terminates execution before doing assertion

---

logstash-core/spec/logstash/pipeline_spec.rb

this test only called "pipeline.start" and expected an output to receive
the "do_close" method call. Therefore it relies on a race condition that
the pipeline shuts down quickly enough, which could fail.
This change ensures the pipeline fully terminated before making the
assertion
Fixes test failures such as https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob--ruby-unit-tests/334/console:
```
21:36:04       1) LogStash::Pipeline close output close should call close of output without output-workers
21:36:04          Failure/Error: expect(output).to have_received(:do_close).once
21:36:04          
21:36:04            (#<LogStash::OutputDelegator:0x34a0c4ad>).do_close(*(any args))
21:36:04                expected: 1 time with any arguments
21:36:04                received: 0 …
```

fix pipeline spec that didn't wait for pipeline to terminate

---

qa/integration/services/elasticsearch_teardown.sh

Integration tests may fail during elasticsearch teardown, as currently
the stop_es function sends a `SIGTERM` to Elasticsearch, but does not
wait for the process to exit. That can lead to issues when deleting
data directories from a still running process. This commit adds
wait functionality to `stop_es` to wait for a short period of time,
sending a `SIGKILL` if Elasticsearch does not terminate in time.
Clean backport of #12061

[7x backport]  Add wait functionality to `stop_es` integration test helper function

---

logstash-core/spec/logstash/agent_spec.rb
logstash-core/spec/logstash/pipeline_pq_file_spec.rb
logstash-core/spec/logstash/queue_factory_spec.rb
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java

Many DLQ and PQ tests are run with default settings for their size, or otherwise set to values such as 1GB.
This means that the container/machine the test runs on needs a lot of disk space (1GB for the test + 1GB for OS and Logstash + some more free space).
This PR reduces the disk space needed at any time for these tests, which helps the windows tests pass as we see here: https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-windows-compatibility/170/ (this test suite has been failing for a month since windows workers don't have a lot of disk space)

make PQ and DLQ tests use less space

---

qa/integration/services/elasticsearch_teardown.sh

Integration tests may fail during elasticsearch teardown, as currently
the stop_es function sends a `SIGTERM` to Elasticsearch, but does not
wait for the process to exit. That can lead to issues when deleting
data directories from a still running process. This commit adds
wait functionality to `stop_es` to wait for a short period of time,
sending a `SIGKILL` if Elasticsearch does not terminate in time.
Clean backport of #12061

[78 bp] Add wait to`stop_es` integration test helper function

---

tools/benchmark-cli/build.gradle

Updated elasticsearch only to 5.6.16 as 6.x introduced a deprecation in
the performRequest method and needs further refactor

update benchmark-cli dependencies

---

logstash-core/lib/logstash/runner.rb

This makes reading the logs much easier to the eye. Instead of logging it after a warning:
```
❯ bin/logstash -e "" 
Sending Logstash logs to /Users/joaoduarte/elastic/logstash/logs which is now configured via log4j2.properties
[2020-07-03T17:47:35,972][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2020-07-03T17:47:36,097][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"8.0.0", "jruby.version"=>"jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11.0.5+10 on 11.0.5+10 +indy +jit [darwin-x86_64]"}
```
We now see:
```
❯ bin/logstash -e "" 
Sending Logstash logs to /Users/joaoduarte/elastic/logstash/logs which is now configured via log4j2.properties …
```

ensure 'starting logstash' log entry happens first

---

docs/static/troubleshooting.asciidoc
rubyUtils.gradle
versions.yml

Also tweak the documentation since most of the add-opens are no longer needed, except two:
* java.io due to https://github.com/colinsurprenant/jruby-stdin-channel/issues/1
* java.security due to jruby-openssl

bump jruby to 9.2.12.0

---

qa/integration/services/elasticsearch_setup.sh

This commit clears the `JAVA_HOME` variable when starting Elasticsearch
to force it to use the bundled version of the JDK, rather than the
default `JAVA_HOME` from the machine Logstash integration tests are being
run on, and removes the likelihood of tests failing to run due to `JAVA_HOME`
being set to a non-compliant JDK.

[Build] Clear `JAVA_HOME` to use bundled JDK for Elasticsearch

---

docs/static/advanced-pipeline.asciidoc
docs/static/fb-ls-kafka-example.asciidoc
docs/static/monitoring/monitoring-mb.asciidoc

Updates links to reflect changes added in elastic/beats#19302.
This change applies to 7.9 and later.

[DOCS] Change links to refactored Beats getting started docs

---

tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/amazing_print-NOTICE.txt

fixes the license check test currently failing in master. This dependency is brought by the new release of the logstash-codec-rubydebug that dropped the awesome_print library in favor of amazing_print.

add dependency notice for amazing_print

---

build.gradle

Inadvertent extra character causes aarch64 builds to fail.

[build] Fix gradle typo

---

qa/integration/services/kafka_setup.sh
qa/integration/specs/kafka_input_spec.rb

This commit updates the kafka setup scripts to ensure that the kafka setup is clean between builds, by
setting an explicit zookeeper data directory to be cleaned each time, and correctly overriding `log.dirs`
instead of `log.dir` to ensure that the kafka logs are written and wiped in a consistent place each time,
which helps when using the non-immutable images used in arm64 tests.

Fix kafka setup scripts

---

build.gradle
x-pack/build.gradle

Release Manager builds were failing as `downloadEs` task was being
needlessly run during `rake artifact:all` task. When run with
`RELEASE=1`. this was causing build failures due to the non-availability
of Elasticsearch release artifacts. This commit aims to avoid running
the `downloadES` task when it is not needed, continuing the work done
in #11914
This commit also removes code that was repeated in different parts of
the build script.

[build] Ensure more gradle tasks using task avoidance API

---

logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/java_pipeline.rb
logstash-core/lib/logstash/pipeline.rb
logstash-core/lib/logstash/pipelines_registry.rb
logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/spec/logstash/pipelines_registry_spec.rb
logstash-core/spec/support/matchers.rb
logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java

Relates to #12005 and fixes the issues in (2).
Should fix #10611
This PR fixes the following issues:
- A pipeline in the process of being created was not marked as such in the pipeline registry resulting in a situation where a slow to initialize pipeline would be recreated on state convergence resulting in a PQ `LockException` because that pipeline was already existing and held the PQ lock. 
- The worker threads were not correctly monitored for a worker loop exception resulting in a complete logstash crash upon any exception even when multiple pipelines are running. Now only the failed pipeline is terminated. If pipeline reloading is enabled, it is possible to edit the config and have that failed pipeline reloaded.

Fix pipeline state logic and worker thread error handling

---

x-pack/lib/helpers/elasticsearch_options.rb
x-pack/spec/config_management/elasticsearch_source_spec.rb
x-pack/spec/helpers/elasticsearch_options_spec.rb

This fixes a regression introduced with the api_key support for xpack monitoring and management in #11864 which disabled the possibility to not use any authentication by relying on the default options and only enabling monitoring for example. 
This PR now ignores the default `username` option when no password is explicitly set.

ignore default username when no password is set to not use authentication in xpack monitoring and management

---

build.gradle

This is a temporary fix.
Currently the check task depends on the integrationt tests task,
which means all dependant tasks will be resolved even if they're just
registered instead of created.
This resolution is a problem because the downloadES task will fail
if, for the version we're building, Elasticsearch doesn't yet have a
build we can download.
Evaluating the task results in the following failure, taken from the 7.x (now 7.10.0) branch:
```
❯ ./gradlew bootstrap
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.5.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
FAILURE: Build failed with an exception.
* Where:
Build file …
```

don't call runIntegrationTests from check gradle task

---

ci/bootstrap_dependencies.sh

This script can be useful for preparing the environment for services like code scanners.

add ci script setup dependencies

---

docs/static/releasenotes.asciidoc

Tag release notes with a "Coming in..." tag. 
Tag will be removed after release. 
**PREVIEW:** https://logstash_12118.docs-preview.app.elstc.co/guide/en/logstash/current/logstash-7-8-1.html

Doc:Add coming tag to 7.8.1 release notes

---

docs/include/plugin_header-integration.asciidoc

Integration plugin repos have different configurations and requirements from traditional plugins. This PR creates an plugin header file more appropriate for integrations. 
To test:
1. Check out this PR (as usual). 
2. Check out this [test PR #882](https://github.com/elastic/logstash-docs/pull/882) for `logstash-docs`. 
3. Build docs locally: `docbldlsx --open`
Next steps (@karenzone):

[Doc]Add a new header for integration plugins

---

docs/static/settings-file.asciidoc

Tested with a keystore secret called "secret"
```
/tmp/logstash-7.8.0
❯ bin/logstash-keystore list     
secret
```
And a pipelines.yml that has a pipeline uses both a keystore secret and an environment variable:
```yml
- pipeline.id: test
pipeline.workers: 1
pipeline.batch.size: 1
config.string: "input { generator { count => 1 message => \"${ENV_VAR}\"} } filter { mutate { add_field => { \"secret\" => \"${SECRET}\"} } } output { stdout { codec => rubydebug } }"
```
```
/tmp/logstash-7.8.0 ❯ ENV_VAR=enviroment bin/logstash
[2020-07-22T16:40:36,945][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.8.0", "jruby.version"=>"jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11.0.5+10 on 11.0.5+10 +indy +jit [darwin-x86_64]"} …
```

Document use of keystore values in pipelines.yml

---

docker/Makefile
docker/templates/Dockerfile.j2

Prior to this commit, the value of `org.label-schema.license` and
the values in `org.opencontainers.image.*` were not set, and therefore
would be inherited from the base OS image.

Fix docker image labels

---

bin/system-install

Present OPTIONSFILE search in a way that reads first-match-wins, since that is
what actually happens.
Resolves: #12145

reword bin/system_install help text to be less confusing.

---

docs/static/security/logstash.asciidoc

Replaces the link to monitoring with APIs with a more appropriate monitoring link. 
**PREVIEW:**  https://logstash_11960.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#ls-monitoring-user

Doc:Fix link to monitoring docs

---

docker/data/logstash/env2yaml/env2yaml.go

In PR #11799 we missed to add the exposure of proxy also as docker env variable so that uses can connect the dockerzied Logstash to a proxed monitoring cluster

Expose xpack.monitoring.elasticsearch.proxy setting as Docker env varible

---

docs/static/security/api-keys.asciidoc
docs/static/settings/configuration-management-settings.asciidoc

Logstash monitoring and management features support API keys with 7.9.
Related: #11864  
**Preview:** https://logstash_12149.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#ls-api-keys

Doc:Add monitoring and management to API key security content

---

ci/docker_acceptance_tests.sh
docker/Makefile
qa/Gemfile
qa/docker/fixtures/custom_logstash_yml/logstash.yml
qa/docker/fixtures/multiple_pipelines/config/pipelines.yml
qa/docker/fixtures/multiple_pipelines/pipelines/basic1.cfg
qa/docker/fixtures/multiple_pipelines/pipelines/basic2.cfg
qa/docker/fixtures/simple_pipeline/basic.cfg
qa/docker/shared_examples/container.rb
qa/docker/shared_examples/container_config.rb
qa/docker/shared_examples/container_options.rb
qa/docker/shared_examples/image_metadata.rb
qa/docker/spec/full/container_spec.rb
qa/docker/spec/full/image_spec.rb
qa/docker/spec/oss/container_spec.rb
qa/docker/spec/oss/image_spec.rb
qa/docker/spec/spec_helper.rb
rakelib/artifacts.rake

Clean backport of #12135
This commit adds integration tests for the Logstash docker images. Previous
integration tests were removed in https://github.com/elastic/logstash/pull/10693,
due to the tests being non functional.
The commit adds image and container tests. The image tests check the contents and the
metadata of the image; the container tests check the logstash process, and includes tests
ensuring that logstash runs, and is configurable.
This test also adds a ci script to allow the tests to be run on jenkins, and to split the
running of these tests up based on the image type and includes updates to the rake tasks to
support this.

7x Introduce integration tests for docker images

---

docs/static/security/logstash.asciidoc

Corrects monitoring settings by adding the `xpack.` prefix.
**PREVIEW:** https://logstash_12153.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#ls-monitoring-user

Doc:Fix name of monitoring settings

---

x-pack/spec/license_checker/license_reader_spec.rb

Accidentally succeeding at connecting to an HTTP resource that is not a real,
live Elasticsearch (such as an Elastic Cloud instance that has been shut down
and reaped) can cause client initialization to fail.

specs: don't start ES connection pool when only validating config

---

rubyUtils.gradle
versions.yml

Note: this is to be merged now to: master and 7.x, and then backported to 7.9 once 7.9.0 is released.

bump jruby to 9.2.13.0

---

docs/include/plugin_header-integration.asciidoc

Made some tweaks so that links make sense in context. For example, when you click "integration" from the plugin, you get the integration.   When you click "other versions" from an input, output, or filter, it makes sense to link to other versions of the individual plugin--not back to the integration. 
To test:
1.  Check out this PR (as usual).
2.  Check out this test [PR #890](https://github.com/elastic/logstash-docs/pull/890) for logstash-docs.
3.  Build docs locally: docbldlsx --open
NOTE: When you're checking links, be sure to navigate from the Table of Contents on the right.  If you're not careful, you will leave your local build `http://localhost:8000/guide` and be clicking live links.
Follow-up to #11891

Doc:Adjust link for integration plugin header file

---

tools/release/bump_plugin_versions.rb

* use the `clean installDefaultGems` gradle tasks instead of `rake artifact:tar`
* terminate the script early if `--no-pr` flag is passed on the command line

allow skipping pr creation in version bump script

---

logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java

Our internal representation of the composite config file needs only to inject
newline delimiters if they are missing, and to avoid doing so if they are
present. This allows `PipelineConfig#sourceReferences()`, used to map back from
the composite line/column to source file/column, to correctly track an offset
using the source fragments `SourceWithMetadata#getLinesCount()`.
Resolves: #12155 
Separately, this change-set contains separate commits for:
- refactoring a test to avoid verbatim copy/paste of the implementation we are testing against
- fixes a failed attempt to memoize the `PipelineConfig#configString()` that was _generating_ the composite config at every invocation and storing it to never be accessed.

Fix: allow trailing newlines in config fragments

---

docs/static/releasenotes.asciidoc

Started with generated release notes #12171. Then lots of cleanup happened. 
**PREVIEW:** https://logstash_12179.docs-preview.app.elstc.co/guide/en/logstash/7.9/logstash-7-9-0.html

Release notes 7.9.0 

---

ci/docker_acceptance_tests.sh
docker/Makefile
docker/templates/Dockerfile.j2
qa/docker/shared_examples/xpack.rb
qa/docker/spec/full/container_spec.rb
qa/docker/spec/ubi8/container_spec.rb
qa/docker/spec/ubi8/image_spec.rb
rakelib/artifacts.rake

This commit adds the rake docker_ubi8 rake task, and associated
changes to the docker template and makefiles.
This commit also refactors the acceptance tests to extract xpack tests
into a helper class to allow the same tests to be used in both 'full'
and 'ubi8' docker image tests

Add UBI8 docker image to artifacts

---

config/logstash.yml
docker/data/logstash/env2yaml/env2yaml.go

Follow up of #12151 
Additionally, fix .yml sample config to include proxy setting.

Docker: Expose xpack.management.elasticsearch.proxy

---

config/logstash.yml
docker/data/logstash/env2yaml/env2yaml.go

Expose the proxy xpack management proxy setting in docker (xpack.management.elasticsearch.proxy).
Also surface the same proxy setting in the sample config.
Backport: 0d82bc064ca8184722d159e3e8036ffe1931e666
Original PR: https://github.com/elastic/logstash/pull/12201

[backport] Docker: Expose xpack.management.elasticsearch.proxy

---

docker/Makefile

This commit fixes a typo in the name of the docker build context for ubi8 images.
Related to #12181

fix ubi8  docker build context

---

logstash-core/spec/logstash/java_pipeline_spec.rb
logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java

Fixes #12158
Reboot of #12196
When running a pipeline with ordered execution, flushes on the pipeline
were no longer being called when compute is called with an empty batch, causing
issues with the aggregate filter, for example, not being able to push events on
timeout.
This fix checks if the batch is empty and if a flush is required in which case compute on an empty batch is called for a flush operation to happen.

fix flushing upon empty batches with ordered execution

---

docs/static/redirects.asciidoc

The functionality in the `multiline filter plugin` has been replaced by `multiline codec plugin` and/or Filebeat. The original page results in a 404.  This PR is intended to provide users with more helpful info and point them toward alternatives.  
**PREVIEW:**  https://logstash_12208.docs-preview.app.elstc.co/guide/en/logstash/master/plugins-filters-multiline.html
Note: The new page will be hidden, but available if a user clicks a link that targets the page that was removed.

Doc:Add redirect from multiline filter to multiline codec

---

logstash-core/lib/logstash/api/app_helpers.rb
logstash-core/lib/logstash/util.rb
qa/integration/specs/reload_config_spec.rb

Fix to implement the blank? method that doesn't exists for String, is added by Rails framework

Fix to implement the blank? method that doesn't exists for String

---

logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
logstash-core/src/test/java/org/logstash/secret/store/backend/JavaKeyStoreTest.java

This commit is intended to fix thread safety issues with the  JavaKeystore implementation of the secret store.
From reading the code, it appears that thread safety for the keystore was intended to be provided by
a ReentrantReadWriteLock, a read lock for accessing secrets from the keystore, and a write lock for updating
secrets in the keystore.
In practice, this was insufficient, the act of accessing a secret from the keystore involved the mutation of
a shared keyStore object - the keyStore is `load`ed every time a secret is retrieved from the store.
Previous to https://github.com/elastic/logstash/pull/10794, this did not matter, each pipeline held its
own instance of the secret store, effectively meaning that only a single thread would ever access a key
store at any one time. This PR …

Fix keystore thread safety

---

logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
logstash-core/src/test/java/org/logstash/secret/store/backend/JavaKeyStoreTest.java

Clean backport of #12233 
This commit is intended to fix thread safety issues with the  JavaKeystore implementation of the secret store.
From reading the code, it appears that thread safety for the keystore was intended to be provided by
a ReentrantReadWriteLock, a read lock for accessing secrets from the keystore, and a write lock for updating
secrets in the keystore.
In practice, this was insufficient, the act of accessing a secret from the keystore involved the mutation of
a shared keyStore object - the keyStore is `load`ed every time a secret is retrieved from the store.
Previous to https://github.com/elastic/logstash/pull/10794, this did not matter, each pipeline held its
own instance of the secret store, effectively meaning that only a single thread would ever access a key
store at …

7x backport Fix keystore thread safety (backport #12233)

---

logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
logstash-core/src/test/java/org/logstash/secret/store/backend/JavaKeyStoreTest.java

Clean backport of #12233
This commit is intended to fix thread safety issues with the  JavaKeystore implementation of the secret store.
From reading the code, it appears that thread safety for the keystore was intended to be provided by
a ReentrantReadWriteLock, a read lock for accessing secrets from the keystore, and a write lock for updating
secrets in the keystore.
In practice, this was insufficient, the act of accessing a secret from the keystore involved the mutation of
a shared keyStore object - the keyStore is `load`ed every time a secret is retrieved from the store.
Previous to https://github.com/elastic/logstash/pull/10794, this did not matter, each pipeline held its
own instance of the secret store, effectively meaning that only a single thread would ever access a key
store at …

[7.9 backport]  Fix keystore thread safety (#12233)

---

logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
logstash-core/src/test/java/org/logstash/secret/store/backend/JavaKeyStoreTest.java

Clean backport of #12233
This commit is intended to fix thread safety issues with the  JavaKeystore implementation of the secret store.
From reading the code, it appears that thread safety for the keystore was intended to be provided by
a ReentrantReadWriteLock, a read lock for accessing secrets from the keystore, and a write lock for updating
secrets in the keystore.
In practice, this was insufficient, the act of accessing a secret from the keystore involved the mutation of
a shared keyStore object - the keyStore is `load`ed every time a secret is retrieved from the store.
Previous to https://github.com/elastic/logstash/pull/10794, this did not matter, each pipeline held its
own instance of the secret store, effectively meaning that only a single thread would ever access a key
store at …

[6.8 backport] Fix keystore thread safety (#12233)

---

docker/templates/Dockerfile.j2
qa/docker/shared_examples/container.rb
qa/docker/shared_examples/image_metadata.rb

This commit includes the required changes to pass RedHat docker image certification.
This includes:
Moving license files to /licenses folder
Adding required base labels for name, description, vendor and summary
Relates: https://github.com/elastic/dev/issues/1287

Fix docker image certification

---

docs/static/troubleshooting.asciidoc

Logging settings can affect performances
Backports #12246 to 7.9 branch

[DOC][Backport-7.9] Logging settings can affect performances

---

tools/dependencies-report/src/main/resources/licenseMapping.csv
tools/dependencies-report/src/main/resources/notices/elastic-app-search-NOTICE.txt
tools/dependencies-report/src/main/resources/notices/jwt-NOTICE.txt

Fixed license after logstash-output-elastic_app_search plugin switched from Java library to Ruby

Added elastic-app-search and jwt license definition and notices

---

bin/logstash
bin/logstash.lib.sh
bin/setup.bat
bin/system-install
build.gradle
docker/templates/Dockerfile.j2
qa/acceptance/spec/lib/artifact_operation_spec.rb
qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
qa/acceptance/spec/shared_examples/installed_with_jdk.rb
qa/docker/shared_examples/container.rb
qa/docker/spec/spec_helper.rb
qa/integration/specs/cli/prepare_offline_pack_spec.rb
qa/rspec/commands.rb
qa/rspec/commands/base.rb
qa/rspec/commands/debian.rb
qa/rspec/commands/redhat.rb
qa/rspec/commands/suse.rb
qa/rspec/commands/system_helpers.rb
qa/rspec/matchers/be_running.rb
rakelib/artifacts.rake
versions.yml

This PR add the bundling of JDK to existing artifacts tasks
The artifacts are:
- Linux distribution's packages: `deb/rpm`
- normal packages `tar.gz` (Linux, MacOS) `.zip` for windows
- Docker images
The JDK to bundle is configured in `versions.yml` file, and are the same for all platform (AdoptOpenJDK 11)
The launch scripts has changed with the following meaning, in case of a bundled package:
use the JVM provided by JAVA_HOME if set, warning the user that he is using a bundled package. If not set use the bundled one if present. As last resource (only on *nix platforms) check for other java with `command -v java`, if no JVM is present quit with error.
On DEB package with JDK bundled removes the dependency on a Java DEB.
----
This PR bring an effort from @robbavey  and proposes changes to …

Download JDK and create distribution artifacts with JDK

---

docs/static/offline-plugins.asciidoc
docs/static/plugin-manager.asciidoc

Elevates visibility of **Offline Plugin Management** section so that air gapped users don't have to struggle through instructions that require an internet connection. 
Related: #12280
**PREVIEW:** https://logstash_12283.docs-preview.app.elstc.co/guide/en/logstash/master/working-with-plugins.html

[Doc] Increase visibility of offline plugin support

---

docs/static/offline-plugins.asciidoc
docs/static/plugin-manager.asciidoc

Elevates visibility of Offline Plugin Management section so that air gapped users 
don't have to struggle through instructions that require an internet connection.
Backports:  #12283
Related: #12280

[Backport to 7.x]Doc: Increase visibility of offline plugin support

---

docs/static/offline-plugins.asciidoc
docs/static/plugin-manager.asciidoc

Elevates visibility of Offline Plugin Management section so that air gapped users 
don't have to struggle through instructions that require an internet connection.
Related: #12280
Backports:  #12283

[Backport to 7.9]Doc:Increase visibility of offline plugin support

---

build.gradle
qa/rspec/commands/debian.rb
qa/rspec/commands/redhat.rb
rakelib/artifacts.rake

Bundle ARM64 JDKs for Linux artifacts: tar.gz/deb/rpm
This PR deprecates #12263 and #12216

Bundle JDK (AdoptOpenJDK 11) in Logstash artifacts (ARM64)

---

logstash-core/logstash-core.gemspec

fix https://github.com/elastic/logstash/issues/12299
pin jruby-openssl to 0.10.4

fix dependency issue, jruby-openssl, of integration test

---

docker/Makefile
docker/templates/Dockerfile.j2
qa/docker/shared_examples/image_metadata.rb
qa/docker/spec/spec_helper.rb
rakelib/artifacts.rake

This commit adds the ability for the docker build to build artifacts for multiple architectures.
By default, the target architecture is inferred from the architecture of the machine the build is being run from - running the build from an aarch64 machine will build an aarch64 docker image, while building from an x86_64 machine will build an x86_64 docker image.
This can be overridden by setting the environment variable DOCKER_ARCHITECTURE to either `x86_64` or `aarch64`.
This commit also updates the integration tests to verify the architecture from the machine the test is being run on.
This commit will enable logstash docker images to be built and published for multiple architectures.
This commit can be tested by running the `rake:docker` and `rake:docker_oss` tasks, and tested using the …

Docker Build: Add ability to detect/set build architecture

---

docker/Makefile
docker/templates/Dockerfile.j2
qa/docker/shared_examples/image_metadata.rb
qa/docker/spec/spec_helper.rb

Clean backport of #12302
This commit adds the ability for the docker build to build artifacts for multiple architectures.
By default, the target architecture is inferred from the architecture of the machine the build is being
run from - running the build from an aarch64 machine will build an aarch64 docker image, while building
from an x86_64 machine will build an x86_64 docker image.
This can be overridden by setting the environment variable DOCKER_ARCHITECTURE to either `x86_64` or
`aarch64`.
This commit also updates the integration tests to test against the architecture from the machine the test
is being run on, and includes the target architecture in the test description.

[7x] Docker Build: Add ability to detect/set build architecture

---

docs/static/releasenotes.asciidoc

Adds placeholder and "coming" tag so that we have a page to link to from 7.10.0 staging.
Note: We don't always put up a page in advance.  This time we'll need a live link for the updated download pages.

Doc: Add placeholder and coming tag for 7.10.0 release notes

---

build.gradle

The `shouldRunAfter` specified in the main script body was causing the runIntegrationTests
task to be evaluated even when it should not have been, causing unnecessary failures
when artifacts required only for integration tests are unavailable.
This can be removed, because the `shouldRunAfter` relationship for the `runIntegrationTests`
task is already defined in the task body.
~~[ ] My code follows the style guidelines of this project~~

Remove redundant shouldRunAfter

---

build.gradle

Clean backport of #12314 
The `shouldRunAfter` specified in the main script body was causing the runIntegrationTests
task to be evaluated even when it should not have been, causing unnecessary failures
when artifacts required only for integration tests are unavailable.
This can be removed, because the `shouldRunAfter` relationship for the `runIntegrationTests`
task is already defined in the task body.

[7x backport] Remove redundant shouldRunAfter

---

config/logstash.yml
config/pipelines.yml
docker/data/logstash/env2yaml/env2yaml.go
docs/static/dead-letter-queues.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/settings.rb
logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java
logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/main/java/org/logstash/common/io/RecordIOReader.java
logstash-core/src/main/java/org/logstash/common/io/RecordIOWriter.java
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
logstash-core/src/test/java/org/logstash/common/DeadLetterQueueFactoryTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
logstash-core/src/test/java/org/logstash/common/io/RecordIOReaderTest.java
qa/integration/build.gradle
qa/integration/specs/dlq_spec.rb
qa/integration/specs/spec_helper.rb

This commit changes the DLQ writer to write to a temporary file
which will be renamed on "completion", to avoid the possibility
of the DLQ reader reading an incomplete DLQ segment. The temp file
will be renamed and made available, either when the capacity of this
segment is reached, or if a configurable 'flush interval' has elapsed
since the last event reached the dead letter queue.
This commit fixes #8022, #10275, #10967
This commit replaces #11127

Write DLQ entries to temp file first

---

docker/data/logstash/env2yaml/env2yaml.go

`pipeline.ecs_compatibility` setting was missing a comma after its definition. This was breaking the docker build.
~~- [ ] My code follows the style guidelines of this project~~
Will run docker ci test and paste results before commit.

Fix env2yaml syntax error

---

config/logstash.yml
config/pipelines.yml
docker/data/logstash/env2yaml/env2yaml.go
docs/static/dead-letter-queues.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/settings.rb
logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java
logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/main/java/org/logstash/common/io/RecordIOReader.java
logstash-core/src/main/java/org/logstash/common/io/RecordIOWriter.java
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
logstash-core/src/test/java/org/logstash/common/DeadLetterQueueFactoryTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
logstash-core/src/test/java/org/logstash/common/io/RecordIOReaderTest.java
qa/integration/build.gradle
qa/integration/specs/dlq_spec.rb
qa/integration/specs/spec_helper.rb

Clean backport of #12304
This commit changes the DLQ writer to write to a temporary file
which will be renamed on "completion", to avoid the possibility
of the DLQ reader reading an incomplete DLQ segment. The temp file
will be renamed and made available, either when the capacity of this
segment is reached, or if a configurable 'flush interval' has elapsed
since the last event reached the dead letter queue.
This commit fixes #8022, #10275, #10967
This commit replaces #11127

[7.10 backport] Write DLQ entries to temp file first

---

config/logstash.yml
config/pipelines.yml
docker/data/logstash/env2yaml/env2yaml.go
docs/static/dead-letter-queues.asciidoc
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/settings.rb
logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java
logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
logstash-core/src/main/java/org/logstash/common/io/RecordIOReader.java
logstash-core/src/main/java/org/logstash/common/io/RecordIOWriter.java
logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
logstash-core/src/test/java/org/logstash/common/DeadLetterQueueFactoryTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
logstash-core/src/test/java/org/logstash/common/io/RecordIOReaderTest.java
qa/integration/build.gradle
qa/integration/specs/dlq_spec.rb
qa/integration/specs/spec_helper.rb

Clean backport of #12304
This commit changes the DLQ writer to write to a temporary file
which will be renamed on "completion", to avoid the possibility
of the DLQ reader reading an incomplete DLQ segment. The temp file
will be renamed and made available, either when the capacity of this
segment is reached, or if a configurable 'flush interval' has elapsed
since the last event reached the dead letter queue.
This commit fixes #8022, #10275, #10967
This commit replaces #11127

[7x backport] Write DLQ entries to temp file first

---

docker/data/logstash/env2yaml/env2yaml.go

Clean backport of #12320
`pipeline.ecs_compatibility` setting was missing a comma after its definition

[7.10 backport] Fix env2yaml syntax error

---

docker/data/logstash/env2yaml/env2yaml.go

Clean backport of #12320
`pipeline.ecs_compatibility` setting was missing a comma after its definition

[7x backport] env2yaml syntax error (#12320)

---

build.gradle

Clean backport of #12314
The `shouldRunAfter` specified in the main script body was causing the runIntegrationTests
task to be evaluated even when it should not have been, causing unnecessary failures
when artifacts required only for integration tests are unavailable.
This can be removed, because the `shouldRunAfter` relationship for the `runIntegrationTests`
task is already defined in the task body.

[710_backport] Remove redundant shouldRunAfter

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java

When deleting temporary files created by the DLQ writer to store data before moving to their
final location, Windows may leave these files in a "delete pending" state, where the files
are somewhat in a state of limbo, where they result of `Files.exist(filename)` is `false`,
but the result of `filename.toFile().exists()` is true. When files are in this state, a new
file with the same name cannot be created, which causes the DLQ test used to ensure that
closing and reopening the DLQ (in such events as a pipeline restart) to fail.
This commit moves the temporary file to an alternative location before deletion, ensuring that
the "pending delete" status does not interrupt with the DLQ startup
This commit fixes integration tests on the Windows platform, which were impacted by the delete pending …

Handle Windows delete pending files

---

docs/static/management/centralized-pipelines.asciidoc

clarify that queue max bytes only applies to persistent queues
Please tag as {doc}
This is to improve documentation only. In a support case, it came to light that the setting "queue max bytes" only affects persistent queues, and I cannt understand why this is not mentioned here.
The configuration site in Kibana is absolutely not intuitive when it puts the "Queue type picker list" next to the "Queue max bytes" picker while that queue max size has absolutely no effect if queue type memory is picked.

more precise declaration hint

---

docs/static/management/centralized-pipelines.asciidoc

Queue max bytes only applies to persistent queues
Forwardports: #12334 to master

Doc: Clarify use of queue max bytes setting

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/spec/logstash/java_pipeline_spec.rb

This addresses an incomplete fix in #12019 starting in 7.8.1 where upon catching a worker exception (to avoid crashing the whole logstash per #12306) the input plugin(s) are **not terminated prior** to closing the pipeline leading to the input plugin(s) continuing execution and failing with `IllegalStateException` &  `Tried to write to a closed queue` since closing the pipeline also correctly closes the queue.
This is a critical bug affecting users if logstash experiences a worker error.
To reproduce the problem prior to this PR:
- setup 2 pipelines, one that works and another that uses a  local output or filter that raises an exception from its filter or receive method
- run logstash; prior to this PR, `IllegalStateException` &  `Tried to write to a closed queue` errors will be produced, …

stop inputs upon a worker error before terminating the pipeline

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/spec/logstash/java_pipeline_spec.rb

[7.9 clean backport of #12307] stop inputs upon a worker error before terminating the pipeline

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/spec/logstash/java_pipeline_spec.rb

7.10 clean backport of #12307 stop inputs upon a worker error before terminating the pipeline

[7.10 clean backport of #12307] stop inputs upon a worker error before terminating the pipeline

---

logstash-core/lib/logstash/java_pipeline.rb
logstash-core/spec/logstash/java_pipeline_spec.rb

7.x clean backport of #12307  stop inputs upon a worker error before terminating the pipeline

[7.x clean backport of #12307] stop inputs upon a worker error before terminating the pipeline

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java

Clean backport of #12335
When deleting temporary files created by the DLQ writer to store data before moving to their
final location, Windows may leave these files in a "delete pending" state, where the files
are somewhat in a state of limbo, where they result of `Files.exist(filename)` is `false`,
but the result of `filename.toFile().exists()` is true. When files are in this state, a new
file with the same name cannot be created, which causes the DLQ test used to ensure that
closing and reopening the DLQ (in such events as a pipeline restart) to fail.
This commit moves the temporary file to an alternative location before deletion, ensuring that
the "pending delete" status does not interrupt with the DLQ startup

[7.10 backport] Handle Windows delete pending files

---

logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java

Clean backport of #12335
When deleting temporary files created by the DLQ writer to store data before moving to their
final location, Windows may leave these files in a "delete pending" state, where the files
are somewhat in a state of limbo, where they result of `Files.exist(filename)` is `false`,
but the result of `filename.toFile().exists()` is true. When files are in this state, a new
file with the same name cannot be created, which causes the DLQ test used to ensure that
closing and reopening the DLQ (in such events as a pipeline restart) to fail.
This commit moves the temporary file to an alternative location before deletion, ensuring that
the "pending delete" status does not interrupt with the DLQ startup

[7x backport] Handle Windows delete pending files

---

build.gradle
logstash-core/logstash-core.gemspec
qa/integration/integration_tests.gemspec

This PR 'properly' resolves LS failing on integration tests with a newer jruby-openssl release.
The failure LS run into was due to how gems where being install-ed for integration tests.
There's a detailed explanation on the [issue](https://github.com/elastic/logstash/issues/12299#issuecomment-711758291).
`./gradlew :logstash-integration-tests:integrationTests`
resolves GH-12299 (reverting GH-12300)

Build: properly isolate integration (test) env setup

---

docs/static/getting-started-with-logstash.asciidoc

Add a note to the documentation to clarify that Logstash needs to be run as a service when installing from a package repository or a deb or rpm.
Attempts to clarify that if you install Logstash through this means, the way to manage it is as a service, and that you should only run it manually for testing purposes.

[doc] Add note to Logstash repo install

---

qa/rspec/commands/redhat.rb

In QA test, when Logstash package with bundled JDK is installed on RedHat it has to check also the architecture
Fix failure like:
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=redhat/155/console

Fix for QA test when Logstash with bundled JDK is verified to be installed

---

docs/static/settings/configuration-management-settings.asciidoc

remind users to set `manage_logstash_pipelines` to their role
https://github.com/elastic/logstash/issues/12291
**PREVIEW:** https://logstash_12388.docs-preview.app.elstc.co/guide/en/logstash/master/configuring-centralized-pipelines.html#configuration-management-settings

document system indices api privilege

---

docs/static/security/logstash.asciidoc
docs/static/settings/configuration-management-settings.asciidoc

remind users to set `manage_logstash_pipelines` to their role
https://github.com/elastic/logstash/issues/12291
https://github.com/elastic/logstash/pull/12388
https://github.com/elastic/logstash/pull/12391

[7.10 backport] document system indices api privilege

---

docs/static/security/logstash.asciidoc
docs/static/settings/configuration-management-settings.asciidoc

remind users to set `manage_logstash_pipelines` to their role
https://github.com/elastic/logstash/issues/12291
https://github.com/elastic/logstash/pull/12388
https://github.com/elastic/logstash/pull/12391

[7x backport] document system indices api privilege

---

docs/index.asciidoc
docs/static/ls-to-cloud.asciidoc
docs/static/modules.asciidoc

Relocates Cloud info to Configuration section to make it more obvious and easier to find
Expands content for using cloud id and cloud auth outside of modules
Moves module-specific info into modules section
Backports #11884 to 7.x

[7x backport][Doc]Move logstash-to-cloud info for increased visibility

---

docs/index.asciidoc
docs/static/ls-to-cloud.asciidoc
docs/static/modules.asciidoc

Moves Cloud info to Configuration section to make it more obvious and easier to find
Expands content for using cloud id and cloud auth outside of modules
Moves module-specific info into modules section
Backports #11884 to 7.10

[Backport][Doc]Relocate logstash-to-cloud topic for increased visibility

---

docs/index.asciidoc
docs/static/troubleshoot/plugin-tracing.asciidoc
docs/static/troubleshoot/troubleshooting.asciidoc
docs/static/troubleshoot/ts-kafka.asciidoc
docs/static/troubleshoot/ts-logstash.asciidoc
docs/static/troubleshoot/ts-other-issues.asciidoc
docs/static/troubleshoot/ts-plugins-general.asciidoc
docs/static/troubleshoot/ts-plugins.asciidoc

Restructures troubleshooting docs in preparation for expanding content. 
Adds info for plugin tracing to help users track down plugins that might be causing problems.
**PREVIEW:** https://logstash_12270.docs-preview.app.elstc.co/guide/en/logstash/master/troubleshooting.html
Related: #12228

Doc:Restructure troubleshooting docs and add plugin tracing

---

docs/index.asciidoc
docs/static/troubleshoot/plugin-tracing.asciidoc
docs/static/troubleshoot/troubleshooting.asciidoc
docs/static/troubleshoot/ts-kafka.asciidoc
docs/static/troubleshoot/ts-logstash.asciidoc
docs/static/troubleshoot/ts-other-issues.asciidoc
docs/static/troubleshoot/ts-plugins-general.asciidoc
docs/static/troubleshoot/ts-plugins.asciidoc

Restructures troubleshooting docs in preparation for expanding content.
Adds info for plugin tracing to help users track down plugins that might be causing problems.
Backports: #12270
Fixes: #12228

[Backport]Doc:Restructure troubleshooting docs and add plugin tracing

---

logstash-core/lib/logstash/settings.rb

Currently, when referencing a setting that doesn't exist, we log the following error:
`Setting "xpack.monitoring.enable" hasn't been registered`
This can be confusing and lead user to think they need to do something else, as opposed to make sure they're using a "real" setting.
This PR changes this to log instead:
```
[2020-10-29T15:09:24,147][FATAL][logstash.runner] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.enable" doesn't exist>, :backtrace=>[..]}
```

Improve error message for non-existing settings

---

x-pack/lib/config_management/bootstrap_check.rb
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/qa/integration/management/multiple_pipelines_spec.rb
x-pack/spec/config_management/bootstrap_check_spec.rb
x-pack/spec/config_management/elasticsearch_source_spec.rb
x-pack/spec/config_management/fixtures/pipelines.json

allow `xpack.management.pipeline.id` to accept wildcard `*` setting to add/ update/ delete pipelines without restarting Logstash
add validation on `xpack.management.pipeline.id` to align with Kibana `pipeline ID must begin with a letter or underscore and contain only letters, underscores, dashes, and numbers`
add warning msg if wildcard is used with elasticsearch version < 7.10
** will need elasticsearch 7.10+, at this moment elastic cloud is 7.9, so unable to test in cloud**
- Logstash enable xpack 
- in logstash.yml `xpack.management.pipeline.id: ["*"]`
- start a local elasticsearch
- add a new pipeline to Elasticsearch
```
curl -X PUT -v "localhost:9200/_logstash/pipeline/heartbeat"  -H 'Content-Type: application/json' -d '{
"pipeline": "input { heartbeat { } } output { stdout {} }", …
```

add wildcard support in xpack pipeline id

---

x-pack/lib/config_management/bootstrap_check.rb
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/qa/integration/management/multiple_pipelines_spec.rb
x-pack/spec/config_management/bootstrap_check_spec.rb
x-pack/spec/config_management/elasticsearch_source_spec.rb
x-pack/spec/config_management/fixtures/pipelines.json

add wildcard support in xpack pipeline id
do the pattern matching with glob
add warning msg to wildcard with legacy api
check invalid pipeline in bootstrap
test cases for invalid checking
origin PR: https://github.com/elastic/logstash/pull/12370

[backport 7x] add wildcard support in xpack pipeline id (#12370)

---

config/pipelines.yml
logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb
logstash-core/lib/logstash/plugins/builtin/pipeline/output.rb
logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb

This commit adds context to the pipeline to pipeline input and output
plugins by adding a string containing the `address` field to the input
plugin, and an array containing the `send_to` field to the output plugin.
This helps gain a picture of how pipeline to pipeline enabled configurations
are communicating with each other, without having to refer back to the pipeline
definition
This commit adds context to the pipeline to pipeline input and output
plugins by adding a string containing the `address` field to the input
plugin, and an array containing the `send_to` field to the output plugin.
This helps gain a picture of how pipeline to pipeline enabled configurations
are communicating with each other, without having to refer back to the pipeline
definition
~- [ ] I have commented my code, …

Add addresses to p2pipeline input and output plugin metrics

---

logstash-core/lib/logstash/pipeline_action/delete.rb
logstash-core/lib/logstash/pipelines_registry.rb
logstash-core/lib/logstash/state_resolver.rb
logstash-core/spec/logstash/pipelines_registry_spec.rb
logstash-core/spec/logstash/state_resolver_spec.rb

Users cannot delete a pipeline and recreate it with the same configuration string in Kibana. Logstash store all pipelines in pipeline_registry and never remove them. Logstash takes actions by comparing the source and registry. It causes difficulties to distinguish if a pipeline is finished or be terminated due to removal in the source(elasticsearch). 
The flow of the issue
1. Users deleted a pipeline in Kibana
2. Logstash stops the pipeline instead of deleting it
3. Users recreate the pipeline with the same setting in Kibana
4. Logstash compares the hash value of the new pipeline with the old pipeline that stays in the registry
5. The hash value is the same. Logstash keeps the old pipeline in terminated status. Users cannot see the pipeline running
This PR deletes the pipeline in the …

delete pipeline in registry

---

logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java
logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/qa/integration/management/multiple_pipelines_spec.rb
x-pack/qa/integration/support/helpers.rb

To fix the issue described in https://github.com/elastic/logstash/issues/12387 ,  this PR modifies the hash function of the pipeline to include metadata and config string.
Users should be able to recreate the pipeline given that the metadata value has changed.
A follow-up Kibana task should update the version number for every change

fix delete and recreate pipeline with same pipeline ID and config string

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/EventCondition.java

This commit adds the toString of the expression(s) that caused the UnexpectedTypeException to the
exception message, giving more context as to where the issue stems from
Subtle syntax errors in configuration can lead to difficult to track down errors, with cryptic error messages not offering much help, eg
```
if [source] =~ "middle.log" or "left.log" or "right.log" {
```
Would lead to the following error:
```
[2020-11-09T11:31:27,711][ERROR][Ruby-0-Thread-172: :1][logstash.javapipeline    ][main] Worker loop initialization error {:pipeline_id=>"main", :error=>"Unexpected input types class org.logstash.config.ir.expression.ValueExpression class org.logstash.config.ir.expression.ValueExpression"
```
After this change, the following error is produced:
``` …
```

Add more information to UnexpectedTypeException

---

logstash-core/src/main/java/org/logstash/config/ir/compiler/EventCondition.java

Clean backport of #12426
Where available, this commit adds information from getSourceWithMetadata to the
error message of UnexpectedTypeException, dropping down to `toString`
if not, giving more context to find where the issue is caused in the configuration.

[7x backport] Add more information to UnexpectedTypeException

---

tools/ingest-converter/src/main/resources/ingest-pipeline.js
tools/ingest-converter/src/main/resources/ingest-set.js

The `ingest-converter ' tool, used to translate Elasticsearch ingest pipelines definitions to Logstash pipeline configuration, should print out some warning when it's not able to translate some attributes or doesn't recognize the processor.
This PR simply print on console if it find a `set` processor with `if` code or if it isn't able to translate a specific processor because not part of the recognized ones.
Fixes #12384

Added console prints in ingest-converter for not recognized processor definitions.

---

tools/ingest-converter/src/main/resources/ingest-pipeline.js
tools/ingest-converter/src/main/resources/ingest-set.js

Backport to `7.x` of #12428 
The `ingest-converter ' tool, used to translate Elasticsearch ingest pipelines definitions to Logstash pipeline configuration, should print out some warning when it's not able to translate some attributes or doesn't recognize the processor.
This PR simply print on console if it find a set processor with if code or if it isn't able to translate a specific processor because not part of the recognized ones.

[7.x backport] Added console prints in ingest-converter for not recognized processor definitions

---

logstash-core/lib/logstash/pipeline_action/delete.rb
logstash-core/lib/logstash/pipelines_registry.rb
logstash-core/lib/logstash/state_resolver.rb
logstash-core/spec/logstash/pipelines_registry_spec.rb
logstash-core/spec/logstash/state_resolver_spec.rb
logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java
logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java
x-pack/lib/config_management/elasticsearch_source.rb
x-pack/qa/integration/management/multiple_pipelines_spec.rb
x-pack/qa/integration/support/helpers.rb

backport of https://github.com/elastic/logstash/pull/12414 and https://github.com/elastic/logstash/pull/12389
meta issue https://github.com/elastic/logstash/issues/12387

[backport 7.10] fix delete and recreate pipeline with same pipeline ID and config string

---

logstash-core/lib/logstash/util/cloud_setting_auth.rb
logstash-core/spec/logstash/settings/modules_spec.rb
logstash-core/src/main/java/co/elastic/logstash/api/Password.java
logstash-core/src/main/java/org/logstash/util/CloudSettingAuth.java
logstash-core/src/test/java/org/logstash/util/CloudSettingAuthTest.java

**What**
This PR moves the class CloudSettingsAuth from Ruby to Java code
**Why**
Moving CloudSettingsAuth to Java let then move all the Setting hierarchy to Java
**How**
This PR leverages the ability of JRuby to use Java classes in JRuby code

Move CloudSettingsAuth to java

---

docker/Makefile
docker/templates/Dockerfile.j2
qa/docker/shared_examples/image_metadata.rb
rakelib/artifacts.rake

This commit fixes two issues with the docker metadata:
Removes non-OCI compliant freeform metadata labels
Uses a consistent build date for all the docker images and dockerfiles
Additionally, this commit adds a `build_docker_ubi8` rake task to enable
`ci/docker_acceptance_tests.sh` to run with no options to build all
docker images for the architecture.
This PR passed docker acceptance tests [here](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-docker-acceptance/55/)
Originally raised in this [comment](https://github.com/elastic/dockerfiles/pull/56) in PR for the committed logstash `7.10.0` dockerfile.

Fix docker image metadata

---

docker/templates/Dockerfile.j2
qa/docker/shared_examples/image_metadata.rb

Removing the freeform description labels left the container metadata without a description label. This commit adds a description under the "org.opencontainers.image.description" label.

Add additional description label

---

docker/Makefile
docker/templates/Dockerfile.j2
qa/docker/shared_examples/image_metadata.rb
rakelib/artifacts.rake

Clean backport of #12447
This commit fixes two issues with the docker metadata:
Removes non-OCI compliant freeform metadata labels
Uses a consistent build date for all the docker images and dockerfiles
Additionally, this commit adds a `build_docker_ubi8` rake task to enable
`ci/docker_acceptance_tests.sh` to run with no options to build all
docker images for the architecture.

[710_backport] Fix docker image metadata

---

docker/Makefile
docker/templates/Dockerfile.j2
qa/docker/shared_examples/image_metadata.rb
rakelib/artifacts.rake

Clean backport of #12447
This commit fixes two issues with the docker metadata:
Removes non-OCI compliant freeform metadata labels
Uses a consistent build date for all the docker images and dockerfiles
Additionally, this commit adds a `build_docker_ubi8` rake task to enable
`ci/docker_acceptance_tests.sh` to run with no options to build all
docker images for the architecture.

[7x backport] Fix docker image metadata

---

logstash-core/lib/logstash/util/cloud_setting_auth.rb
logstash-core/spec/logstash/settings/modules_spec.rb
logstash-core/src/main/java/co/elastic/logstash/api/Password.java
logstash-core/src/main/java/org/logstash/util/CloudSettingAuth.java
logstash-core/src/test/java/org/logstash/util/CloudSettingAuthTest.java

clean backport of #12443 to `7.x`
Move code of CloudSettingAuth to Java
- moved the class's code
- moved spec tests to JUnit tests
(cherry picked from commit b0920eb6fff9bee21a9c2fd54c452adfe229ad71)

Move code of CloudSettingAuth to Java

---

logstash-core/lib/logstash/util/password.rb
logstash-core/src/main/java/co/elastic/logstash/api/Password.java

There is two `Password` classes that almost does the same thing. One in Ruby https://github.com/elastic/logstash/blob/934e44da13db6b96b7a458f52cb2b9429d2a7dfd/logstash-core/lib/logstash/util/password.rb#L20-L37 and one in Java (co.elastic.logstash.api.Password).
This commit drop the the Ruby implementation to import the Java version in the LogStash::Util so that existing Ruby code haven't to be changed, works as it is.

Drop Password Ruby class to use only the Java version

---

rubyUtils.gradle

Per https://github.com/jruby/jruby/issues/6471 the JRuby bundled gem `did_you_mean` contains files with non commercial licenses.

remove evaluation dir from JRuby bundled did_you_mean gem

---

docs/static/breaking-changes.asciidoc
logstash-core/lib/logstash/agent.rb
logstash-core/lib/logstash/environment.rb
logstash-core/lib/logstash/runner.rb
logstash-core/locales/en.yml

Fixed: #12355
remove field-reference-parser for version 8

clean up field-reference-parser

---

logstash-core/spec/logstash/settings/modules_spec.rb
logstash-core/src/main/java/org/logstash/util/CloudSettingAuth.java
logstash-core/src/test/java/org/logstash/util/CloudSettingAuthTest.java

After the move of CloudSettingsId in #12443 theexception raised is Java's IllegalArgumentException instead of Ruby's ArgumentError. This break the code in plugins (like elasticsearch input/filter/output) that catch for the Error.

Fix an API break in CloudSettingsAuth, a Ruby's ArgumentError should be raised

---

logstash-core/spec/logstash/settings/modules_spec.rb
logstash-core/spec/logstash/util/cloud_setting_id_spec.rb
logstash-core/src/main/java/org/logstash/util/CloudSettingId.java
logstash-core/src/test/java/org/logstash/util/CloudSettingIdTest.java

After the move of CloudSettingsId in #12436 theexception raised is Java's `IllegalArgumentException` instead of  Ruby's `ArgumentError`. This break the code in plugins (like elasticsearch input/filter/output) that catch for the Error.

Fix an API break in CloudSettingsId, a Ruby's ArgumentError should be raised

---

logstash-core/spec/logstash/settings/modules_spec.rb
logstash-core/spec/logstash/util/cloud_setting_id_spec.rb
logstash-core/src/main/java/org/logstash/util/CloudSettingId.java
logstash-core/src/test/java/org/logstash/util/CloudSettingIdTest.java

Backport of #12462 to `7.x`
Reestablished Ruby specs to test moved code.
(cherry picked from commit 09f995776e930e823f1e3e37eaf1029ba1e72139)

Fix an API break, a Ruby's ArgumentError should be raised.

---

docs/static/logging.asciidoc

Improves the description of how to grab the loggers names, for example for plugins, or other parts, like classes/libraries used by plugins. For example enabling logging on dissector plugin, which also uses some Java classes like `org.logstash.dissect.Dissector`, the user has to enable the logging also for that, to have a full picture of what's happening during dissect processing.
Doesn't impact the user functionality, just documentation
NA
NA
NA

[Doc] expand the description of how to obtain the logger's names form Java and Ruby class names
